### DISCUSSION TITLE
DNS resolution error

### DISCUSSION THREAD

**Discussion by usma0118** [haugene/docker-transmission-openvpn#1991] [Q&A] [answered]
Environment: Kubernetes on Ubuntu
docker tag: :latest

Container continue to cycle through this error.

## Error log

```
Tue Oct  5 07:05:48 2021 Could not determine IPv4/IPv6 protocol
Tue Oct  5 07:05:48 2021 SIGUSR1[soft,init_instance] received, process restarting
Tue Oct  5 07:10:48 2021 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Tue Oct  5 07:10:58 2021 RESOLVE: Cannot resolve host address: fr.vpnunlimitedapp.com:1194 (Temporary failure in name resolution)
Tue Oct  5 07:11:08 2021 RESOLVE: Cannot resolve host address: fr.vpnunlimitedapp.com:1194 (Temporary failure in name resolution)
Tue Oct  5 07:11:08 2021 Could not determine IPv4/IPv6 protocol
Tue Oct  5 07:11:08 2021 SIGUSR1[soft,init_instance] received, process restarting
Tue Oct  5 07:12:47 2021 SIGTERM[hard,init_instance] received, process exiting
```

## Config

```yaml
      containers:
        - env:
            - name: OPENVPN_PROVIDER
              value: "custom"
            - name: OPENVPN_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: vpnunlimited
            - name: OPENVPN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: vpnunlimited
            - name: TRANSMISSION_RPC_USERNAME
              value: {redacted}
            - name: TRANSMISSION_RPC_PASSWORD
              value: {redacted}
            - name: TRANSMISSION_RPC_AUTHENTICATION_REQUIRED
              value: "true"
            - name: TRANSMISSION_DOWNLOAD_DIR
              value: /downloads/transmission
            - name: PUID
              value: "1001"
            - name: PGID
              value: "1001"
            - name: TRANSMISSION_UMASK
              value: "18"
            - name: TRANSMISSION_RATIO_LIMIT
              value: "1"
            - name: TRANSMISSION_BLOCKLIST_ENABLED
              value: "true"
            - name: TRANSMISSION_BLOCKLIST_URL
              value: https://github.com/Naunter/BT_BlockLists/raw/master/bt_blocklists.gz
            - name: TRANSMISSION_ENCRYPTION
              value: "2"
            - name: TRANSMISSION_RATIO_LIMIT_ENABLED
              value: "true"
            - name: CREATE_TUN_DEVICE
              value: "true"
            - name: WEBPROXY_ENABLED
              value: "true"
            - name: WEBPROXY_PORT
              value: "8118"
            - name: TRANSMISSION_RPC_WHITELIST
              value: "10.1.183.*,127.0.0.1"
            - name: TRANSMISSION_RPC_WHITELIST_ENABLED
              value: "false"
            - name: LOG_TO_STDOUT
              value: "true"
            - name: OPENVPN_OPTS
              value: "--inactive 3600 --ping 10 --ping-exit 60"
            - name: LOCAL_NETWORK
              value: "10.1.183.0/24"
          image: haugene/transmission-openvpn:dev
          imagePullPolicy: Always
          name: transmission
          ports:
            - containerPort: 9091
              name: http
              protocol: TCP
            - containerPort: 8118
              name: webproxy
              protocol: TCP
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            capabilities:
              add:
                - NET_ADMIN
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /data
              name: transmission
              subPath: configs
            - mountPath: /downloads/transmission
              name: transmission
              subPath: downloads
            - mountPath: /etc/openvpn/custom/default.ovpn
              name: config
              subPath: fr.vpnunlimited.ovpn
          readinessProbe:
            tcpSocket:
              port: webproxy
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: webproxy
            initialDelaySeconds: 15
            periodSeconds: 20        
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - name: transmission
          persistentVolumeClaim:
            claimName: transmissionv2
        - configMap:
            name: openvpn-common-config
          name: config
```
