### DISCUSSION TITLE
Add a SOCKS5 proxy server?

### DISCUSSION THREAD

**Discussion by jpbaril** [haugene/docker-transmission-openvpn#2017] [Ideas]
Hi,

Everything is working well for the base setup but I have a particular use case I cannot make to work.

I would like to make the traffic of other torrent clients in my home go through the ~~Privoxy~~ proxy.

For example, I have a qBittorent client that has the option to route its connection through a proxy.

~~The client seem to get peer list but download never happen.~~
~~Also tried with a Transmission client. Same thing happen.~~

~~Is is that bittorrent traffic cannot work on HTTP Privoxy?~~
[**Edit**: I now understand that Privoxy is only a HTTP proxy and that torrent traffic cannot work with HTTP proxies, only with SOCKS5 proxies]

Could it be evaluated to add a SOCKS5 proxy server?

**Comment by pkishino** [comment]
@jay-to-the-dee  any chance you can answer this?

**Reply by jay-to-the-dee** [reply]
I think it would have to be a seperate service, am pretty sure Privoxy is HTTP only explictly by design.

**Reply by jpbaril** [reply]
I used @pkishino suggested container. https://hub.docker.com/r/wernight/dante

 I wasn't aware of the possibility of using another's container networking. That did the trick.

**Comment by jpbaril** [comment]
I think I understand that Privoxy is only a HTTP proxy and that torrent traffic cannot work with HTTP proxies, only with SOCKS5 proxies.
Any recommendation on which socks5 proxy to integrate and how?
Thanks

**Reply by jpbaril** [reply]
Changed discussion title.

I also did some research and it appears that [Dante](http://www.inet.no/dante/index.html) SOCKS proxy server could be a good candidate as other similar VPN+Bittorrent container stacks also use it.

**Reply by pkishino** [reply]
my suggestion is to just containerise the other torrent clients and make them use this containers link, that way all traffic will go through the vpn

**Reply by jpbaril** [reply]
It's not a possibility as they are other computers around the house.

**Reply by pkishino** [reply]
in that case they are better of running their own vpn tunnel per client? just seems much easier to manage and setup then to add an additional package to this container imo

**Reply by jpbaril** [reply]
I have limit of VPN connections with my provider.
Also, with SOCKS5 proxy I can route only the traffic of particular apps (i.e. Bittorrent clients) and not the whole computer traffic.

**Reply by pkishino** [reply]
had a quick google,
setup the container
https://hub.docker.com/r/wernight/dante
and make it use this containers network to tunnel

**Reply by miaLDN** [reply]
My VPN provider has a generous limit on VPN connections; and I have numerous dedicated VPN containers using a different image to this (they are all Wireguard and have a SOCKS5 proxy).

But I only use **one** VPN link per torrent client; as a client can be pulling+pushing 2Gbps sustained.  For other clients and interactive use; a complex PAC `wpad.dat` routes traffic to various endpoints for various reasons (many websites are blocked where I am currently).

## What I raeally want is a @haugene bundle with:
`Wireguard+qBtorrent+SOCKS5+Privoxy`

`Transmisison` is suboptimal, and the devs refuse to handle pad files.  I've even provided detailed technical notes and an easy solution with provided code...
I've switched to `qBittorent` entirely nå.

**Comment by JtMotoX** [comment]
I was able to get it working by adding this service to my docker-compose.yml

```yaml
  socks5-proxy:
    image: wernight/dante
    restart: always
    network_mode: service:transmission-openvpn
    depends_on:
      - transmission-openvpn
    command:
      - /bin/sh
      - -c
      - |
        echo "Waiting for VPN to connect . . ."
        while ! ip link show tun0 >/dev/null 2>&1 || ! ip link show tun0 | grep -q "UP"; do sleep 1; done
        echo "VPN connected. Starting proxy service . . ."
        sed -i 's/^\(external:\).*/\1 tun0/' /etc/sockd.conf
        sockd
```
