### DISCUSSION TITLE
Troubleshooting regular container crashes

### DISCUSSION THREAD

**Discussion by Qhilm** [haugene/docker-transmission-openvpn#2044] [Q&A]
Hello, the container regularly crashes, I am trying to understand why. I have deleted the entire transmission folder, all torrents, started fresh, but it's still crashing.

First thing I need is to have logs of what is happening, which is where I have my first issue. In Docker, I see "no logs available", that's it. That probably hints at a first issue. Any idea what could be causing this?

Synology NAS running DSM 7, using transmission-openvpn:latest, which is regularly updated via ouroboros.

this is the docker compose:

```yaml
version: '3.7'
services:
    transmission-openvpn:
        container_name: 'haugene'
        cap_add:
            - NET_ADMIN
        devices:
            - '/dev/net/tun'
        volumes:
            - '/volume3/xxxxx/:/data'
            - '/volume3/docker/haugene/resolv.conf:/etc/resolv.conf:ro'
            - '/volume3/docker/haugene/:/config'
        environment:
            - OPENVPN_PROVIDER=Mullvad
            - OPENVPN_CONFIG=dk_all
            - OPENVPN_USERNAME=XXXXXXXXX
            - OPENVPN_PASSWORD=m
            - LOCAL_NETWORK=192.168.0.0/24
            - TRANSMISSION_RATIO_LIMIT=2
            - TRANSMISSION_RATIO_LIMIT_ENABLED=true
            - TRANSMISSION_SPEED_LIMIT_UP_ENABLED=true
            - TRANSMISSION_SPEED_LIMIT_UP=200
            - TRANSMISSION_BLOCKLIST_URL=http://list.iblocklist.com/?list=srzondksmjuwsvmgdbhi&fileformat=p2p&archiveformat=gz&username=xxxxxx&pin=xxxxxx
        logging:
            driver: json-file
            options:
                max-size: 10m
        sysctls:
            - net.ipv6.conf.all.disable_ipv6=0
        ports:
            - '9091:9091'
        image: haugene/transmission-openvpn:latest
        
 ```
