### DISCUSSION TITLE
Flaky Connection with Transmission?

### DISCUSSION THREAD

**Discussion by fabge** [haugene/docker-transmission-openvpn#2051] [Q&A] [answered]
Hello everyone,

I am running the latest docker image on an M1 Mac Mini.
Transmission seems to be working, albeit downloading with very slow speeds and a very flaky connection. Even when I download a recently published torrent with hundreds of seeders, the connection doesn't exceed ~200kB/s and fluctuates constantly between zero and the max of around 200kB/s. I have explicitly added the `dns` label to point to my DNS server, although with limited success - it seemed to have improved it somewhat but still nowhere near 100%.
What I am additionally suspicious about is, when I set up a healthcheck, the container won't be up more than a couple of minutes, because it fails.
When running `ping google.com` inside the container, it does succeed, although the frequency of the ping seems rather slow and it shows an alarming percentage of package loss of around 8%.
```bash
--- google.com ping statistics ---
181 packets transmitted, 165 received, 8.83978% packet loss, time 198650ms
rtt min/avg/max/mdev = 423.827/7148.980/19886.639/4660.571 ms, pipe 20
```

Here are my logs on container startup:
[log.txt](https://github.com/haugene/docker-transmission-openvpn/files/7467880/log.txt)

Here is a screenshot. You can see the fluctuating connection on the top left:
![transmission](https://user-images.githubusercontent.com/21140791/140069926-58c1e27f-5341-4b4c-ab5e-b7a71d20dec9.jpg)

Here is my docker compose setup:
```yaml
  torrent:
    image: haugene/transmission-openvpn:latest
    container_name: torrent
    cap_add:
      - NET_ADMIN
    volumes:
      - ${CONFIG}/transmission-openvpn/:/data/transmission-home/
      - ${ROOT}/downloads/incomplete:/data/incomplete
      - ${ROOT}/downloads/completed:/data/completed
      - ${ROOT}/downloads/torrent-blackhole:/data/watch
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - OPENVPN_PROVIDER=NORDVPN
      - OPENVPN_USERNAME=${NORDVPN_USERNAME}
      - OPENVPN_PASSWORD=${NORDVPN_PASSWORD}
      - LOCAL_NETWORK=192.168.1.0/24
      - NORDVPN_COUNTRY=AL
      - NORDVPN_CATEGORY=legacy_p2p
      - NORDVPN_PROTOCOL=tcp
      # - HEALTH_CHECK_HOST='api.nordvpn.com'
      # - SELFHEAL=true
      - TRANSMISSION_WEB_UI=flood-for-transmission
      - TRANSMISSION_DOWNLOAD_QUEUE_SIZE=20
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - 9091:9091
    dns:
      - 192.168.1.2
```

Any help is appreciated, I am really without answers.

Short update:
After some minutes the container terminates with following log:

```
Wed Nov  3 13:18:14 2021 /sbin/ip route add 80.246.28.43/32 via 172.18.0.1
Wed Nov  3 13:18:14 2021 /sbin/ip route add 0.0.0.0/1 via 10.7.3.1
Wed Nov  3 13:18:14 2021 /sbin/ip route add 128.0.0.0/1 via 10.7.3.1
Wed Nov  3 13:18:14 2021 Initialization Sequence Completed
Wed Nov  3 14:19:10 2021 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Wed Nov  3 14:19:10 2021 TLS Error: TLS handshake failed
Wed Nov  3 14:19:10 2021 TLS: move_session: dest=TM_LAME_DUCK src=TM_ACTIVE reinit_src=1
Wed Nov  3 14:19:10 2021 Fatal TLS error (check_tls_errors_co), restarting
Wed Nov  3 14:19:10 2021 /etc/openvpn/tunnelDown.sh tun0 1500 1587 10.7.3.4 255.255.255.0 init
resolv.conf was restored
Sending kill signal to transmission-daemon
Waiting 5s for transmission-daemon to die
Successfuly closed transmission-daemon
Wed Nov  3 14:19:15 2021 /sbin/ip route del 80.246.28.43/32
Wed Nov  3 14:19:15 2021 /sbin/ip route del 0.0.0.0/1
Wed Nov  3 14:19:15 2021 /sbin/ip route del 128.0.0.0/1
Wed Nov  3 14:19:15 2021 Closing TUN/TAP interface
Wed Nov  3 14:19:15 2021 /sbin/ip addr del dev tun0 10.7.3.4/24
Wed Nov  3 14:19:15 2021 SIGTERM[soft,tls-error] received, process exiting
```

Here are additional informations:

```bash
root@9c632c1f83d5:/data/transmission-home# cat /etc/resolv.conf
# Generated by openvpn for interface tun0
nameserver 103.86.96.100
nameserver 103.86.99.100
```

```bash
root@2204fc2e43fb:/etc/openvpn/nordvpn# ls
al25.nordvpn.com.ovpn  default.ovpn
configure-openvpn.sh   updateConfigs.sh
```
