### DISCUSSION TITLE
Downloading Archive Config File When Custom Provider Declared - WHY?

### DISCUSSION THREAD

**Discussion by gist901** [haugene/docker-transmission-openvpn#2058] [Ideas]
Hi all,

I noticed that when I spin up the docker container, even though I have declared in my docker compose file to use a custom OVPN, it still goes ahead downloads the archive config, unzips, checks it for the name declared, then finally utilizes the custom OVPN. This seems like alot of unnecessary steps and a waste of compute power / time. It would be nice if the script would skip the download / unzip process if custom provider is declared.

My logs:

```
Using OpenVPN provider: CUSTOM
Running with VPN_CONFIG_SOURCE auto
No bundled config script found for CUSTOM. Defaulting to external config
Downloading configs from https://github.com/haugene/vpn-configs-contrib/archive/main.zip into /tmp/tmp.BTezFTYqlD
Extracting configs to /tmp/tmp.4Ut8Jq9a7e
ERROR: Could not find any configs for provider CUSTOM in downloaded configs
Cleanup: deleting /tmp/tmp.BTezFTYqlD and /tmp/tmp.4Ut8Jq9a7e
No VPN configuration provided. Using default.
Modifying /etc/openvpn/custom/default.ovpn for best behaviour in this container
Modification: Point auth-user-pass option to the username/password file
```

And here is a sample of my docker compose:

```
  vpn:
    container_name: vpn
    image: haugene/transmission-openvpn:latest
    ports:
      - 8112:8112
      - 7878:7878
      - 9117:9117
    cap_add:
      - NET_ADMIN
    devices:
       - /dev/net/tun
    volumes:
      - /mnt/travel/dockerConfig/transmission:/data
      - /etc/localtime:/etc/localtime:ro
      - /mnt/travel/dockerConfig/openvpn/:/etc/openvpn/custom/
    environment:
      - PUID=1001
      - PGID=1001
      - OPENVPN_PROVIDER=custom
      - OPENVPN_USERNAME=
      - OPENVPN_PASSWORD=
      - WEBPROXY_ENABLED=false
      - LOCAL_NETWORK=192.168.48.0/24
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      vpn_net:
        ipv4_address: 10.0.0.2
```
