### DISCUSSION TITLE
unset TRANSMISSION_DOWNLOAD_DIR and stop it from chowning my files

### DISCUSSION THREAD

**Discussion by MastaG** [haugene/docker-transmission-openvpn#2159] [Q&A] [answered]
Hi, I've got a setup with sickchill.
I'm running Transmission with a custom PUID and PGID which is already correct for my needs.
I don't want the container to override my download and incomplete dir at each startup.
Is it possible to unset TRANSMISSION_DOWNLOAD_DIR and make it not chown anything?

**Comment by pkishino** [comment]
? Sounds like the best thing to do would be for you to set the env variables properly.
What is your current docker config for the container?

**Comment by MastaG** [comment, marked as answer]
My stack looks like:
```
version: '3.3'
services:
    transmission-openvpn:
        cap_add:
            - NET_ADMIN
        volumes:
            - '/volume1/shared/transmission:/data'
            - '/volume1/shared:/shared'
        environment:
            - OPENVPN_PROVIDER=NORDVPN
            - NORDVPN_COUNTRY=NL
            - NORDVPN_PROTOCOL=udp
            - OPENVPN_USERNAME=XXX
            - OPENVPN_PASSWORD=XXX
            - LOCAL_NETWORK=192.168.0.0/24
            - TZ=Europe/Amsterdam
            - PUID=177169
            - PGID=207066
            - TRANSMISSION_DOWNLOAD_DIR=/shared/videos
            - TRANSMISSION_INCOMPLETE_DIR=/shared/incomplete
            - GLOBAL_APPLY_PERMISSIONS=false

        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '9091:9091'
        image: haugene/transmission-openvpn:latest
```
I just set ```GLOBAL_APPLY_PERMISSIONS``` to ```false``` so that it doesn't try to chmod things (I think it should be the default imo).
It works now :)
