### DISCUSSION TITLE
Routing Error

### DISCUSSION THREAD

**Discussion by unintended-consequences** [haugene/docker-transmission-openvpn#2162] [Q&A]
I am not good at container networking, but my docker logs shows Openvpn is spitting out:

`Fri Jan 21 16:31:43 2022 /sbin/ip route add 109.123.122.214/32 via 172.23.0.1`
`Fri Jan 21 16:31:43 2022 /sbin/ip route del 0.0.0.0/0`
`Fri Jan 21 16:31:43 2022 /sbin/ip route add 0.0.0.0/0 via 10.10.8.9`
`Fri Jan 21 16:31:43 2022 /sbin/ip route add 10.10.8.1/32 via 10.10.8.9`
`RTNETLINK answers: File exists`
`Fri Jan 21 16:31:43 2022 ERROR: Linux route add command failed: external program exited with error status: 2`

Is it potentially conflicting with my 10.162.0.0/16 home network?

I have recreated this error in a brand new clean docker-compose container:

```
version: "3.7"

services:

  transvpn:
    image: "haugene/transmission-openvpn"
    container_name: "transvpn"
    cap_add:
      - NET_ADMIN
    environment:
      - OPENVPN_PROVIDER=SLICKVPN
      - OPENVPN_CONFIG=United-Kingdom-London
      - OPENVPN_USERNAME=xxx@slickvpncore.com
      - OPENVPN_PASSWORD=xxx
      - LOCAL_NETWORK=10.162.110.0/24
    logging:
      driver: json-file
      options:
        max-size: 10m
    volumes:
      - $DOCKDIR/08-transvpn/data:/data
    ports:
      - 39091:9091
    labels:
      - flame.type=app
      - flame.name=Transmission
      - flame.url=http://docker:39091
      - flame.icon=cloud-download
    restart: unless-stopped
```
