### DISCUSSION TITLE
Synology NAS & ENABLE_UFW: Does it work?

### DISCUSSION THREAD

**Discussion by mil1i** [haugene/docker-transmission-openvpn#2224] [Q&A]
### My configuration works without issue so long as I keep `ENABLE_UFW=false`.

Hello,

Just came across this as my server died, and I'm trying to get things running on my NAS til I get it back up / replaced. Love this all-in-one piece for transmission + openvpn! Much cleaner than what I was using before, thank you! :)

One part I am stuck on at the moment is getting this working with the `ENABLE_UFW=true`. I'm wondering if anyone has been able to get this work. 

> Synology DSM 7.0.1-42218 (DS918+)
> Image: haugene/docker-transmission-openvpn@sha256:12d8b12276902ab7dbe1a35d8c85d3fea8922ce7128f376dfbf3b350b99c0069

I only see one error in the logs during start, and it appears to be expected as the script is clearing out `/etc/ufw/user.rules`:
```log
transmission            | enabling firewall
transmission            | ERROR: Could not load logging rules
```

```shell
    echo "Disable and blank firewall"
    ufw disable
    echo "" > /etc/ufw/user.rules
```

Here's my docker-compose.yaml configuration.
```yaml
version: '3.3'
services:
  transmission:
    image: haugene/transmission-openvpn:latest
    container_name: transmission
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    volumes:
      - /volume1/media/downloads:/data:rw
    environment:
      - PUID=${MY_PUID}
      - PGID=${MY_GUID}
      - OPENVPN_PROVIDER=PROTONVPN
      - OPENVPN_CONFIG=us-ca-38.protonvpn.com.udp
      - OPENVPN_USERNAME=${MY_OPENVPN_USER}
      - OPENVPN_PASSWORD=${MY_OPENVPN_PW}
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=192.168.0.0/24,172.17.0.0/16
      - CREATE_TUN_DEVICE=true
      - TZ=UTC
      - LOG_TO_STDOUT=true
      - TRANSMISSION_WEB_UI=flood-for-transmission
      - TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=false
      - DROP_DEFAULT_ROUTE=true
      - ENABLE_UFW=true
      - UFW_EXTRA_PORTS=443,80
      - UFW_DISABLE_IPTABLES_REJECT=true
      - HEALTH_CHECK_HOST=google.com
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    ports:
      - 9091:9091
    dns:
      - 9.9.9.9
      - 1.1.1.1
    networks:
      torrents:
        aliases:
          - transmission
        ipv4_address: 10.50.1.28

networks:
  torrents:
    name: torrents
    driver: bridge
    ipam:
     config:
       - subnet: 10.50.1.0/27
```

From the NAS CLI: 
```
ovs_eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1
    inet 192.168.0.10/24 brd 192.168.0.255 scope global ovs_eth1
docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
docker-b4ec528e: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    inet 10.50.1.1/27 brd 10.50.1.31 scope global docker-b4ec528e
```

I've tested a number of things. I've tried widening the `LOCAL_NETWORK` from `/24` to `/16`. I added in the default docker bridge network. I've also tried setting `UFW_ALLOW_GW_NET=true`, as well as adding additional PORTS to allow `UFW_EXTRA_PORTS=80,443`. I've also tried `net.ipv6.conf.all.disable_ipv6=0`. I also tried playing with the `WEBPROXY_` to no avail. Tried without dropping default route.

My setup is also utilizing the NAS's built-in reverse proxy. I cannot access the UI whether I hit `IP:PORT` directly, or via the reverse proxy address.
