### DISCUSSION TITLE
change download directory

### DISCUSSION THREAD

**Discussion by jasonafriedman** [haugene/docker-transmission-openvpn#2228] [Q&A] [answered]
I am trying to get transmission to save to a directory that is not in /data. Here is what I have changed when the container is not running. 
docker-compose.ylm
        volumes:
            - "C:/Users/username/Documents/Docker/Haugene-Transmission-OpenVPN:/data"
            - "D:/Dockershare:/home
        environment:
            - TRANSMISSION_INCOMPLETE_DIR=:/home/incomplete
            - TRANSMISSION_DOWNLOAD_DIR:/home

Also changed this in settings.json for transmission
    "download-dir": "/home",
    "incomplete-dir": "/home/incomplete",
    
My docker log is showing:

Updating Transmission settings.json with values from env variables
Using existing settings.json for Transmission /data/transmission-home/settings.json
Overriding bind-address-ipv4 because TRANSMISSION_BIND_ADDRESS_IPV4 is set to 10.8.3.3
Overriding download-dir because TRANSMISSION_DOWNLOAD_DIR is set to /data/completed
Overriding incomplete-dir because TRANSMISSION_INCOMPLETE_DIR is set to /data/incomplete
Overriding rpc-port because TRANSMISSION_RPC_PORT is set to 9091
Overriding watch-dir because TRANSMISSION_WATCH_DIR is set to /data/watch

Any ideas how to get the settings to stick?

**Comment by pkishino** [comment, marked as answer]
please check your compose
```yaml
volumes:
- "C:/Users/username/Documents/Docker/Haugene-Transmission-OpenVPN:/data"
- "D:/Dockershare:/home
environment:
- TRANSMISSION_INCOMPLETE_DIR=:/home/incomplete
- TRANSMISSION_DOWNLOAD_DIR:/home
```
is not valid..it should be
```yaml
volumes:
- "C:/Users/username/Documents/Docker/Haugene-Transmission-OpenVPN:/data"
- "D:/Dockershare:/home"
environment:
- TRANSMISSION_INCOMPLETE_DIR=/home/incomplete
- TRANSMISSION_DOWNLOAD_DIR=/home
```
Above is also assuming you have properly setup volume sharing in docker for windows etc..
Please check the settings.json file with the container running, are the paths set correctly there or not? It seems not.
I suggest you stop your container, backup settings.json then delete the orig. start container again, it will recreate
