### DISCUSSION TITLE
Upgrading container ?

### DISCUSSION THREAD

**Discussion by DuvelCorp** [haugene/docker-transmission-openvpn#2232] [Q&A] [answered]
Hello

I am not really a docker expert and I can't figure out how I can upgrade my container to run the latest version.

My actual config is running perfectly for several months, but my understanding is that am running an old image **3.3** that can be upgraded to **4.0**.

I currently use this docker-compose (On Ubuntu)

```
version: '3.3'
services:
    transmission-openvpn:
        cap_add:
            - NET_ADMIN
        volumes:
            - '/media/seedbox/torrents/:/data'
            - '/home/seedbox/cyberghost_vpn/:/etc/openvpn/custom/'
        environment:
            - OPENVPN_PROVIDER=CUSTOM
            - OPENVPN_USERNAME=xxxxx
            - OPENVPN_PASSWORD=xxxxx
            - LOCAL_NETWORK=192.168.0.0/16
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '9091:9091'
        image: haugene/transmission-openvpn
        restart: unless-stopped
```

I tried to change my docker-compose file with : 

`version: '4.0'`

but I then end up with those errors : 
```

seedbox@dmzseedbox:~$ sudo docker-compose up
ERROR: Version "4.0" in "./docker-compose.yml" is invalid.
seedbox@dmzseedbox:~$
seedbox@dmzseedbox:~$ sudo docker-compose pull
ERROR: Version "4.0" in "./docker-compose.yml" is invalid
```

I searched quite a lot on google and reddit, I read the documentation, and nothing helps.

Can you explain how I am supposed to do to upgrade my container image (and obviously keep all my config and queued torrents)

Cheers
