### DISCUSSION TITLE
Access proxy outside server

### DISCUSSION THREAD

**Discussion by ondanieldev** [haugene/docker-transmission-openvpn#2258] [Q&A]
Hi,

I've setup a docker container on my server using a web proxy. It works fine using the proxy inside my server. However, I wanna use the proxy outside my server, and it's not working. I've tried a lot of thing but nothing has worked. Someone can help me finding out a way to solve it?

My docker-compose.yml:
```
version: "3"

services:
  transmission-openvpn:
    image: haugene/transmission-openvpn
    container_name: transmission
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    volumes:
      - "~/openvpn/:/data"
      - "~/openvpn/config:/etc/openvpn/custom/"
    ports:
      - 9091:9091
      - 8118:8118
    logging:
      driver: json-file
      options:
        max-size: 10m
    environment:
      - OPENVPN_PROVIDER=custom
      - OPENVPN_CONFIG=US-Roseburg_UDP
      - OPENVPN_USERNAME=ommited
      - OPENVPN_PASSWORD=ommited
      - LOCAL_NETWORK=192.168.0.0/24
      - WEBPROXY_ENABLED=true
      - WEBPROXY_PORT=8118

  transmission-proxy:
    image: haugene/transmission-openvpn-proxy
    container_name: transmission-proxy
    restart: unless-stopped
    links:
      - transmission:transmission
    ports:
      - 8080:8080
```

To give an example, it works properly if I run (inside my server):
```
curl --proxy http://localhost:8118 https://httpbin.org/ip
```

However, it doesn't work if I run (outside my server):
```
curl --proxy http:/my-ip:8118 https://httpbin.org/ip
```

Also, I've opened the 8118 port on my server panel, but it is not being shown if I run nmap:
```
PORT     STATE    SERVICE
22/tcp   open     ssh
25/tcp   filtered smtp
80/tcp   open     http
110/tcp  open     pop3
143/tcp  open     imap
443/tcp  open     https
465/tcp  open     smtps
587/tcp  open     submission
666/tcp  open     doom
888/tcp  open     accessbuilder
993/tcp  open     imaps
995/tcp  open     pop3s
1080/tcp open     socks
1434/tcp filtered ms-sql-m
8080/tcp open     http-proxy
9091/tcp filtered xmltec-xmlmail
```

So I've tried to use other ports, like 8080. However, when I try it, the port state turns from "open" to "filtered".

Thanks in advance for helping me :)
