### DISCUSSION TITLE
K8s Configuration for transmission-rss

### DISCUSSION THREAD

**Discussion by clarkent86** [haugene/docker-transmission-openvpn#2269] [Q&A] [answered]
Hey team,
I was wondering if I could get some help configuring the transmission-rss image on my TrueNas server.
I have the regular image running perfectly and I'm able to upload torrents fine, but was trying to get the rss image to run in my cluster as well.
Since there is no link configuration on K8s I figured I could potentially mount the transmission-rss.conf or config.yml into their respective directories according to the documentation and it would potentially start up, but I've had no luck. This is my config:

```
feeds:
  - url: <custom rss feed>
  #   download_path: <placeholder>
  #   regexp: <placeholder>

server:
  host: localhost
  port: 9091
  rpc_path: /transmission/rpc

# login:
#   username: test
#   password: test
```

I've tried to mount this as `transmission-rss.conf` in `/etc` and also as `config.yml` in `~/.config/transmission-rss`.

Any suggestions? I'm not getting any logs from the container either unfortunately, it seems to be unable to deploy and doesn't log.

Edit:
Fixed my image pull error
When I try with transmission-rss.conf mounted I'm getting a CrashLoopBackoff
When I attempt to mount config.yml I am getting RunContainerError
