### DISCUSSION TITLE
Invalid text being injected into my host address when using a custom ovpn

### DISCUSSION THREAD

**Discussion by strongui** [haugene/docker-transmission-openvpn#2340] [Q&A] [answered]
This is my setup:

```
docker run --rm -it --cap-add=NET_ADMIN \
  -e OPENVPN_PROVIDER=custom \
  -e OPENVPN_USERNAME=<myuser>\
  -e OPENVPN_PASSWORD=<mypass>\
  -e OPENVPN_CONFIG=Skate \
  -e DISABLE_PORT_UPDATER=true \
  -v ${PWD}/config/vpn/:/etc/openvpn/custom/ \
  haugene/transmission-openvpn
```

Inside my folder: `${PWD}/config/vpn/` I two files **Skate.ovpn** and **openvpn-credentials.txt**

The Skate.ovpn has this; I am showing only the relevant parts: (notice the **remote** part)

```
##############################################
# Whatbox OpenVPN Configuration              #
##############################################

#################
# Client Config #
#################
client
dev tun
nobind

## Tries IPv6 if available, with fallback to IPv4.
## This may be changed to "proto udp4" or
## "proto udp6" if your connection requires it.
proto udp
remote skate.whatbox.ca 1194
resolv-retry infinite

```

When I run the above command, this is the error I get:

**Cannot resolve host address: skate.whatbox.ca:/etc/openvpn/custom/1194 (Servname not supported for ai_socktype)**

Notice that it's trying to access: skate.whatbox.ca**:/etc/openvpn/custom/**1194, it is injecting this into the host address for some reason.

After running the command, when I reopen Skate.ovpn, it has now been changed to:

```
##############################################
# Whatbox OpenVPN Configuration              #
##############################################

#################
# Client Config #
#################
client
dev tun
nobind

## Tries IPv6 if available, with fallback to IPv4.
## This may be changed to "proto udp4" or
## "proto udp6" if your connection requires it.
proto udp
remote skate.whatbox.ca /etc/openvpn/custom/1194
```

It modified my opvn file and injected that text into the remote. 

Is this a bug, or something wrong with my setup?

**Comment by pkishino** [comment, marked as answer]
change your mount to:
-v ${PWD}/config/vpn/Skate.ovpn:/etc/openvpn/custom/default.ovpn
instead and try

**Reply by pkishino** [reply]
reason for injection is this:
https://github.com/haugene/docker-transmission-openvpn/blob/a95f586492b2b7e8ff2cc8ac7f91bc43c0cccc40/openvpn/adjustConfigs.sh#L36
to avoid, please pass * CONFIG_MOD_CA_CERTS=0*

**Reply by strongui** [reply]
Thank you for the reply. So I got everything fully working, when using `docker run --rm`, here is the final version:

```
docker run --rm -it --cap-add=NET_ADMIN --sysctl net.ipv6.conf.all.disable_ipv6=0 \
  -p 9091:9091 \
  -e LOCAL_NETWORK=192.168.0.0/16 \
  -e OPENVPN_PROVIDER=custom \
  -e OPENVPN_USERNAME=<myuser> \
  -e OPENVPN_PASSWORD=<mypass> \
  -e OPENVPN_CONFIG=Skate \
  -e CONFIG_MOD_CA_CERTS=0 \
  -e DISABLE_PORT_UPDATER=true \
  -v ${PWD}/config/vpn/:/etc/openvpn/custom/ \
  haugene/transmission-openvpn
```

I had to add: `--sysctl net.ipv6.conf.all.disable_ipv6=0` to get everything up and running. I have been following this guide https://haugene.github.io/docker-transmission-openvpn/debug/ to figure out what was happening.

Now I am trying to migrate all of this into a yml file, so I can use docker-compose, and for some reason my container just keeps restarting, and I have a feeling it's related to the ipv6 part. Here is what I have:

```
  vpn:
    container_name: vpn
    image: haugene/transmission-openvpn:dev
    cap_add:
        - NET_ADMIN
    sysctls:
        - net.ipv6.conf.all.disable_ipv6=0 # make sure ipv6 is on    	  
    restart: unless-stopped
    volumes:
      - ${ROOT}/config/vpn/:/etc/openvpn/custom/ # OpenVPN configuration
    environment:
        - OPENVPN_PROVIDER=custom
        - OPENVPN_USERNAME=<myuser>
        - OPENVPN_PASSWORD=<mypass>
        - OPENVPN_CONFIG=Skate
        - CONFIG_MOD_CA_CERTS=0
        - DISABLE_PORT_UPDATER=true
        - LOCAL_NETWORK=192.168.0.0/24
    logging:
        driver: json-file
        options:
            max-size: 10m
    ports:
      - 9091:9091 # port for transmission container
```

Two question @pkishino :

1. Do you see anything wrong with the file, specifically related to ipv6?
2. Is there a way to enable all the debug info that I was getting before, when I was running just `docker run --rm`, when using `docker-compose up -d vpn`

Thanks!

**Reply by strongui** [reply]
Alright, I've got it figured out, here is all the info if you need, if are trying to set this up via Whatbox VPN.

1. Download your ovpn file from Whatbox
2. Create a file next to it called: openvpn-credentials.txt, put your username on the first line and password directly on the second, nothing else
3. Next your docker-compose will look like this:

```
vpn:
    container_name: vpn
    image: haugene/transmission-openvpn:dev
    cap_add:
        - NET_ADMIN
    sysctls:
        - net.ipv6.conf.all.disable_ipv6=0 # make sure ipv6 is on    	  
    restart: unless-stopped
    volumes:
      - ${ROOT}/config/vpn/:/etc/openvpn/custom/ # OpenVPN configuration
      - ${ROOT}/config/vpn/openvpn-credentials.txt:/config/openvpn-credentials.txt # OpenVPN auth
    environment:
        - OPENVPN_PROVIDER=custom
        - OPENVPN_USERNAME=**None**
        - OPENVPN_PASSWORD=**None**
        - OPENVPN_CONFIG=<INSERT_YOUR_SERVER_NAME> # This is the name of your .ovpn file that you downloaded
        - CONFIG_MOD_CA_CERTS=0
        - DISABLE_PORT_UPDATER=true
        - LOCAL_NETWORK=192.168.0.0/24
        - ENABLE_UFW=true
        - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
    logging:
        driver: json-file
        options:
            max-size: 10m
    ports:
      - 9091:9091 # port for transmission container
```
Another point for your newcomers to docker,  `docker-compose up -d vpn`, the `-d` flag starts the container in "DETACHED" mode, so you will not see any logs. Simply remove it if you want to see all the logs. This will help you greatly debug your setup. Also, this page here is very helpful: https://haugene.github.io/docker-transmission-openvpn/debug/
