### DISCUSSION TITLE
Options error: You must define TUN/TAP device (--dev)

### DISCUSSION THREAD

**Discussion by mendhak** [haugene/docker-transmission-openvpn#2353] [General]
My setup has been working for a long time, but stopped working today. The error logs exit with a message,  "Options error: You must define TUN/TAP device (--dev)".  

FIrst, the error logs:

> Starting container with revision: 2c1f6102ec454003e980d6f64d60b6dc48c75bf8
Creating TUN device /dev/net/tun
Using OpenVPN provider: SURFSHARK
Running with VPN_CONFIG_SOURCE auto
No bundled config script found for SURFSHARK. Defaulting to external config
Downloading configs from https://github.com/haugene/vpn-configs-contrib/archive/main.zip into /tmp/tmp.SeFtS5MArt
Extracting configs to /tmp/tmp.0PLXKxd83e
Found configs for SURFSHARK in /tmp/tmp.0PLXKxd83e/vpn-configs-contrib-main/openvpn/surfshark, will replace current content in /etc/openvpn/surfshark
Cleanup: deleting /tmp/tmp.SeFtS5MArt and /tmp/tmp.0PLXKxd83e
No VPN configuration provided. Using default.
Modifying /etc/openvpn/surfshark/default.ovpn for best behaviour in this container
Modification: Point auth-user-pass option to the username/password file
sed: can't read /etc/openvpn/surfshark/default.ovpn: No such file or directory
Modification: Change ca certificate path
sed: can't read /etc/openvpn/surfshark/default.ovpn: No such file or directory
Modification: Change ping options
sed: can't read /etc/openvpn/surfshark/default.ovpn: No such file or directory
sed: can't read /etc/openvpn/surfshark/default.ovpn: No such file or directory
sed: can't read /etc/openvpn/surfshark/default.ovpn: No such file or directory
sed: can't read /etc/openvpn/surfshark/default.ovpn: No such file or directory
Modification: Update/set resolv-retry to 15 seconds
Modification: Change tls-crypt keyfile path
Modification: Set output verbosity to 3
Modification: Remap SIGUSR1 signal to SIGTERM, avoid OpenVPN restart loop
Modification: Updating status for config failure detection
Setting OpenVPN credentials...
adding route to local network 192.168.50.0/24 via 172.23.0.1 dev eth0
Fri Sep 30 13:01:16 2022 disabling NCP mode (--ncp-disable) because not in P2MP client or server mode
Options error: You must define TUN/TAP device (--dev)
Use --help for more information.
docker-transmission-openvpn-transmission-1 exited with code 1

It seems to be downloading the configs, but then can't find a default?  
Additionally there is the error about the TUN/TAP device.  

Next, the docker-compose.yml 

```
version: '2'
services:
 transmission:
  image: haugene/transmission-openvpn:dev
  cap_add:
    - NET_ADMIN
  restart: always
  ports:
    - "9091:9091"
    - "8888:8888"
  dns:
    - 8.8.8.8
    - 8.8.4.4
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /home/mendhak/Downloads/vpntransmission:/data
  environment:
    - CREATE_TUN_DEVICE=true
    - OPENVPN_PROVIDER=SURFSHARK
    - OPENVPN_USERNAME=xx
    - OPENVPN_PASSWORD=xx
    - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60 --dhcp-option DNS 8.8.8.8
    - LOCAL_NETWORK=192.168.50.0/24
    - GLOBAL_APPLY_PERMISSIONS=false
    - TRANSMISSION_WEB_HOME=/data/flood-for-transmission
    - OVPN_PROTOCOL=udp
    - OVPN_COUNTRY=us
    - OVPN_CITY=chicago
    - OVPN_CONNECTION=multihop

```

I have tried `CREATE_TUN_DEVICE` and also tried mapping `devices: /dev/net/tun` in the docker-compose.yml, but no effect.  
I'm using the `:dev` Docker image since the README mentions it, and although it seems unrelated I've also tried [the Protocol/Country/City/Connection options from here](https://haugene.github.io/docker-transmission-openvpn/provider-specific/#ovpn). 

Does anything stand out here that needs changing?

**Comment by pkishino** [comment]
1) surfshark doesn’t have any default, you need to specify which server file you want to use, you can find them all in the vpn provider repo we host ( same location they are downloaded from)
2) the protocol/city etc stuff is ONLY for nordvpn
3) check your system, does it create the device properly or not? Any recent updates that might have broken this?

**Comment by mendhak** [comment]
Aha. I think I see what you mean.  I followed [this guide here](https://haugene.github.io/docker-transmission-openvpn/run-container/#2_it_is_not_mandatory_but_setting_openvpn_config_is_good) and added this:

    - OPENVPN_CONFIG=nl-ams.prod.surfshark.com_tcp

Is that what you meant? That started working without complaints about TUN/TAP.  

Thanks for the pointers. 

The docker compose I ended up with:

```
version: '3.3'
services:
    transmission-openvpn:
        cap_add:
            - NET_ADMIN
        volumes:
            - '/home/mendhak/Downloads/vpntransmission:/data'
        dns:
            - 8.8.8.8
            - 8.8.4.4
        environment:
            - OPENVPN_PROVIDER=SURFSHARK
            - OPENVPN_CONFIG=nl-ams.prod.surfshark.com_tcp
            - OPENVPN_USERNAME=x
            - OPENVPN_PASSWORD=x
            - LOCAL_NETWORK=192.168.50.0/24
            - OVPN_PROTOCOL=udp
            - OVPN_COUNTRY=us
            - OVPN_CITY=chicago
            - OVPN_CONNECTION=multihop
            - GLOBAL_APPLY_PERMISSIONS=false
            - TRANSMISSION_WEB_UI=flood-for-transmission
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '9091:9091'
        image: haugene/transmission-openvpn:dev

```
