### DISCUSSION TITLE
WebUI inaccessible

### DISCUSSION THREAD

**Discussion by 4xgkg** [haugene/docker-transmission-openvpn#2392] [Q&A]
I've been using the container `:latest` for a few years now.

I used to regularly pull the latest.

A couple of weeks ago, the web UI stopped responding.

I have `LOCAL_NETWORK` set correctly to my home LAN CIDR, as is also described in https://haugene.github.io/docker-transmission-openvpn/vpn-networking/ and this used to work fine for a long time.

Here is the current `docker-compose.yml` (after many tweaks to try to fix this):
```
version: '3.3'
services:
 transmission:
  image: haugene/transmission-openvpn:4.2
  container_name: transmission
  cap_add:
    - NET_ADMIN
  privileged: true
  devices:
    - /dev/net/tun
  restart: unless-stopped
  ports:
    - "9091:9091"
    - "8118:8118"
  dns:
    - 8.8.8.8
    - 8.8.4.4
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - ${HOME}/Downloads/trans/:/data
    # This is a new one, from following the latest docs
    - ${HOME}/transmission/config:/config
  environment:
    - CREATE_TUN_DEVICE=true
    - OPENVPN_PROVIDER=<reducted>
    - OPENVPN_CONFIG=<reducted>
    - OPENVPN_USERNAME=<reducted>
    - OPENVPN_PASSWORD=<reduced>
    - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
    - WEBPROXY_ENABLED=true
    - WEBPROXY_PORT=8118
    - LOCAL_NETWORK=192.168.0.0/24
    - PUID=1000
    - PGID=1000
```
Executing `netstat` and the logs show that the VPN comes up fine, even Transmission finds files in the `watch` directory and pulls them, but I can't reach the WebUI.
```
root@6580534535a8:/# netstat -tlpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.11:39635        0.0.0.0:*               LISTEN      -
tcp        0      0 172.21.0.2:8118         0.0.0.0:*               LISTEN      104/privoxy
tcp        0      0 10.8.8.7:57707          0.0.0.0:*               LISTEN      105/transmission-da
tcp6       0      0 :::57707                :::*                    LISTEN      105/transmission-da
```
Privoxy itself is accessible on port 8118, and lets me tunnel my HTTP traffic through the VPN:

```
❯ curl -x http://transmission-host-ip:8118/ ifconfig.co/json
{
...
  "country": "Singapore",
  "user_agent": {
    "product": "curl",
    "version": "7.79.1",
    "raw_value": "curl/7.79.1"
  }
}
```
(Singapore is the VPN location)

But trying to reach port 9091 (which I also see is not listned to on the container), gets `Connection Refused`:
```
❯ curl -v http://transmission-host-ip:9091/
*   Trying transmission-host-ip:9091...
* connect to transmission-host-ip port 9091 failed: Connection refused
* Failed to connect to nuc port 9091 after 126 ms: Connection refused
* Closing connection 0
curl: (7) Failed to connect to nuc port 9091 after 126 ms: Connection refused
```

What am I missing?
