### DISCUSSION TITLE
Release 4.3.0: Newer OpenVPN and Transmission

### DISCUSSION THREAD

**Discussion by haugene** [haugene/docker-transmission-openvpn#2411] [Announcements]
The main update in this release is that we're changing the base image from Ubuntu 20.04 to 22.04 :tada: 
This means that we're moving from Transmission 2.94 to 3.00, and OpenVPN 2.4.7 to 2.5.5.

There's also a fix for an issue that has been affecting NordVPN users in the last few releases #2404

On the non-functional side we're moving the image builds from CircleCI to GitHub actions both because there was a time limit that caused problems for the beta builds and that it will bring the CI/CD stuff closer to the code. We're already using GitHub for repo hosting, discussion board and issue tracking so we gather more in that ecosystem.

The latter also meant that I had to rewrite the build pipelines and we're changing the image tag strategy ever so slightly. We're relying on the docker/metadata-action to generate tags for us instead of doing it in a custom way, conventions over configuration! `latest` will now point to the latest release rather than the latest commit on master branch. Apart from that it will be pretty similar. `edge` will be the latest commit on master branch (soon main branch I suspect), and we will also tag each build with the branch name as well so `dev` will still be `dev`.

Let's see how it goes. Need to make this release to see that all the tags appear as they should :crossed_fingers: 

<hr /><em>This discussion was created from the release <a href='https://github.com/haugene/docker-transmission-openvpn/releases/tag/v4.3.0'>Release 4.3.0: Newer OpenVPN and Transmission</a>.</em>

**Comment by haugene** [comment]
There was an error with the triggering of GitHub Actions. Fixed in `4.3.1` :+1: 
So `4.3.0` won't exist, but `4.3` will and also `4.3.1` :smile:

**Comment by tmknight** [comment]
No issues encountered with my Nord container.  Reminder that Privoxy is "upgraded" to 3.0.33...fixes and new features (https inspection being the most significant).

**Reply by dankrr** [reply]
> No issues encountered with my Nord container. Reminder that Privoxy is "upgraded" to 3.0.33...fixes and new features (https inspection being the most significant).

My privoxy has stopped working recently and not sure why. Was working on previous builds. Tried looking around for  a solution with no luck

**Reply by tmknight** [reply]
Hard to tell based on what you've shared (and I have my own custom configs for Privoxy, so not sure what is default for the image), though, maybe you need to re-configure the bind address to 0.0.0.0 in the config file.

**Comment by petebanham** [comment]
Unfortunately 4.3.x broke it for me. Running on a Pi using pureVPN. Container starts and logs shows the VPN  initialisation completes fine then nothing, Transmission doesn't start .  Docker shows the container as  unhealthy and server does not respond on port 9091.  Rolled back to 4.2 and it works again

**Reply by petebanham** [reply]
Here is the difference at the end of logs on startup  

```
not working 4.3.x
DROPPING DEFAULT ROUTE
RTNETLINK answers: No such process
2022-11-21 13:31:47 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
2022-11-21 13:31:47 Initialization Sequence Completed

Working 4.2
DROPPING DEFAULT ROUTE
STARTING TRANSMISSION
Transmission startup script complete.
Mon Nov 21 13:27:04 2022 Initialization Sequence Completed
```

**Reply by haugene** [reply]
This might be because of the `up` and `down` directives in the openvpn config files. It doesn't seem like it's firing like it should. Could you provide the docker run or docker compose file you use. Which config are you using? Are you passing in any OPENVPN_OPTS?

**Reply by petebanham** [reply]
Sorry for the delay in reply , I have been working away from home for a few weeks. Here is my config, pinned to v4.2
```
transmission:
    container_name: transmission
    image: haugene/transmission-openvpn:4.2
    ports:
      - '9091:9091'
    environment:
      TZ: 'Europe/London'
      OPENVPN_PROVIDER: PUREVPN
      OPENVPN_CONFIG: de2-ovpn-tcp
      OPENVPN_USERNAME: *******
      OPENVPN_PASSWORD: *******
      DISABLE_PORT_UPDATER: 'true'
      WEBPROXY_ENABLED: 'false'
      TRANSMISSION_DOWNLOAD_DIR: /nas/complete/
      LOCAL_NETWORK: 192.168.5.0/24
      DROP_DEFAULT_ROUTE: 'true'
      TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED: 'false'
      OPENVPN_OPTS: --inactive 3600 --ping 10 --ping-exit 60
    volumes:
      - '/home/pi/nas/:/nas/'
      - '/home/pi/nas/trans/:/config'
      - '/home/pi/nas/trans/:/data' 
    cap_add:
      - NET_ADMIN
    logging:
      driver: json-file
      options:
        max-size: 10m
    restart: unless-stopped
```
