### DISCUSSION TITLE
Can't launch Docker-Transmission using PIA

### DISCUSSION THREAD

**Discussion by pow3rslave** [haugene/docker-transmission-openvpn#2459] [Q&A] [answered]
a few weeks back, i updated to latest build, and immediately found that i couldn't launch Transmission, it seems it can't find the PIA ovpn file i've always used.
```
gershwin@DLbox:~$ sudo docker pull linuxserver/docker-compose:"${DOCKER_COMPOSE_IMAGE_TAG:-latest}"
latest: Pulling from linuxserver/docker-compose
df42d0a7b694: Pull complete 
2601eb96bfaa: Pull complete 
7421ed24fad5: Pull complete 
42be308edb70: Pull complete 
5c32b41951cf: Pull complete 
c99a224c9dd5: Pull complete 
f171060ef457: Pull complete 
e9ffb8de2a6d: Pull complete 
9fe9f2489158: Pull complete 
32704cfd08c0: Pull complete 
Digest: sha256:8dc71d6ac5e20f1c023476ff9d0e06184b6a9462a526f9751dbc5eef486f78c6
Status: Downloaded newer image for linuxserver/docker-compose:latest
```

docker-compose.yaml:
```
version: "3.3"
services:
  transmission-openvpn:
    container_name: Transmission
    image: haugene/transmission-openvpn
    cap_add:
      - NET_ADMIN
    volumes:
      - /media/nfsDL/:/data
    environment:
      - PUID=1000
      - PGID=1000
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_CONFIG=au_melbourne
      - OPENVPN_USERNAME=*****
      - OPENVPN_PASSWORD=*****
      - LOCAL_NETWORK=192.168.0.0/16
      - TRANSMISSION_TRASH_ORIGINAL_TORRENT_FILES=true
      - TRANSMISSION_RPC_USERNAME=*****
      - TRANSMISSION_RPC_PASSWORD=*****
      - HEALTH_CHECK_HOST=google.com
    logging:
      driver: json-file
      options:
          max-size: 10m
    ports:
      - '9091:9091'
    restart: unless-stopped
```
when trying to launch i get
```
gershwin@DLbox:~$ sudo docker-compose up
Starting Transmission ... done
Attaching to Transmission
Transmission            | Starting container with revision: b33d0fe4c938259a0d4eb844e55468f387456121
Transmission            | Creating TUN device /dev/net/tun
Transmission            | Using OpenVPN provider: PIA
Transmission            | Running with VPN_CONFIG_SOURCE auto
Transmission            | No bundled config script found for PIA. Defaulting to external config
Transmission            | Downloading configs from https://github.com/haugene/vpn-configs-contrib/archive/main.zip into /tmp/tmp.4po9R3u6j9
Transmission            | Extracting configs to /tmp/tmp.6iLvn9VmUh
Transmission            | Found configs for PIA in /tmp/tmp.6iLvn9VmUh/vpn-configs-contrib-main/openvpn/pia, will replace current content in /etc/openvpn/pia
Transmission            | Cleanup: deleting /tmp/tmp.4po9R3u6j9 and /tmp/tmp.6iLvn9VmUh
Transmission            | Supplied config au_melbourne.ovpn could not be found.
Transmission            | Your options for this provider are:
```

I can get it working if i set up PIA as an 'other' VPN, and place an au_melbourne.ovpn file in a mounted path, but not sure why the default mechanism is breaking

**Comment by ilike2burnthing** [comment]
Add `/config` volume - https://github.com/haugene/docker-transmission-openvpn#docker-compose

**Comment by pow3rslave** [comment]
thanks, I've added that (mapped  /config path), but still throwing the same output, and not launching.

I've looked through the wiki, and while it does include this config mapping, it doesn't specify any content to be added to this path, or include any provider specific settings for PIA, in fact it was working previously without it.

Given the scripts in the PIA directory at https://github.com/haugene/vpn-configs-contrib/archive/main.zip, haven't been updated for 2 years, and still pull down a bunch of OVPN files, i don't think this is the issue.
I can manually place these ovpn files, but it kind of defeats the purpose of having any PIA scripts or config set on the project

Since last week, I am only able to get it working if i add like this, and save an 'au_melbourne' file in the path defined

```
transmission:
    container_name: Transmission
    image: haugene/transmission-openvpn
    cap_add:
      - NET_ADMIN
    volumes:
      - /media/nfsDL/:/data
      - /media/nfsGen/ovpn/:/etc/openvpn/custom/
    environment:
      - PUID=1000
      - PGID=1000
      - OPENVPN_PROVIDER=custom
      - OPENVPN_CONFIG=au_melbourne
```

**Reply by ilike2burnthing** [reply]
You should keep the `/config` volume, but I blanked that you were using PIA.

You also need to add the ENV `PIA_OPENVPN_CONFIG_BUNDLE` and specify which bundle you want to use:

https://github.com/haugene/docker-transmission-openvpn/blob/51e5f1bcbbbc3c6c54b09896a44b6165531a1305/openvpn/pia/configure-openvpn.sh#L5-L9

e.g. `PIA_OPENVPN_CONFIG_BUNDLE=openvpn-tcp`

You do seem to be correct though about a lack of documentation for this. @haugene @pkishino

**Reply by gapple** [reply]
It looks to me like `PIA_OPENVPN_CONFIG_BUNDLE` should already be optional, defaulting to `openvpn`?  Releases prior to 4.3 started fine without it.
https://github.com/haugene/docker-transmission-openvpn/blob/51e5f1bcbbbc3c6c54b09896a44b6165531a1305/openvpn/pia/configure-openvpn.sh#L14

**Comment by haugene** [comment]
You're right that the documentation is lacking provider specific option for PIA @ilike2burnthing 

But I'm most curious about the line with `Transmission            | No bundled config script found for PIA. Defaulting to external config`

Because the config script for PIA is actually in the main image and such should be categorized as an "internal" provider:
https://github.com/haugene/docker-transmission-openvpn/tree/master/openvpn/pia

When I run the image I get:
```
openvpn  | Running with VPN_CONFIG_SOURCE auto
openvpn  | Provider PIA has a bundled setup script. Defaulting to internal config
openvpn  | Executing setup script for PIA
```

Don't remember why it's in both places. I think I had a follow-up task to remove the scripts from the vpn-configs-contrib repo but maybe good that I didn't. The external one isn't updated as recently as the internal one though so might be some issues there as well, the port-forwarding has been fixed at least in the internal one.

What host OS and Docker version are you running with @pow3rslave?

**Comment by pow3rslave** [comment]
@haugene, i'm running Docker version 18.09.1, build 4c52b90, on Debian GNU/Linux 10 (buster), i just cleared out all old images, and culled my docker-compose file back to basics, but still same output
```
---
version: '3.3'
services:
    transmission:
        container_name: Transmission
        image: haugene/transmission-openvpn
        cap_add:
            - NET_ADMIN
        volumes:
            - /media/nfsDL/:/data
            - /media/config/:/config
        environment:
            - PUID=1000
            - PGID=1000
            - OPENVPN_PROVIDER=PIA
            - PIA_OPENVPN_CONFIG_BUNDLE=openvpn-tcp
            - OPENVPN_CONFIG=au_melbourne
            - OPENVPN_USERNAME=############
            - OPENVPN_PASSWORD=###########
            - LOCAL_NETWORK=192.168.0.0/16
            - TRANSMISSION_TRASH_ORIGINAL_TORRENT_FILES=true
            - TRANSMISSION_SCRIPT_TORRENT_DONE_ENABLED=true
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '9091:9091'
        restart: unless-stopped
```

```
gershwin@helios64:~$ sudo docker images
REPOSITORY                           TAG                 IMAGE ID            CREATED             SIZE
haugene/transmission-openvpn         latest              12b6f42ffd5a        2 weeks ago         247MB
ghcr.io/linuxserver/docker-compose   latest              697cfd34d463        7 months ago        189MB
```

```
gershwin@helios64:~$ sudo docker-compose up
Transmission is up-to-date
Attaching to Transmission
Transmission    | Starting container with revision: b33d0fe4c938259a0d4eb844e55468f387456121
Transmission    | Creating TUN device /dev/net/tun
Transmission    | Using OpenVPN provider: PIA
Transmission    | Running with VPN_CONFIG_SOURCE auto
Transmission    | No bundled config script found for PIA. Defaulting to external config
Transmission    | Downloading configs from https://github.com/haugene/vpn-configs-contrib/archive/main.zip into /tmp/tmp.4wjy91N3fl
Transmission    | Extracting configs to /tmp/tmp.oEoDxbbn9J
Transmission    | Found configs for PIA in /tmp/tmp.oEoDxbbn9J/vpn-configs-contrib-main/openvpn/pia, will replace current content in /etc/openvpn/pia
Transmission    | Cleanup: deleting /tmp/tmp.4wjy91N3fl and /tmp/tmp.oEoDxbbn9J
Transmission    | Supplied config au_melbourne.ovpn could not be found.
Transmission    | Your options for this provider are:
Transmission    | Starting container with revision: b33d0fe4c938259a0d4eb844e55468f387456121
Transmission    | Creating TUN device /dev/net/tun
Transmission    | Using OpenVPN provider: PIA
Transmission    | Running with VPN_CONFIG_SOURCE auto
Transmission    | No bundled config script found for PIA. Defaulting to external config
Transmission    | Downloading configs from https://github.com/haugene/vpn-configs-contrib/archive/main.zip into /tmp/tmp.lk7P7i7m4U
Transmission    | Extracting configs to /tmp/tmp.SJCAkvNVvm
Transmission    | Found configs for PIA in /tmp/tmp.SJCAkvNVvm/vpn-configs-contrib-main/openvpn/pia, will replace current content in /etc/openvpn/pia
Transmission    | Cleanup: deleting /tmp/tmp.lk7P7i7m4U and /tmp/tmp.SJCAkvNVvm
Transmission    | Supplied config au_melbourne.ovpn could not be found.
Transmission    | Your options for this provider are:
Transmission    | Starting container with revision: b33d0fe4c938259a0d4eb844e55468f387456121
Transmission    | Creating TUN device /dev/net/tun
Transmission    | Using OpenVPN provider: PIA
Transmission    | Running with VPN_CONFIG_SOURCE auto
Transmission    | No bundled config script found for PIA. Defaulting to external config
Transmission    | Downloading configs from https://github.com/haugene/vpn-configs-contrib/archive/main.zip into /tmp/tmp.QTDgMPEYMJ
Transmission    | Extracting configs to /tmp/tmp.94HiwOlmUS
Transmission    | Found configs for PIA in /tmp/tmp.94HiwOlmUS/vpn-configs-contrib-main/openvpn/pia, will replace current content in /etc/openvpn/pia
Transmission    | Cleanup: deleting /tmp/tmp.QTDgMPEYMJ and /tmp/tmp.94HiwOlmUS
Transmission    | Supplied config au_melbourne.ovpn could not be found.
Transmission    | Your options for this provider are:
Transmission    | Starting container with revision: b33d0fe4c938259a0d4eb844e55468f387456121
Transmission    | Creating TUN device /dev/net/tun
Transmission    | Using OpenVPN provider: PIA
Transmission    | Running with VPN_CONFIG_SOURCE auto
Transmission    | No bundled config script found for PIA. Defaulting to external config
Transmission    | Downloading configs from https://github.com/haugene/vpn-configs-contrib/archive/main.zip into /tmp/tmp.faGovBp6A8
Transmission    | Extracting configs to /tmp/tmp.0zRSvaEyuS
Transmission    | Found configs for PIA in /tmp/tmp.0zRSvaEyuS/vpn-configs-contrib-main/openvpn/pia, will replace current content in /etc/openvpn/pia
Transmission    | Cleanup: deleting /tmp/tmp.faGovBp6A8 and /tmp/tmp.0zRSvaEyuS
Transmission    | Supplied config au_melbourne.ovpn could not be found.
Transmission    | Your options for this provider are:
Transmission    | Starting container with revision: b33d0fe4c938259a0d4eb844e55468f387456121
Transmission    | Creating TUN device /dev/net/tun
Transmission    | Using OpenVPN provider: PIA
Transmission    | Running with VPN_CONFIG_SOURCE auto
Transmission    | No bundled config script found for PIA. Defaulting to external config
Transmission    | Downloading configs from https://github.com/haugene/vpn-configs-contrib/archive/main.zip into /tmp/tmp.O6BNh77PNM
Transmission    | Extracting configs to /tmp/tmp.pLEVet98IC
Transmission    | Found configs for PIA in /tmp/tmp.pLEVet98IC/vpn-configs-contrib-main/openvpn/pia, will replace current content in /etc/openvpn/pia
Transmission    | Cleanup: deleting /tmp/tmp.O6BNh77PNM and /tmp/tmp.pLEVet98IC
Transmission    | Supplied config au_melbourne.ovpn could not be found.
Transmission    | Your options for this provider are:
Transmission    | Starting container with revision: b33d0fe4c938259a0d4eb844e55468f387456121
Transmission    | Creating TUN device /dev/net/tun
Transmission    | Using OpenVPN provider: PIA
Transmission    | Running with VPN_CONFIG_SOURCE auto
Transmission    | No bundled config script found for PIA. Defaulting to external config
Transmission    | Downloading configs from https://github.com/haugene/vpn-configs-contrib/archive/main.zip into /tmp/tmp.TJXLQiEuzC
Transmission    | Extracting configs to /tmp/tmp.ar6Zpx55sR
Transmission    | Found configs for PIA in /tmp/tmp.ar6Zpx55sR/vpn-configs-contrib-main/openvpn/pia, will replace current content in /etc/openvpn/pia
Transmission    | Cleanup: deleting /tmp/tmp.TJXLQiEuzC and /tmp/tmp.ar6Zpx55sR
Transmission    | Supplied config au_melbourne.ovpn could not be found.
Transmission    | Your options for this provider are:
Transmission    | Starting container with revision: b33d0fe4c938259a0d4eb844e55468f387456121
Transmission    | Creating TUN device /dev/net/tun
Transmission    | Using OpenVPN provider: PIA
Transmission    | Running with VPN_CONFIG_SOURCE auto
Transmission    | No bundled config script found for PIA. Defaulting to external config
Transmission    | Downloading configs from https://github.com/haugene/vpn-configs-contrib/archive/main.zip into /tmp/tmp.p8bMmptByz
Transmission    | Extracting configs to /tmp/tmp.R5V0hxja7O
Transmission    | Found configs for PIA in /tmp/tmp.R5V0hxja7O/vpn-configs-contrib-main/openvpn/pia, will replace current content in /etc/openvpn/pia
Transmission    | Cleanup: deleting /tmp/tmp.p8bMmptByz and /tmp/tmp.R5V0hxja7O
Transmission    | Supplied config au_melbourne.ovpn could not be found.
Transmission    | Your options for this provider are:
Transmission    | Starting container with revision: b33d0fe4c938259a0d4eb844e55468f387456121
Transmission    | Creating TUN device /dev/net/tun
Transmission    | Using OpenVPN provider: PIA
Transmission    | Running with VPN_CONFIG_SOURCE auto
Transmission    | No bundled config script found for PIA. Defaulting to external config
Transmission    | Downloading configs from https://github.com/haugene/vpn-configs-contrib/archive/main.zip into /tmp/tmp.HsjYoD5XsH
Transmission    | Extracting configs to /tmp/tmp.eBAsN8CoqS
Transmission    | Found configs for PIA in /tmp/tmp.eBAsN8CoqS/vpn-configs-contrib-main/openvpn/pia, will replace current content in /etc/openvpn/pia
Transmission    | Cleanup: deleting /tmp/tmp.HsjYoD5XsH and /tmp/tmp.eBAsN8CoqS
Transmission    | Supplied config au_melbourne.ovpn could not be found.
Transmission    | Your options for this provider are:
Transmission exited with code 1
```

what if anything needs to go in the /config folder? i haven't previously run this directory, only mapped /data (which houses download dir and the /transmission dir)
i have the same output from launching docker-compose with or without the config dir mapping in my docker-compose.yaml
