### DISCUSSION TITLE
can not start download

### DISCUSSION THREAD

**Discussion by pousoupou** [haugene/docker-transmission-openvpn#2528] [Q&A]
```
---
version: '3.3'
services:
    transmission-openvpn:
        cap_add:
            - NET_ADMIN
        volumes:
            - /home/stelios/media/:/data
            - /home/stelios/transmission/config/:/config
        environment:
            - OPENVPN_PROVIDER=NORDVPN
            - OPENVPN_CONFIG=Greece
            - OPENVPN_USERNAME=randomGeneratedStringFromNordAccount
            - OPENVPN_PASSWORD=randomGeneratedStringFromNordAccount
            - LOCAL_NETWORK=192.168.1.0/24
            - NORDVPN_COUNTRY=GR
            - NORDVPN_CATEGORY=legacy_p2p
            - NORDVPN_PROTOCOL=tcp
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - 9091:9091
        image: haugene/transmission-openvpn
        restart: unless-stopped
```

This is my compose, I don't get any errors whatsoever in the container's logs

transmission web gui is accessible through localIP:9091

tried to download a torrent to test things and can't announce to peers, so can't connect to any seeders/leechers

/media/ is an smb share from trueNAS to which I have both write/read access

I can't for the life of me figure out what is going wrong here. Any help is greatly appreciated
