### DISCUSSION TITLE
How to enable seeding when using Mullvad and peer listening port is open

### DISCUSSION THREAD

**Discussion by StefanVDWeide** [haugene/docker-transmission-openvpn#2536] [Q&A]
I've successfully deployed this docker container and have downloaded a number of series and movies, but for some reason I can't seem to get the seeding to work. I'm using Mullvad and I've setup port forwarding in my account and added the same port as the `TRANSMISSION_PEER_PORT` in the docker compose file. The upload will always stay at 0.

My docker compose file:

```yml
  transmission:
    image: haugene/transmission-openvpn
    container_name: transmission-openvpn
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "9091:9091"
    networks:
      - mediaserver
    logging:
      driver: json-file
      options:
        max-size: 10m
    environment:
      - OPENVPN_PROVIDER=${VPN_PROVIDER}
      - OPENVPN_CONFIG=${VPN_CONFIG}
      - OPENVPN_USERNAME=${VPN_USERNAME}
      - OPENVPN_PASSWORD=${VPN_PASSWORD}
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=192.168.2.0/24
      - TRANSMISSION_PEER_PORT=54919
      - TRANSMISSION_PORT_FORWARDING_ENABLED=true
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
      - TRANSMISSION_RATIO_LIMIT=2
    env_file:
      - .env
    sysctls:
      - "net.ipv6.conf.all.disable_ipv6=0"
    volumes:
      - /mnt/dm0/docker-services/transmission:/data
```

And my Transmission network settings look like this:

<img width="387" alt="image" src="https://user-images.githubusercontent.com/25407622/220107830-a7954e4f-b96b-4a4d-9a02-9509e02a84fc.png">

Am I missing a setting somewhere? Any help would be greatly appreciated!
