### DISCUSSION TITLE
How do I use my own self-hosted OpenVPN server on Digital Ocean without username or password authentication?

### DISCUSSION THREAD

**Discussion by x0ba** [haugene/docker-transmission-openvpn#2537] [Q&A]
I self host my own OpenVPN server on a Digital Ocean droplet, and I set everything up using the script found [here](https://github.com/Nyr/openvpn-install). As far as I know, there is no username or password, but I do have the .ovpn file. How should I write my docker-compose.yml, seeing as it seems to require a username and password? Here is my current docker-compose:
```
version: '3.3'
services:
    transmission-openvpn:
        cap_add:
            - NET_ADMIN
        volumes:
            - '/home/aspect/downloads/:/data'
            - '/config/:/config'
            - '/home/aspect/vpn/:/etc/openvpn/custom'
        environment:
            - OPENVPN_PROVIDER=custom
            - OPENVPN_CONFIG=darkstar #this is the name of my .ovpn file 
            - LOCAL_NETWORK=192.168.0.0/16
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '9091:9091'
        image: haugene/transmission-openvpn
```
I've tried omitting the username and password as well as setting them to the username and password for my Digital Ocean droplet, but nothing has worked.

**Comment by pkishino** [comment]
set both to ```**None**```
that should work, else create a file at /config/openvpn-credentials.txt that is empty

**Comment by x0ba** [comment]
When I do that, I get this error:
```
Starting container with revision: b33d0fe4c938259a0d4eb844e55468f387456121
Creating TUN device /dev/net/tun
Using OpenVPN provider: CUSTOM
Running with VPN_CONFIG_SOURCE auto
CUSTOM provider specified but not using default.ovpn, will try to find a valid config mounted to /etc/openvpn/custom
Starting OpenVPN using config darkstar.ovpn
Modifying /etc/openvpn/custom/darkstar.ovpn for best behaviour in this container
Modification: Point auth-user-pass option to the username/password file
Modification: Change ca certificate path
Modification: Change ping options
Modification: Update/set resolv-retry to 15 seconds
Modification: Change tls-crypt keyfile path
Modification: Set output verbosity to 3
Modification: Remap SIGUSR1 signal to SIGTERM, avoid OpenVPN restart loop
Modification: Updating status for config failure detection
OpenVPN credentials not set. Exiting.
```
For reference, here is my current `docker-compose.yml`
```
version: '3.3'
services:
    transmission-openvpn:
        cap_add:
            - NET_ADMIN
        volumes:
            - '/mnt/Volume3/downloads/:/data'
            - '/home/daniel/docker/transmission/config/:/config'
            - '/home/daniel/docker/transmission/config/vpn/:/etc/openvpn/custom/'
        environment:
            - OPENVPN_PROVIDER=custom
            - OPENVPN_CONFIG=darkstar
            - OPENVPN_USERNAME=**None**
            - OPENVPN_PASSWORD=**None**
            - LOCAL_NETWORK=192.168.0.0/16
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '9091:9091'
        image: haugene/transmission-openvpn
```
