### DISCUSSION TITLE
Unable to start pod?

### DISCUSSION THREAD

**Discussion by mcdent** [haugene/docker-transmission-openvpn#2562] [Q&A]
I am attempting to install transmission-openvpn to a kubernetes cluster running k3s:
```
NAME   STATUS   ROLES                  AGE     VERSION
k5     Ready    <none>                 15d     v1.24.11-rc1+k3s1
k3     Ready    <none>                 15d     v1.24.11-rc1+k3s1
k1     Ready    control-plane,master   15d     v1.24.11-rc1+k3s1
k4     Ready    <none>                 6d18h   v1.24.11-rc1+k3s1

```
I am using the helm command:
`helm install  bananaspliff/transmission-openvpn --values media.transmission-openvpn.values.yml --namespace media`

Which produces
```
NAME: transmission
LAST DEPLOYED: Sat Mar 25 15:43:28 2023
NAMESPACE: media
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace media -l "app=transmission-openvpn,release=transmission" -o jsonpath="{.items[0].metadata.name}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl port-forward $POD_NAME 8080:80

```
However the pod never starts and just ends in a crash loop. From the logs I see:

```
| ----- |
|  |  | 
| Sat, Mar 25 2023 3:45:15 pm | Starting container with revision: b33d0fe4c938259a0d4eb844e55468f387456121 | 
| Sat, Mar 25 2023 3:45:15 pm | Creating TUN device /dev/net/tun | 
| Sat, Mar 25 2023 3:45:15 pm | rm: cannot remove '/dev/net/tun': Device or resource busy | 

```

and:

`Mar 25 15:55:47 k4 k3s[26699]: E0325 15:55:47.087784   26699 pod_workers.go:965] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"transmission-openvpn\" with CrashLoopBackOff: \"back-off 1m20s restarting failed container=transmission-openvpn pod=transmission-transmission-openvpn-64bd5b68b9-4d6dq_media(2f00aa6d-2673-4167-9524-7949b3a161ce)\"" pod="media/transmission-transmission-openvpn-64bd5b68b9-4d6dq" podUID=2f00aa6d-2673-4167-9524-7949b3a161ce`

My help file is:-

```
## media.transmission-openvpn.values.yml
replicaCount: 1

image:
  repository: haugene/transmission-openvpn
  tag: latest # Suffixed by -armhf to pull the ARM image
  pullPolicy: IfNotPresent

env:
  - name: OPENVPN_PROVIDER
    value: "PIA" # VPN provider. List of supported providers: https://haugene.github.io/docker-transmission-openvpn/supported-providers/
  - name: OPENVPN_USERNAME
    valueFrom: # Reference to the secret | openvpn.username
      secretKeyRef:
        name: "openvpn"
        key: "username"
  - name: OPENVPN_PASSWORD
    valueFrom: # Reference to the secret | openvpn.password
      secretKeyRef:
        name: "openvpn"
        key: "password"
  - name: PIA_PROTOCOL
    value: "TCP"
  - name: PIA_COUNTRY
    value: "DE" # Country where we want to download over VPN
  - name: PIA_CATEGORY
    value: "P2P" # VPN Type
  - name: LOCAL_NETWORK
    value: "192.168.1.0/24"
  - name: TRANSMISSION_PEER_PORT
    value: "47444"
  - name: TRANSMISSION_DOWNLOAD_DIR
    value: "/downloads/transmission"
  - name: PUID
    value: "1000"
  - name: PGID
    value: "1000"

service:
  type: ClusterIP
  port: 80

volumes:
  - name: "media-store"
    persistentVolumeClaim:
      claimName: "media-store" # PersistentVolumeClaim created earlier
  - name: "dev-tun" # Needed for VPN
    hostPath:
      path: "/dev/net/tun"

volumeMounts:
  - name: "media-store"
    mountPath: "/data"
    subPath: "configs/transmission-data" # Path /mnt/ssd/media/configs/transmission-data where transmission writes the configuration
  - name: "media-store"
    mountPath: "/downloads/transmission"
    subPath: "downloads/transmission" # Path /mnt/ssd/media/downloads/transmission where transmission downloads Torrents
  - name: "dev-tun"
    mountPath: "/dev/net/tun" # Needed for VPN

securityContext:
  capabilities: # Needed for VPN
    add:
      - NET_ADMIN
```
Just wondered if anybody had any clues?
Thanks!
