### DISCUSSION TITLE
Transmission downloads owned by root:root

### DISCUSSION THREAD

**Discussion by NCVito** [haugene/docker-transmission-openvpn#2641] [Q&A] [answered]
I've noticed that completed downloads are being saved as root:root causing import issues from my media server. This looks like a recent issue as they were previously being saved as the correct user and group. 

Has anyone else experienced this? Anyone have any troubleshooting ideas?

**Comment by pkishino** [comment, marked as answer]
Check your pid/gid setup

**Reply by emk2203** [reply]
Could you elaborate a little? How exactly do I check? I have the same issue with 5.2.0, my `docker-compose.yml` contains the following lines:

```
version: '3.3'
services:
 transmission:
  image: haugene/transmission-openvpn
  cap_add:
    - NET_ADMIN
  devices:
    - /dev/net/tun
  restart: always
  ports:
    - "9091:9091"
    # - "8888:8888" # proxy support
  volumes:
    - /srv/media/:/data # where transmission will store the data
    - /opt/haugene/:/config # where transmission-home is stored
  environment:
...
    - LOCAL_NETWORK=192.168.88.0/24
    - PUID=65533
    - PGID=65533
    - GLOBAL_APPLY_PERMISSIONS=false
```
This has worked with the April release, after the update, the downloads are stored as root:root despite the PUID/PGID settings.
65533:65533 is the media user media:media on my system. It's in the main system, but not in the docker environment. Do I need to manually add this user to the container, or in the Dockerfile? I can't remember doing this before.
