### DISCUSSION TITLE
Looks like NordVPN download files endpoint is down... - How to proceed?

### DISCUSSION THREAD

**Discussion by export-mike** [haugene/docker-transmission-openvpn#2648] [General]
### Looks like NordVPN download files endpoint is down...  how to proceed?

This has been working for months, And this has also been working since the provider NordVPN required service credentials.

I'm getting this error
```
 ERROR: OVPN: cannot ping https://downloads.nordcdn.com/configs/files, network or internet unavailable. Cannot download NORDVPN configuration files
```

```yaml
version: '3.3'
services:
    transmission-openvpn:
        cap_add:
            - NET_ADMIN
        volumes:
            - '/Users/barry/ts/:/data'
        environment:
            - OPENVPN_PROVIDER=NORDVPN
            - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
            - NORDVPN_COUNTRY=AU
            - OPENVPN_USERNAME=username
            - OPENVPN_PASSWORD=pwd
            - LOCAL_NETWORK=192.168.0.0/16
            - NORDVPN_CATEGORY=legacy_p2p
            - NORDVPN_PROTOCOL=tcp
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '9091:9091'
        image: haugene/transmission-openvpn
        restart: always
```
