### DISCUSSION TITLE
Can't access other containers by their names (internal Docker DNS)

### DISCUSSION THREAD

**Discussion by melyux** [haugene/docker-transmission-openvpn#2666] [Q&A]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [ ] I have tried using dev branch

### Docker run config used

```yaml
  transmission:
    image: haugene/transmission-openvpn
    container_name: transmission
    cap_add:
      - NET_ADMIN
    environment:
      - LOCAL_NETWORK=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
      ...
    volumes:
      ...
# ports:
## None
```

### Current Behavior

Can't ping/access other containers by their names (Docker DNS/service discovery). I can still ping them using their internal Docker IPs though. Global DNS works (i.e. google.com).

### Expected Behavior

Should still be able to access local Docker DNS

Why? When I route other containers through this container to be behind the same VPN, they also lose DNS access to other containers.

### How have you tried to solve the problem?

- `exec`d into this container and tried pinging other containers by name (fail)
- `exec`d into other containers and tried pinging other containers by name (success)
- Tried setting `ENABLE_UFW` to `true`, and also just leaving it blank, to no effect

### Log output

```
root@b07160d60f78:/# ping radarr
ping: radarr: Name or service not known
```

### HW/SW Environment

```markdown
- OS: Debian
- Docker: Docker version 24.0.4, build 3713ee1
```
