### DISCUSSION TITLE
Need help installing or troubleshooting please.

### DISCUSSION THREAD

**Discussion by amrdeus2** [haugene/docker-transmission-openvpn#2676] [Q&A]
I'm very bad at all this docker stuff but I'm really trying to learn. I'm trying to use a custom VPN (BulletVPN) so I had to veer off of all the tutorials I've found. I think I've got it working since it hasn't given me any credential errors now. 

But now I'm getting this error:
2023-08-02 07:29:08 TLS Error: cannot locate HMAC in incoming packet from [AF_INET]192.71.24

I've googled it, but have no idea what the answers mean. For [instance](https://techoverflow.net/2020/09/20/how-to-fix-openvpn-tls-error-cannot-locate-hmac-in-incoming-packet-from/) How do I disable that? Where do I even look?

Running OMV>Docker>Portainer on Macbook. I built the app by pulling it from github, after forking it to add my custom VPN as suggested in the documentation. (which I don't think worked, so I ended up adding the variables manually as suggested in the documentation as well)

Apologies if this is very easy, I've been trying for days. Any help would be very appreciated.

**Comment by pkishino** [comment]
The error above is related to the vpn provider.. contact their support to request they fix their ovpn files

**Reply by amrdeus2** [reply]
Thanks very much for the help. If the issue is the vpn provider then I'd need to understand exactly what it is that worked (for instance which ovpn it worked out of all the ones I tried).

So I tried installing another container (with the old one disabled as backup). I tried using the app template ladled [transmission-openvpn-latest]. I entered all my details and get the following:

> CUSTOM provider specified but not using default.ovpn, will try to find a valid config mounted to /etc/openvpn/custom
Supplied config bulletVPN-AU-Sydney_1-syd01-tcp.ovpn could not be found.

I have my ovpn files in: usr/local/etc/openvpn/custom. Is that where its looking (I left all paths as default)?

Also my webUI isn't loading, I'm guessing this is why and not another issue.


Full log:
```
Running with VPN_CONFIG_SOURCE auto
CUSTOM provider specified but not using default.ovpn, will try to find a valid config mounted to /etc/openvpn/custom
Supplied config bulletVPN-AU-Sydney_1-syd01-tcp.ovpn could not be found.
Your options for this provider are:
Starting container with revision: 1103172c3288b7de681e2fb7f1378314f17f66cf
TRANSMISSION_HOME is currently set to: /config/transmission-home
Creating TUN device /dev/net/tun
Using OpenVPN provider: CUSTOM

```

**Reply by pkishino** [reply]
http://haugene.github.io/docker-transmission-openvpn/supported-providers/#using_a_local_single_ovpn_file_from_a_provider

**Reply by amrdeus2** [reply]
Thanks so much. This worked. I've been too afraid to try this method because I'm an idiot but it worked when I figured out how. Quick question: Does Transmission-OpenVPN always use VPN? Meaning I don't have to worry about kill switches or it not actually using the VPN? Just double checking since the test my IP torrent sites aren't working for some reason (but other torrents are).


For anyone who was dumb like me, what the above link is suggesting, is that in Portainer, you go to STACKS, then create one using something like this: (and place your ovpn files here:  /volume1/docker/ipvanish)
```

version: '3.3'
services:
    transmission-openvpn:
        cap_add:
            - NET_ADMIN
        volumes:
- /volume1/docker/ipvanish/:/etc/openvpn/custom/

        environment:
- OPENVPN_PROVIDER=custom
- OPENVPN_CONFIG=bulletVPN-AU-Sydney_1-syd01-tcp
- OPENVPN_USERNAME=ENTERYOURVPN LOGIN HERE
- OPENVPN_PASSWORD= ENTERYOURVPN PASS HERE
            - LOCAL_NETWORK=192.168.0.0/16
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '9091:9091'
        image: haugene/transmission-openvpn
```
