### DISCUSSION TITLE
Need help routing other containers through the VPN (following the documentation steps)

### DISCUSSION THREAD

**Discussion by amrdeus2** [haugene/docker-transmission-openvpn#2681] [Q&A] [answered]
Hey all, 
Apologies in advance if this is a stupid question. I got Transmission working fine, but when following the documentation to use "network_mode: "service:transmission-openvpn" I'm getting the following error from Portainer:

**"failed to deploy a stack: Network arr_default Creating Network arr_default Created Container transmission-openvpn Creating Container transmission-openvpn Created Container prowlarr Creating Error response from daemon: conflicting options: port publishing and the container type network mode"**

Any help would be greatly appreciated. ChatGPT says "The error message is indicating that you're trying to publish ports (ports property) for containers that are also using the network mode of another service (network_mode: "service:transmission-openvpn")." Then it directs me to do it differently to the documentation, which eventually gets it all installed but the containers don't open their webUIs. 

Any help would be amazing!
Here is my compose (pre any AI help):

```

`version: '3.3'
services:
    transmission-openvpn:
     container_name: transmission-openvpn
        cap_add:
            - NET_ADMIN
        volumes:
        - /volume1/docker/ipvanish/:/etc/openvpn/custom/
        - /media/USB/downloads:/downloads #optional
        - /media/USB/data/transmission:/config #optional?
        environment:
        - OPENVPN_PROVIDER=custom
        - OPENVPN_CONFIG=bulletVPN-AU-Sydney_1-syd01-tcp
        - OPENVPN_USERNAME=XXXXX
        - OPENVPN_PASSWORD=XXXXX
        - LOCAL_NETWORK=192.168.0.0/16
        - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '9091:9091'
            - 8888:8888/tcp # HTTP proxy
            - '8989:8989' # port for sonarr
            - '7878:7878' # port for radarr
            - '9696:9696' # port for prowlarr
            - '6767:6767' # port for bazarr
        restart: always
        image: haugene/transmission-openvpn



version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - puid=998
      - pgid=100
      - TZ=Australia/Sydney
    volumes:
      - /media/USB/data/radarr:/config
      - /media/USB/data:/data #optional

    ports:
      - 7878:7878
    restart: unless-stopped
    network_mode: "service:transmission-openvpn" # Add to the transmission-openvpn Container Network
    depends_on:
      - transmission-openvpn # Set dependency on transmission-openvpn Container
    healthcheck: # Here you will check if transmission is reachable from the Jackett container via localhost
    test: curl -f http://localhost:9091 || exit 1
            # Use this test if you protect your transmission with a username and password
            # comment the test above and un-comment the line below.
            #test: curl -f http://${TRANSMISSION_RPC_USERNAME}:${TRANSMISSION_RPC_PASSWORD}@localhost:9091 || exit 1
   interval: 5m00s
   timeout: 10s
    retries: 2



version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - puid=998
      - pgid=100
      - TZ=Australia/Sydney
    volumes:
    - /media/USB/data/radarr:/config
    - /media/USB/data:/data #optional
    ports:
      - 8989:8989
    restart: unless-stopped
    network_mode: "service:transmission-openvpn" # Add to the transmission-openvpn Container Network
    depends_on:
      - transmission-openvpn # Set dependency on transmission-openvpn Container
    healthcheck: # Here you will check if transmission is reachable from the Jackett container via localhost
    test: curl -f http://localhost:9091 || exit 1
            # Use this test if you protect your transmission with a username and password
            # comment the test above and un-comment the line below.
            #test: curl -f http://${TRANSMISSION_RPC_USERNAME}:${TRANSMISSION_RPC_PASSWORD}@localhost:9091 || exit 1
   interval: 5m00s
   timeout: 10s
    retries: 2



version: "2.1"
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - puid=998
      - pgid=100
      - TZ=Australia/Sydney
    volumes:
      - /media/USB/data/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    network_mode: "service:transmission-openvpn" # Add to the transmission-openvpn Container Network
    depends_on:
      - transmission-openvpn # Set dependency on transmission-openvpn Container
    healthcheck: # Here you will check if transmission is reachable from the Jackett container via localhost
    test: curl -f http://localhost:9091 || exit 1
            # Use this test if you protect your transmission with a username and password
            # comment the test above and un-comment the line below.
            #test: curl -f http://${TRANSMISSION_RPC_USERNAME}:${TRANSMISSION_RPC_PASSWORD}@localhost:9091 || exit 1
   interval: 5m00s
   timeout: 10s
    retries: 2
`
```

**Comment by pkishino** [comment]
If I recall correctly, you need to manually create a network (always recommended over the default anyway..)

**Reply by amrdeus2** [reply]
Thanks, I've tried that and it still won't let me deploy the stack. The current error is "failed to deploy a stack: services.prowlarr Additional property interval is not allowed". I've tried the whole ChatGPT stuff but it just slowly changes more and more things until the compose is very different.

I created a network called "Arr"


```
version: '3.3'

services:
  transmission-openvpn:
    container_name: transmission-openvpn
    cap_add:
      - NET_ADMIN
    volumes:
      - /volume1/docker/ipvanish/:/etc/openvpn/custom/
      - /media/USB/downloads:/downloads #optional
      - /media/USB/data/transmission:/config #optional?
    environment:
      - OPENVPN_PROVIDER=custom
      - OPENVPN_CONFIG=bulletVPN-AU-Sydney_1-syd01-tcp
      - OPENVPN_USERNAME=XXXXX
      - OPENVPN_PASSWORD=XXXXX
      - LOCAL_NETWORK=192.168.0.0/16
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - '9091:9091'
      - 8888:8888/tcp # HTTP proxy
      - '8989:8989' # port for sonarr
      - '7878:7878' # port for radarr
      - '9696:9696' # port for prowlarr
      - '6767:6767' # port for bazarr
    restart: always
    image: haugene/transmission-openvpn
    networks:
      - Arr

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - puid=998
      - pgid=100
      - TZ=Australia/Sydney
    volumes:
      - /media/USB/data/radarr:/config
      - /media/USB/data:/data #optional
    ports:
      - 7878:7878
    restart: unless-stopped
    network_mode: "service:transmission-openvpn" # Add to the transmission-openvpn Container Network
    depends_on:
      - transmission-openvpn # Set dependency on transmission-openvpn Container
    healthcheck: # Here you will check if transmission is reachable from the Jackett container via localhost
      test: curl -f http://localhost:9091 || exit 1
      # Use this test if you protect your transmission with a username and password
      #test: curl -f http://${TRANSMISSION_RPC_USERNAME}:${TRANSMISSION_RPC_PASSWORD}@localhost:9091 || exit 1
    interval: 5m00s
    timeout: 10s
    retries: 2
    networks:
      - Arr

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - puid=998
      - pgid=100
      - TZ=Australia/Sydney
    volumes:
      - /media/USB/data/radarr:/config
      - /media/USB/data:/data #optional
    ports:
      - 8989:8989
    restart: unless-stopped
    network_mode: "service:transmission-openvpn" # Add to the transmission-openvpn Container Network
    depends_on:
      - transmission-openvpn # Set dependency on transmission-openvpn Container
    healthcheck: # Here you will check if transmission is reachable from the Jackett container via localhost
      test: curl -f http://localhost:9091 || exit 1
      # Use this test if you protect your transmission with a username and password
      #test: curl -f http://${TRANSMISSION_RPC_USERNAME}:${TRANSMISSION_RPC_PASSWORD}@localhost:9091 || exit 1
    interval: 5m00s
    timeout: 10s
    retries: 2
    networks:
      - Arr

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - puid=998
      - pgid=100
      - TZ=Australia/Sydney
    volumes:
      - /media/USB/data/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    network_mode: "service:transmission-openvpn" # Add to the transmission-openvpn Container Network
    depends_on:
      - transmission-openvpn # Set dependency on transmission-openvpn Container
    healthcheck: # Here you will check if transmission is reachable from the Jackett container via localhost
      test: curl -f http://localhost:9091 || exit 1
      # Use this test if you protect your transmission with a username and password
      #test: curl -f http://${TRANSMISSION_RPC_USERNAME}:${TRANSMISSION_RPC_PASSWORD}@localhost:9091 || exit 1
    interval: 5m00s
    timeout: 10s
    retries: 2
    networks:
      - Arr

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=998
      - PGID=100
      - TZ=Australia/Sydney
    volumes:
      - /media/USB/data/bazarr/config:/config
      - /media/USB/Movies:/movies #optional
      - /media/USB/TV:/tv #optional
    ports:
      - 6767:6767
    restart: unless-stopped
    networks:
      - Arr

```
