### DISCUSSION TITLE
How do I use Synology Reverse Proxy with RPC?

### DISCUSSION THREAD

**Discussion by Jaxel** [haugene/docker-transmission-openvpn#2693] [Q&A]
I installed Transmission-OpenVPN on my Synology using:

```
version: "3.8"
services:
  transmission-openvpn:
    image: haugene/transmission-openvpn:latest
    container_name: transmission-openvpn
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 9091:9091
    cap_add:
      - NET_ADMIN
    environment:
      - TZ=America/New_York
      - PUID=1028
      - PGID=100
      - CREATE_TUN_DEVICE=true
      - DROP_DEFAULT_ROUTE=true
      - OPENVPN_PROVIDER=SURFSHARK
      - OPENVPN_CONFIG=us-nyc.prod.surfshark.com_tcp
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      - TRANSMISSION_RPC_USERNAME=**********
      - TRANSMISSION_RPC_PASSWORD=**********
    volumes:
      - ./config:/config
      - /volume1/Media:/media
```

I then set up a reverse proxy on my Synology mapping 443 to 9091.
![SYN-DS1520p-Synology-NAS](https://github.com/haugene/docker-transmission-openvpn/assets/3640402/cf34fc77-a88b-48f9-b3c6-3e997bb3e6ac)

I can access the web GUI of Transmission by going to https://torrents.**********.synology.me/
All this is working great and without any issues.

However, if I try to connect to Transmission using Remote GUI and the RPC, I get errors.
![Desktop-screenshot](https://github.com/haugene/docker-transmission-openvpn/assets/3640402/78f90ca0-d605-469f-9bf1-a203a2a51264)
Specifically: `error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version`

What do I need to do to fix this?
