### DISCUSSION TITLE
Transmission authentication not working when using Docker Secrets

### DISCUSSION THREAD

**Discussion by Mahir007** [haugene/docker-transmission-openvpn#2782] [Q&A]
Hi, I am having an issue whereby I cannot login to Web UI when setting a username/password via docker secrets. 
I created a container using the following compose file:
```
version: '3.3'
services:
    transmission-openvpn:
        image: haugene/transmission-openvpn
        container_name: transmission-openvpn
        cap_add:
            - NET_ADMIN
        volumes:
            - /volume1/docker/transmission-openvpn:/config
            - /volume1/docker/openvpn/provider:/etc/openvpn/custom/
            - /volume1/MagZ Plus/Media Apps/downloads:/data/downloads
        environment:
            - PUID=1030
            - PGID=100
            - TZ=Europe/London
            - OPENVPN_PROVIDER=custom
            - OPENVPN_CONFIG=london_GB
            - LOCAL_NETWORK=192.168.1.0/24
            - GLOBAL_APPLY_PERMISSIONS=false
            - TRANSMISSION_WEB_UI=transmission-web-control
            - TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=false
            - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
            - TRANSMISSION_DOWNLOAD_DIR=/data/downloads
            - TRANSMISSION_WATCH_DIR=/data/downloads/watch
            - TRANSMISSION_INCOMPLETE_DIR=/data/downloads/incomplete
        secrets:
            - openvpn_creds
            - rpc_creds
        ports:
            - '9091:9091'
        restart: always
secrets:
    openvpn_creds:
        file: /volume1/docker/openvpn/secrets/openvpn_creds
    rpc_creds:
        file: /volume1/docker/openvpn/secrets/rpc_creds
```
I can successfully navigate to the web ui, however, I just can't seem to be able to login even though I am literally copy/pasting my login info. Here is what my `rpc_creds` file looks like at the moment: 
```
naim
test$password123
```
In addition, when checking the transmission config file, I can see that it added a "\r" to the end of my username for some reason (`"rpc-username": "naim\r",`). Attempting to login with "naim\r" as my username doesn't seem to do anything though. 

So, other than resorting back to using env variables to set my user/pass, is there anything I'm missing as to why this is not working or is there a bug with this feature at the moment?

Lastly, my log file:
[transmission-openvpn.csv](https://github.com/haugene/docker-transmission-openvpn/files/13800144/transmission-openvpn.csv)
