### DISCUSSION TITLE
TRANSMISSION_DOWNLOAD_DIR environment not working

### DISCUSSION THREAD

**Discussion by aborin** [haugene/docker-transmission-openvpn#2783] [Q&A] [answered]
I am trying to align my directory structure with the intent behind [TRaSH Guide](https://trash-guides.info/Hardlinks/How-to-setup-for/Docker/). I have partial success using environment variables in my Docker compose file.  The Watch and Incomplete directories are pointing to the correct locations but the download directory seems to revert to the default "/data/completed" location.  

I cannot change the download directory using the web GUI (changes revert to /data/downloaded on save). I checked the settings.json file after shutting down the container and see the settings match my environment variables.

My compose file and the resultant settings dialog from Transmission web GUI are below.

```
version: '2.21'
services:
    transmission-openvpn:
        container_name: transmission
        cap_add:
            - NET_ADMIN
        volumes:
            - '/mnt/multimedia/torrents/:/data/torrents'
            - '/home/seedadm/.seeder/config/:/config'
        secrets:
            - openvpn_creds
        environment:
            - OPENVPN_PROVIDER=PIA
            - OPENVPN_CONFIG=ca_vancouver
            - LOCAL_NETWORK=192.168.50.0/24
            - PUID=1000
            - PGID=1000
            - UMASK=002
            - TRANSMISSION_WEB_UI=transmission-web-control
            - GLOBAL_APPLY_PERMISSIONS=false
            - WEBPROXY_ENABLED=false
            - TRANSMISSION_DOWNLOAD_DIR="/data/torrents/completed"
            - TRANSMISSION_INCOMPLETE_DIR="/data/torrents/incomplete"
            - TRANSMISSION_WATCH_DIR="/data/torrents/watch"
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '9091:9091'
        image: haugene/transmission-openvpn

secrets:
    openvpn_creds:
      file: /home/seedadm/.openvpn/openvpn_creds
```
![transmission_config](https://github.com/haugene/docker-transmission-openvpn/assets/22307102/9f38685e-5a9d-4fe3-b51a-c861049b5bd0)
