### DISCUSSION TITLE
Transmission stops downloading after a while

### DISCUSSION THREAD

**Discussion by bassmannate** [haugene/docker-transmission-openvpn#2787] [Q&A] [answered]
This has been an ongoing issue and I can't pinpoint what's going on. I start the container and everything seems fine. After a while, it just stops downloading. It could be 30 minutes. It could be a day. Everything still appears to be running but when I pull Transmission up, all files show that they're downloading from 0 of 0 connected peers. I restart the container and it starts working fine again.

There are a few miscellaneous errors in the logs. Some have to do with IPV6 being configured for OVPN but no routes are available because I don't use IPV6. 

I've also got this:

```
setting transmission port to 
localhost:9091/transmission/rpc/ responded: success
Checking port...
Error: Couldn't test port: Bad Request (400)
#######################
        SUCCESS        
#######################
Port: 
Expiration Thu Jan 11 00:00:00 UTC 2024
#######################
Entering infinite while loop
Every 15 minutes, check port status
60 day port reservation reached
Getting a new one
curl: (7) Failed to connect to 10.53.112.1 port 19999 after 15 ms: Connection refused
Thu Jan 11 00:40:24 UTC 2024: getSignature error
the has been a fatal_error
curl: (7) Failed to connect to 10.53.112.1 port 19999 after 26 ms: Connection refused
Thu Jan 11 00:40:24 UTC 2024: bindPort error
the has been a fatal_error
```
 

I've got my current compose file below. At first all this just seemed annoying but it's getting very frustrating to set something up to download and then come back to find that it stalled half way and I have to restart the container.

```
version: '3.3'
services:
    transmission-openvpn:
        cap_add:
            - NET_ADMIN
        sysctls:
            - net.ipv6.conf.all.disable_ipv6=1
        volumes:
            #- ':/data'
            - transmission_config:/config
            - /srv/dev-disk-by-uuid-06b0856b-4714-4d3a-bb20-34c586185a2b/Media/download:/downloads
            - /srv/dev-disk-by-uuid-06b0856b-4714-4d3a-bb20-34c586185a2b/Media/watch:/watch
            - /srv/dev-disk-by-uuid-06b0856b-4714-4d3a-bb20-34c586185a2b/Media:/mnt/Media
        environment:
            - OPENVPN_PROVIDER=PIA
            - OPENVPN_CONFIG=us_chicago
            - OPENVPN_USERNAME=*
            - OPENVPN_PASSWORD=*
            - LOCAL_NETWORK=192.168.1.0/24
            - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
           # - DISABLE_PORT_UPDATER=true
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '9091:9091'
        dns:
          - "1.1.1.1"
        image: haugene/transmission-openvpn
        restart: always

volumes:
  transmission_config:
```
