### DISCUSSION TITLE
Reverse proxy getting 502 Bad Gateway errors

### DISCUSSION THREAD

**Discussion by git-n-pissed** [haugene/docker-transmission-openvpn#2811] [General]
I've got a separate container running an Nginx reverse proxy.  It is using a user defined network and I've got several subdomains (all in containers) running behind it with no issues.  I've added a `/` to the end of the proxy URL as described in the docs and I've disabled UFW on the host.  I've looked at the `docker logs` output and it isn't helpful.  I don't see anywhere in the docs where the location of any other log files are.

Here is my `docker-compose.yml`:

```
version: '3.6'
networks:
  my_net:
    external: true
services:
  transmission:
    image: haugene/transmission-openvpn-proxy:5.3.1
    container_name: transmission
    cap_add:
      - NET_ADMIN
    volumes:
      - './data/:/data/:rw'
      - './config/:/config/:rw'
    environment:
      - OPENVPN_PROVIDER=NORDVPN
      - OPENVPN_USERNAME=username
      - OPENVPN_PASSWORD=password
      - OPENVPN_CONFIG=canada
      - NORDVPN_COUNTRY=CA
      - NORDVPN_CATEGORY=legacy_p2p
      - NORDVPN_PROTOCOL=tcp
      - NORDVPN_SERVER=ca111.nordvpn.com
      #- LOCAL_NETWORK=192.168.0.0/16
    logging:
      driver: json-file
      options:
        max-size: 10m
    networks:
      - my_net
    ports:
      - '9091:9091'
```

I don't know if the container is doing what it is suppoed to be doing or not.  The documentation is... confusing...  The [Supported providers](https://haugene.github.io/docker-transmission-openvpn/supported-providers/) page makes it seem like if `IPVANISH`, `NORDVPN`, `PIA`, or `VYPRVPN` are your provider, then the config will be downloaded for you or something? Best I can tell that hasn't happend.  The `config` and `data` directories mapped in `volumes` are both empty. Any pointers as to what might be happening would be appreciated.

**Update 1:**

I entered the container and ran `curl localhost:9091` as described [here](https://haugene.github.io/docker-transmission-openvpn/debug/) and I got this error `curl: (7) Failed to connect to localhost port 9091 after 0 ms: Couldn't connect to server`, so apparently transmission isn't starting with the container.  I get the same error when I remove my custom network configuration and make the `docker-compose.yml` file "stock".

**Update 2:**

I've been performing the steps listed [here](https://haugene.github.io/docker-transmission-openvpn/debug) and all of them had the expected output until I performed the steps in the [Running with a valid configuration](https://haugene.github.io/docker-transmission-openvpn/debug/#running_with_a_valid_configuration) section with my NORDVPN credentials.  Here is the output:

```
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2024/03/05 04:33:48 [emerg] 1#1: host not found in upstream "transmission" in /etc/nginx/nginx.conf:14
nginx: [emerg] host not found in upstream "transmission" in /etc/nginx/nginx.conf:14
```

**Update 3**

I was using the `haugene/transmission-openvpn-proxy:5.3.1` image, but I changed to the `haugene/transmission-openvpn:5.3.1` image and now I'm getting a new set of errors:

```
Starting container with revision: 07f5a2b9aea5028c9bb75438c1552708e91dde71
TRANSMISSION_HOME is currently set to: /config/transmission-home
Creating TUN device /dev/net/tun
Using OpenVPN provider: NORDVPN
Running with VPN_CONFIG_SOURCE auto
Provider NORDVPN has a bundled setup script. Defaulting to internal config
Executing setup script for NORDVPN
/etc/openvpn/nordvpn/..
INFO: OVPN: Checking curl installation
INFO: OVPN: DNS resolution ok
ERROR: ERROR: OVPN: cannot ping https://downloads.nordcdn.com/configs/files, network or internet unavailable. Cannot download NORDVPN configuration files
```
