### DISCUSSION TITLE
Support TrguiNG for Transmission Web UI

### DISCUSSION THREAD

**Discussion by mytelegrambot** [haugene/docker-transmission-openvpn#2826] [Ideas]
https://github.com/openscopeproject/TrguiNG/wiki

Implement support for the TrguiNG for Transmission web UI.
Thank you for all your work on this image.

**Comment by pkishino** [comment]
I suggest you either create a PR or suggest it to the owner of that UI to create one so we can include it here

**Comment by Tropicananass** [comment]
Hey, for information I did a pull request for this here https://github.com/haugene/docker-transmission-openvpn/pull/2995

**Comment by dandanarsk** [comment]
Here is how to add it as "addon"
1. Create a folder to hold the UI files  /volume1/docker/transmission/trguing-web
2. Download the latest web zip from GitHub releases trguing-web-vX.X.X.zip
3. Extract zip into the folder trguing-web
4. Update your docker-compose
```yaml
services:
  transmission-openvpn:
    image: haugene/transmission-openvpn
    cap_add:
      - NET_ADMIN
    volumes:
      - '/volume1/docker/transmission/data:/data'
      - '/volume1/docker/transmission/config:/config'
      - '/volume1/docker/transmission/trguing-web:/trguing-web'   # ← add this
    environment:
      - OPENVPN_PROVIDER=...
      - OPENVPN_CONFIG=...
      - OPENVPN_USERNAME=...
      - OPENVPN_PASSWORD=...
      - LOCAL_NETWORK=192.168.1.0/24
      - TRANSMISSION_WEB_HOME=/trguing-web                        # ← add this
    ports:
      - 9091:9091
```
5.  Recreate the container
