### DISCUSSION TITLE
Transmission just doesn't start

### DISCUSSION THREAD

**Discussion by mooyg** [haugene/docker-transmission-openvpn#2834] [Q&A]
Hey, I am trying to get transmission up and running with `PUREVPN` as a provider
```
# Torrent client
  transmission-openvpn:
    image: haugene/transmission-openvpn
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    volumes:
      - /mnt/media/services/transmission/config:/config
      - /mnt/media/services/transmission/data:/data
    logging:
      driver: json-file
      options:
        max-size: 10m
    environment:
      - OPENVPN_PROVIDER=PUREVPN
      - OPENVPN_USERNAME=
      - OPENVPN_PASSWORD=
      - LOCAL_NETWORK=192.168.29.0/24
    ports:
      - 9091:9091
      - 19999:19999
```
this is my config as of now but if I check logs I don't see that transmission is running. The port is exposed but can't connect to it as well since transmission just doesn't get up and running
