### DISCUSSION TITLE
When rebooting system, transmission container starts, but proxy doesn't

### DISCUSSION THREAD

**Discussion by bassmadrigal** [haugene/docker-transmission-openvpn#2844] [Q&A] [answered]
I have the docker compose conf file pasted at the end of this post for transmission and its proxy. In it, (I think) I have specified for both transmission-openvpn and transmission-openvpn-proxy to restart unless-stopped.

However, when my system is rebooted, transmission-openvpn restarts fine, but transmission-openvpn-proxy does not.

I am relatively new to docker, so I might be missing something obvious. Maybe my conf file is put together incorrectly or there's some other configuration issue. It doesn't seem like it is a docker startup issue itself since transmission-openvpn starts up fine, so it seems to be an issue with this specific conf file.

I will note that I added the proxy section about 5 months after I created the initial config file. I'm not sure if I'm supposed to run a command to update some internal docker config file with the new settings.

Any help would be appreciated. (If not, it wouldn't be that hard to just add a command to my startup to restart these containers using the conf file, but I would love the proxy startup to be automatic like the transmission container itself).

```
version: '3.3'
services:
    transmission-openvpn:
        cap_add:
            - NET_ADMIN
        volumes:
            - '/share/gothrough/torrent:/data'
            - '/home/jbhansen/.docker-config/transmission:/config'
        environment:
            - OPENVPN_PROVIDER=PIA
            - OPENVPN_CONFIG=ca_vancouver
            - OPENVPN_USERNAME=username
            - OPENVPN_PASSWORD=password
            - LOCAL_NETWORK=10.0.0.0/24
            - TRANSMISSION_DOWNLOAD_DIR=/data/completed
            - TRANSMISSION_INCOMPLETE_DIR=/data/working
            - PUID=1000
            - PGID=100
            - CREATE_TUN_DEVICE=true
            - TZ=America/Los_Angeles
            - DROP_DEFAULT_ROUTE=true
            - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60 --auth-nocache
            - TRANSMISSION_RPC_USERNAME=username
            - TRANSMISSION_RPC_PASSWORD=password
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '1220:9091'
        restart: unless-stopped
        image: haugene/transmission-openvpn

    proxy:
        image: haugene/transmission-openvpn-proxy
        links:
            - transmission-openvpn:transmission
        ports:
            - 1221:8080
        restart: unless-stopped
```
