### DISCUSSION TITLE
Container not starting when using local ovpn file in OMV

### DISCUSSION THREAD

**Discussion by gavinmerry** [haugene/docker-transmission-openvpn#2855] [Q&A]
Hi,

I am currently trying to run this docker container within OMV 7.1.1-1 (Sandworm). I have my own VPN set up using OpenVPN and therefore have my own .ovpn config file with private keys so I need to keep it local. I have followed the guidance here - (https://github.com/haugene/vpn-configs-contrib/blob/main/CONTRIBUTING.md) and it does not seem to work. The container starts up and then stops straight away. 

Please find below my current compose file and the error log:

**Compose file**

```
services:
    transmission-openvpn:
        cap_add:
            - NET_ADMIN
        volumes:
            - 'storage/path:/data'
            - '/home/transmission-openvpn:/config'
            - './vpn_config.ovpn:/config/vpn-configs-contrib/openvpn/local/vpn_config.ovpn:ro'
        environment:
            - "OPENVPN_PROVIDER=local"
            - "OPENVPN_CONFIG=vpn_config"
            - LOCAL_NETWORK=192.168.0.0/24
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '9091:9091'
        image: haugene/transmission-openvpn

```

**Log**

```
Starting container with revision: 07f5a2b9aea5028c9bb75438c1552708e91dde71
TRANSMISSION_HOME is currently set to: /config/transmission-home
Creating TUN device /dev/net/tun
Using OpenVPN provider: LOCAL
Running with VPN_CONFIG_SOURCE auto
No bundled config script found for LOCAL. Defaulting to external config
Will get configs from https://github.com/haugene/vpn-configs-contrib.git
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

The error appears to say that it cannot find the bundle of ovpn configs in LOCAL, which is the directory I specified using the above guide. I'm not sure why the container isn't picking up on the local file and instead trying to download ones from the github page. I have done a bunch of googling and can't seem to find anyone else with a similar issue or a guide on how to do it locally that is different to the specified documentation.

Just to add, my config file and router works fine as other devices on my internal network have used it without issue and can connect to my vpn.

Has anyone managed to get this to work?

Many thanks in advance :)
