### DISCUSSION TITLE
Problems launching transmission docker

### DISCUSSION THREAD

**Discussion by Fagerinfoco** [haugene/docker-transmission-openvpn#2878] [Q&A]
I am having problems launching transmission. I have my secrets set in the main compose

`########################### SECRETS
secrets:
  trans_pw:
    file: $DOCKERDIR/secrets/trans_pw
  trans_un:
    file: $DOCKERDIR/secrets/trans_un
  trust_unpw:
    file: $DOCKERDIR/secrets/trust_unpw
`
then it includes my transmission yml

```
services:
# Transmission with VPN – Bittorrent Downloader
  transmission-vpn:
    image: haugene/transmission-openvpn
    container_name: transmission-vpn
    restart: no
    ports:
    - "9009:9091"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - ${DOCKERDIR}/appdata/transmission/trustzone/:/etc/openvpn/custom/
      - ${DOCKERDIR}/shared:/shared
      - /data/torrents:/data
      - /data/completed:/data/completed

    dns:
      - 109.236.87.2
      - 23.237.56.98

    environment:
      OPENVPN_PROVIDER: TRUSTZONE
      OPENVPN_USERNAME_FILE: /run/secrets/trust_unpw
      TRANSMISSION_RPC_PASSWORD_FILE: /run/secrets/trans_pw
      TRANSMISSION_RPC_USERNAME_FILE: /run/secrets/trans_un
      GITHUB_CONFIG_SOURCE_REPO: <<my_repo (obviously not the real name)>>/vpn-configs-contrib
      OPENVPN_CONFIG: tcp/Trust.Zone-United-States-Colorado
      OPENVPN_OPTS: --inactive 3600 --ping 10 --ping-exit 60
      LOCAL_NETWORK: 192.168.0.0/24
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      TRANSMISSION_RPC_AUTHENTICATION_REQUIRED: true
      TRANSMISSION_RPC_HOST_WHITELIST: "127.0.0.1,192.168.*.*"
      TRANSMISSION_UMASK: 002
      TRANSMISSION_RATIO_LIMIT: 1
      TRANSMISSION_RATIO_LIMIT_ENABLED: true

    secrets:
      - trans_pw
      - trans_un
      - trust_unpw

```

I have my trustzone/openvpn username and password in one file. username on the first line, password on the second.

when i try to start up the container, the message i see in portainer logs is:
2024-09-12T23:17:33.054232292Z OpenVPN credentials not set. Exiting

What am i doing wrong here?
