### DISCUSSION TITLE
OpenVPN and Transmission Container Issue with CyberGhost VPN

### DISCUSSION THREAD

**Discussion by alisa0109** [haugene/docker-transmission-openvpn#2879] [Q&A]
Hi, I need help setting up OpenVPN and Transmission on my system. I'm using a VPN from CyberGhost, but I don't know how to properly configure OpenVPN and Transmission to work with this VPN. Can you help me with this?
Here is my current configuration:

```
version: '3.3'
services:
    transmission-openvpn:
        cap_add:
            - NET_ADMIN
        volumes:
            - /srv/dev-disk-by-uuid-8ca2091b-68f6-4a04-9231-ec170b0bbb32/torrent/:/data     'downloads folder'
            - /srv/dev-disk-by-uuid-8ca2091b-68f6-4a04-9231-ec170b0bbb32/torrent/config:/config    
            - /srv/dev-disk-by-uuid-8ca2091b-68f6-4a04-9231-ec170b0bbb32/torrent/custom/:/etc/openvpn/custom/   'vpn custom configuration'

        environment:
            - OPENVPN_PROVIDER=custom
            - OPENVPN_CONFIG=openvpn    'name file vpn config'
            - OPENVPN_USERNAME=login*** 'login from  vpn'
            - OPENVPN_PASSWORD=password**** ' password from vpn'
            - LOCAL_NETWORK=192.168.1.0/24
            - PUID=1001  # Replace with your actual PUID
            - PGID=100  # Replace with your actual PGID
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - 9091:9091
        image: haugene/transmission-openvpn
```

     

I have the following files in the /srv/dev-disk-by-uuid-8ca2091b-68f6-4a04-9231-ec170b0bbb32/torrent/custom/ directory: ca.crt, client.crt, client.key, and openvpn.ovpn. These are the configuration files provided by my VPN provider, CyberGhost. I followed the instructions for setting up the custom provider configuration from the official documentation: https://haugene.github.io/docker-transmission-openvpn/supported-providers/

After creating the container, I receive the following logs and the container fails to start. Here's the relevant part of the logs:
Starting container with revision: 07f5a2b9aea5028c9bb75438c1552708e91dde71

> TRANSMISSION_HOME is currently set to: /config/transmission-home
> Creating TUN device /dev/net/tun
> Using OpenVPN provider: CUSTOM
> Running with VPN_CONFIG_SOURCE auto
> CUSTOM provider specified but not using default.ovpn, will try to find a valid config mounted to /etc/openvpn/custom
> Starting OpenVPN using config openvpn.ovpn
> Modifying /etc/openvpn/custom/openvpn.ovpn for best behaviour in this container
> Modification: Point auth-user-pass option to the username/password file
> Modification: Change ca certificate path
> Modification: Change ping options
> Modification: Update/set resolv-retry to 15 seconds
> Modification: Change tls-crypt keyfile path
> Modification: Set output verbosity to 3
> Modification: Remap SIGUSR1 signal to SIGTERM, avoid OpenVPN restart loop
> Modification: Updating status for config failure detection
> Setting OpenVPN credentials...
> adding route to local network 192.168.1.0/24 via 172.21.0.1 dev eth0
> 2024-09-18 14:01:29 DEPRECATED OPTION: ncp-disable. Disabling cipher negotiation is a deprecated debug feature that will be removed in OpenVPN 2.6
> 2024-09-18 14:01:29 DEPRECATED OPTION: --cipher set to 'AES-256-CBC' but missing in --data-ciphers (AES-256-GCM:AES-128-GCM). Future OpenVPN version will ignore --cipher for cipher negotiations. Add 'AES-256-CBC' to --data-ciphers or change --cipher 'AES-256-CBC' to --data-ciphers-fallback 'AES-256-CBC' to silence this warning.
> Options error: --cert fails with 'client.crt': No such file or directory (errno=2)
> 2024-09-18 14:01:29 WARNING: cannot stat file 'client.key': No such file or directory (errno=2)
> Options error: --key fails with 'client.key': No such file or directory (errno=2)
> Options error: Please correct these errors.
> Use --help for more information.

...

> Options error: --cert fails with 'client.crt': No such file or directory (errno=2)
> 2024-09-18 14:01:29 WARNING: cannot stat file 'client.key': No such file or directory (errno=2)
> Options error: --key fails with 'client.key': No such file or directory (errno=2)
> Options error: Please correct these errors.

As you can see, the container is unable to find the client.crt and client.key files in the specified directory /etc/openvpn/custom. However, I'm certain that these files are present in that directory, as I had previously placed them there. What could be the cause of this error?"

Thank you in advance to anyone who can help me resolve this issue. I would greatly appreciate any guidance or advice on how to fix the problem and get my container up and running with OpenVPN and Transmission.
