### DISCUSSION TITLE
Listening ports closed

### DISCUSSION THREAD

**Discussion by ibwaheemi** [haugene/docker-transmission-openvpn#2912] [General]
edit: my level of understanding of docker is basic but computer literacy overall is ok

system 5.10.60-qnap using portainer GUI through QNAPs container station

ive done more tinkering with this than a student mechanic on his first build

i cant get the listening port to work.  I have forwarded the port to the container on my router to no avail.
i have also tried adding it to my docker compose

i tried adding this   - '51413:51413/udp' but it didnt work

instead should i be using TRANSMISSION_PEER_PORT_RANDOM_HIGH and TRANSMISSION_PEER_PORT_RANDOM_LOW and port forward the range from my router?

.........
sidenote: is my compose file ok? is OVERRIDE_DNS_1 and 2 a mistake? should i delete it or put my pi-hole IPs in there instead

```
version: '3.3'
services:
    transmission-openvpn:
        cap_add:
            - NET_ADMIN
        volumes:
            - '/share/CACHEDEV1_DATA/Container/Transmission-openvpn/data/:/data'
            - '/share/CACHEDEV1_DATA/Container/Transmission-openvpn/config/:/config'
            - '/share/CACHEDEV1_DATA/Public/downloads:/data/completed'
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=GMT #timezone
            - OPENVPN_PROVIDER=protonvpn
            - OPENVPN_CONFIG=nl-free-34.protonvpn.udp #name of your ovpn file
            - OPENVPN_USERNAME=Cjixxxxxxxxxxxxxxxis
            - OPENVPN_PASSWORD=eQgYxxxxxxxxxxxxxxxxxxxxxxE8
            - LOCAL_NETWORK=192.168.3.0/24
            - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true 
            - TRANSMISSION_RPC_PASSWORD=qnap
            - TRANSMISSION_RPC_USERNAME=qnap
            - OVERRIDE_DNS_1=1.1.1.1
            - OVERRIDE_DNS_2=1.0.0.1
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '9091:9091'
            - '51413:51413/udp'
        image: haugene/transmission-openvpn
```
