### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by kunterbunth** [haugene/docker-transmission-openvpn#1015]
I am very sorry, if this is a dumb question..
I've set up two containers with the docker-compose file provided here. when i start the proxy container, it starts the transmission_vpn container too. so far so good. the containers keep running, but if i try to connect to the rpc via the proxy container (http://192.168.x.y:8080/transmission/rpc/) i get a 502 Bad Gateway Error in my browser/transmission-remote client.
is this a bad transmission config or a bad container setup?

my docker-compose.yml
```
transmission:
  image: haugene/transmission-openvpn:latest-armhf
  cap_add:
    - NET_ADMIN
  devices:
    - "/dev/net/tun"
  restart: always
  ports:
    - "9091:9091"
    - "8888:8888"
  dns:
    - 8.8.8.8
    - 8.8.4.4
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /home/pi/Downloads/:/data
  environment:
    - OPENVPN_PROVIDER=PUREVPN
    - OPENVPN_USERNAME=purevpn0sxxxxxxx
    - OPENVPN_PASSWORD=xxxxxxxx
    - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
    - TRANSMISSION_RPC_ENABLED=true
    - TRANSMISSION_RPC_PORT=9091
    - TRANSMISSION_RPC_WHITELIST_ENABLED=true
    - TRANSMISSION_RPC_WHITELIST=192.168.*.*,127.0.0.1
    - TRANSMISSION_WATCH_DIR=/data/watch
    - TRANSMISSION_WATCH_DIR_ENABLED=true
proxy:
  image: haugene/transmission-openvpn-proxy:latest-armhf
  links:
    - transmission
  ports:
    - "8080:8080"
  volumes:
    - /etc/localtime:/etc/localtime:ro

```

I start the containers with 
`docker-compose up -d proxy`

If i stop the containers, my client says "Couldn't connect", if they are running, it says "502...", so i can definitely reach SOMETHING...

Thanks.
