### ISSUE TITLE
Container running but not transmission

### ISSUE THREAD

**Issue by Xaelias** [haugene/docker-transmission-openvpn#1035]
**Describe the problem**
After some time, the container keeps running, the tunnel is seemingly up, but transmission itself is not running. If I restart the container (kill the openvpn process) everything comes back up normally.

**Add your docker run command**
I'm in kubernetes. Here is the config file:
```
alesieur@OmbreTerre:/volume1/k8s/media/Transmission$ cat transmission.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: transmission
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        k8s-app: transmission
    spec:
      containers:
        - name: transmission
          image: haugene/transmission-openvpn:latest
          securityContext:
            privileged: true
          env:
          - name: OPENVPN_PROVIDER
            value: 'NORDVPN'
          - name: OPENVPN_USERNAME
            valueFrom:
              secretKeyRef:
                name: nordvpn
                key: username
          - name: OPENVPN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: nordvpn
                key: password
          - name: LOCAL_NETWORK
            value: '10.0.0.0/8'
          - name: GLOBAL_APPLY_PERMISSIONS
            value: 'false'
          - name: NORDVPN_COUNTRY
            value: 'US'
          - name: NORDVPN_CATEGORY
            value: 'legacy_p2p'
          - name: NORDVPN_PROTOCOL
            value: 'tcp'
          - name: OPENVPN_OPTS
            value: '--inactive 3600 --ping 10 --ping-exit 60'
          - name: TRANSMISSION_DOWNLOAD_DIR
            value: '/path/to/dl'
          - name: TRANSMISSION_INCOMPLETE_DIR
            value: '/path/to/.incomplete'
          - name: TRANSMISSION_INCOMPLETE_DIR_ENABLED
            value: 'true'
          - name: TRANSMISSION_RPC_AUTHENTICATION_REQUIRED
            value: 'true'
          - name: TRANSMISSION_RPC_USERNAME
            valueFrom:
              secretKeyRef:
                name: transmission
                key: username
          - name: TRANSMISSION_RPC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: transmission
                key: password
          - name: TRANSMISSION_RPC_WHITELIST
            value: '127.0.0.1,10.*.*.*'
          - name: TRANSMISSION_RPC_WHITELIST_ENABLED
            value: 'true'
          - name: TRANSMISSION_SCRIPT_TORRENT_DONE_ENABLED
            value: 'true'
          - name: TRANSMISSION_SCRIPT_TORRENT_DONE_FILENAME
            value: '/path/to/script.sh'
          - name: TRANSMISSION_UTP_ENABLED
            value: 'false'
          - name: TRANSMISSION_CACHE_SIZE_MB
            value: '5120'
          - name: TRANSMISSION_ENCRYPTION
            value: '2'
          - name: TRANSMISSION_PEER_PORT_RANDOM_ON_START
            value: 'true'
          - name: TRANSMISSION_PREALLOCATION
            value: '1'
          - name: PUID
            value: '1026'
          - name: PGID
            value: '100'
          resources:
            limits:
              cpu: 6
              memory: 20Gi
          volumeMounts:
            - name: <name>
              mountPath: /path/
            - name: config
              mountPath: /data/transmission-home/
      volumes:
        - name: flexget
          nfs:
            server: <server>
            path: <path>
        - name: config
          nfs:
            server: <server>
            path: /volume1/Configs/Transmission/
---
apiVersion: v1
kind: Service
metadata:
  name: transmission
  namespace: media
  labels:
    k8s-app: transmission
spec:
  ports:
    - name: http
      port: 80
      targetPort: 9091
      protocol: TCP
  selector:
    k8s-app: transmission
```

**Logs**
```
 Using OpenVPN provider: NORDVPN
2020-01-31 14:10:21 Checking curl installation
2020-01-31 14:10:21 Removing existing configs
2020-01-31 14:10:21 Selecting the best server...
2020-01-31 14:10:21 Searching for technology: openvpn_tcp
2020-01-31 14:10:21 Best server : us3263.nordvpn.com
2020-01-31 14:10:21 Downloading config: default.ovpn
2020-01-31 14:10:21 Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_tcp/servers/us3263.nordvpn.com.tcp.ovpn
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2822  100  2822    0     0   5414      0 --:--:-- --:--:-- --:--:--  5416
2020-01-31 14:10:21 Selecting the best server...
2020-01-31 14:10:21 Searching for country : US (228)
2020-01-31 14:10:21 Searching for technology: openvpn_tcp
2020-01-31 14:10:21 Best server : us3263.nordvpn.com
2020-01-31 14:10:21 Downloading config: us3263.nordvpn.com.ovpn
2020-01-31 14:10:21 Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_tcp/servers/us3263.nordvpn.com.tcp.ovpn
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2822  100  2822    0     0  21410      0 --:--:-- --:--:-- --:--:-- 21541
2020-01-31 14:10:21 Checking line endings
2020-01-31 14:10:21 Updating configs for docker-transmission-openvpn
Starting OpenVPN using config us3263.nordvpn.com.ovpn
Setting OPENVPN credentials...
adding route to local network 10.0.0.0/8 via 10.88.0.1 dev eth0
RTNETLINK answers: File exists
Fri Jan 31 14:10:23 2020 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 19 2019
Fri Jan 31 14:10:23 2020 library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08
Fri Jan 31 14:10:23 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Fri Jan 31 14:10:23 2020 NOTE: --fast-io is disabled since we are not using UDP
Fri Jan 31 14:10:23 2020 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
Fri Jan 31 14:10:23 2020 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
Fri Jan 31 14:10:23 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]181.215.110.244:443
Fri Jan 31 14:10:23 2020 Socket Buffers: R=[131072->131072] S=[16384->16384]
Fri Jan 31 14:10:23 2020 Attempting to establish TCP connection with [AF_INET]181.215.110.244:443 [nonblock]
Fri Jan 31 14:10:24 2020 TCP connection established with [AF_INET]181.215.110.244:443
Fri Jan 31 14:10:24 2020 TCP_CLIENT link local: (not bound)
Fri Jan 31 14:10:24 2020 TCP_CLIENT link remote: [AF_INET]181.215.110.244:443
Fri Jan 31 14:10:24 2020 TLS: Initial packet from [AF_INET]181.215.110.244:443, sid=c4392261 b9719aea
Fri Jan 31 14:10:24 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Fri Jan 31 14:10:24 2020 VERIFY OK: depth=2, C=PA, O=NordVPN, CN=NordVPN Root CA
Fri Jan 31 14:10:24 2020 VERIFY OK: depth=1, C=PA, O=NordVPN, CN=NordVPN CA4
Fri Jan 31 14:10:24 2020 VERIFY KU OK
Fri Jan 31 14:10:24 2020 Validating certificate extended key usage
Fri Jan 31 14:10:24 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Fri Jan 31 14:10:24 2020 VERIFY EKU OK
Fri Jan 31 14:10:24 2020 VERIFY OK: depth=0, CN=us3263.nordvpn.com
Fri Jan 31 14:10:24 2020 Control Channel: TLSv1.2, cipher TLSv1/SSLv3 ECDHE-RSA-AES256-GCM-SHA384, 4096 bit RSA
Fri Jan 31 14:10:24 2020 [us3263.nordvpn.com] Peer Connection Initiated with [AF_INET]181.215.110.244:443
Fri Jan 31 14:10:25 2020 SENT CONTROL [us3263.nordvpn.com]: 'PUSH_REQUEST' (status=1)
Fri Jan 31 14:10:25 2020 PUSH: Received control message: 'PUSH_REPLY,redirect-gateway def1,dhcp-option DNS 103.86.96.100,dhcp-option DNS 103.86.99.100,sndbuf 524288,rcvbuf 524288,explicit-exit-notify,comp-lzo no,route-gateway 10.7.2.1,topology subnet,ping 60,ping-restart 180,ifconfig 10.7.2.3 255.255.255.0,peer-id 0,cipher AES-256-GCM'
Fri Jan 31 14:10:25 2020 OPTIONS IMPORT: timers and/or timeouts modified
Fri Jan 31 14:10:25 2020 OPTIONS IMPORT: --explicit-exit-notify can only be used with --proto udp
Fri Jan 31 14:10:25 2020 OPTIONS IMPORT: compression parms modified
Fri Jan 31 14:10:25 2020 OPTIONS IMPORT: --sndbuf/--rcvbuf options modified
Fri Jan 31 14:10:25 2020 Socket Buffers: R=[131072->425984] S=[87040->425984]
Fri Jan 31 14:10:25 2020 OPTIONS IMPORT: --ifconfig/up options modified
Fri Jan 31 14:10:25 2020 OPTIONS IMPORT: route options modified
Fri Jan 31 14:10:25 2020 OPTIONS IMPORT: route-related options modified
Fri Jan 31 14:10:25 2020 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
Fri Jan 31 14:10:25 2020 OPTIONS IMPORT: peer-id set
Fri Jan 31 14:10:25 2020 OPTIONS IMPORT: adjusting link_mtu to 1659
Fri Jan 31 14:10:25 2020 OPTIONS IMPORT: data channel crypto options modified
Fri Jan 31 14:10:25 2020 Data Channel: using negotiated cipher 'AES-256-GCM'
Fri Jan 31 14:10:25 2020 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Fri Jan 31 14:10:25 2020 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Fri Jan 31 14:10:25 2020 ROUTE_GATEWAY 10.88.0.1/255.255.0.0 IFACE=eth0 HWADDR=5a:ac:12:cb:3c:a0
Fri Jan 31 14:10:25 2020 TUN/TAP device tun0 opened
Fri Jan 31 14:10:25 2020 TUN/TAP TX queue length set to 100
Fri Jan 31 14:10:25 2020 /sbin/ip link set dev tun0 up mtu 1500
Fri Jan 31 14:10:25 2020 /sbin/ip addr add dev tun0 10.7.2.3/24 broadcast 10.7.2.255
Fri Jan 31 14:10:25 2020 /etc/openvpn/tunnelUp.sh tun0 1500 1587 10.7.2.3 255.255.255.0 init
Up script executed with tun0 1500 1587 10.7.2.3 255.255.255.0 init
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.7.2.3
Generating transmission settings.json from env variables
sed'ing True to true
Enforcing ownership on transmission config directories
chown: changing ownership of '***': Operation not permitted
[...]
chown: changing ownership of '***': Operation not permitted
Applying permissions to transmission config directories
chmod: changing permissions of '/data/transmission-home': Operation not permitted

-------------------------------------
Transmission will run as
-------------------------------------
User name:   abc
User uid:    1026
User gid:    100
-------------------------------------

STARTING TRANSMISSION
NO PORT UPDATER FOR THIS PROVIDER
Transmission startup script complete.
Fri Jan 31 14:10:26 2020 /sbin/ip route add 181.215.110.244/32 via 10.88.0.1
Fri Jan 31 14:10:26 2020 /sbin/ip route add 0.0.0.0/1 via 10.7.2.1
Fri Jan 31 14:10:26 2020 /sbin/ip route add 128.0.0.0/1 via 10.7.2.1
Fri Jan 31 14:10:26 2020 Initialization Sequence Completed
Fri Jan 31 15:10:24 2020 VERIFY OK: depth=2, C=PA, O=NordVPN, CN=NordVPN Root CA
Fri Jan 31 15:10:24 2020 VERIFY OK: depth=1, C=PA, O=NordVPN, CN=NordVPN CA4
Fri Jan 31 15:10:24 2020 VERIFY KU OK
Fri Jan 31 15:10:24 2020 Validating certificate extended key usage
Fri Jan 31 15:10:24 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Fri Jan 31 15:10:24 2020 VERIFY EKU OK
Fri Jan 31 15:10:24 2020 VERIFY OK: depth=0, CN=us3263.nordvpn.com
Fri Jan 31 15:10:24 2020 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Fri Jan 31 15:10:24 2020 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Fri Jan 31 15:10:24 2020 Control Channel: TLSv1.2, cipher TLSv1/SSLv3 ECDHE-RSA-AES256-GCM-SHA384, 4096 bit RSA
Fri Jan 31 16:10:24 2020 TLS: tls_process: killed expiring key
Fri Jan 31 16:10:24 2020 VERIFY OK: depth=2, C=PA, O=NordVPN, CN=NordVPN Root CA
Fri Jan 31 16:10:24 2020 VERIFY OK: depth=1, C=PA, O=NordVPN, CN=NordVPN CA4
Fri Jan 31 16:10:24 2020 VERIFY KU OK
Fri Jan 31 16:10:24 2020 Validating certificate extended key usage
Fri Jan 31 16:10:24 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Fri Jan 31 16:10:24 2020 VERIFY EKU OK
Fri Jan 31 16:10:24 2020 VERIFY OK: depth=0, CN=us3263.nordvpn.com
Fri Jan 31 16:10:24 2020 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Fri Jan 31 16:10:24 2020 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Fri Jan 31 16:10:24 2020 Control Channel: TLSv1.2, cipher TLSv1/SSLv3 ECDHE-RSA-AES256-GCM-SHA384, 4096 bit RSA
Fri Jan 31 17:10:24 2020 TLS: tls_process: killed expiring key
Fri Jan 31 17:10:24 2020 VERIFY OK: depth=2, C=PA, O=NordVPN, CN=NordVPN Root CA
Fri Jan 31 17:10:24 2020 VERIFY OK: depth=1, C=PA, O=NordVPN, CN=NordVPN CA4
Fri Jan 31 17:10:24 2020 VERIFY KU OK
Fri Jan 31 17:10:24 2020 Validating certificate extended key usage
Fri Jan 31 17:10:24 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Fri Jan 31 17:10:24 2020 VERIFY EKU OK
Fri Jan 31 17:10:24 2020 VERIFY OK: depth=0, CN=us3263.nordvpn.com
Fri Jan 31 17:10:24 2020 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Fri Jan 31 17:10:24 2020 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Fri Jan 31 17:10:24 2020 Control Channel: TLSv1.2, cipher TLSv1/SSLv3 ECDHE-RSA-AES256-GCM-SHA384, 4096 bit RSA
Fri Jan 31 18:10:24 2020 TLS: tls_process: killed expiring key
Fri Jan 31 18:10:24 2020 VERIFY OK: depth=2, C=PA, O=NordVPN, CN=NordVPN Root CA
Fri Jan 31 18:10:24 2020 VERIFY OK: depth=1, C=PA, O=NordVPN, CN=NordVPN CA4
Fri Jan 31 18:10:24 2020 VERIFY KU OK
Fri Jan 31 18:10:24 2020 Validating certificate extended key usage
Fri Jan 31 18:10:24 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Fri Jan 31 18:10:24 2020 VERIFY EKU OK
Fri Jan 31 18:10:24 2020 VERIFY OK: depth=0, CN=us3263.nordvpn.com
Fri Jan 31 18:10:24 2020 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Fri Jan 31 18:10:24 2020 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Fri Jan 31 18:10:24 2020 Control Channel: TLSv1.2, cipher TLSv1/SSLv3 ECDHE-RSA-AES256-GCM-SHA384, 4096 bit RSA
Fri Jan 31 19:10:24 2020 TLS: tls_process: killed expiring key
Fri Jan 31 19:10:25 2020 VERIFY OK: depth=2, C=PA, O=NordVPN, CN=NordVPN Root CA
Fri Jan 31 19:10:25 2020 VERIFY OK: depth=1, C=PA, O=NordVPN, CN=NordVPN CA4
Fri Jan 31 19:10:25 2020 VERIFY KU OK
Fri Jan 31 19:10:25 2020 Validating certificate extended key usage
Fri Jan 31 19:10:25 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Fri Jan 31 19:10:25 2020 VERIFY EKU OK
Fri Jan 31 19:10:25 2020 VERIFY OK: depth=0, CN=us3263.nordvpn.com
Fri Jan 31 19:10:25 2020 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Fri Jan 31 19:10:25 2020 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Fri Jan 31 19:10:25 2020 Control Channel: TLSv1.2, cipher TLSv1/SSLv3 ECDHE-RSA-AES256-GCM-SHA384, 4096 bit RSA
```
I know there are a bunch of chown being denied, but that's a side effect of NFS. I know for a fact it works as is. But the user the script runs as can't change ownership on these files. The transmission process does have all permissions.

**Host system:**
kubernetes on custom hardware.

Logs from transmission itself don't have anything useful I could spot.

**Comment by bcrens7** [comment]
did you ever figure this out? same issue i'm having.

**Comment by Xaelias** [comment]
Looking at dmsg I'm having some amount of segfaulting happening. The container is not configured to die when transmission crashes (or try and restart it).
So now I have two things to consider. Are the memory errors I'm seeing a code issue, or is some of my memory bad? I can't take that machine offline for a memtest right now so...
The other is trying to find a way for the container to either restart when transmission dies, or crash and burn. I haven't found anything great just yet.

**Comment by digitalrain101** [comment]
I'm having the same issue, anyone find a solution? Minus the k8s though, I'm using Portainer. I tried using the proxy container found in the documentation under "access" but still could not get it going.

**Comment by pkishino** [comment]
Looking at the log above I can see permission problems.. try running container as root just to check if it works, then we can check user

**Comment by pkishino** [comment]
@digitalrain101  any logs?

**Comment by Xaelias** [comment]
> Looking at the log above I can see permission problems.. try running container as root just to check if it works, then we can check user

If you were talking to me, as stated this is not a file permissions issue. I mean there is one, but it's not in anyway preventing transmission from working.

**Comment by digitalrain101** [comment]
> @digitalrain101 any logs?

As requested:

`Using OpenVPN provider: NORDVPN,
2020-04-22 21:53:01 Checking curl installation,
2020-04-22 21:53:01 Removing existing configs,
2020-04-22 21:53:01 Selecting the best server...,
2020-04-22 21:53:01 Searching for technology: openvpn_tcp,
2020-04-22 21:53:01 Best server : us3241.nordvpn.com,
2020-04-22 21:53:01 Downloading config: default.ovpn,
2020-04-22 21:53:01 Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_tcp/servers/us3241.nordvpn.com.tcp.ovpn,
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current,
                                 Dload  Upload   Total   Spent    Left  Speed,

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  2822  100  2822    0     0   5689      0 --:--:-- --:--:-- --:--:--  5678
100  2822  100  2822    0     0   5689      0 --:--:-- --:--:-- --:--:--  5678,
2020-04-22 21:53:01 Selecting the best server...,
2020-04-22 21:53:01 Searching for country : US (228),
2020-04-22 21:53:01 Searching for technology: openvpn_tcp,
2020-04-22 21:53:01 Best server : us3241.nordvpn.com,
2020-04-22 21:53:01 Downloading config: us3241.nordvpn.com.ovpn,
2020-04-22 21:53:01 Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_tcp/servers/us3241.nordvpn.com.tcp.ovpn,
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current,
                                 Dload  Upload   Total   Spent    Left  Speed,

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  2822  100  2822    0     0  11333      0 --:--:-- --:--:-- --:--:-- 11333,
2020-04-22 21:53:01 Checking line endings,
2020-04-22 21:53:01 Updating configs for docker-transmission-openvpn,
Starting OpenVPN using config us3241.nordvpn.com.ovpn,
Setting OPENVPN credentials...,
adding route to local network 10.0.10.0/26 via 172.17.0.1 dev eth0,
Wed Apr 22 21:53:04 2020 OpenVPN 2.4.4 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on May 14 2019,
Wed Apr 22 21:53:04 2020 library versions: OpenSSL 1.1.1  11 Sep 2018, LZO 2.08,
Wed Apr 22 21:53:04 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts,
Wed Apr 22 21:53:04 2020 NOTE: --fast-io is disabled since we are not using UDP,
Wed Apr 22 21:53:04 2020 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication,
Wed Apr 22 21:53:04 2020 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication,
Wed Apr 22 21:53:04 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]184.170.240.105:443,
Wed Apr 22 21:53:04 2020 Socket Buffers: R=[131072->131072] S=[16384->16384],
Wed Apr 22 21:53:04 2020 Attempting to establish TCP connection with [AF_INET]184.170.240.105:443 [nonblock],
Wed Apr 22 21:53:05 2020 TCP connection established with [AF_INET]184.170.240.105:443,
Wed Apr 22 21:53:05 2020 TCP_CLIENT link local: (not bound),
Wed Apr 22 21:53:05 2020 TCP_CLIENT link remote: [AF_INET]184.170.240.105:443,
Wed Apr 22 21:53:05 2020 TLS: Initial packet from [AF_INET]184.170.240.105:443, sid=df68048d 31089a3a,
Wed Apr 22 21:53:05 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this,
Wed Apr 22 21:53:06 2020 VERIFY OK: depth=2, C=PA, O=NordVPN, CN=NordVPN Root CA,
Wed Apr 22 21:53:06 2020 VERIFY OK: depth=1, C=PA, O=NordVPN, CN=NordVPN CA4,
Wed Apr 22 21:53:06 2020 VERIFY KU OK,
Wed Apr 22 21:53:06 2020 Validating certificate extended key usage,
Wed Apr 22 21:53:06 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication,
Wed Apr 22 21:53:06 2020 VERIFY EKU OK,
Wed Apr 22 21:53:06 2020 VERIFY OK: depth=0, CN=us3241.nordvpn.com,
Wed Apr 22 21:53:06 2020 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 4096 bit RSA,
Wed Apr 22 21:53:06 2020 [us3241.nordvpn.com] Peer Connection Initiated with [AF_INET]184.170.240.105:443,
Wed Apr 22 21:53:07 2020 SENT CONTROL [us3241.nordvpn.com]: 'PUSH_REQUEST' (status=1),
Wed Apr 22 21:53:07 2020 PUSH: Received control message: 'PUSH_REPLY,redirect-gateway def1,dhcp-option DNS 103.86.96.100,dhcp-option DNS 103.86.99.100,sndbuf 524288,rcvbuf 524288,explicit-exit-notify,comp-lzo no,route-gateway 10.7.3.1,topology subnet,ping 60,ping-restart 180,ifconfig 10.7.3.3 255.255.255.0,peer-id 0,cipher AES-256-GCM',
Wed Apr 22 21:53:07 2020 Option 'explicit-exit-notify' in [PUSH-OPTIONS]:6 is ignored by previous <connection> blocks ,
Wed Apr 22 21:53:07 2020 OPTIONS IMPORT: timers and/or timeouts modified,
Wed Apr 22 21:53:07 2020 OPTIONS IMPORT: --explicit-exit-notify can only be used with --proto udp,
Wed Apr 22 21:53:07 2020 OPTIONS IMPORT: compression parms modified,
Wed Apr 22 21:53:07 2020 OPTIONS IMPORT: --sndbuf/--rcvbuf options modified,
Wed Apr 22 21:53:07 2020 Socket Buffers: R=[131072->425984] S=[87040->425984],
Wed Apr 22 21:53:07 2020 OPTIONS IMPORT: --ifconfig/up options modified,
Wed Apr 22 21:53:07 2020 OPTIONS IMPORT: route options modified,
Wed Apr 22 21:53:07 2020 OPTIONS IMPORT: route-related options modified,
Wed Apr 22 21:53:07 2020 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified,
Wed Apr 22 21:53:07 2020 OPTIONS IMPORT: peer-id set,
Wed Apr 22 21:53:07 2020 OPTIONS IMPORT: adjusting link_mtu to 1659,
Wed Apr 22 21:53:07 2020 OPTIONS IMPORT: data channel crypto options modified,
Wed Apr 22 21:53:07 2020 Data Channel: using negotiated cipher 'AES-256-GCM',
Wed Apr 22 21:53:07 2020 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Wed Apr 22 21:53:07 2020 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Wed Apr 22 21:53:07 2020 ROUTE_GATEWAY 172.17.0.1/255.255.0.0 IFACE=eth0 HWADDR=02:42:ac:11:00:03,
Wed Apr 22 21:53:07 2020 TUN/TAP device tun0 opened,
Wed Apr 22 21:53:07 2020 TUN/TAP TX queue length set to 100,
Wed Apr 22 21:53:07 2020 do_ifconfig, tt->did_ifconfig_ipv6_setup=0,
Wed Apr 22 21:53:07 2020 /sbin/ip link set dev tun0 up mtu 1500,
Wed Apr 22 21:53:07 2020 /sbin/ip addr add dev tun0 10.7.3.3/24 broadcast 10.7.3.255,
Wed Apr 22 21:53:07 2020 /etc/openvpn/tunnelUp.sh tun0 1500 1587 10.7.3.3 255.255.255.0 init,
Up script executed with tun0 1500 1587 10.7.3.3 255.255.255.0 init,
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.7.3.3,
Generating transmission settings.json from env variables,
sed'ing True to true,
,
-------------------------------------,
Transmission will run as,
-------------------------------------,
User name:   root,
User uid:    0,
User gid:    0,
-------------------------------------,
,
STARTING TRANSMISSION,
NO PORT UPDATER FOR THIS PROVIDER,
Transmission startup script complete.,
Wed Apr 22 21:53:07 2020 /sbin/ip route add 184.170.240.105/32 via 172.17.0.1,
Wed Apr 22 21:53:07 2020 /sbin/ip route add 0.0.0.0/1 via 10.7.3.1,
Wed Apr 22 21:53:07 2020 /sbin/ip route add 128.0.0.0/1 via 10.7.3.1,
Wed Apr 22 21:53:07 2020 Initialization Sequence Completed,`

**Comment by pkishino** [comment]
Above looks all fine, so transmission is not running at that point? Have you ssh into the container and checked?

**Comment by digitalrain101** [comment]
I can execute a command shell from within Portainer, the IP in the logs correspond with what I find when I check the IP addresses in the shell. I'm actually at a loss for words here. Firewall blocking access on the server? Not sure what to do. I've already killed and rebuilt it with the same issue. It resides on a Ubuntu Server 19.10 x86_64 Optiplex 7020.

**Comment by haugene** [comment]
You say you can execute commands in it from Portainer. What is the output of `ps aux` or even `curl localhost:9091` when run inside the container?

**Comment by digitalrain101** [comment]
See attached:

![2020-04-23_16-08](https://user-images.githubusercontent.com/64154725/80154436-ca9dce80-857c-11ea-9a55-1d7ed661a969.jpg)

**Comment by haugene** [comment]
Then transmission is running and responding. Have you read this? https://haugene.github.io/docker-transmission-openvpn/access/

**Comment by digitalrain101** [comment]
Yes sir, I tried that, the proxy container and the modified url. Nothing.

**Comment by pkishino** [comment]
What do you mean, nothing? Does the proxy start? Does it connect to transmission etc? We can clearly see that transmission is up and running above. What version of docker/os are you using?

**Comment by haugene** [comment]
If you're using the LOCAL_NETWORK method there are some scenarios where there is an extra subnet somewhere (for example if it was within a VM) between the container network and your local `10.x.x.x/192.168.x.x` subnet. Depending on how the NATs are set up that could affect the routing.

But... The proxy solution should have worked. Can you try to run this docker-compose setup and let us know how that goes? Just add your own usr/pass and I think that should be enough. Transmission should then be available on `localhost:8080` on the server or `serverIP:8080` in the local net.

```
version: '2'
services:
  transmission-openvpn:
    container_name: transmission
    environment:
      - CREATE_TUN_DEVICE=true
      - OPENVPN_PROVIDER=NORDVPN
      - OPENVPN_USERNAME=username
      - OPENVPN_PASSWORD=password
    cap_add:
      - NET_ADMIN
    image: haugene/transmission-openvpn

  transmission-web-proxy:
    image: haugene/transmission-openvpn-proxy
    ports:
    - 8080:8080
```
