### ISSUE TITLE
Jackett not working with reverse proxy

### ISSUE THREAD

**Issue by JTT-JustTheTip** [haugene/docker-transmission-openvpn#1100]
**Describe the problem**

I forced Jackett to use the VPN as shown below, I can access the Web UI on its local IP and port but when I then try and connect to the Web UI using Lets Encrypt reverse proxy it shows the Web UI  but doesnt populate it, non of my settings or indexers appear. 

**Add your docker run command**

```
transmission-openvpn:
    image: haugene/transmission-openvpn
    hostname: transmission-openvpn
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    container_name: transmission-openvpn
    restart: always
    ports:
      - "9091:9091"
      - "8888:8888"
      - "9117:9117"
    dns:
      - 192.168.2.5
      - 8.8.4.4
    environment:
      PGID: 1001
      PUID: 1001
      OPENVPN_PROVIDER: PIA
      OPENVPN_CONFIG: UK Southampton
      OPENVPN_USERNAME: USER
      OPENVPN_PASSWORD: PASS
      OPENVPN_OPTS: --inactive 3600 --ping 10 --ping-exit 60 --mute-replay-warnings
      LOCAL_NETWORK: 192.168.2.0/24
      TRANSMISSION_RPC_USERNAME: "admin"
      TRANSMISSION_RPC_PASSWORD: "PASS"
      TRANSMISSION_RPC_AUTHENTICATION_REQUIRED: "true"
      TRANSMISSION_SPEED_LIMIT_DOWN: 7000
      TRANSMISSION_SPEED_LIMIT_UP: 100
      TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED: "true"
      TRANSMISSION_SPEED_LIMIT_UP_ENABLED: "true"
      TRANSMISSION_PEER_LIMIT_GLOBAL: 500
      TRANSMISSION_PEER_LIMIT_PER_TORRENT: 100
      TRANSMISSION_DOWNLOAD_QUEUE_SIZE: 100
      TRANSMISSION_RATIO_LIMIT: 0
      TRANSMISSION_RATIO_LIMIT_ENABLED: "true"  
      TRANSMISSION_DOWNLOAD_DIR: "/data/complete"
    volumes:
      - /media/VMRoot/VMMedia/:/data
      - /Docker_Configs/transmission-vpn/config:/config
      - /etc/localtime:/etc/localtime:ro

#Now uses transmission-openvpn web proxy to go through vpn
  Jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      PUID: '1001'
      PGID: '1001'
      TZ: GB
    network_mode: "service:transmission-openvpn"
    volumes:
    - /Docker_Configs/Jackett/config:/config
    - /media/VMRoot/VMMedia/:/downloads
    tty: true
    restart: unless-stopped

```

My LE config is shown below -

```
location /jackett {
    include /config/nginx/proxy.conf;
    set $upstream_jackett 192.168.2.13;
    proxy_pass http://$upstream_jackett:9117;
}

location ~ /jackett/(api|dl) {
    include /config/nginx/proxy.conf;
    set $upstream_jackett 12.168.2.13;
    proxy_pass http://$upstream_jackett:9117;
}
```

Apologies if this is the wrong place to post this!

Many Thanks
