### ISSUE TITLE
Loss of all torrents upon container re-creation

### ISSUE THREAD

**Issue by JTT-JustTheTip** [haugene/docker-transmission-openvpn#1120]
**Describe the problem**

This one is a little unusual, I am sometimes loosing all of my active torrents when the container is re-created, this more commonly happens when I have a large number of active torrents, eg this time I had ~300 active torrents. I have an instance of watchtower running in the background to ensure all of my images are up to date, so when watchtower updates containers overnight ill log on in the morning to find nothing. Nothing is shown in the logs about them all disappearing as far as i can see either.

**Add your docker run command**

```

transmission-openvpn:
    image: haugene/transmission-openvpn
    hostname: transmission-openvpn
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    container_name: transmission-openvpn
    restart: always
    ports:
      - "9091:9091"
      - "8888:8888"
      - "9117:9117"
    dns:
      - 192.168.2.5
      - 8.8.4.4
    environment:
      PGID: '1001'
      PUID: '1001'
      OPENVPN_PROVIDER: PIA
      OPENVPN_CONFIG: Romania
      OPENVPN_USERNAME: -------
      OPENVPN_PASSWORD: -------
      OPENVPN_OPTS: --inactive 3600 --ping 10 --ping-exit 60 --mute-replay-warnings
      LOCAL_NETWORK: 192.168.2.0/24
      TRANSMISSION_RPC_USERNAME: "admin"
      TRANSMISSION_RPC_PASSWORD: "-------"
      TRANSMISSION_RPC_AUTHENTICATION_REQUIRED: "true"
      TRANSMISSION_SPEED_LIMIT_DOWN: 7000
      TRANSMISSION_SPEED_LIMIT_UP: 100
      TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED: "true"
      TRANSMISSION_SPEED_LIMIT_UP_ENABLED: "true"
      TRANSMISSION_PEER_LIMIT_GLOBAL: 500
      TRANSMISSION_PEER_LIMIT_PER_TORRENT: 100
      TRANSMISSION_DOWNLOAD_QUEUE_SIZE: 25
      TRANSMISSION_RATIO_LIMIT: 0
      TRANSMISSION_RATIO_LIMIT_ENABLED: "true"  
      TRANSMISSION_DOWNLOAD_DIR: "/downloads/complete"
      TRANSMISSION_INCOMPLETE_DIR: "/downloads/incomplete"
    volumes:
      - /media/VMRoot/VMMedia/:/downloads
      - /Docker_Configs/transmission-vpn/config:/config
      - /media/VMRoot/VMMedia/watch:/watch
      - /etc/localtime:/etc/localtime:ro


```
