### ISSUE TITLE
[CLOSE THIS!] Still getting "RTNETLINK answers: Permission denied" after applying `pull-filter` fix with Mullvad

### ISSUE THREAD

**Issue by vikekh** [haugene/docker-transmission-openvpn#1129]
**CLOSE THIS ISSUE!** Environment variable `OPENVPN_CONFIG` had a typo, was therefor not using my custom .ovpn file.

**Describe the problem**

I'm trying to setup Transmission with Mullvad VPN, but I am hitting "RTNETLINK answers: Permission denied" error. I have tried applying #847 fix, but either I'm doing it wrong or something else is amiss.

**Add your docker run command**

```
version: "3.7"

services:
  transmission:
    image: haugene/transmission-openvpn
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - TRANSMISSION_WEB_UI=transmission-web-control
      - CREATE_TUN_DEVICE=true
      - OPENVPN_PROVIDER=${OPENVPN_PROVIDER} # MULLVAD
      - OPENVPN_CONFIG=${OPENVPN_CONFIG} # mullvad_xx-xxx_udp
      - OPENVPN_USERNAME=${OPENVPN_USERNAME} # ID
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD} # m
      - WEBPROXY_ENABLED=false
      - LOCAL_NETWORK=192.168.0.0/16
    volumes:
      - ./.transmission/config:/data/transmission-home
      - ${TRANSMISSION_DOWNLOADS_DIR}:/data/completed
      - /etc/localtime:/etc/localtime:ro
      - ./mullvad_xx-xxx_udp.ovpn:/etc/openvpn/mullvad/mullvad_xx-xxx_udp.ovpn
    ports:
      - 9091:9091
      - ${TRANSMISSION_PORT}:${TRANSMISSION_PORT}
      - ${TRANSMISSION_PORT}:${TRANSMISSION_PORT}/udp
    cap_add:
      - NET_ADMIN
    logging:
      driver: json-file
      options:
        max-size: 10m
    restart: unless-stopped
```

Here is an excerpt of what I've changed in .ovpn file I'm mounting:

```
#tun-ipv6 # Commented this
# Added pull-filter instead:
pull-filter ignore "dhcp-option DNS6 "
pull-filter ignore "tun-ipv6 "
pull-filter ignore "ifconfig-ipv6 "
```

Should `pull-filter` commands be somewhere else in .ovpn file?

**Logs**

```
transmission_1  | Using OpenVPN provider: MULLVAD
transmission_1  | Supplied config mullvad_xx-xxx-udp.ovpn could not be found.
transmission_1  | Using default OpenVPN gateway for provider mullvad
transmission_1  | Setting OPENVPN credentials...
transmission_1  | adding route to local network 192.168.0.0/16 via 192.168.144.1 dev eth0
transmission_1  | Thu Apr  9 00:30:25 2020 Note: option tun-ipv6 is ignored because modern operating systems do not need special IPv6 tun handling anymore.
transmission_1  | Thu Apr  9 00:30:25 2020 OpenVPN 2.4.4 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on May 14 2019
transmission_1  | Thu Apr  9 00:30:25 2020 library versions: OpenSSL 1.1.1  11 Sep 2018, LZO 2.08
transmission_1  | Thu Apr  9 00:30:25 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
transmission_1  | Thu Apr  9 00:30:25 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]185.65.134.137:1197
transmission_1  | Thu Apr  9 00:30:25 2020 Socket Buffers: R=[212992->425984] S=[212992->425984]
transmission_1  | Thu Apr  9 00:30:25 2020 UDP link local: (not bound)
transmission_1  | Thu Apr  9 00:30:25 2020 UDP link remote: [AF_INET]185.65.134.137:1197
transmission_1  | Thu Apr  9 00:31:25 2020 [UNDEF] Inactivity timeout (--ping-restart), restarting
transmission_1  | Thu Apr  9 00:31:25 2020 SIGUSR1[soft,ping-restart] received, process restarting
transmission_1  | Thu Apr  9 00:31:25 2020 Restart pause, 5 second(s)
transmission_1  | Thu Apr  9 00:31:30 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
transmission_1  | Thu Apr  9 00:31:30 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]185.65.134.146:1197
transmission_1  | Thu Apr  9 00:31:30 2020 Socket Buffers: R=[212992->425984] S=[212992->425984]
transmission_1  | Thu Apr  9 00:31:30 2020 UDP link local: (not bound)
transmission_1  | Thu Apr  9 00:31:30 2020 UDP link remote: [AF_INET]185.65.134.146:1197
transmission_1  | Thu Apr  9 00:31:30 2020 TLS: Initial packet from [AF_INET]185.65.134.146:1197, sid=97058d39 9d4ecb8b
transmission_1  | Thu Apr  9 00:31:30 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
transmission_1  | Thu Apr  9 00:31:31 2020 VERIFY OK: depth=2, C=SE, ST=Gotaland, L=Gothenburg, O=Amagicom AB, OU=Mullvad, CN=Mullvad Root CA v2, emailAddress=security@mullvad.net
transmission_1  | Thu Apr  9 00:31:31 2020 VERIFY OK: depth=1, C=SE, ST=Gotaland, O=Amagicom AB, OU=Mullvad, CN=Mullvad Intermediate CA v2, emailAddress=security@mullvad.net
transmission_1  | Thu Apr  9 00:31:31 2020 VERIFY KU OK
transmission_1  | Thu Apr  9 00:31:31 2020 Validating certificate extended key usage
transmission_1  | Thu Apr  9 00:31:31 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
transmission_1  | Thu Apr  9 00:31:31 2020 VERIFY EKU OK
transmission_1  | Thu Apr  9 00:31:31 2020 VERIFY OK: depth=0, C=SE, ST=Gotaland, O=Amagicom AB, OU=Mullvad, CN=nl-ams-016.mullvad.net, emailAddress=security@mullvad.net
transmission_1  | Thu Apr  9 00:31:31 2020 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1557', remote='link-mtu 1558'
transmission_1  | Thu Apr  9 00:31:31 2020 WARNING: 'comp-lzo' is present in remote config but missing in local config, remote='comp-lzo'
transmission_1  | Thu Apr  9 00:31:31 2020 Control Channel: TLSv1.2, cipher TLSv1.2 DHE-RSA-AES256-GCM-SHA384, 4096 bit RSA
transmission_1  | Thu Apr  9 00:31:31 2020 [nl-ams-016.mullvad.net] Peer Connection Initiated with [AF_INET]185.65.134.146:1197
transmission_1  | Thu Apr  9 00:31:32 2020 SENT CONTROL [nl-ams-016.mullvad.net]: 'PUSH_REQUEST' (status=1)
transmission_1  | Thu Apr  9 00:31:37 2020 SENT CONTROL [nl-ams-016.mullvad.net]: 'PUSH_REQUEST' (status=1)
transmission_1  | Thu Apr  9 00:31:37 2020 PUSH: Received control message: 'PUSH_REPLY,dhcp-option DNS 10.11.0.1,redirect-gateway def1 bypass-dhcp,route-ipv6 0000::/2,route-ipv6 4000::/2,route-ipv6 8000::/2,route-ipv6 C000::/2,comp-lzo no,route-gateway 10.11.0.1,topology subnet,socket-flags TCP_NODELAY,ifconfig-ipv6 fdda:d0d0:cafe:1197::100c/64 fdda:d0d0:cafe:1197::,ifconfig 10.11.0.14 255.255.0.0,peer-id 15,cipher AES-256-GCM'
transmission_1  | Thu Apr  9 00:31:37 2020 OPTIONS IMPORT: compression parms modified
transmission_1  | Thu Apr  9 00:31:37 2020 OPTIONS IMPORT: --socket-flags option modified
transmission_1  | Thu Apr  9 00:31:37 2020 NOTE: setsockopt TCP_NODELAY=1 failed
transmission_1  | Thu Apr  9 00:31:37 2020 OPTIONS IMPORT: --ifconfig/up options modified
transmission_1  | Thu Apr  9 00:31:37 2020 OPTIONS IMPORT: route options modified
transmission_1  | Thu Apr  9 00:31:37 2020 OPTIONS IMPORT: route-related options modified
transmission_1  | Thu Apr  9 00:31:37 2020 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
transmission_1  | Thu Apr  9 00:31:37 2020 OPTIONS IMPORT: peer-id set
transmission_1  | Thu Apr  9 00:31:37 2020 OPTIONS IMPORT: adjusting link_mtu to 1624
transmission_1  | Thu Apr  9 00:31:37 2020 OPTIONS IMPORT: data channel crypto options modified
transmission_1  | Thu Apr  9 00:31:37 2020 Data Channel: using negotiated cipher 'AES-256-GCM'
transmission_1  | Thu Apr  9 00:31:37 2020 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
transmission_1  | Thu Apr  9 00:31:37 2020 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
transmission_1  | Thu Apr  9 00:31:37 2020 ROUTE_GATEWAY 192.168.144.1/255.255.240.0 IFACE=eth0 HWADDR=02:42:c0:a8:90:02
transmission_1  | Thu Apr  9 00:31:37 2020 GDG6: remote_host_ipv6=n/a
transmission_1  | Thu Apr  9 00:31:37 2020 ROUTE6: default_gateway=UNDEF
transmission_1  | Thu Apr  9 00:31:37 2020 TUN/TAP device tun0 opened
transmission_1  | Thu Apr  9 00:31:37 2020 TUN/TAP TX queue length set to 100
transmission_1  | Thu Apr  9 00:31:37 2020 do_ifconfig, tt->did_ifconfig_ipv6_setup=1
transmission_1  | Thu Apr  9 00:31:37 2020 /sbin/ip link set dev tun0 up mtu 1500
transmission_1  | Thu Apr  9 00:31:37 2020 /sbin/ip addr add dev tun0 10.11.0.14/16 broadcast 10.11.255.255
transmission_1  | Thu Apr  9 00:31:37 2020 /sbin/ip -6 addr add fdda:d0d0:cafe:1197::100c/64 dev tun0
transmission_1  | RTNETLINK answers: Permission denied
transmission_1  | Thu Apr  9 00:31:37 2020 Linux ip -6 addr add failed: external program exited with error status: 2
transmission_1  | Thu Apr  9 00:31:37 2020 Exiting due to fatal error
```

**Host system:**

Ubuntu v18.04.3 LTS, Docker v19.03.5, Docker Compose v1.25.0
