### ISSUE TITLE
Jackett no longer accessible after transmission restart

### ISSUE THREAD

**Issue by JTT-JustTheTip** [haugene/docker-transmission-openvpn#1136]
**Describe the problem**

Now this may be a lack of knowledge on my part so apologies for any ignorance on my end. I have a watchtower container configured to update all my deployed containers as and when required. Now this means my Transmission container is restarted at least once a day-ish from what I can see. When the transmission is restarted the attached jackett container is no restarted and becomes inaccessible from that point on wards.

I am assuming this is to do with the the recreation of the transmission container kills that containers network and therefore leaves jackett connected to a non existent network making it inaccessible. 

Is there a way to force jackett to be restarted simultaneously when the transmission container goes down, or a to keep jackett and transmission connected through container restarts and recreations. 

**Compose**

```
transmission-openvpn:
    image: haugene/transmission-openvpn
    hostname: transmission-openvpn
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    container_name: transmission-openvpn
    restart: always
    ports:
      - "9091:9091"
      - "8888:8888"
      - "9117:9117"
    dns:
      - 192.168.2.5
      - 8.8.4.4
    environment:
      PGID: '1001'
      PUID: '1001'
      OPENVPN_PROVIDER: PIA
      OPENVPN_CONFIG: CA Vancouver
      OPENVPN_USERNAME: 
      OPENVPN_PASSWORD: 
      OPENVPN_OPTS: --inactive 3600 --ping 10 --ping-exit 60 --mute-replay-warnings
      LOCAL_NETWORK: 192.168.2.0/24
      TRANSMISSION_RPC_USERNAME: "admin"
      TRANSMISSION_RPC_PASSWORD: ""
      TRANSMISSION_RPC_AUTHENTICATION_REQUIRED: "true"
      TRANSMISSION_SPEED_LIMIT_DOWN: 7000
      TRANSMISSION_SPEED_LIMIT_UP: 100
      TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED: "true"
      TRANSMISSION_SPEED_LIMIT_UP_ENABLED: "true"
      TRANSMISSION_PEER_LIMIT_GLOBAL: 500
      TRANSMISSION_PEER_LIMIT_PER_TORRENT: 100
      TRANSMISSION_DOWNLOAD_QUEUE_SIZE: 200
      TRANSMISSION_RATIO_LIMIT: 0
      TRANSMISSION_IDLE_SEEDING_LIMIT: 0
      TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED: "true"
      TRANSMISSION_RATIO_LIMIT_ENABLED: "true"  
      TRANSMISSION_DOWNLOAD_DIR: "/downloads/complete"
      TRANSMISSION_INCOMPLETE_DIR: "/downloads/incomplete"
    volumes:
      - /media/VMRoot/VMMedia/:/downloads
      - /media/VMRoot/VMMedia/Config:/data
      - /Docker_Configs/transmission-vpn/config:/config
      - /media/VMRoot/VMMedia/watch:/watch
      - /etc/localtime:/etc/localtime:ro



#Now uses transmission-openvpn web proxy to go through vpn
  Jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      PUID: '1001'
      PGID: '1001'
      TZ: GB
    network_mode: "service:transmission-openvpn"
    volumes:
    - /Docker_Configs/Jackett/config:/config
    - /media/VMRoot/VMMedia/:/downloads
    tty: true
    restart: unless-stopped
    depends_on:
      - "transmission-openvpn"

```
