### ISSUE TITLE
transmission-rss incorrect build metadata for armhf (OS/Arch = linux/amd64) in swarm mode

### ISSUE THREAD

**Issue by ausshir** [haugene/docker-transmission-openvpn#1149]
My apologies if this is not the correct place to submit the issue. The Docker Hub page points here! :)

**Describe the problem**
Docker swarm can not launch the transmission-rss image from the armhf tag, because the build metadata is set incorrectly.

![image](https://user-images.githubusercontent.com/12824055/79827616-0ad23680-835c-11ea-9eb7-da084d88f07b.png)

**Add your docker run command**

Being that this is swarm, the relevant part of my stack is as below:
```
  transmission-rss:
    image: haugene/transmission-rss:latest-armhf
    volumes:
      - '/path/to/transmission/transmission-home/transmission-rss.conf:/etc/transmission-rss.conf'
```

**Logs**
There are no logs, as the task can not start. The only message is "no suitable node (unsupported platform on 2 nodes)"

**Host system:**
This is on an odroid-hc1 (xu4) armv7 cluster (only 2 boards for now).

~~haugene/transmission-openvpn:latest-armhf is working fine!~~
    Edit: Actually no, this image has the same problem. I was not running in swarm mode so it did not check the image metadata first.
