### ISSUE TITLE
Can't get the peer listening port to show as open

### ISSUE THREAD

**Issue by ovizii** [haugene/docker-transmission-openvpn#1152]
- I am using ghostpath VPN
- on the ghostpath website I enabled port forwarding and got a TCP port 12345 assigned to me
- based on https://github.com/haugene/docker-transmission-openvpn/blob/master/DockerEnv I have added this line to my .env file: TRANSMISSION_PEER_PORT=12345
- starting transmission and going to settings - network - listening port 12345 => closed

Do I need to do anything else? Ghostpath VPN said it might take up to 4h to open this port for me but about 8h have already passed...

**Also, by default ghostpath forwards a TCP port but I can change to UDP just not both.**

here are all the .env variables I have enabled inside **.transmission-openvpn-env**

```
OPENVPN_PROVIDER=GHOSTPATH
OPENVPN_CONFIG=Ukraine-Kiev,Brazil-Sao-Paulo,Chile-Vina-del-Mar,Estonia-Tallinn,Hong-Kong-Hong-Kong,Israel-Tel-Aviv-Yafo,India-Pune,Indonesia-Jakarta
OPENVPN_USERNAME=myvpnuser
OPENVPN_PASSWORD=mypassword
PUID=1000
PGID=1000
CREATE_TUN_DEVICE=true
TRANSMISSION_WEB_UI=combustion
OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
# does not seem to work with ghostpath vpn
#DROP_DEFAULT_ROUTE=true
LOCAL_NETWORK=192.168.178.0/24
ENABLE_UFW=true
UFW_ALLOW_GW_NET=false
GLOBAL_APPLY_PERMISSIONS=false
TRANSMISSION_DOWNLOAD_DIR=/data/completed
TRANSMISSION_IDLE_SEEDING_LIMIT=30
TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED=true
TRANSMISSION_INCOMPLETE_DIR=/data/incomplete
TRANSMISSION_PEER_PORT=12345
TRANSMISSION_RATIO_LIMIT=2
TRANSMISSION_RATIO_LIMIT_ENABLED=true
TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
TRANSMISSION_RPC_PASSWORD=mypassword
TRANSMISSION_RPC_USERNAME=admin
TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=false
TRANSMISSION_HOME=/data/transmission-home
```

And here is the relevant part of my **docker-compose.yml** file:

```
    transmission-openvpn:
        image: haugene/transmission-openvpn
        hostname: transmission-openvpn
        container_name: transmission-openvpn
        volumes:
          - /sixer/docker-data/transmission-openvpn/:/data/
          - /sixer/tmp/downloads/completed/:/data/completed/
          - /sixer/tmp/downloads/incomplete/:/data/incomplete/
          - /etc/localtime:/etc/localtime:ro
        env_file: .transmission-openvpn-env
        cpu_count: 4
        mem_limit: 4G
        cap_add:
          - NET_ADMIN
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"
        ports:
            - '9091:9091'
        network_mode: bridge
```

Not sure what other info to provide. Some possibly interesting log file parts:

**data/transmission-home/transmission.log**

```
[2020-04-21 08:32:50.270] Transmission 2.94 (d8e60ee44f) started (session.c:740)
[2020-04-21 08:32:50.270] RPC Server Adding address to whitelist: 127.0.0.1 (rpc-server.c:971)
[2020-04-21 08:32:50.270] RPC Server Serving RPC and Web requests on port 127.0.0.1:9091/transmission/ (rpc-server.c:1213)
[2020-04-21 08:32:50.270] RPC Server Password required (rpc-server.c:1220)
[2020-04-21 08:32:50.270] Port Forwarding Stopped (port-forwarding.c:180)
[2020-04-21 08:32:50.270] UDP Failed to set receive buffer: requested 4194304, got 425984 (tr-udp.c:84)
[2020-04-21 08:32:50.270] UDP Please add the line "net.core.rmem_max = 4194304" to /etc/sysctl.conf (tr-udp.c:89)
[2020-04-21 08:32:50.270] UDP Failed to set send buffer: requested 1048576, got 425984 (tr-udp.c:95)
[2020-04-21 08:32:50.270] UDP Please add the line "net.core.wmem_max = 1048576" to /etc/sysctl.conf (tr-udp.c:100)
[2020-04-21 08:32:50.270] DHT Generating new id (tr-dht.c:311)

```

**docker logs -f transmission-openvpn**
```
Using OpenVPN provider: GHOSTPATH
8 servers found in OPENVPN_CONFIG, Estonia-Tallinn chosen randomly
Starting OpenVPN using config Estonia-Tallinn.ovpn
Setting OPENVPN credentials...
enabling firewall
Firewall is active and enabled on system startup
allowing 12345 through the firewall
Rule added
allowing 172.17.0.1 through the firewall to port 9091
Rule added
adding route to local network 192.168.178.0/24 via 172.17.0.1 dev eth0
allowing 192.168.178.0/24 through the firewall to port 9091
Rule added
Tue Apr 21 08:32:45 2020 OpenVPN 2.4.4 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on May 14 2019
Tue Apr 21 08:32:45 2020 library versions: OpenSSL 1.1.1  11 Sep 2018, LZO 2.08
Tue Apr 21 08:32:45 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Tue Apr 21 08:32:46 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]185.155.96.xxx:443
Tue Apr 21 08:32:46 2020 UDP link local: (not bound)
Tue Apr 21 08:32:46 2020 UDP link remote: [AF_INET]185.155.96.xxx:443
Tue Apr 21 08:32:46 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Tue Apr 21 08:32:47 2020 [VPN] Peer Connection Initiated with [AF_INET]185.155.96.xxx:443
Tue Apr 21 08:32:48 2020 TUN/TAP device tun0 opened
Tue Apr 21 08:32:48 2020 do_ifconfig, tt->did_ifconfig_ipv6_setup=0
Tue Apr 21 08:32:48 2020 /sbin/ip link set dev tun0 up mtu 1500
Tue Apr 21 08:32:48 2020 /sbin/ip addr add dev tun0 local 10.10.8.22 peer 10.10.8.21
Tue Apr 21 08:32:48 2020 /etc/openvpn/tunnelUp.sh tun0 1500 1557 10.10.8.22 10.10.8.21 init
Up script executed with tun0 1500 1557 10.10.8.22 10.10.8.21 init
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.10.8.22
Using Combustion UI, overriding TRANSMISSION_WEB_HOME
Generating transmission settings.json from env variables
sed'ing True to true
Enforcing ownership on transmission config directories
Applying permissions to transmission config directories

-------------------------------------
Transmission will run as
-------------------------------------
User name:   abc
User uid:    1000
User gid:    1000
-------------------------------------

STARTING TRANSMISSION
NO PORT UPDATER FOR THIS PROVIDER
Transmission startup script complete.
Tue Apr 21 08:32:48 2020 Initialization Sequence Completed

```
Any ideas why the peer port still shows as closed?
