### ISSUE TITLE
Ubuntu 20.04 on Raspberry Pi 4 - Transmission fails to start - latest-arm64

### ISSUE THREAD

**Issue by MrLemur** [haugene/docker-transmission-openvpn#1156]
**Describe the problem**
After upgrading to Ubuntu 20.04 from 18.04.1, Transmission fails to start. The error from the logs is `su: Critical error - immediate abort`

**docker-compose.yml**
```
transmission:
    image: haugene/transmission-openvpn:latest-arm64
    restart: always
    volumes:
      - "/hdd/docker_config/downloads:/data"
      - "/hdd/media:/downloads"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - PUID=1001
      - PGID=1001
      - CREATE_TUN_DEVICE=true
      - OPENVPN_PROVIDER=xxx
      - OPENVPN_CONFIG=xxx
      - OPENVPN_USERNAME=${OPENVPN_USERNAME}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - TRANSMISSION_WEB_UI=combustion
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      - TRANSMISSION_RPC_USERNAME=${TRANSMISSION_RPC_USERNAME}
      - TRANSMISSION_RPC_PASSWORD=${TRANSMISSION_RPC_PASSWORD}
    cap_add:
      - NET_ADMIN
    logging:
      driver: json-file
      options:
        max-size: 10m
    healthcheck:
      interval: 5s
      start_period: 10s
    dns: 1.1.1.1
```

**Logs**
```
transmission_1  | Using Combustion UI, overriding TRANSMISSION_WEB_HOME
transmission_1  | Generating transmission settings.json from env variables
transmission_1  | sed'ing True to true
transmission_1  | Enforcing ownership on transmission config directories
transmission_1  | Applying permissions to transmission config directories
transmission_1  | Setting owner for transmission paths to 1001:1001
transmission_1  | Setting permission for files (644) and directories (755)
transmission_1  | Setting permission for watch directory (775) and its files (664)
transmission_1  |
transmission_1  | -------------------------------------
transmission_1  | Transmission will run as
transmission_1  | -------------------------------------
transmission_1  | User name:   abc
transmission_1  | User uid:    1001
transmission_1  | User gid:    1001
transmission_1  | -------------------------------------
transmission_1  |
transmission_1  | STARTING TRANSMISSION
transmission_1  | NO PORT UPDATER FOR THIS PROVIDER
transmission_1  | Transmission startup script complete.
transmission_1  | Fri Apr 24 19:00:46 2020 Initialization Sequence Completed
transmission_1  | su: Critical error - immediate abort
```

**Host system:**
Raspberry Pi 4GB 
Ubuntu Server 20.04
Docker Engine 19.03.8
