### ISSUE TITLE
AUTH_FAIL with NordVPN

### ISSUE THREAD

**Issue by jackbucinskas** [haugene/docker-transmission-openvpn#1191]
**Describe the problem**
Hey all, I am having some problems with AUTH_FAIL, I am using NORDVPN

`docker-compose.yml`
```
version: "3"
services:
  torrent:
    container_name: torrent
    volumes:
        - /media/share/Torrents:/media/share/Torrents
        - /etc/localtime:/etc/localtime:ro
    environment:
        # - PUID=1000
        # - PGID=1000
        - CREATE_TUN_DEVICE=true
        - OPENVPN_PROVIDER=NORDVPN
        - OPENVPN_USERNAME=email@address.com
        - OPENVPN_PASSWORD=passwordhere
        - WEBPROXY_ENABLED=false
        - LOCAL_NETWORK=192.168.20.0/24
        - NORDVPN_COUNTRY=CH
        - NORDVPN_PROTOCOL=tcp
        - NORDVPN_CATEGORY=legacy_p2p
    cap_add:
        - NET_ADMIN
    logging:
        driver: json-file
        options:
            max-size: 10m
    ports:
        - '9091:9091'
    image: haugene/transmission-openvpn
```

**Add your docker run command**

`sudo docker-compose up -d torrent`

**Logs**

```
VERIFY OK: depth=0, CN=ch222.nordvpn.com
Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 4096 bit RSA
[ch222.nordvpn.com] Peer Connection Initiated with [AF_INET]185.156.175.115:443
SENT CONTROL [ch222.nordvpn.com]: 'PUSH_REQUEST' (status=1)
AUTH: Received control message: AUTH_FAILED
SIGTERM[soft,auth-failure] received, process exiting
```

**Host system**
Debian 10

**Troubleshooting**
I have checked issue [#329](https://github.com/haugene/docker-transmission-openvpn/issues/329) to see if there were errors with my credentials.txt file.

I can quickly check the credientials when the container is running and the username, password is correct
`docker exec -it torrent bash -c "cat /config/openvpn-credentials.txt"`
```
email@address.com
passwordhere
```
