### ISSUE TITLE
Cannot access my.vps.ip.address:9091, but can access localhost:9091

### ISSUE THREAD

**Issue by davidmpa** [haugene/docker-transmission-openvpn#1198]
**Describe the problem**

Container is running, able to access `localhost:9091` from within my VPS but not `my.vps.ip.address:9091`, either from within the VPS or from my home PC.

`curl localhost:9091` returns `<h1>301: Moved Permanently</h1>`, but `curl my.vps.ip.address:9091` hangs then times out.

**Add your docker run command**

I used Docker Compose.

```
version: '3.3'
services:
    transmission-openvpn:
        volumes:
            - '/home/kairos/dfiles/:/data'
            - '/etc/localtime:/etc/localtime:ro'
        environment:
            - CREATE_TUN_DEVICE=true
            - OPENVPN_PROVIDER=PIA
            - OPENVPN_CONFIG=CA Toronto
            - OPENVPN_USERNAME=myusername
            - OPENVPN_PASSWORD=mypassword
            - WEBPROXY_ENABLED=false
            - LOCAL_NETWORK=172.20.0.0/16
        cap_add:
            - NET_ADMIN
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '9091:9091'
        image: haugene/transmission-openvpn
```

**Logs**

```
Using OpenVPN provider: PIA
Starting OpenVPN using config CA Toronto.ovpn
Setting OPENVPN credentials...
adding route to local network 172.20.0.0/16 via 172.21.0.1 dev eth0
Fri May 22 15:42:41 2020 OpenVPN 2.4.4 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on May 14 2019
Fri May 22 15:42:41 2020 library versions: OpenSSL 1.1.1  11 Sep 2018, LZO 2.08
Fri May 22 15:42:41 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Fri May 22 15:42:41 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]172.98.**.**:1234
Fri May 22 15:42:41 2020 UDP link local: (not bound)
Fri May 22 15:42:41 2020 UDP link remote: [AF_INET]172.98.**.**:1234
Fri May 22 15:42:41 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Fri May 22 15:42:41 2020 [**********hash***********] Peer Connection Initiated with [AF_INET]172.98.**.**:1234
Fri May 22 15:42:43 2020 TUN/TAP device tun0 opened
Fri May 22 15:42:43 2020 do_ifconfig, tt->did_ifconfig_ipv6_setup=0
Fri May 22 15:42:43 2020 /sbin/ip link set dev tun0 up mtu 1500
Fri May 22 15:42:43 2020 /sbin/ip addr add dev tun0 local 10.90.10.6 peer 10.90.10.5
Fri May 22 15:42:43 2020 /etc/openvpn/tunnelUp.sh tun0 1500 1558 10.90.10.6 10.90.10.5 init
Up script executed with tun0 1500 1558 10.90.10.6 10.90.10.5 init
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.90.10.6
Generating transmission settings.json from env variables
sed'ing True to true

-------------------------------------
Transmission will run as
-------------------------------------
User name:   root
User uid:    0
User gid:    0
-------------------------------------

STARTING TRANSMISSION
CONFIGURING PORT FORWARDING
Transmission startup script complete.
Wait for tunnel to be fully initialized and PIA is ready to give us a port
Fri May 22 15:42:43 2020 Initialization Sequence Completed
Generating new client id for PIA
Got new port 12345 from PIA
transmission auth not required
waiting for transmission to become responsive
transmission became responsive
ID     Done       Have  ETA           Up    Down  Ratio  Status       Name
Sum:              None               0.0     0.0
setting transmission port to 12345
localhost:9091/transmission/rpc/ responded: "success"
Checking port...
Port is open: Yes
```

**Host system:**

Ubuntu 18.04.4 LTS x86_64
Docker version 19.03.8, build afacb8b7f0

**Comment by pkishino** [comment]
Could be dns issue, vps config.. what ip does local host resolve to vs my.vps etc

**Comment by davidmpa** [comment]
@pkishino Could you give me a hint what I can try to narrow down on this?

**Comment by pkishino** [comment]
You’ve setup local_network variable, based on what? Localhost:9091 works as expected.. how is sicher configured in the vps? What ip range is the vps on etc..

**Comment by davidmpa** [comment]
@pkishino Thank you for the reply.

I set up `local_network` based on the first network device that I saw via `ifconfig` (I realized now it's a dumb idea, sorry):

```
br-*****f54a***: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.22.0.1  netmask 255.255.0.0  broadcast 172.22.255.255
        inet6 ****::**:**ff:fe**:****  prefixlen 64  scopeid 0x20<link>
        ether my:mac:address:**:**:94  txqueuelen 0  (Ethernet)
        RX packets 261  bytes 35063 (35.0 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 270  bytes 49881 (49.8 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

docker0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255
        inet6 ****::**:**ff:fe**:****  prefixlen 64  scopeid 0x20<link>
        ether my:mac:address:**:**:8a  txqueuelen 0  (Ethernet)
        RX packets 978  bytes 95247 (95.2 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1049  bytes 206642 (206.6 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

docker_gwbridge: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.18.0.1  netmask 255.255.0.0  broadcast 172.18.255.255
        inet6 ****::**:**ff:fe**:****  prefixlen 64  scopeid 0x20<link>
        ether my:mac:address:**:**:d5  txqueuelen 0  (Ethernet)
        RX packets 1291493  bytes 232911081 (232.9 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1260849  bytes 248641232 (248.6 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet my.vps.ip.address  netmask 255.255.255.0  broadcast my.vps.ip.255
        inet6 my:vps::ipv6:address  prefixlen 64  scopeid 0x0<global>
        inet6 my:vps::ipv6:address  prefixlen 64  scopeid 0x0<global>
        inet6 my:vps::ipv6:address  prefixlen 64  scopeid 0x0<global>
... lots of ipv6 addresses...

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 1066254  bytes 113574703 (113.5 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1066254  bytes 113574703 (113.5 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

veth******8: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 ****::**:**:****:****  prefixlen 64  scopeid 0x20<link>
        ether my:mac:address:**:**:ea  txqueuelen 0  (Ethernet)
        RX packets 342795  bytes 101704554 (101.7 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 353018  bytes 45673062 (45.6 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

veth******2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 ****::**:**:****:****  prefixlen 64  scopeid 0x20<link>
        ether my:mac:address:**:**:4e  txqueuelen 0  (Ethernet)
        RX packets 121  bytes 11722 (11.7 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 2987  bytes 405624 (405.6 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

So I removed the `LOCAL_NETWORK` variable. Then I set the DNS to `8.8.8.8` and `8.8.4.4` hoping that would fix it, but still not working.

I can curl the Transmission WebUI via `localhost:9091`, `127.0.0.1:9091`, `172.22.0.1:9091`, `172.17.0.1:9091`, `172.18.0.1:9091`, but not `my.vps.ip.address`.

My UFW status is

```
Status: active

To                         Action      From
--                         ------      ----
22/tcp                     ALLOW       Anywhere
80,443,996,2377,3000,4789,7946/tcp ALLOW       Anywhere
2377,4789,7946/udp         ALLOW       Anywhere
9091                       ALLOW       Anywhere
22/tcp (v6)                ALLOW       Anywhere (v6)
80,443,996,2377,3000,4789,7946/tcp (v6) ALLOW       Anywhere (v6)
2377,4789,7946/udp (v6)    ALLOW       Anywhere (v6)
9091 (v6)                  ALLOW       Anywhere (v6)
```

**Comment by davidmpa** [comment]
Also I'm using docker compose, this is my compose file

```
version: '3.3'
services:
    transmission-openvpn:
        volumes:
            - '/home/myusername/downloads/:/data'
            - '/etc/localtime:/etc/localtime:ro'
        environment:
            - CREATE_TUN_DEVICE=true
            - OPENVPN_PROVIDER=PIA
            - OPENVPN_CONFIG=CA Toronto
            - OPENVPN_USERNAME=p*******
            - OPENVPN_PASSWORD=*********************
            - WEBPROXY_ENABLED=false
              #    - LOCAL_NETWORK=172.20.0.0/16
        cap_add:
            - NET_ADMIN
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '9091:9091'
        image: haugene/transmission-openvpn
        dns:
            - 8.8.8.8
            - 8.8.4.4
```
