### ISSUE TITLE
Latest Version breaking the json parsing

### ISSUE THREAD

**Issue by kennyparsons** [haugene/docker-transmission-openvpn#1215]
**Describe the problem**
Receiving this in the log file of the latest docker build:
```
[2020-05-29 09:44:42.230] JSON parse failed in /data/transmission-home/settings.json at pos 2234: INVALID_NUMBER -- remaining text "02,,
    "upload-"
```
The only lines with this text is:
```
    "trash-original-torrent-files": false,
    "umask": 002,
    "upload-slots-per-torrent": 14,
```

**Add your docker run command**
`docker-compose`
```
version: "3.6"
services:

# Transmission with PureVPN - tr-01
  tr-01:
    container_name: tr-01
    image: haugene/transmission-openvpn:latest
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: always
    dns:
      - 192.168.2.6
      - 1.0.0.1
    volumes: #removed the lengthy mounts to keep it short. 
    environment:
      - HEALTH_CHECK_HOST=8.8.8.8
      - OPENVPN_PROVIDER=
      - OPENVPN_USERNAME=
      - OPENVPN_PASSWORD=
      - OPENVPN_CONFIG=
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=192.168.2.0/24
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      - TRANSMISSION_RPC_HOST_WHITELIST=127.0.0.1,192.168.*.*,172.30.0.0/16
      - TRANSMISSION_RPC_PASSWORD=mypassword
      - TRANSMISSION_RPC_USERNAME=nyname
      - TRANSMISSION_DOWNLOAD_QUEUE_ENABLED=false
      #- TRANSMISSION_MAX_PEERS_PER_TORRENT=100
      #- TRANSMISSION_MAX_PEERS_GLOBAL=10000
      - TRANSMISSION_PEER_LIMIT_GLOBAL=10000
      - TRANSMISSION_PEER_LIMIT_PER_TORRENT=100
      - TRANSMISSION_UMASK=002
      #- TRANSMISSION_RATIO_LIMIT=0.00
      - TRANSMISSION_RATIO_LIMIT_ENABLED=false
      #- TRANSMISSION_SPEED_LIMIT_UP=0
      - TRANSMISSION_SPEED_LIMIT_UP_ENABLED=false
      - TRANSMISSION_WEB_UI=combustion
```

**Logs**
see above. 

**Host system:**
debian 9
