### ISSUE TITLE
WebUI not accessible

### ISSUE THREAD

**Issue by sameep22** [haugene/docker-transmission-openvpn#1217]
Hey,

First of all, kudos to the contributors for the continuous work that is required to keep up with this project.

I tried searching for a similar issue, but I was unable to find something that corresponds exactly to my problem. If I am wrong here, please do point me to the right direction.

I have had the setup running for a few months, and one fine day, the docker container was no longer accessible. However, the container itself seems to give out a "healthy" status. I am unsure as to what the problem is exactly, and hope you guys can help me figure it out. As far as I can remember, the only change was that I updated the base system to Ubuntu 20.04. However, I as still able to access the container immediately after the update.

For reference, I use a docker-compose file, and here is the configuration that I use:

```
  transmission-vpn:
    container_name: transmission-vpn
    image: haugene/transmission-openvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: always
    ports:
    - "9003:9091"
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/docker/transmission-vpn:/data
      - ${USERDIR}/docker/shared:/shared
      - ${USERDIR}/Downloads:/data/watch
      - ${USERDIR}/Downloads/completed:/data/completed
      - ${USERDIR}/Downloads/incomplete:/data/incomplete
    environment:
      - OPENVPN_PROVIDER=NORDVPN
      - OPENVPN_USERNAME=*****
      - OPENVPN_PASSWORD=*****
      - NORDVPN_COUNTRY=fr
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=192.168.0.0/16
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=false
      - TRANSMISSION_RPC_HOST_WHITELIST="127.0.0.1,192.168.*.*,*.*.*.*"
      - TRANSMISSION_WATCH_DIR_FORCE_GENERIC=true
      - TRANSMISSION_UMASK=002
      - TRANSMISSION_RATIO_LIMIT=1.25
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
```

And here are the logs:

```
Sun May 31 03:01:56 2020 VERIFY OK: depth=0, CN=fr530.nordvpn.com,
Sun May 31 03:01:56 2020 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Sun May 31 03:01:56 2020 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Sun May 31 03:01:56 2020 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 4096 bit RSA,
Sun May 31 04:01:55 2020 TLS: tls_process: killed expiring key,
Sun May 31 04:01:56 2020 VERIFY OK: depth=2, C=PA, O=NordVPN, CN=NordVPN Root CA,
Sun May 31 04:01:56 2020 VERIFY OK: depth=1, C=PA, O=NordVPN, CN=NordVPN CA4,
Sun May 31 04:01:56 2020 VERIFY KU OK,
Sun May 31 04:01:56 2020 Validating certificate extended key usage,
Sun May 31 04:01:56 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication,
Sun May 31 04:01:56 2020 VERIFY EKU OK,
Sun May 31 04:01:56 2020 VERIFY OK: depth=0, CN=fr530.nordvpn.com,
Sun May 31 04:01:56 2020 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Sun May 31 04:01:56 2020 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Sun May 31 04:01:56 2020 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 4096 bit RSA,
Sun May 31 05:01:56 2020 VERIFY OK: depth=2, C=PA, O=NordVPN, CN=NordVPN Root CA,
Sun May 31 05:01:56 2020 VERIFY OK: depth=1, C=PA, O=NordVPN, CN=NordVPN CA4,
Sun May 31 05:01:56 2020 VERIFY KU OK,
Sun May 31 05:01:56 2020 Validating certificate extended key usage,
Sun May 31 05:01:56 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication,
Sun May 31 05:01:56 2020 VERIFY EKU OK,
Sun May 31 05:01:56 2020 VERIFY OK: depth=0, CN=fr530.nordvpn.com,
Sun May 31 05:01:56 2020 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Sun May 31 05:01:56 2020 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Sun May 31 05:01:56 2020 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 4096 bit RSA,
Sun May 31 06:01:56 2020 VERIFY OK: depth=2, C=PA, O=NordVPN, CN=NordVPN Root CA,
Sun May 31 06:01:56 2020 VERIFY OK: depth=1, C=PA, O=NordVPN, CN=NordVPN CA4,
Sun May 31 06:01:56 2020 VERIFY KU OK,
Sun May 31 06:01:56 2020 Validating certificate extended key usage,
Sun May 31 06:01:56 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication,
Sun May 31 06:01:56 2020 VERIFY EKU OK,
Sun May 31 06:01:56 2020 VERIFY OK: depth=0, CN=fr530.nordvpn.com,
Sun May 31 06:01:56 2020 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Sun May 31 06:01:56 2020 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Sun May 31 06:01:56 2020 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 4096 bit RSA,
Sun May 31 07:01:56 2020 TLS: tls_process: killed expiring key,
Sun May 31 07:01:57 2020 VERIFY OK: depth=2, C=PA, O=NordVPN, CN=NordVPN Root CA,
Sun May 31 07:01:57 2020 VERIFY OK: depth=1, C=PA, O=NordVPN, CN=NordVPN CA4,
Sun May 31 07:01:57 2020 VERIFY KU OK,
Sun May 31 07:01:57 2020 Validating certificate extended key usage,
Sun May 31 07:01:57 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication,
Sun May 31 07:01:57 2020 VERIFY EKU OK,
Sun May 31 07:01:57 2020 VERIFY OK: depth=0, CN=fr530.nordvpn.com,
Sun May 31 07:01:57 2020 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Sun May 31 07:01:57 2020 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Sun May 31 07:01:57 2020 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 4096 bit RSA,
Sun May 31 08:01:57 2020 TLS: tls_process: killed expiring key,
Sun May 31 08:01:57 2020 VERIFY OK: depth=2, C=PA, O=NordVPN, CN=NordVPN Root CA,
Sun May 31 08:01:57 2020 VERIFY OK: depth=1, C=PA, O=NordVPN, CN=NordVPN CA4,
Sun May 31 08:01:57 2020 VERIFY KU OK,
Sun May 31 08:01:57 2020 Validating certificate extended key usage,
Sun May 31 08:01:57 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication,
Sun May 31 08:01:57 2020 VERIFY EKU OK,
Sun May 31 08:01:57 2020 VERIFY OK: depth=0, CN=fr530.nordvpn.com,
Sun May 31 08:01:57 2020 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Sun May 31 08:01:57 2020 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Sun May 31 08:01:57 2020 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 4096 bit RSA,
Sun May 31 09:01:57 2020 TLS: tls_process: killed expiring key,
Sun May 31 09:01:58 2020 VERIFY OK: depth=2, C=PA, O=NordVPN, CN=NordVPN Root CA,
Sun May 31 09:01:58 2020 VERIFY OK: depth=1, C=PA, O=NordVPN, CN=NordVPN CA4,
Sun May 31 09:01:58 2020 VERIFY KU OK,
Sun May 31 09:01:58 2020 Validating certificate extended key usage,
Sun May 31 09:01:58 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication,
Sun May 31 09:01:58 2020 VERIFY EKU OK,
Sun May 31 09:01:58 2020 VERIFY OK: depth=0, CN=fr530.nordvpn.com,
Sun May 31 09:01:58 2020 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Sun May 31 09:01:58 2020 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Sun May 31 09:01:58 2020 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 4096 bit RSA,
Sun May 31 10:01:58 2020 TLS: tls_process: killed expiring key,
Sun May 31 10:01:58 2020 VERIFY OK: depth=2, C=PA, O=NordVPN, CN=NordVPN Root CA,
Sun May 31 10:01:58 2020 VERIFY OK: depth=1, C=PA, O=NordVPN, CN=NordVPN CA4,
Sun May 31 10:01:58 2020 VERIFY KU OK,
Sun May 31 10:01:58 2020 Validating certificate extended key usage,
Sun May 31 10:01:58 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication,
Sun May 31 10:01:58 2020 VERIFY EKU OK,
Sun May 31 10:01:58 2020 VERIFY OK: depth=0, CN=fr530.nordvpn.com,
Sun May 31 10:01:59 2020 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Sun May 31 10:01:59 2020 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Sun May 31 10:01:59 2020 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 4096 bit RSA,
Sun May 31 11:01:58 2020 TLS: tls_process: killed expiring key,
Sun May 31 11:01:59 2020 VERIFY OK: depth=2, C=PA, O=NordVPN, CN=NordVPN Root CA,
Sun May 31 11:01:59 2020 VERIFY OK: depth=1, C=PA, O=NordVPN, CN=NordVPN CA4,
Sun May 31 11:01:59 2020 VERIFY KU OK,
Sun May 31 11:01:59 2020 Validating certificate extended key usage,
Sun May 31 11:01:59 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication,
Sun May 31 11:01:59 2020 VERIFY EKU OK,
Sun May 31 11:01:59 2020 VERIFY OK: depth=0, CN=fr530.nordvpn.com,
Sun May 31 11:01:59 2020 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Sun May 31 11:01:59 2020 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Sun May 31 11:01:59 2020 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 4096 bit RSA,
Sun May 31 12:01:59 2020 VERIFY OK: depth=2, C=PA, O=NordVPN, CN=NordVPN Root CA,
Sun May 31 12:01:59 2020 VERIFY OK: depth=1, C=PA, O=NordVPN, CN=NordVPN CA4,
Sun May 31 12:01:59 2020 VERIFY KU OK,
Sun May 31 12:01:59 2020 Validating certificate extended key usage,
Sun May 31 12:01:59 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication,
Sun May 31 12:01:59 2020 VERIFY EKU OK,
Sun May 31 12:01:59 2020 VERIFY OK: depth=0, CN=fr530.nordvpn.com,
Sun May 31 12:01:59 2020 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Sun May 31 12:01:59 2020 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Sun May 31 12:01:59 2020 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 4096 bit RSA,
```

Can anyone help me find out what is going wrong? Is this a docker networking issue?

Thanks,
