### ISSUE TITLE
Options error: You must define TUN/TAP device (--dev)

### ISSUE THREAD

**Issue by jonnyniv** [haugene/docker-transmission-openvpn#1254]
Using default compose file slightly modified to use airvpn gives me this error

```yaml
version: '3.3'
volumes:
  docker:
services:
    transmission-openvpn:
        volumes:
            - 'docker:/data'
            - '/etc/localtime:/etc/localtime:ro'
            - '/project/AirVPN_Europe_UDP-443.ovpn:/etc/openvpn/custom/default.ovpn'
        environment:
            - CREATE_TUN_DEVICE=true
            - OPENVPN_PROVIDER=CUSTOM
            # - OPENVPN_CONFIG=CA Toronto
            - OPENVPN_USERNAME=user
            - OPENVPN_PASSWORD=pass
            - WEBPROXY_ENABLED=false
            - LOCAL_NETWORK=192.168.0.0/24
        cap_add:
            - NET_ADMIN
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '9091:9091'
        image: haugene/transmission-openvpn
```

```
transmission-openvpn_1  | Using OpenVPN provider: CUSTOM
transmission-openvpn_1  | No VPN configuration provided. Using default.
transmission-openvpn_1  | Setting OPENVPN credentials...
transmission-openvpn_1  | adding route to local network 192.168.0.0/24 via 172.18.0.1 dev eth0
transmission-openvpn_1  | Sun Jun 14 10:47:49 2020 disabling NCP mode (--ncp-disable) because not in P2MP client or server mode
transmission-openvpn_1  | Options error: You must define TUN/TAP device (--dev)
transmission-openvpn_1  | Use --help for more information.
```

Running on Ubuntu, Docker version 19.03.11, build 42e35e61f3
