### ISSUE TITLE
DNS connection lost after some time

### ISSUE THREAD

**Issue by rogerfar** [haugene/docker-transmission-openvpn#1259]
I added DNS parameters to my docker-compose.yaml because I am having issues with OpenVPN not able to connect after a few days anymore:

```
Sun Jun 21 04:17:38 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Sun Jun 21 04:17:48 2020 RESOLVE: Cannot resolve host address: nl.windscribe.com:1194 (Temporary failure in name resolution)
Sun Jun 21 04:17:58 2020 RESOLVE: Cannot resolve host address: nl.windscribe.com:1194 (Temporary failure in name resolution)
Sun Jun 21 04:17:58 2020 Could not determine IPv4/IPv6 protocol
Sun Jun 21 04:17:58 2020 SIGUSR1[soft,init_instance] received, process restarting
```

My config has hardcoded DNS in it:
```
        dns:
            - 1.1.1.1
            - 1.0.0.1
```

When I start the container everything works fine, remote access is available, torrents work and when I remote in the shell I can do a DNS lookups.

But after a few days it stops, it's hard to pinpoint when exactly but usually it's about 3-4 days. Remote access still works, I can shell in the container, but DNS seems to have stopped. 

When I do something simple like `ping google.com` it can't resolve the hostname.

I'm running docker on Windows, this my docker-compose.yaml:

```
version: '3.3'
services:
    transmission-openvpn:
        container_name: transmission-vpn
        volumes:
            - 'D:/Downloads/:/data'
        image: haugene/transmission-openvpn
        environment:
            - CREATE_TUN_DEVICE=true
            - OPENVPN_PROVIDER=WINDSCRIBE
            - OPENVPN_CONFIG=Netherlands-udp
            - OPENVPN_USERNAME=
            - OPENVPN_PASSWORD=
            - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
            - WEBPROXY_ENABLED=false
            - LOCAL_NETWORK=192.168.0.0/16
            - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
            - TRANSMISSION_RPC_HOST_WHITELIST="127.0.0.1,192.168.*.*"
            - TRANSMISSION_RPC_USERNAME=
            - TRANSMISSION_RPC_PASSWORD=
        cap_add:
            - NET_ADMIN
        devices:
            - /dev/net/tun
        restart: always
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '9091:9091'
        dns:
            - 1.1.1.1
            - 1.0.0.1
```

What would be the way to troubleshoot this issue?
