### ISSUE TITLE
won't account for openvpn-config attribute

### ISSUE THREAD

**Issue by Snuffsis** [haugene/docker-transmission-openvpn#1269]
**Describe the problem**
Transmission-vpn doesn't seem to take the OPENVPN_CONFIG variable into account in my docker-compose file. It defaults back to the default one regardless of what I put there, I have tried both with and without quotes.
In my case it defaults back to the swedish ovpn file, and that one doesn't seem to work (can't ping the pool address proved) and the container reports back with
`Sun Jun 28 08:18:28 2020 us=406916 RESOLVE: Cannot resolve host address: pool-1.prd.se.ovpn.se:1195 (Name or service not known)`

**Add your docker run command**
```
transmission-vpn:
  container_name: transmission-vpn
  hostname: transmission
image: haugene/transmission-openvpn
cap_add:
- NET_ADMIN
devices:
- /dev/net/tun
restart: always
ports:
- "9091:9091"
dns:
- 1.1.1.1
- 1.0.0.1
volumes:
- /etc/localtime:/etc/localtime:ro
- ${USERDIR}/docker/transmission-vpn:/data
- ${USERDIR}/docker/shared:/shared
- ${USERDIR}/transmission/Downloads:/downloads
environment:
- OPENVPN_PROVIDER=OVPN
- OPENVPN_USERNAME=${OVPN_USER}
- OPENVPN_PASSWORD=${OVPN_PASS}
- OPENVPN_CONFIG=pool-1.prd.no.oslo.ovpn.com
- OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
- LOCAL_NETWORK=192.168.88.0/24
- PUID=${PUID}
- PGID=${PGID}
- TZ=${TZ}
- TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
- TRANSMISSION_RPC_HOST_WHITELIST="127.0.0.1,192.168.*.*"
- TRANSMISSION_RPC_PASSWORD=${TRANSMISSION_RPC_PASSWORD}
- TRANSMISSION_RPC_USERNAME=${TRANSMISSION_RPC_USERNAME}
- TRANSMISSION_RATIO_LIMIT=2
- TRANSMISSION_RATIO_LIMIT_ENABLED=false
- TRANSMISSION_ALT_SPEED_DOWN=2000
- TRANSMISSION_ALT_SPEED_ENABLED=false
- TRANSMISSION_ALT_SPEED_UP=15
- TRANSMISSION_SPEED_LIMIT_DOWN=6000
- TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED=false
- TRANSMISSION_SPEED_LIMIT_UP=30
- TRANSMISSION_SPEED_LIMIT_UP_ENABLED=false
- TRANSMISSION_INCOMPLETE_DIR=/downloads/incomplete
- TRANSMISSION_INCOMPLETE_DIR_ENABLED=true
- TRANSMISSION_WATCH_DIR_ENABLED=false
- TRANSMISSION_DOWNLOAD_DIR=/downloads/completed
- TRANSMISSION_PEER_PORT=58433
- TRANSMISSION_PEER_LIMIT_PER_TORRENT=5000
- TRANSMISSION_PEER_LIMIT_GLOBAL=20000
- TRANSMISSION_MAX_PEERS_GLOBAL=50000
- TRANSMISSION_DOWNLOAD_QUEUE_SIZE=10
sysctls:
- net.ipv6.conf.all.disable_ipv6=0
```

**Logs**

```
Sun Jun 28 08:18:28 2020 us=406916 RESOLVE: Cannot resolve host address: pool-1.prd.se.ovpn.se:1195 (Name or service not known),
Sun Jun 28 08:26:28 2020 us=492869 Restart pause, 300 second(s),
Sun Jun 28 08:26:28 2020 us=492829 SIGUSR1[soft,init_instance] received, process restarting,
Sun Jun 28 08:26:28 2020 us=492744 Could not determine IPv4/IPv6 protocol,
Sun Jun 28 08:26:28 2020 us=492702 RESOLVE: Cannot resolve host address: pool-1.prd.se.ovpn.se:1195 (Name or service not known),
Sun Jun 28 08:26:28 2020 us=483540 Expected Remote Options String (VER=V4): 'V4,dev-type tun,link-mtu 1558,tun-mtu 1500,proto UDPv4,comp-lzo,keydir 0,cipher AES-256-CBC,auth SHA1,keysize 256,tls-auth,key-method 2,tls-server',
Sun Jun 28 08:26:28 2020 us=483530 Local Options String (VER=V4): 'V4,dev-type tun,link-mtu 1558,tun-mtu 1500,proto UDPv4,comp-lzo,keydir 1,cipher AES-256-CBC,auth SHA1,keysize 256,tls-auth,key-method 2,tls-client',
Sun Jun 28 08:26:28 2020 us=483432 RESOLVE: Cannot resolve host address: pool-1.prd.se.ovpn.se:1195 (Name or service not known),
Sun Jun 28 08:26:28 2020 us=483471 Data Channel MTU parms [ L:1622 D:1450 EF:122 EB:406 ET:0 EL:3 ],
Sun Jun 28 08:26:28 2020 us=474836 Control Channel MTU parms [ L:1622 D:1184 EF:66 EB:0 ET:0 EL:3 ],
Sun Jun 28 08:26:28 2020 us=474736 LZO compression initializing,
Sun Jun 28 08:26:28 2020 us=474720 Re-using SSL/TLS context,
Sun Jun 28 08:26:28 2020 us=474670 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
```

**Host system:**
Docker version 19.03.10
Hostsystem:
```
NAME="Zorin OS"
VERSION="15.2"
ID=zorin
ID_LIKE=ubuntu
PRETTY_NAME="Zorin OS 15.2"
VERSION_ID="15"
HOME_URL="https://www.zorinos.com"
SUPPORT_URL="https://www.zorinos.com/help"
BUG_REPORT_URL="https://bugs.launchpad.net/zorin-os"
PRIVACY_POLICY_URL="https://www.zorinos.com/legal/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
