### ISSUE TITLE
Kubernetes Deploy

### ISSUE THREAD

**Issue by silverbullettruck2001** [haugene/docker-transmission-openvpn#1275]
I am trying to deploy this on my microk8s RPi cluster but I am getting issues with the deployment.  When I try to deploy with the below YAML it blows up because of the 'CREATE_TUN_DEVICE' environment variable.  If I take it out, I get an error saying that the 'dev/net/tun' doesn't exist.  Any thoughts on how I can work around this?

```YAML
kind: Deployment
apiVersion: apps/v1
metadata:
  name: transmission
  namespace: default
  labels:
    app: transmission
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transmission
  template:
    metadata:
      labels:
        app: transmission
    spec:
      volumes:
        - name: transmission-config-pv-storage
          persistentVolumeClaim:
            claimName: media-pv-claim
      containers:
        - name: transmission
          image: 'haugene/transmission-openvpn:latest-armhf'
          env:
            - name: OPENVPN_PROVIDER
              value: PIA
            - name: OPENVPN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: vpn-credentials
                  key: username
            - name: OPENVPN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vpn-credentials
                  key: password
            - name: OPENVPN_CONFIG
              value: CA Montreal
            - name: CREATE_TUN_DEVICE
              value: true
            - name: PGID
              value: '1000'
            - name: PUID
              value: '1000'
          volumeMounts:
            - name: transmission-config-pv-storage
              mountPath: /data
              subPath: transmission/data
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext:
        allowPrivilegeEscalation: true
        capabilities:
          add:
            - NET_ADMIN
        privileged: true
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
```

```
Using OpenVPN provider: PIA
Starting OpenVPN using config CA Montreal.ovpn
Setting OPENVPN credentials...
Thu Jul  2 21:56:25 2020 OpenVPN 2.4.7 arm-unknown-linux-gnueabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 20 2019
Thu Jul  2 21:56:25 2020 library versions: OpenSSL 1.1.1d  10 Sep 2019, LZO 2.10
Thu Jul  2 21:56:25 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Thu Jul  2 21:56:25 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]199.229.249.142:1198
Thu Jul  2 21:56:25 2020 UDP link local: (not bound)
Thu Jul  2 21:56:25 2020 UDP link remote: [AF_INET]199.229.249.142:1198
Thu Jul  2 21:56:25 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Thu Jul  2 21:56:25 2020 [bb17b76bafc34f6ab4e9608a15c1f7c7] Peer Connection Initiated with [AF_INET]199.229.249.142:1198
Thu Jul  2 21:56:26 2020 ERROR: Cannot open TUN/TAP dev /dev/net/tun: No such file or directory (errno=2)
Thu Jul  2 21:56:26 2020 Exiting due to fatal error
