### ISSUE TITLE
TLS Error:  TLS handsshake failed

### ISSUE THREAD

**Issue by survivalbloke** [haugene/docker-transmission-openvpn#1279]
**Describe the problem**
The container will not load in the web GUI due to an auth problem.  Details are below.  I'm using a provider which is not included.  Once I figure out how to include it and submit to github I will.  The provider is Usenet Express.  [Link to ovpn](https://www.usenetexpress.com/guides/post/Linux-CLI/).  I had this working a few months ago and I don't recall I changed anything.  Out of nowhere Transmission stopped loading.  I've finally gotten some time to have a look and this is what I found.  I thought perhaps the provider had updated the certificate so I used their .ovpn (linked above), but still didn't work.  Then I tried pinging the server and it wouldn't ping so I thought for sure that was the problem.  I updated the server(to one which pings) but still I cannot get past this TLS handshake issue.  I've submitted a ticket with UsenetExpress because I'm assuming since it's an auth problem, it is on their end but I wanted to submit a ticket here as well JUST IN CASE something with the container had changed and I need to modify my compose.  Thanks!

**Add your docker run command**
docker-compose.yml:
```
##--TRANSMISSION--################################################################
  transmission-vpn:
    container_name: transmission-vpn
    image: haugene/transmission-openvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: unless-stopped
    ports:
      - 9010:9091
      - 51413:51413
      - 51413:51413/udp
    volumes:
      - /home/mike/docker/transmission-vpn:/config
      - /etc/localtime:/etc/localtime:ro
      - /mnt/nasmedia/data/torrents:/data/torrents
      - /home/mike/docker/transmission-vpn/default.ovpn:/etc/openvpn/custom/default.ovpn
      - /home/mike/docker/transmission-vpn/openvpn-credentials.txt:/config/openvpn-credentials.txt
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - OPENVPN_PROVIDER=CUSTOM
        #      - OPENVPN_USERNAME=<redacted>
        #      - OPENVPN_PASSWORD=<redacted>
      - WEBPROXY_ENABLED=false
      - LOCAL_NETWORK=192.168.1.0/24
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      - TRANSMISSION_RPC_HOST_WHITELIST="127.0.0.1,192.168.*.*"
      - TRANSMISSION_RPC_PASSWORD=<redacted>
      - TRANSMISSION_RPC_USERNAME=mike
      - TRANSMISSION_UMASK=2
      - TRANSMISSION_RATIO_LIMIT=1.00
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
      - TRANSMISSION_DOWNLOAD_DIR=/data/torrents
      - TRANSMISSION_INCOMPLETE_DIR=/data/torrents
      - TRANSMISSION_WATCH_DIR=/data/torrents
      - TRANSMISSION_WATCH_DIR_ENABLED=true
      - TRANSMISSION_PORT_FORWARDING_ENABLED=true      
```

**Logs**
```
docker logs transmission-vpn 
Using OpenVPN provider: CUSTOM
No VPN configuration provided. Using default.
Found existing OPENVPN credentials...
adding route to local network 192.168.1.0/24 via 172.18.0.1 dev eth0
Sun Jul  5 11:51:00 2020 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Sep  5 2019
Sun Jul  5 11:51:00 2020 library versions: OpenSSL 1.1.1c  28 May 2019, LZO 2.10
Sun Jul  5 11:51:00 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Sun Jul  5 11:51:00 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]185.80.222.63:8080
Sun Jul  5 11:51:00 2020 UDP link local: (not bound)
Sun Jul  5 11:51:00 2020 UDP link remote: [AF_INET]185.80.222.63:8080
Sun Jul  5 11:52:00 2020 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Sun Jul  5 11:52:00 2020 TLS Error: TLS handshake failed
Sun Jul  5 11:52:00 2020 SIGUSR1[soft,tls-error] received, process restarting
Sun Jul  5 11:52:05 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts

```

**Host system:**
```
ubuntusrv0 5.4.0-37-generic #41-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux
```
**Docker --version:**
Docker version 19.03.8, build afacb8b7f0
