### ISSUE TITLE
Docker env variables not passed to script

### ISSUE THREAD

**Issue by therealthingy** [haugene/docker-transmission-openvpn#1292]
**Add your docker run command**

I'm using docker-compose.
Stripped down version of my `docker-compose.yml` file:
```
version: '2'
services:
 transmission:
  image: haugene/transmission-openvpn:latest-armhf
  restart: "no"
  cap_add:
    - NET_ADMIN
  devices:
    - /dev/net/tun

  ports:
    - "9091:9091"
    - "8888:8888"

  dns:
    - 8.8.8.8
    - 8.8.4.4

  volumes:
    - /etc/localtime:/etc/localtime:ro
    - ./scripts/transmission/hooks:/etc/scripts/hooks/
    - ${MOUNT_POINT}/var/${PUBLIC_DIR}/:/data
    - ${MOUNT_POINT}/etc/vpn-profiles/${VPN_CONFIG_FILE}:/etc/openvpn/custom/default.ovpn


  environment:
    - PUID=${PUID}
    - PGID=${PGID}
    - TZ=${TZ}
      
    - OPENVPN_PROVIDER=CUSTOM
    - OPENVPN_USERNAME=XXX
    - OPENVPN_PASSWORD=XXX
    - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      
    - LOCAL_NETWORK=${LOCAL_NETWORK}
    
    - TRANSMISSION_WEB_UI=kettu
    - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
    - TRANSMISSION_RPC_HOST_WHITELIST="127.0.0.1,192.168.*.*"
    - TRANSMISSION_RPC_USERNAME=${RPC_USERNAME}
    - TRANSMISSION_RPC_PASSWORD=${RPC_PASSWORD}
     
    - TRANSMISSION_UMASK=002
    - TRANSMISSION_HOME=./config
     
    - TRANSMISSION_RATIO_LIMIT=1.00
    - TRANSMISSION_RATIO_LIMIT_ENABLED=true
    - TRANSMISSION_BLOCKLIST_ENABLED=${BLOCKLIST_ENABLED}
    - TRANSMISSION_BLOCKLIST_URL=${BLOCKLIST_URL}
    - TRANSMISSION_DOWNLOAD_QUEUE_SIZE=${MAX_PARALLEL_DOWNLOADS}
    # - TRANSMISSION_ENCRYPTION=1 #prefer encrypted connections

    - TRANSMISSION_SCRIPT_TORRENT_DONE_ENABLED=true
    - TRANSMISSION_SCRIPT_TORRENT_DONE_FILENAME=/etc/scripts/hooks/send-email-when-torrent-done.sh
    - NOTIFICATION_MAIL_SMTP_SERVER_HOST=${NOTIFICATIONS_MAIL_SERVER_HOST}
    - NOTIFICATION_MAIL_SMTP_SERVER_PORT=465
    - NOTIFICATION_MAIL_SERVER_USERNAME=${NOTIFICATIONS_MAIL_SERVER_USERNAME}
    - NOTIFICATION_MAIL_SERVER_PASSWORD=${NOTIFICATIONS_MAIL_SERVER_PASSWORD}
    - NOTIFICATION_MAIL_TO_ADDR=${SYSTEM_ADMIN_MAIL}
    - NOTIFICATION_MAIL_HIDE_FILENAME=false

  [...]
```

My test script (`send-email-when-torrent-done.sh`):
```
#!/bin/bash
env |grep 'NOTIFICATION_' > /etc/scripts/hooks/foo.txt
```

**Describe the problem/Logs**

The Docker environment variables (defined in `docker-compose.yml`) are correctly set within the container:
```
pi@rpi:~ $ docker container exec transmission env |grep 'NOTIFICATION_'
NOTIFICATION_MAIL_SMTP_SERVER_HOST=smtp.gmail.com
NOTIFICATION_MAIL_SMTP_SERVER_PORT=465
NOTIFICATION_MAIL_SERVER_USERNAME=****@gmail.com
NOTIFICATION_MAIL_SERVER_PASSWORD=****
NOTIFICATION_MAIL_TO_ADDR=****@gmail.com
NOTIFICATION_MAIL_HIDE_FILENAME=false
```

However, those envs don't seem to get passed to the script (when download has finished):
```
pi@rpi:~/docker/transmission/scripts/transmission/hooks $ cat foo.txt 
````

So my question: Is this behaviour to be expected or am I doing sth wrong?

Thanks!
Awesome work btw

**Host system:**

```
pi@rpi:~ $ uname -a
Linux rpi 4.19.118-v7l+ #1311 SMP Mon Apr 27 14:26:42 BST 2020 armv7l GNU/Linux

pi@rpi:~ $ docker --version
Docker version 19.03.12, build 48a6621
```
