### ISSUE TITLE
Timeouts & Process Exiting

### ISSUE THREAD

**Issue by aaronfagan** [haugene/docker-transmission-openvpn#1297]
**Describe the problem**
I have been running this container for more than a year without issue. However recently, the container has started exited shortly after booting.

**Add your docker run command**
See above, however, I am using the following `docker-compose.yml`:

```
version: '3.5'
services:
  transmission:
    image: haugene/transmission-openvpn:latest
    container_name: transmission
    hostname: transmission
    privileged: true
    env_file:
      - ./.env
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - ${DIR_MOUNT}/config:/config
      - ${DIR_MOUNT}:/data
    restart: unless-stopped
networks:
  default:
    external:
      name: homeserver
```

**Logs**
```
$ docker-compose up --build --force-recreate
Recreating transmission ... done
Attaching to transmission
transmission    | Using OpenVPN provider: PIA
transmission    | Starting OpenVPN using config US Seattle.ovpn
transmission    | Setting OPENVPN credentials...
transmission    | adding route to local network 192.168.1.0/24 via 172.18.0.1 dev eth0
transmission    | Fri Jul 17 10:18:00 2020 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Sep  5 2019
transmission    | Fri Jul 17 10:18:00 2020 library versions: OpenSSL 1.1.1c  28 May 2019, LZO 2.10
transmission    | Fri Jul 17 10:18:00 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
transmission    | Fri Jul 17 10:18:00 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]104.200.154.22:1198
transmission    | Fri Jul 17 10:18:00 2020 UDP link local: (not bound)
transmission    | Fri Jul 17 10:18:00 2020 UDP link remote: [AF_INET]104.200.154.22:1198
transmission    | Fri Jul 17 10:19:01 2020 [UNDEF] Inactivity timeout (--ping-exit), exiting
transmission    | Fri Jul 17 10:19:01 2020 SIGTERM[soft,ping-exit] received, process exiting
```

**Host system:**
MacOS 10.13.16 (High Sierra)
