### ISSUE TITLE
latest-armhf are tagged as linux/amd64

### ISSUE THREAD

**Issue by duviful** [haugene/docker-transmission-openvpn#1304]
**Describe the problem**
Hello, when running as a stack in a docker swarm environment, the service is not able to start due to this error:

Error message | no suitable node (unsupported platform on 4 nodes)

Apparently, the image pulled from docker hub (latest-armhf) is tagged as a linux/amd64 image and not as a linux/arm/v7

**Add your docker run command**
this is the docker-compose i'm running
```
version: '3.3'
services:
  transmission-openvpn:
    image: haugene/transmission-openvpn:latest-armhf
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
            - /media/:/data
            - /etc/localtime:/etc/localtime:ro
    environment:
            - CREATE_TUN_DEVICE=true
            - OPENVPN_PROVIDER=PROTONVPN
            - OPENVPN_CONFIG=
            - OPENVPN_USERNAME=
            - OPENVPN_PASSWORD=
            - WEBPROXY_ENABLED=false
            - LOCAL_NETWORK=
    cap_add:
            - NET_ADMIN
    ports:
            - 9091:9091
```

**Logs**
I extracted this information inspecting the service

```
"Labels": {
   "com.docker.stack.image": "haugene/transmission-openvpn:latest-armhf",
   "com.docker.stack.namespace": "transmission"
 }
"Platforms": [
    {
     "Architecture": "amd64",
     "OS": "linux"
     }
```
 

**Host system:**
The stack is compose by 4x rpi 3b +
