### ISSUE TITLE
Cpu at 100%

### ISSUE THREAD

**Issue by svh1985** [haugene/docker-transmission-openvpn#1308]
**Describe the problem**
Every now and then the transmission processes will run at 100% CPU until I restart the container. The container status is unhealthy but it will not restart even when applying the restart option.
<img width="884" alt="Screenshot 2020-08-01 at 10 13 56" src="https://user-images.githubusercontent.com/5213210/89100705-83d03800-d3f9-11ea-9a0f-400eeb8126a7.png">
<img width="1587" alt="Screenshot 2020-08-01 at 10 16 22" src="https://user-images.githubusercontent.com/5213210/89100707-86cb2880-d3f9-11ea-9d11-e90a862fc142.png">

**Add your docker run command**
```
  transmission-openvpn:
    hostname: transmission
    cap_add:
    - NET_ADMIN
    dns:
    - 1.1.1.1
    - 8.8.8.8
    container_name: transmission-openvpn
    environment:
      CREATE_TUN_DEVICE: "true"
      HEALTH_CHECK_HOST: google.com
      OPENVPN_OPTS: "--inactive 3600 --ping 10 --ping-exit 60"
      LOCAL_NETWORK: 172.16.0.0/24
      NORDVPN_CATEGORY: ${NORDVPN_CATEGORY}
      NORDVPN_COUNTRY: ${NORDVPN_COUNTRY}
      NORDVPN_PROTOCOL: ${NORDVPN_PROTOCOL}
      OPENVPN_PASSWORD: ${OPENVPN_PASSWORD}
      OPENVPN_PROVIDER: ${OPENVPN_PROVIDER}
      OPENVPN_USERNAME: ${OPENVPN_USERNAME}
      PGID: ${PGID}
      PUID: ${PUID}
      TRANSMISSION_DOWNLOAD_DIR: /downloads/completed
      TRANSMISSION_HOME: /config
      TRANSMISSION_IDLE_SEEDING_LIMIT: 0
      TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED: "true"
      TRANSMISSION_INCOMPLETE_DIR: /downloads/incomplete
      TRANSMISSION_RATIO_LIMIT: 0.0
      TRANSMISSION_RATIO_LIMIT_ENABLED: "true"
      TRANSMISSION_WATCH_DIR: /downloads/torrent
      TRANSMISSION_WEB_UI: transmission-web-control
      WEBPROXY_ENABLED: "false"
    image: haugene/transmission-openvpn:latest #or latest-armhf on ARM devices
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
    - 9091:9091/tcp
    restart: always
    labels: 
      com.centurylinklabs.watchtower.enable: "true"
    volumes:
    - ${DATADIR}/downloads:/downloads:rw
    - ${CONFIGDIR}/transmission-openvpn/config:/config:rw
    - ${CONFIGDIR}/transmission-openvpn/data:/data:rw
    - /etc/localtime:/etc/localtime:ro
```

**Logs**
```
Sat Jul 11 07:33:21 2020 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Sat Jul 11 07:33:21 2020 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 4096 bit RSA,
Sat Jul 11 08:33:21 2020 TLS: tls_process: killed expiring key,
Sat Jul 11 08:33:21 2020 VERIFY OK: depth=2, C=PA, O=NordVPN, CN=NordVPN Root CA,
Sat Jul 11 08:33:21 2020 VERIFY OK: depth=1, C=PA, O=NordVPN, CN=NordVPN CA5,
Sat Jul 11 08:33:21 2020 VERIFY KU OK,
Sat Jul 11 08:33:21 2020 Validating certificate extended key usage,
Sat Jul 11 08:33:21 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication,
Sat Jul 11 08:33:21 2020 VERIFY EKU OK,
Sat Jul 11 08:33:21 2020 VERIFY OK: depth=0, CN=nl736.nordvpn.com,
Sat Jul 11 08:33:21 2020 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Sat Jul 11 08:33:21 2020 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Sat Jul 11 08:33:21 2020 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 4096 bit RSA,
Sat Jul 11 09:33:21 2020 TLS: tls_process: killed expiring key,
Sat Jul 11 09:33:21 2020 VERIFY OK: depth=2, C=PA, O=NordVPN, CN=NordVPN Root CA,
Sat Jul 11 09:33:21 2020 VERIFY OK: depth=1, C=PA, O=NordVPN, CN=NordVPN CA5,
Sat Jul 11 09:33:21 2020 VERIFY KU OK,
Sat Jul 11 09:33:21 2020 Validating certificate extended key usage,
Sat Jul 11 09:33:21 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication,
Sat Jul 11 09:33:21 2020 VERIFY EKU OK,
Sat Jul 11 09:33:21 2020 VERIFY OK: depth=0, CN=nl736.nordvpn.com,
Sat Jul 11 09:33:21 2020 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Sat Jul 11 09:33:21 2020 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Sat Jul 11 09:33:21 2020 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 4096 bit RSA,
Sat Jul 11 10:33:21 2020 TLS: tls_process: killed expiring key,
Sat Jul 11 10:33:21 2020 VERIFY OK: depth=2, C=PA, O=NordVPN, CN=NordVPN Root CA,
Sat Jul 11 10:33:21 2020 VERIFY OK: depth=1, C=PA, O=NordVPN, CN=NordVPN CA5,
Sat Jul 11 10:33:21 2020 VERIFY KU OK,
Sat Jul 11 10:33:21 2020 Validating certificate extended key usage,
Sat Jul 11 10:33:21 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication,
Sat Jul 11 10:33:21 2020 VERIFY EKU OK,
Sat Jul 11 10:33:21 2020 VERIFY OK: depth=0, CN=nl736.nordvpn.com,
Sat Jul 11 10:33:21 2020 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Sat Jul 11 10:33:21 2020 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Sat Jul 11 10:33:21 2020 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 4096 bit RSA,
Sat Jul 11 11:33:21 2020 TLS: tls_process: killed expiring key,
Sat Jul 11 11:33:21 2020 VERIFY OK: depth=2, C=PA, O=NordVPN, CN=NordVPN Root CA,
Sat Jul 11 11:33:21 2020 VERIFY OK: depth=1, C=PA, O=NordVPN, CN=NordVPN CA5,
Sat Jul 11 11:33:21 2020 VERIFY KU OK,
Sat Jul 11 11:33:21 2020 Validating certificate extended key usage,
Sat Jul 11 11:33:21 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication,
Sat Jul 11 11:33:21 2020 VERIFY EKU OK,
Sat Jul 11 11:33:21 2020 VERIFY OK: depth=0, CN=nl736.nordvpn.com,
Sat Jul 11 11:33:21 2020 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Sat Jul 11 11:33:21 2020 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Sat Jul 11 11:33:21 2020 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 4096 bit RSA,
Sat Jul 11 12:33:21 2020 TLS: tls_process: killed expiring key,
Sat Jul 11 12:33:21 2020 VERIFY OK: depth=2, C=PA, O=NordVPN, CN=NordVPN Root CA,
Sat Jul 11 12:33:21 2020 VERIFY OK: depth=1, C=PA, O=NordVPN, CN=NordVPN CA5,
Sat Jul 11 12:33:21 2020 VERIFY KU OK,
Sat Jul 11 12:33:21 2020 Validating certificate extended key usage,
Sat Jul 11 12:33:21 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication,
Sat Jul 11 12:33:21 2020 VERIFY EKU OK,
Sat Jul 11 12:33:21 2020 VERIFY OK: depth=0, CN=nl736.nordvpn.com,
Sat Jul 11 12:33:21 2020 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Sat Jul 11 12:33:21 2020 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Sat Jul 11 12:33:21 2020 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 4096 bit RSA,
Sat Jul 11 13:33:21 2020 TLS: tls_process: killed expiring key,
Sat Jul 11 13:33:21 2020 VERIFY OK: depth=2, C=PA, O=NordVPN, CN=NordVPN Root CA,
Sat Jul 11 13:33:21 2020 VERIFY OK: depth=1, C=PA, O=NordVPN, CN=NordVPN CA5,
Sat Jul 11 13:33:21 2020 VERIFY KU OK,
Sat Jul 11 13:33:21 2020 Validating certificate extended key usage,
Sat Jul 11 13:33:21 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication,
Sat Jul 11 13:33:21 2020 VERIFY EKU OK,
Sat Jul 11 13:33:21 2020 VERIFY OK: depth=0, CN=nl736.nordvpn.com,
Sat Jul 11 13:33:21 2020 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Sat Jul 11 13:33:21 2020 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Sat Jul 11 13:33:21 2020 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 4096 bit RSA,
Sat Jul 11 14:33:21 2020 TLS: tls_process: killed expiring key,
Sat Jul 11 14:33:21 2020 VERIFY OK: depth=2, C=PA, O=NordVPN, CN=NordVPN Root CA,
Sat Jul 11 14:33:21 2020 VERIFY OK: depth=1, C=PA, O=NordVPN, CN=NordVPN CA5,
Sat Jul 11 14:33:21 2020 VERIFY KU OK,
Sat Jul 11 14:33:21 2020 Validating certificate extended key usage,
Sat Jul 11 14:33:21 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication,
Sat Jul 11 14:33:21 2020 VERIFY EKU OK,
Sat Jul 11 14:33:21 2020 VERIFY OK: depth=0, CN=nl736.nordvpn.com,
Sat Jul 11 14:33:21 2020 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Sat Jul 11 14:33:21 2020 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Sat Jul 11 14:33:21 2020 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 4096 bit RSA,
Sat Jul 11 15:33:21 2020 TLS: tls_process: killed expiring key,
Sat Jul 11 15:33:22 2020 VERIFY OK: depth=2, C=PA, O=NordVPN, CN=NordVPN Root CA,
Sat Jul 11 15:33:22 2020 VERIFY OK: depth=1, C=PA, O=NordVPN, CN=NordVPN CA5,
Sat Jul 11 15:33:22 2020 VERIFY KU OK,
Sat Jul 11 15:33:22 2020 Validating certificate extended key usage,
Sat Jul 11 15:33:22 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication,
Sat Jul 11 15:33:22 2020 VERIFY EKU OK,
Sat Jul 11 15:33:22 2020 VERIFY OK: depth=0, CN=nl736.nordvpn.com,
Sat Jul 11 15:33:22 2020 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Sat Jul 11 15:33:22 2020 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Sat Jul 11 15:33:22 2020 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 4096 bit RSA,
Sat Jul 11 16:33:22 2020 VERIFY OK: depth=2, C=PA, O=NordVPN, CN=NordVPN Root CA,
Sat Jul 11 16:33:22 2020 VERIFY OK: depth=1, C=PA, O=NordVPN, CN=NordVPN CA5,
Sat Jul 11 16:33:22 2020 VERIFY KU OK,
Sat Jul 11 16:33:22 2020 Validating certificate extended key usage,
Sat Jul 11 16:33:22 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication,
Sat Jul 11 16:33:22 2020 VERIFY EKU OK,
Sat Jul 11 16:33:22 2020 VERIFY OK: depth=0, CN=nl736.nordvpn.com,
Sat Jul 11 16:33:22 2020 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Sat Jul 11 16:33:22 2020 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Sat Jul 11 16:33:22 2020 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 4096 bit RSA,

```
**Host system:**

Ubuntu 20.04

Docker:
Client:
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.13.8
 Git commit:        afacb8b7f0
 Built:             Tue Jun 23 22:26:12 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       afacb8b7f0
  Built:            Thu Jun 18 08:26:54 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu2
  GitCommit:
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:
 docker-init:
  Version:          0.18.0
  GitCommit:
