### ISSUE TITLE
Container exit with code 137

### ISSUE THREAD

**Issue by kimahry** [haugene/docker-transmission-openvpn#1310]
**Describe the problem**

The vpn connect and the transmisstion application start but the container stop with a exit code 137.
Sometime the container exit with that code even before the vpn connect

**Add your docker run command**

```
version: '3.5'
services:
    transmission:
        image: haugene/transmission-openvpn
        container_name: transmission
        privileged: true
        volumes:
            - '/share/Container/:/data'
            - '/etc/localtime:/etc/localtime:ro'
        environment:
            - OPENVPN_OPTS=--comp-lzo --tun-mtu 1500
            - CREATE_TUN_DEVICE=${CREATE_TUN_DEVICE}
            - OPENVPN_PROVIDER=${OPENVPN_PROVIDER}
            - OPENVPN_CONFIG=${OPENVPN_CONFIG}
            - OPENVPN_USERNAME=${OPENVPN_USERNAME}
            - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
            - WEBPROXY_ENABLED=${WEBPROXY_ENABLED}
            - LOCAL_NETWORK=${LOCAL_NETWORK}
        cap_add:
            - NET_ADMIN
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '9091:9091'
        sysctls:
          - net.ipv6.conf.all.disable_ipv6=0
```
**Logs**

```
transmission    | mknod: /dev/net/tun: File exists
transmission    | Using OpenVPN provider: MULLVAD
transmission    | Starting OpenVPN using config mullvad_de-fra_tcp443.ovpn
transmission    | Setting OPENVPN credentials...
transmission    | adding route to local network 192.168.15.0/24 via 172.29.4.1 dev eth0
transmission    | Sun Aug  2 13:40:36 2020 Note: option tun-ipv6 is ignored because modern operating systems do not need special IPv6 tun handling anymore.
transmission    | Sun Aug  2 13:40:36 2020 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Sep  5 2019
transmission    | Sun Aug  2 13:40:36 2020 library versions: OpenSSL 1.1.1c  28 May 2019, LZO 2.10
transmission    | Sun Aug  2 13:40:36 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
transmission    | Sun Aug  2 13:40:36 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]185.213.155.139:443
transmission    | Sun Aug  2 13:40:36 2020 Socket Buffers: R=[1638400->1048576] S=[1638400->1048576]
transmission    | Sun Aug  2 13:40:36 2020 Attempting to establish TCP connection with [AF_INET]185.213.155.139:443 [nonblock]
transmission    | Sun Aug  2 13:40:37 2020 TCP connection established with [AF_INET]185.213.155.139:443
transmission    | Sun Aug  2 13:40:37 2020 TCP_CLIENT link local: (not bound)
transmission    | Sun Aug  2 13:40:37 2020 TCP_CLIENT link remote: [AF_INET]185.213.155.139:443
transmission    | Sun Aug  2 13:40:37 2020 TLS: Initial packet from [AF_INET]185.213.155.139:443, sid=ca935963 c9f09f6f
transmission    | Sun Aug  2 13:40:37 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
transmission    | Sun Aug  2 13:40:37 2020 VERIFY OK: depth=2, C=SE, ST=Gotaland, L=Gothenburg, O=Amagicom AB, OU=Mullvad, CN=Mullvad Root CA v2, emailAddress=security@mullvad.net
transmission    | Sun Aug  2 13:40:37 2020 VERIFY OK: depth=1, C=SE, ST=Gotaland, O=Amagicom AB, OU=Mullvad, CN=Mullvad Intermediate CA v2, emailAddress=security@mullvad.net
transmission    | Sun Aug  2 13:40:37 2020 VERIFY KU OK
transmission    | Sun Aug  2 13:40:37 2020 Validating certificate extended key usage
transmission    | Sun Aug  2 13:40:37 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
transmission    | Sun Aug  2 13:40:37 2020 VERIFY EKU OK
transmission    | Sun Aug  2 13:40:37 2020 VERIFY OK: depth=0, C=SE, ST=Gotaland, O=Amagicom AB, OU=Mullvad, CN=de-fra-009.mullvad.net, emailAddress=security@mullvad.net
transmission    | Sun Aug  2 13:40:37 2020 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_CHACHA20_POLY1305_SHA256, 4096 bit RSA
transmission    | Sun Aug  2 13:40:37 2020 [de-fra-009.mullvad.net] Peer Connection Initiated with [AF_INET]185.213.155.139:443
transmission    | Sun Aug  2 13:40:38 2020 SENT CONTROL [de-fra-009.mullvad.net]: 'PUSH_REQUEST' (status=1)
transmission    | Sun Aug  2 13:40:39 2020 PUSH: Received control message: 'PUSH_REPLY,dhcp-option DNS 10.5.0.1,redirect-gateway def1 bypass-dhcp,route-ipv6 0000::/2,route-ipv6 4000::/2,route-ipv6 8000::/2,route-ipv6 C000::/2,comp-lzo no,route-gateway 10.5.0.1,topology subnet,socket-flags TCP_NODELAY,ifconfig-ipv6 fdda:d0d0:cafe:443::1003/64 fdda:d0d0:cafe:443::,ifconfig 10.5.0.5 255.255.0.0,peer-id 0,cipher AES-256-GCM'
transmission    | Sun Aug  2 13:40:39 2020 OPTIONS IMPORT: compression parms modified
transmission    | Sun Aug  2 13:40:39 2020 OPTIONS IMPORT: --socket-flags option modified
transmission    | Sun Aug  2 13:40:39 2020 Socket flags: TCP_NODELAY=1 succeeded
transmission    | Sun Aug  2 13:40:39 2020 OPTIONS IMPORT: --ifconfig/up options modified
transmission    | Sun Aug  2 13:40:39 2020 OPTIONS IMPORT: route options modified
transmission    | Sun Aug  2 13:40:39 2020 OPTIONS IMPORT: route-related options modified
transmission    | Sun Aug  2 13:40:39 2020 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
transmission    | Sun Aug  2 13:40:39 2020 OPTIONS IMPORT: peer-id set
transmission    | Sun Aug  2 13:40:39 2020 OPTIONS IMPORT: adjusting link_mtu to 1627
transmission    | Sun Aug  2 13:40:39 2020 OPTIONS IMPORT: data channel crypto options modified
transmission    | Sun Aug  2 13:40:39 2020 Data Channel: using negotiated cipher 'AES-256-GCM'
transmission    | Sun Aug  2 13:40:39 2020 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
transmission    | Sun Aug  2 13:40:39 2020 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
transmission    | Sun Aug  2 13:40:39 2020 ROUTE_GATEWAY 172.29.4.1/255.255.252.0 IFACE=eth0 HWADDR=02:42:ac:1d:04:02
transmission    | Sun Aug  2 13:40:39 2020 GDG6: remote_host_ipv6=n/a
transmission    | Sun Aug  2 13:40:39 2020 ROUTE6: default_gateway=UNDEF
transmission    | Sun Aug  2 13:40:39 2020 TUN/TAP device tun0 opened
transmission    | Sun Aug  2 13:40:39 2020 TUN/TAP TX queue length set to 100
transmission    | Sun Aug  2 13:40:39 2020 /sbin/ip link set dev tun0 up mtu 1500
transmission    | Sun Aug  2 13:40:39 2020 /sbin/ip addr add dev tun0 10.5.0.5/16 broadcast 10.5.255.255
transmission    | Sun Aug  2 13:40:39 2020 /sbin/ip -6 addr add fdda:d0d0:cafe:443::1003/64 dev tun0
transmission    | Sun Aug  2 13:40:39 2020 /etc/openvpn/tunnelUp.sh tun0 1500 1555 10.5.0.5 255.255.0.0 init
transmission    | Up script executed with tun0 1500 1555 10.5.0.5 255.255.0.0 init
transmission    | Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.5.0.5
transmission    | Generating transmission settings.json from env variables
transmission    | sed'ing True to true
transmission    |
transmission    | -------------------------------------
transmission    | Transmission will run as
transmission    | -------------------------------------
transmission    | User name:   root
transmission    | User uid:    0
transmission    | User gid:    0
transmission    | -------------------------------------
transmission    |
transmission    | STARTING TRANSMISSION
transmission    | NO PORT UPDATER FOR THIS PROVIDER
transmission    | Transmission startup script complete.
transmission    | Sun Aug  2 13:40:39 2020 /sbin/ip route add 185.213.155.139/32 via 172.29.4.1
transmission    | Sun Aug  2 13:40:39 2020 /sbin/ip route add 0.0.0.0/1 via 10.5.0.1
transmission    | Sun Aug  2 13:40:39 2020 /sbin/ip route add 128.0.0.0/1 via 10.5.0.1
transmission    | Sun Aug  2 13:40:39 2020 add_route_ipv6(::/2 -> fdda:d0d0:cafe:443:: metric -1) dev tun0
transmission    | Sun Aug  2 13:40:39 2020 /sbin/ip -6 route add ::/2 dev tun0
transmission    | Sun Aug  2 13:40:39 2020 add_route_ipv6(4000::/2 -> fdda:d0d0:cafe:443:: metric -1) dev tun0
transmission    | Sun Aug  2 13:40:39 2020 /sbin/ip -6 route add 4000::/2 dev tun0
transmission    | Sun Aug  2 13:40:39 2020 add_route_ipv6(8000::/2 -> fdda:d0d0:cafe:443:: metric -1) dev tun0
transmission    | Sun Aug  2 13:40:39 2020 /sbin/ip -6 route add 8000::/2 dev tun0
transmission    | Sun Aug  2 13:40:39 2020 add_route_ipv6(c000::/2 -> fdda:d0d0:cafe:443:: metric -1) dev tun0
transmission    | Sun Aug  2 13:40:39 2020 /sbin/ip -6 route add c000::/2 dev tun0
transmission    | Sun Aug  2 13:40:39 2020 Initialization Sequence Completed
transmission exited with code 137
```

**Host system:**

I'm running on Qnap 4.4.3.1381 with Docker version 17.09.1-ce, build 0bbe3ac
