### ISSUE TITLE
Transmission caught in crash loop with alpine-latest container

### ISSUE THREAD

**Issue by Iristyle** [haugene/docker-transmission-openvpn#1320]
**Describe the problem**

Transmission is stuck in a crash loop and no longer starts properly. I have Ouroboros run every night so that I'm always on latest of all the containers I run.  A couple of hours ago it upgraded transmission because it saw a new latest container (and this is what my notification says):

> transmission updated from 013d59dc41 to 7b1dc57540

Oddly the SHA I see in docker hub for `alpine-latest` is not what's being reported on my system:

> haugene/transmission-openvpn:latest-alpine@sha256:7b1dc57540291444782d70f3e0ac740808935b46a848bea94cb6c53bca4701fa

**Add your docker run command**

I don't think the compose file is relevant here as this has worked without changes for months, but I'll include the transmission part anyhow for posterity:

```
 transmission:
    container_name: transmission
    image: haugene/transmission-openvpn:latest-alpine
    restart: unless-stopped
    environment:
      - PUID=1031 # Transmission user
      - PGID=65536 # Download group
      # Necessary for AirVPN which has user specific configs / passwords
      - OPENVPN_PROVIDER=CUSTOM
      # Doesn't need to be set at all
      - OPENVPN_USERNAME=dummy
      - OPENVPN_PASSWORD=dummy
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      # Allows access to Transmission web page from local network
      - LOCAL_NETWORK=192.168.0.0/24
      - CREATE_TUN_DEVICE=true
      - TRANSMISSION_DOWNLOAD_DIR=/volume1/Media/Downloads/Transmission/completed
      - TRANSMISSION_INCOMPLETE_DIR=/volume1/Media/Downloads/Transmission/incomplete
      - TRANSMISSION_UMASK=002
      - TRANSMISSION_PEER_LIMIT_GLOBAL=400
      - TRANSMISSION_PEER_LIMIT_PER_TORRENT=40
      - TRANSMISSION_PEER_PORT=36226
      - TRANSMISSION_PORT_FORWARDING_ENABLED=true
      - TRANSMISSION_DOWNLOAD_QUEUE_SIZE=100
      - TRANSMISSION_SEED_QUEUE_ENABLED=true
      - TRANSMISSION_SEED_QUEUE_SIZE=5
      # When to stop seeding
      - TRANSMISSION_RATIO_LIMIT=1.1
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
      - TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED=true
      # For tools like Sonarr / Radarr to authenticate against
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      - TRANSMISSION_RPC_PASSWORD=REDACTED
      - TRANSMISSION_RPC_PORT=9091
      - TRANSMISSION_RPC_USERNAME=admin
      - TRANSMISSION_WATCH_DIR=/volume1/Media/Downloads/Transmission/watch
      - TRANSMISSION_WATCH_DIR_ENABLED=true
      # Where data like logs / settings are written to
      - TRANSMISSION_HOME=/config
    ports:
      - 8888:8888
      - 9091:9091
    volumes:
      - /volume1/docker/transmissiondata/config:/config
      - /volume1/docker/transmissiondata/resolv.conf:/etc/resolv.conf
      - /volume1/docker/transmissiondata/AirVPN_America_UDP-443.ovpn:/etc/openvpn/custom/default.ovpn
      - /volume1/Media/Downloads/Transmission:/volume1/Media/Downloads/Transmission
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    # Synology needs this to function properly!
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
```

**Logs**

It appears that `/config/settings.json` might be getting created incorrectly based on:

> JSON parse failed in /config/settings.json at pos 2281: INVALID_NUMBER -- remaining text "02,,    "upload-",

```
Up script executed with tun0 1500 1553 10.XXX.XXX.XXX 255.255.255.0 init,
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.XXX.XXX.XXX,
Generating transmission settings.json from env variables,
sed'ing True to true,
Enforcing ownership on transmission config directories,
Applying permissions to transmission config directories,
Setting owner for transmission paths to 1031:65536,
Setting permission for files (644) and directories (755),
Setting permission for watch directory (775) and its files (664),
,
-------------------------------------,
Transmission will run as,
-------------------------------------,
User name:   abc,
User uid:    1031,
User gid:    65536,
-------------------------------------,
,
STARTING TRANSMISSION,
NO PORT UPDATER FOR THIS PROVIDER,
Transmission startup script complete.,
[2020-08-07 06:45:17.393] JSON parse failed in /config/settings.json at pos 2281: INVALID_NUMBER -- remaining text "02,,
    "upload-",
Fri Aug  7 06:45:22 2020 /sbin/ip route add 184.75.XXX.XXX/32 via 172.19.0.1,
Fri Aug  7 06:45:22 2020 /sbin/ip route add 0.0.0.0/1 via 10.XXX.XXX.1,
Fri Aug  7 06:45:22 2020 /sbin/ip route add 128.0.0.0/1 via 10.XXX.XXX.1,
Fri Aug  7 06:45:22 2020 Initialization Sequence Completed,
Fri Aug  7 06:50:03 2020 event_wait : Interrupted system call (code=4),
Fri Aug  7 06:50:03 2020 SIGTERM received, sending exit notification to peer,
Fri Aug  7 06:50:08 2020 /sbin/ip route del 184.75.XXX.XXX/32,
Fri Aug  7 06:50:08 2020 /sbin/ip route del 0.0.0.0/1,
Fri Aug  7 06:50:08 2020 /sbin/ip route del 128.0.0.0/1,
Fri Aug  7 06:50:08 2020 Closing TUN/TAP interface,
Fri Aug  7 06:50:08 2020 /sbin/ip addr del dev tun0 10.XX.XX.XX/24,
Fri Aug  7 06:50:08 2020 /etc/openvpn/tunnelDown.sh tun0 1500 1553 10.XX.XX.XX 255.255.255.0 init,
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec],
Fri Aug  7 06:50:08 2020 SIGTERM[soft,exit-with-notification] received, process exiting,
mknod: /dev/net/tun: File exists,
Using OpenVPN provider: CUSTOM,
No VPN configuration provided. Using default.,
Setting OPENVPN credentials...,
adding route to local network 192.168.0.0/24 via 172.19.0.1 dev eth0,
Fri Aug  7 06:50:12 2020 OpenVPN 2.4.9 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Apr 20 2020,
Fri Aug  7 06:50:12 2020 library versions: OpenSSL 1.1.1g  21 Apr 2020, LZO 2.10,
Fri Aug  7 06:50:12 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts,
Fri Aug  7 06:50:12 2020 Outgoing Control Channel Authentication: Using 160 bit message hash 'SHA1' for HMAC authentication,
Fri Aug  7 06:50:12 2020 Incoming Control Channel Authentication: Using 160 bit message hash 'SHA1' for HMAC authentication,
Fri Aug  7 06:50:12 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]XXX.XXX.XXX.XXX:443,
Fri Aug  7 06:50:12 2020 Socket Buffers: R=[212992->212992] S=[212992->212992],
Fri Aug  7 06:50:12 2020 UDP link local: (not bound),
Fri Aug  7 06:50:12 2020 UDP link remote: [AF_INET]XXX.XXX.XXX.XXX:443,
Fri Aug  7 06:50:12 2020 TLS: Initial packet from [AF_INET]XXX.XXX.XXX.XXX:443, sid=b6ca9b37 29c2a62d,
Fri Aug  7 06:50:13 2020 VERIFY OK: depth=1, C=IT, ST=IT, L=Perugia, O=airvpn.org, CN=airvpn.org CA, emailAddress=info@airvpn.org,
Fri Aug  7 06:50:13 2020 VERIFY KU OK,
Fri Aug  7 06:50:13 2020 Validating certificate extended key usage,
Fri Aug  7 06:50:13 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication,
Fri Aug  7 06:50:13 2020 VERIFY EKU OK,
Fri Aug  7 06:50:13 2020 VERIFY OK: depth=0, C=IT, ST=IT, L=Perugia, O=airvpn.org, CN=Sharatan, emailAddress=info@airvpn.org,
Fri Aug  7 06:50:13 2020 Control Channel: TLSv1.2, cipher TLSv1.2 DHE-RSA-AES256-GCM-SHA384, 4096 bit RSA,
Fri Aug  7 06:50:13 2020 [Sharatan] Peer Connection Initiated with [AF_INET]XXX.XXX.XXX.XXX:443,
Fri Aug  7 06:50:14 2020 SENT CONTROL [Sharatan]: 'PUSH_REQUEST' (status=1),
Fri Aug  7 06:50:14 2020 PUSH: Received control message: 'PUSH_REPLY,comp-lzo no,redirect-gateway  def1 bypass-dhcp,dhcp-option DNS 10.XXX.XX.XXX,route-gateway 10.XXX.XXX.XXX,topology subnet,ping 10,ping-restart 60,ifconfig 10.XXX.XX.XXX 255.255.255.0,peer-id 2,cipher AES-256-GCM',
Fri Aug  7 06:50:14 2020 OPTIONS IMPORT: timers and/or timeouts modified,
Fri Aug  7 06:50:14 2020 OPTIONS IMPORT: compression parms modified,
Fri Aug  7 06:50:14 2020 OPTIONS IMPORT: --ifconfig/up options modified,
Fri Aug  7 06:50:14 2020 OPTIONS IMPORT: route options modified,
Fri Aug  7 06:50:14 2020 OPTIONS IMPORT: route-related options modified,
Fri Aug  7 06:50:14 2020 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified,
Fri Aug  7 06:50:14 2020 OPTIONS IMPORT: peer-id set,
Fri Aug  7 06:50:14 2020 OPTIONS IMPORT: adjusting link_mtu to 1625,
Fri Aug  7 06:50:14 2020 OPTIONS IMPORT: data channel crypto options modified,
Fri Aug  7 06:50:14 2020 Data Channel: using negotiated cipher 'AES-256-GCM',
Fri Aug  7 06:50:14 2020 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Fri Aug  7 06:50:14 2020 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Fri Aug  7 06:50:14 2020 ROUTE_GATEWAY 172.19.0.1/255.255.0.0 IFACE=eth0 HWADDR=02:42:ac:13:00:09,
Fri Aug  7 06:50:14 2020 TUN/TAP device tun0 opened,
Fri Aug  7 06:50:14 2020 TUN/TAP TX queue length set to 100,
Fri Aug  7 06:50:14 2020 /sbin/ip link set dev tun0 up mtu 1500,
Fri Aug  7 06:50:14 2020 /sbin/ip addr add dev tun0 10.XXX.XXX.XXX/24 broadcast 10.XXX.XXX.XXX,
Fri Aug  7 06:50:14 2020 /etc/openvpn/tunnelUp.sh tun0 1500 1553 10.XXX.XXX.XXX 255.255.255.0 init,
```

**Host system:**

Synology
