### ISSUE TITLE
HELP: Stuck in (Temporary failure in name resolution) loop.

### ISSUE THREAD

**Issue by attzonko** [haugene/docker-transmission-openvpn#1322]
I just found my container stuck in a restart loop, here is what I see in the log
```
last Thursday at 11:37 PM Thu Aug  6 23:37:30 2020 [us-lax-011.mullvad.net] Inactivity timeout (--ping-restart), restarting
last Thursday at 11:37 PM Thu Aug  6 23:37:30 2020 SIGUSR1[soft,ping-restart] received, process restarting
last Thursday at 11:37 PM Thu Aug  6 23:37:30 2020 Restart pause, 5 second(s)
last Thursday at 11:37 PM Thu Aug  6 23:37:35 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
last Thursday at 11:37 PM Thu Aug  6 23:37:35 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]89.46.114.145:1197
last Thursday at 11:37 PM Thu Aug  6 23:37:35 2020 Socket Buffers: R=[212992->425984] S=[212992->425984]
last Thursday at 11:37 PM Thu Aug  6 23:37:35 2020 NOTE: setsockopt TCP_NODELAY=1 failed
last Thursday at 11:37 PM Thu Aug  6 23:37:35 2020 UDP link local: (not bound)
last Thursday at 11:37 PM Thu Aug  6 23:37:35 2020 UDP link remote: [AF_INET]89.46.114.145:1197
last Thursday at 11:38 PM Thu Aug  6 23:38:35 2020 [UNDEF] Inactivity timeout (--ping-restart), restarting
last Thursday at 11:38 PM Thu Aug  6 23:38:35 2020 SIGUSR1[soft,ping-restart] received, process restarting
last Thursday at 11:38 PM Thu Aug  6 23:38:35 2020 Restart pause, 5 second(s)
last Thursday at 11:38 PM Thu Aug  6 23:38:40 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
last Thursday at 11:38 PM Thu Aug  6 23:38:50 2020 RESOLVE: Cannot resolve host address: us-lax-012.mullvad.net:1197 (Temporary failure in name resolution)
last Thursday at 11:39 PM Thu Aug  6 23:39:00 2020 RESOLVE: Cannot resolve host address: us-lax-012.mullvad.net:1197 (Temporary failure in name resolution)
last Thursday at 11:39 PM Thu Aug  6 23:39:00 2020 Could not determine IPv4/IPv6 protocol
last Thursday at 11:39 PM Thu Aug  6 23:39:00 2020 SIGUSR1[soft,init_instance] received, process restarting
last Thursday at 11:39 PM Thu Aug  6 23:39:00 2020 Restart pause, 5 second(s)
last Thursday at 11:39 PM Thu Aug  6 23:39:05 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
last Thursday at 11:39 PM Thu Aug  6 23:39:15 2020 RESOLVE: Cannot resolve host address: us-lax-202.mullvad.net:1197 (Temporary failure in name resolution)
last Thursday at 11:39 PM Thu Aug  6 23:39:25 2020 RESOLVE: Cannot resolve host address: us-lax-202.mullvad.net:1197 (Temporary failure in name resolution)
last Thursday at 11:39 PM Thu Aug  6 23:39:25 2020 Could not determine IPv4/IPv6 protocol
last Thursday at 11:39 PM Thu Aug  6 23:39:25 2020 SIGUSR1[soft,init_instance] received, process restarting
last Thursday at 11:39 PM Thu Aug  6 23:39:25 2020 Restart pause, 5 second(s)
last Thursday at 11:39 PM Thu Aug  6 23:39:30 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
last Thursday at 11:39 PM Thu Aug  6 23:39:40 2020 RESOLVE: Cannot resolve host address: us-lax-016.mullvad.net:1197 (Temporary failure in name resolution)
last Thursday at 11:39 PM Thu Aug  6 23:39:50 2020 RESOLVE: Cannot resolve host address: us-lax-016.mullvad.net:1197 (Temporary failure in name resolution)
last Thursday at 11:39 PM Thu Aug  6 23:39:50 2020 Could not determine IPv4/IPv6 protocol
last Thursday at 11:39 PM Thu Aug  6 23:39:50 2020 SIGUSR1[soft,init_instance] received, process restarting
last Thursday at 11:39 PM Thu Aug  6 23:39:50 2020 Restart pause, 5 second(s)
last Thursday at 11:39 PM Thu Aug  6 23:39:55 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
last Thursday at 11:40 PM Thu Aug  6 23:40:05 2020 RESOLVE: Cannot resolve host address: us-lax-102.mullvad.net:1197 (Temporary failure in name resolution)
last Thursday at 11:40 PM Thu Aug  6 23:40:15 2020 RESOLVE: Cannot resolve host address: us-lax-102.mullvad.net:1197 (Temporary failure in name resolution)
last Thursday at 11:40 PM Thu Aug  6 23:40:15 2020 Could not determine IPv4/IPv6 protocol
last Thursday at 11:40 PM Thu Aug  6 23:40:15 2020 SIGUSR1[soft,init_instance] received, process restarting
last Thursday at 11:40 PM Thu Aug  6 23:40:15 2020 Restart pause, 5 second(s)
last Thursday at 11:40 PM Thu Aug  6 23:40:20 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
last Thursday at 11:40 PM Thu Aug  6 23:40:30 2020 RESOLVE: Cannot resolve host address: us-lax-302.mullvad.net:1197 (Temporary failure in name resolution)
last Thursday at 11:40 PM Thu Aug  6 23:40:40 2020 RESOLVE: Cannot resolve host address: us-lax-302.mullvad.net:1197 (Temporary failure in name resolution)
```

Pinging any of the addresses from the log file, they seem to be available:
```
$ ping us-lax-102.mullvad.net
PING us-lax-102.mullvad.net (198.54.129.74) 56(84) bytes of data.
64 bytes from static-198-54-129-74.cust.tzulo.com (198.54.129.74): icmp_seq=1 ttl=55 time=26.1 ms
64 bytes from static-198-54-129-74.cust.tzulo.com (198.54.129.74): icmp_seq=2 ttl=55 time=54.8 ms
64 bytes from static-198-54-129-74.cust.tzulo.com (198.54.129.74): icmp_seq=3 ttl=55 time=81.2 ms
```

Any ideas about what could be wrong?

EDIT: By the way, this was working fine for a few days.

**Comment by haugene** [comment]
This is a DNS issue. What options are you running the container with? https://haugene.github.io/docker-transmission-openvpn/known-issues/#use_google_dns_servers

Also see my comments in #1306 or search other issues. There has been many of them.

**Comment by attzonko** [comment]
I have set the dns to 1.1.1.1 and 8.8.8.8.

**Comment by attzonko** [comment]
Here is my full container config:
```
  transmission:
    image: haugene/transmission-openvpn:latest
    container_name: transmission
    restart: always
    healthcheck:
      disable: true
    networks:
      - t2_proxy
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    security_opt:
      - no-new-privileges:true
    ports:
      - "$TRANSMISSION_PORT:9091"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    dns:
      - 1.1.1.1
      - 8.8.8.8
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $DOCKERDIR/transmission/data:/data
      - $DOCKERDIR/transmission/config:/config
      - $USERDIR/downloads:/downloads
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ

      OPENVPN_PROVIDER: MULLVAD
      OPENVPN_USERNAME: $MULLVAD_ACCOUNT
      OPENVPN_PASSWORD: m
      OPENVPN_CONFIG: mullvad_us-ca_udp
      OPENVPN_OPTS: --inactive 3600 --ping 10 --ping-exit 60

      LOCAL_NETWORK: "$LOCAL_NETWORK"
      ENABLE_UFW: 'true'

      TRANSMISSION_PEER_PORT_RANDOM_ON_START: 'false'
      TRANSMISSION_PEER_PORT: $MULLVAD_PORT
      TRANSMISSION_RATIO_LIMIT: 0
      TRANSMISSION_RATIO_LIMIT_ENABLED: 'true'
      TRANSMISSION_ENCRYPTION: 2
      TRANSMISSION_UTP_ENABLED: 'false'
      TRANSMISSION_PEER_LIMIT_GLOBAL: 1000
      TRANSMISSION_PEER_LIMIT_PER_TORRENT: 100
      TRANSMISSION_RPC_WHITELIST_ENABLED: 'false'
      TRANSMISSION_RPC_HOST_WHITELIST_ENABLED: 'false'
      TRANSMISSION_UMASK: 2
      TRANSMISSION_INCOMPLETE_DIR: /downloads/incomplete
      TRANSMISSION_INCOMPLETE_DIR_ENABLED: 'true'
      TRANSMISSION_WATCH_DIR: /downloads
      TRANSMISSION_WATCH_DIR_ENABLED: 'true'
      TRANSMISSION_DOWNLOAD_DIR: /downloads/completed
```
