### ISSUE TITLE
Update PIA configs to next gen servers

### ISSUE THREAD

**Issue by haugene** [haugene/docker-transmission-openvpn#1334]
**Which provider?**
PIA

**Where are the configs?**
Should probably update to the next gen servers.

https://www.privateinternetaccess.com/helpdesk/news/posts/august-19th-2020-important-updated-server-changes-and-related-issues

**Comment by IroesStrongarm** [comment]
I apologize for asking, but I downloaded the config files but I'm uncertain how I would use them with the docker compose.  Any help please?

**Comment by Kriskras99** [comment]
Here's what I am using:
```
  tr1:
    image: haugene/transmission-openvpn
    container_name: tr1
    volumes:
      - tr1_data:/data
      - tr1_config:/config
      - '/etc/localtime:/etc/localtime:ro'
      - '/home/kriskras99/compose/transmission/Netherlands.ovpn:/etc/openvpn/custom/default.ovpn:ro'
    environment:
      - OPENVPN_PROVIDER=CUSTOM
      - OPENVPN_USERNAME=p1234567
      - OPENVPN_PASSWORD=password
    cap_add:
      - NET_ADMIN
    ports:
      - '9091:9091'
    dns:
      - 1.1.1.1
      - 1.0.0.1
```
Just replace your ovpn file path with mine and your good to go

**Comment by zjorsie** [comment]
> Here's what I am using:
> 
> ```
>   tr1:
>     image: haugene/transmission-openvpn
>     container_name: tr1
>     volumes:
>       - tr1_data:/data
>       - tr1_config:/config
>       - '/etc/localtime:/etc/localtime:ro'
>       - '/home/kriskras99/compose/transmission/Netherlands.ovpn:/etc/openvpn/custom/default.ovpn:ro'
>     environment:
>       - OPENVPN_PROVIDER=CUSTOM
>       - OPENVPN_USERNAME=p1234567
>       - OPENVPN_PASSWORD=password
>     cap_add:
>       - NET_ADMIN
>     ports:
>       - '9091:9091'
>     dns:
>       - 1.1.1.1
>       - 1.0.0.1
> ```
> 
> Just replace your ovpn file path with mine and your good to go

Problem with that config is that port forwarding does not work. If you change it to:
```
   tr1:
     image: haugene/transmission-openvpn
     container_name: tr1
     volumes:
       - tr1_data:/data
       - tr1_config:/config
       - '/etc/localtime:/etc/localtime:ro'
       - '/home/kriskras99/compose/transmission/France.ovpn:/etc/openvpn/pia/France.ovpn:ro'
     environment:
       - OPENVPN_PROVIDER=PIA
       -OPENVPN_CONFIG=France
       - OPENVPN_USERNAME=p1234567
       - OPENVPN_PASSWORD=password
     cap_add:
       - NET_ADMIN
     ports:
       - '9091:9091'
     dns:
       - 1.1.1.1
       - 1.0.0.1
```

it will use port forwarding from PIA (currently, the Netherlands is not in the list of servers supporting port forwarding)

**Comment by IroesStrongarm** [comment]
Thank you both for your help.  It took much trial and error until I got it all correct.  In the end I went with the way zjorsie configured and it works perfect.

Once again, thank you both very much for taking your time to help me out.

**Comment by IroesStrongarm** [comment]
Nevermind.  I'm clearly not doing something right.  It's likely a backend setup for this I'm not getting...Thanks anyway

**Comment by zjorsie** [comment]
Oh yeah, do not use the x.... username pia generates for you. For the nextgen config you'll need your login credentials you also use on the app! took me some time to figure out as well (if you get auth failed messages). 

And I forgot to mention that you have to change a line in your config (as received from the ovpn generator). I chose:
- nextgen config
- openvpn 2.4
- Europe, France
- 1198UDP

Then, in your file you should have a line
``
auth-user-pass 
`` 

Change this line to:
`` 
auth-user-pass /config/openvpn-credentials.txt
``

**Comment by IroesStrongarm** [comment]
I'm sorry to keep asking.  Which config file am I supposed to edit?  I downloaded the ovpn file from PIA directly.  I'm unfamiliar with ovpn generator. This is what my compose looks like:

version: "2"
services:
    transmission-openvpn:
        image: haugene/transmission-openvpn:latest
        container_name: transmission-openvpn-syno
        restart: always
        cap_add:
          - NET_ADMIN
        devices:
          - /dev/net/tun
        volumes:
          - /srv/dev-disk-by-label-scratch/scratch/downloads:/data
          - /srv/dev-disk-by-id-ata-CT500MX500SSD1_1752E108A760-part4/appdata/transmission:/config
          - /srv/dev-disk-by-label-data/users/roy/transmission/Switzerland.ovpn:/etc/openvpn/pia/Switzerland.ovpn:ro
        environment:
          - OPENVPN_PROVIDER=PIA
          - OPENVPN_CONFIG=Switzerland
          - OPENVPN_USERNAME=p1234567 #(I've entered my actual username here)
          - OPENVPN_PASSWORD=password #(I've entered my actual password here)
          - WEBPROXY_ENABLED=false
          - LOCAL_NETWORK=192.168.1.0/24 
          - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60 # Leave this as is
          - PUID=998 #Change to your PUID
          - PGID=100 #Change to your PGID
          - TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=false
        logging:
            driver: json-file
            options:
                max-size: 10m
        dns:
          - 8.8.8.8
          - 8.8.4.4
        ports:
          - 9091:9091
          - 8888:8888

**Comment by zjorsie** [comment]
> I'm sorry to keep asking. Which config file am I supposed to edit? I downloaded the ovpn file from PIA directly. I'm unfamiliar with ovpn generator. This is what my compose looks like:
> 
> version: "2"
> services:
> transmission-openvpn:
> image: haugene/transmission-openvpn:latest
> container_name: transmission-openvpn-syno
> restart: always
> cap_add:
> - NET_ADMIN
> devices:
> - /dev/net/tun
> volumes:
> - /srv/dev-disk-by-label-scratch/scratch/downloads:/data
> - /srv/dev-disk-by-id-ata-CT500MX500SSD1_1752E108A760-part4/appdata/transmission:/config
> - /srv/dev-disk-by-label-data/users/roy/transmission/Switzerland.ovpn:/etc/openvpn/pia/Switzerland.ovpn:ro
> environment:
> - OPENVPN_PROVIDER=PIA
> - OPENVPN_CONFIG=Switzerland
> - OPENVPN_USERNAME=p1234567 #(I've entered my actual username here)
> - OPENVPN_PASSWORD=password #(I've entered my actual password here)
> - WEBPROXY_ENABLED=false
> - LOCAL_NETWORK=192.168.1.0/24
> - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
> - PUID=998
> - PGID=100
> - TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=false
> logging:
> driver: json-file
> options:
> max-size: 10m
> dns:
> - 8.8.8.8
> - 8.8.4.4
> ports:
> - 9091:9091
> - 8888:8888

You have to edit the line in this file:  /srv/dev-disk-by-label-data/users/roy/transmission/Switzerland.ovpn

**Comment by IroesStrongarm** [comment]
If the line you are referring to is the auth-user-pass to auth-user-pass /config/openvpn-credentials.txt I've done that.

The error I get once I deploy and it tries to load is:

Port forwarding is already activated on this connection, has expired, or you are not connected to a PIA region that supports port forwarding
curl encountered an error looking up new port: 7

**Comment by zjorsie** [comment]
On reddit (https://www.reddit.com/r/PrivateInternetAccess/comments/i6qqu0/pia_portforward_request_ip_is_dead/) they say they are migrating servers and it could happen that it doesn't work for the next while.

For the time being you can also just use the included VPN configs and just wait until the nextgen configs are included in the haugene image.

**Comment by haugene** [comment]
I'll get to it very soon. Hopefully this weekend.

**Comment by IroesStrongarm** [comment]
@zjorsie The standard ones sometimes fail to port forward so the next gen ones were recommended as the fix.  That said I really do appreciate all your help.

@haugene I assumed your note at the top was just telling people like me we had to manually do it.  I greatly appreciate the time you've taken in making this docker and maintaining it.

**Comment by haugene** [comment]
@IroesStrongarm No, you shouldn't have to do it manually ;) Trying to keep it up to date. But over the years there has come a lot of providers and there's always stuff to do. I'm using pia myself, so that should be a safe choice though.

**Comment by IroesStrongarm** [comment]
@zjorsie Sorry to keep bothering but I was hoping for a follow up question for my own clarification.  After using everything I've learned this morning from this thread and reading the docs for this docker, I'm able to get connected using the original compose posted by kriskras99.  That said, like you said, it doesn't support port forwarding.

Why is the port forwarding so important for this setup?  When I use a tracking magnet link it does show a Swiss IP.  I just want to properly understand why this setup is bad.

Thank you.

**Comment by zjorsie** [comment]
@IroesStrongarm No problem! Everything has a steep learning curve, which will eventually flatten out (I hope at least).

You don't need the port forwarding to download torrents. The connections you make all origin from your computer, so downloading will work fine.

However, when you want to upload (e.g. for private trackers, or just being someone who enjoys torrents and supports the network) you want to seed torrents. Then, you'll need people to be able to connect to you (to request data), and that's where port forwarding comes in. 

Not sure how much you know about port forwarding in general but basically, the port forwarding service is nothing more than sending traffic that arrives at `PIA ADDRESS:PORT` to your machine over the PIA VPN, where PORT is a random port number which can be requested from PIA. This port forward can then use it to let clients connect to you (to upload torrents in this case).

**Comment by IroesStrongarm** [comment]
@zjorsie Thank you for that write up.  So if I were to want to, for the time being (though not ideal), I could use the setup that Kriskras99 put, that did work for me, but no port forwarding, and I'd be able to download safely, just not upload to anyone?

I know that's not in the spirit of things, and obviously once I can get the next gen working with forwarding I would fix it, but just want to know if it would give me safe and functional functionality for me today?

**Comment by zjorsie** [comment]
@IroesStrongarm Yeah that's true, downloading is fine. For the time being, you can also use the 'normal' PIA config. This works the same as the 'nextgen' config (probably new software they're deploying with better throughput/latencies/routing efficiency/...).

If you want to test if IP hiding works correctly for your torrents, you can go to ipleak.net (activate the torrent address detection and add the magnet link to your torrent client).

**Comment by mizzi0n** [comment]
@zjorsie @haugene @IroesStrongarm hey everyone, i have tried this today with the old gen profiles and some of the new gen profiles, i can connect fine on all but can not get a port on any. has anyone got this working and if so which country and which gen?

**Comment by evil666** [comment]
> @zjorsie @haugene @IroesStrongarm hey everyone, i have tried this today with the old gen profiles and some of the new gen profiles, i can connect fine on all but can not get a port on any. has anyone got this working and if so which country and which gen?

Same here. Tried the client just in case it was the server side acting up, and the client is snagging ports just fine. Not sure if the script for this needs to be tweaked or what. Either way, appreciated your guy's time and awesome image.

**Comment by zjorsie** [comment]
@mizzi0n @evil666 I tried it today as well, with no luck (both on old and new config).

For the old config I get error 52, which means the server did not return any data. Not sure why though, probably issues (or choices) at the PIA side.

The PIA page about port forwarding (https://www.privateinternetaccess.com/helpdesk/kb/articles/can-i-use-port-forwarding-without-using-the-pia-client-current-gen-only) specifies that the port forwarding is only available for their currentgen config (for now), so that's why the nextgen config doesn't work I guess. I will have a look at running the pia app in the container instead of the openvpn approach.

**Comment by mizzi0n** [comment]
@zjorsie @evil666 i done some playing this evening. after reading this https://www.privateinternetaccess.com/pages/client-support/#portforward  i tried the following servers:

Spain
Romania
Israel
and they worked. what i done was download the orginal config files and changed the line auth-user-pass to auth-user-pass /config/openvpn-credentials.txt and mounted into the image - /root/config/pia:/etc/openvpn/pia:ro

it still isnt 100% consistant but once its up it doesnt seem to drop

**Comment by zjorsie** [comment]
@mizzi0n Thanks, tried Romania and got a port on the first try! Couldn't connect to DE Berlin however (closer to my location), they're probably busy with something.

**Comment by mizzi0n** [comment]
> 
> 
> @mizzi0n Thanks, tried Romania and got a port on the first try! Couldn't connect to DE Berlin however (closer to my location), they're probably busy with something.

no problem, did you have to mount your own config files or just used what was there on the docker ?

**Comment by IroesStrongarm** [comment]
@mizzi0n Just wanted to say that your method worked for me.  Currently connected to Spain no problem, port forwarded.  I haven't tried to reconnect so for now the connection just remains open.

Thanks.

**Comment by code-is-art** [comment]
Tried this with no luck. What I did to see if I made a mistake somewhere.
* went to [pia ovpn generator](https://www.privateinternetaccess.com/pages/ovpn-config-generator) and generated a config
> NextGen  
> OpenVPN 2.4 or newer  
> Linux  
> France  
> UDP/1198 
* create config and data dirs
```bash
$ sudo mkdir -p /srv/transmission/{data,config}
$ sudo chmod -R 777 /srv/transmission/
```
* create user-pass file for pia next-gen
```bash
cat << 'EOF' > /srv/transmission/config/openvpn-credentials.txt
u12345
p12345
EOF
```
* changed the .ovpn file line that says...  
> auth-user-pass
to...  
> auth-user-pass /config/openvpn-credentials.txt
* created dir to house .ovpn file
```bash
$ sudo mkdir -p /srv/openvpn/pia
$ sudo chmod -R 777 /srv/openvpn
```
* moved updated .ovpn file to...
> /srv/openvpn/pia
* docker-compose.yml
```yaml
---
version: "3.2"
services:
  transmission:
    image: haugene/transmission-openvpn:latest-armhf
    container_name: transmission
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: always
    ports:
      - 9091:9091
      - 8888:8888
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /srv/transmission/data:/data:rw
      - /srv/transmission/config:/config:rw
      - /srv/openvpn/pia/France.ovpn:/etc/openvpn/pia/France.ovpn:ro
      - type: bind
        source: /media/pi/Media/Torrents
        target: /torrents
    environment:
      - PUID=1001
      - PGID=1000
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_CONFIG=France
      - OPENVPN_USERNAME=u12345
      - OPENVPN_PASSWORD=p12345
      - TRANSMISSION_INCOMPLETE_DIR=/torrents/incomplete
      - TRANSMISSION_DOWNLOAD_DIR=/torrents/complete
      - TRANSMISSION_WATCH_DIR=/torrents/watch
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=192.168.68.100/24
    ports:
      - 9091:9091
    dns:
       - 1.1.1.1
       - 1.0.0.1
    logging:
      driver: json-file
      options:
        max-size: "10m"
```
**still getting***
> curl encountered an error looking up new port: 7

I'm not sure what I did wrong but can't get it to work.
