### ISSUE TITLE
Container fails to exit properly

### ISSUE THREAD

**Issue by SSS475** [haugene/docker-transmission-openvpn#1343]
**Describe the problem**
After a period of time(less than 1 day) the running container stops behaving correctly.  The container no longer responds correctly to the `docker stop ...` command, I have to use `docker rm -f ...` to forcefully shutdown the container and `systemctl restart docker` to remove the entry from the docker compose network in order to restart the container.  Furthermore, if I use `docker exec -it ... /bin/bash` I get a clean shell and can verify everything is working as expected; however, when I then run `exit` inside that shell it never releases control.  I believe the healthcheck suffers the same fate, as `docker exec -it ... /etc/scripts/healthcheck.sh` prints correctly to the terminal, but never returns control.  If I forcefully remove the container, restart the docker daemon, and start the container, it will work and execute correctly up, down, healthcheck; however, by tomorrow morning it will fail again.

**Add your docker run command**
Excerpt from docker compose script
```
version: '3.7'
services:
...
  transmit:
    image: haugene/transmission-openvpn
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - "OPENVPN_PROVIDER=IPVANISH"
      - "OPENVPN_CONFIG=***"
      - "OPENVPN_USERNAME=***"
      - "OPENVPN_PASSWORD=***"
      - PUID
      - PGID
      - "LOCAL_NETWORK=192.168.1.0/24"
    volumes:
      - $TORRENT_LOCATION:/data
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.http.routers.transmit.rule=Host(`transmit.$DOMAIN`)"
      - "traefik.http.services.transmit.loadbalancer.server.port=9091"
      - "traefik.http.routers.transmit.middlewares=auth"
      - "traefik.http.routers.transmit.tls=true"
      - "traefik.http.routers.transmit.tls.certresolver=mainresolver"
```

**Logs**
Results of `docker stop ...`, `docker ps` showing unhealthy, and tail of `docker logs ...`, container never actually stops
```
***% docker stop transmission
transmission
***% docker ps
CONTAINER ID        IMAGE                                  COMMAND                  CREATED             STATUS                    PORTS                                      NAMES
...
2f07a153f5e2        haugene/transmission-openvpn           "dumb-init /etc/open…"   18 hours ago        Up 18 hours (unhealthy)   8888/tcp, 9091/tcp                         transmission
...
***% docker logs transmission
...
Wed Aug 26 09:46:22 2020 event_wait : Interrupted system call (code=4)
Wed Aug 26 09:46:22 2020 SIGTERM received, sending exit notification to peer
Wed Aug 26 09:46:27 2020 /sbin/ip route del 173.245.202.22/32
Wed Aug 26 09:46:27 2020 /sbin/ip route del 0.0.0.0/1
Wed Aug 26 09:46:27 2020 /sbin/ip route del 128.0.0.0/1
Wed Aug 26 09:46:27 2020 Closing TUN/TAP interface
Wed Aug 26 09:46:27 2020 /sbin/ip addr del dev tun0 172.21.20.2/23
Wed Aug 26 09:46:27 2020 /etc/openvpn/tunnelDown.sh tun0 1500 1553 172.21.20.2 255.255.254.0 init
Wed Aug 26 09:46:27 2020 SIGTERM[soft,exit-with-notification] received, process exiting
```

Excerpt from `docker inspect ...`
```
            "Health": {
                "Status": "unhealthy",
                "FailingStreak": 70,
                "Log": [
                    {
                        "Start": "2020-08-26T08:41:45.746714855-04:00",
                        "End": "2020-08-26T08:42:15.746804588-04:00",
                        "ExitCode": -1,
                        "Output": "Health check exceeded timeout (30s)"
                    },
```

Manually executing health check (and attempting to exit with Control-C), control is never returned and I don't get a new prompt.
```
***% docker exec -it *** /etc/scripts/healthcheck.sh
PING google.com (216.58.192.174) 56(84) bytes of data.
64 bytes from ord36s02-in-f14.1e100.net (216.58.192.174): icmp_seq=1 ttl=119 time=20.2 ms

--- google.com ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 20.227/20.227/20.227/0.000 ms
Network is up
Openvpn and transmission-daemon processes are running


^C^C^C^C^C^C

```

**Host system:**
Host is Arch Linux 5.8.1 x86_64 with docker Server Version: 19.03.12-ce
