### ISSUE TITLE
Cannot figure out how to make it working with AirVPN despite explanation for Custom Provider

### ISSUE THREAD

**Issue by P3pit0r** [haugene/docker-transmission-openvpn#1377]
Hello everyone, 

As the title says, I cannot figure out how to make this container works despite the explanation given on this page : https://haugene.github.io/docker-transmission-openvpn/supported-providers/
I am fairly new to Linux so there are things unclear for me.
I have the 5 files provided by the VPN provider (with the following configuration : UDP 443, only IPv4, Raspbian version, OpenVPN version >= 2.4, Netherlands server):
-	ca.crt
-	user.crt
-	user.key
-	ta.key
-	default.ovpn

Unfortunately, as stated above and despite the explanation, I cannot figure out what to do exactly with all these files, where to put them, what to modify/add, etc… 

This is the docker compose I am running: 

```
version: '2.1'
services:
 transmission-openvpn:
    volumes:
        - /srv/dev-disk-by-label-mediadisk/medias/downloads/:/data
        - /etc/localtime:/etc/localtime:ro
        - /srv/dev-disk-by-label-mediadisk/appdata/OpenVPN/default/default.ovpn:/etc/openvpn/custom/default.ovpn
    environment:
        - PUID=997
        - PGID=100
        - CREATE_TUN_DEVICE=true
        - OPENVPN_PROVIDER=CUSTOM
        - OPENVPN_CONFIG=default
        - CUSTOM_COUNTRY=NL
        - CUSTOM_CATEGORY=legacy_p2p
        - CUSTOM_PROTOCOL=udp
        - OPENVPN_USERNAME=*******
        - OPENVPN_PASSWORD=*******
        - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
        - WEBPROXY_ENABLED=false
        - LOCAL_NETWORK=192.168.1.0/24
        - TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=false
        - DNS=8.8.8.8,8.8.4.4
    cap_add:
        - NET_ADMIN
    logging:
        driver: json-file
        options:
            max-size: 10m
    ports:
        - 9091:9091
    restart: always
    image: haugene/transmission-openvpn:latest-armhf
```

**Logs**

```
Using OpenVPN provider: CUSTOM
Supplied config default.ovpn could not be found.
Using default OpenVPN gateway for provider custom
Setting OPENVPN credentials...
adding route to local network 192.168.1.0/24 via 172.17.0.1 dev eth0
Sat Sep 26 12:56:44 2020 disabling NCP mode (--ncp-disable) because not in P2MP client or server mode
Options error: You must define TUN/TAP device (--dev)
Use --help for more information.
```

**Host system:**
Running on Raspberry pi 4; latest-armhf
Docker 5:19.03.13~3-0~debian-buster

Thank you for your help !
