### ISSUE TITLE
NordVPN issues

### ISSUE THREAD

**Issue by lemminol** [haugene/docker-transmission-openvpn#1381]
2020-09-29 10:47:19 | stdout | Use --help for more information.
-- | -- | --
2020-09-29 10:47:19 | stdout | Options error: In [CMD-LINE]:1: Error opening configuration file: /etc/openvpn/nordvpn/default.ovpn
2020-09-29 10:47:19 | stdout | Setting OPENVPN credentials...
2020-09-29 10:47:19 | stdout | No VPN configuration provided. Using default.
2020-09-29 10:47:19 | stdout | 0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0   0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0   0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0   0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0   0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0   0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0   0     0    0     0    0     0      0      0 --:--:--  0:00:06 --:--:--     0   0     0    0     0    0     0      0      0 --:--:--  0:00:07 --:--:--     0   0     0    0     0    0     0      0      0 --:--:--  0:00:08 --:--:--     0   0     0    0     0    0     0      0      0 --:--:--  0:00:09 --:--:--     0curl: (6) Could not resolve host: downloads.nordcdn.com
2020-09-29 10:47:08 | stdout | Dload  Upload   Total   Spent    Left  Speed
2020-09-29 10:47:08 | stdout | % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
2020-09-29 10:47:08 | stdout | 2020-09-29 19:46:38 Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_udp/servers/.udp.ovpn
2020-09-29 10:47:08 | stdout | 2020-09-29 19:46:38 Downloading config: default.ovpn
2020-09-29 10:47:08 | stdout | 2020-09-29 19:46:38 Best server :
2020-09-29 10:46:58 | stdout | 2020-09-29 19:46:38 Unable to find a server with the specified parameters, using any recommended server
2020-09-29 10:46:48 | stdout | 2020-09-29 19:46:38 Searching for technology: openvpn_udp
2020-09-29 10:46:38 | stdout | 2020-09-29 19:46:38 Selecting the best server...
2020-09-29 10:46:38 | stdout | 2020-09-29 19:46:38 Removing existing configs
2020-09-29 10:46:38 | stdout | 2020-09-29 19:46:38 Checking curl installation
2020-09-29 10:46:38 | stdout | Using OpenVPN provider: nordvpn

I tried accessing downloads.nordcdn.com because of this error, and a 503 error appeared.
So, I sent an email to nordvpn to see if that site is now unusable.

"Hello,

Thank you for your reply.

The link which you are trying is not accessible.

If you wish to download the NordVPN OpenVPN configurations you can do that by following the link:

https://nordvpn.com/ovpn/

Simply choosing the specific server you will be able to download it.

Let us know if you have any further questions!"

I got the answer.
How should I solve this problem?
I am not an expert, but I want you to explain it easily.

**Comment by ilike2burnthing** [comment]
Are you using the NordVPN options instead of OpenVPN ones? https://haugene.github.io/docker-transmission-openvpn/nordvpn-script/

**Comment by lemminol** [comment]
https://haugene.github.io/docker-transmission-openvpn/nordvpn-script/
I tried the settings here, but there was an error.

**Comment by ilike2burnthing** [comment]
Which was...?

**Comment by lemminol** [comment]
OPENVPN_USERNAME [nordvpn email]
OPENVPN_PASSWORD [nordvpn password]
OPENVPN_PROVIDER nordvpn
NORDVPN_CATEGORY legacy_p2p
NORDVPN_PROTOCOL 
NORDVPN_COUNTRY
It was set like this and NORDVPN_CATEGORY was blank before a problem occurred.

**Comment by ilike2burnthing** [comment]
Sorry, I was asking what the error was.

Did you put in either TCP or UDP for the protocol?

**Comment by lemminol** [comment]
> Sorry, I was asking what the error was.
> 
> Did you put in either TCP or UDP for the protocol?

Even though I tried putting both tcp and udp, the same error occurred.

**Comment by ilike2burnthing** [comment]
Again, what was the error?

**Comment by RickyXwang** [comment]
I think the error is curl: (6) Could not resolve host: downloads.nordcdn.com.
Looks like need to update the script to the new download server as the host "downloads.nordcdn.com" is no longer valid.

**Comment by ilike2burnthing** [comment]
https://downloads.nordcdn.com/ is purposefully inaccessible, however the config files from it aren't (excuse the double negative - they are accessible), unless there's some DNS issue for you.

For example, you should be able to download these files just fine:
https://downloads.nordcdn.com/configs/files/ovpn_udp/servers/ie81.nordvpn.com.udp.ovpn
https://downloads.nordcdn.com/configs/files/ovpn_udp/servers/ee41.nordvpn.com.udp.ovpn

The issue is that the URL being used in the OP is pointing to a non-existent file:
https://downloads.nordcdn.com/configs/files/ovpn_udp/servers/.udp.ovpn

@lemminol can you post the same log information now that you've made those changes? Also, make sure you aren't causing a conflict by using OPENVPN_CONFIG as well.

**Comment by lemminol** [comment]
> https://downloads.nordcdn.com/ is purposefully inaccessible, however the config files from it aren't (excuse the double negative - they are accessible), unless there's some DNS issue for you.
> 
> For example, you should be able to download these files just fine by clicking on them:
> https://downloads.nordcdn.com/configs/files/ovpn_udp/servers/ie81.nordvpn.com.udp.ovpn
> https://downloads.nordcdn.com/configs/files/ovpn_udp/servers/ee41.nordvpn.com.udp.ovpn
> 
> The issue is that the URL being used in the OP is pointing to a non-existent file:
> https://downloads.nordcdn.com/configs/files/ovpn_udp/servers/.udp.ovpn
> 
> @lemminol can you post the same log information now that you've made those changes? Also, make sure you aren't causing a conflict by using OPENVPN_CONFIG as well.
> 
> Also, make sure you can access https://api.nordvpn.com/v1/servers/countries and https://api.nordvpn.com/v1/servers/groups in browser.

I'm running it on Synology Docker. So I can't access it from the browser.
Internet modem-wired/wireless router-Synology is connected to NAS.

**Comment by lemminol** [comment]
> I think the error is curl: (6) Could not resolve host: downloads.nordcdn.com.
> Looks like need to update the script to the new download server as the host "downloads.nordcdn.com" is no longer valid.

I'm sorry. I do not know the details of this field. I'm using Synology NAS Docker and I don't know how to update. I put the nordvpn -> updateConfigs.sh file on the NAS and ran it as a task schedule. But nothing has changed.

**Comment by ilike2burnthing** [comment]
Being able to access them on your computer's browser should be fine, so long as you haven't manually set a different DNS. If you can't, then we can try setting a different DNS. If you can, then please post either a copy&paste of all your settings for the container or screenshots.

**Comment by RickyXwang** [comment]
@ilike2burnthing is right, the config files should be accessible (I should have been more careful when reading the code). What is the output/log when you run updateConfig? As mention, your run cmd/setting will help diagnosis the issues.

**Comment by lemminol** [comment]
[https://github.com/lemminol/docker](url)
Can I upload these pictures?

**Comment by ilike2burnthing** [comment]
Seems like you have a few things missing - https://haugene.github.io/docker-transmission-openvpn/synology-nas/

**Comment by lemminol** [comment]
@ilike2burnthing LOCAL_NETWORK, OPENVPN_OPTS, OPENVPN_CONFIG were added. But the problem appears the same.

**Comment by ilike2burnthing** [comment]
PUID and PGID also need added, as does NORDVPN_CATEGORY.

The `chmod` line appears to be missing from your script.

I'm assuming the NET_ADMIN setting, port, and volumes have been added as well, just not screenshot.

**Comment by lemminol** [comment]
@ilike2burnthing I tried what you told me. But the same problem occurs.

docker run \
    --cap-add=NET_ADMIN \
    --device=/dev/net/tun \
    -d \
    -v /volume1/docker/resolv.conf:/etc/resolv.conf \
    -v /volume2/1TB/1/:/data \
	-e "NORDVPN_COUNTRY=US" \
	-e "NORDVPN_CATEGORY=legacy_p2p" \
	-e "NORDVPN_PROTOCOL=tcp" \
    -e "OPENVPN_PROVIDER=nordvpn" \
    -e "OPENVPN_CONFIG=" \    # I read that it is okay to leave it blank in nordvpn.
    -e "OPENVPN_USERNAME=nordid(email)" \
    -e "OPENVPN_PASSWORD=password" \
    -e "LOCAL_NETWORK=192.168.10.0/24" \
    -e "OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60" \
    -e "PGID=100" \
    -e "PUID=1026" \
	-e "TZ-Asia/seoul" \
    -p 9091:9091 \
    --sysctl net.ipv6.conf.all.disable_ipv6=0 \
    --name "transmission-openvpn-syno" \
    haugene/transmission-openvpn:latest

docker log:

Using OpenVPN provider: nordvpn
2020-10-01 13:08:15 Checking curl installation
2020-10-01 13:08:15 Removing existing configs
2020-10-01 13:08:15 Selecting the best server...
2020-10-01 13:08:15 Searching for technology: openvpn_tcp
2020-10-01 13:08:15 Unable to find a server with the specified parameters, using any recommended server
2020-10-01 13:08:15 Best server : 
2020-10-01 13:08:15 Downloading config: default.ovpn
2020-10-01 13:08:15 Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_tcp/servers/.tcp.ovpn
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:06 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:07 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:08 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:09 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:10 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:11 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:12 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:13 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:14 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:15 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:16 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:17 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:18 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:19 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:21 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:22 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:23 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:24 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:25 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:26 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:27 --:--:--     0curl: (6) Could not resolve host: downloads.nordcdn.com
No VPN configuration provided. Using default.
Setting OPENVPN credentials...
adding route to local network 192.168.10.0/24 via 172.17.0.1 dev eth0
Options error: In [CMD-LINE]:1: Error opening configuration file: /etc/openvpn/nordvpn/default.ovpn
Use --help for more information.

**Comment by RickyXwang** [comment]
What DNS are you using? Can you try ping downloads.nordcdn.com inside the container? Also, ping 8.8.8.8 to check if the network is working.

**Comment by lemminol** [comment]
root@lEMMINOl:~# ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=114 time=37.4 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=114 time=37.4 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=114 time=37.2 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=114 time=37.2 ms
64 bytes from 8.8.8.8: icmp_seq=5 ttl=114 time=37.0 ms
64 bytes from 8.8.8.8: icmp_seq=6 ttl=114 time=37.2 ms
64 bytes from 8.8.8.8: icmp_seq=7 ttl=114 time=36.4 ms
64 bytes from 8.8.8.8: icmp_seq=8 ttl=114 time=36.9 ms
64 bytes from 8.8.8.8: icmp_seq=9 ttl=114 time=37.2 ms
64 bytes from 8.8.8.8: icmp_seq=10 ttl=114 time=37.1 ms
64 bytes from 8.8.8.8: icmp_seq=11 ttl=114 time=37.2 ms
64 bytes from 8.8.8.8: icmp_seq=12 ttl=114 time=37.4 ms
64 bytes from 8.8.8.8: icmp_seq=13 ttl=114 time=37.6 ms
64 bytes from 8.8.8.8: icmp_seq=14 ttl=114 time=36.7 ms
64 bytes from 8.8.8.8: icmp_seq=15 ttl=114 time=36.8 ms
64 bytes from 8.8.8.8: icmp_seq=16 ttl=114 time=37.2 ms
64 bytes from 8.8.8.8: icmp_seq=17 ttl=114 time=36.7 ms
64 bytes from 8.8.8.8: icmp_seq=18 ttl=114 time=36.7 ms
64 bytes from 8.8.8.8: icmp_seq=19 ttl=114 time=36.5 ms
64 bytes from 8.8.8.8: icmp_seq=20 ttl=114 time=37.4 ms
64 bytes from 8.8.8.8: icmp_seq=21 ttl=114 time=37.5 ms
64 bytes from 8.8.8.8: icmp_seq=22 ttl=114 time=37.1 ms
64 bytes from 8.8.8.8: icmp_seq=23 ttl=114 time=37.1 ms
64 bytes from 8.8.8.8: icmp_seq=24 ttl=114 time=37.3 ms
64 bytes from 8.8.8.8: icmp_seq=25 ttl=114 time=37.0 ms
^C
--- 8.8.8.8 ping statistics ---
25 packets transmitted, 25 received, 0% packet loss, time 24039ms
rtt min/avg/max/mdev = 36.451/37.138/37.660/0.345 ms
root@lEMMINOl:~# 

 DNS?  I use synology.me ddns.  There is no other use.

**Comment by RickyXwang** [comment]
DNS is different than DDNS, you can google a bit more if you want to know. Try ping inside the container, to do so, find out the container id by `docker container list` then do `docker exec -it <id> /bin/bash` to get a shell of the container.

**Comment by ilike2burnthing** [comment]
On your computer can you download these files?
https://downloads.nordcdn.com/configs/files/ovpn_udp/servers/ie81.nordvpn.com.udp.ovpn
https://downloads.nordcdn.com/configs/files/ovpn_udp/servers/ee41.nordvpn.com.udp.ovpn

Also, can you can access https://api.nordvpn.com/v1/servers/countries and https://api.nordvpn.com/v1/servers/groups and https://api.nordvpn.com/v1/technologies as that seems to be where your problem lies

**Comment by lemminol** [comment]
@RickyXwang 
clear
root@lEMMINOl:~# docker exec -it bce0b472bf58 /bin/bash
Error response from daemon: Container bce0b472bf584a987e32b49dddd0997e26e8f93cd29a7a69e4bcdd0faa116d86 is not running
root@lEMMINOl:~# docker exec -it bce0b472bf58 /bin/bash
root@bce0b472bf58:/# ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
root@lEMMINOl:~# 

I can't ping test because the container keeps freezing. And I don't see the transmission-openvpn container in Synology Docker.  So I run the container with the portain container and look at the log.

**Comment by lemminol** [comment]
@ilike2burnthing 
You can download it from a smartphone connected to the same router via wifi, not a computer, or view the contents by accessing countries, groups, and technologies.

**Comment by RickyXwang** [comment]
Somethings are not right if the container keeps freezing. I am not familiar with Portainer, can you try to stop it and run it with docker run and see if you can get a stable shell?
There is also a problem if you can access those files mentioned by ilike2burnthing, are there any error codes? try `wget <url>` in the Synology shell and see if you can access/download them from the Synology NAS.

**Comment by ilike2burnthing** [comment]
Set your computer to use Cloudflare's DNS and see if that resolves the issue - https://1.1.1.1/dns/ (scroll down for setup instructions)

If so then we can set up the container to use that DNS

**Comment by lemminol** [comment]
@ilike2burnthing 
in resolv.conf
nameserver 8.8.4.4
nameserver 8.8.8.8
nameserver 1.1.1.1
It is set like this.

**Comment by lemminol** [comment]
@RickyXwang @ilike2burnthing 
When running the container, the firewall is disabled, so it runs.
It's so vain, but thanks for your help.
However, the container doesn't appear in the synology docker UI yet, it needs to be started with a container called Portainer. You may not know what ports to open in the firewall.

**Comment by ilike2burnthing** [comment]
You should just need to open 9091

**Comment by yansigit** [comment]
I was facing same issue today and found two solutions

1. build dockerfile and modify /etc/resolv.conf using it. 127.0.0.11 to 8.8.8.8 or so on
2.  (recommended way) set network_mode: bridge in docker-compose.yml file

It would solve the problem as charm

**Comment by KillahInstinct1** [comment]
I found these issues were mostly because of not being allowed in the firewall and/or router. IE: You need to allow the subnet from your bridge in the firewall access.

You can test this easily by checking if you can ping 8.8.8.8 from the terminal in Docker.

**Comment by ilike2burnthing** [comment]
Old links, they're dead, try:
- https://downloads.nordcdn.com/configs/files/ovpn_udp/servers/ie181.nordvpn.com.udp.ovpn
- https://downloads.nordcdn.com/configs/files/ovpn_udp/servers/ee70.nordvpn.com.udp.ovpn

**Comment by jlxq0** [comment]
Got it. Is there a way to use these directly though, no "auto discovery"? That's still failing.

**Comment by ilike2burnthing** [comment]
What's the error you're getting?

Provide your Docker compose file or run command for the container.

**Comment by jlxq0** [comment]
I'm getting the following error message on start:

```
Starting container with revision: fd609f2ace1970858d3c32fcbd6c271b3d274d39
TRANSMISSION_HOME is currently set to: /config/transmission-home
Creating TUN device /dev/net/tun
Using OpenVPN provider: NORDVPN
Running with VPN_CONFIG_SOURCE auto
Provider NORDVPN has a bundled setup script. Defaulting to internal config
Executing setup script for NORDVPN
/etc/openvpn/nordvpn/..
INFO: OVPN: Checking curl installation
INFO: OVPN: DNS resolution ok
ERROR: ERROR: OVPN: cannot ping https://downloads.nordcdn.com/configs/files, network or internet unavailable. Cannot download NORDVPN configuration files
```

I'm on k8s and this is my current `deployment.yaml`:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
  namespace: mediacenter
  labels:
    app: transmission
  annotations:
    keel.sh/match-tag: "true"
    keel.sh/policy: force
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 1440m"
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: transmission
  template:
    metadata:
      labels:
        app: transmission
    spec:
      containers:
        - name: transmission
          image: haugene/transmission-openvpn:edge
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media01
              mountPath: /media01
          ports:
            - containerPort: 9091
          env:
            - name: TZ
              value: "Asia/Singapore"
            - name: OPENVPN_PROVIDER
              value: NORDVPN
            - name: OPENVPN_CONFIG
              value: singapore
            - name: OPENVPN_USERNAME
              value: abcdef
            - name: OPENVPN_PASSWORD
              value: abcdef
            - name: LOCAL_NETWORK
              value: "10.0.0.0/16"
            - name: HEALTH_CHECK_HOST
              value: github.com
            - name: NORDVPN_COUNTRY
              value: SG
            - name: NORDVPN_CATEGORY
              value: legacy_p2p
            - name: NORDVPN_PROTOCOL
              value: udp
            - name: NORDVPN_SERVER
              value: sg459.nordvpn.com
            - name: TRANSMISSION_WEB_UI
              value: flood-for-transmission
            - name: OPENVPN_OPTS
              value: "--pull-filter ignore ping"
            - name: TRANSMISSION_INCOMPLETE_DIR
              value: /media01/downloads/incomplete
            - name: TRANSMISSION_DOWNLOAD_DIR
              value: /media01/downloads/completed
            - name: TRANSMISSION_WATCH_DIR
              value: /media01/downloads/watch
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: transmissionconfig
        - name: media01
          persistentVolumeClaim:
            claimName: media01

```

It's been working for a year or so–and a couple days ago it just stopped.
