### ISSUE TITLE
unexpected route in container leaks some packets to LAN

### ISSUE THREAD

**Issue by justsomeguyontheinternet** [haugene/docker-transmission-openvpn#1382]
**Describe the problem**
I noticed my firewall was blocking some packets that the container is leaking to the LAN. I'm not really sure why these packets are being sent, but I wouldn't have expected them to leak to the LAN. There is a matching route in the route table. I obscured/annotated the IPs in the route list below, but there are no subnet conflicts.

![Untitled](https://user-images.githubusercontent.com/34630628/94638209-7c1cfa80-02a7-11eb-8396-076f4f8bcbc7.png)

```
root@containerID:/# ip route list
0.0.0.0/1 via [VPN peer] dev tun0 
default via [docker network gateway IP] dev eth0 
[VPN gateway] via [VPN peer] dev tun0 
[VPN peer] dev tun0 proto kernel scope link src [VPN client IP]
[VPN WAN IP] via [docker network gateway IP] dev eth0
128.0.0.0/1 via [VPN peer] dev tun0 
[docker subnet]/16 dev eth0 proto kernel scope link src [docker container IP] 
[LAN subnet]/24 via [docker network gateway IP] dev eth0 
```

If it matters this is with PIA provider. Generally everything seems to be working in the container (with the exception of port forwarding related to next gen servers/changes discussed in another issue).

**Host system:**
Linux Mint 20
Docker 19.03.8 from Ubuntu repositories

**Docker-Compose File**
```
version: '3.3'
services:
    transmission-openvpn:
        container_name: transmission1
        image: haugene/transmission-openvpn
        ports:
            - 9091:9091/tcp
        restart: unless-stopped
        cap_add:
            - NET_ADMIN
        #logging:
        #    driver: json-file
        #    options:
        #        max-size: 10m
        volumes:
            - ./data:/data
            - /mnt/Data/Share:/mnt/Share
            - /etc/localtime:/etc/localtime:ro
        environment:
            - PUID=1000
            - PGID=1000
            - CREATE_TUN_DEVICE=true
            - OPENVPN_PROVIDER=PIA
...
```
