### ISSUE TITLE
Containers routed through the transmission-vpn container are not accessible

### ISSUE THREAD

**Issue by sirtris** [haugene/docker-transmission-openvpn#1386]
**Describe the problem**
I want to use this container to connect to my VPN (Mullvad). My other containers (nzbget, radarr, sonarr, etc) should use this container as their network to also use the VPN connection. All containers can reach 'curl https://am.i.mullvad.net/connected' and use the VPN as intended. However I can no longer reach them. (my.server.ip:7878, or any other port fails) When I don't use the VPN container the other services work.

**Add your docker run command**
```
docker run -d \
              --name=VPN \
              --cap-add=NET_ADMIN \
              -v /srv/dev-disk-by-label-WD4TB/Downloadds:/data \
              -v /etc/localtime:/etc/localtime:ro \
              -e PUID=998 \
              -e PGID=100 \
              -e "CREATE_TUN_DEVICE=true" \
              -e "OPENVPN_PROVIDER=MULLVAD" \
              -e "OPENVPN_USERNAME=MY_MULLVAD_ACC_NUMBER" \
              -e "OPENVPN_PASSWORD=m" \
              -e "WEBPROXY_ENABLED=false" \
              -e "OPENVPN_CONFIG=mullvad_se-sto_tcp443" \
              -e LOCAL_NETWORK=192.168.178.0/24 \
              --log-driver json-file \
              --log-opt max-size=10m \
              -p 9091:9091 \
              -p 51820:51820/udp \
              -p 6789:6789 \
              -p 7878:7878 \
              -p 8989:8989 \
              -p 8686:8686 \
              -p 5299:5299 \
              --sysctl="net.ipv6.conf.all.disable_ipv6=0" \
              --restart unless-stopped \
              haugene/transmission-openvpn:latest-armhf
```
example for one of the other containers:
```
version: "2.1"
services:
  nzbget:
    image: linuxserver/nzbget
    container_name: nzbget
    network_mode: "container:VPN"
    environment:
      - PUID=998
      - PGID=100
      - TZ=America/New_York
    volumes:
      - /srv/dev-disk-by-label-WD4TB/Configs/nzbget:/config
      - /srv/dev-disk-by-label-WD4TB/Downloadds:/downloads
      - /srv/dev-disk-by-label-WD4TB/Media/Video/Filme:/movies
      - /srv/dev-disk-by-label-WD4TB/Media/Video/Serien:/tv
      - /srv/dev-disk-by-label-WD4TB/Media/Musik:/music
    restart: unless-stopped
```

**Logs**
```
REMOVED
```

**Host system:**
Raspberry Pi OS lite with OMV5
