### ISSUE TITLE
latest update broke VPNUnlimited

### ISSUE THREAD

**Issue by ksurl** [haugene/docker-transmission-openvpn#1393]
**Describe the problem**

updated to latest image version and all newly added torrents now are stuck on waiting for metadata. 

**Add your docker-compose**

```
version: '3'
services:
  transmission:
    image: haugene/transmission-openvpn:latest
    container_name: transmission
    environment:
      - CREATE_TUN_DEVICE=true
      - OPENVPN_PROVIDER=VPNUnlimited
      - OPENVPN_CONFIG=SERVER_LOCATION
      - OPENVPN_USERNAME=USER
      - OPENVPN_PASSWORD=PASSWORD
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60 --mute-replay-warnings
      - WEBPROXY_ENABLED=false
      - LOCAL_NETWORK=192.168.1.0/24
      - PUID=1005
      - PGID=1005      
      - TRANSMISSION_DHT_ENABLED=true
      - TRANSMISSION_DOWNLOAD_DIR=/data/complete
      - TRANSMISSION_IDLE_SEEDING_LIMIT=1
      - TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED=true
      - TRANSMISSION_INCOMPLETE_DIR=/data/incomplete
      - TRANSMISSION_MESSAGE_LEVEL=1
      - TRANSMISSION_PEER_PORT=49165
      - TRANSMISSION_RATIO_LIMIT=0
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
      - TRANSMISSION_RENAME_PARTIAL_FILES=true
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      - TRANSMISSION_RPC_PASSWORD=PASSWORD
      - TRANSMISSION_RPC_USERNAME=USER
      - TRANSMISSION_TRASH_ORIGINAL_TORRENT_FILES=true
      - TRANSMISSION_UMASK=18
      - TRANSMISSION_UTP_ENABLED=true
      - TRANSMISSION_WATCH_DIR=/data
      - TRANSMISSION_WATCH_DIR_ENABLED=true
      - TRANSMISSION_HOME=/data/config
      - TRANSMISSION_WEB_UI=combustion
    cap_add:
      - NET_ADMIN
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - 9091:9091
      - 51413:51413
    volumes:
      - transmission-config:/config
      - '/mnt/share/downloads/:/data'
    restart: unless-stopped
```
**Logs**

logs do not show any errors

**Host system:**

Ubuntu 18.04.5 in a vm
Docker 19.03.13
image is amd64 architecture

**Other info**
I rolled back to 2.13 manually and it is working fine. I noticed 2.13 is showing as latest version in github releases but the hash for 2.13 and latest on docker hub do not match. 2.13 released august 22, but the latest build released sept 29.
