### ISSUE TITLE
Unrecognized option error

### ISSUE THREAD

**Issue by PriamX** [haugene/docker-transmission-openvpn#1403]
Hi all.

My transmission-openvpn containing never fully starts up and gets itself in a restart cycle (over and over).

In the log output, this is the last bit before it restarts:

```
2020-10-17 12:39:21 Checking line endings
2020-10-17 12:39:21 Updating configs for docker-transmission-openvpn
Starting OpenVPN using config default.ovpn
Setting OPENVPN credentials...
adding route to local network 192.168.0.0/24 via 172.17.0.1 dev eth0
Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/nordvpn/default.ovpn:1: html (2.4.4)
Use --help for more information.
```

It's that "options error" that I'm thinking is the issue.  Here's my compose file:
```
---
version: "2.1"
services:
  transmission-openvpn:
    cap_add:
      - NET_ADMIN
    container_name: transmission-openvpn
    restart: always
    environment:
      - PUID=998
      - PGID=996
      - CREATE_TUN_DEVICE=true
      - OPENVPN_PROVIDER=NORDVPN
      - NORDVPN_COUNTRY=US
      - NORDVPN_CATEGORY=legacy_p2p
      - NORDVPN_PROTOCOL=udp
      - OPENVPN_USERNAME=xxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - OPENVPN_PASSWORD=xxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - WEBPROXY_ENABLED=false
      - LOCAL_NETWORK=192.168.0.0/24
      - TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=false
      - DNS=8.8.8.8,8.8.4.4
    image: haugene/transmission-openvpn
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - 9091:9091/tcp # transmission
    volumes:
      - /docker/downloads/:/data
      - /docker/downloads/:/downloads
      - /etc/localtime:/etc/localtime:ro
```

I'm running on CentOS 7.8, with Docker 19.03.13

Any help or advice would be appreciated.

Thank you!
