### ISSUE TITLE
Dev version unable to download via magnet (or Radarr/Medusa).

### ISSUE THREAD

**Issue by jnines** [haugene/docker-transmission-openvpn#1421]
**Describe the problem**
Had no issues with the mainline image.  After updating to the Dev version, as to get the updated PIA configs, I'm no longer able to download via magnets, Radarr/Medusa are affected as well (I'm assuming they're using essentially the same thing).  At first I though it was the server I was connected to, tried multiple PIA servers, no joy.  Looking at the logs I got constant "Connection failed", "Retrying scrape", etc.  Trying an actual .torrent file works, I tested this with the Big Buck Bunny torrent (Creative Commons).  Magnet would just sit there and throw errors, downloading and loading the .torrent file downloaded fine.

**Add your docker run command**
```
  transmission-vpn:
    container_name: transmission-vpn
    image: haugene/transmission-openvpn:dev
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: always
    ports:
    - 9006:9091
    - 42000:42000
    - 9008:9117 # Jacket
    - 9005:7878 # Radarr
    - 9001:8081 # Medusa
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCK}/transmission-vpn/data:/data
      - ${DOCK}/transmission-vpn/shared:/shared
      - ${DL}:/data/watch
      - ${DL}/completed:/data/completed
      - ${DL}/incomplete:/data/incomplete
    environment:
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_USERNAME=${VPN_USERNAME}
      - OPENVPN_PASSWORD=${VPN_PASSWORD}
      - OPENVPN_CONFIG=${VPN_CONFIG}
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=10.10.10.0/24
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=false
      - TRANSMISSION_RPC_HOST_WHITELIST=127.0.0.1,10.10.10.*,10.10.20.*,10.10.30.*
      - TRANSMISSION_RPC_PASSWORD=
      - TRANSMISSION_RPC_USERNAME=
#      - TRANSMISSION_UMASK=002
      - TRANSMISSION_RATIO_LIMIT=1.00
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
    logging:
        driver: json-file
        options:
            max-size: 10m
    networks:
      - media
```

**Logs**
Magnet Link
> [2020-10-25 00:06:45.080] Transmission 3.00 (bb6b5a062e) started (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/session.c:769)
> [2020-10-25 00:06:45.081] RPC Server Adding address to whitelist: 127.0.0.1 (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/rpc-server.c:956)
> [2020-10-25 00:06:45.081] RPC Server Adding address to whitelist: 10.10.10.* (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/rpc-server.c:956)
> [2020-10-25 00:06:45.081] RPC Server Adding address to whitelist: 10.10.20.* (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/rpc-server.c:956)
> [2020-10-25 00:06:45.081] RPC Server Adding address to whitelist: 10.10.30.* (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/rpc-server.c:956)
> [2020-10-25 00:06:45.081] RPC Server Adding address to whitelist: 127.0.0.1 (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/rpc-server.c:956)
> [2020-10-25 00:06:45.081] RPC Server Serving RPC and Web requests on 0.0.0.0:9091/transmission/ (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/rpc-server.c:1243)
> [2020-10-25 00:06:45.081] Port Forwarding Stopped (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/port-forwarding.c:196)
> [2020-10-25 00:06:45.081] Using settings from "/data/transmission-home" (/home/buildozer/aports/community/transmission/src/transmission-3.00/daemon/daemon.c:646)
> [2020-10-25 00:06:45.081] Saved "/data/transmission-home/settings.json" (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/variant.c:1221)
> [2020-10-25 00:06:45.081] Watching "/data/watch" for new .torrent files (/home/buildozer/aports/community/transmission/src/transmission-3.00/daemon/daemon.c:698)
> [2020-10-25 00:07:00.091] web will verify tracker certs using envvar CURL_CA_BUNDLE: none (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/web.c:455)
> [2020-10-25 00:07:00.091] web NB: this only works if you built against libcurl with openssl or gnutls, NOT nss (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/web.c:457)
> [2020-10-25 00:07:00.091] web NB: invalid certs will show up as 'Could not connect to tracker' like many other errors (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/web.c:458)
> [2020-10-25 00:07:02.081] Changed open file limit from 1048576 to 1024 (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/fdlimit.c:408)
> [2020-10-25 00:07:20.080] Saved "/data/transmission-home/torrents/dd8255ecdc7ca55fb0bbf81323d87062db1f6d1c.torrent" (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/variant.c:1221)
> [2020-10-25 00:07:20.080] Big+Buck+Bunny Queued for verification (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/verify.c:272)
> [2020-10-25 00:07:20.080] Big+Buck+Bunny Verifying torrent (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/verify.c:220)
> [2020-10-25 00:08:25.081] Big+Buck+Bunny Connection failed (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/announcer.c:1085)
> [2020-10-25 00:08:25.081] Big+Buck+Bunny Retrying announce in 20 seconds. (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/announcer.c:1094)
> [2020-10-25 00:08:25.081] Big+Buck+Bunny Scrape error: Connection failed (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/announcer.c:1392)
> [2020-10-25 00:08:25.081] Big+Buck+Bunny Retrying scrape in 20 seconds. (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/announcer.c:1401)
> [2020-10-25 00:08:25.081] Big+Buck+Bunny Connection failed (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/announcer.c:1085)
> [2020-10-25 00:08:25.081] Big+Buck+Bunny Retrying announce in 335 seconds. (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/announcer.c:1094)
> [2020-10-25 00:08:25.081] Big+Buck+Bunny Connection failed (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/announcer.c:1085)
> [2020-10-25 00:08:25.081] Big+Buck+Bunny Retrying announce in 20 seconds. (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/announcer.c:1094)
> [2020-10-25 00:08:25.081] Big+Buck+Bunny Connection failed (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/announcer.c:1085)
> [2020-10-25 00:08:25.081] Big+Buck+Bunny Retrying announce in 20 seconds. (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/announcer.c:1094)
> [2020-10-25 00:08:25.081] Big+Buck+Bunny Connection failed (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/announcer.c:1085)
> [2020-10-25 00:08:25.081] Big+Buck+Bunny Retrying announce in 20 seconds. (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/announcer.c:1094)
> [2020-10-25 00:09:04.084] Big+Buck+Bunny Removing torrent (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/torrent.c:2078)
> [2020-10-25 00:09:04.084] Big+Buck+Bunny Pausing (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/torrent.c:2022)

.Torrent, still having issues it seems but starts downloading/finishes.

> [2020-10-25 00:10:34.084] Saved "/data/transmission-home/torrents/dd8255ecdc7ca55fb0bbf81323d87062db1f6d1c.torrent" (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/variant.c:1221)
> [2020-10-25 00:10:34.084] Big Buck Bunny Queued for verification (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/verify.c:272)
> [2020-10-25 00:10:34.084] Big Buck Bunny Verifying torrent (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/verify.c:220)
> [2020-10-25 00:11:35.083] Big Buck Bunny Scrape error: Connection failed (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/announcer.c:1392)
> [2020-10-25 00:11:35.083] Big Buck Bunny Retrying scrape in 20 seconds. (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/announcer.c:1401)
> [2020-10-25 00:11:35.083] Big Buck Bunny Connection failed (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/announcer.c:1085)
> [2020-10-25 00:11:35.083] Big Buck Bunny Retrying announce in 330 seconds. (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/announcer.c:1094)
> [2020-10-25 00:11:35.083] Big Buck Bunny Connection failed (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/announcer.c:1085)
> [2020-10-25 00:11:35.083] Big Buck Bunny Retrying announce in 20 seconds. (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/announcer.c:1094)
> [2020-10-25 00:11:35.083] Big Buck Bunny Scrape error: Connection failed (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/announcer.c:1392)
> [2020-10-25 00:11:35.083] Big Buck Bunny Retrying scrape in 20 seconds. (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/announcer.c:1401)
> [2020-10-25 00:11:35.083] Big Buck Bunny Connection failed (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/announcer.c:1085)
> [2020-10-25 00:11:35.083] Big Buck Bunny Retrying announce in 327 seconds. (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/announcer.c:1094)
> [2020-10-25 00:11:35.083] Big Buck Bunny Scrape error: Connection failed (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/announcer.c:1392)
> [2020-10-25 00:11:35.083] Big Buck Bunny Retrying scrape in 20 seconds. (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/announcer.c:1401)
> [2020-10-25 00:11:35.083] Big Buck Bunny Connection failed (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/announcer.c:1085)
> [2020-10-25 00:11:35.083] Big Buck Bunny Retrying announce in 338 seconds. (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/announcer.c:1094)
> [2020-10-25 00:11:35.083] Big Buck Bunny Connection failed (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/announcer.c:1085)
> [2020-10-25 00:11:35.083] Big Buck Bunny Retrying announce in 20 seconds. (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/announcer.c:1094)
> [2020-10-25 00:11:43.085] Big Buck Bunny State changed from "Incomplete" to "Complete" (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/torrent.c:2302)
> [2020-10-25 00:11:43.085] Big Buck Bunny moving "/data/incomplete/Big Buck Bunny/Big Buck Bunny.en.srt" to "/data/completed/Big Buck Bunny/Big Buck Bunny.en.srt" (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/torrent.c:3294)
> [2020-10-25 00:11:43.085] Big Buck Bunny moving "/data/incomplete/Big Buck Bunny/Big Buck Bunny.mp4" to "/data/completed/Big Buck Bunny/Big Buck Bunny.mp4" (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/torrent.c:3294)
> [2020-10-25 00:11:43.085] Big Buck Bunny moving "/data/incomplete/Big Buck Bunny/poster.jpg" to "/data/completed/Big Buck Bunny/poster.jpg" (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/torrent.c:3294)

**Host system:**
Ubuntu 20.04 Server, Docker 19.03.13, Docker-Compose 1.27.4
