### ISSUE TITLE
curl icanhazip.com giving me different ip after every restart

### ISSUE THREAD

**Issue by mouzzampk2014** [haugene/docker-transmission-openvpn#1424]
Hi, 

I think I am missing something. I added `torguard` .ovpn and also forwarded the incoming port but I am not getting same ip I have in .ovpn. Not sure where I am going wrong with configuration :). I already tried two or three .ovpn but I am getting different ip thank I have in .ovpn. Thank you

This one I am using in terminal to find the ip `docker exec -it transmissionvpn curl icanhazip.com`

.ovpn file is in this location `/home/pi/.config/appdata/.openvpn`

This is my compose

```
  transmissionvpn:
    image: haugene/transmission-openvpn:dev-armhf
    hostname: Tail
    ports:
      - 51413:51413
      - 51413:51413/udp
      - 6881:6881
      - 6881:6881/udp
      - 9091:9091
    cap_add:
      - NET_ADMIN
    container_name: transmissionvpn
    devices:
      - /dev/net/tun
    dns:
      - 1.1.1.1
      - 8.8.8.8
    environment:
      - CREATE_TUN_DEVICE=true
      - LOCAL_NETWORK=192.168.1.0/24
      - OPENVPN_OPTS=
      - OPENVPN_PASSWORD=${VPN_PASS}
      - OPENVPN_PROVIDER=TORGUARD
      - OPENVPN_USERNAME=${VPN_USER}
      - PGID=1000
      - PUID=1000
      - TRANSMISSION_DOWNLOAD_DIR=/storage/downloads
      - TRANSMISSION_HOME=/config
      - TRANSMISSION_INCOMPLETE_DIR=/storage/downloads
      - TRANSMISSION_WATCH_DIR=/storage/downloads
      - TZ=Europe/London
    logging:
      driver: json-file
      options:
        max-file: 10
        max-size: 200k
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/pi/.config/appdata/transmissionvpn:/config
      - /mnt:/storage
      - /home/pi/.config/appdata/.openvpn:/config/openvpn
      - /home/pi/.config/appdata/.openvpn:/etc/openvpn/custom/
```
