### ISSUE TITLE
Transmission Listening Port Closed

### ISSUE THREAD

**Issue by NathanMagnus** [haugene/docker-transmission-openvpn#1434]
**Issue**
After upgrading to the latest version, the Transmission Web UI indicates that the "Listening Port" is closed. Additionally, torrents are not downloading.
I did not change any of my previously working configuration other than removing the mounting of `/dev/net/tun`

**Docker Compose**
```
version: '3.4'
services:
  transmission-openvpn:
    container_name: transmission-openvpn
    image: haugene/transmission-openvpn
    cap_add:
      - NET_ADMIN
    restart: always
    ports:
      - 9091:9091 #transmission
    dns:
      - ${DNS_1} # 8.8.4.4
      - ${DNS_2} # 8.8.8.8
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${TRANSMISSION_BASE}:/data
    environment:
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_USERNAME=${VPN_USER}
      - OPENVPN_PASSWORD=${VPN_PASSWORD}
      - OPENVPN_CONFIG=Switzerland
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=${LOCAL_NETWORK}
      - TRANSMISSION_RPC_WHITELIST=${LOCAL_NETWORK_WILDCARDS}
      - TRANSMISSION_RPC_WHITELIST_ENABLED=false
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      - TRANSMISSION_RPC_ENABLED=true
      - TRANSMISSION_RPC_USERNAME=${TRANSMISSION_USERNAME}
      - TRANSMISSION_RPC_PASSWORD=${TRANSMISSION_PASSWORD}
      - TRANSMISSION_RPC_URL=/transmission/
      - TRANSMISSION_DHT_ENABLED=true
      - TRANSMISSION_LAZY_BITFIELD_ENABLED=true
      - TRANSMISSION_LPD_ENABLED=true
      - TRANSMISSION_PEX_ENABLED=true
      - TRANSMISSION_PREALLOCATION=true
      - TRANSMISSION_QUEUE_STALLED_ENABLED=true
      - TRANSMISSION_QUEUE_STALLED_MINUTES=30
      - TRANSMISSION_DOWNLOAD_QUEUE_ENABLED=false
      - TRANSMISSION_DOWNLOAD_LIMIT_ENABLED=false
```

**Logs **
```
Using OpenVPN provider: PIA
Provider PIA has a custom startup script, executing it
Downloading OpenVPN config bundle openvpn-nextgen into temporary file /tmp/tmp.ONDFMC
Extract OpenVPN config bundle into PIA directory /etc/openvpn/pia
Modify configs for this container
Starting OpenVPN using config Switzerland.ovpn
Setting OpenVPN credentials...
adding route to local network 192.168.50.0/24 via 172.18.0.1 dev eth0
Thu Oct 29 19:43:01 2020 OpenVPN 2.4.9 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Apr 20 2020
Thu Oct 29 19:43:01 2020 library versions: OpenSSL 1.1.1g  21 Apr 2020, LZO 2.10
Thu Oct 29 19:43:01 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Thu Oct 29 19:43:01 2020 CRL: loaded 1 CRLs from file [[INLINE]]
Thu Oct 29 19:43:01 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]*******:1198
Thu Oct 29 19:43:01 2020 UDP link local: (not bound)
Thu Oct 29 19:43:01 2020 UDP link remote: [AF_INET]*******:1198
Thu Oct 29 19:43:01 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Thu Oct 29 19:43:02 2020 [zurich403] Peer Connection Initiated with [AF_INET]212.102.37.150:1198
Thu Oct 29 19:43:03 2020 TUN/TAP device tun0 opened
Thu Oct 29 19:43:03 2020 /sbin/ip link set dev tun0 up mtu 1500
Thu Oct 29 19:43:03 2020 /sbin/ip addr add dev tun0 10.38.112.3/24 broadcast 10.38.112.255
Thu Oct 29 19:43:03 2020 /etc/openvpn/tunnelUp.sh tun0 1500 1558 10.38.112.3 255.255.255.0 init
Up script executed with tun0 1500 1558 10.38.112.3 255.255.255.0 init

Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.38.112.3
Updating Transmission settings.json with values from env variables
Using existing settings.json for Transmission /data/transmission-home/settings.json
Overriding alt-speed-down because TRANSMISSION_ALT_SPEED_DOWN is set to 3500
Overriding alt-speed-enabled because TRANSMISSION_ALT_SPEED_ENABLED is set to True
Overriding alt-speed-time-begin because TRANSMISSION_ALT_SPEED_TIME_BEGIN is set to 420
Overriding alt-speed-time-day because TRANSMISSION_ALT_SPEED_TIME_DAY is set to 127
Overriding alt-speed-time-enabled because TRANSMISSION_ALT_SPEED_TIME_ENABLED is set to True
Overriding alt-speed-time-end because TRANSMISSION_ALT_SPEED_TIME_END is set to 135
Overriding alt-speed-up because TRANSMISSION_ALT_SPEED_UP is set to 300
Overriding bind-address-ipv4 because TRANSMISSION_BIND_ADDRESS_IPV4 is set to 10.38.112.3
Overriding dht-enabled because TRANSMISSION_DHT_ENABLED is set to True
Overriding download-dir because TRANSMISSION_DOWNLOAD_DIR is set to /data/downloads/
Overriding download-queue-enabled because TRANSMISSION_DOWNLOAD_QUEUE_ENABLED is set to False
Overriding incomplete-dir because TRANSMISSION_INCOMPLETE_DIR is set to /var/lib/transmission-daemon/incomplete
Overriding incomplete-dir-enabled because TRANSMISSION_INCOMPLETE_DIR_ENABLED is set to False
Overriding lpd-enabled because TRANSMISSION_LPD_ENABLED is set to True
Traceback (most recent call last):
  File "/etc/transmission/updateSettings.py", line 67, in <module>
    env_value = setting_type(env_value)
ValueError: invalid literal for int() with base 10: 'true'
Overriding pex-enabled because TRANSMISSION_PEX_ENABLED is set to True
Could not coerce TRANSMISSION_PREALLOCATION value true to expected type <class 'int'>
sed'ing True to true

-------------------------------------
Transmission will run as
-------------------------------------
User name:   root
User uid:    0
User gid:    0
-------------------------------------

STARTING TRANSMISSION
Provider PIA has a script for automatic port forwarding. Will run it now.
If you want to disable this, set environment variable DISABLE_PORT_UPDATER=yes
Transmission startup script complete.
Thu Oct 29 19:43:04 2020 Initialization Sequence Completed



yes: Broken pipe
port is 47286
the port has been bound to 47286  Thu Oct 29 19:43:11 CST 2020
transmission auth required
waiting for transmission to become responsive
transmission became responsive
   279   100%    2.50 GB  Done         0.0     0.0    0.5  Idle         ***********
Sum:             1.92 TB               0.0     0.0
setting transmission port to 47286
localhost:9091/transmission/rpc/ responded: "success"
Checking port...
Error: portTested: http error 0: No Response

initial setup complete!

waiting for rebind loop.................
token expiry 1609443782
remaining = 5421580

```

**Host system:**
"Ubuntu 18.04.5 LTS"
