### ISSUE TITLE
Container Unhealthy, Loses Connection Frequently

### ISSUE THREAD

**Issue by dannyvfilms** [haugene/docker-transmission-openvpn#1435]
I've had this for a while and I can't seem to get this container to reboot after it loses its connection. Finally caught it happening and captured a log. Notably, I do have the environment variable I've seen mentioned before enabled in Portainer, along with Restart Always. Unsure what else to do from here.

Log: https://pastebin.com/wspvcnsr

Environment: OPENVPN_OPTS = --inactive 3600 --ping 10 --ping-exit 60

**Comment by DonkeyHotNew** [comment]
Have you look on my thread #1389?
After I put `DROP_DEFAULT_ROUTE = false`, I didn't see it goes unhealthy or any other issues.

**Comment by haugene** [comment]
Or check this comment: https://github.com/haugene/docker-transmission-openvpn/issues/684#issuecomment-454702880
Interested to see the startup logs if windscribe sends you options that overrides your ping-exit.

We're rebuilding the whole parsing and fetching of configs. Will try to add a script that sets some of these filters and other best practices by default so we don't have to do it per provider.

**Comment by YujiShen** [comment]
Also having this issue, `DROP_DEFAULT_ROUTE = false` not work. It becomes more and more frequent after I upgrade to 3.0, no such issue for a long time. From once a day to multiple time a day, and now it becomes multiple times an hour... Not sure whether it is a problem of Docker 2.5.0. I revert back to 2.1.4 Ubuntu also get unhealthy very quickly...

Here is the log after it become unhealthy:
```
Tue Nov  3 06:36:13 2020 SIGUSR1[hard,] received, process restarting
Tue Nov  3 06:36:18 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Tue Nov  3 06:36:23 2020 RESOLVE: Cannot resolve host address: ca-montreal.privacy.network:1198 (Try again)
Tue Nov  3 06:36:28 2020 RESOLVE: Cannot resolve host address: ca-montreal.privacy.network:1198 (Try again)
Tue Nov  3 06:36:28 2020 Could not determine IPv4/IPv6 protocol
Tue Nov  3 06:36:28 2020 SIGUSR1[soft,init_instance] received, process restarting
Tue Nov  3 06:36:33 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Tue Nov  3 06:36:38 2020 RESOLVE: Cannot resolve host address: ca-montreal.privacy.network:1198 (Try again)
Tue Nov  3 06:36:43 2020 RESOLVE: Cannot resolve host address: ca-montreal.privacy.network:1198 (Try again)
Tue Nov  3 06:36:43 2020 Could not determine IPv4/IPv6 protocol
Tue Nov  3 06:36:43 2020 SIGUSR1[soft,init_instance] received, process restarting
Tue Nov  3 06:36:48 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Tue Nov  3 06:36:53 2020 RESOLVE: Cannot resolve host address: ca-montreal.privacy.network:1198 (Try again)
Tue Nov  3 06:36:58 2020 RESOLVE: Cannot resolve host address: ca-montreal.privacy.network:1198 (Try again)
Tue Nov  3 06:36:58 2020 Could not determine IPv4/IPv6 protocol
Tue Nov  3 06:36:58 2020 SIGUSR1[soft,init_instance] received, process restarting
Tue Nov  3 06:37:03 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Tue Nov  3 06:37:08 2020 RESOLVE: Cannot resolve host address: ca-montreal.privacy.network:1198 (Try again)
Tue Nov  3 06:37:13 2020 RESOLVE: Cannot resolve host address: ca-montreal.privacy.network:1198 (Try again)
...
```

My config:
```yaml
version: "3.3"
services:
  transmission-openvpn:
    container_name: transmission-openvpn
    image: haugene/transmission-openvpn:3.0.1
    cap_add:
      - NET_ADMIN
    restart: always
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - CREATE_TUN_DEVICE=true
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_CONFIG=CA Montreal
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - TRANSMISSION_UMASK=2
      - TRANSMISSION_CACHE_SIZE_MB=256
      - TRANSMISSION_RENAME_PARTIAL_FILES=true
      - TRANSMISSION_DOWNLOAD_QUEUE_ENABLED=false
      - TRANSMISSION_DOWNLOAD_QUEUE_SIZE=10
      - TRANSMISSION_RATIO_LIMIT_ENABLED=false
      - TRANSMISSION_UTP_ENABLED=true
      - TRANSMISSION_LPD_ENABLED=true
      - TRANSMISSION_INCOMPLETE_DIR_ENABLED=false
      - TRANSMISSION_START_ADDED_TORRENTS=false
      - TRANSMISSION_PREALLOCATION=1
      - TRANSMISSION_MAX_PEERS_GLOBAL=200000
      - TRANSMISSION_PEER_LIMIT_GLOBAL=200000
      - TRANSMISSION_PEER_LIMIT_PER_TORRENT=100
    logging:
      driver: json-file
      options:
        max-size: 10m
```
