### ISSUE TITLE
openvpn failing to connect - was working before

### ISSUE THREAD

**Issue by gregbert42** [haugene/docker-transmission-openvpn#1440]
After running without problems, I am all of a sudden getting failures with the openvpn / PIA portion. I believe they have recently made some changes to their servers, so this is likely related. I can verify that the same username and password is working with  dperson/openvpn-client docker image

Here is the error I am seeing:

```
transmission_openvpn | Extract OpenVPN config bundle into PIA directory /etc/openvpn/pia
transmission_openvpn | Modify configs for this container
transmission_openvpn | Starting OpenVPN using config Netherlands.ovpn
transmission_openvpn | Setting OpenVPN credentials...
transmission_openvpn | adding route to local network 192.168.2.0/24 via 192.168.112.1 dev eth0
transmission_openvpn | Sat Oct 31 19:57:31 2020 OpenVPN 2.4.9 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Apr 20 2020
transmission_openvpn | Sat Oct 31 19:57:31 2020 library versions: OpenSSL 1.1.1g  21 Apr 2020, LZO 2.10
transmission_openvpn | Sat Oct 31 19:57:31 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
transmission_openvpn | Sat Oct 31 19:57:31 2020 CRL: loaded 1 CRLs from file [[INLINE]]
transmission_openvpn | Sat Oct 31 19:57:31 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]212.102.34.161:1198
transmission_openvpn | Sat Oct 31 19:57:31 2020 UDP link local: (not bound)
transmission_openvpn | Sat Oct 31 19:57:31 2020 UDP link remote: [AF_INET]212.102.34.161:1198
transmission_openvpn | Sat Oct 31 19:57:31 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
transmission_openvpn | Sat Oct 31 19:57:31 2020 [amsterdam403] Peer Connection Initiated with [AF_INET]212.102.34.161:1198
transmission_openvpn | Sat Oct 31 19:57:32 2020 AUTH: Received control message: AUTH_FAILED
transmission_openvpn | Sat Oct 31 19:57:32 2020 SIGTERM[soft,auth-failure] received, process exiting
transmission_openvpn exited with code 0

```

Here is the relevant portion of my docker-compose.yaml (its part of a larger file)
```
  transmission:
    hostname: Transmission
    container_name: transmission_openvpn
    restart: unless-stopped
    image: haugene/transmission-openvpn
    dns: 8.8.8.8
    devices:
      - "/dev/net/tun:/dev/net/tun"
    cap_add:
      - "NET_ADMIN"
    volumes:
      - /mnt/OPERATIONS/Downloads/docker/:/downloads
      - /mnt/OPERATIONS/Downloads/docker/:/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=1002
      - PGID=1002
      - TZ=Europe/Zurich
      - "OPENVPN_PROVIDER=PIA"
      - "OPENVPN_CONFIG=Netherlands"
      - "OPENVPN_USERNAME=x[7numbers]"
      - "OPENVPN_PASSWORD=[MASKED]"
      - "LOCAL_NETWORK=192.168.2.0/24"
      - "TRANSMISSION_ALT_SPEED_DOWN=3500"
      - "TRANSMISSION_ALT_SPEED_TIME_BEGIN=420"
      - "TRANSMISSION_ALT_SPEED_TIME_END=1320"
      - "TRANSMISSION_ALT_SPEED_TIME_ENABLED=true"
      - "TRANSMISSION_ALT_SPEED_UP=0"
      - "TRANSMISSION_RATIO_LIMIT=0"
      - "TRANSMISSION_RATIO_LIMIT_ENABLED=true"
      - "TRANSMISSION_DOWNLOAD_DIR=/downloads/completed"
      - "TRANSMISSION_INCOMPLETE_DIR=/downloads/incomplete"
      - "TRANSMISSION_HOME=/downloads/transmission-home"
      - "TRANSMISSION_SPEED_LIMIT_UP=0"
      - "TRANSMISSION_SPEED_LIMIT_UP_ENABLED=true"
      - WEBPROXY_ENABLED=false
    ports:
      - 9092:9091
    logging:
      driver: json-file
      options:
        max-size: "10m"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

```

Thank you for any ideas.
