### ISSUE TITLE
event_wait : Interrupted system call (code=4)

### ISSUE THREAD

**Issue by c-hri-s** [haugene/docker-transmission-openvpn#1447]
I've been setting up njal.la as a custom VPN following its aquisition of IPredator, and have issues.

I can get the tunnel set up and working, but after an indeterminate amount of time (might be minutes, might be a couple of hours)'event_wait : Interrupted system call (code=4)' appears in the log and the container loses the connection to the VPN.

Transmission stays running, but bound to the VPN IP (so no traffic flows). The external IP of the container reverts to my non-VPN IP.

Restarting the container fixes the issue, but only for a short while.

Logs below:

```
Sun Nov  1 08:27:28 2020 us=756633 event_wait : Interrupted system call (code=4)                                                                                                   
Sun Nov  1 08:27:28 2020 us=756812 TCP/UDP: Closing socket                                                                                                                         
Sun Nov  1 08:27:28 2020 us=756872 SIGUSR1[hard,] received, process restarting                                                                                                     
Sun Nov  1 08:27:28 2020 us=757033 Restart pause, 5 second(s)                                                                                                                      
Sun Nov  1 08:27:33 2020 us=757114 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts                                           
Sun Nov  1 08:27:33 2020 us=757150 Re-using SSL/TLS context                                                                                                                        
Sun Nov  1 08:27:33 2020 us=757166 LZ4v2 compression initializing                                                                                                                  
Sun Nov  1 08:27:33 2020 us=757328 Control Channel MTU parms [ L:1622 D:1184 EF:66 EB:0 ET:0 EL:3 ]                                                                                
Sun Nov  1 08:27:33 2020 us=757364 Data Channel MTU parms [ L:1622 D:1200 EF:122 EB:406 ET:0 EL:3 ]                                                                                
Sun Nov  1 08:27:33 2020 us=757427 Local Options String (VER=V4): 'V4,dev-type tun,link-mtu 1558,tun-mtu 1500,proto UDPv4,comp-lzo,keydir 1,cipher AES-256-CBC,auth SHA1,keysize 25
6,tls-auth,key-method 2,tls-client'                                                                                                                                                
Sun Nov  1 08:27:33 2020 us=757439 Expected Remote Options String (VER=V4): 'V4,dev-type tun,link-mtu 1558,tun-mtu 1500,proto UDPv4,comp-lzo,keydir 0,cipher AES-256-CBC,auth SHA1,
keysize 256,tls-auth,key-method 2,tls-server'                                                                                                                                      
Sun Nov  1 08:27:33 2020 us=757457 TCP/UDP: Preserving recently used remote address: [AF_INET]198.167.192.25:1194                                                                  
Sun Nov  1 08:27:33 2020 us=757497 Socket Buffers: R=[212992->212992] S=[212992->212992]                                                                                           
Sun Nov  1 08:27:33 2020 us=757511 UDP link local: (not bound)                                                                                                                     
Sun Nov  1 08:27:33 2020 us=757524 UDP link remote: [AF_INET]198.167.192.25:1194                                                                                                   
Sun Nov  1 08:27:33 2020 us=801561 TLS: Initial packet from [AF_INET]198.167.192.25:1194, sid=49572b75 fa39a634                                                                    
Sun Nov  1 08:27:33 2020 us=855463 VERIFY OK: depth=1, CN=openvpn.njal.la                                                                                                          
Sun Nov  1 08:27:33 2020 us=855998 VERIFY KU OK                                                                                                                                    
Sun Nov  1 08:27:33 2020 us=856025 Validating certificate extended key usage                                                                                                       
Sun Nov  1 08:27:33 2020 us=856036 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication                                               
Sun Nov  1 08:27:33 2020 us=856048 VERIFY EKU OK                                                                                                                                   
Sun Nov  1 08:27:33 2020 us=856057 VERIFY OK: depth=0, CN=vpn-205                                                                                                                  
Sun Nov  1 08:27:37 2020 us=280455 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_AES_256_GCM_SHA384, 4096 bit RSA                                                                   
Sun Nov  1 08:27:37 2020 us=280517 [vpn-205] Peer Connection Initiated with [AF_INET]198.167.192.25:1194                                                                           
Sun Nov  1 08:27:38 2020 us=441244 SENT CONTROL [vpn-205]: 'PUSH_REQUEST' (status=1)                                                                                               
Sun Nov  1 08:27:38 2020 us=484639 PUSH: Received control message: 'PUSH_REPLY,topology subnet,route-gateway 198.167.205.1,compress lz4-v2,persist-key,persist-tun,redirect-gateway
 def1,explicit-exit-notify 1,route-ipv6 2000::/3,dhcp-option DNS 95.215.19.53,dhcp-option DNS 194.132.32.32,dhcp-option DNS 46.246.46.246,ping 10,ping-restart 120,ifconfig-ipv6 2a
02:6f8:2020:205:1::1015/112 2a02:6f8:2020:205:1::1,ifconfig 198.167.205.21 255.255.255.0,peer-id 1,cipher AES-256-GCM'                                                             
Sun Nov  1 08:27:38 2020 us=484825 OPTIONS IMPORT: timers and/or timeouts modified                                                                                                 
Sun Nov  1 08:27:38 2020 us=484839 OPTIONS IMPORT: explicit notify parm(s) modified                                                                                                
Sun Nov  1 08:27:38 2020 us=484847 OPTIONS IMPORT: compression parms modified                                                                                                      
Sun Nov  1 08:27:38 2020 us=484856 LZ4v2 compression initializing                                                                                                                  
Sun Nov  1 08:27:38 2020 us=484864 OPTIONS IMPORT: --persist options modified                                                                                                      
Sun Nov  1 08:27:38 2020 us=484871 OPTIONS IMPORT: --ifconfig/up options modified                                                                                                  
Sun Nov  1 08:27:38 2020 us=484878 OPTIONS IMPORT: route options modified                                                                                                          
Sun Nov  1 08:27:38 2020 us=484885 OPTIONS IMPORT: route-related options modified                                                                                                  
Sun Nov  1 08:27:38 2020 us=484892 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified                                                                                
Sun Nov  1 08:27:38 2020 us=484899 OPTIONS IMPORT: peer-id set                                                                                                                     
Sun Nov  1 08:27:38 2020 us=484906 OPTIONS IMPORT: adjusting link_mtu to 1625                                                                                                      
Sun Nov  1 08:27:38 2020 us=484913 OPTIONS IMPORT: data channel crypto options modified                                                                                            
Sun Nov  1 08:27:38 2020 us=484922 Data Channel: using negotiated cipher 'AES-256-GCM'                                                                                             
Sun Nov  1 08:27:38 2020 us=484946 Data Channel MTU parms [ L:1553 D:1200 EF:53 EB:406 ET:0 EL:3 ]                                                                                 
Sun Nov  1 08:27:38 2020 us=485054 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key                                                                        
Sun Nov  1 08:27:38 2020 us=485069 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key                                                                        
Sun Nov  1 08:27:38 2020 us=485082 Preserving previous TUN/TAP instance: tun0                                                                                                      
Sun Nov  1 08:27:38 2020 us=485130 Initialization Sequence Completed
```

**Comment by haugene** [comment]
What does your ovpn config file look like? And preferably also your docker run command or docker-compose file?

**Comment by c-hri-s** [comment]
docker-compose is as follows:

```
  transmission:
    container_name:   "transmission"
    image: haugene/transmission-openvpn:latest
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: always
    ports:
      - "9091:9091"
      - "8888:8888"
    dns:
      - 1.1.1.1
      - 8.8.8.8
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume1/docker/transmission-openvpn/scripts_dir:/scripts_dir:rw
      - /volume1/docker/transmission-openvpn/data:/data:rw
      - /volume1/public:/public:rw
      - /volume1/private/in_progress:/in_progress:rw
      - /volume1/docker/transmission-openvpn/config/Njalla-VPN.ovpn:/etc/openvpn/custom/default.ovpn:rw
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    environment:
      - OPENVPN_PROVIDER=CUSTOM
      - OPENVPN_USERNAME=blah
      - OPENVPN_PASSWORD=blah
      - TZ=Europe/London
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=192.168.1.0/24
      - HEALTH_CHECK_HOST=google.com
      - WEBPROXY_ENABLED=false
      - WEBPROXY_PORT=8888
      - TRANSMISSION_RATIO_LIMIT=0
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
      - TRANSMISSION_DHT_ENABLED=true
      - TRANSMISSION_SPEED_LIMIT_UP=100
      - TRANSMISSION_SPEED_LIMIT_UP_ENABLED=true
      - TRANSMISSION_SCRIPT_TORRENT_DONE_FILENAME=/scripts_dir/transmission-purge-completed.sh
      - TRANSMISSION_SCRIPT_TORRENT_DONE_ENABLED=true
      - TRANSMISSION_ENCRYPTION=1
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      - TRANSMISSION_RPC_ENABLED=true
      - TRANSMISSION_DOWNLOAD_QUEUE_ENABLED=false
      - TRANSMISSION_DOWNLOAD_QUEUE_SIZE=20
      - TRANSMISSION_RPC_PASSWORD=blah
      - TRANSMISSION_RPC_PORT=9091
      - TRANSMISSION_LPD_ENABLED=true
      - TRANSMISSION_PEX_ENABLED=true
      - TRANSMISSION_RPC_USERNAME=transmission
      - TRANSMISSION_RPC_WHITELIST="127.0.0.1,192.168.1.*,172.19.0.*"
      - TRANSMISSION_RPC_WHITELIST_ENABLED=true
      - TRANSMISSION_DOWNLOAD_DIR=/public
      - TRANSMISSION_INCOMPLETE_DIR=/in_progress
      - TRANSMISSION_INCOMPLETE_DIR_ENABLED=true
      - TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=false
      - TRANSMISSION_PEER_PORT_RANDOM_ON_START=true
```
And the config file is as follows:

```
# Njalla VPN Configuration
client
dev tun
proto udp4
#remote openvpn.njalla.no 1194
#remote openvpn.njalla.in 1194
#remote openvpn.njalla.fo 1194
remote 198.167.192.25 1194
remote 198.167.192.35 1194
remote 198.167.192.11 1194
remote 198.167.192.47 1194
remote 198.167.192.57 1194
remote 198.167.192.15 1194
remote 198.167.192.27 1194
remote 198.167.192.37 1194
remote 198.167.192.3 1194
remote 198.167.192.1 1194
remote 198.167.192.21 1194
remote 198.167.192.7 1194
remote 198.167.192.9 1194
remote 80.78.17.18 1194
remote 198.167.192.19 1194
remote 198.167.192.33 1194
remote 198.167.192.45 1194
remote 198.167.192.55 1194
remote 198.167.192.13 1194
remote 198.167.192.49 1194
remote 198.167.192.51 1194
remote 198.167.192.29 1194
remote 198.167.192.53 1194
remote 198.167.192.23 1194
remote 198.167.192.17 1194
remote 198.167.192.39 1194
remote 198.167.192.5 1194
remote 198.167.192.43 1194
remote 198.167.192.31 1194
remote 198.167.192.41 1194

resolv-retry infinite
nobind

key-direction 1

#ca [inline]
tls-client
#tls-auth [inline] 1
#cert [inline]
#key [inline]

remote-cert-tls server
auth-nocache
#compress lzo
#comp-lzo
comp-lzo no

#keepalive 10 30
cipher AES-256-CBC

persist-key
persist-tun

tun-mtu 1500
mssfix 1200
replay-window 512 60

# Enable this if your system does support it!
tls-version-min 1.2

# Wireless networks often produce a lot
# of duplicate packets.  Set this flag
# to silence duplicate packet warnings.
mute-replay-warnings

verb 4

<ca>
-----BEGIN CERTIFICATE-----
MIIFDjCCAvagAwIBAgIBADANBgkqhkiG9w0BAQsFADAaMRgwFgYDVQQDDA9vcGVu
dnBuLm5qYWwubGEwIBcNMTkwNjA1MTgyNjI1WhgPMjExOTA1MTIxODI2MjVaMBox
GDAWBgNVBAMMD29wZW52cG4ubmphbC5sYTCCAiIwDQYJKoZIhvcNAQEBBQADggIP
ADCCAgoCggIBAJq4Kto6+eDnQ2XrmbobESMQTKGODvxKs2zJP5X+6Z2LL2C2hmfr
Ur90oqFdQtiFO2rOAHkTgh9RZcIS5wBdfSl3yKqGUuz3mCx17X7ys+Qo9Q0q/uI3
7lakclW1qP5xiiIIhuK7jD/GNcSsIVNHRwKo96p9E6obgyEoeDUPV9pRsxNeiwYF
+SrfHbZFV8ghqF/uW/qAq62GUMPjfFj6fRetiIatch78lHiI/fnYLhqvMgWVwG9l
MA1TND0jMdzo5a3PpVIl1meIrh4zj3jjbwySCxGgpuoxUTOEVT3jGuDdatcByww3
Pydvnhfp0n8KO03yr0lS3P/UzmS2/oC4pEcfZ+cGQJeQJsEFlY8opahay+pugfIo
G7JNV9HIEsz6nBgyP9QWuiSuT7NNEUtJ2H+Vak9/Erdwhb90cpv6EQVrt3F+X97P
Me4Jy+HMYb8qRloRfjdelb41yw4o5WltClK/cuy26MmEITUWWDfWRGsoae6DBaCn
PJSkgTLl+DrlAxzE9tBlMeGofs78anUNJjkj+NxgEM+BKTpXkJoiIXyE0C778KhQ
AO8nlxC4g0NyktcxFX+o0P6O9LDO9nH/fA2Z92k8x6gxHfYu1oT3yhkL5gdxTY7N
10TAxWbhqdDRXDPcsgXF32LiBWCm8sOgpMJ1L4uchbSidHF2QYz5IJIVAgMBAAGj
XTBbMAwGA1UdEwQFMAMBAf8wCwYDVR0PBAQDAgEGMB0GA1UdDgQWBBQ83UzhnBHk
oJgL892PcE712QUo6jAfBgNVHSMEGDAWgBQ83UzhnBHkoJgL892PcE712QUo6jAN
BgkqhkiG9w0BAQsFAAOCAgEADhoL9xver+BXHTKBDGeMAdQ5vIGiiJGyGOUf1dpd
UBHyX7Ypq5dGxWvnhow6GC3gxeJ6ErCvGgsZ1eXlmcYLLyAdTPSAjQ6+X9dbUIqF
Jp7EL9Ql4UU3EWREOtcwffAr1JY3fOR2lsUWmeB+Nz7s+oSybEEPUqgswfgbSNGV
p801iOgIr81muion2DPMxtxkqaNAIbu9nllHaDUu2nmXiAU9org4V2erQbS5OjJ3
JXKu2FdWFHCgElCgu7MARDrlmsJFG0nfhYS9IRlBK9WOJ9qbaIuOQRy0+wQB4J2J
6EcuRxqk22cD+CAnUd5kEiRF6cGrWOMlNsL3gCU7hNJSVW2tFcdgMOpX713kdF9c
57NTA0Yt1VrnLSsr7YI0nRDrFnM01vg9VtxsxrAN45dFLHiETWGVtaRXEq+GpQtP
ynuVKp3vuzsAOUIe3CuCwXYDtW+jnCzExXqPjPhFtl6qnjLifShGSgKDjLe3YMSR
QRg4isMcYuayBWL26qWjGlUSlZ/aEQN+AgTKuvL4PA6R7/VAPGAwRf+JCawKaKHT
OhskUrWWxWRJgDoYcwy7V82q5RIIiPsDzFgNPFVO1THw/KrhXCSS5PyiUXBuy3ok
lRdX8C2D+igOd/zZ01aJwax45wFFPdKu5Nt8C2K6eko1AzdKtS4jAMwr+yz2BPaD
Oe4=
-----END CERTIFICATE-----
</ca>

<tls-auth>
-----BEGIN OpenVPN Static key V1-----
[key snipped]
-----END OpenVPN Static key V1-----
</tls-auth>
<cert>
-----BEGIN CERTIFICATE-----
[certificate snipped]
-----END CERTIFICATE-----
</cert>

<key>
-----BEGIN PRIVATE KEY-----
[private key snipped]
-----END PRIVATE KEY-----
</key>

```
