### ISSUE TITLE
RTNETLINK answers: File exists when adding local network route

### ISSUE THREAD

**Issue by c-patrick** [haugene/docker-transmission-openvpn#1448]
Hello,

Have been having a recent issuse with with container where RTNETLINK seems to attempt to add routes to the local network, but then reports that the file already exists and the container then exits and the process starts agan. I can't seem to find much about this, so any help would be appreciated.

**Host system:**
I am currently running the container on a CentOS 8 VM using docker compose and connection to the WebUI proxied via Traefik2 on network `t2_proxy`. I have recently switched to a CentOS host from a Ubuntu-based one, but as of yesterday both have been giving me the same errors, leading me to believe it is a problem with either my configuration of the container itself.

**Docker run command/compose file**
This is the relevant part of the compose file:
```
version: "3.7"

networks:
  t2_proxy:
    external:
      name: t2_proxy

services:
# Transmission
  transmission:
    container_name: transmission
    image: haugene/transmission-openvpn
    restart: unless-stopped
    networks:
      t2_proxy:
        ipv4_address: 192.168.100.5
    cap_add:
      - NET_ADMIN
    ports:
      - '$TRANSMISSION_PORT:9091'
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $REMOTEDIR/docker/Transmission:/data
      - $USERDIR/transmission/config:/config
    environment:
      OPENVPN_PROVIDER: PIA
      OPENVPN_CONFIG: Spain,Switzerland,Sweden,France
      OPENVPN_USERNAME: $PIA_USERNAME
      OPENVPN_PASSWORD: $PIA_PASSWORD
      LOCAL_NETWORK: $LOCAL_NETWORK
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      TRANSMISSION_RATIO_LIMIT: 1
      TRANSMISSION_RATIO_LIMIT_ENABLED: "true"
      TRANSMISSION_ALT_SPEED_DOWN: 2000
      TRANSMISSION_ALT_SPEED_ENABLED: "false"
      TRANSMISSION_ALT_SPEED_UP: 15
      TRANSMISSION_SPEED_LIMIT_DOWN: 6000
      TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED: "true"
      TRANSMISSION_SPEED_LIMIT_UP: 1
      TRANSMISSION_SPEED_LIMIT_UP_ENABLED: "true"
      TRANSMISSION_INCOMPLETE_DIR: /data/downloads/incomplete
      TRANSMISSION_INCOMPLETE_DIR_ENABLED: "true"
      TRANSMISSION_WATCH_DIR: /data/downloads/watch
      TRANSMISSION_WATCH_DIR_ENABLED: "true"
      TRANSMISSION_DOWNLOAD_DIR: /data/downloads/complete
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.transmission-vpn-rtr.entrypoints=https"
      - "traefik.http.routers.transmission-vpn-rtr.rule=Host(`transmission.$DOMAINNAME`)"
      - "traefik.http.routers.transmission-vpn-rtr.tls=true"
#      - "traefik.http.routers.transmission-vpn-rtr.tls.certresolver=dns-cloudflare"
      ## Middlewares
      - "traefik.http.routers.transmission-vpn-rtr.middlewares=chain-oauth@file,middlewares-rate-limit@file"
      ## HTTP Services
      - "traefik.http.routers.transmission-vpn-rtr.service=transmission-vpn-svc"
      - "traefik.http.services.transmission-vpn-svc.loadbalancer.server.port=9091"
      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
    logging:
      driver: json-file
      options:
        max-size: "10m"
```

**Logs**
The relevent log entries are:
```
Using OpenVPN provider: PIA
Provider PIA has a custom startup script, executing it
Downloading OpenVPN config bundle openvpn-nextgen into temporary file /tmp/tmp.LDcAKn
Extract OpenVPN config bundle into PIA directory /etc/openvpn/pia
Modify configs for this container
4 servers found in OPENVPN_CONFIG, Switzerland chosen randomly
Starting OpenVPN using config Switzerland.ovpn
Setting OpenVPN credentials...
adding route to local network 192.168.1.0/24 via 192.168.100.1 dev eth0
adding route to local network 192.168.100.0/24 via 192.168.100.1 dev eth0
RTNETLINK answers: File exists
Transmission exited with code 2
```

Obviously, I am happy to provide more information should that be helpful.

Thanks in advance for any help.
