### ISSUE TITLE
Unable to connect to trackers

### ISSUE THREAD

**Issue by bmanturner** [haugene/docker-transmission-openvpn#1465]
**Describe the problem**
I'm unable to connect to any trackers

**Add your docker run command**
<img width="1027" alt="Screen Shot 2020-11-05 at 3 55 48 PM" src="https://user-images.githubusercontent.com/8716214/98300845-c46bbe80-1fb1-11eb-8d60-4f0306547f13.png">

**Logs**
```
Starting container with revision: 1970f54b88424bf92bc782c3df87310336adf8f4,
Using OpenVPN provider: PIA,
Provider PIA has a custom startup script, executing it,
Downloading OpenVPN config bundle openvpn-nextgen into temporary file /tmp/tmp.FGdDGb,
Extract OpenVPN config bundle into PIA directory /etc/openvpn/pia,
Modify configs for this container,
Starting OpenVPN using config US Florida.ovpn,
Setting OpenVPN credentials...,
adding route to local network 192.168.1.0/24 via 172.17.0.1 dev eth0,
Thu Nov  5 15:49:14 2020 OpenVPN 2.4.9 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Apr 20 2020,
Thu Nov  5 15:49:14 2020 library versions: OpenSSL 1.1.1g  21 Apr 2020, LZO 2.10,
Thu Nov  5 15:49:14 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts,
Thu Nov  5 15:49:14 2020 CRL: loaded 1 CRLs from file [[INLINE]],
Thu Nov  5 15:49:15 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]156.146.42.112:1198,
Thu Nov  5 15:49:15 2020 UDP link local: (not bound),
Thu Nov  5 15:49:15 2020 UDP link remote: [AF_INET]156.146.42.112:1198,
Thu Nov  5 15:49:15 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this,
Thu Nov  5 15:49:15 2020 [miami407] Peer Connection Initiated with [AF_INET]156.146.42.112:1198,
Thu Nov  5 15:49:16 2020 TUN/TAP device tun0 opened,
Thu Nov  5 15:49:16 2020 /sbin/ip link set dev tun0 up mtu 1500,
Thu Nov  5 15:49:16 2020 /sbin/ip addr add dev tun0 10.47.112.3/24 broadcast 10.47.112.255,
Thu Nov  5 15:49:16 2020 /etc/openvpn/tunnelUp.sh tun0 1500 1558 10.47.112.3 255.255.255.0 init,
Up script executed with tun0 1500 1558 10.47.112.3 255.255.255.0 init,
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.47.112.3,
Updating Transmission settings.json with values from env variables,
Using existing settings.json for Transmission /data/transmission-home/settings.json,
Overriding bind-address-ipv4 because TRANSMISSION_BIND_ADDRESS_IPV4 is set to 10.47.112.3,
Overriding download-dir because TRANSMISSION_DOWNLOAD_DIR is set to /data/completed,
Overriding incomplete-dir because TRANSMISSION_INCOMPLETE_DIR is set to /data/incomplete,
Overriding rpc-port because TRANSMISSION_RPC_PORT is set to 9091,
Overriding watch-dir because TRANSMISSION_WATCH_DIR is set to /data/watch,
sed'ing True to true,
,
-------------------------------------,
Transmission will run as,
-------------------------------------,
User name:   root,
User uid:    0,
User gid:    0,
-------------------------------------,
,
STARTING TRANSMISSION,
Provider PIA has a script for automatic port forwarding. Will run it now.,
If you want to disable this, set environment variable DISABLE_PORT_UPDATER=yes,
Transmission startup script complete.,
Thu Nov  5 15:49:16 2020 Initialization Sequence Completed,
,
,
,
yes: Broken pipe,
curl: (7) Failed to connect to 10.47.112.1 port 19999: Connection refused,
Thu Nov  5 15:49:22 CST 2020: getSignature error,
,
the has been a fatal_error,
date: invalid date '',
port is ,
curl: (7) Failed to connect to 10.47.112.1 port 19999: Connection refused,
Thu Nov  5 15:49:22 CST 2020: bindPort error,
,
the has been a fatal_error,
transmission auth not required,
waiting for transmission to become responsive,
transmission became responsive,
    ID   Done       Have  ETA           Up    Down  Ratio  Status       Name,
Sum:                None               0.0     0.0,
setting transmission port to ,
localhost:9091/transmission/rpc/ responded: "success",
Checking port...,
Error: portTested: http error 400: Bad Request,
,
initial setup complete!,
,
waiting for rebind loop.................,
token expiry ,
remaining = -1604612974,
Thu Nov  5 15:49:34 CST 2020: Getting PF token,
curl: (7) Failed to connect to 10.47.112.1 port 19999: Connection refused,
Thu Nov  5 15:49:34 CST 2020: getSignature error,
,
the has been a fatal_error,
date: invalid date '',
Thu Nov  5 15:49:34 CST 2020: Obtained PF token. Expires at ,
curl: (7) Failed to connect to 10.47.112.1 port 19999: Connection refused,
Thu Nov  5 15:49:35 CST 2020: bindPort error,
,
the has been a fatal_error,
Thu Nov  5 15:49:35 CST 2020: Server accepted PF bind,
Thu Nov  5 15:49:35 CST 2020: Forwarding on port ,
Thu Nov  5 15:49:35 CST 2020: Rebind interval: 1800 seconds,
```

**Host system:**
Ubuntu 18.04, `:latest`

**Comment by chrishilbert** [comment]
Also getting this error.  Been pulling my hair out trying to figure it out.

**Comment by chrishilbert** [comment]
Added Google DNS to resolve it!

**Comment by bmanturner** [comment]
How?

**Comment by chrishilbert** [comment]
I’m on mobile now, look in this container tips and tricks documentation.  It’s a —dns IP address parameter.  Used the Google DNS setting right from the guide.

**Comment by bmanturner** [comment]
Must be unrelated; this didn't work for me.

**Comment by StellaTerra** [comment]
Same problem, also not resolved by `--dns`.

**Comment by StellaTerra** [comment]
Given the timing, I had a thought it might be related to this: https://github.com/haugene/docker-transmission-openvpn/commit/14ec8d4fb8e27925306005f61eb7aafe1887dd10 but not sure how.

**Comment by StellaTerra** [comment]
Something else I've noticed, I switched back from PIA to Nord, which doesn't have port forwarding, and I was able to connect to the trackers again.  But when I use the transmission "test port" feature (again, I'm aware Nord doesn't support it) it hangs and never responds, same as the behavior on PIA.  I think something is wrong with the way the container is setting up the networking, and that the port management is broken.

It's also worth mentioning that my `/etc/resolve.conf` never changes from this, even if I set a DNS in the docker-compose file:
```
nameserver 127.0.0.11
options ndots:0
```
and that I can always ping out to google from within the container, even when the port test hangs.
Also, it seems like the problems with pia started just after tag 2.14.  On 2.14 I can connect, but the port is closed.
This is all complicated by the fact that PIA gets cranky when you try to connect to the same server too often too quickly, and stop authing me… makes it hard to tweak the config and test it.

**Comment by bmanturner** [comment]
Someone recommended changing my password. I did so and received the same error.

**Comment by curtcoulter** [comment]
This is fairly widespread, seems to be related to PIA's next gen servers etc.  See all those curl errors, 'bad request', no port assigned, etc.  

Interestingly, based on other reports of PIA problems in other issues, some folks are having luck with European servers.  I get ports etc assigned and it looks like it's properly up, but still no trackers

**Comment by Toasterme** [comment]
already got the dns and it is not resolving the problem.

**Comment by dwclarknu** [comment]
Not ideal, but I was able to get it working by using the Israel PIA servers...i'll take slightly slower downloads over no downloads

**Comment by rbrussell82** [comment]
I'm noticing the same thing with ProtonVPN in Iceland.  I can ping google.com from the console just fine though.

**Comment by curtcoulter** [comment]
Israel PIA servers didn't behave any differently for me.  I also set up a custom provider per this other thread using the new nextgen PIA ovpn files, same behavior Sweden/US Chicago etc - all trackers are Scrape error:  Connection failed

**Comment by haugene** [comment]
Hey guys. We've had some issues with stability lately. Please test with port-forwarding and health checks disabled. If that runs and is stable then you can try to activate them one by one and see when instability arises. Disable port forwarding by adding the environment variable:
```
DISABLE_PORT_UPDATER=yes
```
To disable health checks add `--no-healthcheck` to your [Docker run](https://docs.docker.com/engine/reference/run/#healthcheck) command or [in docker-compose](https://docs.docker.com/compose/compose-file/#healthcheck):
```
healthcheck:
  disable: true
```

**Comment by rbrussell82** [comment]
> Hey guys. We've had some issues with stability lately. Please test with port-forwarding and health checks disabled. If that runs and is stable then you can try to activate them one by one and see when instability arises. Disable port forwarding by adding the environment variable:
> 
> ```
> DISABLE_PORT_UPDATER=yes
> ```
> 
> To disable health checks add `--no-healthcheck` to your [Docker run](https://docs.docker.com/engine/reference/run/#healthcheck) command or [in docker-compose](https://docs.docker.com/compose/compose-file/#healthcheck):
> 
> ```
> healthcheck:
>   disable: true
> ```

It didn't seem to make a difference in my case.  Here's my Compose:

```
  transmission-vpn:
    container_name: transmission-vpn
    image: haugene/transmission-openvpn
    cap_add:
      - NET_ADMIN
    restart: always
    ports:
    - "9091:9091"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    healthcheck:
      disable: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/docker/transmission-vpn:/data
      - ${USERDIR}/docker/shared:/shared
      - /media/plexdrive/Downloads/transmission:/data/watch
      - /media/plexdrive/Downloads/Completed:/data/completed
      - /media/plexdrive/Downloads/transmission/Incomplete:/data/incomplete
      - ${USERDIR}/docker/is-04.protonvpn.com.tcp.ovpn:/etc/openvpn/custom/default.ovpn
    environment:
      - OPENVPN_PROVIDER=CUSTOM
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60 --mute-replay-warnings
      - LOCAL_NETWORK=192.168.1.0/24
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DISABLE_PORT_UPDATER=yes
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      - TRANSMISSION_RPC_HOST_WHITELIST="127.0.0.1,192.168.*.*"
      - TRANSMISSION_PEER_PORT=****
      - TRANSMISSION_RPC_PASSWORD=****
      - TRANSMISSION_RPC_USERNAME=****
      - TRANSMISSION_PORT_FORWARDING_ENABLED=false
      - TRANSMISSION_UTP_ENABLED=false
      - TRANSMISSION_UMASK=002
      - TRANSMISSION_RATIO_LIMIT=5.00
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
      - TRANSMISSION_IDLE_SEEDING_LIMIT=7200
      - TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED=true

```

```
Here's the Transmission log files related to an Ubuntu ISO:
[2020-11-08 08:53:30.460] Loaded 1 torrents (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/session.c:2170)
[2020-11-08 08:53:30.460] web will verify tracker certs using envvar CURL_CA_BUNDLE: none (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/web.c:455)
[2020-11-08 08:53:30.460] web NB: this only works if you built against libcurl with openssl or gnutls, NOT nss (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/web.c:457)
[2020-11-08 08:53:30.460] web NB: invalid certs will show up as 'Could not connect to tracker' like many other errors (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/web.c:458)
[2020-11-08 08:53:31.461] ubuntu-20.10-desktop-amd64.iso Could not connect to tracker (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/announcer.c:1085)
[2020-11-08 08:53:31.461] ubuntu-20.10-desktop-amd64.iso Retrying announce in 20 seconds. (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/announcer.c:1094)
```
