### ISSUE TITLE
Port update scripts fails when changing RPC url or port

### ISSUE THREAD

**Issue by Weshnaw** [haugene/docker-transmission-openvpn#1474]
I found that when a custom TRANSMISSION_RPC_URL is used then the script to set the port from a vpn provider fails and the log gets filled with: 
`transmission_app         | Unexpected response: <h1>404: Not Found</h1>/transmission/rpc/`

docker-compose:
```
...
 transmission-app:
    image: haugene/transmission-openvpn
    container_name: transmission_app
    ports:
      - 8118:8118
      - 8080:8080
    environment:
      - PUID=1000
      - PGID=1003
      - CREATE_TUN_DEVICE=true
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_CONFIG=CA Toronto
      - OPENVPN_USERNAME=pXXXXXXX
      - OPENVPN_PASSWORD=PASSWORD
      - WEBPROXY_ENABLED=true
      - WEBPROXY_PORT=8118
      - WEBPROXY_USERNAME=USER
      - "WEBPROXY_PASSWORD=PASSWORD"
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      - TRANSMISSION_RPC_USERNAME=USER
      - "TRANSMISSION_RPC_PASSWORD=PASSWORD"
      - "TRANSMISSION_RPC_URL=/"
      - LOCAL_NETWORK=10.0.0.0/16
    volumes:
      - './transmission/data/:/data'
      - '/etc/localtime:/etc/localtime:ro'
    cap_add:
      - NET_ADMIN
    logging:
      driver: json-file
      options:
          max-size: 10m
    restart: always
...
```

logs:
```
STARTING TRANSMISSION
transmission_app         | Provider PIA has a script for automatic port forwarding. Will run it now.
transmission_app         | If you want to disable this, set environment variable DISABLE_PORT_UPDATER=yes
transmission_app         | Transmission startup script complete.
transmission_app         | STARTING TINYPROXY
transmission_app         | Found config file /etc/tinyproxy/tinyproxy.conf, updating settings.
transmission_app         | Setting tinyproxy port to 8118
transmission_app         | Setting tinyproxy basic auth
transmission_app         | tinyproxy is on the PATH, run it
transmission_app         | WARNING: logging deactivated (can't log to stdout when daemonized)
transmission_app         | Tinyproxy startup script complete.
transmission_app         | Fri Nov  6 17:17:46 2020 WARNING: OpenVPN was configured to add an IPv6 route over tun0. However, no IPv6 has been configured for this interface, therefore the route installation may fail or may not work as expected.
transmission_app         | Fri Nov  6 17:17:46 2020 Initialization Sequence Completed
transmission_app         |
transmission_app         |
transmission_app         |
transmission_app         | yes: Broken pipe
transmission_app         | port is 23794
transmission_app         | the port has been bound to 23794  Fri Nov  6 17:17:52 UTC 2020
transmission_app         | transmission auth required
transmission_app         | waiting for transmission to become responsive
transmission_app         | Unexpected response: <h1>404: Not Found</h1>/transmission/rpc/
transmission_app         | Unexpected response: <h1>404: Not Found</h1>/transmission/rpc/
transmission_app         | Unexpected response: <h1>404: Not Found</h1>/transmission/rpc/
...
```
