### ISSUE TITLE
Tinyproxy not connecting

### ISSUE THREAD

**Issue by mouzzampk2014** [haugene/docker-transmission-openvpn#1477]
Hi, definitely its me. I am using this image `haugene/transmission-openvpn:dev-armhf` and I have these environment variables 
```
- WEBPROXY_ENABLED=true
- WEBPROXY_PORT=8888
```
Thats the output after I start the container 
```
today at 18:10 STARTING TRANSMISSION
today at 18:10 Transmission startup script complete.
today at 18:10 STARTING TINYPROXY
today at 18:10 Found config file /etc/tinyproxy/tinyproxy.conf, updating settings.
today at 18:10 Setting tinyproxy port to 8888
today at 18:10 tinyproxy is on the PATH, run it
today at 18:10 Tinyproxy startup script complete.
```
But its not connecting me to any website when I enter the tinyproxy details in my Microsoft Edge or any other browser. I entered this information `192.168.1.89:8888`

![image](https://user-images.githubusercontent.com/44548525/98451180-4509f680-213b-11eb-89c6-fd15b43c55c9.png)

Could you look into this? Thank you so much

**Comment by haugene** [comment]
Install telnet on a computer (not the one where the container is running) and run `telnet 192.168.1.89 8888` what happens then?

Can you share the rest of your config setup? Just those variables are not the only things that are relevant here. Have you set the LOCAL_NETWORK variable?

**Comment by mouzzampk2014** [comment]
Hi thats what happen when I type `telnet 192.168.1.89 8888`

![image](https://user-images.githubusercontent.com/44548525/98464299-d455ef00-21b9-11eb-8e3a-7084f513e2db.png)

And here is my full compose
```
transmissionvpn:
  image: haugene/transmission-openvpn:dev-armhf
  hostname: ${DOCKERHOSTNAME}
  ports:
    - 51413:51413
    - 51413:51413/udp
    - 6881:6881
    - 6881:6881/udp
    - 9091:9091
    - 8888:8888
  cap_add:
    - NET_ADMIN
  container_name: transmissionvpn
  dns:
    - ${NS1}
    - ${NS2}
  environment:
    - LOCAL_NETWORK=192.168.1.0/24
    - TRANSMISSION_WEB_UI=combustion
    - OPENVPN_OPTS=
    - OPENVPN_PASSWORD=password
    - OPENVPN_PROVIDER=custom
    - OPENVPN_USERNAME=username
    - PGID=1000
    - PUID=1000
    - WEBPROXY_ENABLED=true
    - WEBPROXY_PORT=8888
    - TRANSMISSION_DOWNLOAD_DIR=/storage/downloads
    - TRANSMISSION_HOME=/config
    - TRANSMISSION_INCOMPLETE_DIR=/storage/downloads
    - TRANSMISSION_WATCH_DIR=/storage/downloads
    - TZ=${TZ}
  logging:
    driver: json-file
    options:
      max-file: ${DOCKERLOGGING_MAXFILE}
      max-size: ${DOCKERLOGGING_MAXSIZE}
  restart: unless-stopped
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - ${DOCKERCONFDIR}/transmissionvpn:/config
    - ${DOCKERSTORAGEDIR}:/storage
    - ${VPN_OVPNDIR}:/config/openvpn
    - ${VPN_OVPNDIR}:/etc/openvpn/custom/
```
Thank you so much
