### ISSUE TITLE
Unable to access WEBUI error: 404: Not Found

### ISSUE THREAD

**Issue by jpdsceu** [haugene/docker-transmission-openvpn#1481]
Not sure since which version it started happening but I'm getting (must of been within the last 2 weeks).

```
Couldn't find Transmission's web interface files!

Users: to tell Transmission where to look, set the TRANSMISSION_WEB_HOME environment variable to the folder where the web interface's index.html is located.

Package Builders: to set a custom default at compile time, #define PACKAGE_DATA_DIR in libtransmission/platform.c or tweak tr_getClutchDir() by hand.
```

Went from latest to dev but the issue still presists.
Any idea?

Below the setting in the docker-compose.yml
`            - TRANSMISSION_WEB_HOME=`

**Comment by haugene** [comment]
Remove that environment variable. As long as it is set Transmission will look there to load the UI. If you drop it, it will use the default.

**Comment by jpdsceu** [comment]
I tried that and it didn't solve it.
Below the docker-compose.yml

```
# Transmission-VPN
    transmission-openvpn:
        container_name: Transmission-VPN
        cap_add:
            - NET_ADMIN
        environment:
            - OPENVPN_USERNAME=xxx
            - 'OPENVPN_PASSWORD=xxx
            - OPENVPN_PROVIDER=TORGUARD
            - GLOBAL_APPLY_PERMISSIONS=false
            - TRANSMISSION_ALT_SPEED_DOWN=50
            - TRANSMISSION_ALT_SPEED_ENABLED=false
            - TRANSMISSION_ALT_SPEED_TIME_BEGIN=540
            - TRANSMISSION_ALT_SPEED_TIME_DAY=127
            - TRANSMISSION_ALT_SPEED_TIME_ENABLED=false
            - TRANSMISSION_ALT_SPEED_TIME_END=1020
            - TRANSMISSION_ALT_SPEED_UP=50
            - TRANSMISSION_BIND_ADDRESS_IPV4=0.0.0.0
            - 'TRANSMISSION_BIND_ADDRESS_IPV6=::'
            - TRANSMISSION_BLOCKLIST_ENABLED=false
            - 'TRANSMISSION_BLOCKLIST_URL=http://www.example.com/blocklist'
            - TRANSMISSION_CACHE_SIZE_MB=4
            - TRANSMISSION_DHT_ENABLED=true
            - TRANSMISSION_DOWNLOAD_DIR=/shared/Downloads/Unsorted
            - TRANSMISSION_DOWNLOAD_LIMIT=100
            - TRANSMISSION_DOWNLOAD_LIMIT_ENABLED=0
            - TRANSMISSION_DOWNLOAD_QUEUE_ENABLED=true
            - TRANSMISSION_DOWNLOAD_QUEUE_SIZE=5
            - TRANSMISSION_ENCRYPTION=1
            - TRANSMISSION_IDLE_SEEDING_LIMIT=0
            - TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED=true
            - TRANSMISSION_INCOMPLETE_DIR=/shared/Downloading
            - TRANSMISSION_INCOMPLETE_DIR_ENABLED=true
            - TRANSMISSION_LPD_ENABLED=true
            - TRANSMISSION_MAX_PEERS_GLOBAL=200
            - TRANSMISSION_MESSAGE_LEVEL=2
            - TRANSMISSION_PEER_CONGESTION_ALGORITHM=
            - TRANSMISSION_PEER_ID_TTL_HOURS=6
            - TRANSMISSION_PEER_LIMIT_GLOBAL=500
            - TRANSMISSION_PEER_LIMIT_PER_TORRENT=100
            - TRANSMISSION_PEER_PORT=51413
            - TRANSMISSION_PEER_PORT_RANDOM_HIGH=65535
            - TRANSMISSION_PEER_PORT_RANDOM_LOW=49152
            - TRANSMISSION_PEER_PORT_RANDOM_ON_START=false
            - TRANSMISSION_PEER_SOCKET_TOS=default
            - TRANSMISSION_PEX_ENABLED=true
            - TRANSMISSION_PORT_FORWARDING_ENABLED=false
            - TRANSMISSION_PREALLOCATION=1
            - TRANSMISSION_PREFETCH_ENABLED=1
            - TRANSMISSION_QUEUE_STALLED_ENABLED=true
            - TRANSMISSION_QUEUE_STALLED_MINUTES=30
            - TRANSMISSION_RATIO_LIMIT=0
            - TRANSMISSION_RATIO_LIMIT_ENABLED=false
            - TRANSMISSION_RENAME_PARTIAL_FILES=true
            - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
            - TRANSMISSION_RPC_BIND_ADDRESS=0.0.0.0
            - TRANSMISSION_RPC_ENABLED=true
            - TRANSMISSION_RPC_HOST_WHITELIST=
            - TRANSMISSION_RPC_HOST_WHITELIST_ENABLED=false
            - 'TRANSMISSION_RPC_PASSWORD=xxx
            - TRANSMISSION_RPC_PORT=9091
            - TRANSMISSION_RPC_URL=/transmission/
            - TRANSMISSION_RPC_USERNAME=xxx
            - TRANSMISSION_RPC_WHITELIST=127.0.0.1
            - TRANSMISSION_RPC_WHITELIST_ENABLED=false
            - TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=true
            - TRANSMISSION_SCRIPT_TORRENT_DONE_ENABLED=false
            - TRANSMISSION_SCRIPT_TORRENT_DONE_FILENAME=
            - TRANSMISSION_SEED_QUEUE_ENABLED=false
            - TRANSMISSION_SEED_QUEUE_SIZE=10
            - TRANSMISSION_SPEED_LIMIT_DOWN=100
            - TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED=false
            - TRANSMISSION_SPEED_LIMIT_UP=100
            - TRANSMISSION_SPEED_LIMIT_UP_ENABLED=false
            - TRANSMISSION_START_ADDED_TORRENTS=true
            - TRANSMISSION_TRASH_ORIGINAL_TORRENT_FILES=false
            - TRANSMISSION_UMASK=2
            - TRANSMISSION_UPLOAD_LIMIT=100
            - TRANSMISSION_UPLOAD_LIMIT_ENABLED=0
            - TRANSMISSION_UPLOAD_SLOTS_PER_TORRENT=14
            - TRANSMISSION_UTP_ENABLED=false
            - TRANSMISSION_WATCH_DIR=/data/watch
            - TRANSMISSION_WATCH_DIR_ENABLED=true
            - TRANSMISSION_HOME=/data/transmission-home
            - TRANSMISSION_WATCH_DIR_FORCE_GENERIC=false
            - ENABLE_UFW=false
            - UFW_ALLOW_GW_NET=false
            - UFW_EXTRA_PORTS=
            - UFW_DISABLE_IPTABLES_REJECT=false
            - TRANSMISSION_WEB_UI=
            - PUID=1026
            - PGID=101
            #- TRANSMISSION_WEB_HOME=
            - DROP_DEFAULT_ROUTE=
            - WEBPROXY_ENABLED=false
            - WEBPROXY_PORT=8888
            - HEALTH_CHECK_HOST=google.com
            - DOCKER_LOG=false
            - CREATE_TUN_DEVICE=true
            - OPENVPN_CONFIG=Netherlands
            - LOCAL_NETWORK=10.0.0.0/24
        volumes:
            - '/volume2/docker/Transmission-VPN/config:/config:rw'
            - '/volume2/docker/Transmission-VPN/data:/data:rw'
            - '/volume1/Shared/:/shared:rw'
            - '/etc/localtime:/etc/localtime:ro'
        networks:
            private:
                ipv4_address: 10.2.0.4
        hostname: NAS
        expose:
            - '8888'
        ports:
            - '51414:51413'
            - '51414:51413/udp'
            - '9092:9091'
        restart: unless-stopped
        image: 'haugene/transmission-openvpn:latest'
```

**Comment by haugene** [comment]
That's a massive compose file. Are you setting all of these variables because you actually want to override them? A lot of them are set to defaults anyways... It also contains some syntax errors, but I guess that's from you masking your credentials. Nevertheless, can you try running this compose file? Note that I don't mount any of your volumes, so it will not change anything on your host.

```
version: '3.3'
services:
  # Transmission-VPN
  transmission-openvpn:
      container_name: Transmission-VPN
      cap_add:
          - NET_ADMIN
      environment:
          - OPENVPN_USERNAME=xxx
          - OPENVPN_PASSWORD=xxx
          - OPENVPN_PROVIDER=TORGUARD
          - PUID=1026
          - PGID=101
          - OPENVPN_CONFIG=Netherlands
          - LOCAL_NETWORK=10.0.0.0/24
      networks:
          private:
              ipv4_address: 10.2.0.4
      hostname: NAS
      expose:
          - '8888'
      ports:
          - 51414:51413
          - 51414:51413/udp
          - 9092:9091
      restart: unless-stopped
      image: haugene/transmission-openvpn:latest
```

If that works then try adding the volume mounts again, and these settings that I see you have actually overridden:
```
          - TRANSMISSION_DOWNLOAD_DIR=/shared/Downloads/Unsorted
          - TRANSMISSION_INCOMPLETE_DIR=/shared/Downloading
          - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
          - TRANSMISSION_RPC_PASSWORD=xxx
          - TRANSMISSION_RPC_USERNAME=xxx
```

If none of this works for some reason I think you need to share some logs. Without it it's hard to know anything about what's going on.
