### ISSUE TITLE
Docker image tags for arm are labelled as amd64

### ISSUE THREAD

**Issue by rdfedor** [haugene/docker-transmission-openvpn#1483]
I'd love to use this on a new build that's arm64 based but all your labeling for your builds say amd64 which won't work on my system.

https://hub.docker.com/r/haugene/transmission-openvpn/tags

**Comment by haugene** [comment]
The labels are wrong. They're built using the cross-build function on CircleCI. I guess it just defaults to amd64.
Could have a look at what I have to do to label them correctly.

Have you tried running them? You'll quickly see from the logs if there are any format errors:
```
docker run --rm -it haugene/transmission-openvpn:latest-armhf
docker run --rm -it haugene/transmission-openvpn:latest-arm64
```

**Comment by haugene** [comment]
FYI. Started looking into buildx and multi-architecture builds now. Looking very interesting. If I get something going, will you be able to test a bit? I don't have an ARM system myself.

**Comment by haugene** [comment]
I've created #1487 that sets up new builds creating multi architecture manifests in Docker Hub. Can you test it by running the `haugene/transmission-openvpn:multiarch` tag and see what results you get?
PS: When this is merged I will delete the multiarch tag and go back to dev/latest and version tags.

**Comment by jscanzoni** [comment]
I'm seeing the same thing happen for haugene/transmission-rss

**Comment by JB09** [comment]
using "lastest" tag on a RPi4 and image 93d0141 loaded properly, fyi

**Comment by haugene** [comment]
The rss image is not converted to a multiarch build yet. The latest-armhf is an arm build but it's tagged as amd64

**Comment by haugene** [comment]
@jscanzoni I'll keep this issue open and hope to get back to it soon.

**Comment by rdfedor** [comment]
Sorry I missed all  the great comments.  Glad to see the community is active here :) For my purposes to give a little bit more detail is i'm deploying this to a 4 unit docker swarm cluster based on Raspberry OS 64bit managing w/ Portainer.   The main blocker is when trying to deploy a swarm referencing the arm based builds, it comes back saying there's no compatible nodes because they labeled as amd64 and not arm unfortunately.  Great work on the project though, look forward to using it once the labels are fixed.

**Comment by rdfedor** [comment]
Actually just noticed you have the tags fixed so woot! Will have to try it out :)  Thanks.

**Comment by haugene** [comment]
Let me know how it goes :+1: And yes. Planning to give the rss some love as well. Not sure when I'll get around to it though.
There has been a lot of fixup going on after going to the 3.0 release. But collecting everything to the same base image etc also make it easier to see a path for fixes such as this.

So ping if you feel time is running out. If not I guess the stale bot will nudge this in 2 months.

**Comment by haugene** [comment]
Looks like this went better than expected on the first try. Both transmission-rss plugin and the reverse proxy for this container is not built as multiarch. It's only pushed to the `:dev` tag for now. Are you up for testing it @rdfedor and @jscanzoni?

I have simplified the transmission-rss container a bit, dropping Dockerize and using pure `sed` instead. Since dockerize is installed by downloading binaries with curl I would have to figure out the architecture at build time and get the right one. So I'm trying to skip that for now. I added support for mounting your own config though so it should be more extensible now.

Let me know how it goes :crossed_fingers:

**Comment by samwaugh** [comment]
Hey. I'm trying to set up a Raspberry Pi 3 with transmission-openvpn and transmission-rss. Got the transmission-openvpn running using the docker-compose script (the only difficulty was finding the OPENVPN_CONFIG names for PIA in my area, so maybe a link in the documentation?).

I'm trying to get the rss container running now with the dev branch as indicated above. Based on documentation at https://docs.docker.com/network/links/ , I assume <transmission-container> is meant to be the container ID or container name? Running this:

```
docker run -d -e "RSS_URL=<URL>" --link <container ID>:transmission --name "transmission-rss" haugene/transmission-rss:dev
```
I'm getting the following error:
```
docker: Error response from daemon: Cannot link to /haugene_transmission-openvpn_1, as it does not belong to the default network.
```
Any thoughts on what I'm doing wrong? (I am a noob...)

**Comment by samwaugh** [comment]
So I've got things running using the following docker-compose.yml and docker-compose up -d:
```
version: '3.3'
services:
    transmission-openvpn:
        cap_add:
            - NET_ADMIN
        volumes:
            - '/home/pi/:/data'
        environment:
            - OPENVPN_PROVIDER=PIA
            - OPENVPN_CONFIG=au_melbourne,au_sydney,au_perth
            - OPENVPN_USERNAME=<USERNAME>
            - OPENVPN_PASSWORD=<PASSWORD>
            - LOCAL_NETWORK=192.168.0.0/16
            - TZ=Australia/Melbourne
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '9091:9091'
        image: haugene/transmission-openvpn
        container_name: transmission-openvpn
    transmission-rss:
        image: haugene/transmission-rss:dev
        container_name: transmission-rss
        depends_on:
            - transmission-openvpn
        restart: always
        environment:
            - RSS_URL=<URL>
```
The containers started, but I'm not sure this is working yet...
