### ISSUE TITLE
Custom ovpn file stopped working after update.

### ISSUE THREAD

**Issue by SyRaza** [haugene/docker-transmission-openvpn#1527]
I was running Transmission-VPN perfectly and decided to update the image. After the update, the ovpn stopped working. 

Here is my docker-compose
```

# TransmissionBT - Torrent Downloader
  # ONLY ACCESSIBLE THROUGH https://domain.com/transmission/web/ if using PathPrefix
  transmission-vpn:
    image: haugene/transmission-openvpn:latest
    container_name: transmission-vpn
    restart: always
    networks:
      # - t2_proxy
      t2_proxy:
        ipv4_address: 192.168.80.90
    cap_add:
      - NET_ADMIN
    restart: always
    ports:
      - "9092:9091"
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $DOCKERDIR/transmission-vpn/data:/data
      - $DOCKERDIR/transmission-vpn/config:/config
      - $DOCKERDIR/transmission-vpn/config/my_expressvpn_canada_-_toronto_udp.ovpn:/etc/openvpn/custom/default.ovpn
      - /mnt/storage/downloads/:/storage/downloads/
    environment:
      OPENVPN_PROVIDER: CUSTOM
      OPENVPN_USERNAME: $EXPRESS_USERNAME
      OPENVPN_PASSWORD: $EXPRESS_PASSWORD
      OPENVPN_CONFIG: "my_expressvpn_canada_-_toronto_udp"
      OPENVPN_OPTS: --inactive 3600 --ping 10 --ping-exit 60
      LOCAL_NETWORK: "$LOCAL_NETWORK"
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      UMASK_SET: 2
      TRANSMISSION_RPC_AUTHENTICATION_REQUIRED: "true"
      TRANSMISSION_RPC_HOST_WHITELIST: "127.0.0.1,192.168.2.20"
      TRANSMISSION_RPC_PASSWORD: $TRANSMISSION_RPC_PASSWORD
      TRANSMISSION_RPC_USERNAME: $TRANSMISSION_RPC_USERNAME
      TRANSMISSION_UMASK: 002
      TRANSMISSION_RATIO_LIMIT: 0.01
      TRANSMISSION_RATIO_LIMIT_ENABLED: "true"
      TRANSMISSION_ALT_SPEED_DOWN: 8000
      TRANSMISSION_ALT_SPEED_ENABLED: "true"
      TRANSMISSION_ALT_SPEED_UP: 15
      TRANSMISSION_SPEED_LIMIT_DOWN: 6000
      TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED: "true"
      TRANSMISSION_SPEED_LIMIT_UP: 30
      TRANSMISSION_SPEED_LIMIT_UP_ENABLED: "true"
      TRANSMISSION_INCOMPLETE_DIR: /storage/downloads/incomplete
      TRANSMISSION_INCOMPLETE_DIR_ENABLED: "true"
      TRANSMISSION_WATCH_DIR: /storage/downloads
      TRANSMISSION_WATCH_DIR_ENABLED: "true"
      TRANSMISSION_DOWNLOAD_DIR: /storage/downloads/completed
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.transmission-vpn-rtr.entrypoints=https"
      - "traefik.http.routers.transmission-vpn-rtr.rule=HostHeader(`trans.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.transmission-vpn-rtr.middlewares=middlewares-rate-limit@file"
      ## HTTP Services
      - "traefik.http.routers.transmission-vpn-rtr.service=transmission-vpn-svc"
      - "traefik.http.services.transmission-vpn-svc.loadbalancer.server.port=9091"
```
This is the error that I'm getting

```
2020-11-17T21:40:48.166723813Z Starting container with revision: 3d97cd5302985c1a710f46ab0c311f721f224fc6
2020-11-17T21:40:48.170670620Z Using OpenVPN provider: CUSTOM
2020-11-17T21:40:48.171499728Z Supplied config my_expressvpn_canada_-_toronto_udp.ovpn could not be found.
2020-11-17T21:40:48.171519532Z Your options for this provider are:
2020-11-17T21:40:48.172436586Z default.ovpn
2020-11-17T21:40:48.172608699Z NB: Remember to not specify .ovpn as part of the config name.
```

I've taken out the CREATE_TUN_DEVICE variable as it's now true by default. Not sure what I'm missing/doing wrong.
