### ISSUE TITLE
Does not start

### ISSUE THREAD

**Issue by clement-z** [haugene/docker-transmission-openvpn#1529]
**The issue is solved already on my end, but I am writing this up for future reference.**

#### Describe the problem

The container fails to start, giving the following error in the log:

``` 
/etc/openvpn/start.sh: line 222: /usr/sbin/openvpn: No error information
```

#### Add your docker run command

I ran a minimal container setup:

```yaml
version: '3'

services:
  transmission-openvpn:
    image: haugene/transmission-openvpn:latest
    environment:
      - OPENVPN_PROVIDER=${VPN_PROVIDER}
      - PIA_OPENVPN_CONFIG_BUNDLE=${PIA_CONFIG_BUNDLE}
      - OPENVPN_CONFIG=${VPN_CONFIG}
      - OPENVPN_USERNAME=${VPN_USERNAME}
      - OPENVPN_PASSWORD=${VPN_PASSWORD}
    cap_add:
      - NET_ADMIN
    dns:
      - 1.1.1.1
      - 1.0.0.1
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - 19091:9091
    restart: 'no'
```

#### Logs

```
...
Setting OpenVPN credentials...
enabling firewall
allowing 172.19.0.1 through the firewall to port 9091
adding route to local network 127.0.0.1/32 via 172.19.0.1 dev eth0
allowing 127.0.0.1/32 through the firewall to port 9091
/etc/openvpn/start.sh: line 222: /usr/sbin/openvpn: No error information
```
