### ISSUE TITLE
RTNETLINK answers: Operation not permitted / Cannot ioctl TUNSETIFF tun

### ISSUE THREAD

**Issue by Sulter** [haugene/docker-transmission-openvpn#1541]
**Describe the problem**
The stack doesn't start due to the error in the title.
Please note that I already have the pi-hole in docker in swarm mode as well [link](https://hub.docker.com/r/pihole/pihole), and that works just fine with the cap_add: net_admin. That's why I'm suspecting a possible bug with docker-transmission-openvpn, but this might also be a configuration error.

**Add your docker run command**

```
version: '3.3'
services:
    transmission-openvpn:
        volumes:
            - '/srv/dev-disk-by-label-mediaDisk/Film:/data'
        environment:
            - OPENVPN_PROVIDER=GHOSTPATH
            - OPENVPN_CONFIG=Germany-Frankfurt
            - OPENVPN_USERNAME=XXXXXXXX
            - OPENVPN_PASSWORD=YYYYYYYY
            - WEBPROXY_ENABLED=false
            - LOCAL_NETWORK=192.168.1.0/24
        cap_add:
            - NET_ADMIN
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '9091:9091'
        image: haugene/transmission-openvpn
```

**Logs**
```
Starting container with revision: baed33520630e88ba34842cab05f2cd3fd6cf28f,
Creating TUN device /dev/net/tun,
Using OpenVPN provider: GHOSTPATH,
Starting OpenVPN using config Germany-Frankfurt.ovpn,
Setting OpenVPN credentials...,
adding route to local network 192.168.1.0/24 via 172.18.0.1 dev eth2,
RTNETLINK answers: Operation not permitted,
Sun Nov 22 07:09:52 2020 OpenVPN 2.4.9 armv7-alpine-linux-musleabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Apr 20 2020,
Sun Nov 22 07:09:52 2020 library versions: OpenSSL 1.1.1g  21 Apr 2020, LZO 2.10,
Sun Nov 22 07:09:52 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts,
Sun Nov 22 07:09:52 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]139.162.159.184:443,
Sun Nov 22 07:09:52 2020 UDP link local: (not bound),
Sun Nov 22 07:09:52 2020 UDP link remote: [AF_INET]139.162.159.184:443,
Sun Nov 22 07:09:52 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this,
Sun Nov 22 07:09:52 2020 [VPN] Peer Connection Initiated with [AF_INET]139.162.159.184:443,
Sun Nov 22 07:09:53 2020 ERROR: Cannot ioctl TUNSETIFF tun: Operation not permitted (errno=1),
Sun Nov 22 07:09:53 2020 Exiting due to fatal error,
```

**Host system:**
odroidxu4, Armbian 20.08.17 Buster with Linux 5.4.72-odroidxu4
Docker version 19.03.13, build 4484c46

**Comment by clement-z** [comment]
Note that you also have an error before the one you highlight.

```
[...]
adding route to local network 192.168.1.0/24 via 172.18.0.1 dev eth2,
RTNETLINK answers: Operation not permitted,
[...]
Sun Nov 22 07:09:53 2020 ERROR: Cannot ioctl TUNSETIFF tun: Operation not permitted (errno=1),
Sun Nov 22 07:09:53 2020 Exiting due to fatal error,
```

Running with `NET_ADMIN` should be enough to modify routes and configure interfaces.

Some ideas off the top of my head:

1. Can you make sure you recreated the container (`docker-compose up -d -force-recreate`).
2. If unsuccessful, can you try whether it works if you use `privileged: true`.
3. If privileged works but `NET_ADMIN` doesn't, can you add the following to your transmission-openvpn service
   
   ```yml
   entrypoint: dumb-init /bin/bash -i
   stdin_open: true
   tty: true
   ```
   
   then run and show the ouptut of:
   
   * `docker exec -it container_name bash -c 'apk add libcap; getpcaps 1'`
   * `docker exec -it container_name bash -c 'ip a; ip r'`
