### ISSUE TITLE
AEAD Decrypt error: bad packet ID v3

### ISSUE THREAD

**Issue by ajhorvath20** [haugene/docker-transmission-openvpn#1553]
Hi, 

Not stopping how transmission works and working perfectly fine. 

It just I am seeing a lot of these in the logs not sure if I need to change something on my side. Thanks
```
yesterday at 13:29  Tue Nov 24 13:29:20 2020 AEAD Decrypt error: bad packet ID (may be a replay): [ #257 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
yesterday at 13:29  Tue Nov 24 13:29:20 2020 AEAD Decrypt error: bad packet ID (may be a replay): [ #259 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
yesterday at 13:29  Tue Nov 24 13:29:20 2020 AEAD Decrypt error: bad packet ID (may be a replay): [ #260 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
yesterday at 13:29  Tue Nov 24 13:29:21 2020 AEAD Decrypt error: bad packet ID (may be a replay): [ #261 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
yesterday at 13:29  Tue Nov 24 13:29:21 2020 AEAD Decrypt error: bad packet ID (may be a replay): [ #262 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
yesterday at 13:29  Tue Nov 24 13:29:21 2020 AEAD Decrypt error: bad packet ID (may be a replay): [ #263 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
```

**Comment by haugene** [comment]
Are you on a wifi connection? That can generate a lot of these. If I remember correctly there was some discussion on how the mtu size could affect it as well.

Several providers use the mute flag as default. I think we will add that as well.

You can add it to you OPENVPN_OPTS env variable for now and it should be quiet. Someone could be trying to DOS you, but 99% sure this is just replay due to some perceived packet drop or timeout windows making the vpn server send the packets again.

**Comment by ajhorvath20** [comment]
Hi @haugene thank you so much for looking into this for me. I am on ethernet (no wifi). You know what I need to enter in `OPENVPN_OPTS=` because there is a massive list here? :)

![image](https://user-images.githubusercontent.com/65309559/100340984-e0bcb300-2fd3-11eb-96c8-3486f90ea40c.png)

Thank you

**Comment by haugene** [comment]
Oh yes. I see I could have been more explicit. It's the one from the logs: `--mute-replay-warnings`

**Comment by ajhorvath20** [comment]
Awe thank you 

This is my compose so that should be okay?
```
  transmissionvpn:
    image: haugene/transmission-openvpn:dev-armhf
    hostname: Mario
    ports:
      - 51413:51413
      - 51413:51413/udp
      - 6881:6881
      - 6881:6881/udp
      - 9091:9091
      - 8888:8888
    cap_add:
      - NET_ADMIN
    container_name: transmissionvpn
    dns:
      - 1.1.1.1
      - 8.8.8.8
    environment:
      - LOCAL_NETWORK=192.168.1.0/24
      - TRANSMISSION_WEB_UI=combustion
      - OPENVPN_PASSWORD=${VPN_PASS}
      - OPENVPN_PROVIDER=custom
      - OPENVPN_USERNAME=${VPN_USER}
      - OPENVPN_OPTS=--mute-replay-warnings
      - PGID=${PGID}
      - PUID=${PUID}
      - WEBPROXY_ENABLED=true
      - WEBPROXY_PORT=8888
      - TRANSMISSION_DOWNLOAD_DIR=/storage/downloads
      - TRANSMISSION_HOME=/config
      - TRANSMISSION_INCOMPLETE_DIR=/storage/downloads/incomplete
      - TRANSMISSION_WATCH_DIR=/storage/downloads/watch
      - TZ=${TZ}
    logging:
      driver: json-file
      options:
        max-file: 10
        max-size: 200k
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/transmissionvpn:/config
      - ${DOCKERSTORAGEDIR}:/storage
      - ${VPN_OVPNDIR}:/config/openvpn
      - ${VPN_OVPNDIR}:/etc/openvpn/custom/
```
