### ISSUE TITLE
curl: (6) Could not resolve host: www.privateinternetaccess.com

### ISSUE THREAD

**Issue by evanmiller29** [haugene/docker-transmission-openvpn#1564]
**Describe the problem**
On portainer / omv5 can't spin up docker image (using ethernet as internet connection).

Thanks for your help btw, this is an awesome piece of kit and I can't wait to get it working!
I followed the guide from here: https://www.youtube.com/watch?v=R0uracDLuWQ&t=347s&pbjreload=101

**Add your docker run command**
```version: 2
services:
    transmission-openvpn:
        volumes:
            - /srv/dev-disk-by-id-ata-Samsung_SSD_850_EVO_500GB_S2R9NX0J522124F-part1/Torrents:/data
        environment:
            - OPENVPN_PROVIDER=PIA
            - OPENVPN_CONFIG=Israel
            - OPENVPN_USERNAME=***********
            - OPENVPN_PASSWORD=***********
            - WEBPROXY_ENABLED=false
            - PIA_OPENVPN_CONFIG_BUNDLE=openvpn
            - LOCAL_NETWORK= 192.168.0.177/24
        cap_add:
            - NET_ADMIN
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - 9091:9091
        image: haugene/transmission-openvpn:latest-armhf
```

**Logs**
```
Starting container with revision: 3d97cd5302985c1a710f46ab0c311f721f224fc6


Using OpenVPN provider: PIA


Provider PIA has a custom startup script, executing it


Downloading OpenVPN config bundle openvpn into temporary file /tmp/tmp.UZcyoeVi8R


curl: (6) Could not resolve host: www.privateinternetaccess.com
```

**Host system:**
OMV5 with Portainer

**Comment by evanmiller29** [comment]
So I've managed to get it working, here's how I fixed it. Cheers for your help @jscoys

```
version: 2
services:
    transmission-openvpn:
        volumes:
            - /srv/dev-disk-by-id-ata-Samsung_SSD_850_EVO_500GB_S2R9NX0J522124F-part1/Torrents:/data
        environment:
            - OPENVPN_PROVIDER=PIA
            - OPENVPN_CONFIG=spain
            - OPENVPN_USERNAME=*********
            - OPENVPN_PASSWORD=*********
            - WEBPROXY_ENABLED=false
            - PIA_OPENVPN_CONFIG_BUNDLE=openvpn
            - LOCAL_NETWORK=192.168.0.0/24

        dns:
            - 8.8.8.8
        cap_add:
            - NET_ADMIN
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - 9091:9091
        image: haugene/transmission-openvpn:latest-armhf
```

My local network wasn't right before. I had to go through and use the tutorial [here](https://dbtechreviews.com/2020/04/how-to-install-transmission-with-vpn-on-omv/) to know what IP ranges to use for it.
