### ISSUE TITLE
FastestVPN provider not establishing connection correctly

### ISSUE THREAD

**Issue by PhillOliver-Dev** [haugene/docker-transmission-openvpn#1566]
Seemingly fastestvpn has ceased to function as a supported vpn provider. Seeing a failure to connect to UK provider which exists in the config folder 

`transmission    | Sat Nov 28 22:17:20 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]X.XXX.XXX.XXX:XXXX
transmission    | Sat Nov 28 22:17:20 2020 Attempting to establish TCP connection with [AF_INET]X.XXX.XXX.XXX:XXXX [nonblock]
transmission    | Sat Nov 28 22:19:20 2020 TCP: connect to [AF_INET]X.XXX.XXX.XXX:XXXX failed: Operation timed out`

Config hasn't changed,

```
version: "2"                                                
services:                                                   
  transmission:                                             
    image: haugene/transmission-openvpn                     
    container_name: transmission                            
    cap_add:                                                
      - NET_ADMIN                                           
    environment:                                            
      - LOCAL_NETWORK=192.168.2.0/24                        
      - OPENVPN_PROVIDER=FASTESTVPN                         
      - OPENVPN_USERNAME=USER 
      - OPENVPN_PASSWORD=PASS                      
      - OPENVPN_CONFIG=UK-TCP                               
      - WEBPROXY_ENABLED=false                              
      - CREATE_TUN_DEVICE=true                              
      - PUID=1000                                           
      - PGID=1000                                           
      - TZ=Europe/London                                    
    volumes:                                                
      - ./config:/config                                    
      - /mnt/data/share/torrents:/data                      
    ports:                                                  
      - 9091:9091                                           
      - 51413:51413                                         
      - 51413:51413/udp                                     
    restart: unless-stopped                                 
```
