### ISSUE TITLE
Seeding one file multiple times 

### ISSUE THREAD

**Issue by Hamm3rhart** [haugene/docker-transmission-openvpn#1573]
**Describe the problem**
Hello guys,
I am using this container for quite a while now and everything works fine till now. I think it happends a week or 2 ago. That transmission doubles my torrents. Let me explain, in transmission i have one torrent for example. When i start seeding, the tracker tells me that there is only one torrent seeding, but after a couple of minutes the tracker tells me that i have the same torrent twice or tripple times seeding at the same time. All with the same client. In my client are atm 800 torrents. So i tried a fresh installation of the container with a new config path and i added only one torrent and tried again, but same bug again. I tested it with another tracker, but it happend there to so i think it is a problem from transmission. I can't figure out how to solve this, so i hope one of you could help me because i like this container very much. :D

**Add your docker run command**
I am composing this with portainer within stack.
```
version: '2.1'

services:

 transmission-openvpn:

    volumes:
        - /opt/docker/transmission/data:/data
        - /etc/localtime:/etc/localtime:ro
        - /opt/docker/transmission/default.ovpn:/etc/openvpn/custom/default.ovpn
        - /media/Seagate:/media/Seagate
        - /media/Seagate_v2:/media/Seagate_v2
        - /media/Seagate_v3:/media/Seagate_v3
        - /media/Seagate_v4:/media/Seagate_v4

    environment:

        - PUID=1000
        - PGID=1000
        - CREATE_TUN_DEVICE=true
        - OPENVPN_PROVIDER=CUSTOM
        - OPENVPN_CONFIG=default
        - OPENVPN_USERNAME=*User*
        - OPENVPN_PASSWORD=*PW*
        - TRANSMISSION_WEB_UI=transmission-web-control
        - TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=false
        - TRANSMISSION_DOWNLOAD_DIR=/media/Seagate/Transmission/completed
        - TRANSMISSION_INCOMPLETE_DIR_ENABLED=false
        - "OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60"
        - LOCAL_NETWORK=192.168.0.0/16
        - TRANSMISSION_DHT_ENABLED=false
        - TRANSMISSION_PEX_ENABLED=false
        - TRANSMISSION_DOWNLOAD_QUEUE_SIZE=50
        - TRANSMISSION_PEER_PORT=52072
        - WEBPROXY_ENABLED=false
        - DNS=1.1.1.1:1.0.0.1

    cap_add:

        - NET_ADMIN

    logging:

        driver: json-file

        options:

            max-size: 10m

    ports:

        - 9091:9091

        - 9117:9117 #Jackett

        - 7878:7878 #Radarr

        - 8989:8989 #Sonarr

        - 8686:8686 #Lidarr

        - 5299:5299 #lazylibrarian

    restart: always

    image: haugene/transmission-openvpn:latest-armhf
```
 

**Logs**

```
Starting container with revision: 3d97cd5302985c1a710f46ab0c311f721f224fc6
Using OpenVPN provider: CUSTOM
Starting OpenVPN using config default.ovpn
Setting OpenVPN credentials...
adding route to local network 192.168.0.0/16 via 172.17.0.1 dev eth0
Mon Nov 30 16:07:04 2020 OpenVPN 2.4.7 arm-unknown-linux-gnueabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 20 2019
Mon Nov 30 16:07:04 2020 library versions: OpenSSL 1.1.1d  10 Sep 2019, LZO 2.10
Mon Nov 30 16:07:04 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Mon Nov 30 16:07:04 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]93.177.73.130:1215
Mon Nov 30 16:07:04 2020 UDP link local: (not bound)
Mon Nov 30 16:07:04 2020 UDP link remote: [AF_INET]93.177.73.130:1215
Mon Nov 30 16:07:04 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Mon Nov 30 16:07:04 2020 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1634', remote='link-mtu 1601'
Mon Nov 30 16:07:04 2020 WARNING: 'tun-mtu' is used inconsistently, local='tun-mtu 1532', remote='tun-mtu 1500'
Mon Nov 30 16:07:04 2020 WARNING: 'comp-lzo' is present in local config but missing in remote config, local='comp-lzo'
Mon Nov 30 16:07:04 2020 [server] Peer Connection Initiated with [AF_INET]93.177.73.130:1215
Mon Nov 30 16:07:06 2020 TUN/TAP device tun0 opened
Mon Nov 30 16:07:06 2020 /sbin/ip link set dev tun0 up mtu 1500
Mon Nov 30 16:07:06 2020 /sbin/ip addr add dev tun0 local 10.37.0.81 peer 10.37.0.82
Mon Nov 30 16:07:06 2020 /etc/openvpn/tunnelUp.sh tun0 1500 1637 10.37.0.81 10.37.0.82 init
Up script executed with tun0 1500 1637 10.37.0.81 10.37.0.82 init
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.37.0.81
Using Transmission Web Control  UI, overriding TRANSMISSION_WEB_HOME
Updating Transmission settings.json with values from env variables
Using existing settings.json for Transmission /data/transmission-home/settings.json
Overriding bind-address-ipv4 because TRANSMISSION_BIND_ADDRESS_IPV4 is set to 10.37.0.81
Overriding dht-enabled because TRANSMISSION_DHT_ENABLED is set to False
Overriding download-dir because TRANSMISSION_DOWNLOAD_DIR is set to /media/Seagate/Transmission/completed
Overriding download-queue-size because TRANSMISSION_DOWNLOAD_QUEUE_SIZE is set to 50
Overriding incomplete-dir because TRANSMISSION_INCOMPLETE_DIR is set to /data/incomplete
Overriding incomplete-dir-enabled because TRANSMISSION_INCOMPLETE_DIR_ENABLED is set to False
Overriding peer-port because TRANSMISSION_PEER_PORT is set to 52072
Overriding pex-enabled because TRANSMISSION_PEX_ENABLED is set to False
Overriding rpc-port because TRANSMISSION_RPC_PORT is set to 9091
Overriding scrape-paused-torrents-enabled because TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED is set to False
Overriding watch-dir because TRANSMISSION_WATCH_DIR is set to /data/watch
sed'ing True to true
Enforcing ownership on transmission config directories
Applying permissions to transmission config directories
Setting owner for transmission paths to 1000:1000
Setting permission for files (644) and directories (755)
Setting permission for watch directory (775) and its files (664)

-------------------------------------
Transmission will run as
-------------------------------------
User name:   abc
User uid:    1000
User gid:    1000
-------------------------------------

STARTING TRANSMISSION
Transmission startup script complete.
Mon Nov 30 16:07:07 2020 Initialization Sequence Completed
```

**Host system:**

Output from uname -a
`Linux raspberrypi 5.4.72-v7l+ #1356 SMP Thu Oct 22 13:57:51 BST 2020 armv7l GNU/Linux`
docker -v output
`Docker version 19.03.13, build 4484c46`
