### ISSUE TITLE
RAM Usage: possible memory leak ?

### ISSUE THREAD

**Issue by louisgrasset** [haugene/docker-transmission-openvpn#1596]
Hello,
The transmission container is currently empty (no torrent paused, added, running : nothing) and the memory usage is very strange : going from few MB to GB. By restarting it, I can temporarily reduce the RAM usage, but that's all.
Is there something to do ?

Environnement:
Ubuntu Server (AMD 64 bits) LTS
Docker 20.10.0-rc2
haugene/docker-transmission-openvpn:dev (pulled image yesterday, still getting the issue)

**Comment by Dzheky** [comment]
Same

**Comment by haugene** [comment]
Hmm, and not a small leak either. Multiple gigs in 24h doing nothing? It's tempting to say that it's one of these: https://github.com/transmission/transmission/issues?q=is%3Aissue+is%3Aopen+memory+leak

You could try to exec into the container and run `/etc/transmission/stop.sh` just to confirm that the memory usage declines. But I mean. Of course we know it's Transmission, if this is OpenVPN then 2020 would get crazier still.

Not sure what I can do though. It's either Transmission itself on all platforms. Or it's Transmission on Docker. But that's what we do here :) Open for suggestions though! We've touched on this before as well #1347

**Comment by haugene** [comment]
Come to think of it. We could of course downgrade to a version of Transmission that we know to be stable. So far we've always been running the latest ones in the repositories. We're handling settings.json files though, so in the long run I don't want to big stretch on the supported version of Transmission.

**Comment by louisgrasset** [comment]
Can confirm `/etc/transmission/stop.sh` reduces RAM usage

**Comment by pkishino** [comment]
hmm, I've been monitoring this over time and can't really see this issue for the past 2 months.. If this is still an issue with latest alpine release please create a new issue

**Comment by bramus** [comment]
It still is an issue.

The container starts with about 50MB of RAM used. Once a torrent is added and being downloaded, memory shoots up. When said torrent is done (and the file is even removed from the list), the memory level remains the same.

Running `/etc/transmission/stop.sh` as suggested does **not** release the memory.

**Comment by pkishino** [comment]
> It still is an issue.
> 
> The container starts with about 50MB of RAM used. Once a torrent is added and being downloaded, memory shoots up. When said torrent is done (and the file is even removed from the list), the memory level remains the same.
> 
> Running `/etc/transmission/stop.sh` as suggested does **not** release the memory.

are you using latest? ie. transmission 2.94? 
you could try a container using 3.7.1 which uses transmission 3.0 or upgrade transmission within the container to see if the memory issue is fixed. 
I havent seen this issue here locally though..

**Comment by bramus** [comment]
> are you using latest? ie. transmission 2.94?

Yes, I'm using latest. Running on a Synology NAS, as follows:

```
docker run -d \
    --restart=always \
    --cap-add=NET_ADMIN \
    --name "transmission" \
    -p 9091:9091 \
    -p 8118:8118 \
    -v /volume1/downloads:/data \
    -v /volume1/docker/transmission:/config \
    -e PUID=1026 \
    -e PGID=100 \
    -e OPENVPN_PROVIDER="PRIVADO" \
    -e OPENVPN_USERNAME="***REDACTED***" \
    -e OPENVPN_PASSWORD="***REDACTED***" \
    -e LOCAL_NETWORK="192.168.0.0/24" \
    -e TZ="Europe/Brussels" \
    -e PEER_DNS_PIN_ROUTES=false \
    -e DROP_DEFAULT_ROUTE=true \
    -e CREATE_TUN_DEVICE=true \
    -e WEBPROXY_ENABLED=true \
    -e TRANSMISSION_RPC_ENABLED=true \
    -e TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true \
    -e TRANSMISSION_RPC_USERNAME="***REDACTED***" \
    -e TRANSMISSION_RPC_PASSWORD="***REDACTED***" \
    -e TRANSMISSION_RPC_WHITELIST_ENABLED=true \
    -e TRANSMISSION_RPC_WHITELIST=127.0.0.1,192.168.0.* \
    -e TRANSMISSION_BLOCKLIST_ENABLED=true \
    -e TRANSMISSION_BLOCKLIST_URL="https://github.com/Naunter/BT_BlockLists/releases/download/master/bt_blocklists.gz" \
    haugene/transmission-openvpn
```

The Tranmission Log Entries don't indicate any issues (AFAIK):

```
[2022-02-27 22:59:27.985] Transmission 2.94 (d8e60ee44f) started (session.c:740)
[2022-02-27 22:59:27.985] RPC Server Adding address to whitelist: 127.0.0.1 (rpc-server.c:971)
[2022-02-27 22:59:27.985] RPC Server Adding address to whitelist: 192.168.0.* (rpc-server.c:971)
[2022-02-27 22:59:27.985] RPC Server Adding address to whitelist: 172.21.34.* (rpc-server.c:971)
[2022-02-27 22:59:27.985] RPC Server Serving RPC and Web requests on port 127.0.0.1:9091/transmission/ (rpc-server.c:1213)
[2022-02-27 22:59:27.985] RPC Server Password required (rpc-server.c:1220)
[2022-02-27 22:59:27.985] Port Forwarding Stopped (port-forwarding.c:180)
[2022-02-27 22:59:27.985] DHT Reusing old id (tr-dht.c:307)
[2022-02-27 22:59:27.985] DHT Bootstrapping from 59 IPv4 nodes (tr-dht.c:156)
[2022-02-27 22:59:27.985] Using settings from "/data/transmission-home" (daemon.c:528)
[2022-02-27 22:59:27.985] Saved "/data/transmission-home/settings.json" (variant.c:1266)
[2022-02-27 22:59:27.985] transmission-daemon requiring authentication (daemon.c:554)
[2022-02-27 22:59:27.985] Watching "/data/watch" for new .torrent files (daemon.c:573)
[2022-02-27 22:59:27.985] Blocklist "blocklist.bin" contains 436910 entries (blocklist.c:100)
```

**Comment by pkishino** [comment]
Do you have any resource stats over time ?
E.g. I have over the last few months always had around 150-300 torrents in the client, average mem use is 100mb, cached varies quite a bit (200-1gig) based on activity etc.. but the mem use is very stable, it will start up towards 50mb, then once activity starts going it peaks around 110 and drops to 100ish where it will remain for weeks

**Comment by bramus** [comment]
Running `htop`, I see it's privoxy that's hogging the resources. Having limited RAM usage of the container to 2GB, it tries to consume all that.

<img width="854" alt="Screenshot 2022-03-04 at 14 23 03" src="https://user-images.githubusercontent.com/213073/156771407-18489a93-c323-4eb3-a59d-338e872c5c81.png">

This was only a few minutes after having booted the container and loading 4 torrents into it (which were downloading at a combined speed of 9MB/s).

Note that I had to start the container with the extra flags `-e PEER_DNS_PIN_ROUTES=false -e DROP_DEFAULT_ROUTE=true`, in order to make it work with Privado _(see https://github.com/haugene/docker-transmission-openvpn/issues/2192#issuecomment-1046131732)_. Perhaps that might be the culprit?

**Comment by bramus** [comment]
Reading up on Privoxy, I see that there was [a memory leak present (CVE-2021-44542)](https://www.opencve.io/cve/CVE-2021-44542). This leak [was fixed in 3.0.33](https://www.privoxy.org/3.0.33/user-manual/whatsnew.html). The version included in the container is 3.0.28.

**Comment by pkishino** [comment]
ah, I don7t use the webproxy so didn't see this.
great find!
Let me check if I can bum the version

**Comment by stawiski** [comment]
I experience the memory leak problem on current `master`.
When transmission is downloading, memory keeps raising, if I pause transmission then memory increase also stops. I've seen this go up to almost 40GB.

I'm on a MacOS with Docker Desktop 4.8.2 (79419), running only this container.

![image](https://user-images.githubusercontent.com/26871388/169802740-09686876-8edb-4ed6-ab9e-4ffc38b5b171.png)

`bash-5.1# /etc/transmission/stop.sh` doesn't release memory, **nor does stopping the whole container**. Could this be Docker issue?

**Comment by stawiski** [comment]
Well, it seems the above issue goes away after disabling experimental features
![image](https://user-images.githubusercontent.com/26871388/169948475-35b1e836-7474-462d-96fa-85276ed81598.png)

**Comment by Qhilm** [comment]
I also have had extremely high memory usage: with 6 torrents downloading, Transmission would gobble up 10+GB of RAM within two hours and render my synology NAS unresponsive (the drop is when I restarted the container, 100% = 12GB):

<img width="1084" alt="image" src="https://github.com/haugene/docker-transmission-openvpn/assets/3350433/7c27a4af-a358-44e5-9831-ffe901ff4d5f">


I was using the `latest` branch and switched to the `focal` branch as recommended above, it immediately solves the problem, you can see memory is not going up anymore after the last drop (which is when I redeployed with the new image):

<img width="1088" alt="image" src="https://github.com/haugene/docker-transmission-openvpn/assets/3350433/c0edac02-80b0-4339-8c25-76c3da7017f8">


My Docker Compose (the branch is now `focal`, this is the original docker compose):

```yaml
version: '3.8'
services:
  transmission-openvpn:
    container_name: 'haugene'
    cap_add:
      - NET_ADMIN
    devices:
      - '/dev/net/tun'
    volumes:
      - /volume1/Laster/transmission-data/:/data
      - /volume1/docker/haugene/resolv.conf:/etc/resolv.conf
      - /volume1/docker/haugene/:/config
    environment:
      - OPENVPN_PROVIDER=PROTONVPN
      - OPENVPN_CONFIG=dk.protonvpn.net.udp
      - OPENVPN_USERNAME=**None**
      - OPENVPN_PASSWORD=**None**
      - LOCAL_NETWORK=192.168.178.0/24
      - OVERRIDE_DNS_1=9.9.9.9
      - OVERRIDE_DNS_2=149.112.112.112
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - TRANSMISSION_RATIO_LIMIT=3
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
      - TRANSMISSION_SPEED_LIMIT_UP_ENABLED=true
      - TRANSMISSION_SPEED_LIMIT_UP=200
      - TRANSMISSION_BLOCKLIST_URL=http://list.iblocklist.com/?list=xxxx&fileformat=p2p&archiveformat=gz&username=xxx&pin=xxx
      - TRANSMISSION_RPC_USERNAME=xxx
      - TRANSMISSION_RPC_PASSWORD=xxx
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
    logging:
      driver: json-file
      options:
        max-size: 10m
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    ports:
      - '9091:9091'
    image: haugene/transmission-openvpn:latest

networks:
  default:
    external:
      name: mybridge
```

In case it's useful.
