### ISSUE TITLE
ProtonVPN only able to use some config files

### ISSUE THREAD

**Issue by Blehhh** [haugene/docker-transmission-openvpn#1626]
**Before creating this issue I have:**

- [X] Searched for [similar issues](https://github.com/haugene/docker-transmission-openvpn/issues)
- [X] [Read the documentation](https://haugene.github.io/docker-transmission-openvpn/). Especially the troubleshooting section
- [X] Tried to add as much relevant information to the issue as possible

**Describe the problem**

Trying to use the au.protonvpn.com config file, but I get the below error. I have tested with the windows 10 openvpn client and been able to connect to it without issue. I have done a pull of this image so should be on the latest version. 

So far I have it working with the is-*.protonvpn.com.udp config files but was unable to use the sg config files. Have not tried with others

**Add your docker run command or docker-compose file**

Can add if needed but my current setup is working fine just with a limited amount of config files.

**Logs**

```
Starting container with revision: a4d65774f855a04070766e53346661f48c76fa0e
Creating TUN device /dev/net/tun
mknod: /dev/net/tun: File exists
Using OpenVPN provider: PROTONVPN
Supplied config au.protonvpn.com.ovpn could not be found.
Your options for this provider are:
ch-05.protonvpn.com.tcp.ovpn
ch-05.protonvpn.com.udp.ovpn
ch-06.protonvpn.com.tcp.ovpn
ch-06.protonvpn.com.udp.ovpn
ch-07.protonvpn.com.tcp.ovpn
ch-07.protonvpn.com.udp.ovpn
ch-08.protonvpn.com.tcp.ovpn
ch-08.protonvpn.com.udp.ovpn
ch-10.protonvpn.com.tcp.ovpn
ch-10.protonvpn.com.udp.ovpn
ch-11.protonvpn.com.tcp.ovpn
ch-11.protonvpn.com.udp.ovpn
ch-12.protonvpn.com.tcp.ovpn
ch-12.protonvpn.com.udp.ovpn
ch-13.protonvpn.com.tcp.ovpn
ch-13.protonvpn.com.udp.ovpn
is-01.protonvpn.com.tcp.ovpn
is-01.protonvpn.com.udp.ovpn
is-02.protonvpn.com.tcp.ovpn
is-02.protonvpn.com.udp.ovpn
is-03.protonvpn.com.tcp.ovpn
is-03.protonvpn.com.udp.ovpn
is-04.protonvpn.com.tcp.ovpn
is-04.protonvpn.com.udp.ovpn
is-05.protonvpn.com.tcp.ovpn
is-05.protonvpn.com.udp.ovpn
is-06.protonvpn.com.tcp.ovpn
is-06.protonvpn.com.udp.ovpn
is-07.protonvpn.com.tcp.ovpn
is-07.protonvpn.com.udp.ovpn
is-08.protonvpn.com.tcp.ovpn
is-08.protonvpn.com.udp.ovpn
nl-01.protonvpn.com.tcp.ovpn
nl-01.protonvpn.com.udp.ovpn
nl-02.protonvpn.com.tcp.ovpn
nl-02.protonvpn.com.udp.ovpn
nl-03.protonvpn.com.tcp.ovpn
nl-03.protonvpn.com.udp.ovpn
nl-04.protonvpn.com.tcp.ovpn
nl-04.protonvpn.com.udp.ovpn
nl-05.protonvpn.com.tcp.ovpn
nl-05.protonvpn.com.udp.ovpn
nl-06.protonvpn.com.tcp.ovpn
nl-06.protonvpn.com.udp.ovpn
nl-07.protonvpn.com.tcp.ovpn
nl-07.protonvpn.com.udp.ovpn
nl-08.protonvpn.com.tcp.ovpn
nl-08.protonvpn.com.udp.ovpn
nl-09.protonvpn.com.tcp.ovpn
nl-09.protonvpn.com.udp.ovpn
nl-10.protonvpn.com.tcp.ovpn
nl-10.protonvpn.com.udp.ovpn
nl-11.protonvpn.com.tcp.ovpn
nl-11.protonvpn.com.udp.ovpn
nl-12.protonvpn.com.tcp.ovpn
nl-12.protonvpn.com.udp.ovpn
nl-13.protonvpn.com.tcp.ovpn
nl-13.protonvpn.com.udp.ovpn
nl-14.protonvpn.com.tcp.ovpn
nl-14.protonvpn.com.udp.ovpn
nl-15.protonvpn.com.tcp.ovpn
nl-15.protonvpn.com.udp.ovpn
nl-16.protonvpn.com.tcp.ovpn
nl-16.protonvpn.com.udp.ovpn
nl-25.protonvpn.com.tcp.ovpn
nl-25.protonvpn.com.udp.ovpn
nl-26.protonvpn.com.tcp.ovpn
nl-26.protonvpn.com.udp.ovpn
nl-27.protonvpn.com.tcp.ovpn
nl-27.protonvpn.com.udp.ovpn
nl-28.protonvpn.com.tcp.ovpn
nl-28.protonvpn.com.udp.ovpn
se-01.protonvpn.com.tcp.ovpn
se-01.protonvpn.com.udp.ovpn
se-02.protonvpn.com.tcp.ovpn
se-02.protonvpn.com.udp.ovpn
se-03.protonvpn.com.tcp.ovpn
se-03.protonvpn.com.udp.ovpn
se-04.protonvpn.com.tcp.ovpn
se-04.protonvpn.com.udp.ovpn
se-05.protonvpn.com.tcp.ovpn
se-05.protonvpn.com.udp.ovpn
se-06.protonvpn.com.tcp.ovpn
se-06.protonvpn.com.udp.ovpn
se-07.protonvpn.com.tcp.ovpn
se-07.protonvpn.com.udp.ovpn
se-08.protonvpn.com.tcp.ovpn
se-08.protonvpn.com.udp.ovpn
sg-21.protonvpn.com.tcp.ovpn
sg-21.protonvpn.com.udp.ovpn
sg-22.protonvpn.com.tcp.ovpn
sg-22.protonvpn.com.udp.ovpn
sg-23.protonvpn.com.tcp.ovpn
sg-23.protonvpn.com.udp.ovpn
sg-24.protonvpn.com.tcp.ovpn
sg-24.protonvpn.com.udp.ovpn
sg-25.protonvpn.com.tcp.ovpn
sg-25.protonvpn.com.udp.ovpn
sg-26.protonvpn.com.tcp.ovpn
sg-26.protonvpn.com.udp.ovpn
sg-27.protonvpn.com.tcp.ovpn
sg-27.protonvpn.com.udp.ovpn
sg-28.protonvpn.com.tcp.ovpn
sg-28.protonvpn.com.udp.ovpn
sg-29.protonvpn.com.tcp.ovpn
sg-29.protonvpn.com.udp.ovpn
sg-30.protonvpn.com.tcp.ovpn
sg-30.protonvpn.com.udp.ovpn
sg-31.protonvpn.com.tcp.ovpn
sg-31.protonvpn.com.udp.ovpn
sg-32.protonvpn.com.tcp.ovpn
sg-32.protonvpn.com.udp.ovpn
sg-33.protonvpn.com.tcp.ovpn
sg-33.protonvpn.com.udp.ovpn
sg-34.protonvpn.com.tcp.ovpn
sg-34.protonvpn.com.udp.ovpn
sg-35.protonvpn.com.tcp.ovpn
sg-35.protonvpn.com.udp.ovpn
sg-36.protonvpn.com.tcp.ovpn
sg-36.protonvpn.com.udp.ovpn
sg-37.protonvpn.com.tcp.ovpn
sg-37.protonvpn.com.udp.ovpn
sg-38.protonvpn.com.tcp.ovpn
sg-38.protonvpn.com.udp.ovpn
sg-39.protonvpn.com.tcp.ovpn
sg-39.protonvpn.com.udp.ovpn
sg-40.protonvpn.com.tcp.ovpn
sg-40.protonvpn.com.udp.ovpn
sg-41.protonvpn.com.tcp.ovpn
sg-41.protonvpn.com.udp.ovpn
sg-42.protonvpn.com.tcp.ovpn
sg-42.protonvpn.com.udp.ovpn
sg-43.protonvpn.com.tcp.ovpn
sg-43.protonvpn.com.udp.ovpn
sg-44.protonvpn.com.tcp.ovpn
sg-44.protonvpn.com.udp.ovpn
NB: Remember to not specify .ovpn as part of the config name.
```

**Host system:**

Running docker version 20.10.1 on up to date linux mint

**Comment by Ryland0** [comment]
This is how I got mine to work.

OPENVPN_PROVIDER | CUSTOM
OPENVPN_USERNAME | [application username from Proton]
OPENVPN_PASSWORD | [application password from Proton]

Create a bind map with the following:
/etc/openvpn/client/default.ovpn:/etc/openvpn/custom/default.ovpn

Move and rename your downloaded file from Proton to the above.

Edit the default.ovpn file and add the following:
auth-user-pass /config/openvpn-credentials.txt

Create openvpn-credentials.txt in that path on the container (or host and map it)
It only contains the same ProtonVPN user/pass used in the env.

Also in the default.opvn, I had to comment out the following:
# script-security 2
# up /etc/openvpn/update-resolv-conf
# down /etc/openvpn/update-resolv-conf

I have Google on the container so this really wasn't important to me.

That should be it. Let me know if you need anything else.

**Comment by FabriceC01** [comment]
Hello,
I've got the same error than Blehhh using protonvpn
my compose file is :
```
---
version: '2'
services:
    transmission-openvpn:
        volumes:
            - '/srv/dev-disk-by-label-4toNas/Downloads/Torrents:/data'
            - '/srv/dev-disk-by-label-4toNas/Appdata/Transmission/:/config'
            - '/etc/localtime:/etc/localtime:ro'
        devices:
            - /dev/net/tun # This creates a tunnel for Transmission    
        environment:
            - OPENVPN_PROVIDER=PROTONVPN
            - OPENVPN_CONFIG=nl-01.protonvpn.com.tcp
            - OPENVPN_USERNAME=xtbKJ****************InqUe #codé par proton
            - OPENVPN_PASSWORD=Stnm*********************UxrXH #codé par proton
            - WEBPROXY_ENABLED=false
            - LOCAL_NETWORK=192.168.0.0/16
            - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60 # Leave this as is
            - PUID=1000 #Change to your PUID
            - PGID=100 #Change to your PGID
        cap_add:
            - NET_ADMIN
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - 9091:9091
            - 8888:8888
        dns:
            - 1.1.1.1       
        image: haugene/transmission-openvpn
        container_name: transmission-protonvpn
        restart: always
```
I didn't  really understood Ryland0's solution. If someone can help me modifying my compose file ?
Thanks by advance

Fabrice
