### ISSUE TITLE
Not accessible from public IP / DDNS

### ISSUE THREAD

**Issue by thijskaspers** [haugene/docker-transmission-openvpn#165]
Hi Haugene,

First of all thanks for creating this! I've got it running perfectly on my Rpi3 using the armhf Dockerfile and compose file, after some tweaking.

This is my docker-compose-armhf.yml file:

```
version: '2'

services:
 transmission:
  build:
     context: .
     dockerfile: Dockerfile
  privileged: true
  restart: always
  ports:
    - "9091:9091"
  dns:
    - 8.8.8.8
    - 8.8.4.4
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /mnt/library/:/data
  environment:
    - OPENVPN_PROVIDER=PIA
    - OPENVPN_USERNAME=username-here
    - OPENVPN_PASSWORD=password-here
    - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
    - LOCAL_NETWORK=192.168.2.0/24

 proxy:
  build:
    context: ./proxy
    dockerfile: Dockerfile
  links:
    - transmission
  ports:
    - "8080:8080"
  volumes:
    - /etc/localtime:/etc/localtime:ro
```

I'm starting the containers like this:

`sudo docker-compose -f docker-compose-armhf.yml up -d`

The problem I have is that it is perfectly accessible from my local IP: 192.168.2.180:9091, but when I try to run it from my public IP or DDNS address it won't open. I'm certain that I've set up the port forwarding from my router correctly, because all other web interfaces on my Raspberry Pi are accessible from the outside world.

Am I forgetting something obvious here?

Thanks in advance!
