### ISSUE TITLE
rss issues

### ISSUE THREAD

**Issue by samwaugh** [haugene/docker-transmission-openvpn#1668]
**Before creating this issue I have:**

- [x] Searched for [similar issues](https://github.com/haugene/docker-transmission-openvpn/issues)
- [x] [Read the documentation](https://haugene.github.io/docker-transmission-openvpn/). Especially the troubleshooting section
- [x] Tried to add as much relevant information to the issue as possible

**Describe the problem**
I've been asked to create a new issue following on from #1483, even though this relates, given the testing Haugene had asked for had not occurred from what I could see.

I'm trying to set up a Raspberry Pi 3 with transmission-openvpn and transmission-rss using Docker version 20.10.2, build 2291f61. Got the transmission-openvpn running using the docker-compose script (the only difficulty was finding the OPENVPN_CONFIG names for PIA in my area).

I'm trying to get the rss container running now with the rss dev branch as indicated in #1483. Based on documentation at https://docs.docker.com/network/links/ , I assume <transmission-container> is meant to be the container ID or container name? Running this:

```
docker run -d -e "RSS_URL=<URL>" --link <container ID>:transmission --name "transmission-rss" haugene/transmission-rss:dev
```
I'm getting the following error:
```
docker: Error response from daemon: Cannot link to /haugene_transmission-openvpn_1, as it does not belong to the default network.
```
Any thoughts on what I'm doing wrong?

**Add your docker run command or docker-compose file**
So I've also tried getting things running using the following docker-compose.yml and docker-compose up -d:
```
version: '3.3'
services:
    transmission-openvpn:
        cap_add:
            - NET_ADMIN
        volumes:
            - '/home/pi/:/data'
        environment:
            - OPENVPN_PROVIDER=PIA
            - OPENVPN_CONFIG=au_melbourne,au_sydney,au_perth
            - OPENVPN_USERNAME=<USERNAME>
            - OPENVPN_PASSWORD=<PASSWORD>
            - LOCAL_NETWORK=192.168.0.0/16
            - TZ=Australia/Melbourne
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '9091:9091'
        image: haugene/transmission-openvpn
        container_name: transmission-openvpn
    transmission-rss:
        image: haugene/transmission-rss:dev
        container_name: transmission-rss
        depends_on:
            - transmission-openvpn
        restart: always
        environment:
            - RSS_URL=<URL>
```
The rss container keeps restarting without any effect. Happy to take any advice...

**Logs**
Logs for the docker-compose above (used "\<edited\>" to cut specific URLs out):
```
transmission-rss        | Found mounted /etc/transmission-rss.conf file
transmission-rss        | Starting RSS plugin with the following config:
transmission-rss        | 
transmission-rss        | feeds:
transmission-rss        |   - url: http://showrss.info/u<edited>
transmission-rss        |     download_path: /data/completed
transmission-rss        |     
transmission-rss        | server:
transmission-rss        |   host: transmission
transmission-rss        |   port: 9091
transmission-rss        |   rpc_path: /transmission/rpc
transmission-rss        | 2021-01-16 04:17:32 (info) transmission-rss 1.2.0
transmission-rss        | 2021-01-16 04:17:32 (debug) {"feeds"=>[{"url"=>"http://showrss.info<edited>", "download_path"=>"/data/completed"}], "update_interval"=>600, "add_paused"=>false, "server"=>{"host"=>"transmission", "port"=>9091, "rpc_path"=>"/transmission/rpc"}, "login"=>nil, "log"=>{"target"=>#<IO:<STDERR>>, "level"=>:debug}, "fork"=>false, "single"=>false, "pid_file"=>false, "privileges"=>{}, "seen_file"=>nil}
transmission-rss        | 2021-01-16 04:17:32 (debug) no privilege dropping
transmission-rss        | 2021-01-16 04:17:32 (debug) 0 uris from seenfile
transmission-rss        | 2021-01-16 04:17:32 (debug) pid 8
transmission-rss        | 2021-01-16 04:17:32 (debug) aggregator start
transmission-rss        | 2021-01-16 04:17:32 (debug) aggregate http://showrss.info/user/<edited>
transmission-rss        | 2021-01-16 04:17:34 (debug) on_new_item event magnet:?xt=urn:btih:78995307DC1BB215844403AE88CA91701DD698D9&dn=<edited>
transmission-rss        | 2021-01-16 04:17:34 (debug) request transmission:9091
transmission-rss        | /usr/local/lib/ruby/2.6.0/net/http.rb:949:in `rescue in block in connect': Failed to open TCP connection to transmission:9091 (getaddrinfo: Name does not resolve) (SocketError)
transmission-rss        | 	from /usr/local/lib/ruby/2.6.0/net/http.rb:946:in `block in connect'
transmission-rss        | 	from /usr/local/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
transmission-rss        | 	from /usr/local/lib/ruby/2.6.0/timeout.rb:103:in `timeout'
transmission-rss        | 	from /usr/local/lib/ruby/2.6.0/net/http.rb:945:in `connect'
transmission-rss        | 	from /usr/local/lib/ruby/2.6.0/net/http.rb:930:in `do_start'
transmission-rss        | 	from /usr/local/lib/ruby/2.6.0/net/http.rb:919:in `start'
transmission-rss        | 	from /usr/local/lib/ruby/2.6.0/net/http.rb:605:in `start'
transmission-rss        | 	from /usr/local/bundle/gems/transmission-rss-1.2.0/lib/transmission-rss/client.rb:117:in `http_request'
transmission-rss        | 	from /usr/local/bundle/gems/transmission-rss-1.2.0/lib/transmission-rss/client.rb:127:in `block in request'
transmission-rss        | 	from /usr/local/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
transmission-rss        | 	from /usr/local/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
transmission-rss        | 	from /usr/local/lib/ruby/2.6.0/timeout.rb:33:in `catch'
transmission-rss        | 	from /usr/local/lib/ruby/2.6.0/timeout.rb:33:in `catch'
transmission-rss        | 	from /usr/local/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
transmission-rss        | 	from /usr/local/bundle/gems/transmission-rss-1.2.0/lib/transmission-rss/client.rb:125:in `request'
transmission-rss        | 	from /usr/local/bundle/gems/transmission-rss-1.2.0/lib/transmission-rss/client.rb:90:in `get_session_id'
transmission-rss        | 	from /usr/local/bundle/gems/transmission-rss-1.2.0/lib/transmission-rss/client.rb:29:in `rpc'
transmission-rss        | 	from /usr/local/bundle/gems/transmission-rss-1.2.0/lib/transmission-rss/client.rb:59:in `add_torrent'
transmission-rss        | 	from /usr/local/bundle/gems/transmission-rss-1.2.0/bin/transmission-rss:160:in `block in <top (required)>'
transmission-rss        | 	from /usr/local/bundle/gems/transmission-rss-1.2.0/lib/transmission-rss/callback.rb:12:in `block (3 levels) in callback'
transmission-rss        | 	from /usr/local/bundle/gems/transmission-rss-1.2.0/lib/transmission-rss/aggregator.rb:128:in `process_link'
transmission-rss        | 	from /usr/local/bundle/gems/transmission-rss-1.2.0/lib/transmission-rss/aggregator.rb:65:in `block (3 levels) in run'
transmission-rss        | 	from /usr/local/bundle/gems/transmission-rss-1.2.0/lib/transmission-rss/aggregator.rb:64:in `each'
transmission-rss        | 	from /usr/local/bundle/gems/transmission-rss-1.2.0/lib/transmission-rss/aggregator.rb:64:in `block (2 levels) in run'
transmission-rss        | 	from /usr/local/bundle/gems/transmission-rss-1.2.0/lib/transmission-rss/aggregator.rb:44:in `each'
transmission-rss        | 	from /usr/local/bundle/gems/transmission-rss-1.2.0/lib/transmission-rss/aggregator.rb:44:in `block in run'
transmission-rss        | 	from /usr/local/bundle/gems/transmission-rss-1.2.0/lib/transmission-rss/aggregator.rb:43:in `loop'
transmission-rss        | 	from /usr/local/bundle/gems/transmission-rss-1.2.0/lib/transmission-rss/aggregator.rb:43:in `run'
transmission-rss        | 	from /usr/local/bundle/gems/transmission-rss-1.2.0/bin/transmission-rss:198:in `<top (required)>'
transmission-rss        | 	from /usr/local/bundle/bin/transmission-rss:23:in `load'
transmission-rss        | 	from /usr/local/bundle/bin/transmission-rss:23:in `<main>'
transmission-rss        | /usr/local/lib/ruby/2.6.0/net/http.rb:947:in `initialize': getaddrinfo: Name does not resolve (SocketError)
transmission-rss        | 	from /usr/local/lib/ruby/2.6.0/net/http.rb:947:in `open'
transmission-rss        | 	from /usr/local/lib/ruby/2.6.0/net/http.rb:947:in `block in connect'
transmission-rss        | 	from /usr/local/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
transmission-rss        | 	from /usr/local/lib/ruby/2.6.0/timeout.rb:103:in `timeout'
transmission-rss        | 	from /usr/local/lib/ruby/2.6.0/net/http.rb:945:in `connect'
transmission-rss        | 	from /usr/local/lib/ruby/2.6.0/net/http.rb:930:in `do_start'
transmission-rss        | 	from /usr/local/lib/ruby/2.6.0/net/http.rb:919:in `start'
transmission-rss        | 	from /usr/local/lib/ruby/2.6.0/net/http.rb:605:in `start'
transmission-rss        | 	from /usr/local/bundle/gems/transmission-rss-1.2.0/lib/transmission-rss/client.rb:117:in `http_request'
transmission-rss        | 	from /usr/local/bundle/gems/transmission-rss-1.2.0/lib/transmission-rss/client.rb:127:in `block in request'
transmission-rss        | 	from /usr/local/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
transmission-rss        | 	from /usr/local/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
transmission-rss        | 	from /usr/local/lib/ruby/2.6.0/timeout.rb:33:in `catch'
transmission-rss        | 	from /usr/local/lib/ruby/2.6.0/timeout.rb:33:in `catch'
transmission-rss        | 	from /usr/local/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
transmission-rss        | 	from /usr/local/bundle/gems/transmission-rss-1.2.0/lib/transmission-rss/client.rb:125:in `request'
transmission-rss        | 	from /usr/local/bundle/gems/transmission-rss-1.2.0/lib/transmission-rss/client.rb:90:in `get_session_id'
transmission-rss        | 	from /usr/local/bundle/gems/transmission-rss-1.2.0/lib/transmission-rss/client.rb:29:in `rpc'
transmission-rss        | 	from /usr/local/bundle/gems/transmission-rss-1.2.0/lib/transmission-rss/client.rb:59:in `add_torrent'
transmission-rss        | 	from /usr/local/bundle/gems/transmission-rss-1.2.0/bin/transmission-rss:160:in `block in <top (required)>'
transmission-rss        | 	from /usr/local/bundle/gems/transmission-rss-1.2.0/lib/transmission-rss/callback.rb:12:in `block (3 levels) in callback'
transmission-rss        | 	from /usr/local/bundle/gems/transmission-rss-1.2.0/lib/transmission-rss/aggregator.rb:128:in `process_link'
transmission-rss        | 	from /usr/local/bundle/gems/transmission-rss-1.2.0/lib/transmission-rss/aggregator.rb:65:in `block (3 levels) in run'
transmission-rss        | 	from /usr/local/bundle/gems/transmission-rss-1.2.0/lib/transmission-rss/aggregator.rb:64:in `each'
transmission-rss        | 	from /usr/local/bundle/gems/transmission-rss-1.2.0/lib/transmission-rss/aggregator.rb:64:in `block (2 levels) in run'
transmission-rss        | 	from /usr/local/bundle/gems/transmission-rss-1.2.0/lib/transmission-rss/aggregator.rb:44:in `each'
transmission-rss        | 	from /usr/local/bundle/gems/transmission-rss-1.2.0/lib/transmission-rss/aggregator.rb:44:in `block in run'
transmission-rss        | 	from /usr/local/bundle/gems/transmission-rss-1.2.0/lib/transmission-rss/aggregator.rb:43:in `loop'
transmission-rss        | 	from /usr/local/bundle/gems/transmission-rss-1.2.0/lib/transmission-rss/aggregator.rb:43:in `run'
transmission-rss        | 	from /usr/local/bundle/gems/transmission-rss-1.2.0/bin/transmission-rss:198:in `<top (required)>'
transmission-rss        | 	from /usr/local/bundle/bin/transmission-rss:23:in `load'
transmission-rss        | 	from /usr/local/bundle/bin/transmission-rss:23:in `<main>'
```
**Host system:**

Raspberry Pi 3 Model B+ with Buster Raspberry Pi OS 2020-08-20 dist-upgraded prior to issues above (16 January), using Docker version 20.10.2, build 2291f61, docker-compose version 1.27.4, build 40524192.

**Comment by pkishino** [comment]
hmm, I tested this in the past and think it should still work,
as per here:
https://haugene.github.io/docker-transmission-openvpn/rss-plugin/
it would be the container name of the transmission container
..
just tried this now myself and it works fine

**Comment by samwaugh** [comment]
ok, so the name not the ID. I'm still getting the same error when using the dev branch of transmission-rss:
```
docker run -d -e "RSS_URL=\<snip\>" --link transmission-openvpn:transmission --name "transmission-rss" haugene/transmission-rss:dev

docker: Error response from daemon: Cannot link to /transmission-openvpn, as it does not belong to the default network.
```
Thoughts?

**Comment by pkishino** [comment]
try this:
https://stackoverflow.com/questions/36489696/cannot-link-to-a-running-container-started-by-docker-compose
seems this is related to compose creating diff networks

**Comment by samwaugh** [comment]
Thanks! I didn’t realise that was a thing. I’ll report back when I get a chance...

**Comment by samwaugh** [comment]
Based on the article @pkishino linked to, I ran "docker network ls" to find the network is called "haugene_default". So my docker command is now:
```
docker run -d -e "RSS_URL=" --link transmission-openvpn:transmission --name "transmission-rss" --net haugene_default haugene/transmission-rss:dev
```
The process runs and then stops. The logs look like this:

```
Starting RSS plugin with the following config:

feeds:
  - url: *****
    download_path: /data/completed
    
server:
  host: transmission
  port: 9091
  rpc_path: /transmission/rpc
2021-01-24 05:12:30 (info) transmission-rss 1.2.0
2021-01-24 05:12:30 (debug) {"feeds"=>[{"url"=>"****", "download_path"=>"/data/completed"}], "update_interval"=>600, "add_paused"=>false, "server"=>{"host"=>"transmission", "port"=>9091, "rpc_path"=>"/transmission/rpc"}, "login"=>nil, "log"=>{"target"=>#<IO:<STDERR>>, "level"=>:debug}, "fork"=>false, "single"=>false, "pid_file"=>false, "privileges"=>{}, "seen_file"=>nil}
2021-01-24 05:12:30 (debug) no privilege dropping
2021-01-24 05:12:30 (debug) 0 uris from seenfile
2021-01-24 05:12:30 (debug) pid 13
2021-01-24 05:12:30 (debug) aggregator start
2021-01-24 05:12:30 (debug) aggregate ****
2021-01-24 05:12:31 (debug) on_new_item event magnet:?xt=****
2021-01-24 05:12:31 (debug) request transmission:9091
/usr/local/lib/ruby/2.6.0/net/http.rb:949:in `rescue in block in connect': Failed to open TCP connection to transmission:9091 (getaddrinfo: Name does not resolve) (SocketError)

/usr/local/lib/ruby/2.6.0/net/http.rb:947:in `initialize': getaddrinfo: Name does not resolve (SocketError)

```
Each SocketError is followed by a bunch of "from" statements showing the nesting of the error, based in http.rb file.

Any ideas?

Apologies it has taken me a while to get back to this.

**Comment by reconman** [comment]
I have both containers running, I think you're overlooking a trivial thing. It says `Name does not resolve`.

What this means is that the hostname `transmission` cannot be resolved. The docker container hostname is usually assigned via `--hostname transmission`. In your docker compose.yml, I don't see any hostname assigned to transmission.

This stackoverflow answer gives an example on how to specify the hostname in the compose.yml: https://stackoverflow.com/a/49666342/5971497

**Comment by pkishino** [comment]
I tried running these a while back when making a PR and tried this recently and never had to specify a host name, just the link worked fine (using transmission as you did).
So not sure why it's not working for you

**Comment by samwaugh** [comment]
@reconman : thank you! that solved it! I'm still not quite sure why, but adding hostname: transmission worked. I tried hostname: transmission-vpn and that did not work for the rss module. Not quite sure where the hostname default is defined, but...

Adn many thanks to @pkishino for your help too. Greatly appreciated.

For anyone wondering, my final docker-compose.yml follows (with private settings <snip>ped; as mentioned using dev version of rss, and version 3.3 of for https://github.com/haugene/docker-transmission-openvpn/issues/1705):
```
version: '3.9'
services:
    transmission-openvpn:
        image: haugene/transmission-openvpn:3.3
        hostname: transmission
        container_name: transmission-openvpn
        cap_add:
            - NET_ADMIN
        volumes:
            - '/home/pi/:/data'
        environment:
            - OPENVPN_PROVIDER=PIA
            - OPENVPN_CONFIG=au_melbourne,au_sydney,au_perth
            - OPENVPN_USERNAME=<snip>
            - OPENVPN_PASSWORD=<snip>
            - LOCAL_NETWORK=192.168.0.0/16
            - TZ=Australia/Melbourne
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '9091:9091'
    transmission-rss:
        image: haugene/transmission-rss:dev
        hostname: transmission-rss
        container_name: transmission-rss
        depends_on:
            - transmission-openvpn
        environment:
            - RSS_URL=<snip>
```
