### ISSUE TITLE
Transmission stuck in a loop. PIA related issue?

### ISSUE THREAD

**Issue by mdstoll** [haugene/docker-transmission-openvpn#1683]
**Before creating this issue I have:**

- [x] Searched for [similar issues](https://github.com/haugene/docker-transmission-openvpn/issues)
- [x] [Read the documentation](https://haugene.github.io/docker-transmission-openvpn/). Especially the troubleshooting section
- [x] Tried to add as much relevant information to the issue as possible

**Describe the problem**

In Synology NAS, Docker shows the container keeps 'restarting' and never changes status to 'running'. Looking at the logs, it seems the container is in a loop, probably because the VPN isn't connecting correctly. Not sure how to fix this.
Issue has started to occur after a reboot of my Synology Nas. 

**Docker Run:**
```
docker run
--cap-add=NET_ADMIN
--device=/dev/net/tun
-d
-v /volume1/scripts/transmissionsupport/resolv.conf:/etc/resolv.conf
-v /volume2/downloads/:/data
-e "OPENVPN_PROVIDER=PIA"
-e "OPENVPN_CONFIG=Netherlands"
-e "OPENVPN_USERNAME=censored"
-e "OPENVPN_PASSWORD=censored"
-e "LOCAL_NETWORK=192.168.0.0/24"
-e "OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60"
-e "PGID=100"
-e "PUID=1027"
-e "TRANSMISSION_WEB_UI=transmission-web-control"
-e "TRANSMISSION_BLOCKLIST_ENABLED=true"
-e "TRANSMISSION_BLOCKLIST_URL=http://john.bitsurge.net/public/biglist.p2p.gz"
-e "TRANSMISSION_CACHE_SIZE_MB=16"
-e "TRANSMISSION_DOWNLOAD_QUEUE_SIZE=50"
-e "TRANSMISSION_ENCRYPTION=2"
-e "TRANSMISSION_PEER_LIMIT_GLOBAL=400"
-e "TRANSMISSION_RATIO_LIMIT=5"
-e "TRANSMISSION_RATION_LIMIT_ENABLED=true"
-e "TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true"
-e "TRANSMISSION_RPC_PASSWORD="censored"
-e "TRANSMISSION_RPC_USERNAME="censored""
-e "TRANSMISSION_SPEED_LIMIT_UP=10000"
-e "TRANSMISSION_SPEED_LIMIT_UP_ENABLED=true"
-e "TRANSMISSION_UTP_ENABLED=false"
-e "TRANSMISSION_QUEUE_STALLED_ENABLED=false"
-e "DISABLE_PORT_UPDATER=yes"
-p 9091:9091
--sysctl net.ipv6.conf.all.disable_ipv6=0
--name "transmission-openvpn-syno"
haugene/transmission-openvpn:latest
```

**Logs**
This is in a repetative loop
```
2021-01-21 13:35:51 | stderr | curl: (6) Could not resolve host: www.privateinternetaccess.com
2021-01-21 13:35:46 | stdout | Downloading OpenVPN config bundle openvpn into temporary file /tmp/tmp.ClniHK
2021-01-21 13:35:46 | stdout | Provider PIA has a custom setup script, executing it
2021-01-21 13:35:46 | stdout | Using OpenVPN provider: PIA
2021-01-21 13:35:46 | stderr | mknod: /dev/net/tun: File exists
2021-01-21 13:35:46 | stdout | Creating TUN device /dev/net/tun
2021-01-21 13:35:46 | stdout | Starting container with revision: afdf1acb6a891b93e292e46279ad97bf1c19156b
```

**Host system:**
 ```
Synology NAS DSM 6.2.3-25426 Update 2 [Linux]
 ```

**Comment by raphaeldenis** [comment]
Try OPENVPN_CONFIG with the name of the .ovpn config file as value.
`OPENVPN_CONFIG = se-01.nordvpn.com.udp`

**Comment by mdstoll** [comment]
I've changed the value of OPENVPN_CONFIG to netherlands.ovpn. Double checked this by downloading the archive containing the .ovpn from the PIA website.

Unfortunately, this didn't solve the issue and it still persists as described (same log loop).

Thanks for the suggestion though :)

**Comment by mdstoll** [comment]
What I've got from this .ovpn file, is that they list the server address:
`nl-amsterdam.privacy.network`

Maybe that creates a conflict elsewhere in configuration (maybe it changed)? Can't be sure though, as I don't have an older version of the .ovpn file.

**Comment by goose-ws** [comment]
Also having this issue.

Logs:

```
Starting container with revision: 42d00652323b7b7fbee1689a54219599f4795a04
Creating TUN device /dev/net/tun
Using OpenVPN provider: PIA
Provider PIA has a custom setup script, executing it
Downloading OpenVPN config bundle openvpn into temporary file /tmp/tmp.IIIGpL
Extract OpenVPN config bundle into PIA directory /etc/openvpn/pia
Starting OpenVPN using config sweden.ovpn
Modifying /etc/openvpn/pia/sweden.ovpn for best behaviour in this container
Setting OpenVPN credentials...
adding route to local network 192.168.1.0/24 via 172.20.0.1 dev eth0
adding route to local network 192.168.2.0/24 via 172.20.0.1 dev eth0
adding route to local network 192.168.3.0/24 via 172.20.0.1 dev eth0
Thu Jan 21 09:43:53 2021 OpenVPN 2.4.10 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Jan  4 2021
Thu Jan 21 09:43:53 2021 library versions: OpenSSL 1.1.1i  8 Dec 2020, LZO 2.10
Thu Jan 21 09:43:53 2021 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Thu Jan 21 09:43:53 2021 CRL: loaded 1 CRLs from file [[INLINE]]
Thu Jan 21 09:43:53 2021 TCP/UDP: Preserving recently used remote address: [AF_INET]195.246.120.92:1198
Thu Jan 21 09:43:53 2021 UDP link local: (not bound)
Thu Jan 21 09:43:53 2021 UDP link remote: [AF_INET]195.246.120.92:1198
Thu Jan 21 09:43:54 2021 [stockholm403] Peer Connection Initiated with [AF_INET]195.246.120.92:1198
Thu Jan 21 09:43:55 2021 OpenVPN ROUTE6: OpenVPN needs a gateway parameter for a --route-ipv6 option and no default was specified by either --route-ipv6-gateway or --ifconfig-ipv6 options
Thu Jan 21 09:43:55 2021 OpenVPN ROUTE: failed to parse/resolve route for host/network: 2000::/3
Thu Jan 21 09:43:55 2021 TUN/TAP device tun0 opened
Thu Jan 21 09:43:55 2021 /sbin/ip link set dev tun0 up mtu 1500
Thu Jan 21 09:43:55 2021 /sbin/ip addr add dev tun0 10.17.112.3/24 broadcast 10.17.112.255
Thu Jan 21 09:43:55 2021 /etc/openvpn/tunnelUp.sh tun0 1500 1553 10.17.112.3 255.255.255.0 init
Up script executed with tun0 1500 1553 10.17.112.3 255.255.255.0 init
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.17.112.3
Updating Transmission settings.json with values from env variables
Using existing settings.json for Transmission /config/transmission-home/settings.json
Overriding bind-address-ipv4 because TRANSMISSION_BIND_ADDRESS_IPV4 is set to 10.17.112.3
Overriding download-dir because TRANSMISSION_DOWNLOAD_DIR is set to /data/transmission/complete
Overriding incomplete-dir because TRANSMISSION_INCOMPLETE_DIR is set to /data/transmission/incomplete
Overriding preallocation because TRANSMISSION_PREALLOCATION is set to 0
Overriding rpc-port because TRANSMISSION_RPC_PORT is set to 9091
Overriding watch-dir because TRANSMISSION_WATCH_DIR is set to /config/watch
sed'ing True to true
Enforcing ownership on transmission config directories
Applying permissions to transmission config directories
Setting owner for transmission paths to 1000:1000
Setting permission for files (644) and directories (755)
Setting permission for watch directory (775) and its files (664)

-------------------------------------
Transmission will run as
-------------------------------------
User name:   abc
User uid:    1000
User gid:    1000
-------------------------------------

STARTING TRANSMISSION
Provider PIA has a script for automatic port forwarding. Will run it now.
If you want to disable this, set environment variable DISABLE_PORT_UPDATER=true
Transmission startup script complete.
Thu Jan 21 09:43:55 2021 WARNING: OpenVPN was configured to add an IPv6 route over tun0. However, no IPv6 has been configured for this interface, therefore the route installation may fail or may not work as expected.
Thu Jan 21 09:43:55 2021 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Thu Jan 21 09:43:55 2021 Initialization Sequence Completed
Running functions for token based port fowarding
curl: (6) Could not resolve host: www.privateinternetaccess.com
Thu Jan 21 09:44:07 EST 2021: getSignature error
{ "status": "ERROR", "message": "Login failed!" }
the has been a fatal_error
parse error: Invalid numeric literal at EOF at line 1, column 3
parse error: Invalid numeric literal at EOF at line 1, column 3
date: invalid date ''
Thu Jan 21 09:44:07 EST 2021: bindPort error
{ "status": "", "message": "bad signature" }
the has been a fatal_error
transmission auth not required
waiting for transmission to become responsive
transmission became responsive
     1    n/a       None  Unknown      0.0     0.0   None  Idle         [redacted]
Sum:                None               0.0     0.0
setting transmission port to
localhost:9091/transmission/rpc/ responded: "success"
Checking port...
Error: portTested: http error 0: No Response
date: invalid date '@'
#######################
        SUCCESS
#######################
Port:
Expiration
#######################
Entering infinite while loop
Every 15 minutes, check port status
60 day port reservation reached
Getting a new one
```

Container properties, formatted in compose:

```
version: '3.3'
services:
    etc:
        container_name: transmissionvpn
        environment:
            - 'LOCAL_NETWORK=192.168.1.0/24,192.168.2.0/24,192.168.3.0/24'
            - CREATE_TUN_DEVICE=true
            - TZ=America/New_York
            - OPENVPN_CONFIG=sweden
            - OPENVPN_USERNAME=[redacted]
            - OPENVPN_PASSWORD=[redcated]
            - OPENVPN_PROVIDER=PIA
            - TRANSMISSION_RATIO_LIMIT_ENABLED=true
            - TRANSMISSION_RATIO_LIMIT=0
            - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
            - GLOBAL_APPLY_PERMISSIONS=true
            - TRANSMISSION_HOME=/config/transmission-home
            - TRANSMISSION_RPC_PORT=9091
            - TRANSMISSION_DOWNLOAD_DIR=/data/transmission/complete
            - TRANSMISSION_INCOMPLETE_DIR=/data/transmission/incomplete
            - ENABLE_UFW=false
            - UFW_ALLOW_GW_NET=false
            - UFW_DISABLE_IPTABLES_REJECT=false
            - PUID=1000
            - PGID=1000
            - WEBPROXY_ENABLED=false
            - WEBPROXY_PORT=8888
            - LOG_TO_STDOUT=false
            - HEALTH_CHECK_HOST=google.com
            - REVISION=42d00652323b7b7fbee1689a54219599f4795a04
            - TRANSMISSION_PREALLOCATION=0
            - TRANSMISSION_WATCH_DIR=/config/watch
            - UFW_EXTRA_PORTS=
            - DROP_DEFAULT_ROUTE=
            - WEBPROXY_USERNAME=
            - WEBPROXY_PASSWORD=
        volumes:
            - '/docker/config/transmissionvpn:/config'
            - '/download:/data'
            - '/etc/localtime:/etc/localtime:ro'
        network_mode: VergilNet
        ports:
            - '8050:9091'
        restart: unless-stopped
        labels:
            - com.ouroboros.enable=true
            - autoheal=true
        logging:
            options: 'max-file=3,max-size=10m'
        image: /etc/openvpn/start.sh
```

**Comment by kornflex** [comment]
Hello same problem for me:

`Using OpenVPN provider: PIA
Provider PIA has a custom setup script, executing it
Downloading OpenVPN config bundle openvpn into temporary file /tmp/tmp.IAlDDG
curl: (6) Could not resolve host: www.privateinternetaccess.com
Starting container with revision: afdf1acb6a891b93e292e46279ad97bf1c19156b
Creating TUN device /dev/net/tun
mknod: /dev/net/tun: File exists`

**Comment by iFredOS** [comment]
I'm happy to see I'm not alone with this issue. I spend to much time to investigate what is the problem. No solution. I have the same kind of log @mdstoll added. The only thing I can presume the file downloaded is not good.

**Comment by mikeymasonic** [comment]
just putting this out there in case it helps anyone.  I was having various issues with PIA including this one.  I started with a a fresh dev image and added the following to make it work, ymmv:

```
OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60 --pull-filter ignore ping
```
override dns server to PIA's dns servers
```
OVERRIDE_DNS_1=209.222.18.222
OVERRIDE_DNS_2=209.222.18.218
```

A few interesting notes: when I started my container with this configuration, I had no weird error messages (bad request, etc).  Only 1 of four torrents started downloading.  That one torrent finished, the rest sat there.  Stopped and started the container, one torrent started and finished.  Added another torrent while the one torrent was downloading, it started, but there was another torrent in there that _should_ have started, after a few minutes, that torrent started up.

I got rid of OPENVPN_CONFIG and just let the container choose a server, if I had OPENVPN_CONFIG in my env, I would get errors, I tried 'us_seattle' and 'us_california', neither worked well.

I'm using the latest dev build as of 01-21-2021.  hope this helps someone out there!

**Comment by pkishino** [comment]
yeah, this looks dns related..please specify dns explicitly for now until we can work out a way for default to work

**Comment by mdstoll** [comment]
Just adding 

```
OVERRIDE_DNS_1=209.222.18.222
OVERRIDE_DNS_2=209.222.18.218

```

Without the OPENVPN_OPTS changes made the container work again. I'm not really happy about using PIAs own DNS as my experience is that they are really slow. But it's a solution for now. Thanks for sharing mate!

**Comment by pkishino** [comment]
you can set any dns there afaik

**Comment by d4real** [comment]
> 
> 
> just putting this out there in case it helps anyone. I was having various issues with PIA including this one. I started with a a fresh dev image and added the following to make it work, ymmv:
> 
> ```
> OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60 --pull-filter ignore ping
> ```
> 
> override dns server to PIA's dns servers
> 
> ```
> OVERRIDE_DNS_1=209.222.18.222
> OVERRIDE_DNS_2=209.222.18.218
> ```
> 
> A few interesting notes: when I started my container with this configuration, I had no weird error messages (bad request, etc). Only 1 of four torrents started downloading. That one torrent finished, the rest sat there. Stopped and started the container, one torrent started and finished. Added another torrent while the one torrent was downloading, it started, but there was another torrent in there that _should_ have started, after a few minutes, that torrent started up.
> 
> I got rid of OPENVPN_CONFIG and just let the container choose a server, if I had OPENVPN_CONFIG in my env, I would get errors, I tried 'us_seattle' and 'us_california', neither worked well.
> 
> I'm using the latest dev build as of 01-21-2021. hope this helps someone out there!

How are you pulling the dev image for the container?  Is that set in the docker compose .yml file config?

**Comment by Vader699** [comment]
I was experiencing the same issue and none of the suggestions worked for me.  I found in another issue that someone changed the OPENVPN_CONFIG to ca_ontario to fix the issue.  I tried this out and it worked for me.  According to that person, PIA's US servers don't allow port forwarding which is potentially causing this issue.  

This is the issue I found this suggestion in.  https://github.com/haugene/docker-transmission-openvpn/issues/1569

**Comment by mikeymasonic** [comment]
@d4real, I'm personally using the synology docker gui and downloading the dev image from there, I'm not sure about the .yml file config as I'm going about this differently.  sorry I couldn't be of more help!

**Comment by TheRijn** [comment]
> Just adding
> 
> ```
> OVERRIDE_DNS_1=209.222.18.222
> OVERRIDE_DNS_2=209.222.18.218
> ```
> 
> Without the OPENVPN_OPTS changes made the container work again. I'm not really happy about using PIAs own DNS as my experience is that they are really slow. But it's a solution for now. Thanks for sharing mate!

Can confirm this works. I'm running on a Synology with docker-compose:

```yaml
  transmission:
    image: haugene/transmission-openvpn
    container_name: transmission
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - /volume2/downloads:/data
      - /volume2/docker/mm/transmission/resolv.conf:/etc/resolv.conf
    environment:
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_CONFIG=de_frankfurt
      - OPENVPN_USERNAME=nope
      - OPENVPN_PASSWORD=nope
      - PUID=1039
      - PGID=101
      - LOCAL_NETWORK=10.0.0.0/24
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - TRANSMISSION_RPC_PASSWORD=nope
      - TRANSMISSION_RPC_USERNAME=nope
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      - TRANSMISSION_DOWNLOAD_QUEUE_ENABLED=true
      - TRANSMISSION_DOWNLOAD_QUEUE_SIZE=20
      - TRANSMISSION_RATIO_LIMIT=2
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
      - OVERRIDE_DNS_1=209.222.18.222
      - OVERRIDE_DNS_2=209.222.18.218 
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    ports:
      - 9091:9091
    restart: unless-stopped
```

The `OPENVPN_OPTS` were already there 🤷🏼‍♂️ Can't remember why, maybe commenting my compose files would be a good idea.
