### ISSUE TITLE
Flood UI

### ISSUE THREAD

**Issue by mouzzampk2014** [haugene/docker-transmission-openvpn#1701]
Hi, I had `combustion` and was working fine but then few days ago I changed it to `flood` but now its set to default `transmission` theme. I tried on three different browsers and on my mobile but same UI. Thanks

Here is my compose and I am pretty sure I am missing something
```
  transmissionvpn:
    image: haugene/transmission-openvpn:dev
    hostname: ${DOCKERHOSTNAME}
    ports:
      - 51413:51413
      - 51413:51413/udp
      - 6881:6881
      - 6881:6881/udp
      - 9091:9091
      - 8888:8888
    cap_add:
      - NET_ADMIN
    container_name: transmissionvpn
    dns:
      - ${NS1}
      - ${NS2}
    environment:
      - LOCAL_NETWORK=${LAN_NETWORK}
      - TRANSMISSION_WEB_UI=flood
      - OPENVPN_OPTS=${VPN_OPTIONS}
      - OPENVPN_PASSWORD=${VPN_PASS}
      - OPENVPN_PROVIDER=${VPN_PROV}
      - OPENVPN_USERNAME=${VPN_USER}
      - PGID=${PGID}
      - PUID=${PUID}
      - WEBPROXY_ENABLED=true
      - WEBPROXY_PORT=8888
      - TRANSMISSION_DOWNLOAD_DIR=/storage/downloads
      - TRANSMISSION_HOME=/config
      - TRANSMISSION_INCOMPLETE_DIR=/storage/downloads
      - TRANSMISSION_WATCH_DIR=/storage/downloads
      - TZ=${TZ}
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/transmissionvpn:/config
      - ${DOCKERSTORAGEDIR}:/storage
      - ${VPN_OVPNDIR}:/config/openvpn
      - ${VPN_OVPNDIR}:/etc/openvpn/custom/
```
