### ISSUE TITLE
VPN not connecting and no Web UI

### ISSUE THREAD

**Issue by SpectralYeti** [haugene/docker-transmission-openvpn#1705]
**Before creating this issue I have:**

- [x] Searched for [similar issues](https://github.com/haugene/docker-transmission-openvpn/issues)
- [X] [Read the documentation](https://haugene.github.io/docker-transmission-openvpn/). Especially the troubleshooting section
- [] Tried to add as much relevant information to the issue as possible

**Describe the problem**
Unable to connect to OpenVPN at all, and using both Torguard and NordVPN does not let me connect to anything. I've looked up about the "Host Unresolved" and seen that it's an issue with the DNS, so I've tried both Google DNS and 1.1.1.1, but neither have worked. Also the Web UI doesn't want to load either, so I'm completely lost.

I used a similar portainer compose file a few months ago with a different router, and it was fine. Now after an internet upgrade and a new router, it doesn't want to work at all. 

(I will also say, I'm fairly new to Linux, and have no skill with programming bar following instructions on various websites. I'm also used to using docker through portainer, so if that's an issue or that's the reason  I'm doing it wrong, give me a heads-up)
**Add your docker run command or docker-compose file**

 
 ```
 ---
version: "2"
services:
  transmission-openvpn:
    image: haugene/transmission-openvpn:latest
    container_name: transmission-openvpn-syno
    restart: always
    cap_add:
      - NET_ADMIN # This runs the container with raised privileges
    devices:
      - /dev/net/tun # This creates a tunnel for Transmission
    volumes:
      - /srv/dev-disk-by-uuid-068f6d91-0512-496c-8673-b1d814b8d691/DocsAndData/Torrents:/data # Change this to your Torrent path
    environment:
      - OPENVPN_PROVIDER=Torguard # Or other compatible OpenVPN provider
      - OPENVPN_CONFIG=UK.London # Or other region that supports port forwarding. Check with your VPN provider
      - OPENVPN_USERNAME=******* # VPN provider username
      - OPENVPN_PASSWORD=******* # VPN provider password
      - LOCAL_NETWORK=192.168.1.0/24 # If your server's IP address is 192.168.1.x, then use this. If your server's IP address is 192.168.0.x, then change to 192.168.0.0/24
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60 # Leave this as is
      - PUID=1000 #Change to your PUID
      - PGID=100 #Change to your PGID
    ports:
      - 9091:9091 #GUI Port
      - 8888:8888 #Transmission Port
    dns:
      - 8.8.8.8 #Use whatever DNS provider you want. This is Google.
      - 8.8.4.4 #Use whatever DNS provider you want. This is Google.
 ```

**Logs**
Starting container with revision: f13eb3e908521a5d0f7a51e965fd5ad028e4ab49
Creating TUN device /dev/net/tun
mknod: /dev/net/tun: File exists
Using OpenVPN provider: TORGUARD
Starting OpenVPN using config UK.London.ovpn
Setting OpenVPN credentials...
Fatal Python error: pyinit_main: can't initialize time
Python runtime state: core initialized
PermissionError: [Errno 1] Operation not permitted
Current thread 0xb6f12390 (most recent call first):
<no Python frame>
adding route to local network 192.168.1.0/24 via 172.28.0.1 dev eth0
2071-05-26 09:01:36 DEPRECATED OPTION: ncp-disable. Disabling cipher negotiation is a deprecated debug feature that will be removed in OpenVPN 2.6
2071-05-26 10:03:20 OpenVPN 2.5.0 armv7-alpine-linux-musleabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Dec 26 2020
2071-05-26 10:02:56 library versions: OpenSSL 1.1.1i  8 Dec 2020, LZO 2.10
2071-05-26 10:00:16 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
2071-05-26 09:39:28 Outgoing Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC authentication
2071-05-26 09:39:28 Incoming Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC authentication
2071-05-26 09:56:40 RESOLVE: Cannot resolve host address: uk.torguard.com:1912 (Try again)
2071-05-26 09:54:32 RESOLVE: Cannot resolve host address: uk.torguard.com:1912 (Try again)
2071-05-26 09:58:08 Could not determine IPv4/IPv6 protocol
2071-05-26 10:02:48 SIGUSR1[soft,init_instance] received, process restarting
2071-05-26 10:00:16 Restart pause, 5 second(s)

**Host system:**

 ```
RaspberryPi 4 (4GB) - OMV5 - Portainer  
 ```
