### ISSUE TITLE
Container not starting with macvlan network

### ISSUE THREAD

**Issue by JoeTN** [haugene/docker-transmission-openvpn#1707]
**Before creating this issue I have:**

- [x] Searched for [similar issues](https://github.com/haugene/docker-transmission-openvpn/issues)
- [x] [Read the documentation](https://haugene.github.io/docker-transmission-openvpn/). Especially the troubleshooting section
- [x] Tried to add as much relevant information to the issue as possible

**Describe the problem**

When using my macvlan0 network, the container stops right after it is started. If I comment out the macvlan0 network to use the bridge-network it starts fine. I have been running an older version of this container with macvlan-network before (on another host), which worked fine.

**Add your docker run command or docker-compose file**

 
 ```
version: '3.3'
services:
    transmission-openvpn:
        container_name: Transmission
        cap_add:
            - NET_ADMIN
        devices:
            - /dev/net/tun
        volumes:
            - '/mnt/744fa3d8-4c42-44fb-90a4-1cec0422ab15/data/containers/transmission/:/data'
        environment:
            - OPENVPN_PROVIDER=PIA
            - OPENVPN_CONFIG=france
            - OPENVPN_USERNAME=user
            - OPENVPN_PASSWORD=pass
            - LOCAL_NETWORK=192.168.10.0/24
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '9091:9091'
        image: haugene/transmission-openvpn
        networks:
          macvlan0:
            ipv4_address: 192.168.10.108
networks:
  macvlan0:
    external: true
 ```

**Logs**

 ```
 Starting container with revision: f13eb3e908521a5d0f7a51e965fd5ad028e4ab49
Creating TUN device /dev/net/tun
mknod: /dev/net/tun: File exists
Using OpenVPN provider: PIA
Provider PIA has a custom setup script, executing it
Downloading OpenVPN config bundle openvpn into temporary file /tmp/tmp.JDFMik
Extract OpenVPN config bundle into PIA directory /etc/openvpn/pia
Starting OpenVPN using config france.ovpn
Modifying /etc/openvpn/pia/france.ovpn for best behaviour in this container
Setting OpenVPN credentials...
adding route to local network 192.168.10.0/24 via 192.168.10.1 dev eth0
RTNETLINK answers: File exists
 ```

**Host system:**

 ```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 3
  Running: 2
  Paused: 0
  Stopped: 1
 Images: 6
 Server Version: 20.10.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: ep352wn91zywbpdaob48ie5aa
  Is Manager: true
  ClusterID: ackfwdy77zehmvgy1r34s8ci2
  Managers: 1
  Nodes: 1
  Default Address Pool: 10.0.0.0/8  
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 192.168.10.95
  Manager Addresses:
   192.168.10.95:2377
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.8.0-41-generic
 Operating System: Ubuntu 20.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 5.806GiB
 Name: ContainerHost01
 ID: VNHR:XYCT:LEDZ:YMO4:YCVI:73NE:JQ47:VWOT:65OK:WJLB:3QUY:4A3W
 Docker Root Dir: /mnt/744fa3d8-4c42-44fb-90a4-1cec0422ab15/data/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false ```
