### ISSUE TITLE
Docker compose clean up

### ISSUE THREAD

**Issue by mouzzampk2014** [haugene/docker-transmission-openvpn#1716]
**Before creating this issue I have:**

- [X] Searched for [similar issues](https://github.com/haugene/docker-transmission-openvpn/issues)
- [X] [Read the documentation](https://haugene.github.io/docker-transmission-openvpn/) to a reasonable degree

**Describe your request**
Hi, its me again but this time how to clean my compose :). As from your previous comment I removed these ports from compose because these can be managed through my VPN provider.
```
      - 51413:51413
      - 51413:51413/udp
      - 6881:6881
      - 6881:6881/udp
```
But not sure is there anything else I need to remove from environment variables. Like these
```
      - TRANSMISSION_DOWNLOAD_DIR=/storage/downloads
      - TRANSMISSION_HOME=/config
      - TRANSMISSION_INCOMPLETE_DIR=/storage/downloads
      - TRANSMISSION_WATCH_DIR=/storage/downloads
```

**Contextual information**
```
    image: haugene/transmission-openvpn:dev
    hostname: ${DOCKERHOSTNAME}
    ports:
      - 51413:51413
      - 51413:51413/udp
      - 6881:6881
      - 6881:6881/udp
      - 9091:9091
      - 8888:8888
    cap_add:
      - NET_ADMIN
    container_name: transmissionvpn
    dns:
      - ${NS1}
      - ${NS2}
    environment:
      - LOCAL_NETWORK=${LAN_NETWORK}
      - TRANSMISSION_WEB_UI=flood
      - OPENVPN_OPTS=${VPN_OPTIONS}
      - OPENVPN_PASSWORD=${VPN_PASS}
      - OPENVPN_PROVIDER=${VPN_PROV}
      - OPENVPN_USERNAME=${VPN_USER}
      - PGID=${PGID}
      - PUID=${PUID}
      - WEBPROXY_ENABLED=true
      - WEBPROXY_PORT=8888
      - TRANSMISSION_DOWNLOAD_DIR=/storage/downloads
      - TRANSMISSION_HOME=/config
      - TRANSMISSION_INCOMPLETE_DIR=/storage/downloads
      - TRANSMISSION_WATCH_DIR=/storage/downloads
      - TZ=${TZ}
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/transmissionvpn:/config
      - ${DOCKERSTORAGEDIR}:/storage
      - ${VPN_OVPNDIR}:/config/openvpn
      - ${VPN_OVPNDIR}:/etc/openvpn/custom/
```
