### ISSUE TITLE
Cannot access Transmission from WAN

### ISSUE THREAD

**Issue by derekcentrico** [haugene/docker-transmission-openvpn#1720]
**Before creating this issue I have:**

- [ X] Searched for [similar issues](https://github.com/haugene/docker-transmission-openvpn/issues)
- [ X] [Read the documentation](https://haugene.github.io/docker-transmission-openvpn/) to a reasonable degree

**Describe your request**

I'm learning docker and converting my old setup over.  So far so good with one hiccup:  I cannot access Transmission from WAN anymore.  Port is forwarded still.  It just spins until it times out.  I believe I setup the container fine as it certainly forwards incoming LAN traffic to the container as I can access the WEBUI with no issue from LAN.  I reviewed some other requests here and I seem to have the same configuration so I don't know what's off.

**Contextual information**

Here's the container file:

```
  transmission-vpn:
    container_name: transmission-vpn
    hostname: transmission
    image: haugene/transmission-openvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: always
    ports:
    - "9091:9091"
    dns:
      - 1.1.1.1
      - 8.8.8.8
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - REDACTED:/data/completed/tvshows
      - REDACTED/DockerDownloads/Watch:/data/watch
      - REDACTED/Incomplete:/data/incomplete
      - ${USERDIR}/docker/shared:/shared
    environment:
      - OPENVPN_PROVIDER=NORDVPN
      - OPENVPN_USERNAME=REDACTED
      - OPENVPN_PASSWORD=REDACTED
      - NORDVPN_CATEGORY=legacy_p2p
      - NORDVPN_COUNTRY=US
      - NORDVPN_PROTOCOL=udp
      - OPENVPN_OPTS=--inactive 3600 --ping 15 --ping-exit 60
      - LOCAL_NETWORK=192.168.1.0/24
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      - TRANSMISSION_RPC_HOST_WHITELIST="*.*.*.*"
      - TRANSMISSION_RPC_PASSWORD=REDACTEDHASH
      - TRANSMISSION_RPC_USERNAME=admin
      - TRANSMISSION_UMASK=002
      - TRANSMISSION_RATIO_LIMIT=0
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
      - TRANSMISSION_SEED_QUEUE_ENABLED=true
      - TRANSMISSION_SEED_QUEUE_SIZE=1
      - TRANSMISSION_TRASH_ORIGINAL_TORRENT_FILES=true
      - TRANSMISSION_ADDED_TORRENTS=true
      - TRANSMISSION_BLOCKLIST_URL="REDACTED"
      - TRANSMISSION_BLOCKLIST_ENABLED=true
      - TRANSMISSION_BLOCKLIST_UPDATES_ENABLED=true
      - TRANSMISSION_ENCRYPTION=2
      - TRANSMISSION_UTP_ENABLED=true
      - TRANSMISSION_DHT_ENABLED=true
      - TRANSMISSION_PEX_ENABLED=true
      - TRANSMISSION_INCOMPLETE_DIR=/data/incomplete
      - TRANSMISSION_INCOMPLETE_DIR_ENABLED=true
      - TRANSMISSION_WATCH_DIR=/data/watch
      - TRANSMISSION_WATCH_DIR_ENABLED=true
      - TRANSMISSION_DOWNLOAD_DIR=/data/completed/tvshows
      - TRANSMISSION_ALT_SPEED_DOWN=5000
      - TRANSMISSION_ALT_SPEED_ENABLED=true
      - TRANSMISSION_ALT_SPEED_UP=2
      - TRANSMISSION_ALT_SPEED_TIME_BEGIN=1360
      - TRANSMISSION_ALT_SPEED_TIME_DAY=127
      - TRANSMISSION_ALT_SPEED_TIME_ENABLED=true
      - TRANSMISSION_ALT_SPEED_TIME_END=540
      - TRANSMISSION_SPEED_LIMIT_DOWN=4000
      - TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED=true
      - TRANSMISSION_SPEED_LIMIT_UP=1
      - TRANSMISSION_SPEED_LIMIT_UP_ENABLED=true
```

Any input on what is wrong, or if my expectations are just not correct, would be much appreciated.  I'm a container newbie here.  Thanks.
