### ISSUE TITLE
DNS error when trying to connect with PIA

### ISSUE THREAD

**Issue by Syferus** [haugene/docker-transmission-openvpn#1722]
**Before creating this issue I have:**

- [X] Searched for [similar issues](https://github.com/haugene/docker-transmission-openvpn/issues)
- [X] [Read the documentation](https://haugene.github.io/docker-transmission-openvpn/). Especially the troubleshooting section
- [X] Tried to add as much relevant information to the issue as possible

**Describe the problem**
I've tried this with `PIA_OPENVPN_CONFIG_BUNDLE=openvpn-ip-nextgen` and `PIA_OPENVPN_CONFIG_BUNDLE=openvpn-tcp` and with different config locations as suggested in other threads (https://github.com/haugene/docker-transmission-openvpn/issues/1507) to no avail. I'm not sure what is causing this. It could be user error but all the issues I've found with changes to PIA in recent months just adds to my confusion.

**Add your docker run command or docker-compose file**

 
 ```
version: '2.1'
services:
 transmission-openvpn:
    volumes:
        - /srv/dev-disk-by-label-data/media/downloads:/media/downloads
        - /etc/localtime:/etc/localtime:ro
    environment:
        - PUID=1000
        - PGID=1000
        - CREATE_TUN_DEVICE=true
        - OPENVPN_PROVIDER=PIA
        - OPENVPN_CONFIG=spain
        - OPENVPN_USERNAME=p******
        - OPENVPN_PASSWORD=******
        - PIA_OPENVPN_CONFIG_BUNDLE=openvpn-ip-nextgen
        - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
        - WEBPROXY_ENABLED=false
        - LOCAL_NETWORK=192.168.68.0/24
        - TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=false
        - DNS=8.8.8.8,8.8.4.4
    cap_add:
        - NET_ADMIN
    logging:
        driver: json-file
        options:
            max-size: 10m
    ports:
        - 9091:9091
        - 9117:9117
        - 7878:7878
        - 8989:8989
        - 8686:8686
        - 5299:5299
    restart: always
    image: haugene/transmission-openvpn:latest
 
 jackett:
    image: linuxserver/jackett
    container_name: jackett
    network_mode: "service:transmission-openvpn"
    environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/London
        - AUTO_UPDATE=true #optional
        - RUN_OPTS=#optional
    volumes:
        - /srv/dev-disk-by-label-data/appdata/jackett:/config
        #Jackett only needs config
    restart: unless-stopped
 
 radarr:
    image: linuxserver/radarr
    network_mode: "service:transmission-openvpn"
    container_name: radarr
    environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/London
        - UMASK_SET=022 #optional
    volumes:
        - /srv/dev-disk-by-label-data/appdata/radarr:/config
        - /srv/dev-disk-by-label-data/media:/media
    restart: unless-stopped
 
 sonarr:
    image: linuxserver/sonarr
    network_mode: "service:transmission-openvpn"
    container_name: sonarr
    environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/London
        - UMASK_SET=022 #optional
    volumes:
        - /srv/dev-disk-by-label-data/appdata/sonarr:/config
        - /srv/dev-disk-by-label-data/media/:/media
    restart: unless-stopped
 
 lidarr:
    image: linuxserver/lidarr
    network_mode: "service:transmission-openvpn"
    container_name: lidarr
    environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/London
        - UMASK_SET=022 #optional
    volumes:
        - /srv/dev-disk-by-label-data/appdata/lidarr:/config
        - /srv/dev-disk-by-label-data/media/:/media
    restart: unless-stopped
 
 lazylibrarian:
    image: linuxserver/lazylibrarian
    network_mode: "service:transmission-openvpn"
    container_name: lazylibrarian
    environment:
        - PUID=1000
        - PGID=1000
         - TZ=Europe/London
        #- DOCKER_MODS=linuxserver/calibre-web:calibre #optional
    volumes:
        - /srv/dev-disk-by-label-data/appdata/lazylibrarian:/config
        - /srv/dev-disk-by-label-data/media/:/media
    restart: unless-stopped
 ```

**Logs**

 ```
Starting container with revision: 6ce64c4f367e509cbf018296e170cd08c0a93319


WARNING: initial DNS resolution test failed


Creating TUN device /dev/net/tun


Using OpenVPN provider: PIA


Provider PIA has a custom setup script, executing it


Downloading OpenVPN config bundle openvpn into temporary file /tmp/tmp.CCIndF


curl: (6) Could not resolve host: www.privateinternetaccess.com
 ```

**Host system:**

 ```
RPi4/OMV5/Portainer 2.0.0
 ```
