### ISSUE TITLE
Torguard does not work

### ISSUE THREAD

**Issue by drgroot** [haugene/docker-transmission-openvpn#173]
error:
```
docker logs transmission
Could not find OpenVPN provider: "TORGUARD"
Please check your settings.
```

Docker compose file:
```
transmission:
    container_name: transmission
    image: haugene/transmission-openvpn
    env_file: docker.env
    privileged: true
    environment:
      - OPENVPN_PROVIDER="TORGUARD"
      - OPENVPN_CONFIG="Canada Toronto"
      - OPENVPN_USERNAME=""
      - OPENVPN_PASSWORD=""
      - LOCAL_NETWORK="198.12.82.0/24"
    ports:
      - "9091:9091"
```
