### ISSUE TITLE
Reverse proxy of other services (Sonarr, Radarr, etc.) connected to the docker-transmission-openvpn network

### ISSUE THREAD

**Issue by garret** [haugene/docker-transmission-openvpn#1737]
I have connected other containers (Sonarr, Radarr, etc...) to the `docker-transmission-openvpn` container by using the `--network container:transmission-openvpn` option. Everything works, thus all the containers are also under the vpn network. 

However, I would like to access also their web interface outside my local network. I have been using the `haugene/transmission-openvpn-proxy` image to get the transmission web interface to be accessible from outside. That works, but what if I also want to add the other services (Sonarr, Radarr, etc...)? 

May I ask for some help in how to modify the `nginx.conf` present in https://github.com/haugene/docker-transmission-openvpn/tree/master/proxy so that I could build my own image of the proxy?

**Comment by pkishino** [comment]
To be honest, for accessing any of my internal interfaces I went away from opening it up and instead closed down everything and setup WireGuard server in my local and only my setup devices can now access everything from everywhere as if they were local, it’s just more secure and simple

**Comment by garret** [comment]
@pkishino I agree, I had also actually set up a wireguard instance which was working as you mention. However, I recently moved to a new place where port forwarding is not possible and, thus, don't have the possibility to set up a wireguard server. To circumvent the problem I am using [ZeroTier](https://www.zerotier.com/) (for those who don't know what it is, it is just a solution like Hamachi for those _old_ people who remember it).

**Comment by pkishino** [comment]
had a quick look and should be simple if you google nginx config etc.. you would need to create new locations for the different services you want to use, that should be all and then rebuild locally. Will close for now..
if you get it working feel free to submit a PR that would update and allow other services as well

**Comment by garret** [comment]
@pkishino as I wrote before, I have always found this nginx stuff quite difficult to understand. I ended up solving by using ZeroTier as mentioned above. Hope someone will update with a more elegant solution anytime in the future.

**Comment by garret** [comment]
Sorry, I reopen this topic as only now I am finally having time to play around. I have `transmission-openvpn` and `sonarr `(from linuxserver on standard port `8989`) that share the same network (so sonarr is also behind vpn too). I also started the `transmission-proxy` container to be able to access such container from "outside". 

This is an extract of my docker-compose file (removed some not-needed lines to make it simpler): 

```
version: '3'
services:
    transmission:
        container_name: transmission
        cap_add:
            - NET_ADMIN
[...]
# Ports disabled as I will have them enabled in the proxy to access from outside
#        ports:
#            - 9091:9091 #Transmission
#            - 8989:8989 #Sonarr
# ipv6 must be disabled for Mullvad to work
        sysctls:
            - "net.ipv6.conf.all.disable_ipv6=0"
        logging:
            driver: json-file
            options:
                max-size: 10m
        restart: unless-stopped
        image: haugene/transmission-openvpn

    transmission-proxy:
        container_name: transmission-proxy
        volumes:
            - ${CONFIG_FOLDER}/transmission-proxy/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 9091:9091 #Transmission
            - 8989:8989 #Sonarr
        links:
            - transmission:transmission
        restart: unless-stopped
        image: haugene/transmission-openvpn-proxy

    sonarr:
        container_name: sonarr
[...]
        network_mode: 'service:transmission'
        depends_on:
            - transmission
        restart: unless-stopped
        image: ghcr.io/linuxserver/sonarr
```

And this is the `nginx.conf` file from the transmission-proxy: 

```
events {
  worker_connections 1024;
}

http {

  # In case of big files
  client_max_body_size 200M;

  server {
    listen 9091;

    location / {
      proxy_pass http://transmission:9091;
      proxy_set_header Host $http_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;

      # HTTP 1.1 support
      proxy_http_version 1.1;
      proxy_set_header Connection "";
    }
    location /sonarr {
      proxy_pass http://transmission:8989;
      proxy_set_header Host $http_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;

      # HTTP 1.1 support
      proxy_http_version 1.1;
      proxy_set_header Connection "";
    }
  }

}
```

I am able to access transmission through the `9091` port but I am not able to see Sonarr (on port `8989`). Can you help me understanding what I am doing wrong?
