### ISSUE TITLE
fastest vpn on docker on omv5 on rasp pi 4 doesnot work

### ISSUE THREAD

**Issue by bijfy** [haugene/docker-transmission-openvpn#1777]
its not working even on fresh built of os on rpi 4

```
version: '2.1'
services:
    transmission-openvpn:
        volumes:
            - /srv/dev-disk-by-uuid-72ea88d2-a4d3-4953-8d27-2c90e5670cb5/kingston/completed:/data
            - /etc/localtime:/etc/localtime:ro
        environment:
            - PUID=998
            - PGID=100
            - CREATE_TUN_DEVICE=true
            - OPENVPN_PROVIDER=FASTESTVPN
            - OPENVPN_CONFIG=France-UDP
            - OPENVPN_USERNAME=xxxxxxxx@gmail.com
            - OPENVPN_PASSWORD=12345678
            - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
            - WEBPROXY_ENABLED=false
            - LOCAL_NETWORK=192.168.1.0/24
            - TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=false
            
        cap_add:
            - NET_ADMIN
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - 9091:9091
        dns:
            - 1.1.1.1
            - 1.0.0.1
        restart: always
        image: haugene/transmission-openvpn:dev
```

      
```
./etc/openvpn/fetch-external-configs.sh: line 16: config_repo_temp_dir: unbound variable


Supplied config France-UDP.ovpn could not be found.


Your options for this provider are:


NB: Remember to not specify .ovpn as part of the config name.


Starting container with revision: 1221d7cee35a228a09254880f107c80ba8ef26f1


WARNING: initial DNS resolution test failed


Creating TUN device /dev/net/tun


Using OpenVPN provider: FASTESTVPN


Running with VPN_CONFIG_SOURCE auto


No bundled config script found for FASTESTVPN. Defaulting to external config


Downloading configs from https://github.com/haugene/vpn-configs-contrib/archive/main.zip into /tmp/tmp.GCfmdf


curl: (28) Failed to connect to github.com port 443: Operation timed out


./etc/openvpn/fetch-external-configs.sh: line 16: config_repo_temp_dir: unbound variable


Supplied config France-UDP.ovpn could not be found.


Your options for this provider are:


NB: Remember to not specify .ovpn as part of the config name.


Starting container with revision: 1221d7cee35a228a09254880f107c80ba8ef26f1


WARNING: initial DNS resolution test failed


Creating TUN device /dev/net/tun


Using OpenVPN provider: FASTESTVPN


Running with VPN_CONFIG_SOURCE auto


No bundled config script found for FASTESTVPN. Defaulting to external config


Downloading configs from https://github.com/haugene/vpn-configs-contrib/archive/main.zip into /tmp/tmp.Gcnidf


curl: (6) Could not resolve host: github.com


./etc/openvpn/fetch-external-configs.sh: line 16: config_repo_temp_dir: unbound variable


Supplied config France-UDP.ovpn could not be found.


Your options for this provider are:


NB: Remember to not specify .ovpn as part of the config name.


Starting container with revision: 1221d7cee35a228a09254880f107c80ba8ef26f1


WARNING: initial DNS resolution test failed


Creating TUN device /dev/net/tun


Using OpenVPN provider: FASTESTVPN


Running with VPN_CONFIG_SOURCE auto


No bundled config script found for FASTESTVPN. Defaulting to external config


Downloading configs from https://github.com/haugene/vpn-configs-contrib/archive/main.zip into /tmp/tmp.Gcdkdf


curl: (6) Could not resolve host: github.com


./etc/openvpn/fetch-external-configs.sh: line 16: config_repo_temp_dir: unbound variable


Supplied config France-UDP.ovpn could not be found.


Your options for this provider are:


NB: Remember to not specify .ovpn as part of the config name.


Starting container with revision: 1221d7cee35a228a09254880f107c80ba8ef26f1


WARNING: initial DNS resolution test failed


Creating TUN device /dev/net/tun


Using OpenVPN provider: FASTESTVPN


Running with VPN_CONFIG_SOURCE auto


No bundled config script found for FASTESTVPN. Defaulting to external config


Downloading configs from https://github.com/haugene/vpn-configs-contrib/archive/main.zip into /tmp/tmp.GKogaf


curl: (28) Failed to connect to github.com port 443: Operation timed out


./etc/openvpn/fetch-external-configs.sh: line 16: config_repo_temp_dir: unbound variable


Supplied config France-UDP.ovpn could not be found.


Your options for this provider are:


NB: Remember to not specify .ovpn as part of the config name.


Starting container with revision: 1221d7cee35a228a09254880f107c80ba8ef26f1


WARNING: initial DNS resolution test failed


Creating TUN device /dev/net/tun


Using OpenVPN provider: FASTESTVPN


Running with VPN_CONFIG_SOURCE auto


No bundled config script found for FASTESTVPN. Defaulting to external config


Downloading configs from https://github.com/haugene/vpn-configs-contrib/archive/main.zip into /tmp/tmp.GKoNdf


curl: (6) Could not resolve host: github.com


./etc/openvpn/fetch-external-configs.sh: line 16: config_repo_temp_dir: unbound variable


Supplied config France-UDP.ovpn could not be found.


Your options for this provider are:


NB: Remember to not specify .ovpn as part of the config name.


Starting container with revision: 1221d7cee35a228a09254880f107c80ba8ef26f1


WARNING: initial DNS resolution test failed


Creating TUN device /dev/net/tun


Using OpenVPN provider: FASTESTVPN


Running with VPN_CONFIG_SOURCE auto


No bundled config script found for FASTESTVPN. Defaulting to external config


Downloading configs from https://github.com/haugene/vpn-configs-contrib/archive/main.zip into /tmp/tmp.GKEndf


curl: (6) Could not resolve host: github.com


./etc/openvpn/fetch-external-configs.sh: line 16: config_repo_temp_dir: unbound variable


Supplied config France-UDP.ovpn could not be found.


Your options for this provider are:


NB: Remember to not specify .ovpn as part of the config name.


Starting container with revision: 1221d7cee35a228a09254880f107c80ba8ef26f1


WARNING: initial DNS resolution test failed


Creating TUN device /dev/net/tun


Using OpenVPN provider: FASTESTVPN


Running with VPN_CONFIG_SOURCE auto


No bundled config script found for FASTESTVPN. Defaulting to external config


Downloading configs from https://github.com/haugene/vpn-configs-contrib/archive/main.zip into /tmp/tmp.GKeKaf


curl: (6) Could not resolve host: github.com


./etc/openvpn/fetch-external-configs.sh: line 16: config_repo_temp_dir: unbound variable


Supplied config France-UDP.ovpn could not be found.


Your options for this provider are:


NB: Remember to not specify .ovpn as part of the config name.


Starting container with revision: 1221d7cee35a228a09254880f107c80ba8ef26f1


WARNING: initial DNS resolution test failed


Creating TUN device /dev/net/tun


Using OpenVPN provider: FASTESTVPN


Running with VPN_CONFIG_SOURCE auto


No bundled config script found for FASTESTVPN. Defaulting to external config


Downloading configs from https://github.com/haugene/vpn-configs-contrib/archive/main.zip into /tmp/tmp.GKaPaf


curl: (6) Could not resolve host: github.com


./etc/openvpn/fetch-external-configs.sh: line 16: config_repo_temp_dir: unbound variable


Supplied config France-UDP.ovpn could not be found.


Your options for this provider are:


NB: Remember to not specify .ovpn as part of the config name.

```

**Comment by haugene** [comment]
You posted in #1637 that `docker run --rm -it alpine sh -c "ping github.com"` worked, right? But here you are running with Cloudflare DNS servers. Can you try to remove your dns section? Or try to run `docker run --rm -it --dns 1.1.1.1 --dns 1.0.0.1 alpine sh -c "ping github.com"`?

You still get `WARNING: initial DNS resolution test failed` in your logs, which means that the container is not able to look up google.com.

Have you gone through the debug guide as I told you? How far did you get? And what errors did you get where? https://haugene.github.io/docker-transmission-openvpn/debug/

**Comment by haugene** [comment]
What do you get if you run this?
```
version: '2.1'
services:
    transmission-openvpn:
        environment:
            - OPENVPN_PROVIDER=FASTESTVPN
            - OPENVPN_CONFIG=France-UDP
            - OPENVPN_USERNAME=xxxxxxxx@gmail.com
            - OPENVPN_PASSWORD=12345678
            - LOCAL_NETWORK=192.168.1.0/24
        cap_add:
            - NET_ADMIN
        ports:
            - 9091:9091
        image: haugene/transmission-openvpn:dev
```

Or even:
```
version: '2.1'
services:
    transmission-openvpn:
        environment:
            - OPENVPN_PROVIDER=FASTESTVPN
            - OPENVPN_USERNAME=xxxxxxxx@gmail.com
            - OPENVPN_PASSWORD=12345678
        cap_add:
            - NET_ADMIN
        ports:
            - 9091:9091
        image: haugene/transmission-openvpn:dev
```
