### ISSUE TITLE
Mounting /data causes UDP trackers to not connect

### ISSUE THREAD

**Issue by shplamana** [haugene/docker-transmission-openvpn#1808]
## Before creating this issue I have:

**REQUIRED**
- [x] Read through the pinned issues for related problems
- [x] Searched for similar [provider issues][pi] and [container issues][ci]
- [x] [Read the documentation][rd], especially the troubleshooting section and FAQ
- [x] Tried to add as much relevant information to the issue as possible
- [x] Verified I have tried using newest release as well
- [x] Agreed that my issue will be closed if I do not follow this template and will remain closed until I complete the template

[pi]: https://github.com/haugene/vpn-configs-contrib/issues
[ci]: https://github.com/haugene/docker-transmission-openvpn/issues
[rd]: https://haugene.github.io/docker-transmission-openvpn/

### Container version & last working release
```linux, amd64```
**Required, problem occurs in :** 
```3.6```

*If possible, last working version:* 
 

### Describe the problem

**REQUIRED**
```txt
Using portainer to manage the stack.

Mounting the `/data` directory either to a persistent volume or directly to the host causes trackers to not be able to connect. 

Modifying the compose to not mount any volume to `/data` allows transmission to function normally. 

Not a show stopper as I have a working workaround, but any time the host is restarted, I lose any progress on any tracked torrents.

Based on searching around, this sounded very similar to #1465, with similar output in the log, but I see the same output regardless of mounting or not.
```
### Describe the steps you have tried to solve the problem

**REQUIRED**
```txt

- Verified DNS works
- HTTP torrents work, such as Ubuntu distros, but UDP trackers do not
- Tried different mounting options and permissions
- Read the documentation at: https://haugene.github.io/docker-transmission-openvpn/run-container/#1_the_container_assumes_that_you_mount_a_folder_to_data

```

### Add your docker run command or docker-compose file or env details

**REQUIRED**
Compose that causes issues:
```txt
version: '2.4'
services:
  transmission-openvpn:
    image: haugene/transmission-openvpn
    container_name: transmission-openvpn
    volumes:
      - transmission-data:/data
      # - /volume1/docker/appdata/transmission:/data # also doesn't work
      - /volume1/storage/media/downloads:/media/downloads
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=1000
      - PGID=100
      - CREATE_TUN_DEVICE=true
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_CONFIG=us_chicago
      - OPENVPN_USERNAME=######
      - OPENVPN_PASSWORD=######
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - WEBPROXY_ENABLED=false
      - LOCAL_NETWORK=192.168.1.0/24
      - TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=false
      - TRANSMISSION_WEB_UI=flood-for-transmission
      - TRANSMISSION_DOWNLOAD_DIR=/media/downloads
      - TZ=America/Chicago
      - DNS=1.1.1.1,1.0.0.1
    cap_add:
      - NET_ADMIN
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - 9091:9091
      - 9117:9117
      - 7878:7878
      - 8989:8989
      - 8686:8686
    restart: always

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    network_mode: "service:transmission-openvpn"
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Chicago
      - AUTO_UPDATE=true
    volumes:
      - /volume1/docker/appdata/jackett:/config
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    network_mode: "service:transmission-openvpn"
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Chicago
      - UMASK=022
    volumes:
      - /volume1/docker/appdata/radarr:/config
      - /volume1/storage/media:/media
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    network_mode: "service:transmission-openvpn"
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Chicago
      - UMASK=022
    volumes:
      - /volume1/docker/appdata/sonarr:/config
      - /volume1/storage/media/:/media
    restart: unless-stopped

  lidarr:
    image: linuxserver/lidarr
    network_mode: "service:transmission-openvpn"
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Chicago
      - UMASK=022
    volumes:
      - /volume1/docker/appdata/lidarr:/config
      - /volume1/storage/media/:/media
    restart: unless-stopped

volumes:
  transmission-data:
    driver: local
```

Compose that works:
```
version: '2.4'
services:
  transmission-openvpn:
    image: haugene/transmission-openvpn
    container_name: transmission-openvpn
    volumes:
      - /volume1/storage/media/downloads:/media/downloads
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=1000
      - PGID=100
      - CREATE_TUN_DEVICE=true
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_CONFIG=us_chicago
      - OPENVPN_USERNAME=#####
      - OPENVPN_PASSWORD=#####
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - WEBPROXY_ENABLED=false
      - LOCAL_NETWORK=192.168.1.0/24
      - TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=false
      - TRANSMISSION_WEB_UI=flood-for-transmission
      - TRANSMISSION_DOWNLOAD_DIR=/media/downloads
      - TZ=America/Chicago
      - DNS=1.1.1.1,1.0.0.1
    cap_add:
      - NET_ADMIN
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - 9091:9091
      - 9117:9117
      - 7878:7878
      - 8989:8989
      - 8686:8686
    restart: always

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    network_mode: "service:transmission-openvpn"
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Chicago
      - AUTO_UPDATE=true
    volumes:
      - /volume1/docker/appdata/jackett:/config
      #Jackett only needs config
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    network_mode: "service:transmission-openvpn"
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Chicago
      - UMASK=022
    volumes:
      - /volume1/docker/appdata/radarr:/config
      - /volume1/storage/media:/media
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    network_mode: "service:transmission-openvpn"
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Chicago
      - UMASK=022
    volumes:
      - /volume1/docker/appdata/sonarr:/config
      - /volume1/storage/media/:/media
    restart: unless-stopped

  lidarr:
    image: linuxserver/lidarr
    network_mode: "service:transmission-openvpn"
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Chicago
      - UMASK=022
    volumes:
      - /volume1/docker/appdata/lidarr:/config
      - /volume1/storage/media/:/media
    restart: unless-stopped

volumes:
  transmission-data:
    driver: local
```

Portainer config section:
```txt
  "Config": {
    "ArgsEscaped": true,
    "AttachStderr": false,
    "AttachStdin": false,
    "AttachStdout": false,
    "Cmd": [
      "dumb-init",
      "/etc/openvpn/start.sh"
    ],
    "DDSM": false,
    "Domainname": "",
    "Entrypoint": null,
    "Env": [
      "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
      "OPENVPN_USERNAME=#####",
      "OPENVPN_PASSWORD=#####",
      "OPENVPN_PROVIDER=PIA",
      "GLOBAL_APPLY_PERMISSIONS=true",
      "TRANSMISSION_HOME=/data/transmission-home",
      "TRANSMISSION_RPC_PORT=9091",
      "TRANSMISSION_DOWNLOAD_DIR=/media/downloads",
      "TRANSMISSION_INCOMPLETE_DIR=/data/incomplete",
      "TRANSMISSION_WATCH_DIR=/data/watch",
      "CREATE_TUN_DEVICE=true",
      "ENABLE_UFW=false",
      "UFW_ALLOW_GW_NET=false",
      "UFW_EXTRA_PORTS=",
      "UFW_DISABLE_IPTABLES_REJECT=false",
      "PUID=1000",
      "PGID=100",
      "DROP_DEFAULT_ROUTE=",
      "WEBPROXY_ENABLED=false",
      "WEBPROXY_PORT=8888",
      "WEBPROXY_USERNAME=",
      "WEBPROXY_PASSWORD=",
      "LOG_TO_STDOUT=false",
      "HEALTH_CHECK_HOST=google.com",
      "REVISION=416541016b9b30149d8fcb56abe2bc325db4904b",
      "OPENVPN_CONFIG=us_chicago",
      "OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60",
      "LOCAL_NETWORK=192.168.1.0/24",
      "TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=false",
      "TRANSMISSION_WEB_UI=flood-for-transmission",
      "TZ=America/Chicago",
      "DNS=1.1.1.1,1.0.0.1"
    ],
    "ExposedPorts": {
      "7878/tcp": {},
      "8686/tcp": {},
      "8989/tcp": {},
      "9091/tcp": {},
      "9117/tcp": {}
    },
    "Healthcheck": {
      "Interval": 60000000000,
      "Test": [
        "CMD-SHELL",
        "/etc/scripts/healthcheck.sh"
      ]
    },
    "Hostname": "33edee3f650a",
    "Image": "haugene/transmission-openvpn",
    "Labels": {
      "autoheal": "true",
      "com.docker.compose.config-hash": "94c7c12c4538079643af5d49927b834c54e9cb739bb00eaaae9dba6deb835182",
      "com.docker.compose.container-number": "1",
      "com.docker.compose.oneoff": "False",
      "com.docker.compose.project": "vpn",
      "com.docker.compose.project.config_files": "/data/compose/17/docker-compose.yml",
      "com.docker.compose.project.working_dir": "/data/compose/17",
      "com.docker.compose.service": "transmission-openvpn",
      "com.docker.compose.version": "1.27.4",
      "org.opencontainers.image.revision": "416541016b9b30149d8fcb56abe2bc325db4904b",
      "org.opencontainers.image.source": "https://github.com/haugene/docker-transmission-openvpn"
    },
    "OnBuild": null,
    "OpenStdin": false,
    "StdinOnce": false,
    "Tty": false,
    "User": "",
    "Volumes": {
      "/config": {},
      "/data": {},
      "/etc/localtime": {},
      "/media/downloads": {}
    },
    "WorkingDir": ""
  }
```

### Logs

 

**REQUIRED**

Log during compose that doesn't work:
```txt

MCYwEQIBARcMMTYwNzA4MTkwMDQ2MBECAQYXDDE2MDcwODE5MDA0NjANBgkqhkiG

9w0BAQ0FAAOCAQEAQZo9X97ci8EcPYu/uK2HB152OZbeZCINmYyluLDOdcSvg6B5

jI+ffKN3laDvczsG6CxmY3jNyc79XVpEYUnq4rT3FfveW1+Ralf+Vf38HdpwB8EW

B4hZlQ205+21CALLvZvR8HcPxC9KEnev1mU46wkTiov0EKc+EdRxkj5yMgv0V2Re

ze7AP+NQ9ykvDScH4eYCsmufNpIjBLhpLE2cuZZXBLcPhuRzVoU3l7A9lvzG9mjA

5YijHJGHNjlWFqyrn1CfYS6koa4TGEPngBoAziWRbDGdhEgJABHrpoaFYaL61zqy

MR6jC0K2ps9qyZAN74LEBedEfK7tBOzWMwr58A==

-----END X509 CRL-----


2021-04-15 17:01:42 TCP/UDP: Preserving recently used remote address: [AF_INET]154.21.28.11:1198

2021-04-15 17:01:42 UDP link local: (not bound)

2021-04-15 17:01:42 UDP link remote: [AF_INET]154.21.28.11:1198

2021-04-15 17:01:42 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this

2021-04-15 17:01:42 [chicago405] Peer Connection Initiated with [AF_INET]154.21.28.11:1198

2021-04-15 17:01:43 TUN/TAP device tun0 opened

2021-04-15 17:01:43 /sbin/ip link set dev tun0 up mtu 1500

2021-04-15 17:01:43 /sbin/ip link set dev tun0 up

2021-04-15 17:01:43 /sbin/ip addr add dev tun0 10.7.112.7/24

2021-04-15 17:01:43 /etc/openvpn/tunnelUp.sh tun0 1500 1553 10.7.112.7 255.255.255.0 init

Up script executed with tun0 1500 1553 10.7.112.7 255.255.255.0 init

Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.7.112.7

Using Flood for Transmission UI, overriding TRANSMISSION_WEB_HOME

Updating Transmission settings.json with values from env variables

Using existing settings.json for Transmission /data/transmission-home/settings.json

Overriding bind-address-ipv4 because TRANSMISSION_BIND_ADDRESS_IPV4 is set to 10.7.112.7

Overriding download-dir because TRANSMISSION_DOWNLOAD_DIR is set to /media/downloads

Overriding incomplete-dir because TRANSMISSION_INCOMPLETE_DIR is set to /data/incomplete

Overriding rpc-port because TRANSMISSION_RPC_PORT is set to 9091

Overriding scrape-paused-torrents-enabled because TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED is set to false

Overriding watch-dir because TRANSMISSION_WATCH_DIR is set to /data/watch

sed'ing True to true

Enforcing ownership on transmission config directories

Applying permissions to transmission config directories

Setting owner for transmission paths to 1000:100

Setting permission for files (644) and directories (755)

Setting permission for watch directory (775) and its files (664)


-------------------------------------

Transmission will run as

-------------------------------------

User name:   abc

User uid:    1000

User gid:    100

-------------------------------------


STARTING TRANSMISSION

Provider PIA has a script for automatic port forwarding. Will run it now.

If you want to disable this, set environment variable DISABLE_PORT_UPDATER=true

Transmission startup script complete.

2021-04-15 17:01:44 WARNING: OpenVPN was configured to add an IPv6 route. However, no IPv6 has been configured for tun0, therefore the route installation may fail or may not work as expected.

2021-04-15 17:01:44 add_route_ipv6(2000::/3 -> :: metric -1) dev tun0

2021-04-15 17:01:44 Initialization Sequence Completed

Running functions for token based port fowarding

curl: (7) Failed to connect to 10.7.112.1 port 19999: Connection refused

Thu Apr 15 17:01:49 CDT 2021: getSignature error


the has been a fatal_error

date: invalid date ''

curl: (7) Failed to connect to 10.7.112.1 port 19999: Connection refused

Thu Apr 15 17:01:50 CDT 2021: bindPort error


the has been a fatal_error

transmission auth not required

waiting for transmission to become responsive

transmission became responsive

     1     0%       None  Unknown      0.0     0.0   None  Idle         Name
Sum:                None               0.0     0.0

setting transmission port to 

localhost:9091/transmission/rpc/ responded: "success"

Checking port...

Error: portTested: http error 400: Bad Request

date: invalid date '@'

#######################

        SUCCESS        

#######################

Port: 

Expiration 

#######################

Entering infinite while loop

Every 15 minutes, check port status

60 day port reservation reached

Getting a new one

curl: (7) Failed to connect to 10.7.112.1 port 19999: Connection refused

Thu Apr 15 17:02:01 CDT 2021: getSignature error


the has been a fatal_error

date: invalid date ''

curl: (7) Failed to connect to 10.7.112.1 port 19999: Connection refused

Thu Apr 15 17:02:01 CDT 2021: bindPort error


the has been a fatal_error

transmission auth not required

waiting for transmission to become responsive

transmission became responsive

     1     0%       None  Unknown      0.0     0.0   None  Idle         Name

Sum:                None               0.0     0.0

setting transmission port to 

localhost:9091/transmission/rpc/ responded: "success"

Checking port...

Error: portTested: http error 400: Bad Request

```

Log during compose that works:
```txt
Generating settings.json for Transmission from environment and defaults /etc/transmission/default-settings.json

Overriding bind-address-ipv4 because TRANSMISSION_BIND_ADDRESS_IPV4 is set to 10.11.112.202

Overriding download-dir because TRANSMISSION_DOWNLOAD_DIR is set to /media/downloads

Overriding incomplete-dir because TRANSMISSION_INCOMPLETE_DIR is set to /data/incomplete

Overriding rpc-port because TRANSMISSION_RPC_PORT is set to 9091

Overriding scrape-paused-torrents-enabled because TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED is set to false

Overriding watch-dir because TRANSMISSION_WATCH_DIR is set to /data/watch

sed'ing True to true

Enforcing ownership on transmission config directories

Applying permissions to transmission config directories

Setting owner for transmission paths to 1000:100

Setting permission for files (644) and directories (755)

Setting permission for watch directory (775) and its files (664)


-------------------------------------

Transmission will run as

-------------------------------------

User name:   abc

User uid:    1000

User gid:    100

-------------------------------------


STARTING TRANSMISSION

Provider PIA has a script for automatic port forwarding. Will run it now.

If you want to disable this, set environment variable DISABLE_PORT_UPDATER=true

Transmission startup script complete.

2021-04-15 16:33:07 WARNING: OpenVPN was configured to add an IPv6 route. However, no IPv6 has been configured for tun0, therefore the route installation may fail or may not work as expected.

2021-04-15 16:33:07 add_route_ipv6(2000::/3 -> :: metric -1) dev tun0

2021-04-15 16:33:07 Initialization Sequence Completed

Running functions for token based port fowarding

curl: (7) Failed to connect to 10.11.112.1 port 19999: Connection refused

Thu Apr 15 16:33:12 CDT 2021: getSignature error


the has been a fatal_error

date: invalid date ''

curl: (7) Failed to connect to 10.11.112.1 port 19999: Connection refused

Thu Apr 15 16:33:13 CDT 2021: bindPort error


the has been a fatal_error

transmission auth not required

waiting for transmission to become responsive

transmission became responsive

    ID   Done       Have  ETA           Up    Down  Ratio  Status       Name

Sum:                None               0.0     0.0

setting transmission port to 

localhost:9091/transmission/rpc/ responded: "success"

Checking port...

Error: portTested: http error 400: Bad Request

date: invalid date '@'

#######################

        SUCCESS        

#######################

Port: 

Expiration 

#######################

Entering infinite while loop

Every 15 minutes, check port status

60 day port reservation reached

Getting a new one

curl: (7) Failed to connect to 10.11.112.1 port 19999: Connection refused

Thu Apr 15 16:33:24 CDT 2021: getSignature error


the has been a fatal_error

date: invalid date ''

curl: (7) Failed to connect to 10.11.112.1 port 19999: Connection refused

Thu Apr 15 16:33:24 CDT 2021: bindPort error


the has been a fatal_error

transmission auth not required

waiting for transmission to become responsive

transmission became responsive

    ID   Done       Have  ETA           Up    Down  Ratio  Status       Name

Sum:                None               0.0     0.0

setting transmission port to 

localhost:9091/transmission/rpc/ responded: "success"

Checking port...

Error: portTested: http error 400: Bad Request

curl: (7) Failed to connect to 10.11.112.1 port 19999: Connection refused

Thu Apr 15 16:48:35 CDT 2021: bindPort error


the has been a fatal_error

60 day port reservation reached

Getting a new one

curl: (7) Failed to connect to 10.11.112.1 port 19999: Connection refused

Thu Apr 15 16:48:35 CDT 2021: getSignature error


the has been a fatal_error

date: invalid date ''

curl: (7) Failed to connect to 10.11.112.1 port 19999: Connection refused

Thu Apr 15 16:48:35 CDT 2021: bindPort error


the has been a fatal_error

transmission auth not required

waiting for transmission to become responsive

transmission became responsive

    ID   Done       Have  ETA           Up    Down  Ratio  Status       Name

Sum:                None               0.0     0.0

setting transmission port to 

localhost:9091/transmission/rpc/ responded: "success"

Checking port...

```

### Host system

**REQUIRED**
```txt
Synology NAS DS1621+
linux x86_64 4.4.59+

Docker 18.09.8 (API: 1.39)
```

**Comment by pkishino** [comment]
hmm,
care to say why you are doing this ?:
```volumes:
      - /volume1/storage/media/downloads:/media/downloads
      - /etc/localtime:/etc/localtime:ro
```
have you tried to set /data instead of /media?
/data is needed for transmission config..which is a long standing "issue" and is discussed here #1521 
but that post also mentions a workaround.. -e TRANSMISSION_HOME=\config (which I think should be /config..)

**Comment by shplamana** [comment]
> hmm,
> care to say why you are doing this ?:
> 
> ```
>       - /volume1/storage/media/downloads:/media/downloads
>       - /etc/localtime:/etc/localtime:ro
> ```
> 
> have you tried to set /data instead of /media?
> /data is needed for transmission config..which is a long standing "issue" and is discussed here #1521
> but that post also mentions a workaround.. -e TRANSMISSION_HOME=\config (which I think should be /config..)

That's just my lazy copy paste if you're referring to this block from the compose example that doesn't work:
```
volumes:
      - transmission-data:/data
      # - /volume1/docker/appdata/transmission:/data # also doesn't work
      - /volume1/storage/media/downloads:/media/downloads
      - /etc/localtime:/etc/localtime:ro
```

As I left the mount in there that works, and it doesn't harm anything.

If you're just asking why I'm mounting /media, it's because that's the workaround I came up with to get at the completed folder. I set the environment variable for the downloads to redirect there and then mount that instead of /data because of the issue I'm running into:
`- TRANSMISSION_DOWNLOAD_DIR=/media/downloads`

**Comment by pkishino** [comment]
can you try creating a new container with the default compose and check if
the same problem occurs?

**Comment by shplamana** [comment]
> can you try creating a new container with the default compose and check if the same problem occurs?

Tried the compose listed in the readme with just my credentials and area and didn't run into the same issue as noted above:
```
version: '3.3'
services:
    transmission-openvpn:
        cap_add:
            - NET_ADMIN
        volumes:
            - '/volume1/docker/appdata/transmission:/data'
        environment:
            - OPENVPN_PROVIDER=PIA
            - OPENVPN_CONFIG=us_chicago
            - OPENVPN_USERNAME=#######
            - OPENVPN_PASSWORD=#######
            - LOCAL_NETWORK=192.168.1.0/24
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '9091:9091'
        image: haugene/transmission-openvpn
```

Not sure what parameter I'm putting into my compose that is causing it fail in the way that I'm observing. Maybe it's the tunnel?
`- CREATE_TUN_DEVICE=true`

With that default config above, I do still get the same port bind error in the logs, so that doesn't seem to be causing any issue.

**Comment by pkishino** [comment]
Well, in that case it looks like some synology issue perhaps? Next step would be to slowly add your options until it breaks.. I’d be curious if this was the create tun breaking this..

**Comment by shplamana** [comment]
I actually tried deploying this stack on a Raspberry Pi 4 (4GB) before putting it on the NAS. Had the same issue there as well . 

Only reason I moved it to the NAS was because it wouldn't write to the NAS until it fully downloaded the file to the Pi first. The wear and tear that would put on the SD card would chew it up in no time.

I'll spend some time plugging and unplugging options and see what happens.

**Comment by pkishino** [comment]
In that case why not just mount the nas on the raspberry.. I’m not using a pi but for temp storage before uploading to gdrive it’s all stored on external drive, the whole container runs on it and all is stored there, no wait for complete file

**Comment by shplamana** [comment]
I did initially, but the behavior it didn't make any sense.

I tried mounting the nas via fstab with this:
`192.168.1.12:/volume1/storage /mnt/nas nfs defaults 0 0`

And then mounting that to the volume in docker with something like this:
```
volumes:
    - /mnt/nas/media/downloads:/media/downloads
    - /mnt/nas/media/incomplete:/data/incomplete
```
But it didn't write to the NAS until after the file was completely done, which I found very odd.

Even putting the nfs mount right in the compose gave me the same behavior of writing to the SD card before writing to the nas, which looked like this example:
```
  services:
    example-app:
      volumes:
      - "nas-volume:/data"

  volumes:
    nas-volume:
      driver: local
      driver_opts:
        type: nfs
        o: nfsvers=4,addr=nfs.example.com,rw
        device: ":/path/to/dir"
```

Ultimately I couldn't find an answer for the behavior I was seeing other than maybe it has to do with how the storage controller works on the Pi or some odd issue with Docker. So I put it on the nas so I can just access the storage directly and avoid the problem altogether.
