### ISSUE TITLE
Issues with Trust.Zone provider

### ISSUE THREAD

**Issue by HippyRock** [haugene/docker-transmission-openvpn#1823]
## Before creating this issue I have:
**REQUIRED**
- [x] Read through the pinned issues for related problems
- [x] Searched for similar [provider issues][pi] and [container issues][ci]
- [x] [Read the documentation][rd], especially the troubleshooting section and FAQ
- [x] Tried to add as much relevant information to the issue as possible
- [x] Verified I have tried using newest release as well
- [x] Agreed that my issue will be closed if I do not follow this template and will remain closed until I complete the template

was working fine on the current configuration since my [original post](https://github.com/haugene/docker-transmission-openvpn/issues/1183)

### Container version & last working release
```
haugene/transmission-openvpn:latest installed about 1 year ago
```
### Describe the problem
I can't connect to Trust.Zone.
I can connect to Trust.Zone with the same configuration from the other clients.
I saw some notice on Trust.Zone that they did recently some changes, not sure if that is related?

### Describe the steps you have tried to solve the problem

1) tried changing UDP to TCP and different VPN locations
2) tried to use fresh ovpn configuration files

### Add your docker run command or docker-compose file or env details
running using kubenetes 
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: transmission-openvpn-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: transmission-openvpn       
    spec:
      terminationGracePeriodSeconds: 10
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 8.8.4.4       
      containers:
      - image: haugene/transmission-openvpn
        name: transmission-openvpn
        securityContext:
          capabilities:
            add:
              - NET_ADMIN    
        livenessProbe:
          exec:
            command: ["ping", "-I", "tun0", "-c", "1", "google.com"]
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1              
        ports:
        - containerPort: 9091
        livenessProbe:
          exec:
            command: ["ping", "-I", "tun0", "-c", "1", "google.com"]
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
        env:
        - name: PUID
          value: "1020"
        - name: PGID
          value: "1020"          
        - name: CREATE_TUN_DEVICE
          value: "true"
        - name: OPENVPN_PROVIDER
          value: "TRUSTZONE"
        - name: OPENVPN_USERNAME
          value: "--------"
        - name: OPENVPN_PASSWORD
          value: "--------"
        - name: WEBPROXY_ENABLED
          value: "false"
        - name: WEBPROXY_PORT
          value: "8888"
        - name: OPENVPN_CONFIG
          value: "Canada-Quebec"
        - name: LOCAL_NETWORK
          value: "192.168.1.0/24,10.42.0.0/16"
        - name: TRANSMISSION_HOME
          value: "/transmissionvpn"
        - name: TRANSMISSION_RPC_WHITELIST
          value: "127.0.0.1,192.168.1.*"
        - name: "TRANSMISSION_RPC_WHITELIST_ENABLED"
          value: "false"
        - name: TRANSMISSION_RPC_HOST_WHITELIST
          value: "*"
        - name: TRANSMISSION_RPC_HOST_WHITELIST_ENABLED
          value: "false"
        - name: TRANSMISSION_RPC_AUTHENTICATION_REQUIRED
          value: "true"
        - name: TRANSMISSION_RPC_USERNAME
          value: "------"
        - name: TRANSMISSION_RPC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: transmissions
              key: SA_PASSWORD
        - name: OPENVPN_OPTS
          value: "--inactive 3600 --ping 10 --ping-exit 60 --mssfix 1500"
        volumeMounts:
        - name: config
          mountPath: /transmissionvpn        
        - name: config
          mountPath: /scripts
        - name: downloads
          mountPath: /data
        - name: localtime
          readOnly: true
          mountPath: /etc/localtime
        lifecycle:
          postStart:
            exec:
              command:
              - /bin/sh
              - -c 
              - cp /transmissionvpn/Trust.Zone-Canada-Quebec.ovpn  /etc/openvpn/trustzone/canada.ovpn         
              - cp /transmissionvpn/Trust.Zone-Canada-Quebec.ovpn  /etc/openvpn/trustzone/Canada-Quebec.ovpn 
        resources: {}          
      restartPolicy: Always
      volumes:
      - name: config
        nfs: 
          path: /mnt/SSD
          server: x.x.x.x
      - name: localtime
        hostPath:
          path: /etc/localtime
      - name: downloads
        flexVolume:
          driver: "microsoft.com/smb"
          secretRef:
            name: smbcreds  
          options:
            source: "//x.x.x.x/Media/downloads"
            mountoptions: "vers=3.0,dir_mode=0777,file_mode=0777"  
```

### Logs

```
Starting container with revision: 32bcf7522d1ecf9428cefe9044e12f9af5e30476
--
Tue, May 4 2021 4:20:49 pm | Executing /scripts/openvpn-pre-start.sh
Tue, May 4 2021 4:20:49 pm | /scripts/openvpn-pre-start.sh returned 0
Tue, May 4 2021 4:20:49 pm | Creating TUN device /dev/net/tun
Tue, May 4 2021 4:20:49 pm | Using OpenVPN provider: TRUSTZONE
Tue, May 4 2021 4:20:49 pm | Starting OpenVPN using config Canada-Quebec.ovpn
Tue, May 4 2021 4:20:49 pm | Setting OpenVPN credentials...
Tue, May 4 2021 4:20:50 pm | adding route to local network 192.168.1.0/24 via 169.254.1.1 dev eth0
Tue, May 4 2021 4:20:50 pm | adding route to local network 10.42.0.0/16 via 169.254.1.1 dev eth0
Tue, May 4 2021 4:20:50 pm | 2021-05-04 16:20:50 DEPRECATED OPTION: --cipher set to 'AES-256-CBC' but missing in --data-ciphers (AES-256-GCM:AES-128-GCM). Future OpenVPN version will ignore --cipher for cipher negotiations. Add 'AES-256-CBC' to --data-ciphers or change --cipher 'AES-256-CBC' to --data-ciphers-fallback 'AES-256-CBC' to silence this warning.
Tue, May 4 2021 4:20:50 pm | 2021-05-04 16:20:50 OpenVPN 2.5.1 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Apr 16 2021
Tue, May 4 2021 4:20:50 pm | 2021-05-04 16:20:50 library versions: OpenSSL 1.1.1k 25 Mar 2021, LZO 2.10
Tue, May 4 2021 4:20:50 pm | 2021-05-04 16:20:50 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Tue, May 4 2021 4:20:50 pm | 2021-05-04 16:20:50 TCP/UDP: Preserving recently used remote address: [AF_INET]158.69.246.171:443
Tue, May 4 2021 4:20:50 pm | 2021-05-04 16:20:50 Socket Buffers: R=[212992->212992] S=[212992->212992]
Tue, May 4 2021 4:20:50 pm | 2021-05-04 16:20:50 UDP link local: (not bound)
Tue, May 4 2021 4:20:50 pm | 2021-05-04 16:20:50 UDP link remote: [AF_INET]158.69.246.171:443
Tue, May 4 2021 4:21:00 pm | 2021-05-04 16:21:00 [UNDEF] Inactivity timeout (--ping-restart), restarting
Tue, May 4 2021 4:21:00 pm | 2021-05-04 16:21:00 SIGUSR1[soft,ping-restart] received, process restarting
```

### Host system
```
Rancher Kubernetes cluster (RKE)
Kubernetes Version: v1.15.4
```
