### ISSUE TITLE
Impossible to download Config files on startup / Ban on VPN in certain countries

### ISSUE THREAD

**Issue by bedouin345** [haugene/docker-transmission-openvpn#1833]
## Before creating this issue I have:

**REQUIRED**
- [X] Read through the pinned issues for related problems
- [X] Searched for similar [provider issues][pi] and [container issues][ci]
- [X] [Read the documentation][rd], especially the troubleshooting section and FAQ
- [X] Tried to add as much relevant information to the issue as possible
- [X] Verified I have tried using newest release as well
- [X] Agreed that my issue will be closed if I do not follow this template and will remain closed until I complete the template

[pi]: https://github.com/haugene/vpn-configs-contrib/issues
[ci]: https://github.com/haugene/docker-transmission-openvpn/issues
[rd]: https://haugene.github.io/docker-transmission-openvpn/

### Container version & last working release

**Required, problem occurs in :** 
 
```.latest 3.x```

*If possible, last working version:* 
```2.x```

### Describe the problem

**REQUIRED**
```txt
v3 does not contain config/ovpn from providers and downloads them on startup
(in my case IPVanish)
I live in a region where VPN is forbidden and local ISP blocks connections to providers' domains
Therefore, the app stops immediately without having been able to download the config

Is it possible to bypass the download and feed a local configs.zip file ?
```
### Describe the steps you have tried to solve the problem

**REQUIRED**
```txt
1) historically using v 2.13 which contains all configs as part of the build (no problem here)
2) manually started my VPN client, then started the container with .latest, and this time it connected (not a sustainable solution !)
```

### Add your docker run command or docker-compose file or env details

**REQUIRED**
```txt
(Rather irrelevant sample code I used to test v3)
version: '3.3'
services:
    transmission-openvpn:
        cap_add:
            - NET_ADMIN
        volumes:
            - '/volume1/docker/tr/:/data'
        environment:
            - OPENVPN_PROVIDER=IPVANISH
            - OPENVPN_CONFIG=dummy
            - OPENVPN_USERNAME=nothing
            - OPENVPN_PASSWORD=tosee
            - LOCAL_NETWORK=192.168.0.0/16
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '9091:9091'
        image: haugene/transmission-openvpn
```

### Logs

 

**REQUIRED**
```txt
Starting container with revision: xxx
Creating TUN device /dev/net/tun
Using OpenVPN provider: IPVANISH
Provider IPVANISH has a custom setup script, executing it
Downloading OpenVPN config bundle configs.zip into temporary file /tmp/tmp.eHbMea
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to www.ipvanish.com:443
```

### Host system

**REQUIRED**
```txt
Synology > Docker > Portainer
```

**Comment by pkishino** [comment]
Yes, check the wiki for custom provider.. or use older version.. we are definitely not going back to hosting the configs in the container again

**Comment by bedouin345** [comment]
Thank you.
I was not expecting the configs to be re-integrated. I was more hoping for a command indicating where to locally load them from (another volume to map ?)... And I was dreading to use the Custom method.
Cheers.

**Comment by pkishino** [comment]
The custom is just a simple mount of your preferred ovpn file.. that’s it..
plus setting openvpn config to custom

**Comment by bedouin345** [comment]
Well, I spent a few hours to get things to work as I wanted. This was not super easy :)
See below my config and a piece of text, which you can use if you wish to update the documentation where relevant.

Also note 

1. the weird issue with _auth-user-pass /config/openvpn-credentials.txt_ which is necessary but actually not used !
2. the usage of OPENVPN_OPTS which seems to be overwritten by the .ovpn file content unfortunately

I hope it can be helpful to some



### How to declare a Custom provider (IPVanish as example)

**Grab .OVPN files from your provider** (usually a .zip file to download & unzip)
**Copy them in a repository**, there should be a ca.cert file as well (mine is /volume1/docker/transmission/ipvanish/)

**Mount the volume**
Compose sample:
```
             - /volume1/docker/transmission/ipvanish/:/etc/openvpn/custom/
```
**Declare the Custom provider, the target server and login/password**
Compose sample:
```
            - OPENVPN_PROVIDER=custom
            - OPENVPN_CONFIG=ipvanish-UK-Maidenhead-lhr-c02
            - OPENVPN_USERNAME=nothing
            - OPENVPN_PASSWORD=tosee
```

**Open the .OVPN file, and modify**

_ca ca.ipvanish.com.crt_  
into
```
ca /etc/openvpn/custom/ca.ipvanish.com.crt
```
_auth-user-pass_ 
into
```
auth-user-pass /config/openvpn-credentials.txt
```

_Note (1): the file openvpn-credentials.txt should contain 2 lines with your login and password, but actually it is ignored and it reverts nicely to OPENVPN_USERNAME and OPENVPN_PASSWORD variables ! See issue 1497. I don't even have this file on my filesystem any longer)_

_Note (2) : Why can't we use the OPENVPN_OPTS=--ca instead of modifying the .ovpn file ? I tried without luck_


### Compose

```
version: '3.3'
services:
    transmission-openvpn:
        cap_add:
          - NET_ADMIN
        volumes:
          - /volume1/docker/transmission/:/data
          - /volume1/docker/transmission/ipvanish/:/etc/openvpn/custom/
          - /volume1/Downloads/:/downloads
          - /etc/localtime:/etc/localtime:ro
        environment:
          - OPENVPN_PROVIDER=custom
          - OPENVPN_CONFIG=ipvanish-AT-Vienna-vie-c04,ipvanish-UK-Maidenhead-lhr-c02
          - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60 
          - OPENVPN_USERNAME=nothing
          - OPENVPN_PASSWORD=tosee
          - LOCAL_NETWORK=192.168.0.0/16
          - HEALTH_CHECK_HOST
          - TRANSMISSION_HOME=/data
          - TRANSMISSION_WATCH_DIR=/downloads
          - TRANSMISSION_WEB_UI=flood-for-transmission
        logging:
          driver: json-file
          options:
              max-size: 10m
        ports:
          - '9092:9091'
        image: 
          haugene/transmission-openvpn:latest
        restart:
          always
```
