### ISSUE TITLE
WebUI fails to start

### ISSUE THREAD

**Issue by Slyke** [haugene/docker-transmission-openvpn#1851]
## Before creating this issue I have:

**REQUIRED**
- [X] Read through the pinned issues for related problems
- [X] Searched for similar [provider issues][pi] and [container issues][ci]
- [X] [Read the documentation][rd], especially the troubleshooting section and FAQ
- [X] Tried to add as much relevant information to the issue as possible
- [X] Verified I have tried using newest release as well
- [X] Agreed that my issue will be closed if I do not follow this template and will remain closed until I complete the template

[pi]: https://github.com/haugene/vpn-configs-contrib/issues
[ci]: https://github.com/haugene/docker-transmission-openvpn/issues
[rd]: https://haugene.github.io/docker-transmission-openvpn/

### Container version & last working release

Latest docker version (`ca2b5d2c47ff`)
 
```ca2b5d2c47ff```

*If possible, last working version:* Unknown

### Describe the problem
Fails to start when running on K3s.

**REQUIRED**
```
 kubectl logs transmission-vpn-69c57f4544-k222g
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2021/06/09 07:41:18 [emerg] 1#1: host not found in upstream "transmission" in /etc/nginx/nginx.conf:14
nginx: [emerg] host not found in upstream "transmission" in /etc/nginx/nginx.conf:14
```
### Describe the steps you have tried to solve the problem

**REQUIRED**
Contents of `/etc/nginx/nginx.conf`
```
events {
  worker_connections 1024;
}

http {

  # In case of big files
  client_max_body_size 200M;

  server {
    listen 8080;

    location / {
      proxy_pass http://transmission:9091;
      proxy_set_header Host $http_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;

      # HTTP 1.1 support
      proxy_http_version 1.1;
      proxy_set_header Connection "";
    }
    # Add extra locations for other services
    # location /<service-name> {
    #   proxy_pass http://<service-host>:<port>;
    #   proxy_set_header Host $http_host;
    #   proxy_set_header X-Real-IP $remote_addr;
    #   proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #   proxy_set_header X-Forwarded-Proto $scheme;

    #   # HTTP 1.1 support
    #   proxy_http_version 1.1;
    #   proxy_set_header Connection "";
    # }
  }

}
```

Added:
```
      hostAliases:
        - ip: "127.0.0.1"
          hostnames: 
          - "transmission"
```
To deployment spec. It now becomes ready for startup:

```
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
```

But connection refused when testing `curl localhost:9091`

### Add your docker run command or docker-compose file or env details
Docker is not installed. Here is the K3s

**REQUIRED**
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: transmission-vpn
  name: transmission-vpn
  namespace: home
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: transmission-vpn
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: transmission-vpn
    spec:
      containers:
      - env:
        - name: ServerIP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: OPENVPN_USERNAME
          valueFrom:
            secretKeyRef:
              name: transmission-vpn-secret
              key: username
        - name: OPENVPN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: transmission-vpn-secret
              key: password
        envFrom:
        - configMapRef:
            name: transmission-vpn-env-cm
        image: haugene/transmission-openvpn-proxy
        imagePullPolicy: IfNotPresent
        name: transmission-vpn
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 9091
          name: trans-http
          protocol: TCP
        - containerPort: 8080
          name: vpn-proxy
          protocol: TCP
        volumeMounts:
        - mountPath: /data
          name: transmission-vpn-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      hostAliases:
        - ip: "127.0.0.1"
          hostnames: 
          - "transmission"
      terminationGracePeriodSeconds: 30
      volumes:
      - name: transmission-vpn-data
        persistentVolumeClaim:
          claimName: transmission-vpn-claim
status: {}
```

Config Map Env vars:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: transmission-vpn-env-cm
  namespace: home
data:
  postgres.vars: |
    # LOCAL_NETWORK=10.7.0.0/16
    DISABLE_PORT_UPDATER=true # Have tried with this commented out too.
    OPENVPN_PROVIDER=NORDVPN
```

### Logs

 

**REQUIRED**
```
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up

$ curl localhost:9091
curl: (7) Failed to connect to localhost port 9091: Connection refused
```

Should also mention that I'm able to get to nginx's BAD GATEWAY page when navigating to the pod's IP and use port 8080.

### Host system

**REQUIRED**
```txt
K3s cluster. 1 master, 2 workers. MetalLB. Raspberry Pi 4 (8GB).
```

I suspect that it's because it's on K3s and nginx doesn't like K3s for some reason. Probably something to do with the domain name.
