### ISSUE TITLE
Defining Tun/Tap Device

### ISSUE THREAD

**Issue by cjchiarello** [haugene/docker-transmission-openvpn#1877]
## Before creating this issue I have:

**REQUIRED**
- [X] Read through the pinned issues for related problems
- [X] Searched for similar [provider issues][pi] and [container issues][ci]
- [X] [Read the documentation][rd], especially the troubleshooting section and FAQ
- [X] Tried to add as much relevant information to the issue as possible
- [X] Verified I have tried using newest release as well
- [X] Agreed that my issue will be closed if I do not follow this template and will remain closed until I complete the template

[pi]: https://github.com/haugene/vpn-configs-contrib/issues
[ci]: https://github.com/haugene/docker-transmission-openvpn/issues
[rd]: https://haugene.github.io/docker-transmission-openvpn/

### Container version & last working release

**Required, problem occurs in :** 
 
```3.6```

*If possible, last working version:* 
 
```<Leave empty if not known>```

### Describe the problem

**REQUIRED**
```
When Deploying updated docker image it errors out and does not deploy. giving error YOU MUST DEFINE TUN/TAP DEVICE
```
### Describe the steps you have tried to solve the problem

**REQUIRED**
```
1) I have tried rolling back to a good known state 2.10
2) I have tried rolling to 2.14 based on faq recomendation
3) I have tried adding -e OPENVPN_OPTS="--inactive 3600 --ping 10 --ping-exit 60 --dhcp-option DNS 9.9.9.9" \
```

### Add your docker run command or docker-compose file or env details

**REQUIRED**
```
docker run --cap-add=NET_ADMIN -d \
          -v /home/carmen/downloads/:/data \
          -v /etc/localtime:/etc/localtime:ro \
          -e CREATE_TUN_DEVICE=true \
          -e OPENVPN_PROVIDER=NORDVPN \
          -e OPENVPN_OPTS="--inactive 3600 --ping 10 --ping-exit 60 --dhcp-option DNS 9.9.9.9" \
          -e NORDVPN_COUNTRY=Toronto \
          -e OPENVPN_USERNAME=xxxxxxx \
          -e OPENVPN_PASSWORD=xxxxxxx \
          -e WEBPROXY_ENABLED=false \
          -e LOCAL_NETWORK=192.168.1.0/24 \
          --log-driver json-file \
          --log-opt max-size=10m \
          -p 9091:9091 \
          haugene/transmission-openvpndocker:latest
```

### Logs

 

**REQUIRED**
```
Starting container with revision: 73ec516cc246972289c7b96ffa88c81e037fe364,
Creating TUN device /dev/net/tun,
Using OpenVPN provider: NORDVPN,
Provider NORDVPN has a custom setup script, executing it,
2021-07-13 16:24:00 Checking curl installation,
2021-07-13 16:24:00 Removing existing configs,
2021-07-13 16:24:00 Selecting the best server...,
2021-07-13 16:24:00 Searching for group: legacy_p2p,
2021-07-13 16:24:00 Searching for technology: openvpn_udp,
2021-07-13 16:24:00 Best server : ca1265.nordvpn.com,
2021-07-13 16:24:00 Downloading config: default.ovpn,
2021-07-13 16:24:00 Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_udp/servers/ca1265.nordvpn.com.udp.ovpn,
curl: (6) Could not resolve host: downloads.nordcdn.com,
No VPN configuration provided. Using default.,
Modifying /etc/openvpn/nordvpn/default.ovpn for best behaviour in this container,
sed: /etc/openvpn/nordvpn/default.ovpn: No such file or directory,
sed: /etc/openvpn/nordvpn/default.ovpn: No such file or directory,
sed: /etc/openvpn/nordvpn/default.ovpn: No such file or directory,
Setting OpenVPN credentials...,
adding route to local network 192.168.1.0/24 via 172.17.0.1 dev eth0,
2021-07-13 16:24:05 Cipher negotiation is disabled since neither P2MP client nor server mode is enabled,
Options error: You must define TUN/TAP device (--dev),
Use --help for more information.
```

### Host system

**REQUIRED**
```
Docker 20.10.7 on Ubuntu 18.04
```

**Comment by pkishino** [comment]
Please don't create duplicate issues..instead edit and fix the original..
your problem is this:
curl: (6) Could not resolve host: downloads.nordcdn.com
your dns isn't resolving
both the wiki and other issues discuss solving this.
--dhcp-option DNS 9.9.9.9 doesn't do anything for this..
you can try adding
--dns x.x.x.x as a run parameter
then try curl/nslookup the nordvpn url from inside

**Comment by cjchiarello** [comment]
I have added 
`--dns 9.9.9.9 \`
still doesn't run, and if its not running I cant enter the container to run nslookup on the nordvpn url

**Comment by pkishino** [comment]
please check #1866 and try these steps
https://haugene.github.io/docker-transmission-openvpn/debug/

**Comment by cjchiarello** [comment]
@pkishino ok I have tried this and now I get this error
`2021-07-15 15:22:11 Checking curl installation
2021-07-15 15:22:11 Removing existing configs
2021-07-15 15:22:11 Selecting the best server...
2021-07-15 15:22:11 Searching for group: legacy_p2p
2021-07-15 15:22:11 Searching for technology: openvpn_udp
2021-07-15 15:22:11 Best server : ca1287.nordvpn.com
2021-07-15 15:22:11 Downloading config: default.ovpn
2021-07-15 15:22:11 Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_udp/servers/ca1287.nordvpn.com.udp.ovpn
curl: (6) Could not resolve host: downloads.nordcdn.com`

**Comment by PleaseStopAsking** [comment]
@cjchiarello I have had the same issue with recently and I am also using NordVPN (though I do not believe the issue is Nord specific). In my case, the DNS inside the container simply failed to work which was a common issue with the Alpine version used as a base from my research. To work around the issue, I manually downloaded one of the Nord connection files and manually configured my container ENVs to use it instead.

Just remember you will need to edit the .ovpn file as mentioned here.  https://haugene.github.io/docker-transmission-openvpn/supported-providers/#using_a_local_single_ovpn_file_from_provider

This has been working for me for a few months now but once the project switches back to the ubuntu base image, I will likely migrate back to the dynamic method.

Example docker-compose
```
transmission:
    cap_add:
      - NET_ADMIN
    container_name: transmission
    environment:
      - CREATE_TUN_DEVICE=true
      - OPENVPN_PROVIDER=CUSTOM
      - OPENVPN_USERNAME=${transmission_openvpn_username}
      - OPENVPN_PASSWORD=${transmission_openvpn_password}
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - WEBPROXY_ENABLED=false
      - LOCAL_NETWORK=${docker_host_network_cidr}
      - TZ=${timezone}
      - TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=false
      - TRANSMISSION_WEB_UI=flood
      - TRANSMISSION_RATIO_LIMIT=1
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
      - TRANSMISSION_WATCH_DIR_ENABLED=false
      - TRANSMISSION_LPD_ENABLED=true
      - TRANSMISSION_DOWNLOAD_QUEUE_SIZE=30
      - TRANSMISSION_HOME=${transmission_home_dir}
      - TRANSMISSION_DOWNLOAD_DIR=${transmission_downloaded_dir}
      - TRANSMISSION_INCOMPLETE_DIR=${transmission_incomplete_dir}
    hostname: transmission
    image: haugene/transmission-openvpn:3.6
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - 9091:9091
    restart: unless-stopped
    volumes:
      - transmission:/config
      - ./docker-configs/transmission/us5804.nordvpn.com.udp1194.ovpn:/etc/openvpn/custom/default.ovpn:ro
      - ${data_folder_path}:/data
```
