### ISSUE TITLE
Can't connect to WebUI

### ISSUE THREAD

**Issue by sebsebseb1982** [haugene/docker-transmission-openvpn#192]
Hi,

I'm a docker noob. I'm trying to launch this image on a Raspberry Pi. I've build the ARM dockerfile. I've made a script with these parameters :

> docker run --privileged \
>               -v /your/storage/path/:/home/pi/Downloads \
>               -v /etc/localtime:/etc/localtime:ro \
>               -e "OPENVPN_PROVIDER=TIGER" \
>               -e "OPENVPN_CONFIG=NL Amsterdam" \
>               -e "OPENVPN_USERNAME=tigerXXXXX" \
>               -e "OPENVPN_PASSWORD=YYYYYYYYYYYYY" \
>               -e "LOCAL_NETWORK=192.168.1.28/24" \
>               -p 9091:9091 \
>               fadd5b208188

But I can't access the machine WebUI neither on physical IP (192.168.1.50:9091) nor on (what I think to be) the virtual IP 192.168.1.28:9091 (LOCAL_NETWORK option).

When launching, here is the log :

> Using OpenVPN provider: TIGER
> Starting OpenVPN using config NL Amsterdam.ovpn
> Setting OPENVPN credentials...
> 2017/01/24 18:37:48 Command finished successfully.
> adding route to local network 192.168.1.28/24 via 172.17.0.1 dev eth0
> RTNETLINK answers: Invalid argument
> Tue Jan 24 18:37:49 2017 OpenVPN 2.3.4 arm-unknown-linux-gnueabihf [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [MH] [IPv6] built on Jan 23 2016
> Tue Jan 24 18:37:49 2017 library versions: OpenSSL 1.0.1t  3 May 2016, LZO 2.08
> Tue Jan 24 18:37:49 2017 WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.
> Tue Jan 24 18:37:49 2017 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
> Tue Jan 24 18:37:49 2017 UDPv4 link local (bound): [undef]
> Tue Jan 24 18:37:49 2017 UDPv4 link remote: [AF_INET]188.172.219.42:1194
> Tue Jan 24 18:37:49 2017 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
> Tue Jan 24 18:37:50 2017 [tigervpn.com] Peer Connection Initiated with [AF_INET]188.172.219.42:1194
> Tue Jan 24 18:38:03 2017 TUN/TAP device tun0 opened
> Tue Jan 24 18:38:03 2017 do_ifconfig, tt->ipv6=0, tt->did_ifconfig_ipv6_setup=0
> Tue Jan 24 18:38:03 2017 /sbin/ip link set dev tun0 up mtu 1500
> Tue Jan 24 18:38:03 2017 /sbin/ip addr add dev tun0 10.163.21.117/24 broadcast 10.163.21.255
> Tue Jan 24 18:38:03 2017 /etc/transmission/start.sh tun0 1500 1558 10.163.21.117 255.255.255.0 init
> Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.163.21.117
> Generating transmission settings.json from env variables
> 2017/01/24 18:38:03 Command finished successfully.
> 
> #-------------------------------------
> Transmission will run as
> #-------------------------------------
> User name:   root
> User uid:    0
> User gid:    0
> #-------------------------------------
> 
> STARTING TRANSMISSION
> NO PORT UPDATER FOR THIS PROVIDER
> Transmission startup script complete.
> Tue Jan 24 18:38:04 2017 Initialization Sequence Completed
> 

What could I have done wrong/not understand ?

**Comment by haugene** [comment]
Well, I see a couple of mistakes in your run command. The volume mount for your downloads should be the other way around. You should change the `/your/storage/path` part. So for you that seems to be `-v /home/pi/Downloads:/data`

Also the LOCAL_NETWORK variable should be `192.168.1.1/24`, as the `/24` then tells it to match all IP's in the range 192.168.1.1 to 192.168.1.255. But I don't think either of these errors should block you out from the network.

The UI should be accessible on the Raspberry pi IP address, don't know which of them that is, at port 9091. What IP are you trying to access them from, is it another computer in the 192.168.1.1/24 range?

What happens if you do a curl directly from the Raspberry PI? Something like `curl localhost:9091`?

**Comment by sebsebseb1982** [comment]
> Well, I see a couple of mistakes in your run command. The volume mount for your downloads should be the other way around. You should change the /your/storage/path part. So for you that seems to be -v /home/pi/Downloads:/data
> 
> Also the LOCAL_NETWORK variable should be 192.168.1.1/24, as the /24 then tells it to match all IP's in the range 192.168.1.1 to 192.168.1.255. But I don't think either of these errors should block you out from the network.

Thank you for your answer. I've corrected theses errors.

> The UI should be accessible on the Raspberry pi IP address, don't know which of them that is, at port 9091. What IP are you trying to access them from, is it another computer in the 192.168.1.1/24 range?

I'm trying to access it form a computer with IP 192.168.1.12. Can you confirm me that UI should be accessible on the RPi physical IP (192.168.1.50) ?

> What happens if you do a curl directly from the Raspberry PI? Something like curl localhost:9091?

<h1>301: Moved Permanently</h1>

Webserver seems to be up ! But I can't access it form outside ... Could it be a problem of IP Route or Transmission's whitelist parameter ?

**Comment by sebsebseb1982** [comment]
To be more precise : 

Raspberry Pi physical address = 192.168.1.50
Transmission port = 9091
On my router, I've forwarded 29091 (external) on 9091 (internal).

With my mobile phone on Wifi (192.168.1.x IP), I can access the UI on both 192.168.1.50:9091 and [my public dns]:29091.
On my mobile carrier network, I can't access the UI on [my public dns]:29091.

**Comment by haugene** [comment]
As long as you're on wifi your address is in the 192.168.1.1/24 range and the traffic will be routed to the local network. When you're not on wifi you have an IP outside that range and the response is routed through the vpn interface and when it reaches your client it won't accept it as it comes from another IP.

For my setup it still works because my router/NAT will set itself as source when forwarding traffic to the container. I guess your router behaves differently.

You could try the solution using the proxy container, that will work across networks. It's documented in the readme as well.

**Comment by Delvien** [comment]
I'm having the same issue, but your "fix" in response to the OP didnt work for me. 

docker run --privileged  -d \
              -v /media/xxxxx/Torrents/:/data \
              -v /etc/localtime:/etc/localtime:ro \
              -e "LOCAL_NETWORK=192.168.1.1/24"  \
              -e "OPENVPN_PROVIDER=PIA" \
              -e "OPENVPN_CONFIG=Sweden" \
              -e "OPENVPN_USERNAME=xxxxx" \
              -e "OPENVPN_PASSWORD=xxxxxx" \
              -p 9091:9091 \
              haugene/transmission-openvpn

This is my opening command, I cannot access the web interface via the IP to the server thats running the docker.

**Comment by sebsebseb1982** [comment]
try -e "LOCAL_NETWORK=192.168.1.**0**/24"  \ and wait 1 minute that docker container is fully started

**Comment by Delvien** [comment]
I went around that and ran it with --net-host, which worked like a charm. Whats the difference?

**Comment by jchaps** [comment]
Just wanted to jump in and provide some info on this error (in case relevant to others searching).

I'm running on a Mac. Mac runs docker inside a virtual machine, so the "host" is the virtual machine, not the Mac itself. 

I had to use the reverse proxy, and find the host IP (the virtual machine's IP) by running `echo $DOCKER_HOST` in Terminal on the Mac (result was 192.168.99.100). I was then finally able to connect from my Mac at http://192.168.99.100:8080.  

Haven't yet figured out how to connect from other machines on my network...

**Comment by haugene** [comment]
If you want to reach it from other machines you also have to forward the traffic from some port on your mac to the 8080 port on the VM. Either by setting some properties in the VM that binds it to the host on startup, or with another proxy. If you use Docker for Mac, instead of boot2docker you shouldn't have to do this. Docker can run natively on Mac.

@Delvien Running with --net=host would mean that the process in the container joins the network stack of your host, not a virtual interface for the container. This would probably mean that you're passing all your traffic from the server through the VPN now, not just the container?

**Comment by desimaniac** [comment]
Older Mac's are stuck with Docker Toolbox (ie boot2docker) because native VM support is disabled.

**Comment by rourke** [comment]
I can't connect to the WebUI either. I'm running this on a VPS, so it's directly exposed to the internet. My docker-compose.yml for this container looks like this:

```
  transmission:
    image: haugene/transmission-openvpn
    container_name: transmission
    privileged: true
    restart: always
    ports:
      - "9091:9091"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - plexnet
    environment:
      - PUID=1000
      - PGID=1000
      - OPENVPN_PROVIDER=${VPN_PROVIDER}
      - OPENVPN_CONFIG=${VPN_CONFIG}
      - OPENVPN_USERNAME=${VPN_USERNAME}
      - OPENVPN_PASSWORD=${VPN_PASSWORD}
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=46.255.125.216/32
    volumes:
      - ${MOUNT_POINT}/downloads:/data
      - /etc/localtime:/etc/localtime:ro
...
networks:
  plexnet:
    driver: bridge
```

Here is an `ifconfig`. There are more networks but they aren't important right?

```
ens3      Link encap:Ethernet  HWaddr fa:16:3c:0f:4e:b4
          inet addr:46.255.125.216  Bcast:46.255.125.216  Mask:255.255.255.255
          inet6 addr: fe81::f846:3eff:fc0c:4cb4/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:97459776 errors:0 dropped:0 overruns:0 frame:0
          TX packets:53300418 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:126205555903 (126.2 GB)  TX bytes:73630817701 (73.6 GB)
```

I changed the IP addresses so the above is an example

**Comment by underpickled** [comment]
I'm having a similar problem... I can access transmission through port 9091 locally (freenas.local:9091), but using my DDNS address with port 9091 it never connects and eventually times out. Port forwarding is definitely set up for my router to forward 9091 ext to 9091 int, and my DDNS works for every other forwarded port. Is what I'm seeing here that I need to pick a different port that NordVPN (my provider) will forward and have that external port forwarded to 9091 internal?

**Comment by rourke** [comment]
I also tried the proxy so my compose file looks like this:

```
  transmission:
    image: haugene/transmission-openvpn
    container_name: transmission
    privileged: true
    restart: always
    ports:
      - "9091:9091"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - plexnet
    environment:
      - PUID=1000
      - PGID=1000
      - OPENVPN_PROVIDER=${VPN_PROVIDER}
      - OPENVPN_CONFIG=${VPN_CONFIG}
      - OPENVPN_USERNAME=${VPN_USERNAME}
      - OPENVPN_PASSWORD=${VPN_PASSWORD}
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=46.255.125.216/32
    volumes:
      - ${MOUNT_POINT}/downloads:/data
      - /etc/localtime:/etc/localtime:ro

  proxy:
    image: haugene/transmission-openvpn-proxy
    container_name: transmission-proxy
    links:
      - transmission
    ports:
      - 8080:8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
```

But transmission-openvpn-proxy logs:

```
2017-04-17T19:44:35.697021994Z 2017/04/17 21:44:35 [emerg] 1#1: host not found in upstream "transmission" in /etc/nginx/nginx.conf:11
2017-04-17T19:44:35.697049488Z nginx: [emerg] host not found in upstream "transmission" in /etc/nginx/nginx.conf:11
```

This is completely stopping me from continuing using transmission. I rather use less containers though, only if it is necessary. @haugene Could you help out?

**Comment by underpickled** [comment]
Actually, now I can't even connect to the WebUI locally...

**Comment by Resonantmango** [comment]
Was having the same issue - just wanted to leave how I solved it.

I am running this as a service and making the modifications to the `/etc/systemd/system/transmission-openvpn.service` file wasn't helping. I would `systemctl daemon-reload` to load the changes, then `systemctl restart transmission-openvpn.service` to (supposedly) restart the container.

However, I had to go and manually stop the container through docker, i.e. `docker stop transmission-openvpn`, and then `systemctl start transmission-openvpn.service` finally gained me access to the webui from another PC on the LAN. 

No idea if this helps anything, just figured I'd leave my "solution"..

**Comment by haugene** [comment]
@underpickled I'm guessing this has to do with how your router does the port forwarding. If it lets the packets through without changing the source IP (like in NAT) then the remote IP seen by transmission is not your router (which is within LOCAL_NETWORK address scope) but instead the remote machine itself. 

Sending a response to that IP would mean setting destination IP outside of LOCAL_NETWORK and the traffic would be routed through the VPN interface. The packets would probably make it to your device but it will deny them as it does not know the origin (now your VPN address).

As the original issue here is solved, and then another one came and that is solved, and now this... I'm closing this issue and advising you to try setting up the proxy container described in the readme. When the traffic goes through the proxy, all packets to/from the transmission container will be treated as local and it doesn't matter where the real remote machine is.

If that doesn't work, create a new issue and detail your findings so far. Good luck! :)

**Comment by ethanopp** [comment]
@haugene - I realize this is old but just experienced the first issue (not being able to see web UI) mentioned in this thread, and was able to solve it by following the tip from @Delvien, "-net=host"

Is there any downside to using this parameter? Can it compromise the VPN connection at all and expose the hosts true IP?

**Comment by haugene** [comment]
@ethanopp Nah, the VPN connection should be good and the killswitch still active. 

The downside would be that you're then running the VPN on your host network. So all traffic from your host machine will be routed through the VPN.

**Comment by ethanopp** [comment]
@haugene ALL traffic would run through VPN or just traffic on that port? (I'm using `-p 9091:9091`)

Ideally I would like to avoid using the `-net=host` flag if there is another setting I can use to get the web interface working again...

For reference, I have been running this docker for almost 2 years now completely fine on my QNAP TVS-473, but QNAP just did a firmware upgrade (4.3.5) where Container Station & the Network & Virtual switches got redone, which is now causing the the issue with loading the front end...So I am expecting a lot of other people running on qnap may experience this soon...

...I think it has something to do with the IPs that the dockers in container station run on. Not sure how familiar you are with Container Station, but it sets up its own sort of IP network via virtual switches/adapters for the containers to communicate on (10.0.3.1 & 10.0.5.1) so for example in my Sonnar container when I reference transmission I use **10.0.3.1**:9091 (instead of 192.168.x.x:9091) - which does still work as Sonarr can still connect to transmission (with and without the -net='host' flag). When I access Sonarr & transmission on a laptop on the LAN, I just use 192.168.x.x:9091 & 192.168.x.x:8989, however transmission web interface now gives a 'server not responding' error at 192.168.x.x:9091.

The entire container is still working - things are still getting downloaded, I just cant access the web interface 192.168.x.x:9091.

Any ideas?

**Comment by ethanopp** [comment]
@haugene Thanks for the tip... got it working with the following:
`docker run -d --name=Transmission-AirVPN-Web --restart=always \
--link Transmission-AirVPN:transmission \
-p 8888:8080 \
haugene/transmission-openvpn-proxy`

Just out of curiosity, is this the only way to do it... 2 separate containers?

Would be nice to just keep everything in 1 container if possible - not the end of the world if it cant be done in 1 though

**Comment by haugene** [comment]
Not the only way to do it, of course. But by far the simplest and most universal solution.

There are so many networking setups out there and people either have to understand and make their ip-table rules to manoeuvre their own setup, or you can punch a hole in it with the proxy.

The problem is, as the README states, that the traffic from the web-ui that are on it's way to you (192.168.1.X) are sent out through the VPN connection. And then they never arrive of course because it's not a public IP. This would not happen on a local setup because OpenVPN adds routes for the local network ensuring that others addresses on the same network is still accessible.

Inside container networking, the local network is something like 172.17.X.X and your address is suddenly outside that. But another container would be on the same container network, and therefore not affected. And it will not have vpn running inside it and therefore accept connections from anywhere.

So, you can configure ip tables rules for your host, docker vm, container, etc and get the packages where they need to go. Or just run a proxy.

**Comment by ethanopp** [comment]
Fair enough  - I don't trust myself enough to play with the ip tables so 2 containers it is!

Thanks

**Comment by ethanopp** [comment]
Sorry to open this one last time... I just switched over to docker-compose and it seems the proxy isn't working now? No text for errors in the console... page just isn't loading. Any ideas?

```
  transmissionairvpn:
    image: haugene/transmission-openvpn
    container_name: transmission-airvpn
    restart: always
    privileged: true
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "9091:9091"
    env_file: 
      - /share/CACHEDEV1_DATA/Container/Transmission-AirVPN/DockerEnv
    volumes:
      - /share/CACHEDEV1_DATA/Library/Downloads:/data
      - /share/CACHEDEV1_DATA/Library:/library
      - /share/CACHEDEV1_DATA/Container/Transmission-AirVPN/config.ovpn:/etc/openvpn/custom/default.ovpn
      - /share/CACHEDEV1_DATA/Container/Transmission-AirVPN:/config
      - /etc/localtime:/etc/localtime:ro
  transmissionairvpnweb:
    image: haugene/transmission-openvpn-proxy
    container_name: transmission-airvpn-web
    restart: always
    depends_on:
      - transmissionairvpn
    links:
      - transmissionairvpn:transmission
    ports:
      - "8888:8000"
    environment:
      - PUID=1001
      - PGID=100
```
