### ISSUE TITLE
Internal IP sometimes changes after recreating image

### ISSUE THREAD

**Issue by phillipgreenii** [haugene/docker-transmission-openvpn#1943]
### Is there a pinned issue for this?

- [X] I have read the pinned issues

### Is there an existing or similar issue for this?

- [X] I have searched the existing issues

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [ ] I have tried using dev branch

### Config used

```yaml
version: '3.8'

services:
    transmission-openvpn:
        image: haugene/transmission-openvpn:3.7.1
        container_name: transmission-openvpn
        volumes:
            - ${DOWNLOAD_ROOT}/:/data
            - /etc/localtime:/etc/localtime:ro
            - /etc/vpn/:/etc/openvpn/custom/
        environment:
            - PGID=${PGID}
            - PUID=${PUID}
            - CREATE_TUN_DEVICE=true
            - OPENVPN_PROVIDER=custom
            - OPENVPN_CONFIG=str-clt301_a344131
            - OPENVPN_USERNAME=xxx
            - OPENVPN_PASSWORD=xxx
            - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
            - WEBPROXY_ENABLED=false
            - LOCAL_NETWORK=192.168.2.0/24,192.168.10.0/24
            - TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=false
            - DNS=8.8.8.8,8.8.4.4
        cap_add:
            - NET_ADMIN
        devices:
            - /dev/net/tun
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - 9091:9091
            - 9117:9117
            - 7878:7878
            - 8989:8989
            - 8686:8686
            - 6767:6767
            - 5299:5299
            - 3579:3579
        restart: unless-stopped
                max-size: 10m
        ports:
            - 9091:9091
            - 9117:9117
            - 7878:7878
            - 8989:8989
            - 8686:8686
            - 6767:6767
            - 5299:5299
            - 3579:3579
        restart: unless-stopped
    jackett:
        image: linuxserver/jackett:version-v0.18.656
        container_name: jackett
        network_mode: "service:transmission-openvpn"
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - AUTO_UPDATE=false
        volumes:
            - ${DATA_ROOT}/jackett:/config
            - ${DOWNLOAD_ROOT}/watch:/downloads
        restart: unless-stopped
```
### Current Behavior

I have `transmission-openvpn` working with docker-compose.  Included in the docker-compose is other tools as well, `jackett`, `sonarr`, ...  As I am working on my setup I open need to run `docker-compose up -d` which may recreate the `transmission-openvpn` container.  When this happens, the internal IP changes.  This causes a problem because the other containers refer to this container by ip address.

### Expected Behavior

Have a consistent ip address (perhaps `172.22.0.2`) each time the container is created by default.  If doing it by default is a problem, them perhaps allow for an environment variable to force it.

### How have you tried to solve the problem?

1) The ip is similar to `172.22.0.2` each time, but not the same.  I have queried for variations of the ip in the repository, both code and issues.
2) I checked environment variables and saw no way to set it manually.

### Log output

N/A

### Environment

```markdown
- OS: RancherOS 1.5.8
- Docker: 20.10.8
```

**Comment by pkishino** [comment]
this is a docker issue, not this container.. 
you need to create a network with a fixed ip instead of using the default docker network..
this is how I do it..just showing relevant parts
```yaml
version: '3.3'
services:
    transmission-openvpn:
        ...
        image: haugene/transmission-openvpn:dev
        restart: unless-stopped
        networks:
          transmission:
            ipv4_address: 172.20.10.10
networks:
  transmission:
    name: transmission
    driver: bridge
    ipam:
      config:
        - subnet: "172.20.10.0/24"
```
