### ISSUE TITLE
Docker network conflicts when stack is deployed that has docker-transmission-openvpn and other media apps (sabnzb, sonarr, ...)

### ISSUE THREAD

**Issue by juan9999** [haugene/docker-transmission-openvpn#2008]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [ ] I have tried using dev branch

### Config used

[docker.yaml.txt](https://github.com/haugene/docker-transmission-openvpn/files/7335536/docker.yaml.txt)

### Current Behavior

I'm having an issue with docker on ubuntu 20.04 with apparent conflict between networks and network shares.
I have a docker stack that has openvpn, transmission, sabnzb, sonar (all routed through the vpn).
When the stack is not running, my mounted network share drive (where I save my downloads) works great. When the stack is running, I get a bunch of server disconnects within docker, and get a bunch of CIFS VFS errors and slow response/time outs if I try to say do a ls on a NAS share.
When I delete that stack, suddenly the network share works fine again.
This WAS working fine until a few weeks ago.
how can I fix/troubleshoot?

### Expected Behavior

No NAS share issues 

### How have you tried to solve the problem?

See steps above

### Log output

<img width="776" alt="Screen Shot 2021-10-12 at 6 13 29 PM" src="https://user-images.githubusercontent.com/31065728/137080360-ab264ff6-fc87-4609-992a-4d04aacb57b5.png">

### Environment

```markdown
- OS:Ubuntu 20.04
- Docker: 20.10.7
```

**Comment by pkishino** [comment]
have you tried reverting to 3.7.1 ? 
what happened a few weeks ago? check user permissions?

**Comment by pkishino** [comment]
By recreating the container but specify :3.7.1 as the tag instead of: latest
Network drives should be fine though, haven’t seen any issues using them
myself

**Comment by juan9999** [comment]
Correct. On alpine I only tested with latest and since that worked, I didn't bother with 3.7.1.

With the same resource allocation, so not sure if it's alpine that uses less resources, or if it's the implementation of docker, or ...

**Comment by pkishino** [comment]
Ah, cool.
I’ll see if I can dig up something when I have time

**Comment by gist901** [comment]
I would suggest creating your  own Docker network and connecting your containers to it. Don't rely on Docker to create the network.

Might looks something like this for example:

```
version: '2'

services:

  vpn:
    container_name: vpn
    image: haugene/transmission-openvpn:latest
    networks:
      vpn_net:
        ipv4_address: 10.0.0.2

  sonar:
    container_name: sonarr
    image: linuxserver/sonarr
    depends_on:
      - vpn
    network_mode: service:vpn

networks:
  vpn_net:
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.0.0/29
  ```
