### ISSUE TITLE
possibly incorrect debug message says it cannot locate key and cert files

### ISSUE THREAD

**Issue by asignorino** [haugene/docker-transmission-openvpn#2012]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [ ] I have tried using dev branch

### Config used
```
version: "3.7"

########################### SERVICES
services:
  transmission:
   image: haugene/transmission-openvpn:latest
   command: tail -F anything # holds container open to inspect when it crashes
   cap_add:
     - NET_ADMIN  # This runs the container with raised privileges
   devices:
     - /dev/net/tun # Creates a tunnel for Transmission
#  restart: always
   ports:
     - "9091:9091"
   dns:
     - 8.8.8.8
     - 8.8.4.4
   volumes:
     - /volume1/homes/sigs/transmission:/data
     - /etc/localtime:/etc/localtime:ro
     - /volume1/docker/torrent_config/config:/etc/openvpn/custom/
   environment:
     - CREATE_TUN_DEVICE=true
     - OPENVPN_PROVIDER=custom
     - OPENVPN_USERNAME=user  #I'm using an openvpn config file, so user/pass aren't read, but container still requires these variables
     - OPENVPN_PASSWORD=pass
     - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
     - LOCAL_NETWORK=192.168.1.0/24 # If your server's IP address is 192.168.1.x, then use this. If your server's IP address is 192.168.0.x, then change to 192.168.0.0/24
     - TRANSMISSION_WEB_UI=flood
     - PUID=1260
     - PGID=100
     - HEALTH_CHECK_HOST="google.com"
```

Files for /volume1/docker/torrent_config/config:
* ca.crt
* default.ovpn
* signorino.csr
* keys:
  * signorino.crt  
  * signorino.key  
  * tls-auth.key
All of these files are in user:group = sigs:users = 1260:100
I've tried with root, just to match the group in the container, but everything gets the same results.

### Current Behavior

Output from logs reports
```
transmission_1  | Setting OpenVPN credentials...
transmission_1  | adding route to local network 192.168.1.0/24 via 172.23.0.1 dev eth0
transmission_1  | Options error: --cert fails with 'keys/signorino.crt': No such file or directory (errno=2)
transmission_1  | Fri Oct 15 08:10:07 2021 WARNING: cannot stat file 'keys/signorino.key': No such file or directory (errno=2)
transmission_1  | Options error: --key fails with 'keys/signorino.key': No such file or directory (errno=2)
transmission_1  | Fri Oct 15 08:10:07 2021 WARNING: cannot stat file 'keys/tls-auth.key': No such file or directory (errno=2)
transmission_1  | Options error: --tls-auth fails with 'keys/tls-auth.key': No such file or directory (errno=2)
transmission_1  | Options error: Please correct these errors.
transmission_1  | Use --help for more information.
``` 

But I verified they are in the container, and appear as they should. I'm confused if I'm doing something else wrong with permissions, or if the error message is purely a red herring.

### Expected Behavior

At this point, I just have no idea why it's not running as expected.

### How have you tried to solve the problem?

I have it working on my old ubuntu server with all of the cert and key files in the Config Directory, and that works. (Which this doesn't make any sense, given the error message that my current container is outputting)

I recently upgraded to Synology, and was trying on that, I saw some of the other issues about the tunnel device. I think I got that working, but got to the point where I'm hitting this current issue.

After that, I tried on another ubuntu laptop to see if I can get it working on another computer. I am running into the same error message either way I try to organize the files and keys.

I have verified files on everything, the permissions appear to be open more than needed and still receiving the same message. As stated above, when I uncomment the command to leave the container hanging and exec into the container, the files appear as expected and I can read the files if I `cat` them.

/etc/openvpn/custom:
* ca.crt
* default.ovpn
* signorino.csr
* keys:
  * signorino.crt  
  * signorino.key  
  * tls-auth.key

### Log output

```
Attaching to torrent_config_transmission_1
transmission_1  | Starting container with revision: ace9c70feef9469792dca653f504df0b614b761d
transmission_1  | WARNING: initial DNS resolution test failed
transmission_1  | Creating TUN device /dev/net/tun
transmission_1  | mknod: /dev/net/tun: File exists
transmission_1  | Using OpenVPN provider: CUSTOM
transmission_1  | Running with VPN_CONFIG_SOURCE auto
transmission_1  | No bundled config script found for CUSTOM. Defaulting to external config
transmission_1  | Downloading configs from https://github.com/haugene/vpn-configs-contrib/archive/main.zip into /tmp/tmp.jaak2944al
transmission_1  | Extracting configs to /tmp/tmp.lwQHtpgWha
transmission_1  | ERROR: Could not find any configs for provider CUSTOM in downloaded configs
transmission_1  | Cleanup: deleting /tmp/tmp.jaak2944al and /tmp/tmp.lwQHtpgWha
transmission_1  | No VPN configuration provided. Using default.
transmission_1  | Modifying /etc/openvpn/custom/default.ovpn for best behaviour in this container
transmission_1  | Modification: Point auth-user-pass option to the username/password file
transmission_1  | Modification: Change ca certificate path
transmission_1  | Modification: Change ping options
transmission_1  | Modification: Update/set resolv-retry to 15 seconds
transmission_1  | Modification: Change tls-crypt keyfile path
transmission_1  | Modification: Set output verbosity to 3
transmission_1  | Modification: Remap SIGUSR1 signal to SIGTERM, avoid OpenVPN restart loop
transmission_1  | Setting OpenVPN credentials...
transmission_1  | adding route to local network 192.168.1.0/24 via 172.22.0.1 dev eth0
transmission_1  | Options error: --cert fails with 'keys/signorino.crt': No such file or directory (errno=2)
transmission_1  | Thu Oct 14 10:22:43 2021 WARNING: cannot stat file 'keys/signorino.key': No such file or directory (errno=2)
transmission_1  | Options error: --key fails with 'keys/signorino.key': No such file or directory (errno=2)
transmission_1  | Thu Oct 14 10:22:43 2021 WARNING: cannot stat file 'keys/tls-auth.key': No such file or directory (errno=2)
transmission_1  | Options error: --tls-auth fails with 'keys/tls-auth.key': No such file or directory (errno=2)
transmission_1  | Options error: Please correct these errors.
transmission_1  | Use --help for more information.
```

### Environment

```markdown
- OS: Synology DSM7.0 and Ubuntu 21.04
- Docker: 20.10.3
```

### Anything else?

I'm hoping, everything I wrote down makes sense. I've been playing with this for days, but keep hitting the same wall. Part of me is thinking this is user error somewhere, but I just can't see where since this is the only debug message that seems off.
