### ISSUE TITLE
Container randomly stops after a few minutes due rpc-authentication-required

### ISSUE THREAD

**Issue by VMBindraban** [haugene/docker-transmission-openvpn#2014]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [X] I have tried using dev branch

### Config used

```
version: '3.3'

services:
  transmission:
    image: haugene/transmission-openvpn:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - 9091:9091
    environment:
      - LOCAL_NETWORK=192.168.1.0/24
      - OPENVPN_USERNAME=***
      - OPENVPN_PASSWORD=***
      - OPENVPN_PROVIDER=NORDVPN
      - CREATE_TUN_DEVICE=true
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60 --pull-filter ignore ping
      - NORDVPN_COUNTRY=nl
      - TRANSMISSION_DOWNLOAD_DIR=/data/downloads/completed
      - TRANSMISSION_HOME=/config/home
      - TRANSMISSION_INCOMPLETE_DIR=/data/downloads/incomplete
    volumes:
      - /volume3/docker/transmission-openvpn/config:/config
      - /volume3/docker/transmission-openvpn/resolv.conf:/etc/resolv.conf:ro
      - /volume5/plex/:/data
    network_mode: bridge
    mem_limit: 1024m
```

### Current Behavior

I am getting reports from my NAS that the container keeps crashing.

### Expected Behavior

Don't crash :)

### How have you tried to solve the problem?

The fix was caused by setting `rpc-authentication-required` to `false`.
As you can see in the logs, it suddenly just `Port Forwarding Stopped`.

### Log output
```
[2021-10-17 08:39:01.371] Transmission 2.94 (d8e60ee44f) started (session.c:740)
[2021-10-17 08:39:01.371] RPC Server Adding address to whitelist: 192.168.1.* (rpc-server.c:971)
[2021-10-17 08:39:01.371] RPC Server Adding address to whitelist: 127.0.0.1 (rpc-server.c:971)
[2021-10-17 08:39:01.371] RPC Server Adding address to whitelist: ::1 (rpc-server.c:971)
[2021-10-17 08:39:01.371] RPC Server Serving RPC and Web requests on port 127.0.0.1:9091/transmission/ (rpc-server.c:1213)
[2021-10-17 08:39:01.371] Port Forwarding Stopped (port-forwarding.c:180)
[2021-10-17 08:39:01.371] DHT Reusing old id (tr-dht.c:307)
[2021-10-17 08:39:01.371] DHT Bootstrapping from 106 IPv4 nodes (tr-dht.c:156)
[2021-10-17 08:39:01.371] Using settings from "/config/home" (daemon.c:528)
[2021-10-17 08:39:01.371] Saved "/config/home/settings.json" (variant.c:1266)
[2021-10-17 08:39:01.371] Watching "/data/watch" for new .torrent files (daemon.c:573)
[2021-10-17 09:30:13.573] Saved "/config/home/settings.json" (variant.c:1266)
[2021-10-17 09:30:13.573] DHT Saving 119 (119 + 0) nodes (tr-dht.c:369)
[2021-10-17 09:30:13.573] Saved "/config/home/dht.dat" (variant.c:1266)
[2021-10-17 09:30:13.573] Port Forwarding Stopped (port-forwarding.c:180)
```
### Environment

```markdown
- OS: Synology DSM 7
- Docker: 20.10.3
```

### Anything else?

Transmission settings:

```
{
    "alt-speed-down": 50,
    "alt-speed-enabled": false,
    "alt-speed-time-begin": 540,
    "alt-speed-time-day": 127,
    "alt-speed-time-enabled": false,
    "alt-speed-time-end": 1020,
    "alt-speed-up": 50,
    "bind-address-ipv4": "10.8.1.7",
    "bind-address-ipv6": "::",
    "blocklist-enabled": false,
    "blocklist-url": "http://www.example.com/blocklist",
    "cache-size-mb": 4,
    "dht-enabled": true,
    "download-dir": "/data/downloads/completed",
    "download-queue-enabled": true,
    "download-queue-size": 5,
    "encryption": 1,
    "idle-seeding-limit": 0,
    "idle-seeding-limit-enabled": true,
    "incomplete-dir": "/data/downloads/incomplete",
    "incomplete-dir-enabled": true,
    "lpd-enabled": false,
    "message-level": 2,
    "peer-congestion-algorithm": "",
    "peer-id-ttl-hours": 6,
    "peer-limit-global": 240,
    "peer-limit-per-torrent": 60,
    "peer-port": 51413,
    "peer-port-random-high": 65535,
    "peer-port-random-low": 49152,
    "peer-port-random-on-start": false,
    "peer-socket-tos": "default",
    "pex-enabled": true,
    "port-forwarding-enabled": false,
    "preallocation": 1,
    "prefetch-enabled": true,
    "queue-stalled-enabled": true,
    "queue-stalled-minutes": 30,
    "ratio-limit": 0,
    "ratio-limit-enabled": true,
    "rename-partial-files": true,
    "rpc-authentication-required": false,
    "rpc-bind-address": "0.0.0.0",
    "rpc-enabled": true,
    "rpc-host-whitelist": "192.168.1.*",
    "rpc-host-whitelist-enabled": false,
    "rpc-password": "***",
    "rpc-port": 9091,
    "rpc-url": "/transmission/",
    "rpc-username": "***",
    "rpc-whitelist": "127.0.0.1,::1",
    "rpc-whitelist-enabled": false,
    "scrape-paused-torrents-enabled": true,
    "script-torrent-done-enabled": false,
    "script-torrent-done-filename": "",
    "seed-queue-enabled": false,
    "seed-queue-size": 10,
    "speed-limit-down": 100,
    "speed-limit-down-enabled": false,
    "speed-limit-up": 100,
    "speed-limit-up-enabled": false,
    "start-added-torrents": true,
    "trash-original-torrent-files": false,
    "umask": 2,
    "upload-slots-per-torrent": 14,
    "utp-enabled": false,
    "watch-dir": "/data/watch",
    "watch-dir-enabled": true,
    "watch-dir-force-generic": false
}
```
