### ISSUE TITLE
Inactivity Timeout - constant container restarts

### ISSUE THREAD

**Issue by fabge** [haugene/docker-transmission-openvpn#2063]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [ ] My issue is NOT related to a provider (cannot rule out a quality of service decline from NordVPN, but tried different countries)

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [X] I have tried using dev branch

### Config used

docker compose yaml used:
```yaml
  torrent:
    image: haugene/transmission-openvpn:latest
    container_name: torrent
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    volumes:
      - ${CONFIG}/transmission-openvpn/resume:/data/transmission-home/resume
      - ${CONFIG}/transmission-openvpn/torrents:/data/transmission-home/torrents
      - ${ROOT}/downloads/incomplete:/data/incomplete
      - ${ROOT}/downloads/completed:/data/completed
      - ${ROOT}/downloads/torrent-blackhole:/data/watch
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - OPENVPN_PROVIDER=NORDVPN
      - OPENVPN_USERNAME=${NORDVPN_USERNAME}
      - OPENVPN_PASSWORD=${NORDVPN_PASSWORD}
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=192.168.1.0/24
      - NORDVPN_COUNTRY=DE
      - NORDVPN_CATEGORY=legacy_p2p
      - NORDVPN_PROTOCOL=udp
      - GLOBAL_APPLY_PERMISSIONS=false
      - TRANSMISSION_WEB_UI=flood-for-transmission
      - TRANSMISSION_DOWNLOAD_QUEUE_SIZE=20
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - 9091:9091
    dns:
      - 1.1.1.1
```

### Current Behavior

The container boots and sets up correctly, the UI is working and also successfully downloading from seeders. After some time (~5-50 minutes) the container terminates, always with the same error (see below).

### Expected Behavior

The container boots, starts downloading and doesn't restart constantly.

### How have you tried to solve the problem?

1) Tried the :dev tag release
2) Verified the container can resolve DNS
3) Checked ovpn configuration
4) Checked settings.json
5) Tried setting `OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60` as described in the [docs](https://haugene.github.io/docker-transmission-openvpn/faq/#set_the_ping-exit_option_for_openvpn_and_restart-flag_in_docker)

### Log output

```
STARTING TRANSMISSION
Transmission startup script complete.
Thu Nov  4 17:37:26 2021 /sbin/ip route add 80.246.28.33/32 via 172.18.0.1
Thu Nov  4 17:37:26 2021 /sbin/ip route add 0.0.0.0/1 via 10.8.1.1
Thu Nov  4 17:37:26 2021 /sbin/ip route add 128.0.0.0/1 via 10.8.1.1
Thu Nov  4 17:37:26 2021 Initialization Sequence Completed
Thu Nov  4 17:53:32 2021 [al19.nordvpn.com] Inactivity timeout (--ping-restart), restarting
Thu Nov  4 17:53:32 2021 SIGTERM received, sending exit notification to peer
Thu Nov  4 17:53:33 2021 /etc/openvpn/tunnelDown.sh tun0 1500 1585 10.8.1.6 255.255.255.0 init
resolv.conf was restored
Sending kill signal to transmission-daemon
Waiting 5s for transmission-daemon to die
Sending kill signal (SIGKILL) to transmission-daemon
Thu Nov  4 17:53:38 2021 /sbin/ip route del 80.246.28.33/32
Thu Nov  4 17:53:38 2021 /sbin/ip route del 0.0.0.0/1
Thu Nov  4 17:53:38 2021 /sbin/ip route del 128.0.0.0/1
Thu Nov  4 17:53:38 2021 Closing TUN/TAP interface
Thu Nov  4 17:53:38 2021 /sbin/ip addr del dev tun0 10.8.1.6/24
Thu Nov  4 17:53:38 2021 SIGTERM[soft,exit-with-notification] received, process exiting
```

### Environment

```markdown
- OS: macOs Monterey Version 12.0.1 (21A559)
- Docker: Docker version 20.10.8, build 3967b7d
```
