### ISSUE TITLE
WebUI stops working after a few minutes downloading

### ISSUE THREAD

**Issue by Jannomag** [haugene/docker-transmission-openvpn#2125]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [X] I have tried using dev branch

### Config used

Running as service with:
```
[Unit]
Description=haugene/transmission-openvpn docker container
After=docker.service
Requires=docker.service

[Service]
User=jan
Type=forking
TimeoutStartSec=0
ExecStartPre=-/usr/bin/docker kill transmission-openvpn
ExecStartPre=-/usr/bin/docker rm transmission-openvpn
ExecStartPre=/usr/bin/docker pull haugene/transmission-openvpn
ExecStart=/usr/bin/docker run \
        --name transmission-openvpn \
        --cap-add=NET_ADMIN -d \
        -v /etc/localtime:/etc/localtime:ro \
        -v /pladde/Downloads/:/data \
        -e CREATE_TUN_DEVICE=true \
        -e "OPENVPN_PROVIDER=SURFSHARK" \
        -e "OPENVPN_USERNAME=CREDENTIALS" \
        -e "OPENVPN_PASSWORD=CREDENTIALS" \
        -e "OPENVPN_CONFIG=dk-cph_tcp" \
        -e WEBPROXY_ENABLED=false \
        -e "OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60" \
        -e LOCAL_NETWORK=192.168.1.0/24 \
        -e "TRANSMISSION_WEB_UI=flood-for-transmission" \
        -e PUID=1001 \
        -e PGID=1001 \
        --dns 8.8.8.8 \
        --dns 8.8.4.4 \
        -p 9091:9091 \
        haugene/transmission-openvpn
ExecStop=/usr/bin/docker kill transmission-openvpn
ExecStopPost=-/usr/bin/docker rm transmission-openvpn
RemainAfterExit=yes
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
```

### Current Behavior

Starting the service and transmission starts fine. It takes a bit until web ui is reachable but after a minute or so it works.
I can start a torrent and it starts downloading as well.

But after a while, like 3-5 minutes, transmission isn't reachable via web ui or remote guis like BarMagnet or the GUI for Windows.
Also no download traffic anymore.

No errors in `docker logs` or in transmission.log at all.

It already worked but for a few days it doesn't. I didn't change anything.

### Expected Behavior

Everything should work even after a few minutes...

### How have you tried to solve the problem?

1) Tried dev
2) Tried 3.7.1
3) Tried removing the docker container completely
4) Tried with new clean and bare setup
5) Permissions are checked and correct

### Log output

```
Starting container with revision: 76f7a2ce2957c1b48d5dee0c713a3d15903a5905
Creating TUN device /dev/net/tun
Using OpenVPN provider: SURFSHARK
Running with VPN_CONFIG_SOURCE auto
No bundled config script found for SURFSHARK. Defaulting to external config
Downloading configs from https://github.com/haugene/vpn-configs-contrib/archive/main.zip into /tmp/tmp.WVxcoNj7wJ
Extracting configs to /tmp/tmp.9EgZ6ORxwI
Found configs for SURFSHARK in /tmp/tmp.9EgZ6ORxwI/vpn-configs-contrib-main/openvpn/surfshark, will replace current content in /etc/openvpn/surfshark
Cleanup: deleting /tmp/tmp.WVxcoNj7wJ and /tmp/tmp.9EgZ6ORxwI
Starting OpenVPN using config dk-cph_tcp.ovpn
Modifying /etc/openvpn/surfshark/dk-cph_tcp.ovpn for best behaviour in this container
Modification: Point auth-user-pass option to the username/password file
Modification: Change ca certificate path
Modification: Change ping options
Modification: Update/set resolv-retry to 15 seconds
Modification: Change tls-crypt keyfile path
Modification: Set output verbosity to 3
Modification: Remap SIGUSR1 signal to SIGTERM, avoid OpenVPN restart loop
Setting OpenVPN credentials...
adding route to local network 192.168.1.0/24 via 172.17.0.1 dev eth0
Fri Dec 24 22:38:58 2021 OpenVPN 2.4.7 arm-unknown-linux-gnueabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jul 19 2021
Fri Dec 24 22:38:58 2021 library versions: OpenSSL 1.1.1f  31 Mar 2020, LZO 2.10
Fri Dec 24 22:38:58 2021 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Fri Dec 24 22:38:58 2021 NOTE: --fast-io is disabled since we are not using UDP
Fri Dec 24 22:38:58 2021 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
Fri Dec 24 22:38:58 2021 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
Fri Dec 24 22:38:58 2021 TCP/UDP: Preserving recently used remote address: [AF_INET]37.120.194.125:1443
Fri Dec 24 22:38:58 2021 Socket Buffers: R=[131072->131072] S=[16384->16384]
Fri Dec 24 22:38:58 2021 Attempting to establish TCP connection with [AF_INET]37.120.194.125:1443 [nonblock]
Fri Dec 24 22:38:59 2021 TCP connection established with [AF_INET]37.120.194.125:1443
Fri Dec 24 22:38:59 2021 TCP_CLIENT link local: (not bound)
Fri Dec 24 22:38:59 2021 TCP_CLIENT link remote: [AF_INET]37.120.194.125:1443
Fri Dec 24 22:38:59 2021 TLS: Initial packet from [AF_INET]37.120.194.125:1443, sid=94edc507 64ca5e31
Fri Dec 24 22:38:59 2021 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Fri Dec 24 22:38:59 2021 VERIFY OK: depth=2, C=VG, O=Surfshark, CN=Surfshark Root CA
Fri Dec 24 22:38:59 2021 VERIFY OK: depth=1, C=VG, O=Surfshark, CN=Surfshark Intermediate CA
Fri Dec 24 22:38:59 2021 VERIFY KU OK
Fri Dec 24 22:38:59 2021 Validating certificate extended key usage
Fri Dec 24 22:38:59 2021 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Fri Dec 24 22:38:59 2021 VERIFY EKU OK
Fri Dec 24 22:38:59 2021 VERIFY OK: depth=0, CN=dk-cph-v022.prod.surfshark.com
Fri Dec 24 22:38:59 2021 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1635', remote='link-mtu 1583'
Fri Dec 24 22:38:59 2021 WARNING: 'cipher' is used inconsistently, local='cipher AES-256-CBC', remote='cipher AES-256-GCM'
Fri Dec 24 22:38:59 2021 WARNING: 'auth' is used inconsistently, local='auth SHA512', remote='auth [null-digest]'
Fri Dec 24 22:38:59 2021 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 2048 bit RSA
Fri Dec 24 22:38:59 2021 [dk-cph-v022.prod.surfshark.com] Peer Connection Initiated with [AF_INET]37.120.194.125:1443
Fri Dec 24 22:39:01 2021 SENT CONTROL [dk-cph-v022.prod.surfshark.com]: 'PUSH_REQUEST' (status=1)
Fri Dec 24 22:39:01 2021 PUSH: Received control message: 'PUSH_REPLY,dhcp-option DNS 162.252.172.57,dhcp-option DNS 149.154.159.92,redirect-gateway def1,sndbuf 524288,rcvbuf 524288,explicit-exit-notify,block-outside-dns,route-gateway 10.7.7.1,topology subnet,ping 60,ping-restart 180,ifconfig 10.7.7.2 255.255.255.0,peer-id 0,cipher AES-256-GCM'
Fri Dec 24 22:39:01 2021 Options error: Unrecognized option or missing or extra parameter(s) in [PUSH-OPTIONS]:7: block-outside-dns (2.4.7)
Fri Dec 24 22:39:01 2021 OPTIONS IMPORT: timers and/or timeouts modified
Fri Dec 24 22:39:01 2021 OPTIONS IMPORT: --explicit-exit-notify can only be used with --proto udp
Fri Dec 24 22:39:01 2021 OPTIONS IMPORT: --sndbuf/--rcvbuf options modified
Fri Dec 24 22:39:01 2021 Socket Buffers: R=[131072->360448] S=[44800->360448]
Fri Dec 24 22:39:01 2021 OPTIONS IMPORT: --ifconfig/up options modified
Fri Dec 24 22:39:01 2021 OPTIONS IMPORT: route options modified
Fri Dec 24 22:39:01 2021 OPTIONS IMPORT: route-related options modified
Fri Dec 24 22:39:01 2021 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
Fri Dec 24 22:39:01 2021 OPTIONS IMPORT: peer-id set
Fri Dec 24 22:39:01 2021 OPTIONS IMPORT: adjusting link_mtu to 1658
Fri Dec 24 22:39:01 2021 OPTIONS IMPORT: data channel crypto options modified
Fri Dec 24 22:39:01 2021 Data Channel: using negotiated cipher 'AES-256-GCM'
Fri Dec 24 22:39:01 2021 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Fri Dec 24 22:39:01 2021 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Fri Dec 24 22:39:01 2021 ROUTE_GATEWAY 172.17.0.1/255.255.0.0 IFACE=eth0 HWADDR=02:42:ac:11:00:02
Fri Dec 24 22:39:01 2021 TUN/TAP device tun0 opened
Fri Dec 24 22:39:01 2021 TUN/TAP TX queue length set to 100
Fri Dec 24 22:39:01 2021 /sbin/ip link set dev tun0 up mtu 1500
Fri Dec 24 22:39:01 2021 /sbin/ip addr add dev tun0 10.7.7.2/24 broadcast 10.7.7.255
Fri Dec 24 22:39:01 2021 /etc/openvpn/tunnelUp.sh tun0 1500 1586 10.7.7.2 255.255.255.0 init
Up script executed with tun0 1500 1586 10.7.7.2 255.255.255.0 init
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.7.7.2
Using Flood for Transmission UI, overriding TRANSMISSION_WEB_HOME
Updating Transmission settings.json with values from env variables
Using existing settings.json for Transmission /data/transmission-home/settings.json
Overriding bind-address-ipv4 because TRANSMISSION_BIND_ADDRESS_IPV4 is set to 10.7.7.2
Overriding download-dir because TRANSMISSION_DOWNLOAD_DIR is set to /data/completed
Overriding incomplete-dir because TRANSMISSION_INCOMPLETE_DIR is set to /data/incomplete
Overriding rpc-port because TRANSMISSION_RPC_PORT is set to 9091
Overriding watch-dir because TRANSMISSION_WATCH_DIR is set to /data/watch
sed'ing True to true
Enforcing ownership on transmission config directories
Applying permissions to transmission config directories
Setting owner for transmission paths to 1001:1001
Setting permissions for download and incomplete directories
Mask: 002
Directories: 775
Files: 664
Setting permission for watch directory (775) and its files (664)

-------------------------------------
Transmission will run as
-------------------------------------
User name:   abc
User uid:    1001
User gid:    1001
-------------------------------------

STARTING TRANSMISSION
Transmission startup script complete.
Fri Dec 24 22:41:17 2021 /sbin/ip route add 37.120.194.125/32 via 172.17.0.1
Fri Dec 24 22:41:17 2021 /sbin/ip route add 0.0.0.0/1 via 10.7.7.1
Fri Dec 24 22:41:17 2021 /sbin/ip route add 128.0.0.0/1 via 10.7.7.1
Fri Dec 24 22:41:17 2021 Initialization Sequence Completed

```

### Environment

```markdown
- OS: Raspberry OS Buster on A Raspberry Pi 4B
- Docker: 20.10.11, build dea9396
```

### Anything else?

I absolutely can't find any errors and absolutely can't relate or directly reproduce the error.
I just start the download and after a few moments it stops working.
When no download runs, everything works great.

I also noticed that the username in the docker log is different to the one I setup in the service file. Is this normal?

**Comment by pduchnovsky** [comment]
Noticed the same but it does not stop as soon as for you, but after a few hours mostly, running on Synology DS920+ with 1.5G memory limit.

**Comment by Jannomag** [comment]
Tried Windscribe instead of Surfshark. Same issue.

Another log:
```

$ docker inspect --format "{{json .State.Health }}" transmission-openvpn | jq
{
  "Status": "unhealthy",
  "FailingStreak": 5,
  "Log": [
    {
      "Start": "2021-12-29T12:13:41.260137983+01:00",
      "End": "2021-12-29T12:13:42.995635328+01:00",
      "ExitCode": 1,
      "Output": "PING google.com (142.250.179.206) 56(84) bytes of data.\n64 bytes from ams15s42-in-f14.1e100.net (142.250.179.206): icmp_seq=1 ttl=54 time=19.9 ms\n64 bytes from ams15s42-in-f14.1e100.net (142.250.179.206): icmp_seq=2 ttl=54 time=20.3 ms\n\n--- google.com ping statistics ---\n2 packets transmitted, 2 received, 0% packet loss, time 1002ms\nrtt min/avg/max/mdev = 19.873/20.085/20.298/0.212 ms\nNetwork is up\ntransmission-daemon process not running\n"
    },
    {
      "Start": "2021-12-29T12:14:43.016610441+01:00",
      "End": "2021-12-29T12:14:44.364927123+01:00",
      "ExitCode": 1,
      "Output": "PING google.com (142.250.179.206) 56(84) bytes of data.\n64 bytes from ams15s42-in-f14.1e100.net (142.250.179.206): icmp_seq=1 ttl=54 time=19.9 ms\n64 bytes from ams15s42-in-f14.1e100.net (142.250.179.206): icmp_seq=2 ttl=54 time=20.9 ms\n\n--- google.com ping statistics ---\n2 packets transmitted, 2 received, 0% packet loss, time 1002ms\nrtt min/avg/max/mdev = 19.913/20.417/20.922/0.504 ms\nNetwork is up\ntransmission-daemon process not running\n"
    },
    {
      "Start": "2021-12-29T12:15:44.379652058+01:00",
      "End": "2021-12-29T12:15:45.9398978+01:00",
      "ExitCode": 1,
      "Output": "PING google.com (142.250.179.206) 56(84) bytes of data.\n64 bytes from ams15s42-in-f14.1e100.net (142.250.179.206): icmp_seq=1 ttl=54 time=20.1 ms\n64 bytes from ams15s42-in-f14.1e100.net (142.250.179.206): icmp_seq=2 ttl=54 time=20.4 ms\n\n--- google.com ping statistics ---\n2 packets transmitted, 2 received, 0% packet loss, time 1001ms\nrtt min/avg/max/mdev = 20.124/20.254/20.384/0.130 ms\nNetwork is up\ntransmission-daemon process not running\n"
    },
    {
      "Start": "2021-12-29T12:16:45.952385031+01:00",
      "End": "2021-12-29T12:16:47.485957229+01:00",
      "ExitCode": 1,
      "Output": "PING google.com (142.250.179.206) 56(84) bytes of data.\n64 bytes from ams15s42-in-f14.1e100.net (142.250.179.206): icmp_seq=1 ttl=54 time=20.1 ms\n64 bytes from ams15s42-in-f14.1e100.net (142.250.179.206): icmp_seq=2 ttl=54 time=20.4 ms\n\n--- google.com ping statistics ---\n2 packets transmitted, 2 received, 0% packet loss, time 1001ms\nrtt min/avg/max/mdev = 20.105/20.229/20.353/0.124 ms\nNetwork is up\ntransmission-daemon process not running\n"
    },
    {
      "Start": "2021-12-29T12:17:47.498644508+01:00",
      "End": "2021-12-29T12:17:48.938315267+01:00",
      "ExitCode": 1,
      "Output": "PING google.com (142.250.179.206) 56(84) bytes of data.\n64 bytes from ams15s42-in-f14.1e100.net (142.250.179.206): icmp_seq=1 ttl=54 time=19.9 ms\n64 bytes from ams15s42-in-f14.1e100.net (142.250.179.206): icmp_seq=2 ttl=54 time=21.4 ms\n\n--- google.com ping statistics ---\n2 packets transmitted, 2 received, 0% packet loss, time 1001ms\nrtt min/avg/max/mdev = 19.903/20.647/21.392/0.744 ms\nNetwork is up\ntransmission-daemon process not running\n"
    }
  ]
}

```

**Comment by CaptainSolidus** [comment]
I'm getting what is likely the same issue. I have transmission running on Docker through docker-compose, on a Debian buster container on a Proxmox host. It doesn't appear to be running out of memory or anything. Configuration below.

```  
transmission-vpn:
    container_name: transmission-vpn
    image: haugene/transmission-openvpn
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: always
    ports:
      - 9091
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/docker/transmission-vpn:/data
      - ${USERDIR}/docker/certs:/certs
      - /mnt/downloads:/data/watch
      - /mnt/downloads/completed:/data/completed
      - /mnt/downloads/incomplete:/data/incomplete
    environment:
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_USERNAME=
      - OPENVPN_PASSWORD=
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60 --mute-replay-warnings --mssfix 1460
      - PIA_OPENVPN_CONFIG_BUNDLE=openvpn
      - LOCAL_NETWORK=192.168.0.0/24,10.8.0.0/16,172.0.0.0/8
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      - TRANSMISSION_RPC_HOST_WHITELIST="127.0.0.1,192.168.*.*,10.8.*.*,172.*.*.*"
      - TRANSMISSION_RPC_PASSWORD=
      - TRANSMISSION_RPC_USERNAME=
      - TRANSMISSION_UMASK=2
      - TRANSMISSION_WEB_UI=flood-for-transmission
```

And the error code, same as the poster above:

```
PING google.com (142.250.76.110) 56(84) bytes of data. 64 bytes from syd09s24-in-f14.1e100.net (142.250.76.110): icmp_seq=1 ttl=60 time=242 ms 64 bytes from syd09s24-in-f14.1e100.net (142.250.76.110): icmp_seq=2 ttl=60 time=242 ms --- google.com ping statistics --- 2 packets transmitted, 2 received, 0% packet loss, time 1001ms rtt min/avg/max/mdev = 242.075/242.125/242.176/0.050 ms Network is up transmission-daemon process not running 
```

**Comment by fergbrain** [comment]
I also have this issue. Usually occurs about once-a-week or so.

**Comment by fergbrain** [comment]
Can this issue be reopened, or should I create a new one?

**Comment by fergbrain** [comment]
I'll do this next time...hopefully you'll have a response in about a week or so.

**Comment by fergbrain** [comment]
@edgd1er: Daemon not running, though IP address still matches.
```
# ps -ef
root           1       0  0 Apr03 ?        00:00:00 dumb-init /etc/openvpn/start.sh
root           8       1  1 Apr03 ?        01:45:59 openvpn --script-security 2 --route-up /etc/openvpn/tunnelUp.sh --route-pre-down /etc/openvpn/tunnelDown.sh --script-security 2 --up /scripts/openvpn-post-config.sh --config /etc/openvpn/pia/jap
root          95       1  0 Apr03 ?        00:00:00 /bin/bash /etc/openvpn/pia/update-port.sh
root      116881      95  0 19:20 ?        00:00:00 sleep 900
root      117026       0  0 19:30 pts/0    00:00:00 bash
root      117038  117026  0 19:30 pts/0    00:00:00 ps -ef
root      117039       0  0 19:30 ?        00:00:00 /bin/sh -c /etc/scripts/healthcheck.sh
```

Results from log:
```Overriding bind-address-ipv4 because TRANSMISSION_BIND_ADDRESS_IPV4 is set to 10.5.112.229```
...vs actual:
```
# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN group default qlen 500
    link/none 
    inet 10.5.112.229/24 scope global tun0
       valid_lft forever preferred_lft forever
98: eth0@if99: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:ac:17:00:06 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.23.0.6/16 brd 172.23.255.255 scope global eth0
       valid_lft forever preferred_lft forever
100: eth1@if101: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:ac:13:00:11 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.19.0.17/16 brd 172.19.255.255 scope global eth1
       valid_lft forever preferred_lft forever
```
I also checked the service status:
```
# service transmission-daemon status
 * transmission-daemon is not running
```

I tried starting the service and it wouldn't start -- reports that it's not running. However, I do get the following in the browser:
```
403: Forbidden

Unauthorized IP Address.

Either disable the IP address whitelist or add your address to it.

If you're editing settings.json, see the 'rpc-whitelist' and 'rpc-whitelist-enabled' entries.

If you're still using ACLs, use a whitelist instead. See the transmission-daemon manpage for details.
```

Let me know what else I can check or try!

**Comment by edgd1er** [comment]
There is no service nor systemctl available in this container, transmission is started through openvpn's tunnelup script.
https://github.com/haugene/docker-transmission-openvpn/blob/2322fd117d7f48f9068d10cb191181588c2cfe0a/openvpn/tunnelUp.sh#L64

transmission start script will need openvpn env variable to start `/etc/transmission/start.sh`
[`USER_SCRIPT_ARGS=("$dev" "$tun_mtu" "$link_mtu" "$ifconfig_local" "$ifconfig_remote" "$script_context")`
](https://github.com/haugene/docker-transmission-openvpn/blob/2322fd117d7f48f9068d10cb191181588c2cfe0a/transmission/start.sh#L19)

without the logs, difficult to say what went wrong.
Depending of the problem, this line could start transmission:
https://github.com/haugene/docker-transmission-openvpn/blob/2322fd117d7f48f9068d10cb191181588c2cfe0a/transmission/start.sh#L98

In your last post, transmission is started but access is denied. your network is not allowed.
Have a look to the docs [Network configuration options](https://haugene.github.io/docker-transmission-openvpn/config-options/) to define local network

Again without logs and conf, i'm just guessing what could have happened and what could be ran....

**Comment by fergbrain** [comment]
Good to know transmission is started through the script and no the daemon service. I'll try restarting it with that script next time.

As far as network access is concerned, the network normally works just fine. I'm not sure why it was giving me a 403, however I suspect it had to do with the fact that I didn't restart transmission correct...so I think it's a red-herring.

Here's my `docker-compose.yml` file:
```
version: "2.2"
services:
 ...
  transmission:
    image: haugene/transmission-openvpn:latest
    container_name: transmission-openvpn
    restart: always
    cap_add:
      - NET_ADMIN
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=America/Los_Angeles
      - CREATE_TUN_DEVICE=true
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_CONFIG=ca_vancouver,japan,ca_toronto,ca_ontario,mexico
      - OPENVPN_USERNAME=**None**
      - OPENVPN_PASSWORD=**None**
      - OPENVPN_OPTS=--script-security 2 --up /scripts/openvpn-post-config.sh
      - WEBPROXY_ENABLED=false
      - TRANSMISSION_WEB_UI=kettu
      - LOCAL_NETWORK=10.0.0.0/8
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - overseerr
      - default
    volumes:
      - ./config/transmission/openvpn-credentials.txt:/config/openvpn-credentials.txt
      - ./config/transmission/scripts:/scripts
      - ./data/transmission:/config/transmission-home
      - /mnt/media/downloads:/data
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transmission.rule=Host(`<REDACTED>`)"
      - "traefik.http.routers.transmission.tls=true"
      - "traefik.http.routers.transmission.entryPoints=https"
      - "traefik.http.services.transmission.loadbalancer.server.scheme=http"
      - "traefik.http.services.transmission.loadbalancer.server.port=9091"
      - "traefik.http.routers.transmission.middlewares=<REDACTED>@docker"
      - "com.centurylinklabs.watchtower.enable=true"
  ...
networks:
  default:
    external:
      name: traefik
  overseerr:
    external: false
```

I'm not seeing anything exceptional or helpful in the logs.
