### ISSUE TITLE
 Can connect to the web UI but not to transmission/rpc nor transmission/rpc/

### ISSUE THREAD

**Issue by joachimesque** [haugene/docker-transmission-openvpn#2141]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [ ] I have tried using dev branch

### Config used

I'm using a docker image along with a setup of Nginx that provides reverse proxy to multiple services on my server. Nginx does not run through a docker container.

Here's the `docker-compose.yml` file I use for docker-transmission-openvpn

```yml
version: '2'
services:
 transmission:
  image: haugene/transmission-openvpn
  cap_add:
    - NET_ADMIN
  devices:
    - /dev/net/tun
  restart: always
  ports:
    - "9091:9091"
    - "8888:8888"
  dns:
    - 9.9.9.9
    - 1.1.1.1
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /data/Downloads:/data
  environment:
    - OPENVPN_CONFIG=de_frankfurt
    - OPENVPN_PROVIDER=PIA
    - OPENVPN_USERNAME=XXX
    - OPENVPN_PASSWORD=XXX
    - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
    - LOCAL_NETWORK=192.168.0.0/24
    - PUID=1001
    - PGID=1001
    - TRANSMISSION_WEB_UI=transmission-web-control
 ```

Here's the relevant options in my nginx config

```
upstream transmission  {
      server 127.0.0.1:9091; #Transmission
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;

…

      location ^~ /transmission {

          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header Host $http_host;
          proxy_set_header X-NginX-Proxy true;
          proxy_http_version 1.1;
          proxy_set_header Connection "";
          proxy_pass_header X-Transmission-Session-Id;
          add_header   Front-End-Https   on;

          location /transmission/rpc {
              proxy_pass http://transmission;
          }

          location /transmission/web/ {
              proxy_pass http://transmission;
          }

          location /transmission/upload {
              proxy_pass http://transmission;
          }

          location /transmission/ {
              return 301 https://$server_name/transmission/web;
          }
      }
}
```

### Current Behavior

The web interface works well enough most of the time, but `/transmission/rpc` or `/transmission/rpc/` don't work at all. I always get a 409 error.

### Expected Behavior

`/transmission/rpc/` should work.

### How have you tried to solve the problem?

These solutions didn't help:

- #528
- #1606
- #903

### Log output

```
409: Conflict

Your request had an invalid session-id header.

To fix this, follow these steps:

    When reading a response, get its X-Transmission-Session-Id header and remember it
    Add the updated header to your outgoing requests
    When you get this 409 error message, resend your request with the updated header

This requirement has been added to help prevent CSRF attacks.

X-Transmission-Session-Id: hbMTJkdmwculbrv22F676JBAScCeuvQgdXR4XOy5qkHqGo5c
```

Here's the log output for the container after it's connected to OpenVPN:

```
…
transmission_1  | Running functions for token based port fowarding
transmission_1  | Reserved Port: 36777  Thu Jan  6 23:39:39 CET 2022
transmission_1  | transmission auth not required
transmission_1  | waiting for transmission to become responsive
transmission_1  | transmission became responsive
transmission_1  | setting transmission port to 36777
transmission_1  | localhost:9091/transmission/rpc/ responded: "success"
transmission_1  | Checking port...
transmission_1  | Port is open: Yes
transmission_1  | #######################
transmission_1  |         SUCCESS
transmission_1  | #######################
transmission_1  | Port: 36777
transmission_1  | Expiration Thu Mar 10 11:39:33 CET 2022
transmission_1  | #######################
transmission_1  | Entering infinite while loop
transmission_1  | Every 15 minutes, check port status
```

### Environment

```markdown
- OS: Debian GNU/Linux bookworm/sid x86_64
- Docker: Docker version 20.10.11+dfsg1, build dea9396
```

### Anything else?

Thank you!
