### ISSUE TITLE
Since moving from linuxserver/transmission, all my completed/seeding torrents are gone

### ISSUE THREAD

**Issue by JoshuaWalsh** [haugene/docker-transmission-openvpn#2145]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [X] I have tried using dev branch

### Config used

```yaml
transmission:
    cap_add:
      - CAP_NET_ADMIN
    deploy:
      labels:
        io.portainerhack.cap_add: NET_ADMIN
      mode: replicated
      replicas: 1
    image: haugene/transmission-openvpn:dev
    #image: linuxserver/transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
      - OPENVPN_PROVIDER=redacted
      - OPENVPN_CONFIG=redacted
      - OPENVPN_USERNAME=redacted
      - OPENVPN_PASSWORD=redacted
      - LOCAL_NETWORK=192.168.0.0/24
      - TRANSMISSION_WEB_UI=combustion 
    volumes:
      - transmission_config:/config
      - media:/media
      - media:/downloads
      - media_complete:/data/complete
      - media_incomplete:/data/incomplete
      - transmission_watch:/watch
      - transmission_watch:/data/watch
      - transmission_config:/data/transmission-home
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
```

The reason there are many overlapping volumes is so that I can easily switch back and forth between linuxserver/transmission and haugene/transmission-openvpn while testing.

### Current Behavior

After switching image, my in-progress list is empty.

### Expected Behavior

All of the torrents I had in the previous container should also be present in the new container.

### How have you tried to solve the problem?

I mounted the same `/config` volume I was using with the linuxserver.io image into this new image. I was initially surprised to see that the new image was not respecting the paths I had specified in settings.json for complete/incomplete/watch directories. I added some extra volume mounts to ensure that this image would find the files where it was expecting them.

(Looking at the logs, it appears that I should set the `TRANSMISSION_DOWNLOAD_DIR`, `TRANSMISSION_INCOMPLETE_DIR`, and `TRANSMISSION_WATCH_DIR` environment variables. As best as I can tell, these are not mentioned in the documentation.)

I also mounted my config volume in /data/transmission-home. I think since #1521 has been merged this shouldn't be necessary, but I tried it anyway. Initially I didn't have this mounted, but since I was having trouble I added it.

### Log output

```
Setting OpenVPN credentials...
adding route to local network 192.168.10.0/24 via 172.18.0.1 dev eth2
Wed Jan 12 00:27:13 2022 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jul 19 2021
Wed Jan 12 00:27:13 2022 library versions: OpenSSL 1.1.1f  31 Mar 2020, LZO 2.10
Wed Jan 12 00:27:13 2022 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Wed Jan 12 00:27:13 2022 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
Wed Jan 12 00:27:13 2022 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
Wed Jan 12 00:27:13 2022 TCP/UDP: Preserving recently used remote address: [AF_INET]185.159.157.129:1194
Wed Jan 12 00:27:13 2022 Socket Buffers: R=[212992->212992] S=[212992->212992]
Wed Jan 12 00:27:13 2022 UDP link local: (not bound)
Wed Jan 12 00:27:13 2022 UDP link remote: [AF_INET]185.159.157.129:1194
Wed Jan 12 00:27:13 2022 TLS: Initial packet from [AF_INET]185.159.157.129:1194, sid=664e41af 93a1ee08
Wed Jan 12 00:27:13 2022 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Wed Jan 12 00:27:14 2022 VERIFY OK: depth=2, C=CH, O=ProtonVPN AG, CN=ProtonVPN Root CA
Wed Jan 12 00:27:14 2022 VERIFY OK: depth=1, C=CH, O=ProtonVPN AG, CN=ProtonVPN Intermediate CA 1
Wed Jan 12 00:27:14 2022 VERIFY KU OK
Wed Jan 12 00:27:14 2022 Validating certificate extended key usage
Wed Jan 12 00:27:14 2022 ++ Certificate has EKU (str) 1.3.6.1.5.5.8.2.2, expects TLS Web Server Authentication
Wed Jan 12 00:27:14 2022 ++ Certificate has EKU (oid) 1.3.6.1.5.5.8.2.2, expects TLS Web Server Authentication
Wed Jan 12 00:27:14 2022 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Wed Jan 12 00:27:14 2022 VERIFY EKU OK
Wed Jan 12 00:27:14 2022 VERIFY OK: depth=0, CN=node-ch-06.protonvpn.net
Wed Jan 12 00:27:15 2022 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1633', remote='link-mtu 1634'
Wed Jan 12 00:27:15 2022 WARNING: 'comp-lzo' is present in remote config but missing in local config, remote='comp-lzo'
Wed Jan 12 00:27:15 2022 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_AES_256_GCM_SHA384, 4096 bit RSA
Wed Jan 12 00:27:15 2022 [node-ch-06.protonvpn.net] Peer Connection Initiated with [AF_INET]185.159.157.129:1194
Wed Jan 12 00:27:16 2022 SENT CONTROL [node-ch-06.protonvpn.net]: 'PUSH_REQUEST' (status=1)
Wed Jan 12 00:27:16 2022 PUSH: Received control message: 'PUSH_REPLY,dhcp-option DNS 10.32.0.1,sndbuf 524288,rcvbuf 524288,redirect-gateway def1,explicit-exit-notify,comp-lzo no,route-gateway 10.32.0.1,topology subnet,ping 10,ping-restart 60,socket-flags TCP_NODELAY,ifconfig 10.32.0.9 255.255.0.0,peer-id 1048583,cipher AES-256-GCM'
Wed Jan 12 00:27:16 2022 OPTIONS IMPORT: timers and/or timeouts modified
Wed Jan 12 00:27:16 2022 OPTIONS IMPORT: explicit notify parm(s) modified
Wed Jan 12 00:27:16 2022 OPTIONS IMPORT: compression parms modified
Wed Jan 12 00:27:16 2022 OPTIONS IMPORT: --sndbuf/--rcvbuf options modified
Wed Jan 12 00:27:16 2022 Socket Buffers: R=[212992->425984] S=[212992->425984]
Wed Jan 12 00:27:16 2022 OPTIONS IMPORT: --socket-flags option modified
Wed Jan 12 00:27:16 2022 NOTE: setsockopt TCP_NODELAY=1 failed
Wed Jan 12 00:27:16 2022 OPTIONS IMPORT: --ifconfig/up options modified
Wed Jan 12 00:27:16 2022 OPTIONS IMPORT: route options modified
Wed Jan 12 00:27:16 2022 OPTIONS IMPORT: route-related options modified
Wed Jan 12 00:27:16 2022 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
Wed Jan 12 00:27:16 2022 OPTIONS IMPORT: peer-id set
Wed Jan 12 00:27:16 2022 OPTIONS IMPORT: adjusting link_mtu to 1656
Wed Jan 12 00:27:16 2022 OPTIONS IMPORT: data channel crypto options modified
Wed Jan 12 00:27:16 2022 Data Channel: using negotiated cipher 'AES-256-GCM'
Wed Jan 12 00:27:16 2022 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Wed Jan 12 00:27:16 2022 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Wed Jan 12 00:27:16 2022 ROUTE_GATEWAY 172.18.0.1/255.255.0.0 IFACE=eth2 HWADDR=02:42:ac:12:00:0f
Wed Jan 12 00:27:16 2022 TUN/TAP device tun0 opened
Wed Jan 12 00:27:16 2022 TUN/TAP TX queue length set to 100
Wed Jan 12 00:27:16 2022 /sbin/ip link set dev tun0 up mtu 1500
Wed Jan 12 00:27:16 2022 /sbin/ip addr add dev tun0 10.32.0.9/16 broadcast 10.32.255.255
Wed Jan 12 00:27:16 2022 /sbin/ip route add 185.159.157.129/32 via 172.18.0.1
Wed Jan 12 00:27:16 2022 /sbin/ip route add 0.0.0.0/1 via 10.32.0.1
Wed Jan 12 00:27:16 2022 /sbin/ip route add 128.0.0.0/1 via 10.32.0.1
Up script executed with device=tun0 ifconfig_local=10.32.0.9
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.32.0.9
Using Combustion UI, overriding TRANSMISSION_WEB_HOME
TRANSMISSION_HOME is currently set to: /config/transmission-home
WARNING: Deprecated. Found old default transmission-home folder at /data/transmission-home, setting this as TRANSMISSION_HOME. This might break in future versions.
We will fallback to this directory as long as the folder exists. Please consider moving it to /config/<transmission-home>
Enforcing ownership on transmission config directory
Applying permissions to transmission config directory
Setting owner for transmission paths to 1000:1000
Setting permissions for download and incomplete directories
```

### Environment

```markdown
- OS:Ubuntu 20.04.3 LTS

- Docker: 20.10.11
```
