### ISSUE TITLE
Proxy does not work after SIGTERM

### ISSUE THREAD

**Issue by tim0901** [haugene/docker-transmission-openvpn#2171]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [X] I have tried using dev branch

### Config used

```
version: '3.3'
services:
        transmission-openvpn:
                container_name: transmission_openvpn
                image: haugene/transmission-openvpn:dev
                restart: always
                cap_add:
                    - NET_ADMIN
                volumes:
                    - ~/data/transmission-home:/config/transmission-home
                    - ~/data/media:/data
                    - networkShare:/networkShare
                environment:
                    - PUID=1001
                    - GUID=1001
                    - OPENVPN_PROVIDER=WINDSCRIBE
                    - OPENVPN_CONFIG=${OPENVPN_CONFIG}
                    - OPENVPN_USERNAME=${OPENVPN_USERNAME}
                    - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
                    - LOCAL_NETWORK=192.168.0.0/16
                    - TRANSMISSION_SPEED_LIMIT_UP=100
                    - TRANSMISSION_SPEED_LIMIT_DOWN=2048
                    - TRANSMISSION_ALT_SPEED_UP=50
                    - TRANSMISSION_ALT_SPEED_DOWN=1024
                    - TRANSMISSION_RPC_USERNAME=${RPC_USERNAME}
                    - TRANSMISSION_RPC_PASSWORD=${RPC_PASSWORD}
                    - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
                    - TRANSMISSION_ALT_SPEED_TIME_BEGIN=480
                    - TRANSMISSION_ALT_SPEED_TIME_END=1320
                    - TRANSMISSION_IDLE_SEEDING_LIMIT=1
                    - TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED=true
                    - TRANSMISSION_PEER_LIMIT_GLOBAL=2000
                    - TRANSMISSION_PEER_LIMIT_PER_TORRENT=500
                    - TRANSMISSION_PEER_PORT=${TRANSMISSION_PEER_PORT}
                    - TRANSMISSION_DOWNLOAD_QUEUE_SIZE=50
                    - TZ=Europe/London
                logging:
                    driver: json-file
                    options:
                        max-size: 10m
                networks:
                  static-network-vpn:
                    ipv4_address: 172.20.0.3
                  letsencrypt_proxy-tier:

        transmission-proxy:
                container_name: transmission_proxy
                restart: always
                image: haugene/transmission-openvpn-proxy:dev
                environment:
                  - TZ=Europe/London
                links:
                  - "transmission-openvpn:transmission"
                ports:
                  - ${TRANSMISSION_PEER_PORT}:${TRANSMISSION_PEER_PORT} # transmisison peers
                  - 9091:9091 #transmission
                  - 4032:4032
                  - 9117:9117
                  - 8989:8989
                  - 7878:7878
                  - 6767:6767
                depends_on:
                  - transmission-openvpn
                volumes:
                  - ~/vpn/proxy/nginx.conf:/etc/nginx/nginx.conf
                networks:
                  static-network-vpn:
                    ipv4_address: 172.20.0.13

volumes:
  networkShare:
    driver_opts:
      ##REDACTED##

networks:
  static-network-vpn:
    ipam:
      config:
        - subnet: 172.20.0.0/16
          ip_range: 172.20.5.0/24
  letsencrypt_proxy-tier:
    external: true
```
### Current Behavior

Occasionally the container will recieve a reset signal (SIGUSR1) from the server - this is remapped to SIGTERM during startup 'to avoid OpenVPN restart loop' meaning the entire container restarts. (Unsure why others such as https://github.com/haugene/docker-transmission-openvpn/issues/2130 are not seeing the services restart here). 

```
...
Wed Dec  1 16:00:19 2021 Connection reset command was pushed by server ('')
Wed Dec  1 16:00:19 2021 /etc/openvpn/tunnelDown.sh tun0 1500 1552 10.120.102.20 255.255.254.0 init
resolv.conf was restored
Sending kill signal to transmission-daemon
Successfuly closed transmission-daemon
Wed Dec  1 16:00:20 2021 /sbin/ip route del 84.17.42.37/32
Wed Dec  1 16:00:20 2021 /sbin/ip route del 0.0.0.0/1
Wed Dec  1 16:00:20 2021 /sbin/ip route del 128.0.0.0/1
Wed Dec  1 16:00:20 2021 Closing TUN/TAP interface
Wed Dec  1 16:00:20 2021 /sbin/ip addr del dev tun0 10.120.102.20/23
Wed Dec  1 16:00:20 2021 SIGTERM[soft,server-pushed-connection-reset] received, process exiting
Starting container with revision: 22f199814de4aab71f8636c24fbbc2a456e6c862
...
```
Connections will also sometimes be dropped due to inactivity:
```
...
Sat Jan 29 18:10:40 2022 [cdg-342.windscribe.com] Inactivity timeout (--ping-restart), restarting
Sat Jan 29 18:10:40 2022 /etc/openvpn/tunnelDown.sh tun0 1500 1552 10.120.115.146 255.255.254.0 init
resolv.conf was restored
Sending kill signal to transmission-daemon
Successfuly closed transmission-daemon
Sat Jan 29 18:10:41 2022 /sbin/ip route del 84.17.42.2/32
Sat Jan 29 18:10:41 2022 /sbin/ip route del 0.0.0.0/1
Sat Jan 29 18:10:41 2022 /sbin/ip route del 128.0.0.0/1
Sat Jan 29 18:10:41 2022 Closing TUN/TAP interface
Sat Jan 29 18:10:41 2022 /sbin/ip addr del dev tun0 10.120.115.146/23
Sat Jan 29 18:10:41 2022 SIGTERM[soft,ping-restart] received, process exiting
Starting container with revision: b65dedd01e038cfa4dc140246fccd5b393b2da69
...
```
When the container restarts, the VPN connection is restored and transmission works as expected. **However**, proxied services are at this point unaccessible. Attempting to load one gives a 502 Bad Gateway error in a browser, while the proxy logs report a 111: Connection refused error:
```
2022/01/29 23:27:50 [error] 32#32: *72 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.70, server: , request: "GET / HTTP/1.1", upstream: "http://172.20.0.3:8989/", host: "192.168.1.129:8989"
```

The only way to fix this - that I am aware of - is to manually restart the proxy and all proxied services. Just restarting the proxy container does not fix the problem. 

This behaviour can be artificially induced by manually stopping and starting the openvpn container without also restarting the proxy container. 

### Expected Behavior

Proxied services should be accessible when transmission restarts.

### How have you tried to solve the problem?

If you override the SIGUSR1 -> SIGTERM remapping in `modify-openvpn-config.sh` then proxied services are not broken when these signals are recieved because the container is no longer restarting - the service is restarting within the container. Not only is this bad practise for containers, but it also introduces a new problem: OpenVPN boot looping. After a few boot loops, the container starts failing to resolve the host address of the VPN server. 

(Unfortunately I don't have a log for this - will replicate and add below when possible, but this may take several days.)

### Log output

See above for relevant.

### Environment

```markdown
- OS: Linux 4.10.63-v8+ - Pi OS 64-bit Bullseye
- Docker: 20.10.12
```

**Comment by Hebusing** [comment]
Hi team,

I'm facing the exact same issue on a Synology DS1019+.
I have 2 dockers running in parallel and they both stops time to time. Funny enough they stop at a couple of hours apart from each other (from 1 to 6 hours max from what I've noticed).
I'm running the latest version of docker-transmission-openvpn and latest version of the Synology DSM.

My logs are (they are upside down strangely):
```
Tue Feb  1 00:50:11 2022 VERIFY OK: depth=2, C=VG, O=Surfshark, CN=Surfshark Root CA
Tue Feb  1 00:50:11 2022 VERIFY OK: depth=1, C=VG, O=Surfshark, CN=Surfshark Intermediate CA
Tue Feb  1 00:50:11 2022 VERIFY KU OK
Tue Feb  1 00:50:11 2022 Validating certificate extended key usage
Tue Feb  1 00:50:11 2022 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Tue Feb  1 00:50:11 2022 VERIFY EKU OK
Tue Feb  1 00:50:11 2022 VERIFY OK: depth=0, CN=sg-sng-v046.prod.surfshark.com
Tue Feb  1 00:50:12 2022 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1635', remote='link-mtu 1583'
Tue Feb  1 00:50:12 2022 WARNING: 'cipher' is used inconsistently, local='cipher AES-256-CBC', remote='cipher AES-256-GCM'
Tue Feb  1 00:50:12 2022 WARNING: 'auth' is used inconsistently, local='auth SHA512', remote='auth [null-digest]'
Tue Feb  1 00:50:12 2022 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Tue Feb  1 00:50:12 2022 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Tue Feb  1 00:50:12 2022 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 2048 bit RSA
Tue Feb  1 00:57:10 2022 Connection reset, restarting [0]
Tue Feb  1 00:57:10 2022 /etc/openvpn/tunnelDown.sh tun0 1500 1586 10.7.7.6 255.255.255.0 init
resolv.conf was restored
Sending kill signal to transmission-daemon
Successfuly closed transmission-daemon
Tue Feb  1 00:57:12 2022 /sbin/ip route del 89.187.163.210/32
Tue Feb  1 00:57:12 2022 /sbin/ip route del 0.0.0.0/1
Tue Feb  1 00:57:12 2022 /sbin/ip route del 128.0.0.0/1
Tue Feb  1 00:57:12 2022 Closing TUN/TAP interface
Tue Feb  1 00:57:12 2022 /sbin/ip addr del dev tun0 10.7.7.6/24
Tue Feb  1 00:57:12 2022 SIGTERM[soft,connection-reset] received, process exiting
```


Thank you for your support!

**Comment by tim0901** [comment]
> If you override the SIGUSR1 -> SIGTERM remapping in modify-openvpn-config.sh then proxied services are not broken when these signals are recieved because the container is no longer restarting - the service is restarting within the container. Not only is this bad practise for containers, but it also introduces a new problem: OpenVPN boot looping. After a few boot loops, the container starts failing to resolve the host address of the VPN server.
(Unfortunately I don't have a log for this - will replicate and add below when possible, but this may take several days.)

I've finally managed to reproduce this one. 

```
...
Wed Feb 16 15:36:45 2022 TLS: soft reset sec=0 bytes=2484849/-1 pkts=7243/0
Wed Feb 16 15:36:45 2022 VERIFY OK: depth=2, C=CA, ST=ON, L=Toronto, O=Windscribe Limited, OU=Systems, CN=Windscribe Node CA X1
Wed Feb 16 15:36:45 2022 VERIFY OK: depth=1, C=CA, ST=ON, L=Toronto, O=Windscribe Limited, OU=Systems, CN=Windscribe Node CA X2
Wed Feb 16 15:36:45 2022 VERIFY KU OK
Wed Feb 16 15:36:45 2022 Validating certificate extended key usage
Wed Feb 16 15:36:45 2022 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Wed Feb 16 15:36:45 2022 VERIFY EKU OK
Wed Feb 16 15:36:45 2022 VERIFY X509NAME OK: C=CA, ST=ON, L=Toronto, O=Windscribe Limited, OU=Systems, CN=cdg-342.windscribe.com
Wed Feb 16 15:36:45 2022 VERIFY OK: depth=0, C=CA, ST=ON, L=Toronto, O=Windscribe Limited, OU=Systems, CN=cdg-342.windscribe.com
Wed Feb 16 15:36:45 2022 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Wed Feb 16 15:36:45 2022 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Wed Feb 16 15:36:45 2022 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_AES_256_GCM_SHA384, 4096 bit RSA
Wed Feb 16 16:35:04 2022 [cdg-342.windscribe.com] Inactivity timeout (--ping-restart), restarting
Wed Feb 16 16:35:04 2022 SIGUSR1[soft,ping-restart] received, process restarting
Wed Feb 16 16:35:04 2022 Restart pause, 5 second(s)
Wed Feb 16 16:35:09 2022 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Wed Feb 16 16:35:09 2022 TCP/UDP: Preserving recently used remote address: [AF_INET]84.17.42.37:1194
Wed Feb 16 16:35:09 2022 Socket Buffers: R=[212992->425984] S=[212992->425984]
Wed Feb 16 16:35:09 2022 UDP link local: (not bound)
Wed Feb 16 16:35:09 2022 UDP link remote: [AF_INET]84.17.42.37:1194
Wed Feb 16 16:36:09 2022 [UNDEF] Inactivity timeout (--ping-restart), restarting
Wed Feb 16 16:36:09 2022 SIGUSR1[soft,ping-restart] received, process restarting
Wed Feb 16 16:36:09 2022 Restart pause, 5 second(s)
Wed Feb 16 16:36:14 2022 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Wed Feb 16 16:36:14 2022 TCP/UDP: Preserving recently used remote address: [AF_INET]84.17.42.2:1194
Wed Feb 16 16:36:14 2022 Socket Buffers: R=[212992->425984] S=[212992->425984]
Wed Feb 16 16:36:14 2022 UDP link local: (not bound)
Wed Feb 16 16:36:14 2022 UDP link remote: [AF_INET]84.17.42.2:1194
Wed Feb 16 16:37:14 2022 [UNDEF] Inactivity timeout (--ping-restart), restarting
Wed Feb 16 16:37:14 2022 SIGUSR1[soft,ping-restart] received, process restarting
Wed Feb 16 16:37:14 2022 Restart pause, 5 second(s)
Wed Feb 16 16:37:19 2022 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Wed Feb 16 16:37:29 2022 RESOLVE: Cannot resolve host address: cdg-342.whiskergalaxy.com:1194 (Temporary failure in name resolution)
Wed Feb 16 16:37:39 2022 RESOLVE: Cannot resolve host address: cdg-342.whiskergalaxy.com:1194 (Temporary failure in name resolution)
Wed Feb 16 16:37:54 2022 RESOLVE: Cannot resolve host address: cdg-342.whiskergalaxy.com:1194 (Temporary failure in name resolution)
Wed Feb 16 16:38:09 2022 RESOLVE: Cannot resolve host address: cdg-342.whiskergalaxy.com:1194 (Temporary failure in name resolution)
Wed Feb 16 16:38:09 2022 Could not determine IPv4/IPv6 protocol
Wed Feb 16 16:38:09 2022 SIGUSR1[soft,init_instance] received, process restarting
Wed Feb 16 16:38:09 2022 Restart pause, 5 second(s)
Wed Feb 16 16:38:14 2022 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Wed Feb 16 16:38:24 2022 RESOLVE: Cannot resolve host address: cdg-342.whiskergalaxy.com:1194 (Temporary failure in name resolution)
Wed Feb 16 16:38:34 2022 RESOLVE: Cannot resolve host address: cdg-342.whiskergalaxy.com:1194 (Temporary failure in name resolution)
Wed Feb 16 16:38:49 2022 RESOLVE: Cannot resolve host address: cdg-342.whiskergalaxy.com:1194 (Temporary failure in name resolution)
Wed Feb 16 16:39:04 2022 RESOLVE: Cannot resolve host address: cdg-342.whiskergalaxy.com:1194 (Temporary failure in name resolution)
Wed Feb 16 16:39:04 2022 Could not determine IPv4/IPv6 protocol
Wed Feb 16 16:39:04 2022 SIGUSR1[soft,init_instance] received, process restarting
Wed Feb 16 16:39:04 2022 Restart pause, 5 second(s)
Wed Feb 16 16:39:09 2022 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Wed Feb 16 16:39:19 2022 RESOLVE: Cannot resolve host address: cdg-342.whiskergalaxy.com:1194 (Temporary failure in name resolution)
Wed Feb 16 16:39:29 2022 RESOLVE: Cannot resolve host address: cdg-342.whiskergalaxy.com:1194 (Temporary failure in name resolution)
Wed Feb 16 16:39:44 2022 RESOLVE: Cannot resolve host address: cdg-342.whiskergalaxy.com:1194 (Temporary failure in name resolution)
Wed Feb 16 16:39:59 2022 RESOLVE: Cannot resolve host address: cdg-342.whiskergalaxy.com:1194 (Temporary failure in name resolution)
Wed Feb 16 16:39:59 2022 Could not determine IPv4/IPv6 protocol
Wed Feb 16 16:39:59 2022 SIGUSR1[soft,init_instance] received, process restarting
Wed Feb 16 16:39:59 2022 Restart pause, 5 second(s)
...
```
As you can see, at 16:35 the client recieved an inactivity timeout, which caused the system to restart. Due to the SIGUSR1 override, the container did not restart but instead OpenVPN restarted within the container. OpenVPN restarts several times in quick succession for a variety of reasons, before eventually entering a `Cannot resolve host address` loop which continues until the container stack is restarted. During this time the proxied services are still accessible from devices on my local network, but have no internet access.
 
I believe this instance was initiated by my internet connection dropping, but I've had this occur without a loss in internet connectivity in the past. Additionally, the restart loop did not recover when the internet connection was restored - it was still stuck in the same error loop when I found it two days later. As such, removing the remap of SIGUSR1 signals is not - at this time - a suitable fix to the issue presented above.

**Comment by pkishino** [comment]
this could be an issue with your provider which is rate-limiting the connection due to multiple rapid connections..

**Comment by tim0901** [comment]
I don't think so - after all if the logs are to be believed, this is the exact reason SIGUSR1 is remapped to SIGTERM in the first place:

`Modification: Remap SIGUSR1 signal to SIGTERM, avoid OpenVPN restart loop`

It also just doesn't really make sense as a reason. How would I be being rate-limited on the first restart? Why would restarting the container immediately fix the issue, despite only taking a few seconds longer? My guess is that it's an issue with the container's firewall - it is a DNS error after all. I guess I could check this by looking at outgoing packets from the host OS - are they actually making it out of the container?

Either way, removing the remapping of SIGUSR1 to SIGTERM probably isn't a valid avenue for fixing the problem in the title and as such I am completely lost as to how to resolve this issue.

**Comment by DrissiReda** [comment]
Same issue I'd like to reopen it.

I'm on Kubernetes, this is my setup:

```yaml

kind: Deployment
apiVersion: apps/v1
metadata:
  name: transmission-transmission-openvpn
  namespace: media
  labels:
    app: transmission-openvpn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transmission-openvpn
      release: transmission
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: transmission-openvpn
        release: transmission
    spec:
      volumes:
        - name: downloads
          persistentVolumeClaim:
            claimName: torrent-pvc
      containers:
        - name: transmission-openvpn
          image: haugene/transmission-openvpn:latest
          ports:
            - name: http
              containerPort: 9091
              protocol: TCP
          env:
            - name: LOCAL_NETWORK
              value: 10.244.0.0/24,192.168.1.0/24
            - name: OPENVPN_CONFIG
              value: Paris-Seine-tcp
            - name: OPENVPN_PROVIDER
              value: WINDSCRIBE
            - name: OPENVPN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: windscribe-credentials
                  key: username
            - name: OPENVPN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: windscribe-credentials
                  key: password
            - name: TRANSMISSION_RPC_WHITELIST
              value: 127.0.0.1,192.168.1.4,192.168.1.*
            - name: TRANSMISSION_RPC_WHITELIST_ENABLED
              value: 'true'
            - name: TRANSMISSION_RPC_USERNAME
              value: root
            - name: TRANSMISSION_RPC_PASSWORD
              value: <password>
            - name: TRANSMISSION_PEER_PORT
              value: '47444'
            - name: TRANSMISSION_RPC_AUTHENTICATION_REQUIRED
              value: 'true'
            - name: TRANSMISSION_DOWNLOAD_DIR
              value: /downloads
            - name: PUID
              value: '1000'
            - name: PGID
              value: '1000'
          resources: {}
          volumeMounts:
            - name: downloads
              mountPath: /data
              subPath: transmission
            - name: downloads
              mountPath: /downloads
          livenessProbe:
            httpGet:
              path: /
              port: 9091
              scheme: HTTP
            timeoutSeconds: 10
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /
              port: 9091
              scheme: HTTP
            timeoutSeconds: 10
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: None
      securityContext: {}
      schedulerName: default-scheduler
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 8.8.4.4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
```
