### ISSUE TITLE
DNS information not updated after vpn connection

### ISSUE THREAD

**Issue by usma0118** [haugene/docker-transmission-openvpn#2197]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [ ] I have tried using dev branch

### Docker run config used

---
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: transmission
    ver: v4
  name: transmission
  namespace: downloaders
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: transmission
      ver: v4
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: transmission
        ver: v4
    spec:
      containers:
      - env:
        - name: OPENVPN_PROVIDER
          value: vpnunlimited
        - name: OPENVPN_CONFIG
          value: fr
        - name: OPENVPN_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: "{redacted}"
        - name: OPENVPN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: "{redacted}"
        - name: TRANSMISSION_RPC_USERNAME
          value: "{redacted}"
        - name: TRANSMISSION_RPC_PASSWORD
          value: "{redacted}"
        - name: TRANSMISSION_RPC_AUTHENTICATION_REQUIRED
          value: "true"
        - name: TRANSMISSION_DOWNLOAD_DIR
          value: /downloads/transmission
        - name: PUID
          value: "1001"
        - name: PGID
          value: "1001"
        - name: TRANSMISSION_UMASK
          value: "18"
        - name: TRANSMISSION_RATIO_LIMIT
          value: "1"
        - name: TRANSMISSION_BLOCKLIST_ENABLED
          value: "true"
        - name: TRANSMISSION_BLOCKLIST_URL
          value: https://github.com/Naunter/BT_BlockLists/raw/master/bt_blocklists.gz
        - name: TRANSMISSION_ENCRYPTION
          value: "2"
        - name: TRANSMISSION_RATIO_LIMIT_ENABLED
          value: "true"
        - name: CREATE_TUN_DEVICE
          value: "true"
        - name: WEBPROXY_ENABLED
          value: "true"
        - name: WEBPROXY_PORT
          value: "8118"
        - name: TRANSMISSION_RPC_WHITELIST
          value: 10.1.183.*,127.0.0.1
        - name: TRANSMISSION_RPC_WHITELIST_ENABLED
          value: "true"
        - name: LOG_TO_STDOUT
          value: "true"
        - name: OPENVPN_OPTS
          value: --inactive 3600 --ping 10 --ping-exit 60
        - name: LOCAL_NETWORK
          value: 10.1.183.0/24
        image: haugene/transmission-openvpn:latest
        imagePullPolicy: Always
        name: transmission
        ports:
        - containerPort: 9091
          name: http
          protocol: TCP
        - containerPort: 8081
          name: webproxy
          protocol: TCP          
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          capabilities:
            add:
            - NET_ADMIN
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: transmission
          subPath: configs
        - mountPath: /downloads/transmission
          name: transmission
          subPath: downloads
        - mountPath: /etc/openvpn/vpnunlimited/fr.ovpn
          name: config
          subPath: fr.vpnunlimited.ovpn
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: transmission
        persistentVolumeClaim:
          claimName: transmissionv2
      - configMap:
          defaultMode: 420
          name: openvpn-common-config
        name: config
```

### Current Behavior

vpn connected successfully.
but DNS is not changed in /etc/resolv.conf

### Expected Behavior

DNS should be changed to vpn provider.

### How have you tried to solve the problem?

DNS lookup in container shows network connectivity.

```
dig @1.1.1.1 google.com
; <<>> DiG 9.16.1-Ubuntu <<>> @1.1.1.1 google.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 59036
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;google.com.                    IN      A

;; ANSWER SECTION:
google.com.             133     IN      A       142.250.201.174

;; Query time: 52 msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: Tue Feb 22 08:59:37 UTC 2022
;; MSG SIZE  rcvd: 55

```

### Log output

```
Starting container with revision: e6fd367db74075e2b507d420191a55a43b5e8d90
WARNING: initial DNS resolution test failed
Creating TUN device /dev/net/tun
Using OpenVPN provider: CUSTOM
Running with VPN_CONFIG_SOURCE auto
No bundled config script found for CUSTOM. Defaulting to external config
Downloading configs from https://github.com/haugene/vpn-configs-contrib/archive/main.zip into /tmp/tmp.l0qYbFjZLo
curl: (6) Could not resolve host: github.com
./etc/openvpn/fetch-external-configs.sh: line 16: config_repo_temp_dir: unbound variable
No VPN configuration provided. Using default.
Modifying /etc/openvpn/custom/default.ovpn for best behaviour in this container
Modification: Point auth-user-pass option to the username/password file
sed: cannot rename /etc/openvpn/custom/sedxzECRY: Device or resource busy
Modification: Change ca certificate path
sed: cannot rename /etc/openvpn/custom/sedA9GGn9: Device or resource busy
Modification: Change ping options
sed: cannot rename /etc/openvpn/custom/sedbv8Zuf: Device or resource busy
sed: cannot rename /etc/openvpn/custom/sedR3dJ0i: Device or resource busy
sed: cannot rename /etc/openvpn/custom/sed8beqFq: Device or resource busy
sed: cannot rename /etc/openvpn/custom/sedimyssu: Device or resource busy
/etc/openvpn/modify-openvpn-config.sh: line 45: /etc/openvpn/custom/default.ovpn: Read-only file system
/etc/openvpn/modify-openvpn-config.sh: line 46: /etc/openvpn/custom/default.ovpn: Read-only file system
/etc/openvpn/modify-openvpn-config.sh: line 47: /etc/openvpn/custom/default.ovpn: Read-only file system
Setting OpenVPN credentials...
adding route to local network 10.0.0.0/24 via 10.0.0.147 dev eth0
Tue Feb 22 03:04:00 2022 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jul 19 2021
Tue Feb 22 03:04:00 2022 library versions: OpenSSL 1.1.1f  31 Mar 2020, LZO 2.10
Tue Feb 22 03:04:00 2022 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Tue Feb 22 03:04:05 2022 TCP/UDP: Preserving recently used remote address: [AF_INET]195.154.189.85:1194
Tue Feb 22 03:04:05 2022 UDP link local: (not bound)
Tue Feb 22 03:04:05 2022 UDP link remote: [AF_INET]195.154.189.85:1194
Tue Feb 22 03:04:05 2022 [openvpn2.vpnunlimitedapp.com] Peer Connection Initiated with [AF_INET]195.154.189.85:1194
Tue Feb 22 03:04:11 2022 TUN/TAP device tun0 opened
Tue Feb 22 03:04:11 2022 /sbin/ip link set dev tun0 up mtu 1500
Tue Feb 22 03:04:11 2022 /sbin/ip addr add dev tun0 local 10.200.0.6 peer 10.200.0.5
Tue Feb 22 03:04:11 2022 /etc/openvpn/tunnelUp.sh tun0 1500 1553 10.200.0.6 10.200.0.5 init
Up script executed with tun0 1500 1553 10.200.0.6 10.200.0.5 init
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.200.0.6
Updating Transmission settings.json with values from env variables
Using existing settings.json for Transmission /data/transmission-home/settings.json
Overriding bind-address-ipv4 because TRANSMISSION_BIND_ADDRESS_IPV4 is set to 10.200.0.6
Overriding blocklist-enabled because TRANSMISSION_BLOCKLIST_ENABLED is set to true
Overriding blocklist-url because TRANSMISSION_BLOCKLIST_URL is set to https://github.com/Naunter/BT_BlockLists/raw/master/bt_blocklists.gz
Overriding dht-enabled because TRANSMISSION_DHT_ENABLED is set to true
Overriding download-dir because TRANSMISSION_DOWNLOAD_DIR is set to /downloads/transmission
Overriding encryption because TRANSMISSION_ENCRYPTION is set to 2
Overriding incomplete-dir because TRANSMISSION_INCOMPLETE_DIR is set to /data/incomplete
Overriding ratio-limit because TRANSMISSION_RATIO_LIMIT is set to 1
Overriding ratio-limit-enabled because TRANSMISSION_RATIO_LIMIT_ENABLED is set to true
Overriding rpc-authentication-required because TRANSMISSION_RPC_AUTHENTICATION_REQUIRED is set to true
Overriding rpc-password because TRANSMISSION_RPC_PASSWORD is set to [REDACTED]
Overriding rpc-port because TRANSMISSION_RPC_PORT is set to 9091
Overriding rpc-username because TRANSMISSION_RPC_USERNAME is set to secrets
Overriding rpc-whitelist because TRANSMISSION_RPC_WHITELIST is set to 10.0.0.*,127.0.0.1,192.100.1.*
Overriding rpc-whitelist-enabled because TRANSMISSION_RPC_WHITELIST_ENABLED is set to true
Overriding umask because TRANSMISSION_UMASK is set to 18
Overriding watch-dir because TRANSMISSION_WATCH_DIR is set to /data/watch
Overriding watch-dir-force-generic because TRANSMISSION_WATCH_DIR_FORCE_GENERIC is set to true
sed'ing True to true
Enforcing ownership on transmission config directories
Applying permissions to transmission config directories
Setting owner for transmission paths to 1001:1001
Setting permissions for download and incomplete directories
Mask: 022
Directories: 755
Files: 644
Setting permission for watch directory (775) and its files (664)

-------------------------------------
Transmission will run as
-------------------------------------
User name:   abc
User uid:    1001
User gid:    1001
-------------------------------------

STARTING TRANSMISSION
Transmission startup script complete.
Privoxy: Starting
Privoxy: Using config file at /etc/privoxy/config
Privoxy: Setting port to 8118
[2022-02-22 03:04:14.053] Transmission 2.94 (d8e60ee44f) started (session.c:740)
[2022-02-22 03:04:14.053] RPC Server Adding address to whitelist: 10.0.0.* (rpc-server.c:971)
[2022-02-22 03:04:14.053] RPC Server Adding address to whitelist: 127.0.0.1 (rpc-server.c:971)
[2022-02-22 03:04:14.053] RPC Server Adding address to whitelist: 192.100.1.* (rpc-server.c:971)
[2022-02-22 03:04:14.053] RPC Server Serving RPC and Web requests on port 127.0.0.1:9091/transmission/ (rpc-server.c:1213)
[2022-02-22 03:04:14.053] RPC Server Whitelist enabled (rpc-server.c:1217)
[2022-02-22 03:04:14.053] RPC Server Password required (rpc-server.c:1220)
[2022-02-22 03:04:14.053] Port Forwarding Stopped (port-forwarding.c:180)
[2022-02-22 03:04:14.053] DHT Generating new id (tr-dht.c:311)
[2022-02-22 03:04:14.053] Using settings from "/data/transmission-home" (daemon.c:528)
[2022-02-22 03:04:14.053] Saved "/data/transmission-home/settings.json" (variant.c:1266)
[2022-02-22 03:04:14.053] transmission-daemon requiring authentication (daemon.c:554)
[2022-02-22 03:04:14.053] Watching "/data/watch" for new .torrent files (daemon.c:573)
Privoxy: Running as PID 80
Tue Feb 22 03:04:14 2022 Initialization Sequence Completed
[2022-02-22 03:04:49.055] DHT Attempting bootstrap from dht.transmissionbt.com (tr-dht.c:248)
[2022-02-22 03:05:09.055] DHT dht.transmissionbt.com:6881: Temporary failure in name resolution (tr-dht.c:128)
[2022-02-22 03:06:24.056] DHT dht.transmissionbt.com:6881: Temporary failure in name resolution (tr-dht.c:128)
[2022-02-22 03:07:11.053] DHT dht.transmissionbt.com:6881: Temporary failure in name resolution (tr-dht.c:128)
[2022-02-22 03:07:59.053] DHT dht.transmissionbt.com:6881: Temporary failure in name resolution (tr-dht.c:128)
[2022-02-22 03:08:55.054] DHT dht.transmissionbt.com:6881: Temporary failure in name resolution (tr-dht.c:128)
[2022-02-22 03:09:37.054] DHT dht.transmissionbt.com:6881: Temporary failure in name resolution (tr-dht.c:128)
[2022-02-22 07:47:01.056] Searching for web interface file "/config/.local/share/transmission/web/index.html" (platform.c:430)
[2022-02-22 07:47:01.056] Searching for web interface file "/usr/share/transmission/web/index.html" (platform.c:430)
```

### HW/SW Environment

```markdown
- OS:Ubuntu 20.04
```
