### ISSUE TITLE
New VPN provider

### ISSUE THREAD

**Issue by nicolasbelanger** [haugene/docker-transmission-openvpn#221]
Hi,

Could you please add VPNSecure https://www.vpnsecure.me/ as a new provider?

Thanks,

Nicolas

**Comment by haugene** [comment]
Hi,

In order to add this provider I need the .ovpn config files for Linux setup. It's mentioned here: http://support.vpnsecure.me/articles/getting-started/linux-no-gui-ubuntu-openvpn-shell-only-setup

As long as the config files don't inlcude any authentication information you can provide me a link and I will add them. Otherwise you must follow the instructions for using a custom provider in the readme.

**Comment by nicolasbelanger** [comment]
I managed to make it work using the custom provider, thanks!

**Comment by dar8** [comment]
Hi! I tried with the custom provider setting, but I wasn't lucky :D 
Can you tell me how you did?
I have this error:
```
Using OpenVPN provider: CUSTOM
No VPN configuration provided. Using default.
Setting OPENVPN credentials...
adding route to local network 192.168.0.0/24 via 172.18.0.1 dev eth0
 WARNING: Ignoring option 'dh' in tls-client mode, please only include this in your server configuration
 OpenVPN 2.4.6 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Apr 24 2018
 library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08
 WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.
 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
 neither stdin nor stderr are a tty device and you have neither a controlling tty nor systemd - can't ask for 'Enter Private Key Password:'.  If you used --daemon, you need to use --askpass to make passphrase-protected keys work, and you can not use --auth-nocache.
 Exiting due to fatal error
```

Thanks

**Comment by AdrewKirts** [comment]
> Hi,
> 
> In order to add this provider I need the .ovpn config files for Linux setup. It's mentioned here: http://support.vpnsecure.me/articles/getting-started/linux-no-gui-ubuntu-openvpn-shell-only-setup
> 
> As long as the config files don't inlcude any authentication information you can provide me a link and I will add them. Otherwise you must follow the instructions for using a custom provider in the readme.

Hi Kristian, 
Here's a config file from vpnsecure, could you take a look at it and add it as a new provider? I changed my username to "USERNAME" inside the file and in the filename. 

Thanks in advance for your help ! 

[fr1-USERNAME.ovpn.zip](https://github.com/haugene/docker-transmission-openvpn/files/4221353/fr1-USERNAME.ovpn.zip)

**Comment by fleyd-1** [comment]
> I managed to make it work using the custom provider, thanks!

Hi there,

Can you share how you were able to config vpnsecure.me with Transmission (docker) please?

**Comment by nicolasbelanger** [comment]
@fleyd-1 
A couple of things.  

1. Mount your vpnsecure ovpn files into `/etc/openvpn/custom`:

Example with docker-compose:
```yaml
...
    volumes:
      - "<local/path/to/custom>:/etc/openvpn/custom"
...
```

2. Set those 2 env variables (where `my-config` refers to `my-config.ovpn` file that should be in the `<local/path/to/custom>` that you set on 1. :

Example with docker-compose:
```yaml
...
    environment:
      - OPENVPN_PROVIDER=CUSTOM
      - OPENVPN_CONFIG=my-config
...
```

Hope that helps!

**Comment by fleyd-1** [comment]
> @fleyd-1
> A couple of things.
> 
> 1. Mount your vpnsecure ovpn files into `/etc/openvpn/custom`:
> 
> Example with docker-compose:
> 
> ```yaml
> ...
>     volumes:
>       - "<local/path/to/custom>:/etc/openvpn/custom"
> ...
> ```
> 
> 1. Set those 2 env variables (where `my-config` refers to `my-config.ovpn` file that should be in the `<local/path/to/custom>` that you set on 1. :
> 
> Example with docker-compose:
> 
> ```yaml
> ...
>     environment:
>       - OPENVPN_PROVIDER=CUSTOM
>       - OPENVPN_CONFIG=my-config
> ...
> ```
> 
> Hope that helps!

Hi there and thanks for replying, i dont have much experience in this "linux vpn world", at the moment i am stuck [here](https://github.com/haugene/docker-transmission-openvpn/issues/1229)  just jump to the last post

The file/script i am running is this:

```
transmission-vpn:
    container_name: transmission-vpn
    image: haugene/transmission-openvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: always
    ports:
    - 9191:9191
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - ${USERDIR}/docker/transmission-vpn:/data
      - ${USERDIR}/docker/shared:/shared
      - /srv/dev-disk-by-label-1TB/Config/torrents:/torrents
      - /srv/dev-disk-by-label-1TB/Config/OVPN/:/etc/openvpn/custom/
    environment:
      - OPENVPN_PROVIDER=CUSTOM
      - OPENVPN_USERNAME=****
      - OPENVPN_PASSWORD=******
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=192.168.1.0/24
      - PUID=998
      - PGID=100
      - TZ=Europe/Lisbon #${TZ}
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      - TRANSMISSION_RPC_HOST_WHITELIST=127.0.0.1,192.168.1.*
      - TRANSMISSION_RPC_PASSWORD=user
      - TRANSMISSION_RPC_USERNAME=password
      - TRANSMISSION_RATIO_LIMIT=1.00
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
```
Any thoughts? because i dont have any more ideas... 

I can see the logs in the link i posted above, it seems fine (to me anyway), but transmission just run, it says it cant connect to server.

Thanks for helping

**Comment by nicolasbelanger** [comment]
Seems like you are only missing `OPENVPN_CONFIG` no?

**Comment by fleyd-1** [comment]
> Seems like you are only missing `OPENVPN_CONFIG` no?

Below  `- OPENVPN_PROVIDER=CUSTOM`

i sould add 1 or 2?
1. - OPENVPN_CONFIG=/srv/dev-disk-by-label-1TB/Config/OVPN/:/etc/openvpn/custom/
2. - OPENVPN_CONFIG=/srv/dev-disk-by-label-1TB/Config/OVPN/

thanks.

**Comment by nicolasbelanger** [comment]
None of the 2.... See my example:
```
- OPENVPN_CONFIG=my-config
```
would try to load `/srv/dev-disk-by-label-1TB/Config/OVPN/my-config.ovpn`

No really friendly I agree, but it works here ;)

**Comment by fleyd-1** [comment]
> None of the 2.... See my example:
> 
> ```
> - OPENVPN_CONFIG=my-config
> ```
> 
> would try to load `/srv/dev-disk-by-label-1TB/Config/OVPN/my-config.ovpn`
> 
> No really friendly I agree, but it works here ;)

i must be doing something wrong...

This is what i run:
(i named my ovpn file "default.ovpn" and not my-config.ovpn)
```
transmission-vpn:
    container_name: transmission-vpn
    image: haugene/transmission-openvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: always
    ports:
    - 9191:9191
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - ${USERDIR}/docker/transmission-vpn:/data
      - ${USERDIR}/docker/shared:/shared
      - /srv/dev-disk-by-label-1TB/Config/torrents:/torrents
      - /srv/dev-disk-by-label-1TB/Config/OVPN/:/etc/openvpn/custom/
    environment:
      - OPENVPN_PROVIDER=CUSTOM
      - OPENVPN_USERNAME=****
      - OPENVPN_PASSWORD=*******
      - OPENVPN_CONFIG=/srv/dev-disk-by-label-1TB/Config/OVPN/default.ovpn
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=192.168.1.0/24
      - PUID=998
      - PGID=100
      - TZ=Europe/Lisbon #${TZ}
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      - TRANSMISSION_RPC_HOST_WHITELIST=127.0.0.1,192.168.1.*
      - TRANSMISSION_RPC_PASSWORD=user
      - TRANSMISSION_RPC_USERNAME=password
      - TRANSMISSION_RATIO_LIMIT=1.00
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
```

And this is my   default.ovpn   file:

```
client
proto tcp
dev tun
dh dh2048.pem
ca /etc/openvpn/custom/ca.crt
cert /etc/openvpn/custom/fleyd.crt
key /etc/openvpn/custom/fleyd.key
askpass /etc/openvpn/custom/auth.txt
remote fr1.isponeder.com 1282
cipher AES-256-CBC
verb 2
mute 20
comp-lzo
persist-key
persist-tun
float
resolv-retry infinite
nobind
auth-nocache
remote-cert-tls server
```
My log in stacks > transmission-vpn are this:


```
Wed Jun  3 16:27:51 2020 event_wait : Interrupted system call (code=4)
Wed Jun  3 16:27:51 2020 Closing TUN/TAP interface
Wed Jun  3 16:27:51 2020 /sbin/ip addr del dev tun0 172.22.2.67/24
Wed Jun  3 16:27:51 2020 /etc/openvpn/tunnelDown.sh tun0 1500 1563 172.22.2.67 255.255.255.0 init
Wed Jun  3 16:27:51 2020 SIGTERM[hard,] received, process exiting
Using OpenVPN provider: CUSTOM
**Supplied config /srv/dev-disk-by-label-1TB/Config/OVPN/default.ovpn.ovpn could not be found.**
Using default OpenVPN gateway for provider custom
Setting OPENVPN credentials...
adding route to local network 192.168.1.0/24 via 172.17.0.1 dev eth0
Wed Jun  3 16:27:52 2020 WARNING: Ignoring option 'dh' in tls-client mode, please only include this in your server configuration
Wed Jun  3 16:27:52 2020 WARNING: file '/etc/openvpn/custom/fleyd.key' is group or others accessible
Wed Jun  3 16:27:52 2020 WARNING: file '/etc/openvpn/custom/auth.txt' is group or others accessible
Wed Jun  3 16:27:52 2020 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Sep  5 2019
Wed Jun  3 16:27:52 2020 library versions: OpenSSL 1.1.1c  28 May 2019, LZO 2.10
Wed Jun  3 16:27:52 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Wed Jun  3 16:27:52 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]217.78.6.187:110
Wed Jun  3 16:27:52 2020 Attempting to establish TCP connection with [AF_INET]217.78.6.187:110 [nonblock]
Wed Jun  3 16:27:53 2020 TCP connection established with [AF_INET]217.78.6.187:110
Wed Jun  3 16:27:53 2020 TCP_CLIENT link local: (not bound)
Wed Jun  3 16:27:53 2020 TCP_CLIENT link remote: [AF_INET]217.78.6.187:110
Wed Jun  3 16:27:53 2020 VERIFY OK: depth=1, C=US, ST=NY, L=New York, O=vpnsecure.me, emailAddress=support@vpnsecure.me
Wed Jun  3 16:27:53 2020 VERIFY KU OK
Wed Jun  3 16:27:53 2020 Validating certificate extended key usage
Wed Jun  3 16:27:53 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Wed Jun  3 16:27:53 2020 VERIFY EKU OK
Wed Jun  3 16:27:53 2020 VERIFY OK: depth=0, C=US, ST=NY, L=New York, O=vpnsecure.me, OU=Office, CN=vpnsecure-server, emailAddress=support@vpnsecure.me
Wed Jun  3 16:27:53 2020 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 2048 bit RSA
Wed Jun  3 16:27:53 2020 [vpnsecure-server] Peer Connection Initiated with [AF_INET]217.78.6.187:110
Wed Jun  3 16:27:55 2020 Outgoing Data Channel: Cipher 'AES-256-CBC' initialized with 256 bit key
Wed Jun  3 16:27:55 2020 Outgoing Data Channel: Using 160 bit message hash 'SHA1' for HMAC authentication
Wed Jun  3 16:27:55 2020 Incoming Data Channel: Cipher 'AES-256-CBC' initialized with 256 bit key
Wed Jun  3 16:27:55 2020 Incoming Data Channel: Using 160 bit message hash 'SHA1' for HMAC authentication
Wed Jun  3 16:27:55 2020 TUN/TAP device tun0 opened
Wed Jun  3 16:27:55 2020 /sbin/ip link set dev tun0 up mtu 1500
Wed Jun  3 16:27:55 2020 /sbin/ip addr add dev tun0 172.22.2.67/24 broadcast 172.22.2.255
Wed Jun  3 16:27:55 2020 /etc/openvpn/tunnelUp.sh tun0 1500 1563 172.22.2.67 255.255.255.0 init
Up script executed with tun0 1500 1563 172.22.2.67 255.255.255.0 init
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 172.22.2.67
Generating transmission settings.json from env variables
sed'ing True to true
Enforcing ownership on transmission config directories
Applying permissions to transmission config directories
Setting owner for transmission paths to 998:100
setting permission for files (644) and directories (755)
Setting permission for watch directory (775) and its files (664)
-------------------------------------
Transmission will run as
-------------------------------------
User name:   abc
User uid:    998
User gid:    100
-------------------------------------
STARTING TRANSMISSION
NO PORT UPDATER FOR THIS PROVIDER
Transmission startup script complete.
Wed Jun  3 16:27:55 2020 Initialization Sequence Completed
```
What could be wrong? 

In the log is this: "Supplied config /srv/dev-disk-by-label-1TB/Config/OVPN/default.ovpn.ovpn could not be found" the name of the real file is just "default.ovpn"

**Comment by nicolasbelanger** [comment]
```
**Supplied config /srv/dev-disk-by-label-1TB/Config/OVPN/default.ovpn.ovpn could not be found.**

```
Told you, il concats the `.ovpn` for you(`default.ovpn.ovpn`)

**Comment by fleyd-1** [comment]
> ```
> **Supplied config /srv/dev-disk-by-label-1TB/Config/OVPN/default.ovpn.ovpn could not be found.**
> ```
> 
> Told you, it concats the `.ovpn` for you(`default.ovpn.ovpn`)


Now i have this log:

```
Using OpenVPN provider: CUSTOM
Supplied config /srv/dev-disk-by-label-1TB/Config/OVPN/default.ovpn.ovpn could not be found.
Using default OpenVPN gateway for provider custom
Setting OPENVPN credentials...
adding route to local network 192.168.1.0/24 via 172.17.0.1 dev eth0
Options error: In [CMD-LINE]:1: Error opening configuration file: /etc/openvpn/custom/default.ovpn
Use --help for more information.
```

1. this file exists, i can see it throw filezilla 
`/srv/dev-disk-by-label-1TB/Config/OVPN/default.ovpn.ovpn`

2. and this file, _wich is the same content, except the extension_, also exists
`/etc/openvpn/custom/default.ovpn`

what could be happening? i have deleted the container and started again, restarted docker...

**Comment by nicolasbelanger** [comment]
Have you tried
```
- OPENVPN_CONFIG=default
```
?

**Comment by nicolasbelanger** [comment]
Before digging into the ovpn content, your issue is that the file is just not found.

If I may, from reading ^^^, it looks like you have this `/srv/dev-disk-by-label-1TB/Config/OVPN/default.ovpn.ovpn` on local.  So my suggestion would be either:

1. Rename it to /srv/dev-disk-by-label-1TB/Config/OVPN/default.ovpn
Or
2. Have OPENVPN_CONFIG=default.ovpn (which will effectively load /srv/dev-disk-by-label-1TB/Config/OVPN/default.ovpn.ovpn)

Like I said, this is not as friendly as we could expect...

**Comment by fleyd-1** [comment]
> Before digging into the ovpn content, your issue is that the file is just not found.
> 
> If I may, from reading ^^^, it looks like you have this `/srv/dev-disk-by-label-1TB/Config/OVPN/default.ovpn.ovpn` on local. So my suggestion would be either:
> 
> 1. Rename it to /srv/dev-disk-by-label-1TB/Config/OVPN/default.ovpn
>    Or
> 2. Have OPENVPN_CONFIG=default.ovpn (which will effectively load /srv/dev-disk-by-label-1TB/Config/OVPN/default.ovpn.ovpn)
> 
> Like I said, this is not as friendly as we could expect...

I did your first option and now i have this log:

```
Wed Jun  3 18:46:46 2020 TCP: connect to [AF_INET]64.20.43.202:1191 failed: Connection refused
Wed Jun  3 18:46:46 2020 SIGUSR1[connection failed(soft),init_instance] received, process restarting
Wed Jun  3 18:47:26 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Wed Jun  3 18:47:26 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]64.20.43.202:1191
```

**Comment by nicolasbelanger** [comment]
There you go!  Now you have issues with the config itself...

Mine:
```
client
proto udp
dev tun
ca /etc/openvpn/custom/ca.crt
dh /etc/openvpn/custom/dh2048.pem
cert /etc/openvpn/custom/<mycert>.crt
key /etc/openvpn/custom/<my_decrypted_key>.key
remote ca1.isponeder.com 1282
cipher AES-256-CBC
verb 2
mute 20
keepalive 10 120
comp-lzo
persist-key
persist-tun
float
resolv-retry infinite
nobind
auth-nocache
remote-cert-tls server
```

**Comment by fleyd-1** [comment]
i have been testing and with this ovpn file

```
client
proto udp
dev tun
ca /etc/openvpn/custom/ca.crt
dh /etc/openvpn/custom/dh2048.pem
cert /etc/openvpn/custom/fleyd.crt
key /etc/openvpn/custom/fleyd.key
askpass /etc/openvpn/custom/auth.txt
remote ca1.isponeder.com 1282
cipher AES-256-CBC
verb 2
mute 20
comp-lzo
persist-key
persist-tun
float
resolv-retry infinite
nobind
auth-nocache
remote-cert-tls server
```

i got this log:

```
Using OpenVPN provider: CUSTOM
No VPN configuration provided. Using default.
Setting OPENVPN credentials...
adding route to local network 192.168.1.0/24 via 172.17.0.1 dev eth0
Wed Jun  3 20:09:33 2020 WARNING: Ignoring option 'dh' in tls-client mode, please only include this in your server configuration
Wed Jun  3 20:09:33 2020 WARNING: file '/etc/openvpn/custom/fleyd.key' is group or others accessible
Wed Jun  3 20:09:33 2020 WARNING: file '/etc/openvpn/custom/auth.txt' is group or others accessible
Wed Jun  3 20:09:33 2020 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Sep  5 2019
Wed Jun  3 20:09:33 2020 library versions: OpenSSL 1.1.1c  28 May 2019, LZO 2.10
Wed Jun  3 20:09:33 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Wed Jun  3 20:09:34 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]67.215.7.186:1282
Wed Jun  3 20:09:34 2020 UDP link local: (not bound)
Wed Jun  3 20:09:34 2020 UDP link remote: [AF_INET]67.215.7.186:1282
Wed Jun  3 20:09:34 2020 VERIFY OK: depth=1, C=US, ST=NY, L=New York, O=vpnsecure.me, emailAddress=support@vpnsecure.me
Wed Jun  3 20:09:34 2020 VERIFY KU OK
Wed Jun  3 20:09:34 2020 Validating certificate extended key usage
Wed Jun  3 20:09:34 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Wed Jun  3 20:09:34 2020 VERIFY EKU OK
Wed Jun  3 20:09:34 2020 VERIFY OK: depth=0, C=US, ST=NY, L=New York, O=vpnsecure.me, OU=Office, CN=vpnsecure-server, emailAddress=support@vpnsecure.me
Wed Jun  3 20:09:34 2020 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 2048 bit RSA
Wed Jun  3 20:09:34 2020 [vpnsecure-server] Peer Connection Initiated with [AF_INET]67.215.7.186:1282
Wed Jun  3 20:09:36 2020 NOTE: setsockopt TCP_NODELAY=1 failed
Wed Jun  3 20:09:36 2020 Outgoing Data Channel: Cipher 'AES-256-CBC' initialized with 256 bit key
Wed Jun  3 20:09:36 2020 Outgoing Data Channel: Using 160 bit message hash 'SHA1' for HMAC authentication
Wed Jun  3 20:09:36 2020 Incoming Data Channel: Cipher 'AES-256-CBC' initialized with 256 bit key
Wed Jun  3 20:09:36 2020 Incoming Data Channel: Using 160 bit message hash 'SHA1' for HMAC authentication
Wed Jun  3 20:09:36 2020 TUN/TAP device tun0 opened
Wed Jun  3 20:09:36 2020 /sbin/ip link set dev tun0 up mtu 1500
Wed Jun  3 20:09:36 2020 /sbin/ip addr add dev tun0 172.21.2.35/24 broadcast 172.21.2.255
Wed Jun  3 20:09:36 2020 /etc/openvpn/tunnelUp.sh tun0 1500 1561 172.21.2.35 255.255.255.0 init
Up script executed with tun0 1500 1561 172.21.2.35 255.255.255.0 init
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 172.21.2.35
Generating transmission settings.json from env variables
sed'ing True to true
Enforcing ownership on transmission config directories
Applying permissions to transmission config directories
Setting owner for transmission paths to 998:100
Setting permission for files (644) and directories (755)
Setting permission for watch directory (775) and its files (664)
-------------------------------------
Transmission will run as
-------------------------------------
User name:   abc
User uid:    998
User gid:    100
-------------------------------------
STARTING TRANSMISSION
NO PORT UPDATER FOR THIS PROVIDER
Transmission startup script complete.
Wed Jun  3 20:09:36 2020 Initialization Sequence Completed
```

Seems ok BUT transmission doesn´t open, when go to 192.***.1.198:9091 it just says `Connection Failed Could not connect to the server. You may need to reload the page to reconnect.`

**Comment by fleyd-1** [comment]
> There you go! Now you have issues with the config itself...
> 
> Mine:
> 
> ```
> client
> proto udp
> dev tun
> ca /etc/openvpn/custom/ca.crt
> dh /etc/openvpn/custom/dh2048.pem
> cert /etc/openvpn/custom/<mycert>.crt
> key /etc/openvpn/custom/<my_decrypted_key>.key
> remote ca1.isponeder.com 1282
> cipher AES-256-CBC
> verb 2
> mute 20
> keepalive 10 120
> comp-lzo
> persist-key
> persist-tun
> float
> resolv-retry infinite
> nobind
> auth-nocache
> remote-cert-tls server
> ```

Hi again and sorry for disturbing again, i believe that the vpn part is working in my case, but somehow i cant access the web ui of transmission.

Can i ask you to share the script you ran in Stacks - Portainer please?

This i what i am running now:
```
transmission-vpn:
    container_name: transmission-vpn
    image: haugene/transmission-openvpn:latest
    restart: always
    cap_add:
      - NET_ADMIN # This runs the container with raised privileges
    devices:
      - /dev/net/tun
    ports:
    - 9191:9191 #GUI Port
    - 8888:8888 #Transmission Port
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - /srv/dev-disk-by-label-1TB/Config/OVPN/:/etc/openvpn/custom/   
      #- ${USERDIR}/docker/transmission-vpn:/data
      #- ${USERDIR}/docker/shared:/shared
      #- /srv/dev-disk-by-label-1TB/Config/torrents:/torrents
      #- /docker/transmission-vpn/transmission-home/torrents
      - /docker/transmission-vpn/transmission-home/torrents:/data
      #- /docker//shared:/shared
      #- /etc/localtime:/etc/localtime:ro
      #- /sharedfolders/:/data
      #- /sharedfolders/appdata/vpntrans:/config
      #- /docker/transmission-vpn:/data
      #- /docker/shared:/shared
      #- /srv/dev-disk-by-label-1TB/Config/OVPN/ #this doesnt work, can´t find config files

    environment:
      - OPENVPN_PROVIDER=CUSTOM
      - OPENVPN_USERNAME=*****
      - OPENVPN_PASSWORD=*********
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=192.168.1.0/24
      - PUID=998
      - PGID=100
      - TZ=Europe/Lisbon #${TZ}
      - TRANSMISSION_RPC_HOST_WHITELIST="127.0.0.1,192.168.1.*"
      # 
      # below is testing
      #- HEALTH_CHECK_HOST=google.com
      #- DOCKER_LOG=false
      #- TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=false #true
      #- TRANSMISSION_RPC_PORT=9091
      - WEBPROXY_ENABLED=true #false default is false
      #- WEBPROXY_PORT=8888
      #- LOCAL_NETWORK=192.168.0.0/24
      #- TRANSMISSION_PORT_FORWARDING_ENABLED=true
      #- TRANSMISSION_PEER_PORT=5141
      #- TRANSMISSION_WATCH_DIR=/docker/transmission-vpn/watch
      #- TRANSMISSION_WATCH_DIR_ENABLED=true
      #- TRANSMISSION_RPC_PORT=9091
      - TRANSMISSION_HOME=/docker/transmission-vpn
      - TRANSMISSION_WEB_UI=transmission-web-control
```

With that script i have this log:
```
Using OpenVPN provider: CUSTOM


No VPN configuration provided. Using default.


Setting OPENVPN credentials...


adding route to local network 192.168.1.0/24 via 172.17.0.1 dev eth0


Thu Jun  4 14:45:28 2020 WARNING: Ignoring option 'dh' in tls-client mode, please only include this in your server configuration


Thu Jun  4 14:45:28 2020 WARNING: file '/etc/openvpn/custom/fleyd.key' is group or others accessible


Thu Jun  4 14:45:28 2020 WARNING: file '/etc/openvpn/custom/auth.txt' is group or others accessible


Thu Jun  4 14:45:28 2020 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Sep  5 2019


Thu Jun  4 14:45:28 2020 library versions: OpenSSL 1.1.1c  28 May 2019, LZO 2.10


Thu Jun  4 14:45:28 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts


Thu Jun  4 14:45:28 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]144.48.105.34:1282


Thu Jun  4 14:45:28 2020 UDP link local: (not bound)


Thu Jun  4 14:45:28 2020 UDP link remote: [AF_INET]144.48.105.34:1282


Thu Jun  4 14:45:28 2020 VERIFY OK: depth=1, C=US, ST=NY, L=New York, O=vpnsecure.me, emailAddress=support@vpnsecure.me


Thu Jun  4 14:45:28 2020 VERIFY KU OK


Thu Jun  4 14:45:28 2020 Validating certificate extended key usage


Thu Jun  4 14:45:28 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication


Thu Jun  4 14:45:28 2020 VERIFY EKU OK


Thu Jun  4 14:45:28 2020 VERIFY OK: depth=0, C=US, ST=NY, L=New York, O=vpnsecure.me, OU=Office, CN=vpnsecure-server, emailAddress=support@vpnsecure.me


Thu Jun  4 14:45:29 2020 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 2048 bit RSA


Thu Jun  4 14:45:29 2020 [vpnsecure-server] Peer Connection Initiated with [AF_INET]144.48.105.34:1282


Thu Jun  4 14:45:30 2020 NOTE: setsockopt TCP_NODELAY=1 failed


Thu Jun  4 14:45:30 2020 Outgoing Data Channel: Cipher 'AES-256-CBC' initialized with 256 bit key


Thu Jun  4 14:45:30 2020 Outgoing Data Channel: Using 160 bit message hash 'SHA1' for HMAC authentication


Thu Jun  4 14:45:30 2020 Incoming Data Channel: Cipher 'AES-256-CBC' initialized with 256 bit key


Thu Jun  4 14:45:30 2020 Incoming Data Channel: Using 160 bit message hash 'SHA1' for HMAC authentication


Thu Jun  4 14:45:30 2020 TUN/TAP device tun0 opened


Thu Jun  4 14:45:30 2020 /sbin/ip link set dev tun0 up mtu 1500


Thu Jun  4 14:45:30 2020 /sbin/ip addr add dev tun0 172.21.2.173/24 broadcast 172.21.2.255


Thu Jun  4 14:45:30 2020 /etc/openvpn/tunnelUp.sh tun0 1500 1561 172.21.2.173 255.255.255.0 init


Up script executed with tun0 1500 1561 172.21.2.173 255.255.255.0 init


Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 172.21.2.173


Using Transmission Web Control  UI, overriding TRANSMISSION_WEB_HOME


Generating transmission settings.json from env variables


sed'ing True to true


Enforcing ownership on transmission config directories


Applying permissions to transmission config directories


Setting owner for transmission paths to 998:100


Setting permission for files (644) and directories (755)


Setting permission for watch directory (775) and its files (664)




-------------------------------------


Transmission will run as


-------------------------------------


User name:   abc


User uid:    998


User gid:    100


-------------------------------------




STARTING TRANSMISSION


NO PORT UPDATER FOR THIS PROVIDER


Transmission startup script complete.


STARTING TINYPROXY


Found config file /etc/tinyproxy/tinyproxy.conf, updating settings.


Setting tinyproxy port to 8888


Starting Tinyproxy lightweight HTTP proxy daemon: tinyproxy.


Tinyproxy startup script complete.


Thu Jun  4 14:45:31 2020 Initialization Sequence Completed
```

**Comment by nicolasbelanger** [comment]
I also run this:

```yaml
  proxy:
    image: haugene/transmission-openvpn-proxy
    restart: always
    ports:
      - 8880:8080
    links:
      - transmission
    volumes:
      - /etc/localtime:/etc/localtime:ro
```

as shown here: https://github.com/haugene/docker-transmission-openvpn/blob/master/docker-compose.yml

**Comment by fleyd-1** [comment]
> ```yaml
> proxy:
>     image: haugene/transmission-openvpn-proxy
>     restart: always
>     ports:
>       - 8880:8080
>     links:
>       - transmission
>     volumes:
>       - /etc/localtime:/etc/localtime:ro
> ```

When i add those rows/lines to the script it says "proxy is an unsupported config option...." it doesnt even run.... 

That is a separate stack? If yes. how do i run it? because i tried and it says "has a link to transmission who is undefinied"

Sorry, where should i add those lines?

**Comment by nicolasbelanger** [comment]
It's another service (typically another container) that runs alongside. If you look carefully the example here [https://github.com/haugene/docker-transmission-openvpn/blob/master/docker-compose.yml] It's defined into the same docker-compose.yaml file.  Also, make sure to name the link correctly:

```yaml
    links:
      - transmission-vpn
```
is probably what you should have based on the examples you provided previously.

Good luck!

**Comment by fleyd-1** [comment]
> It's another service (typically another container) that runs alongside. If you look carefully the example here https://github.com/haugene/docker-transmission-openvpn/blob/master/docker-compose.yml . It's defined into the same docker-compose.yaml file. Also, make sure to name the link correctly:
> 
> ```yaml
>     links:
>       - transmission-vpn
> ```
> 
> is probably what you should have based on the examples you provided previously.
> 
> Good luck!

I am trying but still with no success.... 

- In Portainer > Container i have pulled `haugene/transmission-openvpn-proxy`
- In Filezilla i searched for the yml file similar to the one in the link you send... then i realize i could just add the lines you said in the editor (in Portainer > Stacks). So i add these to the ones i had:
```
proxy:
    image: haugene/transmission-openvpn-proxy:latest
    restart: always
    ports:
      - 8880:8080
    links:
      - transmission-vpn
    volumes:
      - /etc/localtime:/etc/localtime:ro
```
where it is `- transmission-vpn`          i tried only  `- transmission`  and  `- transmissionvpn` . The name of that in stacks is `transmission-vpn`

The state of both is this:
![image](https://user-images.githubusercontent.com/64219933/83789289-65b2b980-a68e-11ea-87d0-05d6c0fb4903.png)

BUT i cannot access Transmission web ui here   http://192.168.1.198:9091/

**Can you please figure what i am doing wrong?**

This is the log of transmissionvpn_proxy_1:
```
2020/06/04 17:59:59 [emerg] 1#1: host not found in upstream "transmission" in /etc/nginx/nginx.conf:14
nginx: [emerg] host not found in upstream "transmission" in /etc/nginx/nginx.conf:14
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: IPv6 listen already enabled, exiting
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
```
