### ISSUE TITLE
Sudden error on startup

### ISSUE THREAD

**Issue by jes1417** [haugene/docker-transmission-openvpn#2301]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [X] I have tried using dev branch

### Docker run config used

```
version: "2"
services:
  transmission-openvpn:
    image: haugene/transmission-openvpn
    container_name: transmission-openvpn
    environment:
      - CREATE_TUN_DEVICE=true
      - PUID=1000
      - PGID=100
      - OPENVPN_PROVIDER=IPVANISH
      - OPENVPN_CONFIG=ipvanish-US-Dallas-dal-a02,ipvanish-US-Dallas-dal-a22,ipvanish-US-Dallas-dal-a28,ipvanish-US-Houston-hou-c20.ovpn,ipvanish-US-Houston-hou-c31.ovpn,ipvanish-US-Houston-hou-c22.ovpn
      - OPENVPN_USERNAME=xxxxxxxxxxxxxxxxxxxx
      - OPENVPN_PASSWORD=xxxxxxxxxxxxx
      - LOCAL_NETWORK=192.168.1.0/24,192.168.10.0/24
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60 --pull-filter ignore ping
      - TRANSMISSION_WEB_UI=flood-for-transmission
      - TRANSMISSION_WATCH_DIR=/data/torrent/watch
      - TRANSMISSION_INCOMPLETE_DIR_ENABLED=true
      - TRANSMISSION_INCOMPLETE_DIR=/data/torrent/incomplete
      - TRANSMISSION_HOME=/data/torrent/transmission-home
      - TRANSMISSION_DOWNLOAD_DIR=/data/torrent/completed
      - TRANSMISSION_UMASK=2
    cap_add:
      - NET_ADMIN
    volumes:
      - /data/torrent:/data/torrent
      - /etc/localtime:/etc/localtime:ro
      - /appdata/TransmissionOpenVPN:/config
      - /data/torrent:/data
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - 9091:9091
    restart: unless-stopped
```

### Current Behavior

Container does not start due to issue with zip file for VPN configs

### Expected Behavior

This issue just happened with no changes on my end, container has been working for years with no issues

### How have you tried to solve the problem?

Its worked on the latest release for months

### Log output

```
Starting container with revision: 44c82aa1297b0f4473ad141f2cea326b407d9c22
Creating TUN device /dev/net/tun
Using OpenVPN provider: IPVANISH
Running with VPN_CONFIG_SOURCE auto
Provider IPVANISH has a bundled setup script. Defaulting to internal config
Executing setup script for IPVANISH
Downloading OpenVPN config bundle configs.zip into temporary file /tmp/tmp.NZXgNwIkk5
Extract OpenVPN config bundle into /etc/openvpn/ipvanish
[/tmp/tmp.NZXgNwIkk5]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /tmp/tmp.NZXgNwIkk5 or
        /tmp/tmp.NZXgNwIkk5.zip, and cannot find /tmp/tmp.NZXgNwIkk5.ZIP, period.
```

### HW/SW Environment

```markdown
- OS: openmediavault 6
- Docker:
```
