### ISSUE TITLE
Extracting OpenVPN config bundle fails to extract (IPVANISH)

### ISSUE THREAD

**Issue by mim212** [haugene/docker-transmission-openvpn#2303]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [ ] I have tried using dev branch

### Docker run config used

```
 transmission-vpn:
    container_name: transmission-vpn
    #image: haugene/transmission-openvpn:3.7.1
    image: haugene/transmission-openvpn:latest
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: always
    ports:
    - "9091:9091"
    #dns:
    #  - 1.1.1.1
    #  - 1.0.0.1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/docker/transmission-vpn:/data
      - ${USERDIR}/docker/shared:/shared
      - /WD-ext/Downloads:/data/watch
      - /WD-ext/Downloads/completed:/data/completed
      - /WD-ext/Downloads/incomplete:/data/incomplete
    environment:
      - OPENVPN_PROVIDER=IPVANISH
      - OPENVPN_USERNAME=${IPVUSER}
      - OPENVPN_PASSWORD=${IPVPASS}
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=192.168.2.0/24
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      - TRANSMISSION_RPC_HOST_WHITELIST="127.0.0.1,192.168.*.*"
      - TRANSMISSION_RPC_PASSWORD=${TRAPASS}
      - TRANSMISSION_RPC_USERNAME=${TRAUSER}
      - TRANSMISSION_UMASK=2
      - TRANSMISSION_RATIO_LIMIT=1
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true

```

### Current Behavior

Container is currently fails on boot because it cannot cannot find the End-of-central-directory signature when downloading the configs.zip file
```
2022-08-02T09:45:28.291429000Z Starting container with revision: 901c0d2def15fcbd2e2cde2bddd1799678e85a31
2022-08-02T09:45:28.321419000Z Creating TUN device /dev/net/tun
2022-08-02T09:45:28.325473000Z Using OpenVPN provider: IPVANISH
2022-08-02T09:45:28.325596000Z Running with VPN_CONFIG_SOURCE auto
2022-08-02T09:45:28.325673000Z Provider IPVANISH has a bundled setup script. Defaulting to internal config
2022-08-02T09:45:28.325739000Z Executing setup script for IPVANISH
2022-08-02T09:45:28.327859000Z Downloading OpenVPN config bundle configs.zip into temporary file /tmp/tmp.OflgHOhCEW
2022-08-02T09:45:28.605286000Z Extract OpenVPN config bundle into /etc/openvpn/ipvanish
2022-08-02T09:45:28.607616000Z [/tmp/tmp.OflgHOhCEW]
2022-08-02T09:45:28.607829000Z   End-of-central-directory signature not found.  Either this file is not
2022-08-02T09:45:28.607950000Z   a zipfile, or it constitutes one disk of a multi-part archive.  In the
2022-08-02T09:45:28.608044000Z   latter case the central directory and zipfile comment will be found on
2022-08-02T09:45:28.608144000Z   the last disk(s) of this archive.
2022-08-02T09:45:28.608333000Z unzip:  cannot find zipfile directory in one of /tmp/tmp.OflgHOhCEW or
2022-08-02T09:45:28.608449000Z         /tmp/tmp.OflgHOhCEW.zip, and cannot find /tmp/tmp.OflgHOhCEW.ZIP, period.
```

### Expected Behavior

Extract the zip correctly and start the transmission client

### How have you tried to solve the problem?

1) Tried 3.7.1 and latest, both have the same issue
2) added 8.8.8.8 to DNS as trial, with no difference
3) pulled latest image and recreated container with no change

### Log output

  latter case the central directory and zipfile comment will be found on,
  the last disk(s) of this archive.,
unzip:  cannot find zipfile directory in one of /tmp/tmp.DD1LDXzVKB or,
        /tmp/tmp.DD1LDXzVKB.zip, and cannot find /tmp/tmp.DD1LDXzVKB.ZIP, period.,
Starting container with revision: 901c0d2def15fcbd2e2cde2bddd1799678e85a31,
Creating TUN device /dev/net/tun,
mknod: /dev/net/tun: File exists,
Using OpenVPN provider: IPVANISH,
Running with VPN_CONFIG_SOURCE auto,
Provider IPVANISH has a bundled setup script. Defaulting to internal config,
Executing setup script for IPVANISH,
Downloading OpenVPN config bundle configs.zip into temporary file /tmp/tmp.CvaSnxAgZd,
Extract OpenVPN config bundle into /etc/openvpn/ipvanish,
[/tmp/tmp.CvaSnxAgZd],
  End-of-central-directory signature not found.  Either this file is not,
  a zipfile, or it constitutes one disk of a multi-part archive.  In the,
  latter case the central directory and zipfile comment will be found on,
  the last disk(s) of this archive.,
unzip:  cannot find zipfile directory in one of /tmp/tmp.CvaSnxAgZd or,
        /tmp/tmp.CvaSnxAgZd.zip, and cannot find /tmp/tmp.CvaSnxAgZd.ZIP, period.,
Starting container with revision: 901c0d2def15fcbd2e2cde2bddd1799678e85a31,
Creating TUN device /dev/net/tun,
mknod: /dev/net/tun: File exists,
Using OpenVPN provider: IPVANISH,
Running with VPN_CONFIG_SOURCE auto,
Provider IPVANISH has a bundled setup script. Defaulting to internal config,
Executing setup script for IPVANISH,
Downloading OpenVPN config bundle configs.zip into temporary file /tmp/tmp.tK90ug25O6,
Extract OpenVPN config bundle into /etc/openvpn/ipvanish,
[/tmp/tmp.tK90ug25O6],
  End-of-central-directory signature not found.  Either this file is not,
  a zipfile, or it constitutes one disk of a multi-part archive.  In the,
  latter case the central directory and zipfile comment will be found on,
  the last disk(s) of this archive.,
unzip:  cannot find zipfile directory in one of /tmp/tmp.tK90ug25O6 or,
        /tmp/tmp.tK90ug25O6.zip, and cannot find /tmp/tmp.tK90ug25O6.ZIP, period.,
Starting container with revision: 901c0d2def15fcbd2e2cde2bddd1799678e85a31,
Creating TUN device /dev/net/tun,
mknod: /dev/net/tun: File exists,
Using OpenVPN provider: IPVANISH,
Running with VPN_CONFIG_SOURCE auto,
Provider IPVANISH has a bundled setup script. Defaulting to internal config,
Executing setup script for IPVANISH,
Downloading OpenVPN config bundle configs.zip into temporary file /tmp/tmp.lfRENWZExz,
Extract OpenVPN config bundle into /etc/openvpn/ipvanish,
[/tmp/tmp.lfRENWZExz],
  End-of-central-directory signature not found.  Either this file is not,
  a zipfile, or it constitutes one disk of a multi-part archive.  In the,
  latter case the central directory and zipfile comment will be found on,
  the last disk(s) of this archive.,
unzip:  cannot find zipfile directory in one of /tmp/tmp.lfRENWZExz or,
        /tmp/tmp.lfRENWZExz.zip, and cannot find /tmp/tmp.lfRENWZExz.ZIP, period.,
Starting container with revision: 901c0d2def15fcbd2e2cde2bddd1799678e85a31,
Creating TUN device /dev/net/tun,
mknod: /dev/net/tun: File exists,
Using OpenVPN provider: IPVANISH,
Running with VPN_CONFIG_SOURCE auto,
Provider IPVANISH has a bundled setup script. Defaulting to internal config,
Executing setup script for IPVANISH,
Downloading OpenVPN config bundle configs.zip into temporary file /tmp/tmp.En3Me3OSJx,
Extract OpenVPN config bundle into /etc/openvpn/ipvanish,
[/tmp/tmp.En3Me3OSJx],
  End-of-central-directory signature not found.  Either this file is not,
  a zipfile, or it constitutes one disk of a multi-part archive.  In the,
  latter case the central directory and zipfile comment will be found on,
  the last disk(s) of this archive.,
unzip:  cannot find zipfile directory in one of /tmp/tmp.En3Me3OSJx or,
        /tmp/tmp.En3Me3OSJx.zip, and cannot find /tmp/tmp.En3Me3OSJx.ZIP, period.,
Starting container with revision: 901c0d2def15fcbd2e2cde2bddd1799678e85a31,
Creating TUN device /dev/net/tun,
mknod: /dev/net/tun: File exists,
Using OpenVPN provider: IPVANISH,
Running with VPN_CONFIG_SOURCE auto,
Provider IPVANISH has a bundled setup script. Defaulting to internal config,
Executing setup script for IPVANISH,
Downloading OpenVPN config bundle configs.zip into temporary file /tmp/tmp.JkRx0AVFOr,
Extract OpenVPN config bundle into /etc/openvpn/ipvanish,
[/tmp/tmp.JkRx0AVFOr],
  End-of-central-directory signature not found.  Either this file is not,
  a zipfile, or it constitutes one disk of a multi-part archive.  In the,
  latter case the central directory and zipfile comment will be found on,
  the last disk(s) of this archive.,
unzip:  cannot find zipfile directory in one of /tmp/tmp.JkRx0AVFOr or,
        /tmp/tmp.JkRx0AVFOr.zip, and cannot find /tmp/tmp.JkRx0AVFOr.ZIP, period.,
Starting container with revision: 901c0d2def15fcbd2e2cde2bddd1799678e85a31,
Creating TUN device /dev/net/tun,
mknod: /dev/net/tun: File exists,
Using OpenVPN provider: IPVANISH,
Running with VPN_CONFIG_SOURCE auto,
Provider IPVANISH has a bundled setup script. Defaulting to internal config,
Executing setup script for IPVANISH,
Downloading OpenVPN config bundle configs.zip into temporary file /tmp/tmp.Wbke7YcIPt,
Extract OpenVPN config bundle into /etc/openvpn/ipvanish,
[/tmp/tmp.Wbke7YcIPt],
  End-of-central-directory signature not found.  Either this file is not,
  a zipfile, or it constitutes one disk of a multi-part archive.  In the,
  latter case the central directory and zipfile comment will be found on,
  the last disk(s) of this archive.,
unzip:  cannot find zipfile directory in one of /tmp/tmp.Wbke7YcIPt or,
        /tmp/tmp.Wbke7YcIPt.zip, and cannot find /tmp/tmp.Wbke7YcIPt.ZIP, period.,

### HW/SW Environment

```markdown
- OS: Debian GNU/Linux 11 bullseye (x86-64)
- Docker: version 20.10.12 build e91ed57
```
