### ISSUE TITLE
Cannot find a way to set preallocation settings

### ISSUE THREAD

**Issue by blitzmann** [haugene/docker-transmission-openvpn#2310]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [ ] I have tried using dev branch

### Docker run config used

```
transmission-openvpn:
    volumes:
        - /srv/dev-disk-by-uuid-d32018a9-cacb-412d-853d-9151fb426940/AppConfig/Transmission:/data
        - /etc/localtime:/etc/localtime:ro
    environment:
        - PUID=1000
        - PGID=100
        - CREATE_TUN_DEVICE=true
        - OPENVPN_PROVIDER=NORDVPN
        # - OPENVPN_CONFIG=default
        - NORDVPN_COUNTRY=US
        - NORDVPN_CATEGORY=legacy_p2p
        - NORDVPN_PROTOCOL=udp
        - OPENVPN_USERNAME=
        - OPENVPN_PASSWORD=
        - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
        - WEBPROXY_ENABLED=false
        - LOCAL_NETWORK=192.168.1.0/24
        - TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=false
        - TRANSMISSION_WEB_UI=transmission-web-control
        - DNS=8.8.8.8,8.8.4.4
    cap_add:
        - NET_ADMIN
    logging:
        driver: json-file
        options:
            max-size: 10m
    ports:
        - 9091:9091
    restart: always
    image: haugene/transmission-openvpn
 
```

### Current Behavior

I try to edit the `settings.json` but it reverts every time the container restarts. I understand the reasoning behind this, in which contianer configuration is supposed to be done via env variables. However, I'm trying to set `"preallocation": 0` and am unsure how to do this via env variables, if it's even possible

### Expected Behavior

I wish to be able to set my settings, specifically `preallocation`, how I need them, either through settings/json which persists (preferred), or if thats not possible, through env variables

### How have you tried to solve the problem?

1) set settings.json
2) look for env variable pertaining to this setting

### Log output

n/a

### HW/SW Environment

```markdown
- OS: 
- Docker:
```

**Comment by blitzmann** [comment]
ofc immediately after I post this

https://haugene.github.io/docker-transmission-openvpn/config-options/#transmission_configuration_options

It seems to suggest that settings.json is persisted, but for me it's not. Oh well, using the TRANSMISSION_ variable seems to work.

**Comment by pkishino** [comment]
If you edit settings.json on the running container it will NOT persist. Stop the container, edit then start

**Comment by gustavodeon** [comment]
Having this same issue, I'm trying to set 'download-dir' and 'incomplete-dir' on Settings.json, but every time I start the container it resets. I thought this would save me:

> Stop the container, edit then start

but sadly it didn't solve the problem, and even worse I can't find an env to set the download directory, only the incomplete one.

Here's my current setup: 
```
transmission:
    cap_add:
      - NET_ADMIN
    container_name: transmission-vpn
    environment:
      - PUID=1000
      - PGID=1000
      - OPENVPN_PROVIDER=custom
      - OPENVPN_CONFIG=us-free-18.protonvpn.net.udp
      - OPENVPN_USERNAME=${TRANSMISSION_OPENVPN_USERNAME}
      - OPENVPN_PASSWORD=${TRANSMISSION_OPENVPN_PASSWORD}
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=${DOCKER_HOST_NETWORK_CIDR}
      - TRANSMISSION_WEB_UI=flood-for-transmission
      - TZ=${TIMEZONE}
    hostname: transmission
    image: haugene/transmission-openvpn:latest
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - 9091:9091
    restart: unless-stopped
    volumes:
      - /home/gustavo/aplications/transmission/config/:/config/
      - /home/gustavo/aplications/transmission/cert/:/etc/openvpn/custom/
      - ${DOWNLOAD_FOLDER_PATH}:/downloads/
      - /home/gustavo/aplications/transmission/data/:/data/
    networks:
      - reverseproxy-nw
   ```
