### ISSUE TITLE
Container exits with code 0 but it should be a non-zero code

### ISSUE THREAD

**Issue by theAkito** [haugene/docker-transmission-openvpn#2341]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [X] I have tried using dev branch

### Docker run config used

```yaml
version: '3.7'
services:
  transmission-openvpn:
    container_name: transmission-openvpn
    cap_add:
      - NET_ADMIN
.....
.....
.....
  autoheal: # https://github.com/willfarrell/docker-autoheal
    image: willfarrell/autoheal
    environment: # https://github.com/willfarrell/docker-autoheal#env-defaults
      - AUTOHEAL_CONTAINER_LABEL=autoheal
      - AUTOHEAL_INTERVAL=5   # check every 5 seconds
      - AUTOHEAL_START_PERIOD=30   # wait 0 seconds before first health check
      - AUTOHEAL_DEFAULT_STOP_TIMEOUT=10   # Docker waits max 10 seconds (the Docker default) for a container to stop before killing during restarts (container overridable via label, see below)
      - DOCKER_SOCK=/var/run/docker.sock   # Unix socket for curl requests to Docker API
      - CURL_TIMEOUT=10     # --max-time seconds for curl requests to Docker API
      - WEBHOOK_URL=""    # post message to the webhook if a container was restarted (or restart failed)
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
```

### Current Behavior

```
transmission-openvpn    | [Secure-Server] Inactivity timeout (--ping-restart), restarting
transmission-openvpn    | /etc/openvpn/tunnelDown.sh tun0 ***************************************** init
transmission-openvpn    | resolv.conf was restored
transmission-openvpn    | Sending kill signal to transmission-daemon
transmission-openvpn    | Waiting 5s for transmission-daemon to die
transmission-openvpn    | Successfuly closed transmission-daemon
.....
.....
.....
transmission-openvpn    | SIGTERM[soft,ping-restart] received, process exiting
transmission-openvpn exited with code 0
```

The container exits with code 0.

### Expected Behavior

The container shall exit with a non-zero code, to indicate failure, i.e. unhealthiness, so the `autoheal` functionality kicks in.

### How have you tried to solve the problem?

This is an essential issue with the Docker image, so upstream needs to fix it.

### Log output

```
transmission-openvpn    | [Secure-Server] Inactivity timeout (--ping-restart), restarting
transmission-openvpn    | /etc/openvpn/tunnelDown.sh tun0 ***************************************** init
transmission-openvpn    | resolv.conf was restored
transmission-openvpn    | Sending kill signal to transmission-daemon
transmission-openvpn    | Waiting 5s for transmission-daemon to die
transmission-openvpn    | Successfuly closed transmission-daemon
.....
.....
.....
transmission-openvpn    | SIGTERM[soft,ping-restart] received, process exiting
transmission-openvpn exited with code 0
```

### HW/SW Environment

```markdown
- OS: Debian GNU/Linux 11 (bullseye)
- Docker: 20.10.17
```

### Anything else?

I did not find the script that manages the error catching & manipulation, in this repository. I can fix it, if you show me where these OpenVPN related errors are handled & manipulated.

This is why I decided to use Autoheal.
* https://github.com/haugene/docker-transmission-openvpn/blob/25b9724178f48227084f5a462b82b1fbc087498d/docs/faq.md#set-the-ping-exit-option-for-openvpn-and-restart-flag-in-docker
* https://github.com/haugene/docker-transmission-openvpn/blob/25b9724178f48227084f5a462b82b1fbc087498d/docs/faq.md#use-a-third-party-tool-to-monitor-and-restart-the-container
