### ISSUE TITLE
Starting from docker-compose

### ISSUE THREAD

**Issue by jagorski2** [haugene/docker-transmission-openvpn#236]
Using the default docker-compose.yml file and current repo.

When running 
    docker-compose up

I get:
transmission_1  | Using OpenVPN provider: PIA
transmission_1  | No VPN configuration provided. Using default.
transmission_1  | Setting OPENVPN credentials...
transmission_1  | adding route to local network 192.168.0.0/24 via 172.18.0.1 dev eth0
transmission_1  | Options error: the --down directive should have at most 1 parameter.  To pass a list of arguments as one of the parameters, try enclosing them in double quotes ("").

Any ideas?

**Comment by rourke** [comment]
Change
        - OPENVPN_OPTS="--inactive 3600 --ping 10 --ping-exit 60"
to
        - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60

That worked for me.

**Comment by haugene** [comment]
Any luck?

**Comment by byronmejia** [comment]
Just had same issue as @jagorski2 and can confirm following @rourke advice worked in my case.

Running Moby on Windows 10 in my situation.

**Comment by byronmejia** [comment]
My compose file, for reference:

```yaml
version: "3"
services:
  transmission:
    container_name: transmission
    privileged: true
    restart: always
    image: haugene/transmission-openvpn
    environment:
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_CONFIG=Netherlands
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=192.168.1.0/24
    volumes:
      - ./transmission:/data
    env_file:
      - transmission.env
    dns:
      - 8.8.8.8
      - 8.8.4.4
  transmission-proxy:
    container_name: transmission-proxy
    image: haugene/transmission-openvpn-proxy
    ports:
      - "8080:8080"
    links:
      - transmission:transmission
```
