### ISSUE TITLE
Stored rpc credentials cleared if not included in environment variables or docker secrets

### ISSUE THREAD

**Issue by toddrob99** [haugene/docker-transmission-openvpn#2387]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [X] I have tried using dev branch

### Docker run config used

```
version: '3.3'
services:
  transmission:
    container_name: transmission
    cap_add:
      - NET_ADMIN
    volumes:
      - /volume1/Downloads:/downloads
      - /volume1/Downloads/transmission/completed:/data/completed
      - /volume1/Downloads/transmission/incomplete:/data/incomplete
      - /volume1/Downloads/transmission/watch:/data/watch
      - ./transmission-home:/data/transmission-home
      - ./config:/config
    environment:
      - PUID=1033
      - PGID=65537
      - TZ=America/New_York
      - OPENVPN_PROVIDER=NORDVPN
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=192.168.0.0/23
      - WEBPROXY_ENABLED=true
      - WEBPROXY_PORT=8118
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      - TRANSMISSION_RPC_ENABLED=true
      - TRANSMISSION_RPC_USERNAME=xxxx
      - TRANSMISSION_RPC_PASSWORD=xxxx
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - '9091:9091'
      - '8118:8118'
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: unless-stopped
    image: haugene/transmission-openvpn
    networks:
      - media-automation

  transmission-proxy:
    container_name: transmission-proxy
    links:
      - 'transmission:transmission'
    ports:
      - '8888:8080'
    image: haugene/transmission-openvpn-proxy
    networks:
      - media-automation

networks:
  media-automation:
    name: media-automation
    external: true
```

### Current Behavior

Discussion in #2386 

After upgrading to the latest version, rpc credentials are wiped out if not included in the container's environment variables or docker secrets. Logging in with blank username/password works, but previously-stored credentials do not.

Previously, I set the username/password via environment variables and they were written to transmission-credentials.txt, and then removed the environment variables to avoid having my password in the docker-compose.yml file. The values in transmission-credentials.txt would persist across container restarts/recreations.

It appears the logic introduced in #2321 to support docker secrets has broken this scenario, and the values in transmission-credentials.txt are wiped out if not still defined in environment variables.

### Expected Behavior

Values in transmission-credentials.txt should not be cleared out upon container start if no credentials are defined in environment variables or docker secrets.

### How have you tried to solve the problem?

Tested by adding rpc username/password back to environment variables and confirming that works. Then removed environment variables and observed transmission-credentials.txt was cleared out upon container restart. Found #2321 and reviewed the logic--it appears pre-existing values in transmission-credentials.txt are not considered.

### Log output

```
TRANSMISSION_HOME is currently set to: /config/transmission-home
WARNING: Deprecated. Found old default transmission-home folder at /data/transmission-home, setting this as TRANSMISSION_HOME. This might break in future versions.
We will fallback to this directory as long as the folder exists. Please consider moving it to /config/<transmission-home>
Enforcing ownership on transmission config directory
Applying permissions to transmission config directory
Setting owner for transmission paths to 1033:65537
Setting permissions for download and incomplete directories
Mask: 002
Directories: 775
Files: 664
Setting permission for watch directory (775) and its files (664)

-------------------------------------
Transmission will run as
-------------------------------------
User name:   abc
User uid:    1033
User gid:    65537
-------------------------------------

Updating Transmission settings.json with values from env variables
Attempting to use existing settings.json for Transmission
Successfully used existing settings.json /data/transmission-home/settings.json
Overriding bind-address-ipv4 because TRANSMISSION_BIND_ADDRESS_IPV4 is set to 10.8.3.10
Overriding download-dir because TRANSMISSION_DOWNLOAD_DIR is set to /data/completed
Overriding incomplete-dir because TRANSMISSION_INCOMPLETE_DIR is set to /data/incomplete
Overriding rpc-authentication-required because TRANSMISSION_RPC_AUTHENTICATION_REQUIRED is set to true
Overriding rpc-enabled because TRANSMISSION_RPC_ENABLED is set to true
Overriding rpc-password because TRANSMISSION_RPC_PASSWORD is set to [REDACTED]
Overriding rpc-port because TRANSMISSION_RPC_PORT is set to 9091
Overriding rpc-username because TRANSMISSION_RPC_USERNAME is set to
Overriding watch-dir because TRANSMISSION_WATCH_DIR is set to /data/watch
sed'ing True to true
STARTING TRANSMISSION
Transmission startup script complete.
Privoxy: Starting
Privoxy: Using config file at /etc/privoxy/config
Privoxy: Setting port to 8118
Privoxy: Running as PID 155
Thu Nov 10 08:57:09 2022 Initialization Sequence Completed
```

### HW/SW Environment

```markdown
- OS: DSM 7.1.1-42962
- Docker: 20.10.3, build 55f0773
```
