### ISSUE TITLE
OVPN break

### ISSUE THREAD

**Issue by derekcentrico** [haugene/docker-transmission-openvpn#2388]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [X] I have tried using dev branch

### Docker run config used

see additional comments

### Current Behavior

Doesn't start

### Expected Behavior

Should start.

### How have you tried to solve the problem?

see additional comments

### Log output

Docker log:
```
Downloading configs from https://github.com/haugene/vpn-configs-contrib/archive/main.zip into /tmp/tmp.ts3MuwQ1bS
Extracting configs to /tmp/tmp.XnhThWs1rH
Found configs for OVPN in /tmp/tmp.XnhThWs1rH/vpn-configs-contrib-main/openvpn/ovpn, will replace current content in /etc/openvpn/ovpn
Cleanup: deleting /tmp/tmp.ts3MuwQ1bS and /tmp/tmp.XnhThWs1rH
No VPN configuration provided. Using default.
Modifying /etc/openvpn/ovpn/default.ovpn for best behaviour in this container
Modification: Point auth-user-pass option to the username/password file
sed: can't read /etc/openvpn/ovpn/default.ovpn: No such file or directory
Modification: Change ca certificate path
sed: can't read /etc/openvpn/ovpn/default.ovpn: No such file or directory

### HW/SW Environment

```markdown
- OS:  Ubuntu 22.04
- Docker:  4.2
```

### Anything else?

I am not sure what may have changed in the other updates to create 4.2.  However, the OVPN script broke.  It worked fine by dumping into /tmp/ and moving the files prior to the latest merge of all the other changes.  I tested it again on an old docker build and it worked fine still.  

Script that is used:
```
wget -c https://github.com/haugene/vpn-configs-contrib/archive/refs/heads/main.zip  -P /tmp/
echo "Extract OpenVPN config bundle into $VPN_PROVIDER_HOME"
unzip /tmp/main.zip "vpn-configs-contrib-main/openvpn/ovpn/*" -d /tmp/
mv /tmp/vpn-configs-contrib-main/openvpn/ovpn/* /etc/openvpn/ovpn
rm /tmp/vpn-configs-contrib-main/openvpn/ovpn/ -R
```

I am unsure if we need to specify further a directory for the output due to other changes since it seems to be dumping into random subdirectories within /tmp/ suddenly?

**Comment by derekcentrico** [comment]
Mind is running on this while supposed to be working (ugh)

@haugene  @pkishino  I presume, whatever the change, modifying wget to "wget -c **-O main.zip** https://github.com/haugene/vpn-configs-contrib/archive/refs/heads/main.zip  -P /tmp/" (emphasis added) would solve it.  Thoughts? 

Again, 4.0 works fine no issues as originally committed.  Gonna be a bit busy the next few days so can't build 4.2. to toy with it at the moment.

**Comment by DanGarion** [comment]
So it looks like this is what is going on with mine today. 

/etc/openvpn/start.sh: line 321: OPENVPN_OPTS: unbound variable

**Comment by derekcentrico** [comment]
@DanGarion so there's a change I wrote back in 4.0 that just made it to the main branch.  It is a selector to pick the OVPN options vs. using just the single server that was used.

Check out https://haugene.github.io/docker-transmission-openvpn/provider-specific/.  Looks like one of the tables is borked, but I don't see the error in the commit for the table.  

Basically, you add new variables into the ENV to get whatever server/protocol you want.

**Comment by greasykumquat** [comment]
Same situation here, same error as DanGarion. I messed with the variables in my compose a bit, adding in some to select specific countries, types, protocols, etc. No change in behaivor.

Rolled down to 4.1 and it works as expected with the same variables I'd added trying get 4.2 to work. Not sure if that helps at all, but I wanted to add that tidbit of info.

**Comment by derekcentrico** [comment]
So to be fair, the only way you would have been using the changes to OVPN would be to use the dev branch or building your own docker image with the script added.  I did all the work using the main branch for 4.0 with the modifications and committed from there.  I hopped on my test server and confirmed it was all functional after seeing the errors in 4.2.

**Comment by derekcentrico** [comment]
Everyone, temporary fix for you is to add this ENV:
      - GITHUB_CONFIG_SOURCE_REPO=derekcentrico/vpn-configs-contrib

I added the default.ovpn file there so it will allow your systems to work until there is a patch to whatever conflicts in 4.2.

**Comment by willekind** [comment]
Mine also broke with the `/etc/openvpn/start.sh: line 321: OPENVPN_OPTS: unbound variable` error. Downgraded to 4.1 resolved the issue.

**Comment by derekcentrico** [comment]
Okay, forget my comment on the wget.  The output I see is likely that 4.2 is not running the configure-openvpn.sh.  It then is going on to the external contrib assumption and downloading the vpn repo that does not have the default.ovpn.  So 4.2 is not actually using the 4.0 changes for OVPN but of course the VPN repo does not have old static file in place which causes this to fail to start.

**Comment by DanGarion** [comment]
I tried creating a new container with the above-mentioned ENV setting and that seemed to not solve anything. More than happy to do some additional testing or prodding if needed. I'll see about downgrading and holding for now. Might need to turn off my autoupdater. :)

**Comment by derekcentrico** [comment]
https://github.com/haugene/docker-transmission-openvpn/pull/2390 fixes this.  It appears the script lost its executable permissions when merged at some point.  Apologies all as I likely was the culprit in my foolishness.  Glad I skipped out on a meeting so this didn't eat at me.  

Workaround until a new master build is available would be to use:
- GITHUB_CONFIG_SOURCE_REPO=derekcentrico/vpn-configs-contrib

Or, you could maybe run docker run -it --entrypoint sh <image name> and chmod 755 the file.  ENV is smoother to be sure.

**Comment by MastaG** [comment]
Adding:
```
GITHUB_CONFIG_SOURCE_REPO=derekcentrico/vpn-configs-contrib
```
To my environment doesn't seem to fix: ```/etc/openvpn/start.sh: line 321: OPENVPN_OPTS: unbound variable```

**Comment by MastaG** [comment]
I've changed the CMD in docker compose to read:
```command: sh -c " chmod 0755 /etc/openvpn/ovpn/configure-openvpn.sh && dumb-init /etc/openvpn/start.sh "```

I've verified that ```/etc/openvpn/ovpn/configure-openvpn.sh``` now had the executable bit, but it still errors out with:
```/etc/openvpn/start.sh: line 321: OPENVPN_OPTS: unbound variable```

My config:
```
version: '3.3'
services:
    transmission-openvpn:
        cap_add:
            - NET_ADMIN
        volumes:
            - '/volume1/shared/transmission:/data'
            - '/volume1/shared:/shared'
        environment:
            - OPENVPN_PROVIDER=NORDVPN
            - NORDVPN_COUNTRY=NL
            - NORDVPN_PROTOCOL=udp
            - NORDVPN_CATEGORY=legacy_p2p
            - OPENVPN_USERNAME=X
            - OPENVPN_PASSWORD=X
            - LOCAL_NETWORK=192.168.2.0/24
            - TZ=Europe/Amsterdam
            - PUID=X
            - PGID=X
            - TRANSMISSION_DOWNLOAD_DIR=/shared/videos
            - TRANSMISSION_INCOMPLETE_DIR=/shared/incomplete
            - GLOBAL_APPLY_PERMISSIONS=false
        command: sh -c " chmod 0755 /etc/openvpn/ovpn/configure-openvpn.sh && dumb-init /etc/openvpn/start.sh "
        logging:
            driver: json-file
            options:
                max-size: 10m
        restart: always
        ports:
            - '9091:9091'
        image: haugene/transmission-openvpn:latest
```
