### ISSUE TITLE
rm -f tun device breaks startup

### ISSUE THREAD

**Issue by polaris940** [haugene/docker-transmission-openvpn#2389]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [ ] I have tried using dev branch

### Docker run config used

```yaml
# docker compose
version: "3.3"
services:
  transmission:
    image: haugene/transmission-openvpn
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
```

> pinning it to 4.1 works without any additional changes

### Current Behavior

container fails to start when trying to remove /dev/net/tun

### Expected Behavior

Failing gracefully and/or using the existing tun device that is passed through

### How have you tried to solve the problem?

- Reverting to 4.1 allows it to startup fine again
- Have also tried mucking with the permissions at the host level. No joy

## v4.2
```
Starting container with revision: f9cb4dea2da1a3aa63bd3945e0162c9b8a9789a4
Creating TUN device /dev/net/tun
rm: cannot remove '/dev/net/tun': Device or resource busy
# forces container restart loop
```

##  v4.1
```
<TIMESTAMP> Starting container with revision: 84941a9ea4663d8b2e1af3db1d50fe4f7fa8736e
<TIMESTAMP> Creating TUN device /dev/net/tun
<TIMESTAMP> mknod: /dev/net/tun: File exists
<TIMESTAMP> chmod: changing permissions of '/dev/net/tun': Operation not permitted
...
<TIMESTAMP> STARTING TRANSMISSION
<TIMESTAMP> Transmission startup script complete.
<TIMESTAMP> Initialization Sequence Completed
```

### HW/SW Environment

```markdown
- OS: Proxmox VE
- Docker: 20.10.12, build e91ed57

- LXC host with Docker container running transmission-openvpn
- permissions for /dev/net/tun are set on the host and then passed through to the container
```

### Anything else?

Appears to be related to https://github.com/haugene/docker-transmission-openvpn/issues/2296.

Seems like trying to force the removal of the device in this instance doesn't work since permissions are set at the host level and passed all the way through. Likely just needs to be able to fail gracefully.

**Comment by ianhundere** [comment]
same behavior here as well

**Comment by polaris940** [comment]
Resolved this with an environment config. `CREATE_TUN_DEVICE=false` can be set to disable removing/creating the tun device and allows the container to start. 

```yaml
# docker compose
version: "3.3"
services:
  transmission:
    image: haugene/transmission-openvpn:4.2
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    environment:
      - CREATE_TUN_DEVICE=false
```
