### ISSUE TITLE
pull request 2196 breaking-change; privoxy only listens to eth0 (not eth1, eth2 etc.)

### ISSUE THREAD

**Issue by planetrocky** [haugene/docker-transmission-openvpn#2398]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [ ] I have tried using dev branch

### Docker run config used

N/A

### Current Behavior

privoxy no longer listens to eth1

### Expected Behavior

privoxy used to listen to eth1

### How have you tried to solve the problem?

rolled back to release 4.0

### Log output

N/A

### HW/SW Environment

```markdown
- OS:
- Docker: yes
```

**Comment by planetrocky** [comment]
https://github.com/haugene/docker-transmission-openvpn/pull/2196

**Comment by edgd1er** [comment]
proxy used to listen to all adresses (0.0.0.0)  including vpn, turning your container into an open proxy, not sure this is what you want.
You can either push a merge request to specify interface to listen to or define a way to listen to all safe interfaces.

**Comment by samuv** [comment]
I was using this as a proxy too 🤔

**Comment by haugene** [comment]
@samuv I think your boot loop could be the combination of `devices` and `CREATE_TUN_DEVICE`. Would need to get some logs as well but have a look at #2393 and #2389

**Comment by samuv** [comment]
> @samuv I think your boot loop could be the combination of `devices` and `CREATE_TUN_DEVICE`. Would need to get some logs as well but have a look at #2393 and #2389

Ok thanks @haugene, after your advice, I have tried different things:

I have removed from the config the `device` and left `CREATE_TUN_DEVICE=true`, but the error persisted, so I tried to also remove the `sysctls` and set `OPENVPN_OPTS=` to empty, and it works 🥳 

I should try again, enabling one change at a time to understand what the problem was, but this config works for me:

```yaml
version: '3.7'

services:
  transmission:
    image: haugene/transmission-openvpn:latest
    container_name: transmission
    networks:
      - media_server
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    ports:
      - 9091:9091
      - 1111:1111 #other-service
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - /share/CACHEDEV1_DATA/Public/transmission/:/data
      - /share/CACHEDEV1_DATA/Public/open-vpn:/etc/openvpn/custom
    environment:
      - PUID=1000
      - PGID=0
      - TZ=Europe/Rome
      - CREATE_TUN_DEVICE=true
      - OPENVPN_PROVIDER=PROTONVPN
      - OPENVPN_USERNAME=
      - OPENVPN_PASSWORD=
      - OPENVPN_CONFIG=ch.protonvpn.net.udp,lv.protonvpn.net.udp
      - OPENVPN_OPTS=
      - VPN_CONFIG_SOURCE=auto
      - LOCAL_NETWORK=192.168.0.0/16
      - HEALTH_CHECK_HOST=google.com
      - TRANSMISSION_BLOCKLIST_ENABLED=true
      - TRANSMISSION_BLOCKLIST_URL=https://github.com/Naunter/BT_BlockLists/raw/master/bt_blocklists.gz
      - TRANSMISSION_RATIO_LIMIT=0.1
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
      - TRANSMISSION_SPEED_LIMIT_UP=2000
      - TRANSMISSION_SPEED_LIMIT_UP_ENABLED=true
      - TRANSMISSION_WEB_UI=flood-for-transmission
    logging:
      driver: json-file
      options:
        max-size: 10m

  other-service:
    image: myservice
    container_name: myservice
    network_mode: service:transmission
    depends_on:
      - transmission
    environment:
      - PUID=1000
      - PGID=0
      - TZ=Europe/Rome
    volumes:
      - stuff/config:/config
    restart: unless-stopped

networks:
  media_server:
    driver: bridge
```
