### ISSUE TITLE
crash on boot event_wait : Interrupted system call

### ISSUE THREAD

**Issue by DrissiReda** [haugene/docker-transmission-openvpn#2460]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [ ] I have tried using dev branch

### Docker run config used

I'm on Kubernetes, this is my setup:

```yaml

kind: Deployment
apiVersion: apps/v1
metadata:
  name: transmission-transmission-openvpn
  namespace: media
  labels:
    app: transmission-openvpn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transmission-openvpn
      release: transmission
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: transmission-openvpn
        release: transmission
    spec:
      volumes:
        - name: downloads
          persistentVolumeClaim:
            claimName: torrent-pvc
      containers:
        - name: transmission-openvpn
          image: haugene/transmission-openvpn:latest
          ports:
            - name: http
              containerPort: 9091
              protocol: TCP
          env:
            - name: LOCAL_NETWORK
              value: 10.244.0.0/24,192.168.1.0/24
            - name: OPENVPN_CONFIG
              value: Paris-Seine-tcp
            - name: OPENVPN_PROVIDER
              value: WINDSCRIBE
            - name: OPENVPN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: windscribe-credentials
                  key: username
            - name: OPENVPN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: windscribe-credentials
                  key: password
            - name: TRANSMISSION_RPC_WHITELIST
              value: 127.0.0.1,192.168.1.4,192.168.1.*
            - name: TRANSMISSION_RPC_WHITELIST_ENABLED
              value: 'true'
            - name: TRANSMISSION_RPC_USERNAME
              value: root
            - name: TRANSMISSION_RPC_PASSWORD
              value: <password>
            - name: TRANSMISSION_PEER_PORT
              value: '47444'
            - name: TRANSMISSION_RPC_AUTHENTICATION_REQUIRED
              value: 'true'
            - name: TRANSMISSION_DOWNLOAD_DIR
              value: /downloads
            - name: PUID
              value: '1000'
            - name: PGID
              value: '1000'
          resources: {}
          volumeMounts:
            - name: downloads
              mountPath: /data
              subPath: transmission
            - name: downloads
              mountPath: /downloads
          livenessProbe:
            httpGet:
              path: /
              port: 9091
              scheme: HTTP
            timeoutSeconds: 10
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /
              port: 9091
              scheme: HTTP
            timeoutSeconds: 10
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: None
      securityContext: {}
      schedulerName: default-scheduler
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 8.8.4.4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
```

### Current Behavior

Crash on boot after a few seconds with thus output:

```sh
Starting container with revision: 84941a9ea4663d8b2e1af3db1d50fe4f7fa8736e
Creating TUN device /dev/net/tun
mknod: /dev/net/tun: File exists
Using OpenVPN provider: WINDSCRIBE
Running with VPN_CONFIG_SOURCE auto
No bundled config script found for WINDSCRIBE. Defaulting to external config
Downloading configs from https://github.com/haugene/vpn-configs-contrib/archive/main.zip into /tmp/tmp.Y8Cgrhjify
Extracting configs to /tmp/tmp.0jkXThE8tz
Found configs for WINDSCRIBE in /tmp/tmp.0jkXThE8tz/vpn-configs-contrib-main/openvpn/windscribe, will replace current content in /etc/openvpn/windscribe
Cleanup: deleting /tmp/tmp.Y8Cgrhjify and /tmp/tmp.0jkXThE8tz
Starting OpenVPN using config Paris-Seine-tcp.ovpn
Modifying /etc/openvpn/windscribe/Paris-Seine-tcp.ovpn for best behaviour in this container
Modification: Point auth-user-pass option to the username/password file
Modification: Change ca certificate path
Modification: Change ping options
Modification: Update/set resolv-retry to 15 seconds
Modification: Change tls-crypt keyfile path
Modification: Set output verbosity to 3
Modification: Remap SIGUSR1 signal to SIGTERM, avoid OpenVPN restart loop
Setting OpenVPN credentials...
adding route to local network 10.244.0.0/24 via 169.254.1.1 dev eth0
adding route to local network 192.168.1.0/24 via 169.254.1.1 dev eth0
Sun Dec  4 08:13:00 2022 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Mar 22 2022
Sun Dec  4 08:13:00 2022 library versions: OpenSSL 1.1.1f  31 Mar 2020, LZO 2.10
Sun Dec  4 08:13:00 2022 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Sun Dec  4 08:13:00 2022 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
Sun Dec  4 08:13:00 2022 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
Sun Dec  4 08:13:00 2022 TCP/UDP: Preserving recently used remote address: [AF_INET]82.102.18.35:1194
Sun Dec  4 08:13:00 2022 Socket Buffers: R=[131072->131072] S=[16384->16384]
Sun Dec  4 08:13:00 2022 Attempting to establish TCP connection with [AF_INET]82.102.18.35:1194 [nonblock]
Sun Dec  4 08:13:01 2022 TCP connection established with [AF_INET]82.102.18.35:1194
Sun Dec  4 08:13:01 2022 TCP_CLIENT link local: (not bound)
Sun Dec  4 08:13:01 2022 TCP_CLIENT link remote: [AF_INET]82.102.18.35:1194
Sun Dec  4 08:13:01 2022 TLS: Initial packet from [AF_INET]82.102.18.35:1194, sid=f0357072 8dd6acdc
Sun Dec  4 08:13:01 2022 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Sun Dec  4 08:13:01 2022 VERIFY OK: depth=2, C=CA, ST=ON, L=Toronto, O=Windscribe Limited, OU=Systems, CN=Windscribe Node CA X1
Sun Dec  4 08:13:01 2022 VERIFY OK: depth=1, C=CA, ST=ON, L=Toronto, O=Windscribe Limited, OU=Systems, CN=Windscribe Node CA X2
Sun Dec  4 08:13:01 2022 VERIFY KU OK
Sun Dec  4 08:13:01 2022 Validating certificate extended key usage
Sun Dec  4 08:13:01 2022 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Sun Dec  4 08:13:01 2022 VERIFY EKU OK
Sun Dec  4 08:13:01 2022 VERIFY X509NAME OK: C=CA, ST=ON, L=Toronto, O=Windscribe Limited, OU=Systems, CN=cdg-103.windscribe.com
Sun Dec  4 08:13:01 2022 VERIFY OK: depth=0, C=CA, ST=ON, L=Toronto, O=Windscribe Limited, OU=Systems, CN=cdg-103.windscribe.com
Sun Dec  4 08:13:01 2022 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_AES_256_GCM_SHA384, 4096 bit RSA
Sun Dec  4 08:13:01 2022 [cdg-103.windscribe.com] Peer Connection Initiated with [AF_INET]82.102.18.35:1194
Sun Dec  4 08:13:02 2022 SENT CONTROL [cdg-103.windscribe.com]: 'PUSH_REQUEST' (status=1)
Sun Dec  4 08:13:02 2022 PUSH: Received control message: 'PUSH_REPLY,redirect-gateway def1,rcvbuf 0,sndbuf 0,route-gateway 10.114.192.1,topology subnet,ping 5,ping-restart 60,dhcp-option DNS 10.255.255.2,ifconfig 10.114.192.22 255.255.254.0,peer-id 0,cipher AES-256-GCM'
Sun Dec  4 08:13:02 2022 OPTIONS IMPORT: timers and/or timeouts modified
Sun Dec  4 08:13:02 2022 OPTIONS IMPORT: --sndbuf/--rcvbuf options modified
Sun Dec  4 08:13:02 2022 Socket Buffers: R=[131072->131072] S=[87040->87040]
Sun Dec  4 08:13:02 2022 OPTIONS IMPORT: --ifconfig/up options modified
Sun Dec  4 08:13:02 2022 OPTIONS IMPORT: route options modified
Sun Dec  4 08:13:02 2022 OPTIONS IMPORT: route-related options modified
Sun Dec  4 08:13:02 2022 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
Sun Dec  4 08:13:02 2022 OPTIONS IMPORT: peer-id set
Sun Dec  4 08:13:02 2022 OPTIONS IMPORT: adjusting link_mtu to 1626
Sun Dec  4 08:13:02 2022 OPTIONS IMPORT: data channel crypto options modified
Sun Dec  4 08:13:02 2022 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Sun Dec  4 08:13:02 2022 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Sun Dec  4 08:13:02 2022 ROUTE_GATEWAY 169.254.1.1
Sun Dec  4 08:13:02 2022 TUN/TAP device tun0 opened
Sun Dec  4 08:13:02 2022 TUN/TAP TX queue length set to 100
Sun Dec  4 08:13:02 2022 /sbin/ip link set dev tun0 up mtu 1500
Sun Dec  4 08:13:02 2022 /sbin/ip addr add dev tun0 10.114.192.22/23 broadcast 10.114.193.255
Sun Dec  4 08:13:02 2022 /etc/openvpn/tunnelUp.sh tun0 1500 1554 10.114.192.22 255.255.254.0 init
Up script executed with tun0 1500 1554 10.114.192.22 255.255.254.0 init
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.114.192.22
Updating Transmission settings.json with values from env variables
Using existing settings.json for Transmission /data/transmission-home/settings.json
Overriding bind-address-ipv4 because TRANSMISSION_BIND_ADDRESS_IPV4 is set to 10.114.192.22
Overriding download-dir because TRANSMISSION_DOWNLOAD_DIR is set to /downloads
Overriding incomplete-dir because TRANSMISSION_INCOMPLETE_DIR is set to /data/incomplete
Overriding peer-port because TRANSMISSION_PEER_PORT is set to 47444
Overriding rpc-authentication-required because TRANSMISSION_RPC_AUTHENTICATION_REQUIRED is set to true
Overriding rpc-password because TRANSMISSION_RPC_PASSWORD is set to [REDACTED]
Overriding rpc-port because TRANSMISSION_RPC_PORT is set to 9091
Overriding rpc-username because TRANSMISSION_RPC_USERNAME is set to root
Overriding rpc-whitelist because TRANSMISSION_RPC_WHITELIST is set to 127.0.0.1,192.168.1.4,192.168.1.*
Overriding rpc-whitelist-enabled because TRANSMISSION_RPC_WHITELIST_ENABLED is set to true
Overriding watch-dir because TRANSMISSION_WATCH_DIR is set to /data/watch
sed'ing True to true
Enforcing ownership on transmission config directories
Applying permissions to transmission config directories
Setting owner for transmission paths to 1000:1000
Setting permissions for download and incomplete directories
Mask: 002
Directories: 775
Files: 664
Setting permission for watch directory (775) and its files (664)

-------------------------------------
Transmission will run as
-------------------------------------
User name:   abc
User uid:    1000
User gid:    1000
-------------------------------------

STARTING TRANSMISSION
Transmission startup script complete.
Sun Dec  4 08:13:03 2022 /sbin/ip route add 82.102.18.35/32 via 169.254.1.1
Sun Dec  4 08:13:03 2022 /sbin/ip route add 0.0.0.0/1 via 10.114.192.1
Sun Dec  4 08:13:03 2022 /sbin/ip route add 128.0.0.0/1 via 10.114.192.1
Sun Dec  4 08:13:03 2022 Initialization Sequence Completed
Sun Dec  4 08:15:28 2022 event_wait : Interrupted system call (code=4)
Sun Dec  4 08:15:28 2022 /etc/openvpn/tunnelDown.sh tun0 1500 1554 10.114.192.22 255.255.254.0 init
resolv.conf was restored
Sending kill signal to transmission-daemon
Waiting 5s for transmission-daemon to die
Successfuly closed transmission-daemon
Sun Dec  4 08:15:32 2022 /sbin/ip route del 82.102.18.35/32
Sun Dec  4 08:15:32 2022 /sbin/ip route del 0.0.0.0/1
Sun Dec  4 08:15:32 2022 /sbin/ip route del 128.0.0.0/1
Sun Dec  4 08:15:32 2022 Closing TUN/TAP interface
Sun Dec  4 08:15:32 2022 /sbin/ip addr del dev tun0 10.114.192.22/23
Sun Dec  4 08:15:32 2022 SIGTERM[hard,] received, process exiting

```

### Expected Behavior

startup with no problem

### How have you tried to solve the problem?

changing create_tun_device config

### Log output

check above

### HW/SW Environment

```markdown
- OS: kubernetes v1.24
```
