### ISSUE TITLE
Containers using the VPN Network, Resulting in IP Leaks

### ISSUE THREAD

**Issue by SachaTe** [haugene/docker-transmission-openvpn#2524]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [X] I have tried using dev branch

### Current Behavior

I am trying to configure other docker containers (e.g. [qbittorrent](https://hub.docker.com/r/linuxserver/qbittorrent) docker image) to use the VPN, as described [in this doc ](https://haugene.github.io/docker-transmission-openvpn/tips-tricks/#let_other_containers_use_the_vpn). However, when I validate the IP usage using a tool like [torguard torrent VPN check](https://torguard.net/checkmytorrentipaddress.php?hash=f1f5bda133bdbb4743773cc8548cbaee1fbff88a), I see that that both my regular IP and VPN IP is being exposed through the other docker.

I have followed multiple online instructions and the issue never goes away.

### Docker compose YML file

```
version: '3.3'
services:
    transmission-openvpn:
        cap_add:
          - NET_ADMIN
        volumes:
          - 'E:\Downloads\:/downloads'
          - 'C:\Backups\Docker\transmission\:/config'
        environment:
          - PUID=1000
          - PGID=1000
          - OPENVPN_PROVIDER=NORDVPN
          - OPENVPN_USERNAME=XYZ
          - OPENVPN_PASSWORD=XYZ
          - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
          - LOCAL_NETWORK=192.168.0.0/24
          - NORDVPN_PROTOCOL=TCP
          - NORDVPN_CATEGORY=P2P
          - NORDVPN_COUNTRY=CA
          - TRANSMISSION_RATIO_LIMIT=5
          - TRANSMISSION_RATIO_LIMIT_ENABLED=true
          - TRANSMISSION_IDLE_SEEDING_LIMIT=0
          - TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED=true
          - TRANSMISSION_DOWNLOAD_DIR=/downloads
        logging:
            driver: "json-file"
            options:
                max-size: 10m
        privileged: true
        ports:
          - '9091:9091'
          - '8080:8080' # Qbittorrent
          - '6881:6881' # Qbittorrent, TCP connection port
          - '6881:6881/udp' # Qbittorrent, UDP connection port
        restart: unless-stopped
        image: haugene/transmission-openvpn
    qbittorrent:
        privileged: true
        volumes:
            - 'C:\Backups\Docker\qbittorrent\config:/config'
            - 'E:\Downloads\:/downloads'
        environment:
            - PUID=1000
            - PGID=1000
            - WEBUI_PORT=8080
        restart: unless-stopped
        network_mode: "service:transmission-openvpn"
        depends_on:
            - "transmission-openvpn"
        image: 'lscr.io/linuxserver/qbittorrent:latest'
 ```

### Expected Behavior

My regular IP should not be visible in such situation as we specified to use the openvpn container network

### How have you tried to solve the problem?

1) Checked online instructions for network setup to validate
