### ISSUE TITLE
User labels set in the web gui not getting set in the daemon, and disappear after container restart

### ISSUE THREAD

**Issue by Stampede** [haugene/docker-transmission-openvpn#2543]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [ ] I have tried using dev branch

### Docker run config used

Compose file:
```
version: '3.3'
services:
    transmission-openvpn:
        cap_add:
            - NET_ADMIN
        volumes:
            - /mnt/XXXXX:/data
            - /home/XXXXXXX/transmission/config:/config
            #- '/your/storage/path/:/data'
            #- '/your/config/path/:/config'
            - './XXXXX:/config/openvpn-credentials.txt'
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        environment:
            - PUID=1000
            - PGID=1000
            - OPENVPN_PROVIDER=PIA
            - OPENVPN_CONFIG=XXXXXX
            - OPENVPN_USERNAME=**None**
            - OPENVPN_PASSWORD=**None**
            - LOCAL_NETWORK=XXXXXX
            - TRANSMISSION_WEB_UI=transmission-web-control
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '9091:9091'
        image: haugene/transmission-openvpn
```

### Current Behavior

In WebUI:
Click the gear/settings at the top --> "More" tab --> User Labels to "On"
Now click "Labels" Tab --> "Add" --> Create a label and enter description
Save config and back to main webUI

Right click a torrent --> "Set user labels" and apply a label

after a few seconds, the applied label show up in the web GUI.
So far, so good.

Now I enter a shell in the docker container and the "Labels" field is still blank:
`# transmission-remote -t 9 --info`
```
NAME
  Id: 9
  Name: XXXXXXX
  Hash: XXXXXXX
  Magnet: XXXXXXX
  Labels: 

TRANSFER
  State: Idle
...
```
Also, if I shut down the docker container the next time I start it, it knows nothing about my labels, not even in the webGUI.

### Expected Behavior

* Label shows up in the "Labels" field with `# transmission-remote -t 9 --info`
* Label to persist in web gui between restarts

### How have you tried to solve the problem?

Read documentations and searching for issues / discussions on this github

### Log output

I notice after I try to apply a user label to a torrent, I get these log errors. Not sure if related, or a coincidence.
```
[2023-03-04 13:52:47.799] Couldn't connect socket 25 to 2a01:e0a:41d:77b0::1, port 31992 (errno 99 - Cannot assign requested address) (net.c:339)
[2023-03-04 13:52:57.805] Couldn't connect socket 33 to 2001:470:26:7c:b26e:bfff:fe1d:e19b, port 48995 (errno 99 - Cannot assign requested address) (net.c:339)
[2023-03-04 13:53:04.807] Couldn't connect socket 34 to 2a01:e0a:bab:7650::1, port 17049 (errno 99 - Cannot assign requested address) (net.c:339)
```

### HW/SW Environment

```markdown
- OS: Debian Bullseye
- Docker version 23.0.1, build a5ee5b1
```
