### ISSUE TITLE
Transmission doesn't care about custom download dir

### ISSUE THREAD

**Issue by m0n0pr1x** [haugene/docker-transmission-openvpn#2548]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [ ] I have tried using dev branch

### Docker run config used

 ```
 torrent:
    container_name: torrent
    image: haugene/transmission-openvpn
    cap_add:
      - NET_ADMIN
    volumes:
      - /mnt/d500/mediaserver/torrents/:/data/
      - ./torrent-data/seedbox/config/:/config/
    environment:
      - OPENVPN_PROVIDER=
      - OPENVPN_CONFIG=
      - OPENVPN_USERNAME=
      - OPENVPN_PASSWORD=
      - LOG_TO_STDOUT=true
      - LOCAL_NETWORK=
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60 --pull-filter ignore ping
      - ENABLE_UFW=true
      - UFW_EXTRA_PORTS=
      - UFW_ALLOW_GW_NET=true
      - PUID=1000
      - PGID=1000

    logging:
      driver: json-file
      options:
        max-size: 10M
    ports:
      - '9091:9091'
    restart: unless-stopped
    networks:
      torrent_network:
        ipv4_address: 172.20.3.10

```

### Current Behavior

Every new finished torrents get moved from /data/incompleted to /downloads/torrents/

### Expected Behavior

files be moved to /data/completed as specified in the settings.json

### How have you tried to solve the problem?

1) Its not a permission issue
2) Transmission can move the finished torrent to /data/complete if done manually, but wont default to it
3) changed the default download location in transmission web UI, no effect
4) I solved the problem by mounting the /downloads/torrents volume
so the volumes tab look like this now
volumes:
      - /mnt/d500/mediaserver/torrents/:/data/
      - /mnt/d500/mediaserver/torrents/:/downloads/torrents
      - ./torrent-data/seedbox/config/:/config/

### Log output

There is a failure log if /downloads/torrents is not created when transmission tries to move files from incomplete but otherwise no errors when done manually for /data/completed

### HW/SW Environment

```markdown
Not related
```
