### ISSUE TITLE
Can't change settings

### ISSUE THREAD

**Issue by Uzurka** [haugene/docker-transmission-openvpn#2629]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [ ] I have tried using dev branch

### Docker run config used

```
  - name: seedbox
    image: haugene/transmission-openvpn
    restart_policy: unless-stopped
    capabilities:
      - net_admin
    ports:
      - 9091:9091
    mounts:
      - source: /mnt/md1/Transmission
        target: /data
        type: bind
    env:
      OPENVPN_PROVIDER: PIA
      OPENVPN_CONFIG: de_frankfurt
      OPENVPN_USERNAME: p9939088
      OPENVPN_PASSWORD: '{{ transmission_openvpn_password }}'
      LOCAL_NETWORK: 192.168.1.0/24
      TRANSMISSION_WEB_UI: flood-for-transmission
      PUID: '33'
      GUID: '33'
      TRANSMISSION_DOWNLOAD_DIR: /data/Downloads
      TRANSMISSION_RPC_AUTHENTICATION_REQUIRED: 'false'
      TRANSMISSION_RPC_USERNAME: Transmission
      TRANSMISSION_RPC_PASSWORD: '{{ transmission_rpc_password}}'
      TRANSMISSION_WATCH_DIR: /data/Torrents
    labels:
      com.centurylinklabs.watchtower.enable: 'true'
```

### Current Behavior

Using the WebUI (Flood), or transmission remote GUI, i can't change settings.
I can access the settings and edit fields, check or uncheck cases, but those aren't applied and if i go back to settings, my changes are reverted.
I also can see some weird logs : 

```
Setting owner for transmission paths to 33:
Setting permissions for download and incomplete directories
/etc/transmission/userSetup.sh: line 56: "002": syntax error: operand expected (error token is ""002"")
/etc/transmission/userSetup.sh: line 57: "002": syntax error: operand expected (error token is ""002"")
      
0
Directories: 
Files: 
chmod: invalid mode: ''
Try 'chmod --help' for more information.
chmod: invalid mode: ''
Try 'chmod --help' for more information.
chmod: invalid mode: ''
Try 'chmod --help' for more information.
Setting permission for watch directory (775) and its files (664)
```

### Expected Behavior

Changes made in settings are applied

### How have you tried to solve the problem?

Edit permissions of my transmission-home folder, restart the container and recreate it

### Log output

```
Enforcing ownership on transmission directories
Applying permissions to transmission directories
Setting owner for transmission paths to 33:
Setting permissions for download and incomplete directories
/etc/transmission/userSetup.sh: line 56: "002": syntax error: operand expected (error token is ""002"")
/etc/transmission/userSetup.sh: line 57: "002": syntax error: operand expected (error token is ""002"")
      
0
Directories: 
Files: 
chmod: invalid mode: ''
Try 'chmod --help' for more information.
chmod: invalid mode: ''
Try 'chmod --help' for more information.
chmod: invalid mode: ''
Try 'chmod --help' for more information.
Setting permission for watch directory (775) and its files (664)
-------------------------------------
Transmission will run as
-------------------------------------
User name:   abc
User uid:    33
User gid:    33
-------------------------------------
Updating Transmission settings.json with values from env variables
Attempting to use existing settings.json for Transmission
Successfully used existing settings.json /data/transmission-home/settings.json
Overriding bind-address-ipv4 because TRANSMISSION_BIND_ADDRESS_IPV4 is set to 10.9.112.136
Overriding download-dir because TRANSMISSION_DOWNLOAD_DIR is set to /data/Downloads
Overriding incomplete-dir because TRANSMISSION_INCOMPLETE_DIR is set to /data/incomplete
Overriding rpc-authentication-required because TRANSMISSION_RPC_AUTHENTICATION_REQUIRED is set to false
Overriding rpc-password because TRANSMISSION_RPC_PASSWORD is set to [REDACTED]
Overriding rpc-port because TRANSMISSION_RPC_PORT is set to 9091
Overriding rpc-username because TRANSMISSION_RPC_USERNAME is set to Transmission
Overriding watch-dir because TRANSMISSION_WATCH_DIR is set to /data/Torrents
sed'ing True to true
STARTING TRANSMISSION
Provider PIA has a script for automatic port forwarding. Will run it now.
If you want to disable this, set environment variable DISABLE_PORT_UPDATER=true
Transmission startup script complete.
2023-06-05 21:26:03 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
2023-06-05 21:26:03 Initialization Sequence Completed
Running functions for token based port fowarding
Reserved Port: 54451  Mon Jun  5 21:26:09 UTC 2023
transmission auth not required
waiting for transmission to become responsive
transmission became responsive
    26   100%   247.9 MB  Done         0.0     0.0   2.06  Idle         Simon Joyner - Songs from a Stolen Guitar - 2022 - Album - FLAC (16Bits)
Sum:            220.8 GB               0.0     0.0
setting transmission port to 54451
localhost:9091/transmission/rpc/ responded: success
Checking port...
Port is open: Yes
#######################
        SUCCESS        
#######################
Port: 54451
Expiration Mon Aug  7 09:26:09 UTC 2023
#######################
Entering infinite while loop
Every 15 minutes, check port status
Reserved Port: 54451  Mon Jun  5 21:41:20 UTC 2023
Reserved Port: 54451  Mon Jun  5 21:56:20 UTC 2023
Reserved Port: 54451  Mon Jun  5 22:11:20 UTC 2023
Reserved Port: 54451  Mon Jun  5 22:26:20 UTC 2023
Reserved Port: 54451  Mon Jun  5 22:41:20 UTC 2023
Reserved Port: 54451  Mon Jun  5 22:56:20 UTC 2023
Reserved Port: 54451  Mon Jun  5 23:11:21 UTC 2023
Reserved Port: 54451  Mon Jun  5 23:26:21 UTC 2023
Reserved Port: 54451  Mon Jun  5 23:41:21 UTC 2023
Reserved Port: 54451  Mon Jun  5 23:56:21 UTC 2023
Reserved Port: 54451  Tue Jun  6 00:11:21 UTC 2023
Reserved Port: 54451  Tue Jun  6 00:26:21 UTC 2023
Reserved Port: 54451  Tue Jun  6 00:41:22 UTC 2023
Reserved Port: 54451  Tue Jun  6 00:56:22 UTC 2023
Reserved Port: 54451  Tue Jun  6 01:11:22 UTC 2023
Reserved Port: 54451  Tue Jun  6 01:26:22 UTC 2023
Reserved Port: 54451  Tue Jun  6 01:41:22 UTC 2023
Reserved Port: 54451  Tue Jun  6 01:56:22 UTC 2023
Reserved Port: 54451  Tue Jun  6 02:11:23 UTC 2023
Reserved Port: 54451  Tue Jun  6 02:26:23 UTC 2023
Reserved Port: 54451  Tue Jun  6 02:41:23 UTC 2023
Reserved Port: 54451  Tue Jun  6 02:56:24 UTC 2023
Reserved Port: 54451  Tue Jun  6 03:11:24 UTC 2023
Reserved Port: 54451  Tue Jun  6 03:26:24 UTC 2023
Reserved Port: 54451  Tue Jun  6 03:41:24 UTC 2023
Reserved Port: 54451  Tue Jun  6 03:56:24 UTC 2023
Reserved Port: 54451  Tue Jun  6 04:11:24 UTC 2023
Reserved Port: 54451  Tue Jun  6 04:26:25 UTC 2023
Reserved Port: 54451  Tue Jun  6 04:41:25 UTC 2023
Reserved Port: 54451  Tue Jun  6 04:56:25 UTC 2023
Reserved Port: 54451  Tue Jun  6 05:11:25 UTC 2023
Reserved Port: 54451  Tue Jun  6 05:26:25 UTC 2023
Reserved Port: 54451  Tue Jun  6 05:41:25 UTC 2023
Reserved Port: 54451  Tue Jun  6 05:56:25 UTC 2023
Reserved Port: 54451  Tue Jun  6 06:11:26 UTC 2023
Reserved Port: 54451  Tue Jun  6 06:26:26 UTC 2023
Reserved Port: 54451  Tue Jun  6 06:41:26 UTC 2023
Reserved Port: 54451  Tue Jun  6 06:56:26 UTC 2023
```

### HW/SW Environment

```markdown
- OS: Debian 11
- Docker: Docker version 24.0.1, build 6802122
```
