### ISSUE TITLE
Download disappears after complete

### ISSUE THREAD

**Issue by madnlooney** [haugene/docker-transmission-openvpn#265]
When a torrent finishes it seems to disappear. I've turned all auto moving off. I see in the incomplete folder while it downloads but then when complete it doesn't do to the main folder. I'm running it on my Nas drive

**Comment by haugene** [comment]
Hi. Sounds weird. What is your settings for completed directory? Using default? What volume mounts have you set up? Might be that it is moved somewhere else inside the container that is not mounted to your nas, but that would mean that the download location is either configured wrong or it's manually set when adding a torrent.

**Comment by haugene** [comment]
As I wrote in the issue referenced over, what does it say in the web ui details view for the torrent? Should be able to see the location.

**Comment by madnlooney** [comment]
Hi this is the startup script

docker run --name transmission --cap-add=NET_ADMIN --device=/dev/net/tun -d \
              -v /media/3b2d3f9f-e9a1-404d-ac5e-4d016f049384/tor//:/data \
              -e TZ=Europe/London \
              --env-file /media/08952ca4-450d-46a5-9336-a12305192b97/backups/Docker/transmission/DockerEnv \
              -p 8086:9091 \
              haugene/transmission-openvpn

In the env file I have removed the # from filling lines including others. I see on the gui screen that the location is /data

TRANSMISSION_DOWNLOAD_DIR=/data 
TRANSMISSION_INCOMPLETE_DIR=/data/incomplete 

So I see the download in the incomplete folder when in process but not moved to the parent folder when completed

**Comment by haugene** [comment]
Ah, so it's on the base of the volume then. Don't see why it should be a problem necessarily, but try changing the TRANSMISSION_DOWNLOAD_DIR to /data/completed just in case. That is the default from the dockerfile.

**Comment by kronnnnnn** [comment]
Having the same issue here. Added the /data/ root before the incomplete and completed location and still the files move somewhere after. Also, the torrent never stops seeding, even if I set the ratio to something other than 0.  Tried searching the entire system for the files but they are nowhere. 

grep -Ril "file_name_here" /

docker run --name trans-vpn --cap-add=NET_ADMIN --device=/dev/net/tun -d \
              -v /opt/trans-vpn/:/config \
              -v /media/downloads/:/data \
              -v /etc/localtime:/etc/localtime:ro \
              -e LOCAL_NETWORK=192.168.1.0/24 \
              -e "TRANSMISSION_DOWNLOAD_LIMIT_ENABLED=0" \
              -e "TRANSMISSION_DOWNLOAD_DIR=/data/completed" \
              -e "TRANSMISSION_INCOMPLETE_DIR_ENABLED=true" \
              -e "TRANSMISSION_INCOMPLETE_DIR=/data/incomplete" \
              -e "OPENVPN_PROVIDER=TORGUARD" \
              -e "OPENVPN_CONFIG=xxxxxxxx" \
              -e "OPENVPN_USERNAME=xxxxxxxxxxxxxxxxx" \
              -e "OPENVPN_PASSWORD=xxxxxxxxxxxxxxx" \
              -p 9091:9091 \
              haugene/transmission-openvpn

**Comment by haugene** [comment]
Closing this as it's probably not a bug with the container, but an error introduced because of faulty volume mapping or as in the case of @kronnnnnn, that the path is set to something else when the torrent is added. There are so many using this container that I don't think there's actually something wrong with something this central to its functionality.

That being said. If you still have problems, you're welcome to re-open this isssue. Or probably a better place for this, try the chat on [gitter](https://gitter.im/docker-transmission-openvpn). If you do, please provide all the info you can from logs, run commands, torrent download dir etc etc.

**Comment by globalnomad** [comment]
Sorry to reopen this, but I just did a fresh install and my download has disappeared and I can't find it anywhere. Used to work perfectly.

These are the relevant settings in my yaml file:

```
version: '3.3'
services:
    transmission-openvpn:
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
            - SYS_RESOURCE
        volumes:
            - '/volume1/docker/transmission-openvpn/data/:/data'
            - '/volume1/docker/transmission-openvpn/data/:/config'
        environment:
            ...
            - TRANSMISSION_DOWNLOAD_DIR=/volume1/NAS/Temp
            - TRANSMISSION_INCOMPLETE_DIR=/volume1/NAS/Incomplete
        logging:
            driver: json-file
            options:
                max-size: 10m
```
I've checked all folders under /transmission-opnvpn/ as well as all folders under Temp and Incomplete using FileStation in Synology DSM. When I first started the torrent, I set the download location to Temp/Folder.

I've tried resetting the location and keeping move data checked to no avail (both as /volume1/NAS/Temp/Folder and /volume1/NAS/Temp/Folder/). I've run Verify Data on the torrent and it re-checks to 100% complete, so the data must be somewhere...
