### ISSUE TITLE
"you must define TUN/TAP device option" error

### ISSUE THREAD

**Issue by gtrhayrug** [haugene/docker-transmission-openvpn#2654]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [ ] I have tried using dev branch

### Docker run config used

Hi,

Moving from a old docker version, i've tried to modify my yaml file and i've removed almost error or warning (mainly by removing old transmission files, config).

My previous configuration works perfectly with Cyberghost as Custom provider (crt, key, ovpn etc files).

I've tried to change some options by adding CREATE_TUNE_DEVICE, HEALT_CHECK_CONTROL etc.

Any idea ?

My config file :
```
version: '3.3'
services:
  transmission:
    container_name: transmission
    image: haugene/transmission-openvpn
    cap_add:
      - NET_ADMIN
    restart: always
    ports:
      - "9091:9091"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    devices:
      - /dev/net/tun
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mymountfordownload/:/data
      - /mymoutforopenvpnfiles/:/etc/openvpn/custom

    environment:
      - CREATE_TUN_DEVICE=true
      - HEALTH_CHECK_HOST=www.google.com
      - PUID=1000
      - PGID=1000
      - LOCAL_NETWORK=192.168.2.0/24
      - OPENVPN_PROVIDER=custom
      - OPENVPN_USERNAME=xxxxxx
      - OPENVPN_PASSWORD=xxxxxxx

```
### Current Behavior

No access on Web UI.
Error on tun/tap definition, core dump nslookup

### Expected Behavior

Connection on VPN & Transmission loggin possible.
At this time, no web connection.

### How have you tried to solve the problem?

Working perfectly in V2.6 previously. 

### Log output

`Starting container with revision: 1103172c3288b7de681e2fb7f1378314f17f66cf
TRANSMISSION_HOME is currently set to: /config/transmission-home
/etc/openvpn/start.sh: line 51:    10 Aborted                 (core dumped) nslookup ${HEALTH_CHECK_HOST:-"google.com"} > /dev/null 2>&1
WARNING: initial DNS resolution test failed
Creating TUN device /dev/net/tun
Using OpenVPN provider: CUSTOM
Modifying /etc/openvpn/custom/default.ovpn for best behaviour in this container
Modification: Point auth-user-pass option to the username/password file
Modification: Change ca certificate path
Modification: Change ping options
Modification: Update/set resolv-retry to 15 seconds
Modification: Change tls-crypt keyfile path
Modification: Set output verbosity to 3
Modification: Remap SIGUSR1 signal to SIGTERM, avoid OpenVPN restart loop
Modification: Updating status for config failure detection
Setting OpenVPN credentials...
adding route to local network 192.168.2.0/24 via 172.26.0.1 dev eth0
2023-07-12 15:10:50 Cipher negotiation is disabled since neither P2MP client nor server mode is enabled
Options error: You must define TUN/TAP device (--dev)
Use --help for more information.`

### HW/SW Environment

```markdown
- OS: Debian10 + Docker 19.03.15 + Portainer 2.18.3
```
