### ISSUE TITLE
Privoxy fails to start due to duplicate listen address in config file

### ISSUE THREAD

**Issue by Mossop** [haugene/docker-transmission-openvpn#2692]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [X] I have tried using dev branch

### Docker run config used

`docker-compose.yml`:

```
  transmission:
    container_name: transmission
    image: haugene/transmission-openvpn:edge
    restart: always

    dns:
      - 1.1.1.1
      - 1.0.0.1

    networks:
      - services

    cap_add:
      - NET_ADMIN

    devices:
      - /dev/net/tun

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/transmission/:/config/transmission-home
      - /pool/media/:/pool/media

    environment:
      OPENVPN_PROVIDER: "PIA"
      OPENVPN_CONFIG: "uk_london"
      PIA_OPENVPN_CONFIG_BUNDLE: "openvpn-tcp"
      OPENVPN_USERNAME: "****"
      OPENVPN_PASSWORD: "****"
      ENABLE_UFW: "true"
      LOCAL_NETWORK: "10.10.0.0/16,172.16.0.0/12"
      PUID: "137"
      PGID: "151"
      TRANSMISSION_DOWNLOAD_DIR: "/pool/media/torrents/completed"
      TRANSMISSION_INCOMPLETE_DIR: "/pool/media/torrents/incomplete"
      TRANSMISSION_WATCH_DIR: "/pool/media/torrents/watch"
      TRANSMISSION_WEB_UI: flood-for-transmission
      WEBPROXY_ENABLED: "true"
      WEBPROXY_PORT: "8888"
```

### Current Behavior

Privoxy fails to start, logs the following error:
```
2023-08-30 11:15:52.884 7f5f921d0b80 Fatal error: can't bind to 10.10.12.131:8888: There may be another Privoxy or some other proxy running on port 8888
```

### Expected Behavior

Privoxy should start as normal.

### How have you tried to solve the problem?

Tried the edge tag. Looked at the privoxy config file and spotted the issue, see discussion below.

### Log output

```
2023-08-30 11:15:52.884 7f5f921d0b80 Fatal error: can't bind to 10.10.12.131:8888: There may be another Privoxy or some other proxy running on port 8888
```

### HW/SW Environment

```markdown
- OS: Linux
- Docker: version 24.0.5, build ced0996
```

### Anything else?

Appears to have been introduced by this change to the privoxy startup script in #2610.

The config file looks like this before the script runs:

```
listen-address  127.0.0.1:8118
listen-address  [::1]:8118
```

Before the change above the first sed script would replace the IPv4 listen address with the correct one and the second sed script would remove the IPv6 listen address. Now the first sed script replaces both the listen addresses and the second sed script does nothing. This tells privoxy to attempt to listen on the same address twice causing it to fail.
