### ISSUE TITLE
expressvpn connection

### ISSUE THREAD

**Issue by azchoi** [haugene/docker-transmission-openvpn#2709]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [ ] I have tried using dev branch

### Docker run config used

version: '3.3'
services:
    transmission-openvpn:
        restart: always
        cap_add:
            - NET_ADMIN
        volumes:
            - '/volume2/Transmission/:/data'
            - '/volume2/Transmission/:/config'
        environment:
            - OPENVPN_PROVIDER=EXPRESSVPN
            - OPENVPN_USERNAME=*******
            - OPENVPN_PASSWORD=*******
            - OPENVPN_CONFIG=*******
            - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
            - LOCAL_NETWORK=192.168.1.0/24
            - TZ=*******
            - HEALTH_CHECK_HOST=google.com
            - TRANSMISSION_WEB_UI=flood-for-transmission
            - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
            - TRANSMISSION_RPC_HOST_WHITELIST="127.0.0.1,192.168.1.*,172.17.0.*"
            - TRANSMISSION_RPC_HOST_WHITELIST_ENABLED=true
            - TRANSMISSION_RPC_PASSWORD=*******
            - TRANSMISSION_RPC_USERNAME=*******
            - TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=false
            - TRANSMISSION_WATCH_DIR_ENABLED=true
            - TRANSMISSION_WATCH_DIR=/data/torrentfile
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '9091:9091'
		dns:
			- 1.1.1.1
			- 1.0.0.1
	image: haugene/transmission-openvpn

### Current Behavior

Now I'm using expressVPN and Docker cannot start and restart continuously after v5.2.0 update.

### Expected Behavior

It seems docker cannot connect to vpn server.
Please see this log message.
"No bundled config script found for EXPRESSVPN."

### How have you tried to solve the problem?

I tried to chage "OPENVPN_CONFIG" location but failed.

### Log output

Please commit your changes or stash them before you merge.
Aborting
Updating ca833e094..45cc9b305
Starting container with revision: b33d0fe4c938259a0d4eb844e55468f387456121
TRANSMISSION_HOME is currently set to: /config/transmission-home
WARNING: Deprecated. Found old default transmission-home folder at /data/transmission-home, setting this as TRANSMISSION_HOME. This might break in future versions.
We will fallback to this directory as long as the folder exists. Please consider moving it to /config/transmission-home
Creating TUN device /dev/net/tun
Using OpenVPN provider: EXPRESSVPN
Running with VPN_CONFIG_SOURCE auto
No bundled config script found for EXPRESSVPN. Defaulting to external config
Will get configs from https://github.com/haugene/vpn-configs-contrib.git
Repository is already cloned, checking for update
error: Your local changes to the following files would be overwritten by merge:
	openvpn/nordvpn/configure-openvpn.sh
Please commit your changes or stash them before you merge.
Aborting
Updating ca833e094..45cc9b305

### HW/SW Environment

```markdown
- OS:synology dsm 7.2
- Docker: v5.2.0 (latest)
```

**Comment by petebanham** [comment]
I have the same issue in that since 5.2.0 my container will not start either but in my case it looks like it is DNS related (Happy to log a different issue if than better). I  am running Docker on a pi and the host and all other containers can still resolve DNS fine but since 5.2.0  get this error when transmission tries to start:

```
Starting container with revision: 5d6174c4b6ff4c5dcff115c01da336b39c14a28d
transmission     | TRANSMISSION_HOME is currently set to: /config/transmission-home
transmission     | /etc/openvpn/start.sh: line 51:    10 Aborted                 (core dumped) nslookup ${HEALTH_CHECK_HOST:-"google.com"} > /dev/null 2>&1
transmission     | WARNING: initial DNS resolution test failed
transmission     | Creating TUN device /dev/net/tun
transmission     | Using OpenVPN provider: PUREVPN
transmission     | Running with VPN_CONFIG_SOURCE auto
transmission     | No bundled config script found for PUREVPN. Defaulting to external config
transmission     | Will get configs from https://github.com/haugene/vpn-configs-contrib.git
transmission     | Repository is already cloned, checking for update
transmission     | fatal: unable to access 'https://github.com/haugene/vpn-configs-contrib.git/': Failed to resolve host 'github.com' with timeout after -9284778
```

This is my compose file, I have have tried with and without the specific DNS entries:

```
  transmission:
    container_name: transmission
    image: haugene/transmission-openvpn
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    ports:
      - '9091:9091'
    dns:
      - 1.1.1.1
      - 1.0.0.1
    environment:
#      DEBUG: 'true'
      TZ: 'Europe/London'
      OPENVPN_PROVIDER: PUREVPN
      OPENVPN_CONFIG: es2-ovpn
#      OPENVPN_CONFIG: ch2-ovpn-udp
      OPENVPN_USERNAME: purevpn*******
      OPENVPN_PASSWORD: ******
      DISABLE_PORT_UPDATER: 'true'
      WEBPROXY_ENABLED: 'false'
      TRANSMISSION_DOWNLOAD_DIR: /nas/complete/
      LOCAL_NETWORK: 192.168.5.0/24
#      DROP_DEFAULT_ROUTE: 'true'  #This command broke versions from 4.3
      TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED: 'false'
      OPENVPN_OPTS: --inactive 3600 --ping 10 --ping-exit 60
    volumes:
      - '/home/pi/nas/:/nas/'
      - '/home/pi/nas/trans/config:/config'
      - '/home/pi/nas/trans/data:/data' 
    cap_add:
      - NET_ADMIN
    logging:
      driver: json-file
      options:
        max-size: 10m
    restart: unless-stopped
```
