### ISSUE TITLE
Container keeps failing healthcheck (unhealthy)

### ISSUE THREAD

**Issue by jad222** [haugene/docker-transmission-openvpn#2758]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [ ] I have tried using dev branch

### Docker run config used

```
version: '3.3'
services:
    transmission-openvpn:
        container_name: TransmissionOVPN
        restart: always
        #disable ipv6
        sysctls:
            net.ipv6.conf.all.disable_ipv6: 0
        cap_add:
            - NET_ADMIN
        volumes:
            - /srv/dev-disk/Downloads:/data
            - /srv/dev-disk/Config/TransmissionOVPN:/config
            - /srv/dev-disk/Files:/etc/openvpn/custom
        environment:
            - TZ=TIMEZONE
            - OPENVPN_PROVIDER=custom
            - OPENVPN_CONFIG=default
            - OPENVPN_USERNAME=XXXXXX
            - OPENVPN_PASSWORD=XXXXXX
            - LOCAL_NETWORK=10.18.1.0/24,10.8.0.0/16
            - TRANSMISSION_RPC_USERNAME=user
            - TRANSMISSION_RPC_PASSWORD=xxxxxxxx
            - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '9091:9091'
        image: haugene/transmission-openvpn:latest
```

### Current Behavior

Container after starting and connecting to vpn it keeps failing the healthcheck and when i enter into container (shell) i try to ping and it tooks long time to retrieve the response

### Expected Behavior

ping will be fast like always before and container is healthy as always before

### How have you tried to solve the problem?

Tried PGID AND PUID-
Tried seccomp:unconfined-

### Log output

```
-------------------------------------
Transmission will run as
-------------------------------------
User name:   root
User uid:    0
User gid:    0
-------------------------------------
Updating Transmission settings.json with values from env variables
Attempting to use existing settings.json for Transmission
Successfully used existing settings.json /config/transmission-home/settings.json
Overriding bind-address-ipv4 because TRANSMISSION_BIND_ADDRESS_IPV4 is set to 10.251.24.170
Overriding download-dir because TRANSMISSION_DOWNLOAD_DIR is set to /data/completed
Overriding incomplete-dir because TRANSMISSION_INCOMPLETE_DIR is set to /data/incomplete
Overriding rpc-authentication-required because TRANSMISSION_RPC_AUTHENTICATION_REQUIRED is set to true
Overriding rpc-password because TRANSMISSION_RPC_PASSWORD is set to [REDACTED]
Overriding rpc-port because TRANSMISSION_RPC_PORT is set to 9091
Overriding rpc-username because TRANSMISSION_RPC_USERNAME is set to user
Overriding watch-dir because TRANSMISSION_WATCH_DIR is set to /data/watch
sed'ing True to true
STARTING TRANSMISSION
Transmission startup script complete.
2023-12-09 15:45:55 Initialization Sequence Completed
```

### HW/SW Environment

```markdown
- OS: (omv) Debian 6.1.38-4~bpo11+1 (2023-08-08) x86_64 GNU/Linux
- Docker: client: 24.0.7, server: 24.0.7
```
