### ISSUE TITLE
Container healthcheck fails for NordVPN

### ISSUE THREAD

**Issue by mightyguava** [haugene/docker-transmission-openvpn#2768]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [ ] I have tried using dev branch

### Docker run config used

```yaml
 transmission:
    container_name: transmission
    image: haugene/transmission-openvpn  
    cap_add:
      - NET_ADMIN
    volumes:
      - /volume2/services/transmission/config/transmission-home:/config/transmission-home
      - /volume2/services/transmission/data:/data
      - /volume1/media:/media
    environment:
      - PUID=1028
      - PGID=100
      - TZ=America/New_York
      - OPENVPN_USERNAME=<omitted>
      - OPENVPN_PASSWORD=<omitted>
      - OPENVPN_PROVIDER=NORDVPN
      - NORDVPN_COUNTRY=US
      - NORDVPN_CATEGORY=legacy_p2p
      - NORDVPN_PROTOCOL=udp
      - LOCAL_NETWORK=10.0.0.0/24
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - GLOBAL_APPLY_PERMISSIONS=true
      - TRANSMISSION_HOME=/config/transmission-home
      - TRANSMISSION_RPC_PORT=9091
      - TRANSMISSION_DOWNLOAD_DIR=/media/downloads/torrents
      - TRANSMISSION_INCOMPLETE_DIR=/media/downloads/torrents/incomplete
      - TRANSMISSION_WATCH_DIR=/data/watch
      - CREATE_TUN_DEVICE=true
      - DROP_DEFAULT_ROUTE=
      - WEBPROXY_ENABLED=false
      - WEBPROXY_PORT=8888
      - WEBPROXY_USERNAME=
      - WEBPROXY_PASSWORD=
      - LOG_TO_STDOUT=false
      - HEALTH_CHECK_HOST=google.com
    healthcheck:
      disable: true
    ports:
      - 9091:9091
    dns:
      - 8.8.8.8
      - 8.8.4.4
    logging:
        driver: "json-file"
        options:
            max-size: "50m"
    restart: unless-stopped
```

### Current Behavior

The healthcheck script is failing even though DNS can be resolved:

```
# /etc/scripts/healthcheck.sh
DNS resolution failed
```

Running the nslookup manually inside the container returns

```
/# nslookup google.com
Server:		103.86.96.100
Address:	103.86.96.100#53

Non-authoritative answer:
Name:	google.com
Address: 192.0.0.88
** server can't find google.com: NXDOMAIN

/# echo $?
1
```

I am able to, within the container, successfully `ping` and `curl` `google.com`

### Expected Behavior

The healthcheck script should succeed.

### How have you tried to solve the problem?

Looked at this post https://serverfault.com/questions/1121447/nslookup-finds-ip-address-but-still-claims-nxdomain.

Confirmed that `nslookup -q=A google.com` succeeds while `nslookup -q=AAAA google.com` fails. So I'm wondering if the healthcheck command can be modified to just check ipv4?

### Log output

Relevant logs pasted above

### HW/SW Environment

```markdown
- OS: Synology DSM 7
- Docker: 20.10.23
```
