### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by auanasgheps** [haugene/docker-transmission-openvpn#2780]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [ ] I have tried using dev branch

### Docker run config used

```yaml
version: "2"
services:
  transmission:
    image: haugene/transmission-openvpn
    container_name: transmission-vpn
    restart: unless-stopped
    cap_add:
        - NET_ADMIN
    logging:
        driver: json-file
        options:
            max-size: 10m  
    sysctls:
        - net.ipv6.conf.all.disable_ipv6=1
    volumes:
        - /srv/nvme/downloads/:/media
        - /srv/nvme/docker-apps/transmission/config:/config
        - /srv/nvme/docker-apps/transmission/openvpn/:/etc/openvpn/custom
        - /srv/nvme/docker-apps/transmission/config/scripts:/scripts
        - /etc/localtime:/etc/localtime:ro
    environment:
        - PUID=1001
        - PGID=100
        - LOCAL_NETWORK=192.168.0.0/24
        - TZ=Europe/Rome
        - GLOBAL_APPLY_PERMISSIONS=false
        - OPENVPN_PROVIDER=custom
        - OPENVPN_CONFIG=vpnconfig
        - OPENVPN_USERNAME=**None**
        - OPENVPN_PASSWORD=**None**
        - TRANSMISSION_WEB_UI=transmission-web-control
        - TRANSMISSION_DOWNLOAD_DIR="/media/torrent"
        - TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=false
        - TRANSMISSION_WATCH_DIR_ENABLED=false
        - TRANSMISSION_DOWNLOAD_QUEUE_SIZE=10
        - TRANSMISSION_PEER_LIMIT_PER_TORRENT=200
        - TRANSMISSION_RATIO_LIMIT=3
        - TRANSMISSION_RATIO_LIMIT_ENABLED=true
        - TRANSMISSION_INCOMPLETE_DIR_ENABLED=true
        - TRANSMISSION_INCOMPLETE_DIR="/media/torrent/_incomplete"
        - TRANSMISSION_SPEED_LIMIT_UP_ENABLED=false
        - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
        - TRANSMISSION_RPC_USERNAME=superusername
        - TRANSMISSION_RPC_PASSWORD=${RPC_PASSWORD}
    ports:  
        - 9091:9091
    networks:
        default:   
        
networks:
    default:
        external: 
            name: rete
           # Use flag external telling compose that network is already created and should be taken outside, otherwise it will be created on the fly with project prefix  
```

### Current Behavior

This container is using too much CPU compared to what it used to do.
Currently there's no torrent being actively downloaded or uploaded, so I would expect a very low CPU consumption.
To be clear I have few torrents in seeding state, but network activity is 0 because nobody is pulling them.
Here's the situation:
![immagine](https://github.com/haugene/docker-transmission-openvpn/assets/20586878/bb42f80f-ed5f-4584-ab76-c72ee7830a9a)

### Expected Behavior

Low CPU usage when there are no torrents actively transferred, as it used to be in the past. Around 5% or lower

### How have you tried to solve the problem?

- Checked VPN connection is fine
- Using the latest version
- Nothing strange in transmission.log 

### Log output

Every hour it prints this, I think it's normal:

2023-12-30 18:05:58 TLS: soft reset sec=3600/3600 bytes=316893946/-1 pkts=2499308/0

2023-12-30 18:05:58 VERIFY OK: depth=1, CN=TG-VPN-CA

2023-12-30 18:05:58 VERIFY KU OK

2023-12-30 18:05:58 Validating certificate extended key usage

2023-12-30 18:05:58 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication

2023-12-30 18:05:58 VERIFY EKU OK

2023-12-30 18:05:58 VERIFY OK: depth=0, CN=server

2023-12-30 18:05:58 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1582', remote='link-mtu 1569'

2023-12-30 18:05:58 WARNING: 'tun-mtu' is used inconsistently, local='tun-mtu 1532', remote='tun-mtu 1500'

2023-12-30 18:05:58 WARNING: 'comp-lzo' is present in local config but missing in remote config, local='comp-lzo'

2023-12-30 18:05:58 WARNING: 'auth' is used inconsistently, local='auth [null-digest]', remote='auth SHA256'

2023-12-30 18:05:58 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key

2023-12-30 18:05:58 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key

2023-12-30 18:05:58 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_AES_256_GCM_SHA384, peer certificate: 2048 bit RSA, signature: RSA-SHA256

### HW/SW Environment

```markdown
- OS: Debian 11
- Docker: 24.0.7
```

### Anything else?

An update: 
The CPU usage is not constant. The day after I opened this issue it was about 7-8%, with the same conditions (no torrent actively being downloaded or uploaded).
I would like to understand what Transmission is doing, but the logs don't say much.
