### ISSUE TITLE
Container seems to star fine, but cannot reach & killed after 5 mins

### ISSUE THREAD

**Issue by Wiirlak** [haugene/docker-transmission-openvpn#2793]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [ ] I have tried using dev branch

### Docker run config used

```yaml
  transmission-openvpn:
    image: haugene/transmission-openvpn
    restart: unless-stopped
    privileged: true
    networks:
      - traefik-public
    cap_add:
      - NET_ADMIN
    volumes:
      - /dev/net:/dev/net:z
      - ${ROOT}/download2:/data
      - ${ROOT_CONFIG}/transmission:/config
    ports:
      - 9091:9091
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - OPENVPN_PROVIDER=NORDVPN
      - OPENVPN_CONFIG=france
      - OPENVPN_USERNAME=secret
      - OPENVPN_PASSWORD=secret
      - NORDVPN_COUNTRY=FR
      - NORDVPN_CATEGORY=legacy_p2p
      - LOCAL_NETWORK=10.0.2.0/24 # I also tried 192.168.1.0/24
      - DEBUG=true
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.http.routers.transmission-secure.rule=Host(`transmission.x.com`)
        - traefik.http.routers.transmission-secure.entrypoints=https
        - traefik.http.routers.transmission-secure.tls=true
        - traefik.http.routers.transmission-secure.tls.certresolver=le
        - traefik.http.routers.transmission-secure.service=transmission
        - traefik.http.services.transmission.loadbalancer.server.port=9091
 ```

### Current Behavior

I run on Swarm, with a Traefik in front.
in docker, the line "Initialization Sequence Completed" is here for 5 minutes before the container get a Interrupted system call (code=4)
When trying to access 9091 through my local network, it doesn't work,. When i unplug the vpn, everything run fine. But i don't see any clear error in my logs ??
I don't have any idea of what am I doing wrong and why different solution don't work either, if you have any leads I can follow, I would be grateful

### Expected Behavior

To be able to at least access the UI

### How have you tried to solve the problem?

1) I pinged with "curl http://ifconfig.me/ip", it give my current IP (not vpn one)
2) tried with GLOBAL_APPLY_PERMISSIONS=false & DROP_DEFAULT_ROUTE=true
3) tried to go trought custom OVPN instead of NORDVPN, same result
4) tried multiple local network
5) tried to run openvpn --script-security 2 --route-up /etc/openvpn/tunnelUp.sh --route-pre-down /etc/openvpn/tunnelDown.sh --config ... -> no visible error, same as debug

### Log output

```
... (full logs in separate file)
2024-01-20 01:28:40 Initialization Sequence Completed
2024-01-20 01:31:31 event_wait : Interrupted system call (code=4)
2024-01-20 01:31:31 /etc/openvpn/tunnelDown.sh tun0 1500 1659 10.7.2.3 255.255.255.0 init
+ ls /etc/resolv.conf-tun0.sv
+ cp /etc/resolv.conf-tun0.sv /etc/resolv.conf
+ echo 'resolv.conf was restored'
+ /etc/transmission/stop.sh
resolv.conf was restored
Sending kill signal to transmission-daemon
+ [[ -x /scripts/transmission-pre-stop.sh ]]
+ echo 'Sending kill signal to transmission-daemon'
++ pidof transmission-daemon
�
0
+ kill 180
+ TRANSMISSION_TIMEOUT_SEC=5
++ seq 5
+ for i in $(seq "$TRANSMISSION_TIMEOUT_SEC")
�
1
++ pidof transmission-daemon
+ [[ -z '' ]]
+ break
++ pidof transmission-daemon
Successfuly closed transmission-daemon
+ [[ -z '' ]]
+ echo 'Successfuly closed transmission-daemon'
+ [[ -x /scripts/transmission-post-stop.sh ]]
+ [[ -f /opt/privoxy/stop.sh ]]
+ /opt/privoxy/stop.sh
+ [[ false = \t\r\u\e ]]
2024-01-20 01:31:32 net_route_v4_del: 31.187.69.45/32 via 172.18.0.1 dev [NULL] table 0 metric -1
2024-01-20 01:31:32 net_route_v4_del: 0.0.0.0/1 via 10.7.2.1 dev [NULL] table 0 metric -1
2024-01-20 01:31:32 net_route_v4_del: 128.0.0.0/1 via 10.7.2.1 dev [NULL] table 0 metric -1
2024-01-20 01:31:32 Closing TUN/TAP interface
2024-01-20 01:31:32 net_addr_v4_del: 10.7.2.3 dev tun0
2024-01-20 01:31:32 SIGTERM[hard,] received, process exiting
```

Log file:
[gtpe6erjyry5jfvg57qyy0uj1_logs.txt](https://github.com/haugene/docker-transmission-openvpn/files/14009515/gtpe6erjyry5jfvg57qyy0uj1_logs.txt)

### HW/SW Environment

```markdown
- OS: Ubuntu 22.04.3 LTS
- Docker: 24.0.7
- Swarm
```

### Anything else?

few years ago I implemented a deluge service going through a open-vpn client service, and everything worked well, until recently when everything crashed and docker wasn't usable on my machine.
I had to reinstall all, and it was not working anymore. I tried Gluetun, and this docker-transmission-openvpn, but none of them seems to work
