### ISSUE TITLE
healthcheck.sh reporting DNS failure if VPN service DNS incorrectly filters IPv6 addresses

### ISSUE THREAD

**Issue by apschultz** [haugene/docker-transmission-openvpn#2823]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [ ] I have tried using dev branch

### Docker run config used

docker-compose
```
version: "3.8"
services:
  transmission:
    image: haugene/transmission-openvpn:latest
    hostname: transmission
    container_name: transmission
    labels:
      - com.centurylinklabs.watchtower.enable=true
    privileged: true
    restart: always
    network_mode: "bridge"
    ports:
      - "9090:9090/tcp"
      - "9091:9091/tcp"
    dns:
      - 8.8.8.8 
      - 8.8.4.4
    volumes:
      - /volume2/docker/transmission:/config 
      - /volume1/Downloads:/data/Downloads
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - /volume2/docker/transmission/settings.env
```

Relevant env:
```
OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
CREATE_TUN_DEVICE=false
OPENVPN_PROVIDER=NORDVPN
NORDVPN_PROTOCOL=udp
NORDVPN_CATEGORY=legacy_p2p
NORDVPN_COUNTRY=................
LOCAL_NETWORK=172.16.0.0/12,192.168.0.0/16,10.1.0.0/24
```

### Current Behavior

docker reports the container as unhealthy. Upon entering the container, I found the reason is DNS is failing.

The root of the issue is the container replacing the configured resolv.conf with those learned from OpenVPN. NordVPN does not support IPv6 and has apparently implemented DNS filtering to return NXDOMAIN when AAAA records are requested. I'm aware I can disable the resolv.conf changes, however, NordVPN also appears to be doing a DNAT in their datacenters and absorbs other DNS traffic (or at least traffic from common DNS).

Add to this, nslookup always queries both A and AAAA even if no IPv6 addresses are present, the healthcheck script fails.

### Expected Behavior

healtcheck.sh should selectively use the -q option of nslookup based on configured protocols.

### How have you tried to solve the problem?

Ran and debugged healthcheck script from inside the container.

### Log output

```
root@transmission:/# nslookup google.com
Server:         103.86.96.100
Address:        103.86.96.100#53

Non-authoritative answer:
Name:   google.com
Address: 192.0.0.88
** server can't find google.com: NXDOMAIN

root@transmission:/# nslookup -q=a google.com
Server:         103.86.96.100
Address:        103.86.96.100#53

Non-authoritative answer:
Name:   google.com
Address: 192.0.0.88

root@transmission:/# nslookup -q=aaaa google.com
Server:         103.86.96.100
Address:        103.86.96.100#53

** server can't find google.com: NXDOMAIN

root@transmission:/# dig AAAA google.com

; <<>> DiG 9.18.18-0ubuntu0.22.04.1-Ubuntu <<>> AAAA google.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 29894
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 2

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;google.com.                    IN      AAAA

;; ADDITIONAL SECTION:
.                       60      IN      SOA     dns1.nordvpn.com. hostmaster.nordvpn.com. 1970010100 14400 3600 2419200 3600

;; Query time: 100 msec
;; SERVER: 103.86.96.100#53(103.86.96.100) (UDP)
;; WHEN: Wed Apr 03 15:05:55 EDT 2024
;; MSG SIZE  rcvd: 112

root@transmission:/# dig AAAA google.com @8.8.8.8

; <<>> DiG 9.18.18-0ubuntu0.22.04.1-Ubuntu <<>> AAAA google.com @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 55720
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 2

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;google.com.                    IN      AAAA

;; ADDITIONAL SECTION:
.                       60      IN      SOA     dns1.nordvpn.com. hostmaster.nordvpn.com. 1970010100 14400 3600 2419200 3600

;; Query time: 99 msec
;; SERVER: 8.8.8.8#53(8.8.8.8) (UDP)
;; WHEN: Wed Apr 03 15:06:02 EDT 2024
;; MSG SIZE  rcvd: 112

```

### HW/SW Environment

- OS: Synology DSM 7.2
- Docker: 20.10.23, build 876964a
