### ISSUE TITLE
ERROR: Cannot open TUN/TAP dev /dev/net/tun: Operation not permitted (errno=1)

### ISSUE THREAD

**Issue by DavidPeltz** [haugene/docker-transmission-openvpn#2900]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [X] I have tried using dev branch

### Docker run config used

  transmission:
    container_name: transmission
    cap_add:
      - NET_ADMIN
    volumes:
      - ${DOCKERDIR}/appdata/transmission:/config
      - ${DATADIR}/Downloads/completed:/data/
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - OPENVPN_PROVIDER=NORDVPN
      - OPENVPN_CONFIG=default
      - NORDVPN_COUNTRY=GB
      - NORDVPN_CATEGORY=P2P
      - NORDVPN_PROTOCOL=tcp
      - OPENVPN_USERNAME=${VPNUSER}
      - OPENVPN_PASSWORD=${VPNPASS}
      #      - NORDVPN_SERVER=uk2313.nordvpn.com
      - LOCAL_NETWORK=192.168.1.0/24
      - WEBPROXY_ENABLED=true
      - WEBPROXY_PORT=9999
    #      - TRANSMISSION_WEB_UI=combustion
    #      - TRANSMISSION_WEB_UI=kettu
    #      - TRANSMISSION_WEB_UI=transmission-web-control
    #      - TRANSMISSION_WEB_UI=flood-for-transmission
    #      - TRANSMISSION_WEB_UI=shift
      - HEALTH_CHECK_HOST=github.com
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - 9091:9091
    image: haugene/transmission-openvpn:latest
    restart: unless-stopped
    networks:
      - network1

### Current Behavior

Container up but VPN failing and so cannot even connect to container on the web interface

### Expected Behavior

Web interface works as VPN connects

### How have you tried to solve the problem?

rebooted server, portainer stack and removed and re-pulled container

### Log output

[_transmission_logs.txt](https://github.com/user-attachments/files/18048547/_transmission_logs.txt)

### HW/SW Environment

```markdown
- OS:Ubuntu 24.04
- Docker:Docker version 27.3.1, build ce12230
```

### Anything else?

nothing to add

**Comment by BarrRedKola** [comment]
you don't need the mapping inside the container if it is the same path, meaning
```
devices:
  - /dev/net/tun
```
is sufficient.

And it indeed solves the issue.

The main issue is probably related to an update of container.io [https://github.com/qdm12/gluetun/issues/2606](https://github.com/qdm12/gluetun/issues/2606)

**Comment by hanspetzer** [comment]
@BarrRedKola Thanks, worked for me.

If you use a systemctl service to start the container you need to add this line:
`--device /dev/net/tun \`

**Comment by silvanschermer** [comment]
> Add this to your compose file
> 
> ```
> devices:
>   - /dev/net/tun
> ```
> 
> And it indeed solves the issue.
> 
> The main issue is probably related to an update of container.io [qdm12/gluetun#2606](https://github.com/qdm12/gluetun/issues/2606)

This is only a fix for compose users. In docker swarm this won't work.

I locked the containerd version for as long as I have no real fix for this.

**Comment by DaemonDude23** [comment]
Thanks to the clues above, here's a workaround for a **Kubernetes** environment.
I'm using `k3s` and ran into this problem after upgrading the control plane to `1.31.3` and restarting the pod.

Modify the **Deployment** object to add:
- `volumes`
- `volumeMounts`
- `privileged: true`


 Here's a full example since indention gets out of hand with these:
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission-openvpn
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: transmission-openvpn
      app.kubernetes.io/instance: transmission-openvpn
  template:
    metadata:
      labels:
        app.kubernetes.io/name: transmission-openvpn
        app.kubernetes.io/instance: transmission-openvpn
    spec:
      hostNetwork: false
      serviceAccountName: transmission-openvpn
      dnsPolicy: ClusterFirst
      containers:
        - name: transmission-openvpn
          securityContext:
            privileged: true
          image: "haugene/transmission-openvpn:5.3.1"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /data
              name: data
            - mountPath: /dev/net/tun
              name: dev-net-tun
              readOnly: true
          envFrom:
            - configMapRef:
                name: transmission-openvpn
            - secretRef:
                name: transmission-openvpn
          ports:
            - name: http
              containerPort: 9091
              protocol: TCP
      volumes:
        - name: data
          hostPath:
            path: /data/transmission/
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
            type: CharDevice
```

**Comment by allywilson** [comment]
Dumb question maybe, how do I factor this in to a docker run command?

tried:
```

-e DEVICES=/dev/net/tun
--device /dev/net/tun
-e device=/dev/net/tun
-v device=/dev/net/tun
```

**Comment by hanspetzer** [comment]
> Dumb question maybe, how do I factor this in to a docker run command?
> 
> tried:
> 
> ```
> 
> -e DEVICES=/dev/net/tun
> --device /dev/net/tun
> -e device=/dev/net/tun
> -v device=/dev/net/tun
> ```

`--device=/dev/net/tun` should work


https://docs.docker.com/reference/cli/docker/container/run/#device

**Comment by demonbane** [comment]
> Add this to your compose file
> 
> ```
> devices:
>   - /dev/net/tun
> ```

I've added this but I continue to get:
> error gathering device information while adding custom device "/dev/net/tun": no such file or directory

Does the `/dev/net/tun` device need to be available on the host, because I'm not seeing it there?

**Comment by tessierp** [comment]
Same problem as everyone else.. still no solution

**Comment by iamzoltan** [comment]
`--device=/dev/net/tun` this worked for me

**Comment by SixteenOne** [comment]
I have been trying to fix this for the last few weeks and tried different things, but still get the TUN Error

I have it working on another machine that I set up ages ago, but I can't get it working on a new machine

Mapping the `/dev/net/tun` doesn't resolve the issue for me

## Fix that works for me :-)

Docker must have changed how you access certain things, so you now have to make the Container privileged in order to create a VPN Tunnel

So pop `privileged: true` in line with the `image` level and this will now work. I have got this working on Debian and Ubuntu VM's in Proxmox

```yaml
...
    ports:
      - '9091:9091'
      - '8118:8118'
    image: haugene/transmission-openvpn
    privileged: true
...
```

**Comment by davinkevin** [comment]
For my `k8s` configuration, I had to mount the `tun` device like mentioned above and I had to change this env variable to `false` instead of `true`: 

```
            - name: CREATE_TUN_DEVICE
              value: "false"
```

**Comment by davinkevin** [comment]
Still an issue; please unstale it 😇

**Comment by SirMartin** [comment]
``Hi, I am trying to make it work, but I got the operation not permitted error, I followed all the tips from this thread and the other one, and nothing changes.

I can create the container but it does not start and only have this on the logs.

```shell
Starting container with revision: fd609f2ace1970858d3c32fcbd6c271b3d274d39
TRANSMISSION_HOME is currently set to: /config/transmission-home
Creating TUN device /dev/net/tun
mknod: /dev/net/tun: Operation not permitted
```

Here is my docker compose file.

```
version: '3.3'
services:
    transmission-openvpn:
        cap_add:
            - NET_ADMIN
        devices:
          - /dev/net/tun
        volumes:
            - '/data/transmission-vpn/data/:/data'
            - '/data/transmission-vpn/config:/config'
        environment:
            - CREATE_TUN_DEVICE=true
            - OPENVPN_PROVIDER=NORDVPN
            - OPENVPN_CONFIG=france
            - OPENVPN_USERNAME=user
            - OPENVPN_PASSWORD=pass
            - LOCAL_NETWORK=192.168.1.0/24
            - "NORDVPN_COUNTRY=FR"
        logging:
            driver: json-file
            options:
                max-size: 10m
        privileged: true
        ports:
            - '9091:9091'
        image: haugene/transmission-openvpn
```

Any ideas?
