### ISSUE TITLE
Seeding at 0kb/s

### ISSUE THREAD

**Issue by zabernoki** [haugene/docker-transmission-openvpn#298]
First off, amazing build. Almost everything is running perfectly and that's all thanks to the contributors here.

I've gotten Transmission running great with my VPN (OVPN). Download speeds are good and everything seems to work there. Unfortunately, my upload isn't working at all. I've port forwarded from OVPN and I passed that value to Transmission via "TRANSMISSION_PEER_PORT=<PORT>" in my docker-compose file.

I'm not familiar with openVPN but it seems like maybe something there isn't allowing me to use the port for seeding. Is there a parameter or setting that I need to provide somewhere for that as well? 

Here's my current docker-compose setup if that helps to call out any issues.
```
transmission:
image: haugene/transmission-openvpn
    ports:
      - "9091:9091"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/messy/apps/transmission/data:/data
      - /media/external/downloads:/data/completed:rw
      - /media/external/downloads/_incomplete:/data/incomplete:rw
    devices:
      - "/dev/net/tun -d"
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    environment:
      - uid=1000
      - gid=1000
      - "OPENVPN_PROVIDER=OVPN"
      - "OPENVPN_CONFIG=Sweden"
      - "OPENVPN_USERNAME=USERNAME"
      - "OPENVPN_PASSWORD=PASSWORD"
      - "LOCAL_NETWORK=192.168.1.0/24"
      - "TRANSMISSION_PEER_PORT=62823"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: always
    privileged: true
    container_name: transmission
```
I know this was predominantly built for the PIA community, but hoping somebody can at least point me in the right direction. I've googled as much information as I could but I'm kind of at the end of my knowledge base so thank you in advance for any guidance!

**Comment by illegalprime** [comment]
I have the same issue with mine, I just get stuck at:
![spectacle h29946](https://user-images.githubusercontent.com/4401220/30384312-f55c958e-9871-11e7-8cdc-4244e8ca26a3.png)

**Comment by zabernoki** [comment]
@illegalprime It looks like you aren't even able to initialize the download. I'm getting really good download speeds and completions, but I can't seed to anyone. 

I don't have any great advice to solve your problem, but I will say that I moved to PIA instead of OVPN because it's better supported here. Didn't help with my upload but it has some nice features around randomizing ports automatically and things like that. If you're not using PIA I might give it a try to see if you can at least get your download going.

**Comment by illegalprime** [comment]
@zabernoki thanks for the help! I actually got it working and made a PR: #306

**Comment by zabernoki** [comment]
@illegalprime Oh awesome! Are you getting any seeding ratio as a bi-product or just able to download now?

**Comment by illegalprime** [comment]
@zabernoki My upload / download ratios are about even

**Comment by illegalprime** [comment]
@zabernoki you can use the `illegalprime/transmission-openvpn` image to test.

**Comment by zabernoki** [comment]
@illegalprime Oh wow, if this solves my issue I will be forever thankful. I'll give it a go tonight.

**Comment by illegalprime** [comment]
This is my `docker-compose.yaml`
```yaml
version: "3"
services:
    transmission:
        image: illegalprime/transmission-openvpn
        ports:
          - "9091:9091"
        volumes:
          - /etc/localtime:/etc/localtime:ro
          - /home/michael/Downloads/Transmission:/data
        devices:
          - "/dev/net/tun -d"
        cap_add:
          - NET_ADMIN
        environment:
          - uid=1000
          - gid=1000
          - "OPENVPN_PROVIDER=PIA"
          - "OPENVPN_CONFIG=Sweden"
          - "OPENVPN_USERNAME=<username>"
          - "OPENVPN_PASSWORD=<password>"
          - "TRANSMISSION_PEER_PORT=62823"
        dns:
          - 8.8.8.8
          - 8.8.4.4
        restart: always
        privileged: true
        container_name: transmission
```
