### ISSUE TITLE
Torrents are not persisted

### ISSUE THREAD

**Issue by epichub** [haugene/docker-transmission-openvpn#369]
Hi, 

I cannot seem to get this dockerimage to persist the torrents through reboots/docker image restarts.
I have the config set up to a volume that should contain the transmission config/peristant storage, but it does not seem to work. The mapped volume with the config directory does not change when I add torrents, the only files being written to recently is the *-credentials.txt files.. My environment is rancheros, with the following config:

```
rancher:
  services:
    transmission-openvpn:
      image:  haugene/transmission-openvpn
      labels:
        io.rancher.os.after: console, preload-user-images
        io.rancher.os.scope: system
      cap_add:
        - NET_ADMIN
      devices:
        - /dev/net/tun
      restart: always
      dns:
        - 8.8.8.8
        - 8.8.4.4
      labels:
        io.rancher.os.after: portainer
      ports:
        - "9091:9091"
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - /mnt/containerdata/TransmissionConfig:/config:rw
      environment:
        PGID: '1101'
        PUID: '1101'
        OPENVPN_PROVIDER: '<REDACTED>'
        OPENVPN_USERNAME: '<REDACTED>'
        OPENVPN_PASSWORD: '<REDACTED>'
        LOCAL_NETWORK: '<REDACTED>'
        TRANSMISSION_BLOCKLIST_ENABLED: 'true'
        TRANSMISSION_BLOCKLIST_URL: 'http://john.bitsurge.net/public/biglist.p2p.gz'
        TRANSMISSION_DOWNLOAD_DIR: '<REDACTED>'
        TRANSMISSION_DHT_ENABLED: 'true'
        TRANSMISSION_DOWNLOAD_QUEUE_ENABLED: 'false'
        TRANSMISSION_RENAME_PARTIAL_FILES: 'false'
        TRANSMISSION_ENCRYPTION: '1'
        TRANSMISSION_INCOMPLETE_DIR: '<REDACTED>'
        TRANSMISSION_RPC_AUTHENTICATION-REQUIRED: '<REDACTED>'
        TRANSMISSION_RPC_ENABLED: 'true'
        TRANSMISSION_RPC_PASSWORD: '<REDACTED>'
        TRANSMISSION_RPC_USERNAME: '<REDACTED>'
        TRANSMISSION_WATCH_DIR: '<REDACTED>'
        TRANSMISSION_WATCH_DIR_ENABLED: 'true'
        TRANSMISSION_UMASK: '2'
        TRANSMISSION_RATIO_LIMIT: '2'
        TRANSMISSION_PEER_LIMIT_GLOBAL: '1000000'
        TRANSMISSION_PEER_LIMIT_PER_TORRENT: '1000'
```
