### ISSUE TITLE
tty device error? Can't ask for 'Enter Auth Username:'.

### ISSUE THREAD

**Issue by SuperJakish** [haugene/docker-transmission-openvpn#497]
Your guides and the other issue resolutions have been awesome, but I'm now stuck. I'm running docker-compose on Windows 10 with Linux containers and I'm using ExpressVPN. Here are the transmission portions of the compose file:

```
version: '3'
services:
    transmission:
        container_name: transmission
        image: haugene/transmission-openvpn
        privileged: true
        #cap_add:
        #    - NET_ADMIN
        #devices:
        #    - /dev/net/tun
        restart: unless-stopped
        ports:
            - "9091:9091"
            - "8080:8080"
        dns:
            # Cloudfare
            - 1.1.1.1
            - 1.0.0.1
            # Google
            #- 8.8.8.8
            #- 8.8.4.4
        volumes:
            #- /etc/localtime:/etc/localtime:ro # A way to get the time zone in Linux or Mac
            - .\data:/data
            - .\vpn\config.ovpn:/etc/openvpn/custom/default.ovpn
        environment:
            - OPENVPN_PROVIDER=CUSTOM
            - OPENVPN_USERNAME=dummy
            - OPENVPN_PASSWORD=dummy
            - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
            - LOCAL_NETWORK=192.168.0.0/24
            - TZ=America/New_York
            - TRANSMISSION_RPC_HOST_WHITELIST=HOSTNAME
    
    transmission-proxy:
        container_name: transmission-proxy
        image: haugene/transmission-openvpn-proxy
        links:
            - transmission:transmission
        ports:
            - "8080:8080"
        #volumes:
            #- /etc/localtime:/etc/localtime:ro # A way to get the time zone in Linux or Mac
        environment:
            - TZ=America/New_York
```

And here is the output with the error I get:
```
transmission          | Using OpenVPN provider: CUSTOM
transmission          | No VPN configuration provided. Using default.
transmission          | Setting OPENVPN credentials...
transmission          | adding route to local network 192.168.0.0/24 via 172.18.0.1 dev eth0
transmission          | Wed May  2 15:35:47 2018 WARNING: --keysize is DEPRECATED and will be removed in OpenVPN 2.6
transmission          | Wed May  2 15:35:47 2018 OpenVPN 2.4.5 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Mar  1 2018
transmission          | Wed May  2 15:35:47 2018 library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08
transmission          | Wed May  2 15:35:47 2018 neither stdin nor stderr are a tty device and you have neither a controlling tty nor systemd - can't ask for 'Enter Auth Username:'.  If you used --daemon, you need to use --askpass to make passphrase-protected keys work, and you can not use --auth-nocache.
transmission          | Wed May  2 15:35:47 2018 Exiting due to fatal error
```

I know I'm missing a device call that was in the example compose file, so that may be my problem, but I'm new to this and am not sure what device that was supposed to be referencing so I could convert it over to my Windows equivalent.

Many thanks in advance for your time!
