### ISSUE TITLE
Support for docker secrets

### ISSUE THREAD

**Issue by NoMoreNicksLeft** [haugene/docker-transmission-openvpn#534]
In the latest version of docker, it has a facility for using "secrets", such that they don't have to be entered onto the command line or left in unencrypted files like  docker-compose.yml.

Can this image be modified to look for the openvpn password there?

I've found several solutions for this, but they all require doing up my own Dockerfile and messing with the entrypoint, something I don't feel comfortable doing.

**Comment by Carbohydron** [comment]
I'd love for this issue to be revisited. If I can move my credentials to a secrets file, then I could more easily share my docker-compose with others!

**Comment by Carbohydron** [comment]
Bump! I'm hoping that eventually this feature will be implemented.

**Comment by Carbohydron** [comment]
Bump! I'm still hoping for this feature

**Comment by pkishino** [comment]
feel free to create a PR, I had a quick look and there is a PR on jwilder/dockerize to support this but that project doesnt update much ...

**Comment by haugene** [comment]
Allright. So stale bot closed this one, but I had it in the back of my mind and wanted to have a look at it. It seems to me like this feature would make most sense in a Docker swarm setup, is that what you're running?

It does also work with docker-compose and I've tested the change I just committed ☝️ by using this compose file.
NOTE: I built the image locally and the feature is not yet a part of the official :dev tag image.
```
version: '3.8'
services:
  transmission-openvpn:
    image: haugene/transmission-openvpn:dev
    environment:
        - OPENVPN_PROVIDER=PIA
        - OPENVPN_CONFIG=Israel
        - LOCAL_NETWORK=192.168.0.0/16
    cap_add:
        - NET_ADMIN
    ports:
        - '9091:9091'
    secrets:
        - transmission-user-pass

secrets:
    transmission-user-pass:
        file: ./user-pass.txt
```

Would this be a good solution? I want your comments here. Because the user-pass.txt file that I'm referring to here is an unencrypted file. And to me there is no difference in this and just mounting the username and password file to `/config/openvpn-credentials.txt` which has been supported for a long time. Now you might not have known that, and that's OK. Just want to hear your thoughts. The added benefit of this approach is of course that we actually will support secrets in swarm mode.
The contents of the file is just two lines:
```
username
password
```
which is how OpenVPN reads credentials from a file.

As you can see in my commit I'm just copying the secret into the OpenVPN credentials file. The reason for this is that we've modified all the .ovpn files of the providers to point to this file. So changing the location and reading directly from secrets would be a larger change. Another question is if it matters, it will be mounted unencrypted into the container anyways.

There is also a new feature on the dev branch that lets you supply a URL directly to the .ovpn file and then the container will download it and modify it as needed. That script could directly reference the secret and we wouldn't have to copy it. But for the built in providers we would have to make another script to fix it.
