### ISSUE TITLE
Docker Restarting (Possibly a QNAP Bug)

### ISSUE THREAD

**Issue by kylecribbs** [haugene/docker-transmission-openvpn#564]
Is this container suppose to restart every 30 seconds? Not sure why it would, but as the container is up i can curl ifconfig.co and get a different IP than mine. Here is my docker compose let me know if you see anything wrong?

```
  transmission-pia:
    image: haugene/transmission-openvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: always
    logging:
      driver: json-file
      options: 
        max-size: "10m"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - /share/Container/transmission/data:/data
    environment:
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_CONFIG=CA Toronto,CA Montreal,CA Vancouver
      - OPENVPN_USERNAME=x
      - OPENVPN_PASSWORD=x
      - WEBPROXY_ENABLED=true
      - LOCAL_NETWORK=192.168.168.0/24
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60 --pull-filter ignore ping
```

Right after port is open: yes, it restarts 
```
STARTING TRANSMISSION
CONFIGURING PORT FORWARDING
Transmission startup script complete.
Wait for tunnel to be fully initialized and PIA is ready to give us a port
STARTING TINYPROXY
Setting tinyproxy port to 8888
Starting tinyproxy: tinyproxy.
Tinyproxy startup script complete.
Sat Jul 21 23:24:35 2018 Initialization Sequence Completed
Got new port 29309 from PIA
transmission auth not required
localhost:9091/transmission/rpc/ responded: "success"
Checking port...
Port is open: Yes
```
