### ISSUE TITLE
Permissions errors on NFS mount

### ISSUE THREAD

**Issue by Ralim** [haugene/docker-transmission-openvpn#601]
Hi,

I haven't used NFS much so i'm fairly sure the issue is related to the NFS setup, but hoping someone here has pointers...

Whenever I try to run the docker container with its `/data` partition located on an NFS mount files cannot be saved and show a permissions error. However the files are actually made but they are size 0.

Here is the docker-compose I'm using : 
```
R@S:~/dockerStuff$ cat docker-compose.yml
version: '2'

services:
 transmission:
  build:
     context: .
     dockerfile: Dockerfile.armhf
  image: haugene/rpi-transmission-openvpn
  cap_add:
    - NET_ADMIN
  devices:
    - "/dev/net/tun"
  restart: always
  ports:
    - "9091:9091"
    - "8888:8888"
  dns:
    - 8.8.8.8
    - 8.8.4.4
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /NAS/Torrents/:/data
  environment:
    - OPENVPN_PROVIDER=PIA
    - OPENVPN_USERNAME=p6162050
    - OPENVPN_PASSWORD=VdLrGa87CR
    - LOCAL_NETWORK=192.168.0.0/23
    - OPENVPN_CONFIG=Switzerland,France,Romania,Spain,Sweden
    - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
    - TRANSMISSION_WEB_UI=combustion
    - PUID=1000
    - PGID=1000
R@S:~/dockerStuff$
```

Here is `df-h`  and `/etc/fsab` : 
```
192.168.0.10:/mnt/Front4BayData/R/Torrents  4.5T  894G  3.6T  20% /NAS/Torrents

192.168.0.10:/mnt/Front4BayData/R/Torrents  /NAS/Torrents   nfs     rw      0       0

```

The mount is mounted with the owner UID/GID as 1000 (user R) which is why I tried adding this to the docker image.

Any help with permissions would be loved :)
