### ISSUE TITLE
Docker-compose proxy issues

### ISSUE THREAD

**Issue by ethanopp** [haugene/docker-transmission-openvpn#659]
QNAP TVS-473. These two containers work perfectly fine when I run them as individual docker create statements, however when I run with the following docker-compose, both containers run without errors however I cannot access the proxy from the browser on local machine:

```
  transmissionairvpn:
    image: haugene/transmission-openvpn
    container_name: transmission-airvpn
    restart: always
    privileged: true
    cap_add:
      - NET_ADMIN
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "9091:9091"
    env_file: 
      - /share/CACHEDEV1_DATA/Container/Transmission-AirVPN/DockerEnv
    volumes:
      - /share/CACHEDEV1_DATA/Library/Downloads:/data
      - /share/CACHEDEV1_DATA/Library:/library
      - /share/CACHEDEV1_DATA/Container/Transmission-AirVPN/config.ovpn:/etc/openvpn/custom/default.ovpn
      - /share/CACHEDEV1_DATA/Container/Transmission-AirVPN:/config
      - /etc/localtime:/etc/localtime:ro
  transmissionairvpnweb:
    image: haugene/transmission-openvpn-proxy
    container_name: transmission-airvpn-web
    restart: always
    depends_on:
      - transmissionairvpn
    links:
      - transmissionairvpn:transmission
    ports:
      - "8888:8000"
    environment:
      - PUID=1001
      - PGID=100

```
