### ISSUE TITLE
Wrong country for IPvanish and can't use custom

### ISSUE THREAD

**Issue by SyRaza** [haugene/docker-transmission-openvpn#660]
For whatever reason, when using the provided configs for IPvanish, at least the ones for Toronto, I'm getting the wrong IP address. 

I ran the torrent from checkmyip.torrentprivacy.com, and the ip addresses it is showing are in the Netherlands. 
As a test, I used the IPvanish program for windows, connecting to the same servers, and did the checkmyip torrent test, and the IP comes out as Toronto. 

I'm not sure what's going on. but perhaps the configs that come with the image are outdated.

I tried to use the CUSTOM setting, but I keep getting a "connection failed" error. I put both the ca file and the ovpn file I downloaded from IPvanish into one folder and edited the ovpn file to look for the ca file in that folder. Still getting that error.

I realise these are two different issues so if I have to create two different submissions, I will.

Here is my docker-compose when using the provided configs:

```
# Transmission with VPN – Bittorrent Downloader

  transmission-vpn:
    container_name: transmission-vpn
    hostname: transmission
    image: haugene/transmission-openvpn	
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: always
    ports:
    - "9091:9091"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/docker/transmission-vpn:/data
      - /opt/docker/shared:/shared
      - /mnt/storage/downloads:/data/watch
      - /mnt/storage/complete:/data/completed
      - /mnt/storage/incomplete:/data/incomplete
    environment:
      - OPENVPN_PROVIDER=IPVANISH
      - OPENVPN_USERNAME=[REDACTED]
      - OPENVPN_PASSWORD=[REDACTED]
      - OPENVPN_CONFIG="ipvanish-CA-Toronto-tor-a11.ovpn" 
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=192.168.1.0/24
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      - TRANSMISSION_RPC_HOST_WHITELIST="127.0.0.1,192.168.1.*"
      - TRANSMISSION_RPC_PASSWORD=[REDACTED]
      - TRANSMISSION_RPC_USERNAME=[REDACTED]
      - TRANSMISSION_UMASK=077
      - TRANSMISSION_RATIO_LIMIT=0.01
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
      - TRANSMISSION_ALT_SPEED_DOWN=2000
      - TRANSMISSION_ALT_SPEED_ENABLED=true
      - TRANSMISSION_ALT_SPEED_UP=15
      - TRANSMISSION_SPEED_LIMIT_DOWN=8000
      - TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED=true
      - TRANSMISSION_SPEED_LIMIT_UP=8000
      - TRANSMISSION_SPEED_LIMIT_UP_ENABLED=true
      - TRANSMISSION_INCOMPLETE_DIR=/downloads/incomplete
      - TRANSMISSION_INCOMPLETE_DIR_ENABLED=true
      - TRANSMISSION_WATCH_DIR=/downloads
      - TRANSMISSION_WATCH_DIR_ENABLED=true
      - TRANSMISSION_DOWNLOAD_DIR=/downloads/completed
```

Here is the ovpn

```
client
dev tun
proto udp
remote tor-a11.ipvanish.com 443
resolv-retry infinite
nobind
persist-key
persist-tun
persist-remote-ip
ca /opt/docker/ipvan/ca.ipvanish.com.crt
verify-x509-name tor-a05.ipvanish.com name
auth-user-pass /config/openvpn-credentials.txt
comp-lzo
verb 3
auth SHA256
cipher AES-256-CBC
keysize 256
tls-cipher TLS-DHE-RSA-WITH-AES-256-CBC-SHA:TLS-DHE-DSS-WITH-AES-256-CBC-SHA:TLS-RSA-WITH-AES-256-CBC-SHA
```

When using the files I downloaded from IPvanish, I add `- /opt/docker/ipvan/ipvanish-CA-Toronto-tor-a05.ovpn:/etc/openvpn/custom/default.ovpn` to the volumes section and change `- OPENVPN_PROVIDER=IPVANISH` to `- OPENVPN_PROVIDER=CUSTOM`

Any insight on how to proceed would be appreciated. Thank you.

**Comment by haugene** [comment]
A couple of quick comments. You're setting:
`OPENVPN_CONFIG="ipvanish-CA-Toronto-tor-a11.ovpn" `
But the container will automatically append .ovpn to the name, and I guess you will find "ipvanish-CA-Toronto-tor-a11.ovpn.ovpn not found" in the logs and then it defaults back to Netherlands.

That's one problem. The second is that I think your ENV variables are not optimal. There are default values, listed in the dockerfile: https://github.com/haugene/docker-transmission-openvpn/blob/master/Dockerfile

For example TRANSMISSION_WATCH_DIR_ENABLED=true is already the default.
Also, you're setting TRANSMISSION_WATCH_DIR=/downloads but you have no volume mount for /downloads.

Also you need to check with Docker documentation but you have mount points within mountpoints:
- /opt/docker/transmission-vpn:/data 
- /mnt/storage/downloads:/data/watch
- /mnt/storage/complete:/data/completed
- /mnt/storage/incomplete:/data/incomplete

Not sure how well that will play out.

**Comment by SyRaza** [comment]
Thanks haugene, I'll have a look at this further. I used the compose AtoMiC-ToolKit docker-compose file as the base for this. I'll have to tweak it more. 

Ty for pointing out that `.ovpn` automatically gets appended. I forgot about that. I'll report back in a few. Appreciate the quick response.

**Comment by SyRaza** [comment]
So here is the updated compose file. Still reverting back to Netherlands. Did I set the config filename correctly? 

As for the mount points, they work with my other containers, I'm not expecting to run into trouble, but I'll troubleshoot that if it comes down to it.

And lastly, if the `TRANSMISSION_WATCH_DIR_ENABLED=true` is already the default, is it ok for me to remove from the compose file? Asking because, as I said, I used the AtoMIC-ToolKit as a bases for this.

```
# Transmission with VPN – Bittorrent Downloader
  transmission-vpn:
    container_name: transmission-vpn
    hostname: transmission
    image: haugene/transmission-openvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: always
    ports:
    - "9091:9091"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/docker/transmission-vpn:/data
      - /opt/docker/shared:/shared
      - /mnt/storage/downloads:/data/watch
      - /mnt/storage/complete:/data/completed
      - /mnt/storage/incomplete:/data/incomplete
    environment:
      - OPENVPN_PROVIDER=IPVANISH
      - OPENVPN_USERNAME=[REDACTED]
      - OPENVPN_PASSWORD=[REDACTED]
      - OPENVPN_CONFIG="ipvanish-CA-Toronto-tor-a05"
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=192.168.1.0/24
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      - TRANSMISSION_RPC_HOST_WHITELIST="127.0.0.1,192.168.1.*"
      - TRANSMISSION_RPC_PASSWORD=[REDACTED]
      - TRANSMISSION_RPC_USERNAME=[REDACTED]
      - TRANSMISSION_UMASK=2
      - TRANSMISSION_RATIO_LIMIT=1
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
      - TRANSMISSION_ALT_SPEED_DOWN=2000
      - TRANSMISSION_ALT_SPEED_ENABLED=true
      - TRANSMISSION_ALT_SPEED_UP=15
      - TRANSMISSION_SPEED_LIMIT_DOWN=8000
      - TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED=true
      - TRANSMISSION_SPEED_LIMIT_UP=8000
      - TRANSMISSION_SPEED_LIMIT_UP_ENABLED=true
      - TRANSMISSION_INCOMPLETE_DIR=/data/incomplete
      - TRANSMISSION_INCOMPLETE_DIR_ENABLED=true
      - TRANSMISSION_WATCH_DIR=/data/watch
      - TRANSMISSION_WATCH_DIR_ENABLED=true
      - TRANSMISSION_DOWNLOAD_DIR=/data/completed
```
