### ISSUE TITLE
Tinyproxy was unable to connect to the remote web server

### ISSUE THREAD

**Issue by CoderKiwi** [haugene/docker-transmission-openvpn#661]
Hi,

I have some other containers' traffic forwarded through Transmission's tiny proxy. It was working perfectly for a long time up until this week when it suddenly seemed to have lost connection. 

The easiest logs to find are from Sonarr which says:

```
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">

<head>
<title>500 Unable to connect</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
</head>

<body>

<h1>Unable to connect</h1>

<p>Tinyproxy was unable to connect to the remote web server.</p>

<hr />

<p><em>Generated by <a href="https://banu.com/tinyproxy/">tinyproxy</a> version 1.8.3.</em></p>

</body>

</html>
```

Jackett and Radarr throw similar errors, so it looks like a transmission-openvpn error.

I can download a torrent within the Transmission container, proving that the container itself has a connection to the internet. 

Here's part of the docker-compose.yml:

```
services:
  transmission:
    image: haugene/transmission-openvpn:latest
    container_name: transmission
    privileged: false
    restart: always
    ports:
      - "38000:9091"
      - "8888:8888"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - ./transmission/:/data
      - ./transmission/expressvpn.ovpn:/etc/openvpn/custom/default.ovpn:ro
      - ./transmission/expressvpn_credentials.txt:/config/openvpn-credentials.txt:ro
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
      OPENVPN_CONFIG: default
      OPENVPN_PROVIDER: CUSTOM
      OPENVPN_USERNAME: its_reading_from_mounted_file_instead
      OPENVPN_PASSSWORD: its_reading_from_mounted_file_instead
      OPENVPN_OPTS: --inactive 3600 --ping 10 --ping-exit 60
      TRANSMISSION_ENCRYPTION: 1
      TRANSMISSION_BLOCKLIST_ENABLED: 0
      TRANSMISSION_BLOCKLIST_URL: "http://john.bitsurge.net/public/biglist.p2p.gz" 
      TRANSMISSION_RPC_WHITELIST: 127.0.0.1
      TRANSMISSION_RPC_WHITELIST_ENABLED: 0
      TRANSMISSION_DOWNLOAD_DIR: /data/complete
      TRANSMISSION_INCOMPLETE_DIR: /data/incomplete
      TRANSMISSION_RATIO_LIMIT: 0
      TRANSMISSION_RATIO_LIMIT_ENABLED: 0
      TRANSMISSION_RPC_ENABLED: 1
      TRANSMISSION_RPC_PORT: 9091
      TRANSMISSION_RPC_URL: /transmission/
      TRANSMISSION_RPC_USERNAME: ${HTTP_USERNAME}
      TRANSMISSION_RPC_PASSWORD: ${HTTP_PASSWORD}
      TRANSMISSION_RPC_AUTHENTICATION_REQUIRED: 1
      # TRANSMISSION_WEB_UI: combustion
      TRANSMISSION_TRASH_ORIGINAL_TORRENT_FILES: 1
      TRANSMISSION_DOWNLOAD_QUEUE_ENABLED: 1
      TRANSMISSION_DOWNLOAD_QUEUE_SIZE: 10
      TRANSMISSION_UPLOAD_LIMIT_ENABLED: 1
      TRANSMISSION_UPLOAD_LIMIT: 50 # kB/s
      WEBPROXY_PORT: 8888
      WEBPROXY_ENABLED: "true"
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=false"
      - "traefik.backend=transmission"
      - "traefik.frontend.rule=Host:domain.com"
      - "traefik.port=9091"
      - "traefik.docker.network=traefik_proxy"
```

I stopped and removed all containers, pulled new images, restarted the host machine, and re-up'd it and the proxy still doesn't work. 

Somewhat related to #495 but I don't have a `resolv.conf`.

Thanks!
