### ISSUE TITLE
Can't seem to set download queue to more than 5.

### ISSUE THREAD

**Issue by kiwijunglist** [haugene/docker-transmission-openvpn#700]
My transmission only wants to download 5 torrents at once, despite me setting
`- TRANSMISSION_DOWNLOAD_QUEUE_SIZE=10`
I would expect that line to mean that 10 torrents will be actively trying to download at once.

Here is the docker compose followed by the settings.json file inside the container.

**DOCKER COMPOSE:**
```
  transmission_vpn:
    container_name: transmission_vpn
    image: haugene/transmission-openvpn
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    dns:
      - 209.222.18.222
      - 209.222.18.218
    environment:
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_USERNAME=xxxxxxxxxxxxxx
      - OPENVPN_PASSWORD=xxxxxxxxxxxxxxxx
      - "OPENVPN_CONFIG=CA Montreal,CA Toronto,CA Vancouver"
      - LOCAL_NETWORK=192.168.1.0/24
      - TRANSMISSION_DOWNLOAD_DIR=/downloads
      - TRANSMISSION_INCOMPLETE_DIR=/downloads/incomplete
      - TRANSMISSION_WATCH_DIR=/downloads/watch
      - TRANSMISSION_RPC_USERNAME=xxxxxxxxxxxxxxxxxxx
      - "TRANSMISSION_RPC_PASSWORD=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - TRANSMISSION_IDLE_SEEDING_LIMIT=1
      - TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED=true
      - TRANSMISSION_RATIO_LIMIT=0
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
      - TRANSMISSION_DOWNLOAD_QUEUE_SIZE=10
      - TRANSMISSION_PEER_LIMIT_GLOBAL=300
      - TRANSMISSION_MAX_PEERS_GLOBAL=300
      - TRANSMISSION_PEER_LIMIT_PER_TORRENT=75
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    ports:
      - 9091:9091
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/transmission_vpn/vpn:/config
      - ${DOCKERCONFDIR}/transmission_vpn/transmission:/data/transmission-home
      - ${DOCKERSHAREDDIR}:/shared
      - ${DOWNLOADSDIR}:/downloads
```

**/var/lib/transmission-daemon/.config/transmission-daemon/settings.json**
```
# cat /var/lib/transmission-daemon/.config/transmission-daemon/settings.json
{
    "blocklist-enabled": 0,
    "download-dir": "\/var\/lib\/transmission-daemon\/downloads",
    "download-limit": 100,
    "download-limit-enabled": 0,
    "encryption": 1,
    "max-peers-global": 200,
    "peer-port": 51413,
    "pex-enabled": 1,
    "port-forwarding-enabled": 0,
    "rpc-authentication-required": 1,
    "rpc-password": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "rpc-port": 9091,
    "rpc-username": "xxxxxxxxxxxxxxxxxxxxxxx",
    "rpc-whitelist": "127.0.0.1",
    "upload-limit": 100,
    "upload-limit-enabled": 0
}
```

**/etc/transmission-daemon/settings.json**
```
# cat ./etc/transmission-daemon/settings.json
{
    "blocklist-enabled": 0,
    "download-dir": "\/var\/lib\/transmission-daemon\/downloads",
    "download-limit": 100,
    "download-limit-enabled": 0,
    "encryption": 1,
    "max-peers-global": 200,
    "peer-port": 51413,
    "pex-enabled": 1,
    "port-forwarding-enabled": 0,
    "rpc-authentication-required": 1,
    "rpc-password": "xxxxxxxxxxxxxxxx",
    "rpc-port": 9091,
    "rpc-username": "xxxxxxxxxxxxxxxxxxx",
    "rpc-whitelist": "127.0.0.1",
    "upload-limit": 100,
    "upload-limit-enabled": 0
}
```

**/data/transmission-home/settings.json**
```
# cat ./data/transmission-home/settings.json
{
    "alt-speed-down": 50,
    "alt-speed-enabled": false,
    "alt-speed-time-begin": 540,
    "alt-speed-time-day": 127,
    "alt-speed-time-enabled": false,
    "alt-speed-time-end": 1020,
    "alt-speed-up": 50,
    "bind-address-ipv4": "xxxxxxxxxxxx",
    "bind-address-ipv6": "::",
    "blocklist-enabled": false,
    "blocklist-url": "http://www.example.com/blocklist",
    "cache-size-mb": 4,
    "dht-enabled": true,
    "download-dir": "/downloads",
    "download-limit": 100,
    "download-limit-enabled": 0,
    "download-queue-enabled": true,
    "download-queue-size": 10,
    "encryption": 1,
    "idle-seeding-limit": 1,
    "idle-seeding-limit-enabled": true,
    "incomplete-dir": "/downloads/incomplete",
    "incomplete-dir-enabled": true,
    "lpd-enabled": false,
    "max-peers-global": 300,
    "message-level": 2,
    "peer-congestion-algorithm": "",
    "peer-id-ttl-hours": 6,
    "peer-limit-global": 300,
    "peer-limit-per-torrent": 75,
    "peer-port": 51413,
    "peer-port-random-high": 65535,
    "peer-port-random-low": 49152,
    "peer-port-random-on-start": false,
    "peer-socket-tos": "default",
    "pex-enabled": true,
    "port-forwarding-enabled": false,
    "preallocation": 1,
    "prefetch-enabled": true,
    "queue-stalled-enabled": true,
    "queue-stalled-minutes": 30,
    "ratio-limit": 0,
    "ratio-limit-enabled": true,
    "rename-partial-files": true,
    "rpc-authentication-required": false,
    "rpc-bind-address": "0.0.0.0",
    "rpc-enabled": true,
    "rpc-host-whitelist": "",
    "rpc-host-whitelist-enabled": false,
    "rpc-password": "xxxxxxxxxxxxxxxxxxxxxx",
    "rpc-port": 9091,
    "rpc-url": "/transmission/",
    "rpc-username": "xxxxxxxxxxxxxxxxxxxxxx",
    "rpc-whitelist": "127.0.0.1",
    "rpc-whitelist-enabled": false,
    "scrape-paused-torrents-enabled": true,
    "script-torrent-done-enabled": false,
    "script-torrent-done-filename": "",
    "seed-queue-enabled": false,
    "seed-queue-size": 10,
    "speed-limit-down": 100,
    "speed-limit-down-enabled": false,
    "speed-limit-up": 100,
    "speed-limit-up-enabled": false,
    "start-added-torrents": true,
    "trash-original-torrent-files": false,
    "umask": 2,
    "upload-slots-per-torrent": 14,
    "utp-enabled": true,
    "watch-dir": "/downloads/watch",
    "watch-dir-enabled": true,
    "watch-dir-force-generic": false
}
```
