### ISSUE TITLE
Inactivity timeout while connecting to Anonine

### ISSUE THREAD

**Issue by b0red** [haugene/docker-transmission-openvpn#729]
Since a few days back (2 or 3?) I've had connection refused errors when trying to connect to the transmission-gui. I haven't change anything on my end. The webgui doesn't work either. Any clues?

this is the .yml file:
```
`  #Transmission + VPN                                           --------------------- Transmission VPN
  transmission-vpn:
    container_name: transmission-vpn
    image: haugene/transmission-openvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: always
    ports:
      - "9091:9091"
      - "51414:51414"
    networks:
      - traefik_proxy
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/docker/transmission-vpn:/data
      - ${USERDIR}/docker/transmission-vpn:/config
      - ${USERDIR}/docker/shared:/shared
      - /media/all/Downloads/watched:/data/watched
      - /media/all/Downloads/complete:/data/complete
      - /media/all/Downloads/incomplete:/data/incomplete
    environment:
      - TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=false
      - TRANSMISSION_INCOMPLETE_DIR=/data/incomplete
      - TRANSMISSION_INCOMPLETE_DIR_ENABLED=true
      - TRANSMISSION_WATCH_DIR=/data/watched
      - TRANSMISSION_WATCH_DIR_ENABLED=true
      - TRANSMISSION_DOWNLOAD_DIR=/data/complete
      - OPENVPN_PROVIDER=ANONINE
      - OPENVPN_USERNAME=xxx
      - OPENVPN_PASSWORD=xxx
        #  - OPENVPN_CONFIG="Sweden" 
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=192.168.1.0/24
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      - TRANSMISSION_RPC_HOST_WHITELIST="127.0.0.1,192.168.*.*,192.168.1.0/24,192.168.1.1/24"
      - TRANSMISSION_RPC_PASSWORD=[redacted]
      - TRANSMISSION_RPC_USERNAME=transmission
      - TRANSMISSION_UMASK=002
      - TRANSMISSION_DOWNLOAD_QUEUE_SIZE=20
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - TRANSMISSION_BLOCKLIST_URL=http://john.bitsurge.net/public/biglist.p2p.gz
      - TRANSMISSION_DOWNLOAD_QUE_SIZE=20`
```
Log from transmission-vpn:
```
Setting OPENVPN credentials...,
adding route to local network 192.168.1.0/24 via 172.19.0.1 dev eth0,
Thu Mar  7 11:28:11 2019 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 19 2019,
Thu Mar  7 11:28:11 2019 library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08,
Thu Mar  7 11:28:11 2019 WARNING: --ns-cert-type is DEPRECATED.  Use --remote-cert-tls instead.,
Thu Mar  7 11:28:11 2019 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts,
Thu Mar  7 11:28:11 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]103.194.171.157:443,
Thu Mar  7 11:28:11 2019 UDP link local: (not bound),
Thu Mar  7 11:28:11 2019 UDP link remote: [AF_INET]103.194.171.157:443,
Thu Mar  7 11:29:11 2019 [UNDEF] Inactivity timeout (--ping-exit), exiting,
Thu Mar  7 11:29:11 2019 SIGTERM[soft,ping-exit] received, process exiting,
Using OpenVPN provider: ANONINE,
No VPN configuration provided. Using default.,
Setting OPENVPN credentials...,
adding route to local network 192.168.1.0/24 via 172.19.0.1 dev eth0,
Thu Mar  7 11:29:15 2019 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 19 2019,
Thu Mar  7 11:29:15 2019 library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08,
Thu Mar  7 11:29:15 2019 WARNING: --ns-cert-type is DEPRECATED.  Use --remote-cert-tls instead.,
Thu Mar  7 11:29:15 2019 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts,
Thu Mar  7 11:29:15 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]95.211.112.19:443,
Thu Mar  7 11:29:15 2019 UDP link local: (not bound),
Thu Mar  7 11:29:15 2019 UDP link remote: [AF_INET]95.211.112.19:443,
Thu Mar  7 11:30:15 2019 [UNDEF] Inactivity timeout (--ping-exit), exiting,
Thu Mar  7 11:30:15 2019 SIGTERM[soft,ping-exit] received, process exiting,
Using OpenVPN provider: ANONINE,
No VPN configuration provided. Using default.,
Setting OPENVPN credentials...,
adding route to local network 192.168.1.0/24 via 172.19.0.1 dev eth0,
Thu Mar  7 11:30:19 2019 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 19 2019,
Thu Mar  7 11:30:19 2019 library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08,
Thu Mar  7 11:30:19 2019 WARNING: --ns-cert-type is DEPRECATED.  Use --remote-cert-tls instead.,
Thu Mar  7 11:30:19 2019 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts,
Thu Mar  7 11:30:19 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]103.194.171.157:443,
Thu Mar  7 11:30:19 2019 UDP link local: (not bound),
Thu Mar  7 11:30:19 2019 UDP link remote: [AF_INET]103.194.171.157:443,
Thu Mar  7 11:31:19 2019 [UNDEF] Inactivity timeout (--ping-exit), exiting,
Thu Mar  7 11:31:19 2019 SIGTERM[soft,ping-exit] received, process exiting,
Using OpenVPN provider: ANONINE,
No VPN configuration provided. Using default.,
Setting OPENVPN credentials...,
adding route to local network 192.168.1.0/24 via 172.19.0.1 dev eth0,
Thu Mar  7 11:31:23 2019 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 19 2019,
Thu Mar  7 11:31:23 2019 library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08,
Thu Mar  7 11:31:23 2019 WARNING: --ns-cert-type is DEPRECATED.  Use --remote-cert-tls instead.,
Thu Mar  7 11:31:23 2019 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts,
Thu Mar  7 11:31:23 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]94.100.29.243:443,
Thu Mar  7 11:31:23 2019 UDP link local: (not bound),
Thu Mar  7 11:31:23 2019 UDP link remote: [AF_INET]94.100.29.243:443,
Thu Mar  7 11:32:23 2019 [UNDEF] Inactivity timeout (--ping-exit), exiting,
Thu Mar  7 11:32:23 2019 SIGTERM[soft,ping-exit] received, process exiting,
Using OpenVPN provider: ANONINE,
No VPN configuration provided. Using default.,
Setting OPENVPN credentials...,
adding route to local network 192.168.1.0/24 via 172.19.0.1 dev eth0,
Thu Mar  7 11:32:27 2019 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 19 2019,
Thu Mar  7 11:32:27 2019 library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08,
Thu Mar  7 11:32:27 2019 WARNING: --ns-cert-type is DEPRECATED.  Use --remote-cert-tls instead.,
Thu Mar  7 11:32:27 2019 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts,
Thu Mar  7 11:32:31 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]95.211.112.19:443,
Thu Mar  7 11:32:31 2019 UDP link local: (not bound),
Thu Mar  7 11:32:31 2019 UDP link remote: [AF_INET]95.211.112.19:443,
Thu Mar  7 11:33:32 2019 [UNDEF] Inactivity timeout (--ping-exit), exiting,
Thu Mar  7 11:33:32 2019 SIGTERM[soft,ping-exit] received, process exiting,
Using OpenVPN provider: ANONINE,
No VPN configuration provided. Using default.,
Setting OPENVPN credentials...,
adding route to local network 192.168.1.0/24 via 172.19.0.1 dev eth0,
Thu Mar  7 11:33:36 2019 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 19 2019,
Thu Mar  7 11:33:36 2019 library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08,
Thu Mar  7 11:33:36 2019 WARNING: --ns-cert-type is DEPRECATED.  Use --remote-cert-tls instead.,
Thu Mar  7 11:33:36 2019 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts,
Thu Mar  7 11:33:36 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]95.211.112.19:443,
Thu Mar  7 11:33:36 2019 UDP link local: (not bound),
Thu Mar  7 11:33:36 2019 UDP link remote: [AF_INET]95.211.112.19:443,
Thu Mar  7 11:34:36 2019 [UNDEF] Inactivity timeout (--ping-exit), exiting,
Thu Mar  7 11:34:36 2019 SIGTERM[soft,ping-exit] received, process exiting,
Using OpenVPN provider: ANONINE,
No VPN configuration provided. Using default.,
Setting OPENVPN credentials...,
adding route to local network 192.168.1.0/24 via 172.19.0.1 dev eth0,
Thu Mar  7 11:34:40 2019 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 19 2019,
Thu Mar  7 11:34:40 2019 library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08,
Thu Mar  7 11:34:40 2019 WARNING: --ns-cert-type is DEPRECATED.  Use --remote-cert-tls instead.,
Thu Mar  7 11:34:40 2019 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts,
Thu Mar  7 11:34:41 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]94.100.28.99:443,
Thu Mar  7 11:34:41 2019 UDP link local: (not bound),
Thu Mar  7 11:34:41 2019 UDP link remote: [AF_INET]94.100.28.99:443,
Thu Mar  7 11:35:41 2019 [UNDEF] Inactivity timeout (--ping-exit), exiting,
Thu Mar  7 11:35:41 2019 SIGTERM[soft,ping-exit] received, process exiting,
Using OpenVPN provider: ANONINE,
No VPN configuration provided. Using default.,
Setting OPENVPN credentials...,
adding route to local network 192.168.1.0/24 via 172.19.0.1 dev eth0,
Thu Mar  7 11:35:46 2019 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 19 2019,
Thu Mar  7 11:35:46 2019 library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08,
Thu Mar  7 11:35:46 2019 WARNING: --ns-cert-type is DEPRECATED.  Use --remote-cert-tls instead.,
Thu Mar  7 11:35:46 2019 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts,
Thu Mar  7 11:35:46 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]95.211.112.19:443,
Thu Mar  7 11:35:46 2019 UDP link local: (not bound),
Thu Mar  7 11:35:46 2019 UDP link remote: [AF_INET]95.211.112.19:443,
```
some info:
Docker 18.03.1-ee-3 on linux, amd64
image created: 2019-02-27 01:10:25
haugene/transmission-openvpn:latest
