### ISSUE TITLE
OpenVPN no longer let's you pass remote in VPN_OPTS (Torguard Denmark)

### ISSUE THREAD

**Issue by tinefin** [haugene/docker-transmission-openvpn#767]
I have been using this docker image for over a year (thank you!!).

*Issue*
Lately I have been experiencing intermittent connection issues and closed port when I am able to connect (I have a port forward set up w Torguard on a specific IP).

*Symptoms*
I am getting this error constantly:

`RESOLVE: Cannot resolve host address: den.torguardvpnaccess.com:995 (Temporary failure in name resolution)`

At other times I see:

Which is odd, since I am passing the IP I want in my .env file (see below).

I am also seeing this error

*Theory*
Seems like the connection hangs on to the `den.torguardvpnaccess.com:995` in Denmark.opvn, rather than replace it with my `--remote` in the .env file?

The den.torguardvpnaccess.com domain resolves to at least 6 different IPs:
https://www.whatsmydns.net/#A/den.torguardvpnaccess.com
At worst, I get an IP which refuses connection.
At best, I get a (round robin?) danish IP which might or might not be the one which has my port forward,

Any chance something changed, so the remote can no longer be overridden in .env file / passed as parameter?

**Add your docker run command**
`docker-compose up -d`

docker-compose.yml:
```
version: "3.4"

services:
  tmv:
    container_name: tmv
    image: haugene/transmission-openvpn:latest
    dns: 
      - 8.8.8.8
      - 8.8.4.4
    env_file: 
      - "/Users/[***]/_bin/tmvdocker.env"
    cap_add: 
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    volumes:
      - "/Users/[***]/_dockertransmission:/data"
    ports:
      - "9091:9091"
    devices: 
      - "/dev/net/tun"
    restart: unless-stopped
    logging: 
      driver: "json-file"
      options:
        max-size: "10m"
```
tmvdocker.env:
```
OPENVPN_PROVIDER=TorGuard
OPENVPN_CONFIG=Denmark
OPENVPN_OPTS=--remote [***.***.***.***] 1912 --inactive 3600 --ping 10 --ping-exit 60 --reneg-sec 300
OPENVPN_USERNAME=[***]
OPENVPN_PASSWORD=[***]
LOCAL_NETWORK=[***]
TRANSMISSION_DOWNLOAD_DIR=/data/completed
TRANSMISSION_IDLE_SEEDING_LIMIT=720
TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED=true
TRANSMISSION_MAX_PEERS_GLOBAL=1200
TRANSMISSION_PEER_LIMIT_GLOBAL=1200
TRANSMISSION_PEER_LIMIT_PER_TORRENT=250
TRANSMISSION_PEER_PORT=[***]
TRANSMISSION_RATIO_LIMIT=8
TRANSMISSION_RATIO_LIMIT_ENABLED=true
TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=false
TRANSMISSION_SPEED_LIMIT_UP=500
TRANSMISSION_SPEED_LIMIT_UP_ENABLED=true
TRANSMISSION_UTP_ENABLED=false
TRANSMISSION_WEB_UI=transmission-web-control
```
