### ISSUE TITLE
.magnet files not getting picked up

### ISSUE THREAD

**Issue by Spass1966** [haugene/docker-transmission-openvpn#785]
Some indexers only support .magnet torrents. When these .magnet files are downloaded to Transmission's watch folder they aren't picked up. I have confirmed these magnet links have the same permissions as Transmission's.

```
  transmission:
    image: haugene/transmission-openvpn
    container_name: transmission
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: always
    ports:
      - "5143:5143"
      - "9091:9091"
      - 8888:8888
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/services/homes/taohansen/watch:/data/watch
      - /var/services/homes/taohansen/downloads:/data/completed
    environment:
      - PUID=1026
      - PGID=101
      - TZ=Europe/Warsaw
      - OPENVPN_PROVIDER=Windscribe
      - OPENVPN_CONFIG=Poland-udp
      - OPENVPN_USERNAME=obfuscated
      - OPENVPN_PASSWORD=obfuscated
      - TRANSMISSION_WATCH_DIR_FORCE_GENERIC=true
      - TRANSMISSION_DOWNLOAD_DIR=/data/completed
      - TRANSMISSION_WATCH_DIR=/data/watch
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=192.168.0.0/24
      - WEBPROXY_ENABLED=true
```

**Logs**
```
Sat Apr 20 20:14:34 2019 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Sat Apr 20 20:14:34 2019 VERIFY EKU OK
Sat Apr 20 20:14:34 2019 VERIFY OK: depth=0, C=CA, ST=ON, O=Windscribe Limited, OU=Operations, CN=Windscribe Node Server 4096
Sat Apr 20 20:14:34 2019 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1602', remote='link-mtu 1550'
Sat Apr 20 20:14:34 2019 WARNING: 'cipher' is used inconsistently, local='cipher AES-256-CBC', remote='cipher AES-256-GCM'
Sat Apr 20 20:14:34 2019 WARNING: 'auth' is used inconsistently, local='auth SHA512', remote='auth [null-digest]'
Sat Apr 20 20:14:34 2019 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Sat Apr 20 20:14:34 2019 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Sat Apr 20 20:14:34 2019 Control Channel: TLSv1.2, cipher TLSv1/SSLv3 ECDHE-RSA-AES256-GCM-SHA384, 4096 bit RSA
Sat Apr 20 21:14:34 2019 VERIFY OK: depth=1, C=CA, ST=ON, L=Toronto, O=Windscribe Limited, OU=Operations, CN=Windscribe Node CA
Sat Apr 20 21:14:34 2019 VERIFY KU OK
Sat Apr 20 21:14:34 2019 Validating certificate extended key usage
Sat Apr 20 21:14:34 2019 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Sat Apr 20 21:14:34 2019 VERIFY EKU OK
Sat Apr 20 21:14:34 2019 VERIFY OK: depth=0, C=CA, ST=ON, O=Windscribe Limited, OU=Operations, CN=Windscribe Node Server 4096
Sat Apr 20 21:14:34 2019 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1602', remote='link-mtu 1550'
Sat Apr 20 21:14:34 2019 WARNING: 'cipher' is used inconsistently, local='cipher AES-256-CBC', remote='cipher AES-256-GCM'
Sat Apr 20 21:14:34 2019 WARNING: 'auth' is used inconsistently, local='auth SHA512', remote='auth [null-digest]'
Sat Apr 20 21:14:34 2019 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Sat Apr 20 21:14:34 2019 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Sat Apr 20 21:14:34 2019 Control Channel: TLSv1.2, cipher TLSv1/SSLv3 ECDHE-RSA-AES256-GCM-SHA384, 4096 bit RSA
Sat Apr 20 22:14:34 2019 VERIFY OK: depth=1, C=CA, ST=ON, L=Toronto, O=Windscribe Limited, OU=Operations, CN=Windscribe Node CA
Sat Apr 20 22:14:34 2019 VERIFY KU OK
Sat Apr 20 22:14:34 2019 Validating certificate extended key usage
Sat Apr 20 22:14:34 2019 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Sat Apr 20 22:14:34 2019 VERIFY EKU OK
Sat Apr 20 22:14:34 2019 VERIFY OK: depth=0, C=CA, ST=ON, O=Windscribe Limited, OU=Operations, CN=Windscribe Node Server 4096
Sat Apr 20 22:14:34 2019 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1602', remote='link-mtu 1550'
Sat Apr 20 22:14:34 2019 WARNING: 'cipher' is used inconsistently, local='cipher AES-256-CBC', remote='cipher AES-256-GCM'
Sat Apr 20 22:14:34 2019 WARNING: 'auth' is used inconsistently, local='auth SHA512', remote='auth [null-digest]'
Sat Apr 20 22:14:34 2019 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Sat Apr 20 22:14:34 2019 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Sat Apr 20 22:14:34 2019 Control Channel: TLSv1.2, cipher TLSv1/SSLv3 ECDHE-RSA-AES256-GCM-SHA384, 4096 bit RSA
Sat Apr 20 23:14:34 2019 VERIFY OK: depth=1, C=CA, ST=ON, L=Toronto, O=Windscribe Limited, OU=Operations, CN=Windscribe Node CA
Sat Apr 20 23:14:34 2019 VERIFY KU OK
Sat Apr 20 23:14:34 2019 Validating certificate extended key usage
Sat Apr 20 23:14:34 2019 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Sat Apr 20 23:14:34 2019 VERIFY EKU OK
Sat Apr 20 23:14:34 2019 VERIFY OK: depth=0, C=CA, ST=ON, O=Windscribe Limited, OU=Operations, CN=Windscribe Node Server 4096
Sat Apr 20 23:14:34 2019 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1602', remote='link-mtu 1550'
Sat Apr 20 23:14:34 2019 WARNING: 'cipher' is used inconsistently, local='cipher AES-256-CBC', remote='cipher AES-256-GCM'
Sat Apr 20 23:14:34 2019 WARNING: 'auth' is used inconsistently, local='auth SHA512', remote='auth [null-digest]'
Sat Apr 20 23:14:34 2019 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Sat Apr 20 23:14:34 2019 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Sat Apr 20 23:14:34 2019 Control Channel: TLSv1.2, cipher TLSv1/SSLv3 ECDHE-RSA-AES256-GCM-SHA384, 4096 bit RSA
```
