### ISSUE TITLE
"Torrent Done" Script Doesn't Appear to Run

### ISSUE THREAD

**Issue by MitchTalmadge** [haugene/docker-transmission-openvpn#802]
**Describe the problem**

Using the "torrent done" environment variables (below), I cannot get a script to run when a torrent finishes downloading. The `/data/transmission-home/transmission.log` file does say that the script is called, but the script never does what it is supposed to, and the file `atime` does not change since its creation which implies that it is never read or executed.

Environment variables in question:
`TRANSMISSION_SCRIPT_TORRENT_DONE_ENABLED`
`TRANSMISSION_SCRIPT_TORRENT_DONE_FILENAME`

Related issues: (Nothing seemed to help. Many authors just abandoned their issues or did not describe their solution.)
#75 
#483
#494 
#622 
#701

**Add your docker run command**

<details><summary>docker-compose.yml (Click Here)</summary>

```yml
version: "3"
services:
  transmission:
    image: haugene/transmission-openvpn:2.7
    ports:
      - "9091:9091"
    dns:
      - 1.1.1.1
      - 8.8.8.8
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    volumes:
      - "/var/opt/transmission/data:/data"
      - "/opt/transmission/scripts:/scripts"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - "PUID=120"
      - "PGID=124"
      - "OPENVPN_PROVIDER=PIA"
      - "OPENVPN_CONFIG=US Midwest,US West,US California,US Seattle"
      - "OPENVPN_USERNAME=?????????"
      - "OPENVPN_PASSWORD=?????????"
      - "WEBPROXY_ENABLED=false"
      - "LOCAL_NETWORK=127.0.0.1/32"
      - "TRANSMISSION_WEB_UI=transmission-web-control"
      - "TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true"
      - "TRANSMISSION_RPC_USERNAME=????????????"
      - "TRANSMISSION_RPC_PASSWORD=????????????"
      - "TRANSMISSION_PEER_PORT=9092"
      - "TRANSMISSION_RATIO_LIMIT=2.0"
      - "TRANSMISSION_RATIO_LIMIT_ENABLED=true"
      - "TRANSMISSION_SCRIPT_TORRENT_DONE_ENABLED=true"
      - "TRANSMISSION_SCRIPT_TORRENT_DONE_FILENAME=/scripts/test.sh"
    restart: unless-stopped
```

</details>

The `PUID` and `PGID` provided are for the user `transmission`, as seen here:
```
transmission:x:120:124::/home/transmission:/bin/false
```
Interestingly, when the docker container starts it claims that the user is called `abc`. Not sure why.

**Script**
The script that is being run is as follows:

`test.sh`:
```bash
echo "test" > test.txt
```

Permissions: (Full permissions granted to world as a last resort -- no luck)
```
mitchtalmadge@cloud:/opt/transmission/scripts$ ls -al
drwxr-xr-x 2 transmission transmission 4096 May  3 17:25 .
drwxr-xr-x 3 transmission transmission 4096 May  3 17:26 ..
-rwxrwxrwx 1 transmission transmission   23 May  3 17:25 test.sh
-rwxrwxrwx 1 transmission transmission    0 May  3 17:25 test.txt
```

The `test.txt` file is empty, even after download completes.

**Logs**

<details><summary>Docker Logs (Click Here)</summary>

```
mitchtalmadge@cloud:/opt/transmission$ sudo docker-compose logs
[sudo] password for mitchtalmadge:
Attaching to transmission_transmission_1
transmission_1  | Using OpenVPN provider: PIA
transmission_1  | 4 servers found in OPENVPN_CONFIG, US California chosen randomly
transmission_1  | Starting OpenVPN using config US California.ovpn
transmission_1  | Setting OPENVPN credentials...
transmission_1  | adding route to local network 127.0.0.1/32 via 172.27.0.1 dev eth0
transmission_1  | Fri May  3 17:27:44 2019 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 19 2019
transmission_1  | Fri May  3 17:27:44 2019 library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08
transmission_1  | Fri May  3 17:27:44 2019 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
transmission_1  | Fri May  3 17:27:44 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]91.207.175.34:1198
transmission_1  | Fri May  3 17:27:44 2019 UDP link local: (not bound)
transmission_1  | Fri May  3 17:27:44 2019 UDP link remote: [AF_INET]91.207.175.34:1198
transmission_1  | Fri May  3 17:27:44 2019 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
transmission_1  | Fri May  3 17:27:44 2019 [7d704bdf3731cc5d3e82f312868cc42a] Peer Connection Initiated with [AF_INET]91.207.175.34:1198
transmission_1  | Fri May  3 17:27:50 2019 TUN/TAP device tun0 opened
transmission_1  | Fri May  3 17:27:50 2019 /sbin/ip link set dev tun0 up mtu 1500
transmission_1  | Fri May  3 17:27:50 2019 /sbin/ip addr add dev tun0 local 10.8.11.6 peer 10.8.11.5
transmission_1  | Fri May  3 17:27:50 2019 /etc/openvpn/tunnelUp.sh tun0 1500 1558 10.8.11.6 10.8.11.5 init
transmission_1  | Up script executed with tun0 1500 1558 10.8.11.6 10.8.11.5 init
transmission_1  | Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.8.11.6
transmission_1  | Using Transmission Web Control  UI, overriding TRANSMISSION_WEB_HOME
transmission_1  | Generating transmission settings.json from env variables
transmission_1  | sed'ing True to true
transmission_1  | Enforcing ownership on transmission config directories
transmission_1  | Applying permissions to transmission config directories
transmission_1  | Setting owner for transmission paths to 120:124
transmission_1  | Setting permission for files (644) and directories (755)
transmission_1  |
transmission_1  | -------------------------------------
transmission_1  | Transmission will run as
transmission_1  | -------------------------------------
transmission_1  | User name:   abc
transmission_1  | User uid:    120
transmission_1  | User gid:    124
transmission_1  | -------------------------------------
transmission_1  |
transmission_1  | STARTING TRANSMISSION
transmission_1  | CONFIGURING PORT FORWARDING
transmission_1  | Transmission startup script complete.
transmission_1  | Wait for tunnel to be fully initialized and PIA is ready to give us a port
transmission_1  | Fri May  3 17:27:50 2019 Initialization Sequence Completed
transmission_1  | Generating new client id for PIA
transmission_1  | Port forwarding is already activated on this connection, has expired, or you are not connected to a PIA region that supports port forwarding
transmission_1  | curl encountered an error looking up new port: 7
```

</details>

<details><summary>Transmission Logs (Click Here)</summary>

```
[2019-05-03 17:31:08.125] Example_Torrent State changed from "Incomplete" to "Complete" (torrent.c:2218)
[2019-05-03 17:31:08.125] Example_Torrent moving "/data/incomplete/Example_Torrent/Example.txt" to "/data/completed/Example_Torrent/Example.txt" (torrent.c:3157)
[2019-05-03 17:31:08.125] Example_Torrent Calling script "/scripts/test.sh" (torrent.c:2118)
```

</details>

**Host system:**

Debian 9:
```
Linux 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1 (2019-04-12) x86_64 GNU/Linux
```

Docker:
```
Docker version 18.09.5, build e8ff056dbc
docker-compose version 1.24.0, build 0aa59064
```

Thank you for your help.
