### ISSUE TITLE
Transmission 2.94 on armhf

### ISSUE THREAD

**Issue by LarsaSolidor** [haugene/docker-transmission-openvpn#805]
**Describe the problem**

The version of transmission installed by the docker-transmission-openvpn image is 2.92 on the armhf tag; the latest is 2.94 which is what should be installed. 

**Add your docker run command**

```
transmission-vpn:
    container_name: transmission-vpn
    image: haugene/transmission-openvpn:latest-armhf
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: always
    ports:
      - "10005:9091"
    dns:
      - 209.222.18.222
      - 209.222.18.218
    volumes:
      - ${DATASTOREDIR}/transmission/transmission-vpn:/data
      - ${MEDIADIR}/Downloads/Completed:/data/completed
      - ${MEDIADIR}/Downloads/Incomplete:/data/incomplete
    env_file:
      - .env
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=transmission-vpn"
      - "traefik.frontend.rule=Host:transmission.${DOMAINNAME}"
      - "traefik.port=9091"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=redacted-host-name.com"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
```

**Logs**

```
-------------------------------------
Transmission will run as
-------------------------------------
User name:   abc
User uid:    1000
User gid:    1000
-------------------------------------

STARTING TRANSMISSION
CONFIGURING PORT FORWARDING
Transmission startup script complete.
Wait for tunnel to be fully initialized and PIA is ready to give us a port
STARTING TINYPROXY
Found config file /etc/tinyproxy/tinyproxy.conf, updating settings.
Setting tinyproxy port to 8888
Starting Tinyproxy lightweight HTTP proxy daemon: tinyproxy.
Tinyproxy startup script complete.
Sun May  5 21:53:17 2019 Initialization Sequence Completed
Got new port 24673 from PIA
transmission auth required
Unexpected response: <h1>401: Unauthorized</h1>Unauthorized Userc ****

Unexpected response: <h1>401: Unauthorized</h1>Unauthorized Userc ****

Checking port...
Unexpected response: <h1>401: Unauthorized</h1>Unauthorized Userc ****
```

**Host system:**

Raspberry Pi running Docker version 18.09.0, build 4d60db4
