### ISSUE TITLE
Need help with two issues, expressVPN and no ports assigned.

### ISSUE THREAD

**Issue by SyRaza** [haugene/docker-transmission-openvpn#822]
I'm having two issues. I can't seem to authorise ExpressVPN even after following the instructions provided in #610.

Second issue is that the ports get unassigned after the container is started. My guess is this is because the VPN can't be authorised, is that corrected?

Here is my docker-compose configuration

```
# Transmission with VPN – Bittorrent Downloader
  transmission:
    image: haugene/transmission-openvpn
    container_name: transmission-vpn
    hostname: transmission
    cap_add:
      - NET_ADMIN
#    devices:
#      - /dev/net/tun
    restart: always
    ports:
      - "9091:9091"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/docker/shared:/shared
      - /opt/docker/transmission-vpn:/data
      - /mnt/storage/downloads:/data/watch
      - /mnt/storage/complete:/data/completed
      - /mnt/storage/incomplete:/data/incomplete
      - /opt/docker/transmission-vpn/exp.ovpn:/etc/openvpn/custom/default.ovpn
      - /opt/docker/transmission-vpn/auth.txt:/etc/openvpn/custom/auth.txt
    environment:
      - OPENVPN_PROVIDER=CUSTOM
      - OPENVPN_USERNAME=user
      - OPENVPN_PASSWORD=pass
      - CREATE_TUN_DEVICE=true
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 300
      - LOCAL_NETWORK=192.168.1.0/24      
      - PGID=${PUID}
      - PUID=${PGID}
      - TZ=${TZ}
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      - TRANSMISSION_RPC_PASSWORD=###mypass12312###
      - TRANSMISSION_RPC_USERNAME=###myusername###
      - TRANSMISSION_UMASK=077      
      - TRANSMISSION_SPEED_LIMIT_UP=8000
      - TRANSMISSION_SPEED_LIMIT_UP_ENABLED=true
      - TRANSMISSION_SPEED_LIMIT_DOWN=8000
      - TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED=true
      - TRANSMISSION_RATIO_LIMIT=2
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
      - TRANSMISSION_INCOMPLETE_DIR=/downloads/incomplete
      - TRANSMISSION_INCOMPLETE_DIR_ENABLED=true
      - TRANSMISSION_WATCH_DIR=/downloads
      - TRANSMISSION_WATCH_DIR_ENABLED=true
      - TRANSMISSION_DOWNLOAD_DIR=/downloads/completed
      - TRANSMISSION_WEB_UI=combustion
```

Here is part of the ovpn file I downloaded from ExpressVPN, with the cert part omitted

```
dev tun
fast-io
persist-key
persist-tun
nobind
remote canada-toronto-ca-version-2.expressnetw.com 1195

remote-random
pull
comp-lzo no
tls-client
verify-x509-name Server name-prefix
ns-cert-type server
key-direction 1
route-method exe
route-delay 2
tun-mtu 1500
fragment 1300
mssfix 1200
verb 3
cipher AES-256-CBC
keysize 256
auth SHA512
sndbuf 524288
rcvbuf 524288
auth-user-pass /etc/openvpn/custom/auth.txt
```

The auth.txt file has this:
```
myemail@email.com
mypassword
```

And here is the log from portainer.

```
Using OpenVPN provider: CUSTOM
No VPN configuration provided. Using default.
Setting OPENVPN credentials...
adding route to local network 192.168.1.0/24 via 172.18.0.1 dev eth0
Mon Jun  3 00:24:22 2019 WARNING: --keysize is DEPRECATED and will be removed in OpenVPN 2.6
Mon Jun  3 00:24:22 2019 WARNING: file '/etc/openvpn/custom/auth.txt' is group or others accessible
Mon Jun  3 00:24:22 2019 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 19 2019
Mon Jun  3 00:24:22 2019 library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08
Mon Jun  3 00:24:22 2019 WARNING: --ns-cert-type is DEPRECATED.  Use --remote-cert-tls instead.
Mon Jun  3 00:24:22 2019 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Mon Jun  3 00:24:22 2019 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
Mon Jun  3 00:24:22 2019 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
Mon Jun  3 00:24:22 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]199.167.137.18:1195
Mon Jun  3 00:24:22 2019 Socket Buffers: R=[212992->425984] S=[212992->425984]
Mon Jun  3 00:24:22 2019 UDP link local: (not bound)
Mon Jun  3 00:24:22 2019 UDP link remote: [AF_INET]199.167.137.18:1195
Mon Jun  3 00:24:22 2019 TLS: Initial packet from [AF_INET]199.167.137.18:1195, sid=bea70fa4 b73322ad
Mon Jun  3 00:24:22 2019 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Mon Jun  3 00:24:22 2019 VERIFY OK: depth=1, C=VG, ST=BVI, O=ExpressVPN, OU=ExpressVPN, CN=ExpressVPN CA, emailAddress=support@expressvpn.com
Mon Jun  3 00:24:22 2019 VERIFY OK: nsCertType=SERVER
Mon Jun  3 00:24:22 2019 VERIFY X509NAME OK: C=VG, ST=BVI, O=ExpressVPN, OU=ExpressVPN, CN=Server-2188-1a, emailAddress=support@expressvpn.com
Mon Jun  3 00:24:22 2019 VERIFY OK: depth=0, C=VG, ST=BVI, O=ExpressVPN, OU=ExpressVPN, CN=Server-2188-1a, emailAddress=support@expressvpn.com
Mon Jun  3 00:24:22 2019 Control Channel: TLSv1.2, cipher TLSv1/SSLv3 ECDHE-RSA-AES256-GCM-SHA384, 2048 bit RSA
Mon Jun  3 00:24:22 2019 [Server-2188-1a] Peer Connection Initiated with [AF_INET]199.167.137.18:1195
Mon Jun  3 00:24:23 2019 SENT CONTROL [Server-2188-1a]: 'PUSH_REQUEST' (status=1)
Mon Jun  3 00:24:24 2019 AUTH: Received control message: AUTH_FAILED
Mon Jun  3 00:24:24 2019 SIGTERM[soft,auth-failure] received, process exiting
```

Not sure where I'm supposed to go from here. Any suggestions?
