### ISSUE TITLE
ERROR: Cannot ioctl TUNSETIFF tun: Operation not permitted (errno=1)

### ISSUE THREAD

**Issue by tyhawk** [haugene/docker-transmission-openvpn#888]
**Describe the problem**
When starting the container I get the following error:
```
ERROR: Cannot ioctl TUNSETIFF tun: Operation not permitted (errno=1)
```
I suspect this is due to an upstream issue with Docker, but I wanted to create a bug report anyway, either as a reference to others with the same issue or in case I am wrong and there is a solution for it.

**Add your docker run command**
```
version: "3"
services:
  transmission:
    image: haugene/transmission-openvpn
    environment:
      - PUID=1000
      - PGID=999
      - TZ=Europe/Amsterdam
      - CREATE_TUN_DEVICE=true
      - OPENVPN_PROVIDER=PROVIDER
      - OPENVPN_USERNAME=user
      - OPENVPN_PASSWORD=password
      - WEBPROXY_ENABLED=false
      - TRANSMISSION_WEB_UI=kettu
      - LOCAL_NETWORK=172.16.10.0/24
    volumes:
      - /srv/downloads:/downloads
    networks:
      - traefik-public
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
    dns:
      - myhomedns
    ports:
      - 9091:9091
    deploy:
      restart_policy:
        condition: any
      labels:
        - traefik.enable=true
        - traefik.tags=traefik-public
        - traefik.frontend.rule=Host:torrent.mydomain.com
        - traefik.docker.network=traefik-public
        - traefik.port=9091
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "4"
```

**Logs**
```
Sat Aug 31 11:56:14 2019 us=377975 Data Channel: using negotiated cipher 'AES-256-GCM',
Sat Aug 31 11:56:14 2019 us=378078 Data Channel MTU parms [ L:1553 D:1400 EF:53 EB:406 ET:0 EL:3 ],
Sat Aug 31 11:56:14 2019 us=378806 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Sat Aug 31 11:56:14 2019 us=378928 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key,
Sat Aug 31 11:56:14 2019 us=380012 ROUTE_GATEWAY 172.18.0.1/255.255.0.0 IFACE=eth2 HWADDR=02:42:ac:12:00:0d,
Sat Aug 31 11:56:14 2019 us=380276 ERROR: Cannot ioctl TUNSETIFF tun: Operation not permitted (errno=1),
Sat Aug 31 11:56:14 2019 us=380343 Exiting due to fatal error
```

**Host system:**
I am running on three Ubuntu 18.04.3 hosts (amd64 and armv7l) with the latest packages and Docker version 19.03.1, build 74b1e89. The issue is probably this: I run Docker in Swarm Mode and according to the Docker documentation, cap_add is  ignored when deploying a stack in swarm mode with a (version 3) Compose file.

**Workaround**
Starting the container from the commandline according to instructions in the documentation of this project.
