### ISSUE TITLE
docker-compose: OpenVPN provider not set. Exiting.

### ISSUE THREAD

**Issue by stefnats** [haugene/docker-transmission-openvpn#889]
Hi.

I'm using docker-compose like this:

```yaml
version: '3'
services:
 transmission:
  image: haugene/transmission-openvpn
  cap_add:
    - NET_ADMIN
  devices:
    - /dev/net/tun
  restart: always
  ports:
    - "9091:9091"
    - "8888:8888"
  dns:
    - 8.8.8.8
    - 8.8.4.4
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /my/path/to/data:/data
  env_file:
    - /my/path/to/vpn.env
```

However, the environment variables don't get set which results in:

```
me@server:/my/docker-compose/path$ sudo docker logs leecher_transmission_1
OpenVPN provider not set. Exiting.
OpenVPN provider not set. Exiting.
OpenVPN provider not set. Exiting.
OpenVPN provider not set. Exiting.
```

This is `vpn.env`

```env
OPENVPN_PROVIDER=PERFECTPRIVACY
OPENVPN_CONFIG=Berlin
OPENVPN_USERNAME=user
OPENVPN_PASSWORD=pass
#LOCAL_NETWORK=192.168.0.0/16
#OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
```

Even with the `environment` array in `docker-compose.yml` it's the same:

```
transmission-openvpn:
  image: haugene/transmission-openvpn
  environment:
   - OPENVPN_PROVIDER=PERFECTPRIVACY
   - OPENVPN_CONFIG=Berlin
   - OPENVPN_USERNAME=user
   - OPENVPN_PASSWORD=pass
   - LOCAL_NETWORK=192.168.0.0/16
   - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
```

i don't know any further. can you help?
