### ISSUE TITLE
DNS not being set in container

### ISSUE THREAD

**Issue by odinsride** [haugene/docker-transmission-openvpn#896]
**Describe the problem**

When checking the DNS from `/etc/resolv.conf`, the nameserver is not set to the value I'm passing in via docker-compose.yml

I have tried with :latest as well as :dev images.  Also, the repercussions of this seems to be that magnetized links are not downloading, and stalling at "Retrieving metadata".  I searched the issues for the magnetized links issue and followed the suggestions in #533 but the DNS portion doesn't seem to be working for me.

**Add your docker run command**

I'm using docker-compose and this is my section for transmission-openvpn:

```
  transmission-vpn:
    container_name: transmission-vpn
    image: haugene/transmission-openvpn:dev
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: always
    ports:
      - "9091:9091"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/docker/transmission-vpn:/data
      - ${USERDIR}/docker/shared:/shared
      - /media/downloads:/data/watch
      - /media/downloads/completed:/data/completed
      - /media/downloads/incomplete:/data/incomplete
    environment:
      - OPENVPN_PROVIDER=IPVANISH
      - OPENVPN_USERNAME=${IPV_USERNAME}
      - OPENVPN_PASSWORD=${IPV_PASSWORD}
      - OPENVPN_CONFIG=${IPV_SERVER}
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60 --mssfix 1640
      - LOCAL_NETWORK=192.168.1.0/24
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      - TRANSMISSION_RPC_HOST_WHITELIST="127.0.0.1,192.168.*.*"
      - TRANSMISSION_RPC_USERNAME=${TRANSMISSION_USERNAME}
      - TRANSMISSION_RPC_PASSWORD=${TRANSMISSION_PASSWORD}
      - TRANSMISSION_UMASK=002
      - TRANSMISSION_RATIO_LIMIT=0.0
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    dns:
      - 8.8.8.8
      - 8.8.4.4
```

**Logs**

**/etc/resolv.conf**
```
root@089b435cf4d1:/# cat /etc/resolv.conf
nameserver 127.0.0.11
options ndots:0
```

**Docker log**
```
Using OpenVPN provider: IPVANISH
Starting OpenVPN using config xyzxyz.ovpn
Setting OPENVPN credentials...
adding route to local network 192.168.1.0/24 via 172.24.0.1 dev eth0
Mon Sep 16 11:21:15 2019 WARNING: --keysize is DEPRECATED and will be removed in OpenVPN 2.6
Mon Sep 16 11:21:15 2019 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 19 2019
Mon Sep 16 11:21:15 2019 library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08
Mon Sep 16 11:21:15 2019 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Mon Sep 16 11:21:15 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]216.151.191.12:443
Mon Sep 16 11:21:15 2019 Socket Buffers: R=[212992->212992] S=[212992->212992]
Mon Sep 16 11:21:15 2019 UDP link local: (not bound)
Mon Sep 16 11:21:15 2019 UDP link remote: [AF_INET]216.151.191.12:443
Mon Sep 16 11:21:15 2019 TLS: Initial packet from [AF_INET]216.151.191.12:443, sid=d1a0a0e7 e0b4888f
Mon Sep 16 11:21:15 2019 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Mon Sep 16 11:21:15 2019 VERIFY OK: depth=1, C=US, ST=FL, L=Winter Park, O=IPVanish, OU=IPVanish VPN, CN=IPVanish CA, emailAddress=support@ipvanish.com
Mon Sep 16 11:21:15 2019 VERIFY X509NAME OK: C=US, ST=FL, L=Winter Park, O=IPVanish, OU=IPVanish VPN, CN=xyzxyz.ipvanish.com emailAddress=support@ipvanish.com
Mon Sep 16 11:21:15 2019 VERIFY OK: depth=0, C=US, ST=FL, L=Winter Park, O=IPVanish, OU=IPVanish VPN, CN=xyzxyz.ipvanish.com, emailAddress=support@ipvanish.com
Mon Sep 16 11:21:15 2019 Control Channel: TLSv1.2, cipher TLSv1/SSLv3 DHE-RSA-AES256-SHA, 2048 bit RSA
Mon Sep 16 11:21:15 2019 [xyzxyz.ipvanish.com] Peer Connection Initiated with [AF_INET]216.151.191.12:443
Mon Sep 16 11:21:17 2019 SENT CONTROL [xyzxyz.ipvanish.com]: 'PUSH_REQUEST' (status=1)
Mon Sep 16 11:21:17 2019 PUSH: Received control message: 'PUSH_REPLY,redirect-gateway def1 bypass-dhcp,dhcp-option DNS 198.18.0.1,dhcp-option DNS 198.18.0.2,rcvbuf 493216,sndbuf 493216,explicit-exit-notify 5,comp-lzo no,route-gateway 172.21.22.1,topology subnet,ping 20,ping-restart 40,ifconfig 172.21.22.213 255.255.254.0,peer-id 58,cipher AES-256-GCM'
Mon Sep 16 11:21:17 2019 OPTIONS IMPORT: timers and/or timeouts modified
Mon Sep 16 11:21:17 2019 OPTIONS IMPORT: explicit notify parm(s) modified
Mon Sep 16 11:21:17 2019 OPTIONS IMPORT: compression parms modified
Mon Sep 16 11:21:17 2019 OPTIONS IMPORT: --sndbuf/--rcvbuf options modified
Mon Sep 16 11:21:17 2019 Socket Buffers: R=[212992->425984] S=[212992->425984]
Mon Sep 16 11:21:17 2019 OPTIONS IMPORT: --ifconfig/up options modified
Mon Sep 16 11:21:17 2019 OPTIONS IMPORT: route options modified
Mon Sep 16 11:21:17 2019 OPTIONS IMPORT: route-related options modified
Mon Sep 16 11:21:17 2019 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
Mon Sep 16 11:21:17 2019 OPTIONS IMPORT: peer-id set
Mon Sep 16 11:21:17 2019 OPTIONS IMPORT: adjusting link_mtu to 1625
Mon Sep 16 11:21:17 2019 OPTIONS IMPORT: data channel crypto options modified
Mon Sep 16 11:21:17 2019 Data Channel: using negotiated cipher 'AES-256-GCM'
Mon Sep 16 11:21:17 2019 NCP: overriding user-set keysize with default
Mon Sep 16 11:21:17 2019 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Mon Sep 16 11:21:17 2019 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Mon Sep 16 11:21:17 2019 ROUTE_GATEWAY 172.24.0.1/255.255.0.0 IFACE=eth0 HWADDR=02:42:ac:18:00:06
Mon Sep 16 11:21:17 2019 TUN/TAP device tun0 opened
Mon Sep 16 11:21:17 2019 TUN/TAP TX queue length set to 100
Mon Sep 16 11:21:17 2019 /sbin/ip link set dev tun0 up mtu 1500
Mon Sep 16 11:21:17 2019 /sbin/ip addr add dev tun0 172.21.22.213/23 broadcast 172.21.23.255
Mon Sep 16 11:21:17 2019 /etc/openvpn/tunnelUp.sh tun0 1500 1553 172.21.22.213 255.255.254.0 init
Up script executed with tun0 1500 1553 172.21.22.213 255.255.254.0 init
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 172.21.22.213
Generating transmission settings.json from env variables
sed'ing True to true
Enforcing ownership on transmission config directories
Applying permissions to transmission config directories
Setting owner for transmission paths to 1000:997
Setting permission for files (644) and directories (755)

-------------------------------------
Transmission will run as
-------------------------------------
User name:   abc
User uid:    1000
User gid:    997
-------------------------------------

STARTING TRANSMISSION
NO PORT UPDATER FOR THIS PROVIDER
Transmission startup script complete.
Mon Sep 16 11:21:17 2019 /sbin/ip route add 216.151.191.12/32 via 172.24.0.1
Mon Sep 16 11:21:17 2019 /sbin/ip route add 0.0.0.0/1 via 172.21.22.1
Mon Sep 16 11:21:17 2019 /sbin/ip route add 128.0.0.0/1 via 172.21.22.1
Mon Sep 16 11:21:17 2019 Initialization Sequence Completed
```

**Transmission logs**

```
[2019-09-16 11:21:18.478] Transmission 2.94 (d8e60ee44f) started (session.c:740)
[2019-09-16 11:21:18.479] RPC Server Adding address to whitelist: 127.0.0.1 (rpc-server.c:971)
[2019-09-16 11:21:18.479] RPC Server Adding address to whitelist: 192.168.*.* (rpc-server.c:971)
[2019-09-16 11:21:18.479] RPC Server Adding address to whitelist: 127.0.0.1 (rpc-server.c:971)
[2019-09-16 11:21:18.479] RPC Server Serving RPC and Web requests on port 127.0.0.1:9091/transmission/ (rpc-server.c:1213)
[2019-09-16 11:21:18.479] RPC Server Password required (rpc-server.c:1220)
[2019-09-16 11:21:18.479] Port Forwarding Stopped (port-forwarding.c:180)
[2019-09-16 11:21:18.479] UDP Failed to set receive buffer: requested 4194304, got 425984 (tr-udp.c:84)
[2019-09-16 11:21:18.479] UDP Please add the line "net.core.rmem_max = 4194304" to /etc/sysctl.conf (tr-udp.c:89)
[2019-09-16 11:21:18.479] UDP Failed to set send buffer: requested 1048576, got 425984 (tr-udp.c:95)
[2019-09-16 11:21:18.479] UDP Please add the line "net.core.wmem_max = 1048576" to /etc/sysctl.conf (tr-udp.c:100)
[2019-09-16 11:21:18.479] DHT Reusing old id (tr-dht.c:307)
[2019-09-16 11:21:18.479] DHT Bootstrapping from 87 IPv4 nodes (tr-dht.c:156)
[2019-09-16 11:21:18.479] Using settings from "/data/transmission-home" (daemon.c:528)
[2019-09-16 11:21:18.479] Saved "/data/transmission-home/settings.json" (variant.c:1266)
[2019-09-16 11:21:18.479] transmission-daemon requiring authentication (daemon.c:554)
[2019-09-16 11:21:18.479] Watching "/data/watch" for new .torrent files (daemon.c:573)
[2019-09-16 11:21:18.479] Loaded 1 torrents (session.c:2034)
[2019-09-16 11:21:35.479] LinuxISO Starting IPv4 DHT announce (poor, 9 nodes) (tr-dht.c:577)
[2019-09-16 11:21:42.478] Searching for web interface file "/config/.local/share/transmission/web/index.html" (platform.c:430)
[2019-09-16 11:21:42.478] Searching for web interface file "/usr/share/transmission/web/index.html" (platform.c:430)
[2019-09-16 11:21:49.479] LinuxISO Removing torrent (torrent.c:1915)
[2019-09-16 11:21:49.479] LinuxISO Pausing (torrent.c:1856)
```

**Host system:**

**OS**: Debian Buster 10.1
**Docker**: Docker version 19.03.2, build 6a30dfc
