### ISSUE TITLE
Can't get this to work with Traefik

### ISSUE THREAD

**Issue by mdrichardson** [haugene/docker-transmission-openvpn#904]
**Describe the problem**
I've tried just about every combination of settings and get one of two errors:

* Bad Gateway
* Too Many Redirects

Here's my current settings (they've changed A LOT while troubleshooting this:

**docker-compose**

```
version: "3.7"
services:
  traefik:
    image: traefik:latest
    container_name: traefik
    command:
      - --configFile=etc/traefik.toml
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./traefik/traefik.toml:/etc/traefik.toml
      - letsencrypt:/letsencrypt/
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)
      - traefik.http.routers.http-catchall.entrypoints=web,websecure
      - traefik.http.routers.http-catchall.middlewares=redirect-to-https@docker
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.traefik.tls.certresolver=letsencrypt
      - traefik.http.routers.traefik.rule=Host(`traefik.********)
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.middlewares=auth
      - traefik.http.middlewares.auth.basicauth.users=${BasicAuth}
    restart: always

  transmission:
    container_name: transmission
    image: haugene/transmission-openvpn:latest
    ports:
      - 9091:9091
    environment:
      - CREATE_TUN_DEVICE=true
      - OPENVPN_PROVIDER=${OpenVpnProvider}
      - OPENVPN_CONFIG=${OpenVpnConfig}
      - OPENVPN_USERNAME=${OpenVpnUser}
      - OPENVPN_PASSWORD=${OpenVpnPassword}
      - WEBPROXY_ENABLED=true
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60 --pull-filter ignore ping
      - HEATH_CHECK_HOST=google.com
      # - LOCAL_NETWORK=192.168.1.0/24
    cap_add:
      - NET_ADMIN
    volumes:
      - ./transmission:/data
    healthcheck:
      test: ping -w 8 -n -c 1 8.8.8.8 || exit 1
      interval: 1s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.transmission.tls.certresolver=letsencrypt
      - traefik.http.routers.transmission.rule=Host(`transmission.**********`)
    networks:
      - web
    depends_on:
      - traefik

networks:
  web:
    name: web
    external: true

volumes:
  letsencrypt:
```

**traefik.toml**

```
[global]
  checkNewVersion = true
  sendAnonymousUsage = false

[entryPoints]
  [entryPoints.web]
    address = ":80"
  
  [entryPoints.websecure]
    address = ":443"

[log]
  level = "DEBUG"

[api]
  dashboard = true
  insecure = false
  debug = true

[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  defaultRule = "Host(`{{ normalize .Name }}.**********`)"
  exposedByDefault = false
  watch = true
  network = "web"
  #useBindPortIP = true

[certificatesResolvers.letsencrypt.acme]
  email = "*************"
  storage = "/letsencrypt/acme.json"
  [certificatesResolvers.letsencrypt.acme.httpChallenge]
    # used during the challenge
    entryPoint = "web"
```
**Logs**

**Host system:**
Windows

What am I missing?
