### ISSUE TITLE
Running in kunenetes?

### ISSUE THREAD

**Issue by HippyRock** [haugene/docker-transmission-openvpn#944]
Hi, I'm trying to run in kubernetes, pod is running and transmission seams to be funtional (exec inside pod)
```
curl localhost:9091
<h1>401: Unauthorized</h1>Unauthorized User

netstat -ntlp | grep LISTEN
tcp        0      0 10.0.0.37:51413         0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:9091            0.0.0.0:*               LISTEN      -
tcp6       0      0 :::51413                :::*                    LISTEN      -
```

But, I'm having troubles accessing WebUI from outside pod, from my local network.

Transmission logs:
```
[2019-11-03 08:40:32.067] Transmission 2.94 (d8e60ee44f) started (session.c:740)
[2019-11-03 08:40:32.067] RPC Server Adding address to whitelist: * (rpc-server.c:971)
[2019-11-03 08:40:32.067] RPC Server Adding address to whitelist: 127.0.0.1 (rpc-server.c:971)
[2019-11-03 08:40:32.067] RPC Server Adding address to whitelist: 192.168.1.* (rpc-server.c:971)
[2019-11-03 08:40:32.067] RPC Server Serving RPC and Web requests on port 127.0.0.1:9091/transmission/ (rpc-server.c:1213)
[2019-11-03 08:40:32.067] RPC Server Password required (rpc-server.c:1220)
[2019-11-03 08:40:32.067] Port Forwarding Stopped (port-forwarding.c:180)
[2019-11-03 08:40:32.067] DHT Generating new id (tr-dht.c:311)
[2019-11-03 08:40:32.067] Using settings from "/transmissionvpn" (daemon.c:528)
[2019-11-03 08:40:32.067] Saved "/transmissionvpn/settings.json" (variant.c:1266)
[2019-11-03 08:40:32.067] transmission-daemon requiring authentication (daemon.c:554)
[2019-11-03 08:40:32.067] Watching "/data/watch" for new .torrent files (daemon.c:573)
[2019-11-03 08:40:59.063] DHT Attempting bootstrap from dht.transmissionbt.com (tr-dht.c:249)
```

Pod logs:
```
Using OpenVPN provider: TRUSTZONE
Starting OpenVPN using config Canada-Quebec.ovpn
Setting OPENVPN credentials...
adding route to local network 192.168.1.0/24 via 169.254.1.1 dev eth0
Sun Nov  3 08:40:18 2019 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 19 2019
Sun Nov  3 08:40:18 2019 library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08
Sun Nov  3 08:40:18 2019 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Sun Nov  3 08:40:18 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]158.69.246.171:443
Sun Nov  3 08:40:18 2019 Socket Buffers: R=[212992->212992] S=[212992->212992]
Sun Nov  3 08:40:18 2019 UDP link local: (not bound)
Sun Nov  3 08:40:18 2019 UDP link remote: [AF_INET]158.69.246.171:443
Sun Nov  3 08:40:18 2019 TLS: Initial packet from [AF_INET]158.69.246.171:443, sid=21f77663 d02113f5
Sun Nov  3 08:40:18 2019 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Sun Nov  3 08:40:18 2019 VERIFY OK: depth=2, C=US, O=DigiCert Inc, OU=www.digicert.com, CN=DigiCert Global Root CA
Sun Nov  3 08:40:18 2019 VERIFY OK: depth=1, C=US, O=DigiCert Inc, CN=DigiCert SHA2 Secure Server CA
Sun Nov  3 08:40:18 2019 VERIFY X509NAME OK: C=SC, ST=Mahe Island, L=Victoria, O=Internet Privacy Ltd, OU=trust.zone, CN=*.trust.zone
Sun Nov  3 08:40:18 2019 VERIFY OK: depth=0, C=SC, ST=Mahe Island, L=Victoria, O=Internet Privacy Ltd, OU=trust.zone, CN=*.trust.zone
Sun Nov  3 08:40:18 2019 Control Channel: TLSv1.2, cipher TLSv1/SSLv3 ECDHE-RSA-AES256-GCM-SHA384, 2048 bit RSA
Sun Nov  3 08:40:18 2019 [*.trust.zone] Peer Connection Initiated with [AF_INET]158.69.246.171:443
Sun Nov  3 08:40:20 2019 SENT CONTROL [*.trust.zone]: 'PUSH_REQUEST' (status=1)
Sun Nov  3 08:40:25 2019 SENT CONTROL [*.trust.zone]: 'PUSH_REQUEST' (status=1)
Sun Nov  3 08:40:30 2019 SENT CONTROL [*.trust.zone]: 'PUSH_REQUEST' (status=1)
Sun Nov  3 08:40:30 2019 PUSH: Received control message: 'PUSH_REPLY,ping 3,ping-restart 10,ifconfig 10.0.0.77 10.0.0.78,route 10.0.0.0 255.255.0.0 10.0.0.78 1,dhcp-option DNS 8.8.8.8,dhcp-option DNS 8.8.4.4,route-gateway 10.0.0.78,redirect-gateway def1'
Sun Nov  3 08:40:30 2019 OPTIONS IMPORT: timers and/or timeouts modified
Sun Nov  3 08:40:30 2019 OPTIONS IMPORT: --ifconfig/up options modified
Sun Nov  3 08:40:30 2019 OPTIONS IMPORT: route options modified
Sun Nov  3 08:40:30 2019 OPTIONS IMPORT: route-related options modified
Sun Nov  3 08:40:30 2019 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
Sun Nov  3 08:40:30 2019 Outgoing Data Channel: Cipher 'AES-256-CBC' initialized with 256 bit key
Sun Nov  3 08:40:30 2019 Outgoing Data Channel: Using 512 bit message hash 'SHA512' for HMAC authentication
Sun Nov  3 08:40:30 2019 Incoming Data Channel: Cipher 'AES-256-CBC' initialized with 256 bit key
Sun Nov  3 08:40:30 2019 Incoming Data Channel: Using 512 bit message hash 'SHA512' for HMAC authentication
Sun Nov  3 08:40:30 2019 ROUTE_GATEWAY 169.254.1.1
Sun Nov  3 08:40:30 2019 TUN/TAP device tun0 opened
Sun Nov  3 08:40:30 2019 TUN/TAP TX queue length set to 100
Sun Nov  3 08:40:30 2019 /sbin/ip link set dev tun0 up mtu 1500
Sun Nov  3 08:40:30 2019 /sbin/ip addr add dev tun0 local 10.0.0.77 peer 10.0.0.78
Sun Nov  3 08:40:30 2019 /etc/openvpn/tunnelUp.sh tun0 1500 1601 10.0.0.77 10.0.0.78 init
Up script executed with tun0 1500 1601 10.0.0.77 10.0.0.78 init
Updating TRANSMISSION_BIND_ADDRESS_IPV4 to the ip of tun0 : 10.0.0.77
Generating transmission settings.json from env variables
sed'ing True to true
Enforcing ownership on transmission config directories
Applying permissions to transmission config directories
Setting owner for transmission paths to 1020:1020
Setting permission for files (644) and directories (755)

-------------------------------------
Transmission will run as
-------------------------------------
User name:   abc
User uid:    1020
User gid:    1020
-------------------------------------

STARTING TRANSMISSION
NO PORT UPDATER FOR THIS PROVIDER
Transmission startup script complete.
Sun Nov  3 08:40:30 2019 /sbin/ip route add 158.69.246.171/32 via 169.254.1.1
Sun Nov  3 08:40:30 2019 /sbin/ip route add 0.0.0.0/1 via 10.0.0.78
Sun Nov  3 08:40:30 2019 /sbin/ip route add 128.0.0.0/1 via 10.0.0.78
Sun Nov  3 08:40:30 2019 /sbin/ip route add 10.0.0.0/16 metric 1 via 10.0.0.78
Sun Nov  3 08:40:30 2019 Initialization Sequence Completed
Sun Nov  3 08:40:30 2019 PUSH: Received control message: 'PUSH_REPLY,ping 3,ping-restart 10,ifconfig 10.0.0.77 10.0.0.78,route 10.0.0.0 255.255.0.0 10.0.0.78 1,dhcp-option DNS 8.8.8.8,dhcp-option DNS 8.8.4.4,route-gateway 10.0.0.78,redirect-gateway def'
Sun Nov  3 08:40:30 2019 Options error: unknown --redirect-gateway flag: def
Sun Nov  3 09:40:18 2019 TLS: soft reset sec=0 bytes=474895/-1 pkts=3243/0
……….
```

Configurations:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: transmission-openvpn-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: transmission-openvpn
    spec:
      terminationGracePeriodSeconds: 10
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 8.8.4.4
      containers:
      - image: haugene/transmission-openvpn
        name: transmission-openvpn
        securityContext:
          capabilities:
            add:
              - NET_ADMIN        
        ports:
        - containerPort: 9091
        env:
        - name: PUID
          value: "1020"
        - name: PGID
          value: "1020"          
        - name: CREATE_TUN_DEVICE
          value: "true"
        - name: OPENVPN_PROVIDER
          value: "TRUSTZONE"
        - name: OPENVPN_USERNAME
          value: "foo"
        - name: OPENVPN_PASSWORD
          value: "foo"
        - name: WEBPROXY_ENABLED
          value: "false"
        - name: WEBPROXY_PORT
          value: "8888"
        - name: OPENVPN_CONFIG
          value: "Canada-Quebec"
        - name: LOCAL_NETWORK
          value: "192.168.1.0/24"
        - name: TRANSMISSION_HOME
          value: "/transmissionvpn"
        - name: TRANSMISSION_RPC_WHITELIST
          value: "127.0.0.1,192.168.1.*"
        - name: "TRANSMISSION_RPC_WHITELIST_ENABLED"
          value: "false"
        - name: TRANSMISSION_RPC_HOST_WHITELIST
          value: "*"
        - name: TRANSMISSION_RPC_HOST_WHITELIST_ENABLED
          value: "false"
        - name: TRANSMISSION_RPC_AUTHENTICATION_REQUIRED
          value: "true"
        - name: TRANSMISSION_RPC_USERNAME
          value: "foo"
        - name: TRANSMISSION_RPC_PASSWORD
          value: "foo"
        - name: OPENVPN_OPTS
          value: "--inactive 3600 --ping 10 --ping-exit 60 --mssfix 1500"
        volumeMounts:
        - name: config
          mountPath: /transmissionvpn        
        - name: localtime
          readOnly: true
          mountPath: /etc/localtime
        - name: downloads
          mountPath: /data
        resources: {}          
      restartPolicy: Always
      volumes:
…       
---
apiVersion: v1
kind: Service
metadata:
  name: transmission-openvpn-deployment
spec:
  type: NodePort
  ports:
  - protocol: TCP
    name: "transmission-openvpn-web-ui"
    port: 9091
    targetPort: 9091
    nodePort: 30011
  - protocol: TCP
    name: "transmission-openvpn-proxy"
    port: 8888
    targetPort: 8888
    nodePort: 30012
  selector:
    app: transmission-openvpn

```

Any ideas? Having regular transmission running in another pod just fine with similar port mapping configurations. Thanks!

**Comment by HippyRock** [comment]
Hmmm it turned out that I can access WebUI, but only directly from Node's IP address from where Pod is running. I still don't know why this happens specifically for this Pod tho...

**Comment by haugene** [comment]
I don't know exactly what's going on here, but I have a feeling.

If you try to access the Kubernetes service from one of the other Nodes in the cluster then that would forward the traffic to the node/pod with transmission-openvpn. Could there be a NAT-layer here that makes the traffic hitting the pod have another remote IP? The pod and services subnetworks in kubernetes are different from your 192.168.1.0/24 local network cidr and then the return traffic could be routed through VPN.

You could try to add service subnet and/or pod subnet to the LOCAL_NETWORK. Just be careful as the LOCAL_NETWORK addresses in principle is a "hole" in the VPN tunnel - where all traffic bound for these IPs are routed outside the tunnel. If egress traffic from the pod somehow is NATed as well and is in the same subnet range, then all traffic can suddenly escape the VPN.

Hope that makes sense, and that I'm on the trail of something. It's a bit outside the scope of an issue here, so we can keep this closed. But I'm curious to hear your solution when you find it. Others will probably also encounter this :)

**Comment by HippyRock** [comment]
@haugene you are right. Using service with type: NodePort in kubenetes cluster hides source IP address if request comes to the Node where Pods is missing (request gets routed to the other node and source IP gets replaced with with Nodes IP). After I added internal subnet into LOCAL_NETWORK transmission got available on all cluster nodes. Thank you for a nice hint!

**Comment by lando1577** [comment]
Has anyone running this configuration had an issue with the container not restarting after a VPN connection drop? The WebUI works just fine, but torrents stop. I keep having to manually restart the deployment and then it's fine for like a day.

**Comment by JoooostB** [comment]
@lando1577 I was experiencing the same issue, but managed to automatically restart the pod on VPN-failure using a `livenessProbe` that pings [google.com](https://google.com) using the `tun0` interface:
```yaml
livenessProbe:
    exec:
      command: ["ping", "-I", "tun0", "-c", "1", "google.com"]
    failureThreshold: 3
    initialDelaySeconds: 10
    periodSeconds: 10
    successThreshold: 1
```
