### ISSUE TITLE
High Ram Usage

### ISSUE THREAD

**Issue by WouterJN** [haugene/docker-transmission-openvpn#955]
**Describe the problem**

Package is using a lot of RAM. At the moment 7.42gb while only uploading two torrents.

**Add your docker run command**

```
 transmission:
    image: haugene/transmission-openvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: always
    ports:
      - "9091:9091"
      - "8888:8888"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./transmission-openvpn/:/data
      - /volume1/Downloads/:/downloads
      - ./transmission-openvpn/resolv.conf:/etc/resolv.conf
    environment:
      - OPENVPN_PROVIDER=NEWSHOSTING
      - OPENVPN_USERNAME=secret@newshosting
      - OPENVPN_PASSWORD=secret
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=192.168.2.0/24
      - TRANSMISSION_DOWNLOAD_DIR=/downloads/
      - TRANSMISSION_INCOMPLETE_DIR=/downloads/incomplete
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      - TRANSMISSION_RPC_PASSWORD=secret
      - TRANSMISSION_RPC_USERNAME=secret
```

**Host system:**

Docker Compose on a Synology NAS.
