### ISSUE TITLE
Could someone share a working docker compose setup and its proxy is working?

### ISSUE THREAD

**Issue by orange888** [haugene/docker-transmission-openvpn#973]
I have the following compose file, 

```
version: '2'
services:
 transmission:
  image: haugene/transmission-openvpn
  cap_add:
    - NET_ADMIN
  devices:
    - /dev/net/tun
  restart: always
  ports:
    - "127.0.0.1:9091:9091"
    - "8888:8888"
  dns:
    - 1.1.1.1
  #sysctls:
  #  - net.ipv6.conf.all.disable_ipv6=1
  volumes:
    - /etc/localtime:/etc/localtime:ro
  environment:
    - OPENVPN_PROVIDER=xx
    - OPENVPN_CONFIG=xx
    - OPENVPN_USERNAME=xx
    - OPENVPN_PASSWORD=xx
    - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
    - LOCAL_NETWORK=192.168.0.0/24
    - WEBPROXY_ENABLED=true

```

but when I tried: 
```
curl -x http://VPS_IP:8888 -H -L http://google.com
```

It got stuck there. It does not work, any idea? Thanks.
